### ISSUE TITLE
Adding multiple sectors duplicates stakeholder name in list view

### ISSUE THREAD

**Issue by esinn** [mercycorps/TolaActivity#10]
When adding multiple sectors to one stakeholder and I click save, the stakeholder is listed separately for each sector added. In this case I added three sectors and it was listed three times. https://tola-activity.mercycorps.org/workflow/stakeholder_list/0/0/  See test stakeholder in image below. 

![image](https://user-images.githubusercontent.com/13574772/33621289-17da6690-d99f-11e7-90b6-b828021b28dd.png)

**Comment by jennyhavah** [comment]
No longer developing Workflow.
