### ISSUE TITLE
Save changes and Cancel buttons don't reflect selected language

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1003]
Even after multiple refreshes, the button language doesn't change to reflect the language that was selected by the user.  The rest of the profile page gets translated fine.

![screen shot 2018-12-27 at 10 58 18 am](https://user-images.githubusercontent.com/6685499/50491282-5d991980-09c6-11e9-8ebf-fdb0ba3a2d99.png)

**Comment by camgnostic** [comment]
Addressed this in commit 74aba96a1552c5e3639863265734322c3619b17f

**Comment by RickieT** [comment]
**Validation Complete**
* Issue no longer persists as written. Changed to all languages, and refreshed page, and saved changes - languages remain according to set language on buttons
