### ISSUE TITLE
Program page: Add details about target periods completed to date to clarify "on track" calculations

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1004]
**Note:** Separate ticket covers similar improvements to the home page: #1005

# Issue
It's not emphasized enough that the "on track" metrics only include target periods completed to date. Simply stating that fact is not adequate, due to the variability of target frequencies, the inclusion of frequencies that are not time aware, and so on. 

**Proposed solutions:** Emphasize the "target periods completed to date" element in the title immediately above the "on track" metrics, and include a tool-tip that not only explains, but provides program-specific context -- when the last target period was completed, for each time-aware target frequency used.

![image](https://user-images.githubusercontent.com/33670923/50492750-55dd7300-09ce-11e9-8e4b-0ad9eab7955f.png)

# Acceptance criteria

## Static text
- [x] 1. In the chart area, append to the title **Program metrics** the string "for target periods completed to date" in non-bold text
- [x] 2. At the end of the string is a question mark icon
- [x] 3. Clicking the icon produces a tool-tip. 
     - [x] 3.1. Introductory sentence: Only completed target periods are included in the “Indicators on track” calculations.
     - [x] 3.2. Paragraph at the bottom of the tooltip: If an indicator only has a Life of Program (LoP) target, we calculate performance after the program end date.  For midline/endline and event-based target periods, we begin tracking performance as soon as the first result is submitted.

## Variable text
Under a bold header "Last completed target period", we display the following:
- [ ] 1. Time-aware target frequencies _except for LoP-only_
- [ ] 2. Each frequency is followed by the end date of the last completed target period in localized date format. The following examples are from QA Program - Jenny:
        Annual: May 31, 2018
        Semi-annual: Nov 30, 2018
        Tri-annual: Sep 30, 2018
        Quarterly: Nov 30, 2018
        Monthly: Dec 31, 2018
- [ ] When a program uses no time-aware target frequencies: Hide the entire "Last completed target period" chunk so that there's only the introductory sentence, followed by a paragraph break, then the "If an indicator only..." paragraph.
- [ ] When a program does not have any targets set up: Ditto.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
> 1. In the chart area, append to the title Program metrics the string "for target periods completed to date" in non-bold text

Currently it says "so far" instead of "to date".  I intentionally used "to date" thinking it'd be easier to translate and more accessible to ESL users. (Validated this with LJ who is fluent in Spanish.)

**Comment by RickieT** [comment]
See @jennyhavah 's comments for Failure reason:
