### ISSUE TITLE
Home page: Add details about target periods completed to date to clarify "on track" calculations

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1005]
**Note:** Separate ticket covers similar improvements to the program page: #1004

# Issue
It's not emphasized enough that the "on track" metrics only include target periods completed to date. Simply stating that fact is not adequate, due to the variability of target frequencies, the inclusion of frequencies that are not time aware, and so on. 

**Proposed solutions:** Emphasize the "target periods completed to date" element in the title immediately above the "on track" metrics, and include a tool-tip that not only explains, but provides program-specific context -- when the last target period was completed, for each time-aware target frequency used.

![image](https://user-images.githubusercontent.com/33670923/50492959-62ae9680-09cf-11e9-9dfa-fc9b0df57e09.png)

# Acceptance criteria

## Static text
- [x] 1. Above the charts in each program "blob", is a new header that mimics the one on the program page -- with font scaled down so it doesn't dominate the page: **Program metrics:** for target periods completed to date
- [x] 2. At the end of the string is a question mark icon
- [x] 3. Clicking the icon produces a tool-tip. 
     - [x] 3.1. Introductory sentence: Only completed target periods are included in the “Indicators on track” calculations.
     - [x] 3.2. Paragraph at the bottom of the tooltip: If an indicator only has a Life of Program (LoP) target, we calculate performance after the program end date.  For midline/endline and event-based target periods, we begin tracking performance as soon as the first result is submitted.

## Variable text
Under a bold header "Last completed target period", we display the following:
- [x] 1. Time-aware target frequencies _except for LoP-only_
- [x] 2. Each frequency is followed by the end date of the last completed target period in localized date format. The following examples are from QA Program - Jenny:
        Annual: May 31, 2018
        Semi-annual: Nov 30, 2018
        Tri-annual: Sep 30, 2018
        Quarterly: Nov 30, 2018
        Monthly: Dec 31, 2018
- [x] When a program uses no time-aware target frequencies: Hide the entire "Last completed target period" chunk so that there's only the introductory sentence, followed by a paragraph break, then the "If an indicator only..." paragraph.
- [x] When a program does not have any targets set up: Ditto.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
> 1. Above the charts in each program "blob", is a new header that mimics the one on the program page -- with font scaled down so it doesn't dominate the page: Program metrics: for target periods completed to date

Currently it says "so far" instead of "to date".  I intentionally used "to date" thinking it'd be easier to translate and more accessible to ESL users. (Validated this with LJ who is fluent in Spanish.)

**Comment by RickieT** [comment]
See @jennyhavah 's comments for Failure reason:

**Comment by jennyhavah** [comment]
Check out MRED in Timor Leste -- shouldn't there be a "last target period completed" string in there? This is a situation where there are Annual targets but no results reported. Even so, the annual period is, technically, over. So I'd expect to see this type of string (copied from a different program):

![image](https://user-images.githubusercontent.com/33670923/51148414-f4f9cb80-1812-11e9-9929-408041f2aecf.png)

**Comment by jennyhavah** [comment]
After digging into it a bit more, Paul and I think this issue may have nothing to do with the tool-tip work itself, and may be a manifestation of a different issue. If you go to the IPTT creation page and select the MRED program in the Program menu on the left side, you'll see Annual as a target frequency option. 

![image](https://user-images.githubusercontent.com/33670923/51211801-6eed8b80-18cb-11e9-90e4-fe4e0bee1ca8.png)

That is why I expected to see the last Annual target period completed in the tool tip. However, if you locate the indicator that supposedly has Annual targets, it does not, in fact, have any targets:
![image](https://user-images.githubusercontent.com/33670923/51211922-bd028f00-18cb-11e9-8a23-4aa87335983f.png)

This would explain why I'm not seeing the latest annual period in the tool tip, but... Why am I able to select Annual in the IPTT creation form, and to see an Annual IPTT at all, if there are no indicators with Annual targets? Do we have "ghost targets" in the system? 

@sanjuroj @RickieT Should this become a separate ticket?

**Comment by RickieT** [comment]
@jennyhavah If its not related to the acceptance criteria and expected function of the final design of *this* ticket, then yes from what it looks like, another ticket to address the issue you speak of.

**Comment by sanjuroj** [comment]
Let's put it on ghost pepper.  We'll need to update some other translations for ghost pepper as well, I think.

**Comment by jennyhavah** [comment]
> Which wording change? "so far" to "to date" in the program blob?

Yes

**Comment by RickieT** [comment]
Closing as fixed/deployed

**Comment by jennyhavah** [comment]
This work is done.
