### ISSUE TITLE
Program page: Highlight the specific %Met calculations relevant to "on track" chart

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1006]
# Issue
Users are experiencing confusion about our "on track" metrics and how they relate (or don't) to the %Met calculations displayed in the results table. As a result, we're getting reports of calculation errors when the queries are, in fact, behaving as expected. 

The proposed solutions use a combination of strategically timed visual highlights of %Met results (covered in this ticket) and context-specific tool-tips to clearly communicate these relationships, covered in #1007. 

# Acceptance criteria

## Indicators with time-aware target frequencies
- [x] 1. When a target period is incomplete, % Met for that period has no highlighting. This is true _regardless of whether or not any results are reported._ (This is because we only want highlighting of results used in "on track" calculations.)
- [x] 2. Until the program end date has passed (meaning all target periods are complete), the % Met for the total Life of Program to date has no highlighting. 
- [x] 3. For any **_completed_** _intermediate target periods_, the following are true:
     - [x] 3.1. When the actual value is **not on track** (more than 15% above or below the target value), the %Met result is highlighted in pale yellow.
     - [x] 3.2. When the actual value is **on track** (within the band of 15% above or below the target value), the %Met result is highlighted in pale green.

![image](https://user-images.githubusercontent.com/33670923/50494951-1ff2bb80-09db-11e9-8318-c6689e015fb6.png)

## Indicators with LoP only target frequency
- [x] 1. Until the program end date has passed, there is no highlighting of any %Met results, regardless of whether or not any results are reported.
- [x] 2. After the program end date has passed, the %Met value is highlighted in yellow or green in two places:
     - [x] 2.1. The Life of Program target period row
     - [x] 2.2. The Life of Program summary row

## Midline/endline and Event target frequency
- [x] 1. As soon as a result is associated with a midline or endline period, the %Met for that period is highlighted in yellow or green, to reflect the fact that we immediately include them in "on track" calculations.
- [x] 2. Until the program end date has passed, there is no highlighting of the Life of Program %Met result. 

![image](https://user-images.githubusercontent.com/33670923/50494765-14eb5b80-09da-11e9-9431-6c4df43ab099.png)

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by axoplasm** [comment]
There are several edges we need to capture in display of individual values (here and on IPTT):

* No results data or target value (`NoneType`, `None`, or `Null` [these might be different]) : print `—`
* results data or target value = `0` : print `0`
* `x/0` or `x/None` where `x ≠ 0`: print `N/A`
* `0/x` where `x ≠ 0` : print `0`
* `0/0` : print `0` (?)

**Comment by axoplasm** [comment]
Per Jenny:

> 1. For Actual, if there is no data, we use --
> 2. For %Met, if there is no data, we use --   (not % or empty or --%)
> 3. EXCEPTION: When Target = 0, %Met always says N/A regardless of what's in the Actual column.

**Comment by axoplasm** [comment]
OK this is easier than I thought:
``` pseudocode
if _value_ is a valid number: # including 0
    print _value_
if _value_ is not a valid number: # div/0, 0/0, None, NoneType, x/None, None/x
    print "N/A" if column is "% Met" else print "—"
```

**Comment by RickieT** [comment]
This looks good to me on qa, moving to ready for deploy

**Comment by jennyhavah** [comment]
I'm not seeing the highlighting on LoP only targets. This is on QA - Jenny

![image](https://user-images.githubusercontent.com/33670923/51770007-6d754d80-2099-11e9-8425-0e9b3573b495.png)

Shouldn't % Met be green?

![image](https://user-images.githubusercontent.com/33670923/51770032-854cd180-2099-11e9-8792-8ee266f3262c.png)

Shouldn't % Met be yellow?

**Comment by axoplasm** [comment]
yes, if the value is included in the on-track gas gauge. (They *should* use the same logic.)

Which program is this?

**Comment by jennyhavah** [comment]
Right after I took off in the air, it occurred to me in a flash, why it's not green: The program isn't over yet. If it's LoP only, it's not included in the gauge until the program is over. 

![image](https://user-images.githubusercontent.com/33670923/51784794-54a18200-2103-11e9-9d3c-616886f6e9a4.png)

This is the QA - Jenny program. 

Seeing as this is not a bug after all, I'm moving it back out of Failed.
