### ISSUE TITLE
Extra rows appear on results table after periodic target deletion.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1009]
There are a couple of issues with target creation:

1. When creating Midline/Endline and Event targets, an extra periodic target is created.
2. Although it looks like the extra Event target can be deleted, it is never actually deleted.

Example for problem 1:
Before saving Midline/Endline Targets:
<img width="603" alt="screen shot 2018-12-28 at 11 11 46 am" src="https://user-images.githubusercontent.com/6685499/50525664-cb5e4780-0a91-11e9-8ee4-6ad379bbb2bd.png">

After saving Midline/Endline Targets:
<img width="599" alt="screen shot 2018-12-28 at 11 12 13 am" src="https://user-images.githubusercontent.com/6685499/50525674-da44fa00-0a91-11e9-9096-8de63d5ffb81.png">

Example for problem 2:
Extra Event target created.
<img width="575" alt="screen shot 2018-12-28 at 11 17 43 am" src="https://user-images.githubusercontent.com/6685499/50525808-ab7b5380-0a92-11e9-8d99-b5c1061178c2.png">

Pressing the red X appears to delete the period (and persists after Save button is pressed):
<img width="581" alt="screen shot 2018-12-28 at 11 17 52 am" src="https://user-images.githubusercontent.com/6685499/50525819-bdf58d00-0a92-11e9-9830-06bbaba68aa5.png">

After closing the modal, the extra period still shows up in the Results table:
<img width="852" alt="screen shot 2018-12-28 at 11 18 14 am" src="https://user-images.githubusercontent.com/6685499/50525838-dd8cb580-0a92-11e9-86af-56d0af05e2aa.png">

Reopening the modal shows that the extra period is still there:
<img width="573" alt="screen shot 2018-12-28 at 11 18 32 am" src="https://user-images.githubusercontent.com/6685499/50525850-eed5c200-0a92-11e9-883f-e1c36f85b6c9.png">

**Comment by hannalcamp** [comment]
I'm getting similar issues in Annual and other time-bound target periods too
![screen shot 2018-12-28 at 12 20 49 pm](https://user-images.githubusercontent.com/38020496/50526016-7ecc3980-0a9c-11e9-882c-9beb9be51e54.png)

**Comment by axoplasm** [comment]
NTS: this is related to issues with #978

**Comment by axoplasm** [comment]
bug here is related to the listener on `.periodic-targets` in `templates/indicators/indicator_form_common_js.html:297` which was appending a dummy `periodic_target` for the summary row (i.e. `forloop.last`) which incorrectly had class `periodic-target`

**Comment by hannalcamp** [comment]
Everything looks good on my end.

**Comment by RickieT** [comment]
Agree, this does not appear to be happening any longer.
