### ISSUE TITLE
Results with evidence rounds to 100%/0% when not actually 100%

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1011]
This is a regression from the move to React - logic in the templatetag edition of gaugeband/gaugetank wasn't copied to the JS react calculations.  Can be repeated by removing a single piece of evidence from a single result on the QA-Jenny program.  Gauge shows 100% despite having 1 element on the filter (when clicking the "0%" an item is displayed)

**Comment by camgnostic** [comment]
Addressed in PR #1012, test conditions mentioned above

**Comment by jennyhavah** [comment]
@camgnostic Does this ticket cover the rounding issue in the other direction as well -- 0%/100%? I recall Hanna finding an example where the gauge would show 0% despite there being one indicator that should have bumped it to 1%.

**Comment by jennyhavah** [comment]
# Evidence gauge
I tested removing a single piece of evidence from QA Program - Emily (that had 100% evidence) and got a 1% with evidence gauge as expected. 

I also tried adding one piece of evidence to the QA Program -- No Evidence here program, and got a "99% no evidence" gauge, as expected.

# Results gauge
Tried the same tests with Results gauge -- adding a result to a no-results program and removing a result from a 100% results program, worked as expected.

**Comment by jennyhavah** [comment]
@camgnostic 

Check out this program: https://tola-activity-demo.mercycorps.org/program/547/0/0/

I just added targets to the one indicator in there, and would expect the "indicator with targets" gauge to be 100%.

**Comment by jennyhavah** [comment]
Also, this may be -- at least in part -- a QA script issue, but on the "No targets here" program, all the LoP indicators have targets, and yet the "Indicators with targets" gauge is at 0%

https://tola-activity-demo.mercycorps.org/program/601/0/0/
