### ISSUE TITLE
help text on "are on track" metric is incomplete

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1020]
The "are on track" help text is missing a link to a google doc.  On production (pre-React), the link is in the code but isn't appearing on the page.  The React page has a version of the text without the link.  

It's not clear if that text is still desired or if it was cut out.  If it is desired, it is curious that it's not being rendered, even though it's in the code.  Creating this issue so the text can be followed up on.

The code in question is
`<a href='https://docs.google.com/document/d/1Gl9bxJJ6hdhCXeoOCoR1mnVKZa2FlEOhaJcjexiHzY0' target='_blank'>See our documentation for more information.</a>"`

The full code snippet is `data-content="{% trans "The actual value matches the target value, plus or minus 15%. So if your target is 100 and your result is 110, the indicator is 10% above target and on track.  <br><br>Please note that if your indicator has a decreasing direction of change, then “above” and “below” are switched. In that case, if your target is 100 and your result is 200, your indicator is 50% below target and not on track.<br><br><a href='https://docs.google.com/document/d/1Gl9bxJJ6hdhCXeoOCoR1mnVKZa2FlEOhaJcjexiHzY0' target='_blank'>See our documentation for more information.</a>" %}"`

**Comment by jennyhavah** [comment]
@sanjuroj We definitely still want to link to the help doc. It was not intentionally removed.

**Comment by RickieT** [comment]
**Validation Complete** 
* It looks like it now still contains what it is supposed to now, and link to the doc listed in the description.
