### ISSUE TITLE
User is not directed to tab with missing required fields If a requirement is not met 

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1022]
**Description:**
As a user, when attempting to save when some required fields are not met, a message appears at the top of the form informing the user they have not completed all required fields in a tab (in this example, targets). 

I would expect the site to tab to open automatically and highlight the field(s) that are missing required input. 

**Steps to Reproduce:** 
1. Login to Tola-Activity
2. Click Testing specific Program "TolaData Test"
3. Click "+ Add Indicator"
4. Add name to Indicator and click "Save Changes"
5. Fill out the required fields on the Summary Tab
6. Click Save Changes

**Results:** 
User is told requirements are missing through an error message at the top of the form. 

**Expected Results:**  
User is told requirements are missing with an error message, and then focused/directed to the form & fields requiring data/input. 

**Attachments:**
![screen shot 2019-01-04 at 9 02 36 am](https://user-images.githubusercontent.com/23220180/50701504-e5a0a400-1002-11e9-92b1-6b99ac40083e.png)

**Comment by jennyhavah** [comment]
As far as I can tell, it's behaving as expected. Here's what I saw when I reproduced the steps:

![image](https://user-images.githubusercontent.com/33670923/50939322-251b2600-1431-11e9-9069-52f9410dd74f.png)

When I go to the Performance tab, I see the incomplete field highlighted as expected:
![image](https://user-images.githubusercontent.com/33670923/50939345-4845d580-1431-11e9-8ca4-70b319955bd4.png)

When I go to the Targets tab, I see the incomplete fields highlighted as expected:
![image](https://user-images.githubusercontent.com/33670923/50939337-3b28e680-1431-11e9-9f96-9bf30c066121.png)

**Comment by RickieT** [comment]
So I think we discussed this ticket when we were planning work for GP, and I think what was decided is that this was functioning as designed. The issue I was seeing here is that I was not being pulled to the tab with the issue, but as discussed, there could be multiple tabs with issues, therefore it wouldnt make sense to have the site direct the user to the tab automatically

**Comment by jennyhavah** [comment]
Thanks for the clarification @RickieT -- going ahead and closing this ticket.
