### ISSUE TITLE
Disaggregation/Indicator Type selector function is confusing

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1023]
**Description:**
On the Performance tab when creating a new or editing an indicator, it is difficult to understand the disaggregation and indicator type fields based on how a selection can be made. 
Though there is no indication that these two options with selections are required, there is no way to DE-select an option once clicked. 

**Steps to Reproduce:**
1. Login to Tola-Activity
2. Click Testing specific Program "TolaData Test"
3. Click "+ Add Indicator"
4. Add name to Indicator and click "Save Changes"
5. Click the performance tab
6. Click/Highlight options under disaggregation & indicator type

**Results:**
Multiple options can be "selected" by clicking and dragging for highlighting. When clicking an option, there is no way to deselect an option. 

**Expected Results:**
If multiple selection is allowed, check box or similar selector is used. If not an optional field/selection, mark properly and block saving as required. 

**Attachments:**
![screen shot 2019-01-04 at 9 22 40 am](https://user-images.githubusercontent.com/23220180/50701337-5abfa980-1002-11e9-9f49-25803aba3f09.png)

**Comment by sanjuroj** [comment]
On a Mac, I can deselect by doing a command-click, but you're right, that's not really intuitive.

**Comment by sanjuroj** [comment]
Let's try a mutliselect widget there instead.

**Comment by KennyMonster** [comment]
I am also:

Using BS multiselect widget on Summary -> Program Objective

Converting Summary -> Country Strategic Objective to use BS multiselect instead of Select2 which is something we are trying to phase out, and also looks terrible with those badges/pills containing long names.

**Comment by jennyhavah** [comment]
@KennyMonster @RickieT I noticed that the Reset function doesn't seem to be working with the new multi-select widgets used for Program Objectives or Country Strategic Objectives.

How easy/hard is this to fix?
