### ISSUE TITLE
After saving a result, the indicator modal should close automatically (Multiple clicks on "save" create multiple result records)

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1025]
**Description:**
After saving a result, the modal should close, and provide a notification of the save, as changes appear on target chart. Additionally, after saving a Result, I was left in the modal the results I had entered. If I clicked save again, this created a NEW result with the same information I had just created, a piggy back sort of off the above issue. Don’t know if this is intended design

**Steps to Reproduce:**
1. Login to Tola-Activity
2. Click Testing specific Program "TolaData Test"
3. Click an indicator on the list
4. Click "+ Add Results"
5. Add information to fields and required fields
6. Click Save Changes

**Results:**
Changes are saved, and result is added. If the user clicks save changes again, a duplicate of the same result is added.

**Expected Results:**
When Result is added, prompt user with successful save message, and close modal. 

**Attachments:**
![screen shot 2019-01-04 at 9 51 50 am](https://user-images.githubusercontent.com/23220180/50702663-6dd47880-1006-11e9-96ab-d57604222684.png)

**Comment by sanjuroj** [comment]
Will fix as part of Huckleberry.

**Comment by RickieT** [comment]
Talked with @sanjuroj, opening & moving to huckleberry for a patch fix post release.

**Comment by RickieT** [comment]
@sanjroj @jennyhavah Closing this, splitting into two tickets

Duplicate saving will go into huckleberry
Global modal closing on save issue, sticking in Satsuma for now
