### ISSUE TITLE
Automate the "junk" query string on static assets

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1035]
Add this to the `npm start` task

Ken suggests hashing the file so users arent constantly reloading static assets

**Testing:**
No test plan necessary for this one. Make sure change doesn't break UI and site loads.

**Comment by KennyMonster** [comment]
Because the webpack based implementation is a major change, it was decided to make this part of huckleberry release.

**Comment by RickieT** [comment]
No test plan necessary for this one.

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Site does not break and UI loads
