### ISSUE TITLE
Indicator help link does not open tab with tola wiki, opens old form

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1038]
**Description:**
"help" link on indicator setup form should be linking to the Tola Design Wiki, but currently links an outdated form. 

Please see attached image. 

**Steps to Reproduce:**
1. Login to Tola-Activity
2. Select Tola-Data Test program
3. Edit an indicator (click gear icon) 
4. Click Help link on form

**Results:**
Link opens out of date google doc form

**Expected Results:**
Link opens new tab to Tola-Wiki

**Attachments:**

![image](https://user-images.githubusercontent.com/23220180/50857150-a5faf480-1341-11e9-8e1d-06b9444b5312.png)

**Comment by axoplasm** [comment]
Help links are managed in the admin interface at https://tola-activity.mercycorps.org/admin/workflow/formguidance/ . Someone with admin access on production will need to make this change.

**Comment by axoplasm** [comment]
…in other news, I'm taking this opportunity to clean up modal footers, so expect a few screenshots there

**Comment by axoplasm** [comment]
Per convos on Slack, I'm replacing hardlinks to Google Docs. One of these is a link to the contact form on the 403 (access denied) error page. 

This link is apparently defunct (no such form). (This also happens BTW when I click on “Feedback” in the footer)

*Do we have an alternative means of contact for users?* Like an email address?

**Comment by RickieT** [comment]
@axoplasm I am not seeing this link to the wiki, this is still linking to the doc in the qa server, with latest commit deployed.

**Comment by axoplasm** [comment]
@RickieT — The original bug is a content problem. I don't have admin access to the production server so I can't fix it. However I cleaned up some markup and styling related to modal footers and the links therein. 

Someone with (content) admin privileges can fix the wiki link on this page: 
https://tola-activity.mercycorps.org/admin/workflow/formguidance

**Comment by RickieT** [comment]
@axoplasm You're absolutley correct, I totally forgot this was the solution. In which case, you did mention some clean up on footers, is there code attached to this ticket that does not solve the originally listed issue?

**Comment by axoplasm** [comment]
Yes, that's my bad. I forgot to link the PR (#1048) to this ticket
