### ISSUE TITLE
Revert "Records" back to "Documents" in UI

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#1039]
**Story Description:**
As part of Browse Records #150, #823, the term Documents was renamed to Records. Revert these changes so we are no longer using Records as evidence on results.

This change only exists in the `browse_records` branch at the moment. Make this change before merging into `huckleberry`.

-- **Acceptance Criteria:** --
- [ ] The term "Documents" should be in place of any place where "records" would have been initially. ~(Basicly, records should not be a term anywhere in the application or effected forms in huckleberry)~ (see first comment below) 

**Testing:**
- [x] Gloss over huckleberry's effected UI scope and comb for "records" instead of "documents" in those places. 

**Risks: **
* Having the two unintentionally exist (one spot is records, while another is documents) could cause confusion, but at worst is a relatively minor ui fix.

**Estimated Test Time (Acceptance): **
1 - 2 hours

**Comment by jennyhavah** [comment]
Erring on the side of over-communication here... 

For the record (no pun intended), we're not 100% abolishing the term "record" from the entire app. Here's one place where we use the word three times -- within the Result form, Evidence section.

![image](https://user-images.githubusercontent.com/33670923/52735431-80828b80-2f7c-11e9-9bad-90bca316cad0.png)

The goal of this ticket was to revert some work we had begun to replace the term "Document" with "Record". Instead, we're continuing to use the term "Document" for anything related to the Document object.

**Comment by RickieT** [comment]
@jennyhavah Thanks for clarifying, I hopefully assumed this was the case. 
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
* Re-Verifying that there is no incorrect use based on the use of records vs documents from the original scope.
