### ISSUE TITLE
Add URL to Result for evidence and populate field with migration

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#1040]
**Original Story Description:** 
Instead of using a Record/Document or TolaTable link as evidence, we now want to use a URL field directly on the Result model.

There is also an optional name field that needs to be added as well.

The existing evidence FK should not be removed, and instead should be preserved as not to destroy any existing Records or associates to those Records.

The existing TolaTable FK should also not be removed, and should be preserved to allow continued UI access to the TolaTable for migration purposes on the part of the end user.

Create a DB migration to populate the new URL and name field with the contents of a Document that is already associated as evidence on a Result. There will be not migration of data from existing TolaTable links to the new fields.

**Acceptance Criteria:** 
* URL is now an acceptable form of evidence
* Form contains new input field "name" (Optional) 
* Create a migration to populate the new URL and name field with the contents of a Document that is 
already associated as evidence on a Result.
* Existing evidence FK should not be removed, and instead should be preserved as not to destroy any existing Records or associates to those Records.

**Testing:**
- [x] URL Form does not accept strings that are not recognized as a URL
- [x] All required fields remain as required
- [x] No optional fields are required
- [x] No previous evidence is overwritten or removed when submitting URL evidence
- [x] Information submitted is properly stored (Database table check) 
- [x] Validate the function of evidence creation from start to finish of any type remains the same
- [x] Repeat steps in any forms or pages that contain the same form 

**Risks:**
There should be no risks provided the acceptance criteria and testing marks are met.

**Estimated Test Time (Acceptance):**  
1 - 2 hours

**Comment by jennyhavah** [comment]
@KennyMonster @sanjuroj What do we do when a result has both a linked TolaTable AND a linked Document?

First step: Figure out how many of these there are.

**Comment by KennyMonster** [comment]
> First step: Figure out how many of these there are.

There are only 34 results having both a linked TolaTable and also a document. See attached CSV.

[results_with_both_tolatabl_and_document.csv.zip](https://github.com/mercycorps/TolaActivity/files/2746342/results_with_both_tolatabl_and_document.csv.zip)

**Comment by jennyhavah** [comment]
All of the result creation dates are prior to August of 2017. In the case of the Kandahar program, only 1% of indicators have targets set up which means that results are not linked to targets. The results also look old enough that they have no dates associated with them. I think it's fair to assume that these TolaTables are unlikely to be sought out as evidence. Plus, we're pulling the plug on TolaTables entirely in 6 months.

If we want to be SUPER conservative about this, we could include this logic in @KennyMonster 's script:

1. If there is both a Doc and a TolaTable linked to the result, put the URL of the Doc as evidence.
2. Put the URL to the TolaTable in the Comment field -- appended after any other text that is already in there, with a paragraph break in between.

**Comment by KennyMonster** [comment]
As it stands, I believe we display a link to the TolaTable in the evidence column of the results table on the program page. What if we just left the TolaTable link intact and leave the link to it in the evidence column, but otherwise make it un-editable in the results form?

**Comment by jennyhavah** [comment]
@KennyMonster I think it would be acceptable to leave the link in the evidence column of the results table... and nowhere else. (My hope is to remove the TolaTables selector entirely from the Result form, rather than leaving it in there but making it uneditable.)

So this would mean: You see any existing TolaTables links on the program page. You cannot view or edit it on the Result form.

Sound ok?

**Comment by KennyMonster** [comment]
Works for me!

**Comment by KennyMonster** [comment]
@RickieT 

> URL Form does not accept strings that are not recognized as a URL

The URL evidence name is a bit misleading as this field can also hold a path to a file on a network storage device. The new field on the results form should allow this, in the same way that the Documents form allows file paths (but displays a warning if you type one in).

**Comment by esinn** [comment]
@KennyMonster For existing indicator results that had an existing document there were using as evidence, the document name and file path are transposed. For example, see screen shot below - the file path is in the record name and the record name is in the URL. 
![image](https://user-images.githubusercontent.com/13574772/52739612-28e91d80-2f86-11e9-88b5-835b60aa5469.png)

**Comment by esinn** [comment]
Remove comment above, the document has the URL in the  name and the name of the doc in URL. :facepalm:

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Confirmed Acceptance Criteria still met:
* URL is now an acceptable form of evidence
* Form contains new input field "name" (Optional)
* Create a migration to populate the new URL and name field with the contents of a Document that is
  already associated as evidence on a Result.
* Existing evidence FK should not be removed, and instead should be preserved as not to destroy any existing Records or associates to those Records.

**Comment by jennyhavah** [comment]
TolaTable links that we are preserving in the Evidence column are broken. Here are some examples from program 443 on QA

![image](https://user-images.githubusercontent.com/33670923/52765317-71312b80-2fd8-11e9-9e65-861d6cdbb9aa.png)

**Comment by sanjuroj** [comment]
The link that is stored in the database is not a good link to view the data.  For viewing through a link, the stored link can be converted to a viewable link by rewriting a little bit of the URL.  

The way to build it is to concatenate the domain address with "silo_detail/" and <silo number>.  <silo_number> is the last number in the stored link.  The final URL should be something like:  https://tola-tables.mercycorps.org/silo_detail/2701/

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Confirmed Acceptance Criteria still met:
* URL is now an acceptable form of evidence
* Form contains new input field "name" (Optional)
* Create a migration to populate the new URL and name field with the contents of a Document that is
  already associated as evidence on a Result.
* Existing evidence FK should not be removed, and instead should be preserved as not to destroy any existing Records or associates to those Records.
* EXISTING Tola-Tables are working now as described in the comment from @sanjuroj , and the links are no longer broken
