### ISSUE TITLE
Program page sidebar: Remove Documents section and add GAIT link under Program details

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1052]
# Issue summary
With Huckleberry, we are no longer using Documents as evidence, and want to start de-emphasizing this feature set. While we ARE keeping Documents in place for the few teams that still use Projects, these teams are unlikely to access project-related docs from the Program page. They are much more likely to access them directly from the Project forms and dashboards.

We want to remove the Documents section from the Program page sidebar.

On the basic principle of "replace with something more useful when you remove a feature", we'd like to add a link under **Program details** to the program's GAIT page, where a lot of useful documentation is stored.

# Acceptance criteria

## Remove Documents from sidebar
- [x] Remove Documents section from the Program Page sidebar

## When the program has a GAIT ID
- [x] In the Program details section, under "Indicator plan", is a link: "View program in GAIT"
- [x] The link opens the program's GAIT page in a new tab. Here's an example: https://gait.mercycorps.org/editgrant.vm?GrantID=7365

## When the program does NOT have a GAIT ID
- [x] Don't include a GAIT link.

## Minor UI detail
- [x] Please edit the link "Indicator Plan" (title case) to "Indicator plan" (sentence case).

![image](https://user-images.githubusercontent.com/33670923/51512825-c81e5900-1dbc-11e9-8087-a31843ef1c3b.png)

## Housekeeping (where applicable)
- [ ] Unit test/s written
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by esinn** [comment]
This looks good. Nothing to add.

**Comment by sanjuroj** [comment]
Does the term "program documents in GAIT" make sense?  I feel like "View GAIT record" might make more sense.  

And does it make sense to continue to use the word "Documents" for the section title?  What about "Links"?  We've toyed around with the idea of letting them add bookmark like links to the program view.

**Comment by sanjuroj** [comment]
Ah, ok, that makes sense.  Maybe the one thing to mention is that the documents tab is reached by a pretty non-specific anchor tab.  e.g. https://gait.mercycorps.org/editgrant.vm?GrantID=5112#edit_tabs-pane-6.  I'm assuming that "edit_tabs-pane-6" always refers to the "Documents" pane, but we'd need to confirm that.  If the Documents tab can't be consistently accessed, we'll need to link to just the main GAIT record for that grant.

**Comment by jennyhavah** [comment]
@sanjuroj Can you please confirm and let me know? Depending, I'll keep things as is or update the ticket to eliminate the Docs section entirely and put the GAIT link in the Program Details section.

**Comment by sanjuroj** [comment]
@jennyhavah, @esinn  I asked Doug and he said he's never been able to reliably link to a tab.  I did a bit of experimenting and it looks like GAIT does some version of remembering the last tab I was on, because when I switched from one program to another the tab I was on remained constant.  And using the URL param when I was not on the Documents tab didn't result in my going to the Documents tab.

**Comment by jennyhavah** [comment]
So it sounds like we should NOT link to the Docs tab in GAIT, if we can't reliably send users to that specific tab.

So how about this: Remove the Documents section and add a link to Program Details, like so:

![image](https://user-images.githubusercontent.com/33670923/51142722-911ad700-1801-11e9-9e06-243829577c23.png)

@esinn Work for you?

**Comment by jennyhavah** [comment]
Heads up @esinn and @sanjuroj. Ticket updated to remove the Documents section entirely and add the GAIT link when the program has a GAIT ID. (We are no longer attempting to link to the Documents tab specifically, which is why I moved it into the Program details section.)

I updated the corresponding wiki section here: https://learn.mercycorps.org/index.php/TOLA:Huckleberry#Updates_to_the_Program_page_sidebar

**Comment by camgnostic** [comment]
Per Slack:
@me: there are a large number of programs with GAIT ID’s stored as something weird.  The ticket for “view program in GAIT” just says “if it has a GAIT ID, show the URL” but I’m pretty sure that GAIT ID’s like `YES!` and `FY-17` and `DREAMS` aren’t going to work.  Do you want me to check if it’s numeric?  A four-digit number?   I don’t really know the GAIT validation system, and we just let them put anything they want in that field
question put to @esinn and @jennyhavah  - will update this thread with results.  For now validation is for numeric and non-zero (no link displayed if there is a non-numeric or zero-equivalent gait ID)

**Comment by axoplasm** [comment]
I see #1052 is merged already. RN the property `gait_url` is checking for this condition:

```python
# gaitid exists, is numeric, is nonzero, and is a 3 or 4 digit number:
```
I have a couple other ideas/thoughts:
1. `curl` or `wget` `gaitid` & check for a 200-grade response.
1. Similar to 1: validate this on the __frontend__ via JS
1. The production site could ping GAIT privately i.e. entirely on the MC network, without making an HTTP request
2. Doug (or whomever) could write a non-privileged endpoint that returns something other than a 401 error. It wouldn't need to be public. Could it at least return something like "Program exists?"

**Comment by axoplasm** [comment]
It's 200 if you have permissions to GAIT, which I do not & which I assume an anonymous request from Tola (e.g. curl or wget) wouldn't either. I get 401 if I'm already signed in on the SSO.

now that I think about, an anonymous request would be redirected to the SSO, right?

**Comment by RickieT** [comment]
@sanjuroj @axoplasm I'm not seeing this change live on QA where the latest huckleberry is deployed

**Comment by sanjuroj** [comment]
@RickieT Try it on the -qa server now?  I think it should be working.

**Comment by RickieT** [comment]
I'm not seeing the link still :
![image](https://user-images.githubusercontent.com/23220180/52676175-161b0e00-2ede-11e9-8cd6-144ac36b3d6f.png)
