### ISSUE TITLE
Update program queries to use the new definition of "evidence" on results

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#1053]
Once the migration in #1040 is completed, evidence on a result will now be tracked by a URL field on the result model instead of a link to Documentation or TolaTable.

The business rule to answer the question "does this result have evidence?" can be answered with "yes, if the URL field contains a non-empty string". This is a change from the previous rule of "yes, if a link to Documentation OR a link to TolaTable exists".

The DB queries the power the metrics reported on the home and program page will need to be updated to reflect this change.

Unit tests will also be need to be updated.

### Implementation strategy

I'm thinking it may be a good idea to rename the Documentation and TolaTable FK fields on the Result model. This will cause a ton of breakage, but allow us to more easily track down the places that need to be updated in the code.

**Acceptance Criteria:**
- [x] Metrics reported at the top of the program and home page are valid and reflect the current state of the indicators

**Testing:**
- [x] Need to create a Test program, and create multiple indicators with differing values using the URL field. 
- [x] Match values to metrics, values recorded on the new evidence tracking values need to be accurate. Multiple programs tests, indicator types and values will need to be created to ensure this is being tracked properly. 
- [x] Filter works & tracks correctly on the program page when that gauge is clicked

**Estimated Test Time:**  
3 - 4 hours

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: Creating indicators, results, evidence, the gauges and filters react appropriately to what is recorded
![screen shot 2019-02-13 at 2 14 14 pm](https://user-images.githubusercontent.com/23220180/52747865-bbdf8300-2f99-11e9-9933-c86d6ff0e684.png)
