### ISSUE TITLE
Update UI elements to reflect new "evidence" on results

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#1054]
After #1040 is completed, and related to #1053, the UI will need to be updated in the app to reflect the now evidence data model.

This will for sure need to be done to the indicator results table present on the program page.

Other places in the code will need to be searched for as well.

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Verified as part of verification and completion of testing in #1040 & #1053
