### ISSUE TITLE
The map on sites page does not show pins if language is in french/spanish

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1071]
**Description:**
The map on sites page does not show pins if language is in french/spanish

Please see attached image. 

**Steps to Reproduce:**
1. Login to Tola-Activity
2. Click settings
3. Set Langauge to spanish/french
4. go to this link:
https://tola-activity.mercycorps.org/workflow/siteprofile_list/0/0/

**Results:**
No pins show for locations on map

**Expected Results:**
Pins show in all languages

**Comment by camgnostic** [comment]
Fixing this with #1072 
DEV NOTE: anywhere that uses a latitude or longitude in a template needs to be wrapped in {% localize off %} . ... {% endlocalize %} tags because the French use commas for decimal separators, and that causes Google to hiccup.

**Comment by RickieT** [comment]
This issue seems to now persist on the program home page now: 
![screen shot 2019-01-15 at 1 47 29 pm](https://user-images.githubusercontent.com/23220180/51212246-d1935700-18cc-11e9-950f-727aea58847f.png)
