### ISSUE TITLE
Indicator Disaggregation report filter redirects to Program page

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1075]
On the Indicator Disaggregation Report, if you try to filter by Indicator, it redirects to the Program page instead of filtering the report page.

**Comment by RickieT** [comment]
@sanjuroj I am unable to reproduce this issue in QA2, I think this is okay for Deploy.

**Comment by RickieT** [comment]
Verified fix is now live in production. Archiving...
