### ISSUE TITLE
Automatically test error condition behavior: A result is unassigned AND targets are Midline/Endline or Event

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1084]
When a result is unassigned AND targets are Midline/Endline or Event, the following are true:

1. The result is displayed in the table. 
2. Under the table, we display error message: This record is not associated with a target. Open the data record and select an option from the “Measure against target” menu. 

Here's what we'd expect: 
![image](https://user-images.githubusercontent.com/33670923/51229385-1214c400-1911-11e9-93f0-83350e01c330.png)

**Comment by KennyMonster** [comment]
Worked for me!

**Comment by RickieT** [comment]
Closing this, adding to my list of test cases

**Comment by KennyMonster** [comment]
After talking to Jenny, this needs to be an automated test.
