### ISSUE TITLE
Automatically test error condition behavior: A result is unassigned because no targets are set up

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1086]
When a result is unassigned because no targets are set up, the following are true:

1. The result is displayed in the table.
2. Under the table, we display error message: Targets are not set up for this indicator. Start by selecting a target frequency.
3. The string "Start by selecting a target frequency" links to the Targets tab of the indicator setup form.

Here's a screenshot of what we'd expect:

![image](https://user-images.githubusercontent.com/33670923/51229254-88fd8d00-1910-11e9-97d1-9db05dc5c52b.png)

**Comment by KennyMonster** [comment]
This worked correctly for me.

**Comment by RickieT** [comment]
Closing and adding as a test case for future testing /smoke tests.

**Comment by KennyMonster** [comment]
After talking to Jenny, this needs to be an automated test.

**Comment by jennyhavah** [comment]
There was a misunderstanding. We want to write tests to make sure that the error condition
