### ISSUE TITLE
Additional backend validation checks for program period modal

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1100]
We need these additional backend validation checks for the program period modal (some may already be complete):

- [x] Start date should always be the first day of the month
- [x] End date should always be the last day of the month
- [x] Start date should be < End date
- [x] If any indicator in the program has a date-aware target set, the start date should not be changed.
- [x] If any indicator in the program has a date aware target set, the end date can be changed to no earlier than the latest start date.  For instance, if a program period is set to Jan 1st, 2018 - Sept 30th 2019, and it has one annual indicator and one semi-annual indicator, the program date can be changed to no earlier than July 1st, 2019.  July 1st would be the latest period start date.  The goal is to make sure that the change to the program end date does not invalidate any of the existing target periods.

**Comment by RickieT** [comment]
Looks like the validation is behaving as described in the ticket, and no side effects of program/indicator creation appeared here. Moving to Ready for Deploy

**Comment by RickieT** [comment]
Closing as fixed/deployed
