### ISSUE TITLE
Result table not showing actuals for Midline/Endline + cumulative indicators

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1101]
If an indicator is designated as Midline/Endline and cumulative,  the results don't show up in the actuals column of the result table.  The results show up in the Results column and are given the proper value in the Life of Program row, but just not displayed in the Actuals column.  As far as I can tell, it is only the combination of Midline/Endline and cumulative that causes this.

I'm guessing this is a frontend issue, since the results are getting to the page ok, so I'll assign to Ken.  Please reassign to Cameron if it's a query issue.

<img width="835" alt="screen shot 2019-01-19 at 10 58 22 am" src="https://user-images.githubusercontent.com/6685499/51431178-23dcbc80-1bda-11e9-9319-d5f86685708c.png">

**Comment by sanjuroj** [comment]
Looks like it's also happening with Events.

<img width="830" alt="screen shot 2019-01-21 at 12 05 06 am" src="https://user-images.githubusercontent.com/6685499/51460442-5557a400-1d10-11e9-8662-cab4d5984a1c.png">

**Comment by KennyMonster** [comment]
Right now this issue is reproducible in `ghost_pepper` and not in `dev`. It also seems to be a query dealio:

```
def collected_data_view(request, indicator, program):
    indicator = ResultsIndicator.results_view.get(pk=indicator)
    reset_indicator_target_frequency(indicator)
    template_name = 'indicators/collected_data_table.html'
    program_obj = indicator.program
    program = program_obj.id
    #last_data_record = CollectedData.objects.filter(periodic_target=OuterRef('pk')).order_by('-date_collected', '-pk')
    # periodictargets = PeriodicTarget.objects \
    #     .filter(indicator=indicator) \
    #     .prefetch_related('collecteddata_set') \
    #     .annotate(
    #         achieved_sum=Sum('collecteddata__achieved', output_field=DecimalField()),
    #         last_data_row=Subquery(last_data_record.values('achieved')[:1])) \
    #     .order_by('customsort')
    periodictargets = indicator.annotated_targets

    for pt in periodictargets:
        print pt.id, pt.period_name, pt.actual
```

prints:

```
8548 Midline None
8549 Endline None
```

Test case was "QA Program - Emily" id 560. Indicator "Midline and endline | Number (#) | Increase (+) | cumulative" id 5701.

Punting to @camgnostic

**Comment by RickieT** [comment]
Looks like actuals are now showing, setting to ready for deploy.
![image](https://user-images.githubusercontent.com/23220180/51635616-12fab680-1f0c-11e9-973d-328ef6f87b48.png)

**Comment by jennyhavah** [comment]
I am not seeing the fix. Actuals in Event and Midline/Endline indicators are missing.

QA Jenny program:

![image](https://user-images.githubusercontent.com/33670923/51770091-b0cfbc00-2099-11e9-8dc9-4d075f29ba3f.png)

![image](https://user-images.githubusercontent.com/33670923/51770102-b9c08d80-2099-11e9-8913-20de41b9b03a.png)

**Comment by sanjuroj** [comment]
@RickieT Any idea why it worked for you and not for Jenny?  That seems very odd.

**Comment by esinn** [comment]
Confirming this works for me when testing against mid/endline and event targets. 
![image](https://user-images.githubusercontent.com/13574772/51838113-5171e600-22fd-11e9-8f2e-7f3113f84bf8.png)
![image](https://user-images.githubusercontent.com/13574772/51838148-664e7980-22fd-11e9-872f-446b3e1e7892.png)

**Comment by RickieT** [comment]
@sanjuroj I am not sure, can you provide program/environment specifics to your failure @jennyhavah? Also, is your cache refreshed? Perform a hard refresh (I apologize if you know this, cmd + shift + R).

**Comment by sanjuroj** [comment]
@RickieT I don't think Jenny has looked at it after the fix that Cam put in, so it's probably ok now.  But she was using a hard-refreshed browser on the -qa server. One thing to note is that the image you attached is for time-aware targets, not midline/endline or event, which is where the problem was occurring.

**Comment by jennyhavah** [comment]
Right, I reported that I wasn't seeing the fix on Friday. Just checked again and the Actuals are showing up. @camgnostic curious what the issue turned out to be, just for future reference?

**Comment by sanjuroj** [comment]
We're not sure how Jenny was unable to see the actuals but all testing seems to show that the actuals are now available, so closing the ticket.
