### ISSUE TITLE
Potentially confusing highlighting with rounded numbers

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1104]
In the results table, values of 85% appear to be highlighted in yellow, which is not the expected behavior.  We would expect everything 85% to 115%, inclusive, to be highlighted in green.  The most likely explanation for this is that the value's category (i.e. above, on-track, or below) is determined on a decimal value and then rounded for display purposes.  For instance, if the %Met value is 84.8, it is technically below the 85% threshold to would be categorized as below target (yellow).  But for display purposes, this would be rounded up to 85%. 

@jennyhavah We probably need to make a design decision about how we want to handle cases like this.  Technically, the yellow highlight in the above scenario is more correct, since the metric is below 85%.  However, it could be confusing and inconsistent (sometimes 85% could be green, sometimes it's yellow).

This might also be happening on the gas tank gauges.  Any place where these sorts of metrics are being categorized and displayed should be checked for consistency.

**Comment by jennyhavah** [comment]
@sanjuroj If the % met value is 84.8, I agree that it should be yellow because anything under 85 is considered not on track.

I thought for some reason that it was the reverse -- that things were showing up yellow when they should be green.

**Comment by axoplasm** [comment]
The test happens BEFORE the `abs()` function, so there are cases where the user will see "85%" and it will be green, and other cases where the user sees "85%" and it's yellow. They won't know when you are actually a whisker under 85 or over. 

The easy fix is to move the text to the the computed number.

Which gets me to my design question from earlier:

> When the user sees "85%" in the UI, should that be green or yellow?

**Comment by jennyhavah** [comment]
> When the user sees "85%" in the UI, should that be green or yellow?

We're saying that if it's between 85% and 115% **inclusive**, you're on track. So if the user sees 85% in the UI, then they will (and should) expect the results highlighting to be green as well.

**Comment by axoplasm** [comment]
What it was:

![image](https://user-images.githubusercontent.com/169060/51629320-269e2100-1efc-11e9-8511-ffdad78fbaf4.png)

What it will be:

![image](https://user-images.githubusercontent.com/169060/51629340-3453a680-1efc-11e9-83e1-62f3344fe817.png)

**Comment by jennyhavah** [comment]
@axoplasm Shouldn't the 115% be green?

**Comment by RickieT** [comment]
Looks like we've got this dialed in now:
85% through 115% is green

Less than 85% is yellow
more than 115.01% is yellow
