### ISSUE TITLE
Inconsistent data: some programs were created with start/end dates that are mid-month

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1109]
Some programs were created with mid-month start and end dates.  Needs to be investigated to find out which have no targets (and can thus be edited directly), which have targets that will not require target changes to update, and which potentially require user input/support to update to follow the required first-of-the-month to last-of-the-month reporting period date validation.
[bad start and end dates.xlsx](https://github.com/mercycorps/TolaActivity/files/2784807/bad.start.and.end.dates.xlsx)

**Comment by camgnostic** [comment]
of that list, there are:
- [ ] - 15 programs with no time-aware indicators (so should be no problem to write a script that just adjusts their reporting period dates with no other changes).
- [ ] - 6 programs with a reporting period that starts on the first of the month and ends mid month - changing the end date for the reporting period should not affect targets at all (if 9 monthly targets get us from Jan 1 to Sept 15, then they also get us to Sept 30)
- [ ] - 1 program which has a time-aware indicator but no targets set up
- [ ] - (the tricky part) 3 programs with mid-month start AND end dates that require some judgment on the adjustment of dates.

How much of this should I automate in a script, and when should we release it?  @jennyhavah / @sanjuroj ?

**Comment by jennyhavah** [comment]
> (the tricky part) 3 programs with mid-month start AND end dates that require some judgment on the adjustment of dates.

@camgnostic Which three programs are these, and from which country?

**Comment by RickieT** [comment]
**QA Verified:**
* Checked all the start dates in the excel sheet listed, all showing 1st day month/last day of month end dates for all programs

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.
