### ISSUE TITLE
Update translation of "Before adding indicators..."

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1113]
There is currently this English string in the translation files:  "Before adding indicators and performance results, we need to know your program's".  We should update this to be in a blocktrans that includes the rest of this sentence, even if it results in a bunch of code being included.  Word order and gender can change with possessives, so it's important to have all the of translation context.  The English string appears in at least a couple of places in the code.

**Comment by RickieT** [comment]
*QA Verified:*
@KennyMonster suggestion was to check this in english to best verify as the translations are here yet, so I checked the forms and didn't see any issue there, moving to deploy ready.
