### ISSUE TITLE
Program page: Trailing zeroes displayed in result table

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1117]
This is a regression in how we are displaying numbers in the result table. We do not want to show trailing zeroes.

**Affects:** Result table including:
- [x] 1. LoP target
- [x] 2. Target values
- [x] 3. Actual values
- [x] 4. Result values

In addition, if I then reopen the result form, it will show the trailing zero as well.

![image](https://user-images.githubusercontent.com/33670923/51699616-09338a80-1fc2-11e9-8aa8-ee87b78025a9.png)

![image](https://user-images.githubusercontent.com/33670923/51700787-d8a12000-1fc4-11e9-93ea-10a169d0bdb1.png)

**Comment by jennyhavah** [comment]
@camgnostic I have a vague recollection of a discussion with you about this when you were working on the result form a while back. I can't remember what the resolution was, so am not sure if I'm seeing a regression or what we decided to go with because the desired display would have negative consequences elsewhere.

**Comment by jennyhavah** [comment]
@camgnostic Paul thinks it's not just a simple formatting issue in the result table. So I'd like to bring you back into this ticket so we can make sure there are no surprises.

What I can say with pretty high confidence is that the behavior of me typing in 12.5 and then the result table displaying 12.50, and the result form also displaying 12.50... is new.

**Comment by jennyhavah** [comment]
p.s. If this is a non-trivial fix, we can move it into Huckleberry.

**Comment by axoplasm** [comment]
To replicate the weird and possibly new thing:

1. Open the collected results table for an indicator (for example on your program page)
1. Add or edit a result
2. Enter a result with one decimal digit (e.g. `12.1`)
3. Save and close the dialog
4. Reopen the results dialog for that result: it will now be a two digital decimal with a trailing zero (e.g. `12.10`)

**Comment by axoplasm** [comment]
…I can probably write a filter that will replicate the expected behavior but it might not be as sophisticated as "remove following zeroes". Right now the template is coded with `|floatformat:"-2"` which is shorthand for "truncate up to two digits for this float." Here's what we see when we show this field unfiltered:

![image](https://user-images.githubusercontent.com/169060/51701468-5b76aa80-1fc6-11e9-9fae-e5eaf7594ea1.png)

**Comment by axoplasm** [comment]
…actually now that I reflect "remove following zeroes (and periods)" (i.e. as a regex) might be *exactly* how I'd write this filter.

@camgnostic I can do this, but are there other implications for where this decimal data surfaces?

**Comment by RickieT** [comment]
Looks like were not seeing trailing zero's anymore:
![image](https://user-images.githubusercontent.com/23220180/51851995-f5499a80-22d9-11e9-9648-84beae7156a4.png)
