### ISSUE TITLE
IPTT and result table: When results are unnassigned to targets, don't include in Actuals or %Met calculations

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1125]
**Issue originally identified by Rickie:** Today, when results are not assigned to targets, we still include them in our Actuals and % Met calculations. We need to rethink the expected behavior.

# Affects
1. Result table on the Program page
2. IPTT Recent Progress report
3. IPTT Target vs Actuals report

# Acceptance criteria

## Time-aware indicators (except LoP where everything automatically gets assigned to LoP target)

- [x] 1. Actual values are not displayed for any unassigned results

- [x] 2. No actual value appears in the LoP row either, because there's nothing to total.

- [x] 3. No % met appears in either the result rows or the LoP total row, because there are no actuals.

![image](https://user-images.githubusercontent.com/33670923/51711849-ff218400-1fe1-11e9-9a8e-103f1195b937.png)

_Making note of this because it has caught a couple of us off guard: Results are ALWAYS auto-assigned to time-aware targets. You can't have a time-aware indicator with some results assigned and some unassigned. As soon as you set up new time-aware targets, any existing results are auto-assigned to the new targets, and this is the desired behavior._ 

## Midline/endline and Event indicators

- [x] 1. Actual values are not displayed for any unassigned results

- [x] 2. Regression check: Actual values are still displayed for any manually assigned results. (You can have some unassigned and some assigned in this scenario.)

- [x] 3. LoP Actual only includes values from _assigned results._

- [x] 4. LoP %Met only includes values from _assigned results._

![image](https://user-images.githubusercontent.com/33670923/51711991-4f98e180-1fe2-11e9-9379-24ed81809c3d.png)

## Recent Progress IPTT
- [x] **Time aware indicators except LoP:** For the scenario I described above, the values in LoP Actual and LoP % Met columns match what you see in the corresponding result table, if you click the table icon in the IPTT.

- [x] **Midline/endline and event indicators:** For the scenario I described above, the values in LoP Actual and LoP % Met columns match what you see in the corresponding result table, if you click the table icon in the IPTT.

## Target vs Actuals IPTT
- [x] **Time aware indicators except LoP:** Not applicable. If there are no targets, the indicator shouldn't be showing up at all.

- [x] **Midline/endline indicators:** For the scenario I described above, the values in LoP Actual and LoP % Met columns match what you see in the corresponding result table, if you click the gear icon in the IPTT... _for all target periods_ not only the LoP columns. 

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by RickieT** [comment]
I believe Jenny's comments to be sound here.

**Comment by sanjuroj** [comment]
This looks good to me.  I'd recommend that we do this as part of Huckleberry rather than Ghost Pepper, especially since we are changing the way the IPTT is working.  We haven't done much with the IPTT since it was created so we'll need to test thoroughly.  Also, I'm curious if this is going to require changes to the IPTT queries.  If so, would it be better to make the IPTT changes at the same time we update all of the IPTT queries to use the new ones that Cameron as developed?

**Comment by jennyhavah** [comment]
**Time aware indicators except LoP:** PASSED
![image](https://user-images.githubusercontent.com/33670923/58986099-8e5d5600-8791-11e9-9ecd-23b718759c55.png)

**Midline/endline and Event indicators** PASSED
![image](https://user-images.githubusercontent.com/33670923/58991543-59570080-879d-11e9-96b5-c725efc3fb7f.png)

**Recent progress IPTT** PASSED
Values in IPTT columns match what's in the results table.

**Target vs actuals IPTT** PASSED
Values in IPTT columns match what's in the results table.
