### ISSUE TITLE
Update QA Program creation to handle new Evidence model structure

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1130]
In the  Huckleparadigm, evidence is no longer a documentation object but is now a URL/File path (URI with a file or http scheme) and the QA program creation script needs to be updated to reflect those changes, as well as any edge cases that need to be QA'd in the huckleverse.

**Comment by KennyMonster** [comment]
I think this is actually already done, though not well tested. I made the change to the QA generation script as part of the change over from Documents to URL fields for evidence.

**Comment by sanjuroj** [comment]
Ah, Cameron probably stomped it.  I made a ton of changes on the dev branch which superseded anything on other branches.  It's a pretty quick mod to update for huckleberry.

**Comment by RickieT** [comment]
**Deployment Verification**
 - [] Confirmed “Ready for Deploy” status
