### ISSUE TITLE
Redirect for old program page URLs to new (no indicator ID or type ID) program page URL

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1133]

**Comment by RickieT** [comment]
@camgnostic can you point me to where i can check this?

**Comment by RickieT** [comment]
Looks like the re-direct works properly from the old URL's, moving to deploy ready

**Comment by RickieT** [comment]
**Deployment Verification**
- [x] Confirmed “Ready for Deploy” status
- old "/0/0" url redirects to the new url appropriately
