### ISSUE TITLE
404 error loading results table into modal on IPTT

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1136]
I found this on my local machine and dev.

#### Steps to reproduce:

1. Open any IPTT
2. Click on the results table for an indicator
3. PNotify returns a 404

**Comment by axoplasm** [comment]
![image](https://user-images.githubusercontent.com/169060/51930728-0e247f80-23b0-11e9-8cda-c66aff20a012.png)

**Comment by RickieT** [comment]
**Deployment Verification**
* Can no longer reproduce based on steps.
- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 3 32 30 pm](https://user-images.githubusercontent.com/23220180/52751550-a15ed700-2fa4-11e9-9489-f737345a941c.png)
