### ISSUE TITLE
 "add results" modal > Inconsistant function and styling on disaggregation selectors

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1137]
In the results adding modal, the Standard Disaggregations and New Disaggregations, they both function the same, but share different styles, as well as missing the drop down arrow on "new disaggregations".

See attached image: 
![screen shot 2019-01-29 at 10 35 45 am](https://user-images.githubusercontent.com/23220180/51932100-48dbe700-23b3-11e9-9c29-b289d54131d2.png)

**Comment by axoplasm** [comment]
See #808 and #1165

**Comment by jennyhavah** [comment]
@RickieT Can we close this ticket?

**Comment by RickieT** [comment]
Yeah this is good now 👍
