### ISSUE TITLE
Indicator targets tab: Unit of measurement: Introduce Number (#) and Percentage (%) toggle

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#114]
**System user story:** System needs to know whether the indicator is being measured as a percentage or a number of something, so that it may correctly display target period values in the periodic targets table, collected data records, and indicator tracking reports.

**TolaActivity user story:** When I want to track indicators as a percentage, I let the system know this.

**Affects:** Targets tab of the indicator configuration form in both full-page and modal versions.

![image](https://user-images.githubusercontent.com/33670923/37637681-3cf28e70-2bc6-11e8-9731-f80e44bd5de5.png)

**UI DETAILS**
1. Gray box behind form fields is color #F5F5F5
2. Gray box has rounded corners with a radius of 8.
3. Form fields are 450 pixels wide.
4. Padding between form fields and gray box is 12 pixels

**ACCEPTANCE CRITERIA**
1. Under the "Unit of measure" text box are two side-by-side radio button options: Number (#) and Percentage (%). 
2. Number (#) is the default
3. It is not possible to de-select or select both options -- only one or the other.
4. When I toggle to percentage, the following things happen:
4.1. A placeholder % appears, right-aligned inside the Life of Program (LoP) and Baseline text boxes. This should happen immediately, without having to submit the form.
4.2 After the user types in a number, a % sign is automatically appended to it. (We are making no changes to form validation; we still want to prevent people from _manually_ typing in symbols and letters. This is to prevent human error -- it would be too easy to forget the symbol, etc.)
4.2.1. Erring on the side of over-communicating here: We're _not_ automatically appending a % sign to the _Unit of measure_ field itself, because it's a descriptive field and not a numeric one. (Example: It would not make sense to append a % symbol to the following _Unit of measure_ text field entry: "Percentage of households with access to water %"

![image](https://user-images.githubusercontent.com/33670923/37637891-6057433c-2bc7-11e8-8b0d-3e0d6e8390ed.png)

**Comment by mahmoodkhan** [comment]
@jennyhavah I appreciate the detailed and specific descriptions in the stories you write. It is very helpful esp. the mockups you include. To save everyone some time, I would suggest that let's not include hard values for padding/width/height etc unless it is absolutely necessary for UI reasons. We will try to implement UI details as close as possible to your mockups without spending too much time. You can, of course, review the initial implementation and provide feedback to adjust things a little more.

**Comment by jennyhavah** [comment]
Understood about fixed values, @mahmoodkhan. I'll send you a message offline to explore a better way to communicate things like padding, in a relative way.

**Comment by jennyhavah** [comment]
Validated except for UI portion.
