### ISSUE TITLE
Indicators list on Program page: explicate the subtotals for closed time-aware periods which may cause an apparent mismatch between gauge highlighting and periodic target highlighting

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1141]

**Comment by axoplasm** [comment]
For programs that:

1. Have not yet reached end of program;
2. Have time-aware indicators;
3. Have some periods ended for those indicators…

…there may be situations in which results against targets are being __correctly__ calculated for inclusion in the "on track" gauge, but which appear to have the __opposite__ highlighting periodic targets list. To wit:

This indicator has five ended target periods, three of which are on target, but two periods that are also ended but have no results. So even though all __highlighted__ target periods are "on track," the indicator is __not on track.__

![image](https://user-images.githubusercontent.com/169060/52079101-ab66eb80-2549-11e9-8b5f-df46a7bff81c.png)

Conversely, __this__ indicator also have five ended target periods, two of which are off-track (too high), but three periods with no results. So even though all __highlighted__ target periods are "off track," the indicator __is on track__.

![image](https://user-images.githubusercontent.com/169060/52079124-bae63480-2549-11e9-8d48-5fac7474e430.png)

**Comment by axoplasm** [comment]
Our proposed solution is to make explicit the “subtotals“ for ended periods that are actually used in calculating indicator on/off track. For example:

![completed-periods-subtotals](https://user-images.githubusercontent.com/169060/52079267-0ef11900-254a-11e9-9a47-725778d7a499.png)

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 3 19 13 pm](https://user-images.githubusercontent.com/23220180/52750991-c6524a80-2fa2-11e9-9ec7-1b0d5fefd15a.png)

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Verified this is accurate for multiple other indicators that apply
- [x] Media Verifying: 
![screen shot 2019-02-13 at 3 19 13 pm](https://user-images.githubusercontent.com/23220180/52751139-44165600-2fa3-11e9-8f24-507af8c30348.png)
