### ISSUE TITLE
End of period should trigger at midnight UTC

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1143]
It's not clear that this is an issue but I wanted to document it just in case.  When we were investigating #1141, we noticed that the completed period was showing as Jan 31, 2019.  We thought that was true in Nepal, which is the country we were looking at.  But it wasn't true in Scotland, which is where we were looking at the site.  So it's possible that the period showing up as "complete" one day early?

**Comment by KennyMonster** [comment]
Playing with the system clock on my laptop, I wasn't able to obviously break things. That said, I was using the new UI indicator added by Paul to 1141-indicator-subtotal as opposed to computing the "on track" status.

![screen shot 2019-01-31 at 11 58 03 pm](https://user-images.githubusercontent.com/1278224/52297681-26f3de80-2936-11e9-8439-e995a484ae33.png)

The sub-total bar appears before the "current" periodic target, where current is defined by

```
    def current_periodic_target(self, date_=None):
        """
        Return the periodic target with start/end date containing localdate() or specified date

        :return: A PeriodicTarget with start_date and end_date containing now(), or None
        if no PeriodicTargets are found matching that criteria such as MIDLINE/ENDLINE
        """
        today = date_ or timezone.localdate()
        return self.periodictargets.filter(start_date__lte=today, end_date__gte=today).first()
```

**Comment by camgnostic** [comment]
commit #eff1340b addresses the other half of this ticket (as part of issue #1141) by ensuring that the calculation for the "on-track" status of an indicator similarly only counts periods that are completED today, not completING today

**Comment by axoplasm** [comment]
note that Program to Date was previously showing the *current* period, as of 5da3050 it shows the last completed period for that indicator

**Comment by sanjuroj** [comment]
To follow up on the post by @KennyMonster above, if the current date is Jan 31st, shouldn't the most recent completed period be December, 2018?  In other words, doesn't the image posted by Ken show a Program to Date period that is incorrect?  I'm not sure who worked on this, @axoplasm or @camgnostic.

**Comment by camgnostic** [comment]
I think this needs clarification from business-logic as it's beyond a mere programming error.  I fixed the "date less than or equal to" bug, but there is a murkier issue:
- what is "now"?  If I'm in Japan and talking to my coworker in Hawaii and it's Jan 31st for them but Feb 1st for me, should we see two different screens?  If not, what's the global "today" marker?  We punted on this issue with the "now or within a couple days" for result date validation, but this one I think we need to decide.  When is a period over?  Midnight in Greenwich? Midnight in Portland?  Wherever the user is?

**Comment by jennyhavah** [comment]
Notes from team huddle: UTC time = Tola time _(Cue MC Hammer video.)_

**Comment by camgnostic** [comment]
- [ ] Period completed query (rollups for progress)
- [ ] Period completed query (for showing UI "progress" bar)

**Comment by RickieT** [comment]
@camgnostic can you provide any details on how to best test this from a user perspective?

**Comment by RickieT** [comment]
*QA Verification:*
* with dev sign off, due to the complexity of actually testing this, moving to ready for deploy.

**Comment by sanjuroj** [comment]
Fixed in Hucklepatch
