### ISSUE TITLE
Double percent sign appearing on the "unavailable" section of "Indicators on track"

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1144]
There are two percent signs (e.g. 25%% unavailable) appearing in the % unavailable section of the "Indicators on track" gas tank.

<img width="300" alt="screen shot 2019-02-01 at 5 04 58 pm" src="https://user-images.githubusercontent.com/6685499/52137980-d2a1e380-2643-11e9-874a-d14c64eadbf9.png">

**Comment by KennyMonster** [comment]
I noticed and fixed this a few days back. The fix might be in huckleberry?

**Comment by KennyMonster** [comment]
I dug up the commit: 1b86e892165f07ff0733c8ba91ae4f051b429a59

It is in huckleberry, though could easily be cherry picked if needed.

**Comment by sanjuroj** [comment]
It can stay in huckleberry, I just put it in GP because it would be a quick fix.

**Comment by KennyMonster** [comment]
I'm making the executive decision to move this ticket to huckleberry such that the fix that lives there can be tested and made officially part of the release.

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
_Home Page_
![screen shot 2019-02-13 at 2 25 32 pm](https://user-images.githubusercontent.com/23220180/52748408-4d032980-2f9b-11e9-8406-ec1a4a7ba901.png)
_Program Page_
![screen shot 2019-02-13 at 2 25 42 pm](https://user-images.githubusercontent.com/23220180/52748434-5d1b0900-2f9b-11e9-9313-40115498bb14.png)
