### ISSUE TITLE
Scaling and white space has disappeared from huckleberry development branch

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1148]
Please see attached media: 

Huckelberry (tola-activity-qa):
![image](https://user-images.githubusercontent.com/23220180/52154368-581c9800-2632-11e9-9228-712e7d14e673.png)
Production:
![image](https://user-images.githubusercontent.com/23220180/52154351-4a671280-2632-11e9-81a3-a140c3d01298.png)

**Comment by axoplasm** [comment]
I am refactoring away a lot of max-widths imposed by Bootstrap. These changes *should* have been picked up in 7293616. See 
https://github.com/mercycorps/TolaActivity/issues/729#issuecomment-459483876 for more info.

**Comment by axoplasm** [comment]
It looks like the rebuilt js & css files didn't get committed last week. I added these for huckleberry in 38405aa

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 3 24 35 pm](https://user-images.githubusercontent.com/23220180/52751198-7e7ff300-2fa3-11e9-8771-72ad5bf4c7dc.png)
