### ISSUE TITLE
Gauges on homepage dashboard should follow same filter logic as on program page

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1155]
(See #1019 for more info on what that behavior is.)

Jenny's update, capturing for posterity: There are some significant differences between the program page and home page in how we approach one of the two the scenarios referenced in #1019.

# Scenario 1: No targets set up <-- significant differences

## Home page
We want this:
![image](https://user-images.githubusercontent.com/33670923/52810438-66fa4600-3047-11e9-972c-184d32b118f4.png)

## Program page
We want this:
![image](https://user-images.githubusercontent.com/33670923/52810461-7bd6d980-3047-11e9-99a7-425b3aaa3843.png)

# Scenario 2: Targets set up but no results 
The only difference is that on the program page, the Indicators with results filter is highlighted, since you've filtered on that metric after clicking "Add missing results" on the home page.

## Home page
We want this:
![image](https://user-images.githubusercontent.com/33670923/52810594-c48e9280-3047-11e9-8745-f765e6405f53.png)

## Program page
We want this -- note yellow box around "Indicators with results"
![image](https://user-images.githubusercontent.com/33670923/52810619-d3754500-3047-11e9-96b3-3b70e384c79f.png)

**Comment by jennyhavah** [comment]
Right now I'm not seeing the "Add missing"... links at all on the home page.

**Comment by RickieT** [comment]
@jennyhavah are you still seeing this issue? I can see them on qa right now:
![screen shot 2019-02-13 at 10 33 05 am](https://user-images.githubusercontent.com/23220180/52734748-d0605300-2f7a-11e9-819f-a2d0c38d1e49.png)

**Comment by jennyhavah** [comment]
@RickieT Yep, I see them now! The links are unresponsive though, and there's a very minor styling issue.

I added two comments to #948 and moved that ticket back into the Backlog to be done for the patch release. Heads up @camgnostic as he's currently assigned to the ticket.

**Comment by jennyhavah** [comment]
Heads up @axoplasm -- fine tuned the original ticket a bit to reflect the current (and desired) state of things.
