### ISSUE TITLE
Table on Indicator Plan page is large, requires a lot of scrolling, scale is large

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1156]
The indicator plan page is a bit difficult to navigate, elements seem large, and even on a large monitor, takes a bit of finesse to move about the page and view information in the tables.

Heres an example link:
https://tola-activity-qa.mercycorps.org/indicators/indicator_plan/572/

![screen shot 2019-02-07 at 11 06 41 am](https://user-images.githubusercontent.com/23220180/52436187-78cc6e00-2ac8-11e9-8978-2ed36c431cff.png)

**Comment by axoplasm** [comment]
I added two new text size utility classes we can use for tables (or elsewhere) including this.

The scrolling behavior is the Bootstrap-standard [responsive](https://getbootstrap.com/docs/4.2/content/tables/#responsive-tables) class. This is what we use for the IPTT as well. It has a known UI tradeoff with pointer devices that don’t have sidescrolling, namely it’s tricky to get a horizontal scroll handle. This is the sort of tradeoff where I fall back to “if it doesn’t work for our site, it won’t work for any similar site,” and assume the user accepts this as a universal behavior.

**Comment by jennyhavah** [comment]
@axoplasm Are you recommending that we leave as it is at this point, or is there anything else you'd like to do before we close this ticket?

**Comment by axoplasm** [comment]
Yes, I'm recommending we leave it.

**Comment by jennyhavah** [comment]
Closing this ticket, based on Paul's recommendation that we leave as is.
