### ISSUE TITLE
Home page: Don't show "Program metrics for target periods completed to date" for various empty state conditions

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1159]
Issue: When there are no program metrics for a given program, we still show the "Program metrics for target periods completed to date" message/

All the scenarios I can think of:

- [x] 1. No indicators added yet
![image](https://user-images.githubusercontent.com/33670923/52582458-1cc45b00-2de2-11e9-92ba-aca3754b9089.png)

- [x] 2. All indicators missing targets
![image](https://user-images.githubusercontent.com/33670923/52582572-55fccb00-2de2-11e9-9bfc-01a37c9d3afc.png)

- [x] 3. Need to update program reporting start and end dates
![image](https://user-images.githubusercontent.com/33670923/52582626-73ca3000-2de2-11e9-9ac4-3116c4b47715.png)

_Did I miss any other scenarios?_

**Comment by axoplasm** [comment]
Here's how these error states look on Huckleberry RN (image from my local):

![image](https://user-images.githubusercontent.com/169060/52583736-31562280-2de5-11e9-8ddd-998a26aecce7.png)

**Comment by axoplasm** [comment]
View from my machine on commit 414d268:

The second case above is (slightly) tricky. We had captured it entirely inside the gauge tank as well — see the third blob on the previous screenshot. This kind of puts us back on the road of nesting these conditions. Not a deal breaker but flagging it FFR.

![image](https://user-images.githubusercontent.com/169060/52592293-e47d4680-2dfa-11e9-933e-f4b969c8ef67.png)

**Comment by KennyMonster** [comment]
From Cameron, the heart of this ticket at this point is simply hiding

![screen shot 2019-02-11 at 12 47 45 pm](https://user-images.githubusercontent.com/1278224/52592462-476edd80-2dfb-11e9-92b0-660ea9f19d49.png)

on both the program page and the home page when there are no gauges displayed.

**Comment by camgnostic** [comment]
This looks appropriate on tola-activity-qa right now, screenshot attached
![screen shot 2019-02-12 at 3 17 41 pm](https://user-images.githubusercontent.com/7941355/52674744-6479de00-2ed9-11e9-8f33-930aa0ee08dc.png)

Moving to staged

**Comment by RickieT** [comment]
Can verify, working now as expected

**Comment by KennyMonster** [comment]
I was going to implement this on the program page last Monday before having to run off and pick up a sick kiddo. Was this taken care of on the program page, specifically with the React versions of the metrics?

**Comment by jennyhavah** [comment]
@KennyMonster As discussed in Slack, this ticket only applies to the Home page. A user who hasn't set their program period or entered their first indicator yet doesn't see a link to the program page. And when they don't have any targets set up, we show the gauge set to 0% and the "Program metrics for target periods completed to date" is appropriate.

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 2 04 33 pm](https://user-images.githubusercontent.com/23220180/52747307-5ccd3e80-2f98-11e9-9222-bd422ae1a34d.png)
