### ISSUE TITLE
Indicator plan: Change export button label

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1161]
I'd like to see the button be consistent with our IPTT, with the label "Excel". "Export all" doesn't tell you the format to which you're exporting. It also implies that you can opt to partially export, which isn't the case.

Please change from this:
![image](https://user-images.githubusercontent.com/33670923/52653333-a177ad80-2ea4-11e9-93a4-c960545f0dfa.png)

to this:
![image](https://user-images.githubusercontent.com/33670923/52653355-aa687f00-2ea4-11e9-8f74-08b195bfd2e1.png)

**Comment by RickieT** [comment]
on the indicator plan page, this now reads Excel, moving to ready for deploy.
