### ISSUE TITLE
Indicator plan export: Inconsistent treatment of text truncation/wrapping in columns

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1162]
I'm noticing inconsistency in that some columns appear to be truncating text while others spread across neighboring columns. An example:

![image](https://user-images.githubusercontent.com/33670923/52598956-24005e80-2e0c-11e9-9160-808f15745c17.png)

@KennyMonster what do you think about setting text to wrap instead of truncating or sprawling? Any risks, layout-wise? Could we get some wacky results if we do that?

**Comment by KennyMonster** [comment]
Attached is an XLS with wrapped text (top aligned)

[indicator_plan with wrapped text.xlsx](https://github.com/mercycorps/TolaActivity/files/2861539/indicator_plan.with.wrapped.text.xlsx)

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 3 44 15 pm](https://user-images.githubusercontent.com/23220180/52752005-3d3d1280-2fa6-11e9-8581-a6e4809ee28d.png)
