### ISSUE TITLE
Evidence section of Result form: Record name field is highlighted when it's the Link field that is empty.

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1164]
We have a rule that if you fill in the "Record name" field, you must include a link to a file or folder. The validation is working as expected, but its location is unexpected and a bit confusing.

![image](https://user-images.githubusercontent.com/33670923/52665744-2c66a100-2ec1-11e9-93b3-7ba82db6f10d.png)

Expected behavior:
1. "Link to file or folder" field label is red instead of "Record name"
2. Text box under "Link to file or folder" is outlined in red rather than the text box under "Record name.
3. Warning message appears underneath the "Link to file or folder" text box. Suggested update to the warning text: "A link must be included along with the record name."

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy”
- [x] Media Verifying: 
![screen shot 2019-02-13 at 3 52 15 pm](https://user-images.githubusercontent.com/23220180/52752368-6316e700-2fa7-11e9-9944-e5ce8d38096e.png)
