### ISSUE TITLE
Results modal: Styling for disaggregation accordions

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1165]
This was originally reported in #1163. Some Results modals show the old accordion styling:

![](https://user-images.githubusercontent.com/33670923/52663279-1d7cf000-2ebb-11e9-893d-c8d4336de142.png)

@jennyhavah's original message:
> Some additional weirdness -- this is program 544 that has custom disaggregations set up in additional to standard. Note the system message with two types of disaggregation below, that seem to be lacking the styling Paul introduced with Huckleberry -- blue links instead of gray boxes, etc.

**Comment by axoplasm** [comment]
@jennyhavah : this was waiting on unmerged code (PR #1147). I think we might have not merged it because we had an open question on #808 about the "submitted by" field. If you get a chance, can you take a look at that? https://github.com/mercycorps/TolaActivity/issues/808#issuecomment-459860431

**Comment by jennyhavah** [comment]
Responded to the comment in #808.

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 3 46 25 pm](https://user-images.githubusercontent.com/23220180/52752093-88efbc00-2fa6-11e9-8b67-b230b92b09a3.png)
