### ISSUE TITLE
Result table, Evidence column: Record names not showing up.

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1169]
Looking at a bunch of indicators on QA Jenny and TolaData Demo, and am not seeing the record names displayed as expected. The rule according to ticket #808 (see section 5.3) is that if there is a record name, it should be displayed in the Evidence column. 

Here's what i see in the result table -- note the URLS in the evidence column:
![image](https://user-images.githubusercontent.com/33670923/52672214-101f3000-2ed2-11e9-8b17-0953a781c7bd.png)

Each of those evidence links actually has a corresponding Record name. For instance:
![image](https://user-images.githubusercontent.com/33670923/52672239-1f9e7900-2ed2-11e9-8d1b-176cfc511ae7.png)

**Comment by axoplasm** [comment]
Do we see the record name instead of the URL? (I thought we were just showing the URL)

**Comment by axoplasm** [comment]
d192414 should fix this.

My local:

![image](https://user-images.githubusercontent.com/169060/52674016-2f6c8c00-2ed7-11e9-9d71-41d2016fe462.png)

Throwing out a flag: there are some edges where the "Evidence Name" might contain only nonprinting characters so it would look like there's no link. It looks like the form validation checks for fields that contain only spaces and submit them as [empty], I couldn't replicate __that__ edge in my spot checks

**Comment by RickieT** [comment]
Results with names, now show a name and not the URL, regardless
![1169-pass](https://user-images.githubusercontent.com/23220180/52736893-d3aa0d80-2f7f-11e9-8dfc-a8abfbaedd54.png)
