### ISSUE TITLE
Result form: Visual refinements

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1170]
Suggestions for visual refinements to the Result form, plus a few details carried over from #808.

## General
- [x] 1. It's feeling a bit crowded -- add more padding between the edges of the form and the content?
- [ ] 2. Would like to see the Evidence section set off more from the rest of the form -- the gray on gray is pretty subtle. Ideas: Make the form background white and leave the Evidence area gray, or leave the form background alone and make the Evidence area white to increase contrast.

## Form field order
- [x] "Submitted by" should be after Project.

## Evidence section
- [x] 1. Swap the order of the two fields -- first link, then Record name.
- [x] 2. I'd like to see the "Browse Google Drive" link either right aligned (see below) -- or perhaps indented a bit if you prefer to keep it left-aligned -- to more clearly signify that it's a _sub-option_ of "Link to file or folder". From original mockup: 
![image](https://user-images.githubusercontent.com/33670923/52685597-2d1e2800-2eff-11e9-9ed1-ffdacffad4aa.png) 
- [x] 3. View button could use a bit of horizontal padding. Here's how it looks at the moment: 
![image](https://user-images.githubusercontent.com/33670923/52686931-a10eff00-2f04-11e9-86bc-6def4e98ae01.png)

**Comment by KennyMonster** [comment]
My attempts as styling:

![screen shot 2019-02-13 at 4 31 52 pm](https://user-images.githubusercontent.com/1278224/52753819-0caca700-2fad-11e9-8841-cf501d2fd56e.png)

I was unsure what colors to use to increase contrast.

**Comment by jennyhavah** [comment]
@KennyMonster 

1. Can you please right-align "Browse Google Drive" as shown in my mockup snippet above? (I thought indenting might work just as well as right-aligning, but I was wrong... I think it looks awkward and unintentional.)

2. Let's try changing the Evidence area's background to white instead of the slightly darker gray.

3. Can you add more padding above "Result"?

**Comment by jennyhavah** [comment]
@axoplasm Just want to check that you two are not simultaneously styling this form. I know you were changing the "Submitted by" treatment to plain text, not sure if you were doing other stuff as well?

**Comment by axoplasm** [comment]
@KennyMonster I can take a look at this tomorrow. I'm trying to establish a repeatable pattern for things like the background of nested fieldsets. So changing it here means changing it elsewhere

**Comment by jennyhavah** [comment]
Regression watch: Let's make sure the validation shows up under the right field, as per #1164 -- now that we've flipped the order of the two Evidence fields.

**Comment by jennyhavah** [comment]
One more thing to be mindful of with regards to the "Browse Google Drive" link -- validation weirdness:

![image](https://user-images.githubusercontent.com/33670923/52758707-27d3e280-2fbe-11e9-93ca-a5fb97e0ff7f.png)

This further strengthens my preference to right-align the link as a way to differentiate, rather than indenting...

**Comment by axoplasm** [comment]
For a variety of reasons we are limited in where that "Browse Google Drive" link should go. For example, here's how it will look when it's right-aligned (and with an error condition):

![image](https://user-images.githubusercontent.com/169060/52759267-11c72180-2fc0-11e9-8cfd-1dbcad37532f.png)

**Comment by axoplasm** [comment]
How about this? It also has the advantage of keeping the browse button in the tabfocus flow in case I'm the type who tabs between form elements.

![image](https://user-images.githubusercontent.com/169060/52760041-e7c32e80-2fc2-11e9-864c-9b06afa8ea79.png)

**Comment by axoplasm** [comment]
Here's where we're at this form:

![image](https://user-images.githubusercontent.com/169060/52761739-82267080-2fc9-11e9-888b-c584ecfc590a.png)

I used the `btn-link` style with an icon for Google drive and pushed it to the right of the "view" button. That way "view" is tied directly to the URL field (i.e. "view this URL") and hopefully the Browse Gdrive button subtly looks like "feed this URL field"

I fiddled a lot with the background for the nested evidence field. White background had the dual effect of washing out the form elements (which I like to "pop" from the background) + made that section visually too hot. But the slightly-darker gray was too much like the background gray…yet if I made it any darker it also got too visually hot! 

So we have the standard border for a `card` element. This is straight out of Bootstrap I guess.

**Comment by axoplasm** [comment]
…and error states:
![image](https://user-images.githubusercontent.com/169060/52762203-75a31780-2fcb-11e9-92ad-95d196d74a44.png)

**Comment by RickieT** [comment]
**QA Verification Complete**
* Status: Deploy Ready

- [ ] Validation is present, referenced from #1185. Validation is not real time, but on save, will display. 
- [ ]  Browse Google Drive is on the right, and opens drive/team drives accordingly when clicked.
- [ ] Link field occurs BEFORE name field
- [ ] View button padding increased

**Media Verified:** 
![screen shot 2019-02-14 at 11 25 55 am](https://user-images.githubusercontent.com/23220180/52811997-551aa200-304b-11e9-98e2-bc92679d9825.png)
