### ISSUE TITLE
Gauge interaction: When a gauge reaches 100%, the purpose of clicking it becomes unclear

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1172]
**Affects:** Three gauges on the program page and home page -- Indicators with targets, Indicators with results, Results with evidence.

Here's a program that has 100% of targets set up. Yay!
![image](https://user-images.githubusercontent.com/33670923/52687833-7d4db800-2f08-11e9-9ae5-aacddc73beaa.png)

Hovering over it invites me to click on it. But there's no communication of what clicking on it will accomplish. Here's what actually happens:
![image](https://user-images.githubusercontent.com/33670923/52687878-a5d5b200-2f08-11e9-9bf9-6e7ab4368137.png)

We intentionally hid the "Add missing ____" filter link because it's not a meaningful filter when the gauge is set to 100%. 

Proposed: When the gauge reaches 100%, we disable the "click gauge to filter" function.

**Comment by RickieT** [comment]
**QA Verified**
* Highlight disappears when hovering over gauges with 100%
* Filter does not occur when clicking anywhere within the 100% gauge sections on the Program Page, or Home Page. 
![image](https://user-images.githubusercontent.com/23220180/52879694-acd11000-3114-11e9-9b81-5bcb912b80f3.png)

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.
