### ISSUE TITLE
Update Translations

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1183]
Here are a few strings that seem like they should be checked:

- "\# / %"
- "Before adding indicators and performance results, we need to know your program's"
- "Showing rows %(fromCount)s to %(toCount)s of %(totalCount)s"
- check capitalization of 'LOP target' in Spanish (and French?).  It is translated as Objetivo LOP in Spanish and I'm not sure the capitalization is appropriate in some places.
- Check that link works after "Before adding indicators and performance results, we need to know your program's"
- %s%s unavailable:  this is the x% unavailable on the program page, needs to be checked for translation and to make sure there aren't two percent signs.

**Comment by RickieT** [comment]
*QA Verified*:
* I did some poking in spanish/french and didn't see anything out of the ordinary, when looking through the suggested checklist.

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.

**Comment by sanjuroj** [comment]
Fixed in Hucklepatch
