### ISSUE TITLE
Possible to save multiple/duplicate results on result modal

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1184]
**Description:**
After saving a result, the modal does not close and provides a notification of the save, as changes appear on target chart. After saving a Result, I was left in the modal the results I had entered. If I clicked save again, this created a NEW result with the same information I had just created, a piggy back sort of off the above issue. 

**Steps to Reproduce:**
1. Login to Tola-Activity
2. Click Testing specific Program "TolaData Test"
3. Click an indicator on the list
4. Click "+ Add Results"
5. Add information to fields and required fields
6. Click Save Changes

**Results:**
Changes are saved, and result is added. If the user clicks save changes again, a duplicate of the same result is added.

**Expected Results:**
Results should not duplicate from the same result. 

**Attachments:**
![screen shot 2019-01-04 at 9 51 50 am](https://user-images.githubusercontent.com/23220180/50702663-6dd47880-1006-11e9-96ab-d57604222684.png)

**Comment by jennyhavah** [comment]
> **Expected Results:**
When Result is added, prompt user with successful save message, and close modal.

@sanjuroj @RickieT We have not yet made this design decision, and it should be tackled as a global pattern in a different ticket.

**Comment by camgnostic** [comment]
Disabled submit while submission is processing, and updated the result form target to "update" instead of "create" on successful save.

**Comment by camgnostic** [comment]
tagging @sanjuroj and @jennyhavah since this was hotly discussed today

**Comment by jennyhavah** [comment]
I see that this ticket was edited so that it no longer includes changes to the broader design patterns around saving changes, which is the part I was concerned about. 

Thumbs up on fixing the duplication issue.

**Comment by RickieT** [comment]
@camgnostic was there going to be an additional push to this branch for the false warnings on save?

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.

**Comment by sanjuroj** [comment]
Fixed in Hucklepatch
