### ISSUE TITLE
URI paths are not validated on Result modal

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1185]
In the Document creation/update form, the URI field contains some light validation to encourage users to use a network resource.  In changing the Evidence link to a field from a link to Document, the URI validation didn't get ported over.  

Expected behavior:  On the Result modal, in the Evidence section, the "Link to file or folder" field should have some light validation to encourage users to use networked resources, just as is currently in place with Document creation.  Issue #701 can be used as a guide to how this should behave (read all the way down to the bottom, one of the comments contains relevant information).

**Comment by camgnostic** [comment]
merged in from pr #1189 
on dev branch

**Comment by sanjuroj** [comment]
QA note:  URI validation should be same on Document creation and Result creation.

**Comment by RickieT** [comment]
Validation occurs ALMOST the same way:
The document form will perform validation in real time, before hitting the save button. In order to get the validation to occur on the result form, the user must first try and save the invalid address in the URL field, and then click save.
