### ISSUE TITLE
Indicator Performance Tracking Table (IPTT): Landing page with quick start options

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#119]
Story: I need an easy way to get started with my Target vs Actuals report that doesn't overwhelm me with its complexity.

**How I get here:** By selecting "Indicator Performance Tracking Table" in the Reports menu.

**Default state**
![emptystate](https://user-images.githubusercontent.com/33670923/39488952-d023fbc8-4d38-11e8-9631-b3f15d9be1f6.png)

**All fields complete -- Show all option selected**
(This mockup shows what both forms look like when they're completed. The user only needs to complete the form for the program type he or she wants.)
![alldata](https://user-images.githubusercontent.com/33670923/39488958-d2eaa596-4d38-11e8-9c53-0f76a16d2126.png)

**All fields complete -- Relative time option selected**
(This mockup shows what both forms look like when they're completed. The user only needs to complete the form for the program type he or she wants.)
![relativetime](https://user-images.githubusercontent.com/33670923/39488975-e1753e5a-4d38-11e8-8dc5-785c4ef8d0f7.png)

**ACCEPTANCE CRITERIA**
1. The page name is **Indicator Performance Tracking Table**.
2. There are two side-by-side sections: "Program impact overview" and "Periodic target overview"
3. For whichever report type you choose, all fields must be complete before the _View report_ button becomes active.

**Program impact overview**
1. The description says, "View progress toward Life of Program targets for all of a program’s indicators."
2. Options for _Time periods_ are:
2.1. Years
2.2. Semi-annual periods
2.3. Tri-annual periods
2.4. Quarters
2.5. Months
![image](https://user-images.githubusercontent.com/33670923/38398192-e2f04a96-38f6-11e8-8fa9-06025e76c9f5.png)
3. The default selection under Time Periods is "Show all"
4. The _View report_ button is inactive until all form fields are complete.
4.1. A program is selected.
4.2. A time period option is chosen.
4.3. Show all or "Most recent" is selected.
4.4. If "Most recent" is chosen, there is a number in the numeric field.
4.4.1. If the user enters a larger number of periods than there is data available, we just show all available data going back to the first data record submitted for the program.
5. Clicking _View report_ generates the report with sliding filter panel open. 
5.1. in the filter panel, _Program_ and _Time periods_ fields are automatically filled in.
5.2. Additionally, the _Time Span_ fields are automatically populated.
5.2.1. If _Show all_ is selected, we show the date range for all available periods.
5.2.2. If _Most recent_ is selected, we show the date range for the last _n_ periods.
5.2.3. This is captured in a different story, but just for reference: Calendar dates will always be the first day of a month and the last day of a month. We will not permit users to only show a partial amount of data within any given period. The calendar pickers will behave similarly to the one in the Targets tab that only permits you to pick entire months, not dates.

**Periodic impact assessment**
The description says, "View progress toward a program’s periodic targets in addition to Life of Program targets."

The basic interactions are quite similar to that of _Program Indicator Overview_, but there are some important differences that I will highlight.
1. We have a _Target periods_ label instead of a _Time periods_ label.
2. The target period options are:
2.1. Life of Program (LoP) only
2.2. Midline and endline
2.3. Years
2.4. Semi-annual periods
2.5. Tri-annual periods
2.6. Quarters
2.7. Months
2.8. Events
![image](https://user-images.githubusercontent.com/33670923/38398146-968f8c5c-38f6-11e8-80fd-f24ff17e60f5.png)
3. If I pick _Life of Program (LoP) only_, _Midline and Endline_, or Events, then:
3.1. "Show all" is automatically selected.
3.2. "Most recent" toggle option and numeric field are disabled.

**Comment by kurtwall** [comment]
> With the exception of Custom, the Start/End date pickers are automatically populated based on time span selected. You can start by picking one of the relative options and then adjust Start and End pickers you like, whereupon the "Time span" menu automatically switches to "Custom"

Making sure I understand: If I select a time span from the dropdown, the date pickers populate automatically to match the time span. If I then change the start or end date, the time span selected in the dropdown changes to Custom.

Edge case: Leave the time span at its default, that is, untouched, then use one or both of the date pickers to set "custom" start and end dates that just coincidentally match one of the time spans in the dropdown. Is that still a custom time span and displayed as such in the dropdown?

**Comment by jennyhavah** [comment]
@kurtwall I've significantly modified, and hopefully simplified, this interaction design. Take a look and see if it is clearer.

**Comment by kurtwall** [comment]
@jennyhavah Thanks!

**Comment by jennyhavah** [comment]
The name of the report on the right should be "Periodic target overview".

**Comment by jennyhavah** [comment]
Mahmood, can we please use the searchable version of the selection drop-down for Program? That list can get really long.

It's fine to leave the time/target period drop downs as is, because those lists are pretty short.

**Comment by jennyhavah** [comment]
Title of the right side report should be "Periodic target overview". (Right now it says Program target overview.)

**Comment by jennyhavah** [comment]
I have a number of UI issues I've captured in #239. The one UI issue I would like to have addressed before the demo, if possible, is: Implement the correct resting, active, and on-hover button states for the “View report” button. @sanjuroj knows what the appropriate states are.
