### ISSUE TITLE
Result form "Submitted by" field: My name appears as the submitter on all saved result forms

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1191]
To reproduce on QA, I open up any saved result form I did not submit myself.

I see this: 
![image](https://user-images.githubusercontent.com/33670923/52764836-7beac100-2fd6-11e9-801d-1825ce3782e5.png)

The intention of that field is to show who _originally submitted the result_. It appears, instead to be showing who is _currently viewing/editing_ the result.

**Comment by jennyhavah** [comment]
Tagging @hannalcamp and @axoplasm as this is tied to Partner Access:

I want to validate my assumption that we always want to show the _original submitter_ of the form, and use the change logs to track edits beyond the original submission.

**Comment by axoplasm** [comment]
Ooh that's terrible. Excellent catch.

We could just get rid of this item all together for the moment. It's not terribly useful until we have Partner Access going anyway.

**Comment by camgnostic** [comment]
Yeah - that field doesn't connect to anything on the model.  It's not saving anything.  The "tracking who submitted" part of this was supposed to come from PA, but isn't there yet.  I think we should hide the field for now.

**Comment by sanjuroj** [comment]
I removed the field on dev branch with #1193.

**Comment by jennyhavah** [comment]
Closing this ticket, because we removed the field and it will be tackled once Partner Access is in place.
