### ISSUE TITLE
Result form: Add missing period at the end of the Result date tooltip message.

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1192]
Tiniest ticket ever. Please add a period after the word "appear" at the end of the Result date tooltip.

![image](https://user-images.githubusercontent.com/33670923/52767318-ff101500-2fde-11e9-8660-7d857e7d6ea8.png)

**Comment by RickieT** [comment]
**QA Verified:**
Period is there now:
![image](https://user-images.githubusercontent.com/23220180/52881690-215a7d80-311a-11e9-9939-45bee6216f14.png)

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.
