### ISSUE TITLE
Hide "Submitted by" field in Result modal until partner access release

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1193]
The "Submitted by" field on the result modal just displays the current user, rather than the person who actually entered the data.  This could be confusing and really isn't useful until partner access anyway, so let's hide or remove the field for now.

**Comment by RickieT** [comment]
**QA Verified**
* Submitted by Field is no longer visible on the result form: 
![screen shot 2019-02-14 at 9 13 50 am](https://user-images.githubusercontent.com/23220180/52804339-da488b80-3038-11e9-8531-648bd66fa4bd.png)
