### ISSUE TITLE
Opening empty Result form is slow as heck

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#1199]
When I click "Add result" on the program page to open an empty result form, the network request is consistently taking around 1.5 seconds running locally on my laptop. This happens consistently and seems to have started recently.

Example URL: http://localhost:8000/indicators/result_add/585/5953/?modal=1

<img width="1552" alt="screen shot 2019-02-14 at 4 00 24 pm" src="https://user-images.githubusercontent.com/1278224/52825465-ad649a80-3071-11e9-8de3-839c70b7639d.png">

I'm seeing this happen on production as well with huckleberry pushed.

**Comment by sanjuroj** [comment]
My money is on the Sites query.

**Comment by KennyMonster** [comment]
Part of the fix here is to change how the Sites field is populated in the results form.

For the Sites field on the Results form, Cameron had the good idea of only listing sites associated with countries, which are associated with the program of the indicator a result is going to be attached to.

Before, the dropdown would list all sites associated with all countries the current user has access to.

This change gave a massive speedup if the user is associated with all countries.

**Comment by RickieT** [comment]
*QA Verified:* 

Opening result forms empty/not empty seem to be pretty quick, at least on my machine. Less than a second in most cases

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.
