### ISSUE TITLE
500 Error when I click on Google+ link in stakeholder or contact form

### ISSUE THREAD

**Issue by esinn** [mercycorps/TolaActivity#12]
When I'm in a stakeholder or contact form and i click on the Google+ icon on the bottom left I receive the Jordan 500 error message. Consider deleting/removing this icon as I have no idea what it's supposed to do. 
https://tola-activity.mercycorps.org/complete/google-oauth2/?state=V2Ks3Fg8KgwViVeMY8fyKdSzOcU18dc7&code=4/4v7B2ub9afvP-5yFzc447mhylCZ2j6Zi9KZ1TGPHtf4&authuser=0&hd=mercycorps.org&session_state=2ea29e0d1ff0465c9f3ab6eb43b0e7800c97117c..93e2&prompt=none#

**Comment by mahmoodkhan** [comment]
This link should not be there since we have not yet migrated to Google authentication. I will remove it.
