### ISSUE TITLE
Indicator Performance Tracking Table (IPTT): Filter slide out panel

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#120]
**Program Indicator Overview IPTT with filters**
![ipttprogramoverviewfiltersopen](https://user-images.githubusercontent.com/33670923/39612768-0ac38962-4f17-11e8-81fd-27f9afb05f9b.png)

**Periodic Target Overview IPTT with filters**
![ipttperiodictargetoverviewfiltersopen](https://user-images.githubusercontent.com/33670923/39612772-11dd161e-4f17-11e8-89e0-78d00de9c6f3.png)

**VISIBILITY OF FILTERS**
1. When you create your report on the IPTT landing page as described in ticket #119, and click "View report", you land on the report with the filter panel already open.
2. Just a heads up: There may be other links to the IPTT report in the future where we do not want to automatically expose the filter panel.
3. You can open and close the filter panel using a gear button near the report title. The icon used is the gear icon from FontAwesome.
![image](https://user-images.githubusercontent.com/33670923/39612825-80ac4452-4f17-11e8-9de9-b305d8d94579.png)

**FILTERS**

The filter panels look nearly identical, whether you're building the **Program Indicator Overview** or **Target Period Overview** variation of the IPTT report. The only difference is in how you define units of time. These interactions mimic the interactions described in ticket #119, in terms of what your options are and what options are active or disabled at any given moment.

![image](https://user-images.githubusercontent.com/33670923/39612899-368ccd46-4f18-11e8-9e61-1038f100eb39.png)

**Interaction details**
We would like to use a new multi-select widget. Details moved to a separate story: #248. 

_**Unless otherwise indicated below, all filters are multi-select.**_

All filter menus in the light gray area should default to "All (whatever)". All sectors, All sites, All levels, etc.

**Filter list**
1. Program (SINGLE-SELECT)
2. Time periods / Target periods (SINGLE-SELECT)
2.1. Show all / Most recent (TOGGLE)
2.2. Most recent (NUMERIC FIELD)
3. Start / End dates
3.1. These are automatically filled in based on what you've selected in the IPTT landing page. From there, you can adjust the start and end months to customize your date range. 
3.2. The year drop-down menu should only include years from the program's reporting period. See #227 for an overview of how we are defining a program's reporting start and end months.)
3.3. The month drop-down only include months from the program's reporting period.
3.4. The calendar picker widget should be similar in behavior to the "first target period begins" widget in the Targets tab. That is, you cannot pick dates, only months. But the system automatically converts your selection into a date. _Start_ will always be the first day of a month. _End_ will always be the last day of a month.
3.5. If you manually adjust a start or end month, both radio options (Show all and Most recent) are automatically de-selected and any number entered in "Most recent" is removed. This gives you visual feedback that you have customized your date range. You can then re-select "Show all" or "Most recent" if you wish to return to these generic options.
3.5.1. If you manually adjust the start month to be earlier than the program's reporting start month or the end month to be later than the program's reporting end month, the system does not prompt the user with an error message. Instead, the report is generated with all available program data. The start month is automatically reset to the program's reporting start month and/or the end month is automatically reset to the program's reporting end month.
4. **Level:** These options map to options on the Indicator modal's _Performance_ tab, plus _All levels_, which is the first and default option.
- All levels
- Goal
- Impact
- Outcome
- Intermediate Outcome
- Output
- Activity
5. **Type:** These options map to options on the Indicator modal's _Performance_ tab, plus _All types_, which is the first and default option.
6. **Sector:** These options map to options on the Indicator modal's _Summary_ tab, plus _All sectors_, which is the first and default option.
7. **Site**: Only show sites from the country/countries associated with the currently selected program. Default option is _All sites_.
8. **Select indicators**: This is the filter that allows you to fine tune, very precisely, the indicators you want to include in the report.
8.1. Ideally we show the indicator number (when available) followed by the indicator name, for easier searching and scanning. So if an indicator has the name 1.1.1. and the name "Number of people trained", it would appear in this menu as "1.1.1. Number of people trained" and you could type in 1 or "Number" to get type-ahead results.
8.2. Default is _All indicators_.
8.3. Selections in this filter are responsive to other filters. For example, if you filter on the level Outcome, any indicators not at that level would automatically be unchecked. 
8.3.1. You can always manually add (check) an indicator that was otherwise filtered out.
8.3.2. You can always manually remove (uncheck) an indicator that would otherwise be included in the list.

**Apply button**
Clicking _Apply_ reloads the IPTT report with updated indicators and data based on your filter parameters.

**Reset button**
Clicking _Reset_ sets the filters back to the way they were the last time you saved changes.

**Comment by kurtwall** [comment]
> 7.1. This will be more useful if we can somehow constrain the list to sites for which there is data.
Seems like managers might find it useful to be able to identify sites which have no data, but perhaps this isn't the report for that.

**Comment by jennyhavah** [comment]
You're right, @kurtwall! I took that out.

**Comment by Daniel-Avila** [comment]
@jennyhavah There are a few definitions such as Level where it is defined as "Same options as ..." but there is no link to those values. 

Could you link to them here so I can find them? Hunting through other tickets is a little tricky. :)

**Comment by jennyhavah** [comment]
Hi @Daniel-Avila -- the "same options as" refers to a multi-tab indicator details form that you get to by going to Indicators, clicking on of the green "# Indicators" buttons, and clicking an Indicator name. There are tabs called Summary, Performance, Targets, etc.

**Comment by jennyhavah** [comment]
@Daniel-Avila I updated the story with the current available options for level, type, and sector. (Just for reference, not intended as a substitute for pulling directly from the database.)

**Comment by jennyhavah** [comment]
> Site: Only show sites from the country/countries associated with the currently selected program. Default option is All sites.

Let's extend this behavior to the following filters:
- [ ] Level
- [ ] Type
- [ ] Sector
