### ISSUE TITLE
Improve URI validation on Result modal for the Evidence link field

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1204]
On the result form modal, there is some validation on the evidence link URI to ensure it is a valid web address.  The View button to the right of the field is linked to this status, it will only show for valid addresses.  Currently, the warning about a bad web address or a local file only appears once you save the Result.  The goal is to have the warning appear earlier, but not have it appear immediately once you start typing.  

In addition, if a "bad" link was submitted earlier, and you reopen the modal, the warning doesn't appear at first.  Again, it only appears if you try to save the result. 

Two things should be done for this ticket

- Change how the warning message is triggered so it shows up upon the mouse leaving the field.  One way to do this would be to attach an onblur to the link field and have it check  the status of the view button.  
- Display the warning, if appropriate, when the modal is opened.

**Comment by RickieT** [comment]
*QA Verified:*
* I can see the validation happening in real time now, when opening and when attempting to put invalid URL's in the field.

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.
