### ISSUE TITLE
Remove access to entire Browse menu

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1205]
UPDATE: We can hide the entire Browse menu as part of LevelUp -- see comments.

# Acceptance criteria

- [x] 1. I no longer see a Browse menu under any circumstances. Doesn't matter what my role is -- User, Basic Admin, Super Admin, what programs I have access to, or whether or not my country has access to Projects. (That last variable should be a moot point after Intercision.)

---

Original ticket

> As part of Huckleberry, two fields were added to each Result (link and name) and the use of Documents as Result evidence was discontinued.  The existing links between Results and Documents were preserved in the database, but no new associations will be made between Results and Documents.  Also as part of Huckleberry, an indicator filter was added to the Documents page, probably in response to an early design decision to continue using Documents for Result evidence.  
> 
> The Documents page is now a little bit confusing for users.  If an indicator has Documents that served as Result evidence prior to Huckleberry, those documents will still be visible on the Documents page, however, any new evidence will not be listed there.  Users might expect to be able to filter their Documents by indicator and get a complete list of evidence, but that list will be only partially complete.  
> 
> Here are a few obvious (partially non-exclusive) ways that we could handle this, as a way to get the conversation started:
> 1.  Put a note at the top of the page reminding users that the Document page is no longer a good way to get a list of all evidence associated with an indicator or program.
> 2.  Eliminate the Indicator filter so the legacy link between Indicators and Documents is less obvious.
> 3.  Create an expand all button on the program page that opens up all of the indicators, which would allow users to see all of the evidence links on a single page.  
> 
> @axoplasm and @jennyhavah, in consultation with others, will need to design a path forward.

**Comment by axoplasm** [comment]
The current proposal is that we hide “Documents” and/or “Documentation” in the same way we do for “Projects.” i.e. show it only Afghanistan

**Comment by jennyhavah** [comment]
Sanjuro is going to start a thread to run this solution by Hanna, Marie and others.

**Comment by sanjuroj** [comment]
@jennyhavah Now that we have hidden Documents, can we close this ticket?

**Comment by jennyhavah** [comment]
Capturing our Huckleberry Huddle: Our preferred solution is to hide the Browse Documents page as part of LevelUp. (Afghanistan will still be able to access their project related documents via Intercision.) This means that there will be no way for programs to create or browse documents in TolaActivity, going forward.

Sanjuro ran a query on documents created after the Huckleberry release that are not linked to Projects, that would be affected by this change. It appears as though many of them are duplicates of evidence links, and therefore no loss to the team if we hide them. I'm going to share the list with Marie and get her sign off on hiding Documents as part of LevelUp.

**Comment by jennyhavah** [comment]
Marie agrees that it makes sense to remove Documents from the Browse menu... which means the only remaining item would be Sites. It seems unfortunate to devote an entire top level Browse menu to a single option... that is buggy to boot.

Idea: Replace Country menu above the country map with a link to Browse sites and eliminate the top nav Browse menu entirely... Removing Country menu is proposed in #1952. I will run this by Marie and, if she agrees, update THAT ticket and move it into LevelUp along with this one.

**Comment by jennyhavah** [comment]
Marie has approved this approach. Updated the original ticket to remove entire Browse menu. Will update 1952 to move Site browse above the country map.

**Comment by jennyhavah** [comment]
Browse menu is gone! 🔥
