### ISSUE TITLE
Indicator Performance Tracking Table (IPTT) Layouts

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#121]
There are two variations of the Indicator Performance Tracking Table (IPTT): _Program Indicator Overview_ and _Periodic Target Overview_. Which report gets created depends on choices made on the IPTT landing page. (See #119).

## Above the table
1. We always display the date range from the start date of the first time/target period needed to the end date of the last time/target period needed. (Periods will always start at the beginning of a month and end at the end of a month.)
2. We always display the program name.

## IPTT -- Program Indicator Overview
![ipttprogramindicatoroverview](https://user-images.githubusercontent.com/33670923/40035828-897cff96-57b8-11e8-8103-b9c268d71399.png)

This table organizes data by unit of time, and can show any combination of program indicators, regardless of their target frequencies. Note that with the exception of Life of Program, we only display Actuals -- no target or % met.

**Sorting**: The indicators should be sorted by Level, then Number, then Name. 

## IPTT -- Periodic Target Overview
![ipttperiodictargetoverview](https://user-images.githubusercontent.com/33670923/40035837-8fb0742e-57b8-11e8-9daa-6ed2badf4a66.png)

This table organizes data by periodic target. It can only show indicators with one target frequency at a time. 

**Sorting:** The order of single-indicator tables should use the same sorting defaults as the Program Indicator Overview report: Level, then Number, then Name. 

## Table column headers and contents
1. **NO.** -- Indicator number (if entered)
1.1. Links to Indicators page open to that indicator with data/evidence table exposed (link not included in exports)
2. **INDICATOR**
2.1. Indicator name -- links to Indicators page open to that indicator with data/evidence table exposed (link not included in exports)
3. **Gear icon** -- Pops open indicator configuration modal. (Icon not included in exports.)
4. **LEVEL**
5. **UNIT OF MEASURE**
6. **CHANGE** -- N/A, + or -
7. **C / NC** -- Cumulative or Non-cumulative
8. **BASELINE** -- Baseline value or N/A
9. **LIFE OF PROGRAM**
9.1. Target
9.2. Actual
9.3. % Met
9. **PERIOD DATA** (Quarter 1, Semi-annual period 2, Midline, etc.)
10.1. Target (Only in Periodic Target Overview report)
10.2. Actual (Both types of reports)
10.3. % Met (Only in Periodic Target Overview report)

## UI detail
If it's not difficult to do, an on-hover row highlight color helps the eye travel across the table. The highlight color is #CCEFEE

**Comment by mahmoodkhan** [comment]
@jennyhavah based on our conversation earlier today, I am not going to be developing the "EVENT-BASED" targets report and will take out that option from the dropdown.

**Comment by jennyhavah** [comment]
For LoP indicators, can we display the phrase "Not applicable" in the C/NC column? It came across like there was missing data, when it's simply that we don't currently offer any C/NC choices for LoP target.

**Comment by jennyhavah** [comment]
> Sorting: The order of single-indicator tables should use the same sorting defaults as the Program Indicator Overview report: Level, then Number, then Name.

Doesn't appear to be implemented yet. The default sorting order is very important. (This is independent of any manual sorting which is in a different story.)

**Comment by jennyhavah** [comment]
Change "Actuals" plural to "Actual" in the data column headers.

**Comment by jennyhavah** [comment]
> INDICATOR
2.1. Indicator name -- links to Indicators page open to that indicator with data/evidence table exposed (link not included in exports)

Not done yet. Is this easy or hard?

**Comment by jennyhavah** [comment]
Please make the following UI tweaks in time for the demo. (It needs a lot of polishing, but the following items will make it look a lot less busy and broken up.)

1. The page title is not supposed to be on top of the filter panel, pushing it down. See the mockup: It is positioned above the date range.
2. Please change the background color of the page to #F5F5F5.
3. Please change the header row colors to #F5F5F5.
4. Please change the Life of Program columns to #F5F5F5.

**Comment by jennyhavah** [comment]
When a baseline is marked N/A, then an "N/A" should show up in the Baseline column of the IPTT.

**Comment by mahmoodkhan** [comment]
The title that shows up underneath the table is the "table caption" and used by screen readers.

**Comment by jennyhavah** [comment]
That's fine. I noted the page title issue in a ticket Paul will work on.

**Comment by jennyhavah** [comment]
I see the updated order in the IPTT table rows, but not the other places I mentioned. My top priority is to make the order of options in the filter panel consistent with that of the table itself.

If you like, I can move the other places to a separate ticket.

**Comment by mahmoodkhan** [comment]
Let's create another story for updating the level order in other places. This issue is getting too long. I updated the level sorting issue in the IPTT table as well as in the filter form.

**Comment by jennyhavah** [comment]
New ticket created to capture remaining level-related work: #296
