### ISSUE TITLE
Results: UI updates to support disaggregation entry

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1214]
# Stories

1. When I'm disaggregating a result in multiple ways (parallel disaggregations), it's easy for me to enter the correct values into the correct disaggregation types.

2. When I'm disaggregating a result for a **_number indicator_**, the system prevents me from submitting disaggregated values whose sum does not match the total actual value.

# Background context 

Here's how we display disaggregation options today on the Result form:

![image](https://user-images.githubusercontent.com/33670923/64738620-8d307900-d4a4-11e9-9536-34df670b5248.png)

1. There are two types of disaggregation in the Django database: Standard and Custom. These labels are vague and imprecise. Going forward, we'll use the terms "Global" (instead of Standard) and "Country" (instead of Custom). Global disaggregations are administered in Django admin, by Super Admins only. Country disaggregations are managed by Basic Admins in the Countries section of Admin Lite.

2. Today, if you want to disaggregate by multiple Custom disaggregations, you're in trouble -- all categories are mushed together into a single "Custom" list, for no apparent reason; this renders them unusable for data entry purposes, and it may have implications for calculations as well. In the screenshot above, you're seeing a blend of geographic and nationality based options.

# Acceptance criteria

## Interactions

- [x] 1. Each disaggregation type is displayed as a discrete expandable/collapsable list. 

- [x] 2. When there are multiple disaggregations, they are listed in alphabetical order. 

     - [x] 2.1. For ordering purposes, we can ignore whether the disaggregations are Global (such as SADD) or Country level. We do _not_ need to label and cluster them the way we do in the indicator setup form. (This would be overkill, as it is relatively rare for indicators to be disaggregated multiple ways.)<P>

- [x] 3. Please replace the table header "Disaggregation level" with "Disaggregation" and "Actuals" with "Actual value".

## Entering results for NUMBER indicators

- [x] 0. Disaggregated value fields are _numeric_. 

     - [x] 0.1. I should not be able to type any letters. (Right now I can type the letter "e" which is not the case in other number fields.)

     - [x] 0.2. I should not be able to enter special characters, including negative and positive signs. (We do not permit negative LoP values, so this needs to carry over to disaggregated values.) Currently I can enter both, and it saves the negative signs.

- [x] 1. When you expand a disaggregation type, we include a Sum and Actual value row, like so:

     ![image](https://user-images.githubusercontent.com/33670923/61325865-759d8280-a7ca-11e9-997a-e978a952fea4.png)

- [x] 2. When an actual value field is entered, it is mirrored in the Actual value row. _Note: It is not necessary to enter the actual value prior to entering disaggregated values, as long as it's completed prior to submission._

- [x] 3. As I enter disaggregated values, the Sum row automatically updates, like so:

     ![image](https://user-images.githubusercontent.com/33670923/61324869-4259f400-a7c8-11e9-85c0-b5fe83ed8528.png)

- [x] 4. Until I submit the form, I see no warning messages when the sum does not match the actual value. (Don't want to be overly aggro and imply there's something wrong the entire time you're entering data.) But when I submit, the system checks the sum against the actual value. If they do not match, the following things happen:

     - [x] 4.1. **Collapsed disaggregation:** I see a warning symbol and the phrase "Needs attention", like so:

     ![image](https://user-images.githubusercontent.com/33670923/61325249-2145d300-a7c9-11e9-8311-11a6d79d648b.png)

     - [ ] 4.2. **Expanded disaggregation:**

     ![image](https://user-images.githubusercontent.com/33670923/61325956-ae3d5c00-a7ca-11e9-8dd9-62941d46bb4b.png)

     - [x] 4.2.1. I see the standard warning message in red text, left-aligned under the table: The sum of disaggregated values does not match the actual value.

     - [x] 4.2.2. The sum is highlighted with a red fill background, with red text to the left, displaying how much over or under you are. As I update my disaggregated values, the sum immediately updates, as does the red warning text, if the sum is still not equal to the actual value. (At this point, we DO want to warn you immediately and help you correct the situation, rather than waiting for you to submit again to tell you that you're still wrong.)

     - [x] 4.2.3. There is an "Update actual value" button with a "sync" symbol, near the sum. Clicking on it updates the actual value row immediately below, in addition to updating the number entered in the actual value form field.

     - [x] 4.2.4.  As soon as the two values match, all warning messages and highlighting go away, along with the "Update actual value" button.

_Jenny's note to self: See comments about validation messaging and QA those too._

## Entering results for Percentage indicators

- [x] 1. For percentage indicators, a percent sign appears in every value field, similar to what we do in the indicator form's target table.

     ![image](https://user-images.githubusercontent.com/33670923/61324587-a6c88380-a7c7-11e9-938a-4911624370fb.png)

- [x] 2. For percentage indicators we DO include an Actual row, that reflects whatever is in the Actual value field -- helpful to have it in both places when the list of disaggregation categories is long. But we do NOT include a Sum row, because it doesn't make sense -- just as we don't sum our percentage targets. (Note: In the future, we may introduce a type of % indicator that involves entering separate numerators and denominators, allowing us to automatically calculate _average_ % targets and average % results.)

## Regression checks

- [x] 1. Roles/permissions criteria 

     - [x] 1.1. **Low access user:** I can only _view_ disaggregated data. All form fields and buttons ("update actual value", etc. are hidden or disabled.

     - [x] 1.2. **Medium and high access users:** I can view and edit disaggregated results.

- [x] 2. All validation, confirmation and rationale prompts are preserved and behave as expected. Note: For saved results, we do not need any _new_ rationale prompts specific to disaggregated values. We do need to make sure that if you open up a saved result and add/edit/clear any disaggregated value fields, we bring up the existing prompt for rationale... 

     - [x] 2.1. I get the prompt when I edit disaggregated values, _even if the total actual value remains the same._

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah We also talked about renaming the SADD disaggregation to make it clear that it's the MC standard, just in case there is some other Sex and Age disaggregation that is required by a donor.

**Comment by jennyhavah** [comment]
> We also talked about renaming the SADD disaggregation to make it clear that it's the MC standard, just in case there is some other Sex and Age disaggregation that is required by a donor.

@sanjuroj I think this goes beyond naming the one Global type we happen to have today to a broader issue of "How do we express the levels of disaggregation?" 

Captured in Acceptance criteria #3 -- requires some visual exploration.

**Comment by axoplasm** [comment]
> How do we communicate the levels of disaggregation without making the result form even longer and busier than it already is? Can we avoid two levels of collapse/expand rows, or is that the only way to keep things compact?

@jennyhavah I hadn’t even explored separating these levels on the results form itself. It might be overkill. How often does an indicator have more than two or three disaggregations?

**Comment by jennyhavah** [comment]
@axoplasm My understanding from Emily is that an indicator does not often have multiple disaggregations selected. So it is definitely overkill to have any sort of multi-level accordion or even nested headers.

I crossed out the third acceptance criteria. If there are multiple disaggregations, they can all be in a single flat list.

**Comment by camgnostic** [comment]
Large ticket to the point of difficult to estimate.  Tagged "HIGH" - at least.  The input changes, disaggregation label option changes, and the summing logic are three separate large changes.

**Comment by jennyhavah** [comment]
@camgnostic Heads up that I added a third criteria to the "Interactions" section -- some text changes within the table header.

**Comment by jennyhavah** [comment]
From Slack:

> quick question - you have (in ticket #1214) the details for how to handle values that don’t add up to the achieved value, but not the language for the feedback when a value is, say, negative or words or some other wackiness.  What should this say?

Let's use this message for both the total actual and disaggregated actual values:

Please enter a number greater than zero.

While we're thinking about this, let's make the _**indicator targets**_ error messaging more consistent.

1. **Baseline:** Right now it's a little weird. If you type -5, it says "Please complete this field. Your baseline can be zero." (Weird because you have completed it, it's just not valid.) 

     Regardless of whether you've left it blank or typed a value less than zero, let's say: Please enter a number greater than or equal to zero. 

     I want to emphasize that baseline CAN be zero! We don't want to change that.

     Please also update the formatting to match what we're using elsewhere -- looks like it's larger and possibly a different shade of red though I can't say for sure because it's on a different background.

2. **Life of program target:** Please enter a number greater than zero. (Right now it says "larger". Just being hyper-consistent.)

3. **Any other target:** Please enter a number greater than zero.

**Comment by jennyhavah** [comment]
The expando caret is missing when I first open the Add result form or open a saved result to edit it.

![image](https://user-images.githubusercontent.com/33670923/71493443-92b39400-27f3-11ea-9d0f-a811b9a9c1de.png)

After I open it the first time, I see it:

![image](https://user-images.githubusercontent.com/33670923/71493448-9ba46580-27f3-11ea-917c-d5ff28bc169b.png)

It needs to look like the above when I first open it.

**Comment by jennyhavah** [comment]
I am able to type letters and symbols into the numeric value fields:

![image](https://user-images.githubusercontent.com/33670923/71493541-5b91b280-27f4-11ea-9972-823de09bd9fc.png)

I remember we discussed changes to how we handle validation, to better handle translation, but I assumed we could still prevent people from entering invalid characters in most cases. Did I misunderstand?

Looks like the total Actual value field behaves differently from the disaggregated values. Seems like whatever we decide, we should treat them all the same way.

My ideal is that: We prevent people from entering non-numeric characters except for those that make sense for the language in question -- commas for French, etc.

**Comment by jennyhavah** [comment]
The actual value field is turning transparent when I click into it. It should remain white.

![image](https://user-images.githubusercontent.com/33670923/71493640-28035800-27f5-11ea-95a5-46000a327852.png)

**Comment by jennyhavah** [comment]
All rows except for the Actual Value row should be white. Actual Value should always be the darker shade of gray.

Here's what I see -- alternating gray stripes that seem to ignore what type of row it is.

![image](https://user-images.githubusercontent.com/33670923/71493722-e1fac400-27f5-11ea-80db-89e207516868.png)

versus my mockup:

![image](https://user-images.githubusercontent.com/33670923/71493695-a52ecd00-27f5-11ea-93c4-6dbb00232580.png)

**Comment by jennyhavah** [comment]
Please add a space between the symbol and the first letter:

![image](https://user-images.githubusercontent.com/33670923/71493776-4ae23c00-27f6-11ea-8955-83020e1ddd02.png)

**Comment by jennyhavah** [comment]
When the total disaggregated value is _greater than_ the total actual value, let's put a + sign in front of the overage number. So here, it'd say +3.

![image](https://user-images.githubusercontent.com/33670923/71493850-305c9280-27f7-11ea-8001-48117b1c1a5c.png)

(Without that symbol, I find there's a question in my mind as to whether I'm replacing the total actual value with 3 or 33.)

**Comment by jennyhavah** [comment]
The vertical spacing between sections needs some tweaking. 

![image](https://user-images.githubusercontent.com/33670923/71494114-6ef34c80-27f9-11ea-93ce-67d0c78beb28.png)

**Comment by jennyhavah** [comment]
Adjust spacing after percentage sign in disaggregated value fields.

![image](https://user-images.githubusercontent.com/33670923/71494149-ba0d5f80-27f9-11ea-9886-997512dc08e3.png)

**Comment by jennyhavah** [comment]
After I fill out a field and move on to the next, it has a green outline around it, instead of returning to the previous gray.

![image](https://user-images.githubusercontent.com/33670923/71494294-df4e9d80-27fa-11ea-8acf-be68ea8f84e4.png)

And when I'm being corrected, I'd expect the relevant fields to have a red outline. Instead, it's green.

![image](https://user-images.githubusercontent.com/33670923/71494299-e5dd1500-27fa-11ea-8ce7-2581414c2e0c.png)

**Comment by jennyhavah** [comment]
Right now, the numbers are not all right-aligned, and pink background highlighting extends the entire width of the number field, like this:

![image](https://user-images.githubusercontent.com/33670923/71494597-1faf1b00-27fd-11ea-8aed-23dd5a028530.png)

In Paul's original design for this, he has the pink highlighting behind the number only -- which really draws attention to the delta -- and the numbers are all right-aligned, like this:

![image](https://user-images.githubusercontent.com/33670923/71494434-1ffae680-27fc-11ea-9ea4-7e683053bbca.png)

**Comment by jennyhavah** [comment]
I'm sorry, I made a mistake in [this comment above](https://github.com/mercycorps/TolaActivity/issues/1214#issuecomment-568061189) when I requested this:

> Let's use this message for both the total actual and disaggregated actual values: Please enter a number greater than zero.

While you can't have a _target_ of zero, it is fine to have an actual result of zero.

Right now, it appears to be accepting zero for the total actual value, but for disaggregated values, we're disallowing it. We need to update disaggregated value fields as follows:

1. Accept a zero value -- for both percentage and number indicators.

2. Validation message for invalid entries should be: Please enter a number greater than or equal to zero.

**Comment by jennyhavah** [comment]
Looks like the following updates aren't implemented yet -- probably lost because they were in a comment instead of the original ticket. 

![image](https://user-images.githubusercontent.com/33670923/71495157-47a07d80-2801-11ea-9363-c333b10d9a54.png)

Here's a screenshot to show the difference in font size/maybe color? between the error messages under the baseline vs. the target fields:

![image](https://user-images.githubusercontent.com/33670923/71495065-ab767680-2800-11ea-8a93-f198eb189080.png)

**Comment by sanjuroj** [comment]
Another possible tweak:  when the disaggregation type is clicked on, it's active form has different color, a border, and an underline, which I'm assuming isn't what's desired?

The is when the modal loads
<img width="784" alt="Screen Shot 2019-12-30 at 3 39 54 PM" src="https://user-images.githubusercontent.com/6685499/71605012-b429be00-2b1a-11ea-9821-6862f2a7564e.png">

This is after clicking "Type of Leader"
<img width="784" alt="Screen Shot 2019-12-30 at 3 39 58 PM" src="https://user-images.githubusercontent.com/6685499/71605013-b855db80-2b1a-11ea-9c40-1e8fe501c6aa.png">

**Comment by jennyhavah** [comment]
@sanjuroj I agree that there isn't supposed to be a white fill or an underline.

I just asked Paul about the blue border, and he says it's a browser thing to make it more apparent what you're focused on when you use the keyboard (tab button) to move across the screen. He recommends leaving the border alone even though it doesn't look awesome.

But the other two things -- fill and underline -- can go. Basically, we can mimic the treatment of the expando-collapso on the Program page.

**Comment by sanjuroj** [comment]
Sounds fine.  If it's not weirdly difficult, It might be nice to put a little bit of padding between the disaggregation type text and right border of the highlighted "box".

**Comment by jennyhavah** [comment]
> Sounds fine. If it's not weirdly difficult, It might be nice to put a little bit of padding between the disaggregation type text and right border of the highlighted "box".

I agree -- looks like Paul managed to do this on the Program page. If you find an indicator of the right length, you'll notice that the string slightly wraps upon opening, so that there's always a space between the right edge and the border.

**Comment by camgnostic** [comment]
@jennyhavah can we move the updates to the indicator setup form to its own ticket since this one has already spiraled in complexity?

**Comment by jennyhavah** [comment]
@camgnostic Yep! Created #2082.

**Comment by jennyhavah** [comment]
1/16/2020 note: Any remaining styling work discussed in the above comments has been moved into separate tickets and assigned to Paul. 

The only thing remaining for Cameron to fix on this ticket is https://github.com/mercycorps/TolaActivity/issues/1214#issuecomment-569149946

**Comment by jennyhavah** [comment]
@camgnostic Still seeing some issues related to special characters and numeric fields. I created a new ticket for them so that I can pass this one. See #2125
