### ISSUE TITLE
Recent progress IPTT > Result table pop-up: Hide "Add targets" button when no targets are set up for the indicator

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1215]
**Affects:** Recent Progress version of the IPTT, when a program has an indicator with no targets set up. 

## To reproduce the issue
1. Find a program that has at least one indicator with no targets set up. One example is program 446.
2. Run a Recent Progress IPTT on the program.
3. Find the indicator with no targets and click the blue table icon at the left end of its row. You'll get this:

![image](https://user-images.githubusercontent.com/33670923/52891536-79a47600-3140-11e9-9cc5-2a50f97886bd.png)

The problem is that if you click "Add targets", you get bounced out of the report context to a full page version of the indicator setup form.

## Requested fix
Hide the "Add targets" button when no targets are set up. If someone wants to go ahead and set up targets for the indicator without leaving the IPTT report, they can click the gear icon to get the pop-up version of the form.

**Comment by RickieT** [comment]
**QA Verified:**
* issue no longer persists as written:
![image](https://user-images.githubusercontent.com/23220180/53274691-fab5bd00-36ac-11e9-8fc8-288fa1395820.png)
