### ISSUE TITLE
IPTT Recent Periods Report shows value for first period of cumulative indicator regardless of whether period has any results

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1218]
Hang on to your hats, this case is edge-tastic.

Prerequisites:
- Time-aware indicator (annual, semi-annual, tri-annual, quarterly, or monthly)
- Cumulative type
- Numeric type
- Has some results
- Has at least one period without results
- Timeperiods-based IPTT (not TvA)
- some number of most recent periods (not "show all")

In this case, the IPTT will display the current cumulative value in the first time period, even if that period has no results.  Expected behavior: '–' (to match indicator result table, a dash indicates "no results during this period") and the cumulative total to appear in the first column _for which results exist_.

**Comment by RickieT** [comment]
**QA Verified:**
Page verified: 
https://tola-activity-qa.mercycorps.org/indicators/iptt_report/542/timeperiods/?timeperiods=7&timeframe=2&numrecentperiods=2
Media Verifying:
![qa](https://user-images.githubusercontent.com/23220180/53125763-8c89c280-3513-11e9-88f3-b8d791718827.png)
![prod](https://user-images.githubusercontent.com/23220180/53125764-8c89c280-3513-11e9-907b-cf3f8062ec4f.png)

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.
