### ISSUE TITLE
Document browe: Remove indicator filter

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1221]
Indicator filter no longer makes sense as we are not attaching documents as evidence.

Solution: Remove indicator filter

![image](https://user-images.githubusercontent.com/33670923/53038369-6ab80f00-3431-11e9-8d1f-3d4513ab11f8.png)

**Comment by RickieT** [comment]
*QA Verified:*
Indicator search filter is not longer visible on the browse documents page:
![screen shot 2019-02-21 at 3 15 45 pm](https://user-images.githubusercontent.com/23220180/53208461-b1516900-35eb-11e9-8ba4-8fce369e3630.png)

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.
