### ISSUE TITLE
SPIKE - Google Drive Picker

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1222]
**Issue:**
Reports have come in that the picker for google drive within the result form is not ideal. For some users (many with shared documents/folders) can be viewed as convoluted and confusing. 

One solution discussed was to split the Drive between owned by me and shared, but was not decided on the final solution to this issue. 

**Spike:** 
Determine best solution for drive picker based on user/tola team feedback

**Solution:**
Close's this ticket when NEW Ticket with code fix is PR'd or close the ticket if no code is necessary or the issue will not be resolved, (move through normal process for tracking.)

**Comment by jennyhavah** [comment]
@RickieT Now that we've pushed Ken's improvements with the HucklePatch, can we close this ticket?

**Comment by RickieT** [comment]
@sanjuroj I believe this is resolved via ken's fix. We can open a new one if we get some feedback on this feature in the future.
