### ISSUE TITLE
Result form: Unexpected warning when I save a result without evidence

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1226]
## To reproduce the issue:

1. Click "Add a result" to any indicator.
2. Fill out all required fields but don't attach any evidence.
3. Click "Save changes"

Observed behavior:

1. I see a yellow "Result saved, however view the warnings below." First time I've seen this warning message, that I can recall.

![image](https://user-images.githubusercontent.com/33670923/53121941-35332480-350a-11e9-9d95-7b49cf2a49bf.png)

2. The warning is out of context -- it's the one you get when you try to attach a local file as evidence.

![image](https://user-images.githubusercontent.com/33670923/53121945-395f4200-350a-11e9-8c0c-6c1a36a297a9.png)

## Requested fixes
I actually like the yellow warning message, but we need to fix the in-line validation to fit the context and to use a 

- [ ] 1. Red box and text should have a "warning" (yellow) treatment instead of an invalid/can't submit (red) treatment.
- [ ] 2. Message under the "Link to file or folder" field can say: Please add evidence to your result.

**Comment by jennyhavah** [comment]
@axoplasm What do you think of my requested fixes? Do you like this pattern of having a warning without validation messaging, when it's not a field that actually blocks saving, but that you want to encourage completion of?

**Comment by axoplasm** [comment]
I like this solution but there's some UI/code handles to consider.

There is sort of a pattern for inline messages near the input. It should use the "warning" color space (yellow/orange).

Not sure if custom messages in the alert space (at the top of the modal) are easy or hard.

**Comment by jennyhavah** [comment]
@axoplasm A yellow-orange warning inline treatment makes sense, to go with the yellow warning at the top.

Updated the ticket to keep the generic message at the top, to use a warning (yellow/orange) instead of an invalid (red) in-line treatment and display a message that makes sense for the context.

**Comment by jennyhavah** [comment]
Turns out Ken fixed this. I'm closing the ticket. We need a separate ticket addressing the standardization of our warning message styling. I'll see if we already have this and, if not, file a new ticket.
