### ISSUE TITLE
Home page map: Right border is missing

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1231]
The right border is missing on the map:

![image](https://user-images.githubusercontent.com/33670923/53221148-f346d300-361c-11e9-81c4-f42f11efe2fa.png)

**Comment by axoplasm** [comment]
I'm only able to replicate this 1) on Chrome 2) when I zoom out to less than 90%. 

Can you try resetting to your usual zoom level and refreshing?

**Comment by jennyhavah** [comment]
@axoplasm You're right that the borders look fine at 100%. But... I suspect I'm not unusual in that I almost never have my laptop set to 100%.

I don't see this as high priority to fix. Moving to Fruit Basket.

**Comment by jennyhavah** [comment]
Closing this ticket because it's browser-driven behavior that likely would require silly hacks to address and that nobody else seems to have noticed but me. Also, if we ever invest in Sites again, it's highly likely we'll go with a entirely different library, rendering these kinds of visual details moot.
