### ISSUE TITLE
Residual translations

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1232]
There are a few translations that got missed in the last round.  These were Google Translated and need to be checked by professional translators. Mark as fuzzy before sending to translators.

**Spanish**
- Percentage (%%) indicators
- Only completed target periods are included in the “indicators on track” calculations.
- Last completed target period
- If an indicator only has a Life of Program (LoP) target, we calculate performance after the program end date.
- The actual value is 95% of the target value. An indicator is on track if the result is no less than 85%% of the target and no more than 115%% of the target. Remember to consider your direction of change when thinking about whether the indicator is on track.
- For midline/endline and event-based target periods, we begin tracking performance as soon as the first result is submitted.

**French**
- %(percentNonReporting)s% unavailable
- No active country
- Proceed anyway?
- Please select a target.
- Find
- Percentage (%%) indicators
- Only completed target periods are included in the “indicators on track” calculations.
- Last completed target period
- If an indicator only has a Life of Program (LoP) target, we calculate performance after the program end date.
- The actual value is 95% of the target value. An indicator is on track if the result is no less than 85%% of the target and no more than 115%% of the target. Remember to consider your direction of change when thinking about whether the indicator is on track.
- For midline/endline and event-based target periods, we begin tracking performance as soon as the first result is submitted.

**Comment by RickieT** [comment]
### QA Passed: 

I checked in as many places I could look through for translation errors in french and spanish:

Admin lite create user
Admin lite create country
Admin lite Create program
Admin lite create Organization

and across country country > Program page > indicator form > IPTT > change log > Results form
