### ISSUE TITLE
Program list is massive if user has access to a lot of programs/countries

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1234]
When you have access to multiple countries/programs, the list when browsing programs on the site page is pretty egregious:
![image](https://user-images.githubusercontent.com/23220180/53360310-0e9a3280-38ea-11e9-8067-a12136479eac.png)

**Comment by jennyhavah** [comment]
Moving this to Fruit Basket. Sites are very low priority for fixes, relative to other areas of the application.

**Comment by jennyhavah** [comment]
Closing because this isn't a bug so much as a "we need to rethink Sites entirely" type of issue, and we have no plans to work on sites anytime soon.
