### ISSUE TITLE
Sites > Indicator Data is not showing

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1241]
After a short investigation, the data is not showing, when it used to, currently looking like this: 
![screen shot 2019-02-28 at 10 36 26 am](https://user-images.githubusercontent.com/23220180/53589627-b90d9200-3b44-11e9-9617-06bf72f71c87.png)

**Comment by RickieT** [comment]
@sanjuroj I believe I tested this live on dev or qa - in either case, this was checked as good to go. I don't see this noted as a hotfix anywhere in the releases page of the project, so I'll set it here for now assuming this has not been put to production yet.

**Comment by sanjuroj** [comment]
Correct I haven't launched it yet.  Might add a few extra translations to the release.
