### ISSUE TITLE
Baseline* Required field should be hidden/grayed out when user selects "Not applicable"

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1242]
When the user checks the box for not applicable, I expect the input field to be disabled, and the baseline red asterisk " * " to disappear or fade, so that the selection I've made is more apparent. 

Current visual when checked:
![image](https://user-images.githubusercontent.com/23220180/53591611-4652e580-3b49-11e9-9983-1a6077eb4a9c.png)

When checked, I would expect the field to function/look to be similar to this field in the Summary Tab on indicator setup: 
![screen shot 2019-02-28 at 11 09 32 am](https://user-images.githubusercontent.com/23220180/53591678-65ea0e00-3b49-11e9-8bd2-96821e4f24b7.png)

**Comment by jennyhavah** [comment]
I don't recommend this design change. An inactive field implies that you cannot edit it without first unchecking the box. In fact, we intentionally designed it so that if you type in that box, you _can_ edit it. You don't have to first uncheck the box.

Closing and removing from Poblano.
