### ISSUE TITLE
Results framework: Templates are a thing (database)

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1247]
These are the preset Results Framework level templates we need to offer. Please note the consistent use of **Title Case**. (I've been pushing hard for sentence case in TolaActivity, except where title case is appropriate, which it is here.)

These templates are listed in alphabetical order by organization name.

# Acceptance criteria
- [x] 1. The templates with preset levels _are not customizable by the end user._  
     - [x] 1.1. The template name _should_ be translated.
     - [x] 1.2. The template levels _should_ be translated.

**Note:** We eventually plan to offer a custom template option, covered in ticket #1331. We need to ensure that our database model can support both translate-able presets and custom templates. (Today's indicator levels are not translate-able, and we don't want to repeat that mistake.)

-----
**Department for International Development (DFID)**
1. Impact
2. Outcome
3. Output
4. Input
-----
**European Commission (EC)**
1. Overall Objective
2. Specific Objective
3. Purpose
4. Result
5. Activity
-----
**Mercy Corps**
1. Goal
2. Outcome
3. Output
4. Activity
-----
**USAID 1**
1. Goal
2. Purpose
3. Sub-Purpose
4. Output
5. Input
-----
**USAID 2**
1. Strategic Objective
2. Intermediate Result
3. Sub-Intermediate Result
4. Output
5. Input
-----
**USAID FFP**
1. Goal
2. Purpose
3. Sub-Purpose
4. Intermediate Outcome
5. Output

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@sanjuroj I just realized I failed to update a criteria here, to match the most recent mockups. I'd like the Mercy Corps template to just be called "Mercy Corps". (At the moment it's called "Mercy Corps standard." 

We don't have a non-standard MC template, so the word "standard" is extraneous.

**Comment by sanjuroj** [comment]
Translation of level tiers should be working properly now.

**Comment by jennyhavah** [comment]
@sanjuroj Where's DFID?

**Comment by sanjuroj** [comment]
Huh, apparently in the wind.  I'll add.

**Comment by jennyhavah** [comment]
@sanjuroj  I see DFID now! And all templates appear to be translated in both French and Spanish in the RF builder

I find myself questioning the translation for "Input" is quite right, though. Wondering if that translated string was grabbed from another context, since you surely haven't sent it out for review by Daniel yet.

"Données" (current translation) is closer to "Data" in meaning, in the sense of data entry. I think in this context, "Contributions" (French word) or similar would be more accurate. Because the RF tier is not about inputting data. It's about the _work_ you contribute, to result in a particular output.

![image](https://user-images.githubusercontent.com/33670923/60905179-5ed6b900-a229-11e9-8c12-3da3e43baf4d.png)

Spanish translation of that template should probably also be reviewed. It's currently "entrada" which also seems to suggest data entry rather than activities contributing to an output.

Functionally speaking, this ticket is working as expected, so I am going to pass it.
