### ISSUE TITLE
Update straggler translations

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1249]
Update two late translations:

Warning: This may be a badly formatted web address. It should be something like \'https://domain.com/path/to/file\' or \'https://docs.google.com/spreadsheets/d/OIjwljwoihgIHOEies\'

Singular:  "Warning: This action cannot be undone. Removing this target means that %s data record will no longer have targets associated with it.\n\nProceed anyway?"
Plural: "Warning: This action cannot be undone. Removing this target means that %s data records will no longer have targets associated with them.\n\nProceed anyway?"

**Comment by sanjuroj** [comment]
Updated by #aa690d3

**Comment by RickieT** [comment]
Checked the messages here in french/english/spanish, didn't see anything out of what I would expect. I think this is ok
