### ISSUE TITLE
RF builder: Roles and permissions

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1252]
# Story
Only people with the right permissions are able to view and modify a program's Results Framework (RF). For detailed descriptions of roles and permissions, check out the [Partner Access matrix of roles and permissions](https://learn.mercycorps.org/site/tola/index.php/TOLA:Partner_Access#Tabular_summary_of_roles.2Fpremissions).

# Acceptance criteria
To access the RF builder, the following things must be true:
- [x] 1. User must be assigned to the program.
- [x] 2. Users with Low, Medium, or High permissions can **VIEW** the results framework builder.
- [x] 3. Only users with **High level permissions** **MODIFY** the results framework. 
- [x] 4. These rules are the same for MC and non-MC users.

User Role | Results framework builder
------------ | -------------
**Low - Mercy Corps user** | View 
**Low - non-MC user**  | View
**Medium - Mercy Corps user** | View
**Medium - non-MC user**  | View
**High - Mercy Corps user** | Modify
**High - non-MC user**  | Modify

### Low and Medium roles
- [x] 1. I can view saved RF levels.

- [x] 2. I can view currently selected template with the preview of levels _after_ the first level is saved. (These roles don't even see a link to the RF builder on the Program Page until at least one level is saved, as described in #1246.)

- [x] 3. I can expand and collapse levels by clicking the expando-collapso caret or text of the level.

- [x] 4. When an RF level has linked indicators, I can view and click on "# indicators" link to visit the IPTT filtered on those indicators.

I do NOT see the following elements:
- [x] 1. Delete button for saved RF levels.

- [x] 2. Edit button for saved RF levels.
     - Yes, this means I _do not have access to the actual RF level forms -_- only to the saved levels. This is fine because essential details are included in the saved levels.
     - Yes, this means I cannot view Assumptions associated with an RF level without visiting the Logframe. That is fine, because the Logframe is actually where people are conditioned to expect Assumptions to be displayed, and the format that will be most familiar to them. (My hypothesis is that most users will prefer the Logframe for reviewing program logic, and that only High access users will spend significant time in the RF builder.)

### High role
- [x] 1. Can see and do everything the Low and Medium roles can see and do.

- [x] 2. Access the RF builder _before_ the first level is saved, via the Program Page.

- [x] 3. Select and apply a different template before the first level is saved.

- [x] 4. Add a level - sibling or child.

- [x] 5. Edit a level - all form fields.

- [x] 6. Delete a level, as long as it has no sub-levels or linked indicators.

## Back end validation

It seems like we ought to bolster any front end solutions with back end validation, to ensure that there are no extra-edgy edge cases or loopholes that somehow enable the wrong people to see and do the wrong things. _I'd like to ask the developer who works on this ticket to flesh out this section a bit, ideally including instructions if they'd like any manual testing._

- [x] 1. There is back end validation to block someone without program access at any level from viewing or editing the RF.

- [x] 2. There is back end validation to block someone with Low/Medium access from modifying a results framework.

## Housekeeping

- [ ] Unit test/s written wherever applicable
- [ ] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@hannalcamp I've fleshed out this ticket a bunch since our Slack chat. Just let me know if you see any red flags.

**Comment by hannalcamp** [comment]
@jennyhavah Looks good to me!

**Comment by sanjuroj** [comment]
@jennyhavah Part of the reason I hadn't moved this into Acceptance testing is the items for the RF export, changelog, and custom templates.  Can we add items to those respective tickets so we can move this one along?

**Comment by jennyhavah** [comment]
@sanjuroj I removed those items. I created that ticket pretty early in the process, when I thought that the RF change log might be different than the one you access from the program page / IPTT. No new permissions required there. The logframe is view-only, and you can only access it after there is at least one level saved. If you can view it, no reason you shouldn't be able to export it.

So go ahead and move it to Testing whenever you're ready.

**Comment by sanjuroj** [comment]
Generally looking good but noticed that the `3 indicators` popover doesn't work in firefox.  Will look into that before moving over to testing.

**Comment by sanjuroj** [comment]
Popover should now work in both Firefox and Chrome.

**Comment by jennyhavah** [comment]
Validated that the popover works in Firefox!

**Comment by hannalcamp** [comment]
Looks good to me!
