### ISSUE TITLE
Update Yemen country border

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1257]
Update the Yemen country borders on the map.

**Comment by RickieT** [comment]
*QA Verified:*
* Ensured map highlighting was working as expected for multiple other countries as well, maintained functionality. 
* I compared the Yemen map on staging vs production, and the new implementation has a much improved highlight. 
![Screen Shot 2019-03-14 at 11 17 16 AM](https://user-images.githubusercontent.com/23220180/54381363-cbaabf80-464a-11e9-8ccf-4b0374abb556.png)
