### ISSUE TITLE
Slack and Workplace: Add a link to the Tola User Feedback & Reporting Google Form

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#126]
This task comes from the [Nigeria training issues log](https://docs.google.com/document/d/1uwf3vN1UE8A57pJWzEKf1OfWEQIA58Dsc3huOmqkQyc/edit).

Let's pin a link to the Tola Feedback / Issue Reporting form -- with encouragement to use it -- in the following places:
1. Slack Tola-users channel
2. Workplace Tola group

**Comment by jennyhavah** [comment]
@esinn This is the pinned item I see in #tola-users:

![image](https://user-images.githubusercontent.com/33670923/37629029-95f7a992-2b99-11e8-97c5-72ade221f470.png)

Can we replace with a more current welcome message, in addition to linking to the tola user feedback and reporting Google form?

**Comment by esinn** [comment]
Posted to WP and Slack, pinned to Slack and removed this old msg.
