### ISSUE TITLE
Flyout filter sidebar ala IPTT

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1262]
The flyout filter sidebar should look like the IPTT.

**Comment by axoplasm** [comment]
Update: Roderick has built this:

![image](https://user-images.githubusercontent.com/169060/54224686-404cf500-44b7-11e9-8392-d965cf361da8.png)

**Comment by camgnostic** [comment]
I rewrote some of Roderick's work to match the styling and animation of the IPTT Report.  In PR #1371  which I'm tagging @axoplasm on to have a look if he can.  I think it needs break points and a minimum width, but for the moment it is more consistent in style to the IPTT filter form sidebar.  And more reusable.

**Comment by RickieT** [comment]
**QA - PASSED**
* Confirmed on parthenon's staging a while back, and confirming here, flyout behavior between IPTT and Admin page filters, consistent function.
