### ISSUE TITLE
Overhead filters

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1263]
Look like this in PA: 
![image](https://user-images.githubusercontent.com/169060/54154680-b55cf380-43ff-11e9-883c-8f0eba4081da.png)

Should look more like this:
![image](https://user-images.githubusercontent.com/169060/54154704-c86fc380-43ff-11e9-946b-544b331b92be.png)

and when it gets some tags it looks like this: 
![image](https://user-images.githubusercontent.com/169060/54716172-6c4d2380-4b12-11e9-95e5-18556d498278.png)

**Comment by axoplasm** [comment]
Broadly overlaps with #1271

**Comment by axoplasm** [comment]
The tag/pill issue will (mostly) be fixed along with #1335. I've tweaked the layout in 29317ecd  to keep the "Apply" button from growing vertically.

**Comment by RickieT** [comment]
**QA - PASSED**
* Media: 
![Screen Shot 2019-04-09 at 10 45 53 AM](https://user-images.githubusercontent.com/23220180/55822550-b17ec880-5ab4-11e9-9592-fa489d11ccb1.png)

**Comment by RickieT** [comment]
Something has changed with this styling here, it doesn't quite match up with the original passing criteria: 
![Screen Shot 2019-04-29 at 9 52 24 AM](https://user-images.githubusercontent.com/23220180/56912662-96282d00-6a64-11e9-9457-1addfdc5b4d4.png)
![Screen Shot 2019-04-29 at 9 52 15 AM](https://user-images.githubusercontent.com/23220180/56912664-96282d00-6a64-11e9-9cf5-9006f5ad4fbc.png)

Looks a little funky when selecting items in this menu now, I'll file a new ticket to address if needed
