### ISSUE TITLE
Admin table styling

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1264]
Looks like this in PA:
![image](https://user-images.githubusercontent.com/169060/54154760-e5a49200-43ff-11e9-9a75-f43859d893e9.png)

Should look like:

![image](https://user-images.githubusercontent.com/169060/54154788-f35a1780-43ff-11e9-8f9c-8ee2a0f986b1.png)

**Comment by axoplasm** [comment]
There are related sub-tables aka “virtual tables”, see #1287

**Comment by RickieT** [comment]
@axoplasm I'm not seeing these styling changes on Dev2

**Comment by RickieT** [comment]
*QA - PASSED* 
![Screen Shot 2019-03-29 at 10 50 07 AM](https://user-images.githubusercontent.com/23220180/55253357-5cb89380-5212-11e9-90c1-e83d026a675a.png)
