### ISSUE TITLE
Pager (Pagination)

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1267]
As built in PA:
![image](https://user-images.githubusercontent.com/169060/54155154-c65a3480-4400-11e9-899a-1555d6dadc74.png)

As built on e.g. Sites page:
![image](https://user-images.githubusercontent.com/169060/54155256-fa355a00-4400-11e9-87aa-2b086df2565a.png)

As built on e.g. Stakeholders page (this is BS default per our system):
![image](https://user-images.githubusercontent.com/169060/54155343-281a9e80-4401-11e9-96e1-ce82abbca635.png)

As mocked up by Jenny:

![image](https://user-images.githubusercontent.com/169060/54155114-b5112800-4400-11e9-8b55-966d70e5cc17.png)

As mocked up our Sketch library:
![image](https://user-images.githubusercontent.com/169060/54155396-47b1c700-4401-11e9-9db6-81d181c707ee.png)

**Comment by RickieT** [comment]
**QA - PASSED**
![Screen Shot 2019-03-29 at 10 50 07 AM](https://user-images.githubusercontent.com/23220180/55252552-7527ae80-5210-11e9-9d55-4cf3979a54c1.png)
