### ISSUE TITLE
Vertical tabs

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1268]
These are Extremely Not Bootstrap.

As built in PA:
![image](https://user-images.githubusercontent.com/169060/54155533-8cd5f900-4401-11e9-9a58-85ab35983e6a.png)

As built in e.g. Indicator Setup:
![image](https://user-images.githubusercontent.com/169060/54155484-76c83880-4401-11e9-9a76-df7d5dff498d.png)

**Comment by RickieT** [comment]
![Screen Shot 2019-04-29 at 10 17 21 AM](https://user-images.githubusercontent.com/23220180/56914065-fc627f00-6a67-11e9-8f5b-e60c74c673e9.png)
