### ISSUE TITLE
Save/Reset buttons

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1269]
As built in PA:
![image](https://user-images.githubusercontent.com/169060/54155595-b2fb9900-4401-11e9-871f-b8f181eafabf.png)

Should be:
![image](https://user-images.githubusercontent.com/169060/54155569-a6774080-4401-11e9-969f-689aa585c89b.png)

**Comment by axoplasm** [comment]
We revised reset buttons in mockup thus:
![image](https://user-images.githubusercontent.com/169060/54708933-b4177f00-4b01-11e9-9da7-f421c80ab061.png)
addressed in e89fa270

**Comment by RickieT** [comment]
*QA - PASSED* 
* Verified changes on Organizations/Users/Country/Programs, using the image above. The stylistic changes are visible, functionality remains.

**Comment by RickieT** [comment]
![Screen Shot 2019-04-23 at 1 14 16 PM](https://user-images.githubusercontent.com/23220180/56612630-b457de00-65c9-11e9-9817-b25ea864addc.png)
