### ISSUE TITLE
Status/History pane

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1272]
Looks like this in PA:
![image](https://user-images.githubusercontent.com/169060/54156125-d115c900-4402-11e9-915a-4b863f8f8320.png)

Should look (something) like this per mockups:
![image](https://user-images.githubusercontent.com/169060/54156150-dffc7b80-4402-11e9-8b0d-afb54e253b79.png)

**Comment by RickieT** [comment]
**QA - PASSED**
* This looks pretty close to whats in the suggested image above:
![Screen Shot 2019-03-26 at 10 22 43 AM](https://user-images.githubusercontent.com/23220180/55018953-292afe80-4fb1-11e9-9d18-8971a28a4fd5.png)

**Comment by RickieT** [comment]
This is actually looking even better now: 
![Screen Shot 2019-04-23 at 1 25 45 PM](https://user-images.githubusercontent.com/23220180/56613352-55936400-65cb-11e9-8e65-6091129129ce.png)
