### ISSUE TITLE
[Edit] User: Programs and Roles Pane: “Select All” button

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1273]
looks like this:

![image](https://user-images.githubusercontent.com/169060/54223101-03333380-44b4-11e9-9560-4057585c436e.png)

Make it nice!

**Comment by axoplasm** [comment]
forgot to tag this in 41df749f

**Comment by RickieT** [comment]
*QA - PASSED* 
* Considerable difference in styling vs PA: 
![Screen Shot 2019-04-01 at 9 58 24 AM](https://user-images.githubusercontent.com/23220180/55345482-ccbe5800-5464-11e9-9a47-10fce3e54587.png)
