### ISSUE TITLE
Virtual tables

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1287]
These also need to be aligned to our expected style. Currently look like:

![image](https://user-images.githubusercontent.com/169060/54548839-0459da00-4966-11e9-86a5-ffa70f5ab2a5.png)

Per Jenny's mockups:

![image](https://user-images.githubusercontent.com/169060/54548876-18054080-4966-11e9-89ec-ab3b369e9e02.png)

**Comment by axoplasm** [comment]
Forgot to tag this in commit 41df749f

**Comment by RickieT** [comment]
@axoplasm is this the implementation of the styling?
![Screen Shot 2019-03-29 at 11 12 14 AM](https://user-images.githubusercontent.com/23220180/55253805-858d5880-5213-11e9-91f5-b0f0be8e7882.png)

**Comment by axoplasm** [comment]
Yes

**Comment by RickieT** [comment]
**QA - PASSED**
* verified in #1273
