### ISSUE TITLE
General housekeeping

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1289]
Sweep contributed code for:

- [x] Correctly capitalized titles (**S**entence **c**ase)
- [x] Strings marked for translation
- [x] Translator notes
- [x] Default output for null variables *(example: `Profile` or `Add Object: Profile`, not `: Profile` for new objects, or objects without names)*
- [x] Remove/replace code placeholders
- [x] Remove BS special-purpose layout selectors, e.g. `col-sm-12`; also make responsive!

**Comment by RickieT** [comment]
@axoplasm I think issue #1343 may be a result of these changes, based on looking at the code. But I may be wrong - I'm gonna continue poking around the pages affected

**Comment by RickieT** [comment]
@axoplasm I've been through pretty much the entire site while executing the test cases for PA - I did not see anything stand out other than what we've already reported as styling issues and other things that may have been a cause of changes in this ticket. I think this is probably safe to move to deploy ready? Unless there is anything you can point out I can directly focus on

**Comment by axoplasm** [comment]
Let's move this one on
