### ISSUE TITLE
Consistently say "Add thing" instead of "new thing"

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#129]
This ticket is connected to #152 -- Navigation menu options are inconsistent with page titles and breadcrumbs are a mess. 

This story also results in our top nav dropdown menu labels being consistent with the page titles they link to... with one notable exception, Program Index. (We'll address that in a separate story.)

While we are in there, we want to move the buttons to a consistent location and make them more easily discoverable.

## Button style
Right now, we use a standard rectangular button for "New thing". Let's turn all of these into "Add a thing" buttons in the same style as the "Add a [year/quarter/event/etc.] button used for periodic target setup. If it's easy to do, let's also right-align all of the "Add a thing" buttons to visually differentiate them more. 

## Button locations
- [x] 1. New Document --> Rename "Add document" 
- [x] 2. New Site Profile --> Rename "Add site"
- [x] 3. New Stakeholder --> Rename "Add stakeholder"
- [x] 4. Create a Project --> Rename "Add a project"

**Comment by kurtwall** [comment]
@jennyhavah @mahmoodkhan Could this story/issue incorporate #142 , requesting each page have its own unique `<title />` element in the HTML `<head />` section? Or are you talking about a different _page title_ than the HTML one?

**Comment by mahmoodkhan** [comment]
@kurtwall this is a separate issue, but I will start to update the title tag based on the page title.

**Comment by axoplasm** [comment]
Splitting Page Titles in #362

**Comment by jennyhavah** [comment]
Paul says that right-aligning the "Add" buttons sounds good but would sometimes mean adding layout markup. I don't consider this a must-have. 

Ticket validated.
