### ISSUE TITLE
Secure all API endpoints

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1292]
All API endpoints need to be assessed to ensure they are appropriately secured, since we are coming out from behind the SSO with this release.   It's possible that some of these endpoints are used for internal purposes (e.g. feeding React pages), so we need to make sure they can still function in that way.

**Comment by jennyhavah** [comment]
Hey @camgnostic Can we get some guidance on how to test this one?

**Comment by RickieT** [comment]
@camgnostic we're still looking for update on this one.

**Comment by jennyhavah** [comment]
Checked in with Cameron on Slack, and he said "That should be covered by automated testing- I wrote tests for all endpoints I could find."

I think we can consider this done.
