### ISSUE TITLE
IPTT: Replace "Apply" and "Reset" buttons with a Clear button

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1302]
**Affects:** Filter panels on both types of IPTT report.

# Issues
1. Apply and Reset buttons don't do anything useful at this point.
2. It _would_ be useful to have an easy way to clear some (but not all) filters, especially as we introduce more complex filtering options related to Results Framework tiers and levels.

# Acceptance criteria

- [x] 1. _Apply_ and _Reset_ button section is gone -- this bit:
![image](https://user-images.githubusercontent.com/33670923/54947472-a72acf00-4ef7-11e9-9557-87d4c46084ab.png)

- [x] 2. Incorporated inside the bottom (light gray) section of filters is a new _CLEAR FILTERS_ button.
     - [x] 2.1. The button has the _Reset_ style -- i.e. dark gray text on a white background.

![image](https://user-images.githubusercontent.com/33670923/55118657-4c86a400-50ac-11e9-9e3c-55d25a7fb169.png) 

- [x] 3. Clicking the _Clear_ button clears out all selections in the bottom section only -- i.e. Levels, Types, Sectors, Sites, Indicators. 

     - [x] 3.1. If any RF level rows in the table were filtered out, they are now restored. (See section 2 in #1298 for additional details on filtering effects on RF level rows.)

     - [x] 3.2. There is no effect on any of the report options in the top dark gray section -- Program, Time/Target periods, Start / End periods, or "Group indicators by" options.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [x] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by RickieT** [comment]
@jennyhavah @camgnostic If there is no apply button for the filter anymore, how is the filter engaged? Does it automatically filter results whenever a criteria is entered/selected/changed?

**Comment by jennyhavah** [comment]
@RickieT Yes, the filters will all respond immediately, making the Apply button extraneous.

**Comment by jennyhavah** [comment]
@camgnostic Not sure if this belongs in a separate ticket, but we'll need to address it before I can finish testing this one:

Looking at a program _other_ than the RF QA program -- just a regular old program -- when I open the very last INDICATORS filter and click any of the Indicator check boxes in the list, I get a blank page.

**Comment by jennyhavah** [comment]
PASSED. "Clear filters" button is working as expected and meets all the acceptance criteria.
