### ISSUE TITLE
Indicator Plan update: Incorporate RF levels into web view and export

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1303]
**Affects:** Indicator plan and Excel export

**Affected by:** Legacy indicator levels and our migration plan for those. See the "Indicator Plan" section in #1286.

# Stories
1. My indicator plan groups indicators by Results Framework (RF) levels, just like the IPTT does.
2. I can group indicators by results chain or by level, just as I can in the IPTT.
3. My indicator plan export includes RF level rows and reflects my grouping selection.

# Acceptance criteria

![image](https://user-images.githubusercontent.com/33670923/55180056-054cf180-5146-11e9-885a-545057b8535b.png)

There are two options for grouping indicators, identical to what we are doing for the IPTT (see #1298): by [2ndRFtier] chain or by Level, where "level" in this case refers to what we're internally calling tier. Length-wise, make sure to take into account long RF tier names translated into French, like so:

![image](https://user-images.githubusercontent.com/33670923/55107436-88127580-508e-11e9-8374-48da57f4402e.png)
    
- [x] 1. The Indicator plan now includes RF level rows, in exactly the same way we're displaying them in the IPTT.

     - [x] ~1.1. RF level rows are displayed regardless of whether or not there are indicators linked to them.~ Only show RF levels with at least one indicator linked to it. Exception: Top level, which often does not have indicators, and we need it to still show up and export.

     - [x] ~1.2. Any indicators unassigned to an RF level is grouped at the bottom under a row called "Indicators unassigned to a results framework level" -- same as the IPTT.~ No longer relevant. See 1.1 above.
 
- [x] 2. I can toggle between two indicator grouping options using a single-select menu with only the two options and no selectable "null" option like "------". The menu is in the upper right corner, right-aligned under the Excel export button. The search function should be OFF, since there are only two options.

     - [x] 2.1. The form field label to the left of the menu is "Group indicators:"

     - [x] 2.2. The default selection is "by [2ndRFtier] chain" -- so in the case of the MC template where the 2nd tier is Outcome, it'd be "by Outcome chain" and in the case of EC it'd be "by Specific Objective chain". Please note the capitalization -- "by" is lower case, and the RF tier is title case.

     - [x] 2.3. The other option is "by Level".

- [x] 3. When I toggle between the options, the Indicator Plan table reloads, grouped according to my selection.

- [x] 4. My Excel Export:
     - [x] 4.1. Includes the RF level rows
     - [x] 4.2. Reflects my grouping preference

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by camgnostic** [comment]
@jennyhavah what behavior do you want for the indicator plan in the case of programs that haven't migrated to the new RF levels?  Should we be displaying the old levels and not adding grey level rows, until they switch over their "grouping" in the program admin?

**Comment by jennyhavah** [comment]
@camgnostic I was imagining we'd handle it exactly like we're handing the IPTT -- no gray rows, ordered according to the original sorting criteria -- OldLevel, then number. Which I _think_ is what we're doing right now.

**Comment by jennyhavah** [comment]
PASSED. RF tier rows are displaying as expected, and export as expected, whether I group by Chain or by Level.
