### ISSUE TITLE
Re-implement collapsing changelog entries

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1304]
This spun out of the refactor ticket (#1276). I removed expanding/collapsing functionality to implement the changelog refactor. We'll need to add it back in both the admin lite changelogs (in the `<ChangeLog>` component) and in the audit log.

### Expected behavior:

Records are __open__ by default (*note: check on this with @jennyhavah*) and look like this:

![image](https://user-images.githubusercontent.com/169060/55113699-332a2b80-509d-11e9-938e-5dc1ca6cbe15.png)

Each record can be independently expanded/collapsed. This is not a "real" accordion (i.e. only one open record at a time)

I can click on the date field to collapse the data row. Note that user program and country permissions are returned as __multiple rows__. When all rows are collapsed they look like this:

![image](https://user-images.githubusercontent.com/169060/55113750-4dfca000-509d-11e9-96a5-cc30891fd55f.png)

### BONUS FUNCTIONALITY

Implement “Expand all” and “Collapse all” buttons that do exactly that. For clarity it will be simplest if these are two separate buttons. They can be disabled in the following circumstances:

* if __all__ records are expanded, “Expand all” is disabled
* if __all__ records are collapsed, “Collapse all” is disabled

**Comment by KennyMonster** [comment]
@axoplasm Working code for this is now in `1304_expandos`. It currently needs some styling work though, namely the dates need coloring and probably styling to change the moues cursor to a pointer, so users know is clickable.

I also added expand all and collapse all to the audit log, and those buttons need placement/styling as well (see upper right corner next to the Excel export button):

![Screen Shot 2019-04-10 at 3 24 08 PM](https://user-images.githubusercontent.com/1278224/55917653-ff72f980-5ba4-11e9-9b3b-39b7e585dadd.png)

**Comment by RickieT** [comment]
**QA - FAILED**
https://tola-activity-dev2.mercycorps.org/tola_management/audit_log/480/

I made numerous changes to some indicators, the items in the change log will not expand so I can view the changes made.

**Comment by RickieT** [comment]
**QA - PASSED**
Not sure why this wasn't expanding before, but it is now. 
![image](https://user-images.githubusercontent.com/23220180/56052470-59d79b80-5d06-11e9-8b3a-d138f676eca8.png)
