### ISSUE TITLE
Replace nerdy change_type values with human-readable values

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1305]
This spun out of the truncation ticket which is now changelog refactor/redesign (#1276). In building the changelog, `entry.change_type` values have dorky names like `user_program_updated` when they should have nice human names like `Program access changed` or somesuch.

__This will be bigger than I anticipated.__ Values are hardcoded in the DB and the React components rely on the raw strings for all kinds of comparisons.

**Comment by axoplasm** [comment]
Roderick fixed this with b836b343 and elsewhere

**Comment by RickieT** [comment]
**QA - PASSED**
* Can confirm, these "string" names can't be found anymore, when viewing change log and admin pages
