### ISSUE TITLE
Replace nerdy field names with human-readable names

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1306]
The changelog prints field names like `mode_of_contact` when they should be printing field names like `Mode of Contact`

Also:
- [ ] Translate!

**Comment by axoplasm** [comment]
Roderick fixed this with b836b343 and elsewhere

**Comment by RickieT** [comment]
**QA - PASSED**
* I am unable to find these "nerdy" names in the change log, looks like regular old words now. 
![Screen Shot 2019-04-03 at 9 46 15 AM](https://user-images.githubusercontent.com/23220180/55497068-5735c180-55f5-11e9-95e0-fc5531a67897.png)
