### ISSUE TITLE
"Add Country" Is justified left, while users/programs/orgs is justified on right side of page

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1307]
Add User / Add programs / Add organization is justified on the right side of each of the administration pages. 

Though, on the country page, it is justified on the left side, away from its brethren. 
![country_out_of_place](https://user-images.githubusercontent.com/23220180/55016462-0e09c000-4fac-11e9-9aa5-aaaf00b019e0.png)

**Comment by axoplasm** [comment]
This was fixed in ee2a393e

**Comment by RickieT** [comment]
**QA - PASSED**
Confirmed, this is now right justified with its other like elements
