### ISSUE TITLE
Indicator Setup > 400 Error (Bad request) is occurring when attempting to create targets after correcting a missing required field  

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1308]
400 Error (Bad request) is occurring when attempting to create targets after correcting a missing required field. 

**Steps to Reproduce:** 
1. Create a new indicator
2. Forget to fill out the Level field.
3. Fill out all required fields on the Targets tab and click “Create targets”
4. See prompt to fix level. Go to Performance tab, select a level.
5. Come back to the Targets tab and click “Create targets” again.

Note: I am not able to reproduce this issue in Parthenon's staging server

![Screen Shot 2019-03-26 at 11 34 06 AM](https://user-images.githubusercontent.com/23220180/55024467-27b30380-4fbc-11e9-8b1e-fb6a97e826c6.png)

**Comment by camgnostic** [comment]
Unable to reproduce on -dev2 (or local) @RickieT  can you retest?

**Comment by RickieT** [comment]
@camgnostic following the steps above after a few attempts, I am not able to reproduce this on dev2. I think we can close this and re-open if anything similar pops
