### ISSUE TITLE
Program page: Updates to indicator numbering, levels, grouping

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1311]
**Affected by:** 
1. #1286 migration plan for legacy indicators (old levels vs new levels)
2. #1288 indicator numbering options and migration plan (in terms of which numbers appear)

# Stories
1. Automatically generated indicator numbers appear as expected on the program page.
2. I have a choice whether to group indicators by results chain or by tier, same as I can in the IPTT.

_Important to note: **We are NOT incorporating the actual RF level rows into this page**, the way we are with the IPTT and Indicator plan. That would introduce a ton of visual complexity without adding much value. This ticket is only about grouping indicators._

# Acceptance criteria

## Changes to indicator rows

![image](https://user-images.githubusercontent.com/33670923/55182170-5ced5c00-514a-11e9-86b0-de57d0335a95.png)

- [x] 1. There is no longer a "Level" column.
- [x] 2. Instead of only displaying the indicator number in bold text before the indicator, we display the RF tier as well -- **[RFtier][indicatorNumber]:** For example, Outcome 1a, Output 1.1a, Activity 1.1.1a.

## Changes to grouping of indicators

- [x] 1. By default, indicators are grouped hierarchically by results chain, meaning Goal, Outcome 1, Output 1.1, Activity 1.1.1, Outcome 2, Output 2.1, etc.

- [x] 2. Any indicators unassigned to RF levels are batched at the end.

- [x] 3. I have the ability to toggle between grouping by results chain or by Level, using the exact same interaction I use on the IPTT, Logframe, Indicator plan, etc. Here is how it looks elsewhere:
![image](https://user-images.githubusercontent.com/33670923/55174223-450ddc00-513a-11e9-81ab-a22b14556762.png)
     - [x] 3.1. Above the list of indicators, is a single-select menu. Consider long RF level names translated into French. (WHERE EXACTLY, you ask? I'm struggling with this question and would like to get Paul's thoughts on placement.)
     - [x] 3.2. The form field label is "Group indicators:"

     - [x] 3.3. The menu is a single-select with two toggle options and no "null" type value such as "-----". The search function should be OFF, since there are only two options.

     - [x] 3.4. The default selection is "by [2ndRFtier] chain". For the MC template it would be "by Outcome chain" and for the EC template it would be "by Specific Objective chain". Please note the capitalization -- "by" is lower case, and the RF tier is title case. 

     - [x] 3.5. When the menu is set to "by [whatever] chain", the table is organized hierarchically -- e.g. for Mercy Corps template it would be Goal, Outcome 1, Output 1.1, Activity 1.1.1, Outcome 2, etc.

     - [x] 3.6. When the menu is set to "by Level", the table is organized by RF tier -- e.g. for Mercy Corps template it would be Goal, all Outcomes, all Outputs, all Activities.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by camgnostic** [comment]
@axoplasm probably going to want to glance at styling for this new program page box (visible on program page for programs like RF QA Program which have new-style levels) - I tried to follow semantic class naming based on the other filter box

**Comment by jennyhavah** [comment]
Functionality is working as expected. I have a few styling requests.

![image](https://user-images.githubusercontent.com/33670923/59063243-86b6b380-885c-11e9-9fb2-1225ebafc372.png)

- [ ] 1. Remove indentation when indicator names wrap, such that everything aligns with the left edge of the indicator number.

- [ ] 2. Add a little bit of space between the caret and the indicator number.

- [ ] 3. @axoplasm We put the "Group indicators" menu in line with the "Find an indicator" menu, which I think works well; one thing filters the list, the other sorts the list. But proportionally speaking, the indicator menu needs more space than the grouping menu, due to the long indicator names.

     What do you think about moving the labels above the menus instead of in-line, reducing the font size to match the form label style on the RF template picker? It'll push the list down a bit, but there'd be more horizontal space available for the menus. It might look terrible, so let us know what you recommend.

**Comment by axoplasm** [comment]
FFR (this was kind of confusing) I have to go to the program's edit page in admin lite and set the "Group indicators according to the results framework" flag

**Comment by axoplasm** [comment]
@jennyhavah I think this looks pretty good!

<img width="865" alt="image" src="https://user-images.githubusercontent.com/169060/59153317-126e4280-8a0b-11e9-9b1b-4f274cb96eff.png">

However there is a visual regression for programs that don't use RFs:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/169060/59153320-2fa31100-8a0b-11e9-8642-917d33034e29.png">

This is not an insurmountable problem but I'm a little hesitant to add a bunch of display switches just to get that label inline

**Comment by jennyhavah** [comment]
@axoplasm What visual regression are you seeing? Nothing is jumping out at me. If the program doesn't use RFs, then it would not make sense to show the "Group indicators" menu.

Also, how easy or hard would it be to force the width of the Group indicators menu to be proportionately narrower than the "Find an indicator" menu? Chains are rarely more than 3 words long, but indicators can be looooooooooooooooong. So if it doesn't require anything hacky, would like to give the indicators menu more breathing room.

**Comment by axoplasm** [comment]
The visual regression is the second screenshot, where filter labels are now block elements not inline

Setting widths for each filter list is *possible* but it would be hacky. Do not recommend.

**Comment by jennyhavah** [comment]
Okay, I'm good.
