### ISSUE TITLE
Program Objectives import

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1312]
**Affects:** Results framework (RF) builder

# Story
As a program team that went to a lot of effort to set up Program Objectives in the Django admin, we don't have to type everything again from scratch. We can import text from PO text directly into our RF levels as we add them.

# Acceptance criteria

## RF builder

![image](https://user-images.githubusercontent.com/33670923/59527544-b7b46b00-8e90-11e9-811f-8148ee76a90c.png)

If, _and only if_, a program (a) already exists (by the time Satsuma is deployed to Production) and (b) has at least one Program Objective linked to it, the following things happen.

- [x] 1. In the upper right corner of each RF level is a searchable single-select menu called "Import Program Objective"

     - [x] 1.1. To the right of the menu is a question mark icon that opens a tooltip. Please note that most, but not all, of the text is bold red. The tooltip says: 
     Import text from a Program Objective. **Make sure to remove levels and numbers from your text, because they are automatically displayed.** <P>

- [x] 2. The menu displays whatever is in the Name field of each Program Objective.

- [x] 3. When I select a Program Objective, the following things happen:
     - [x] 3.1. The RF level text box is populated with whatever is in the Name field.
     - [x] 3.2. The Assumptions text box is populated with whatever is in the Description field.

Note: I considered adding logic to make POs disappear from the list as they're selected and saved to levels. My concern is that people will inevitably make mistakes or second-guess themselves, wondering if they imported text from the wrong PO -- and be unable to fix the mistake or access the original text without digging into the Django admin. So let's keep this feature simple and always display the full list.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
If I select something from the PO menu straightaway and don't type anything, I can't access the various Save functions -- "Save and link indicators", or any of the "Save..." buttons.

**Comment by jennyhavah** [comment]
@KennyMonster Instead of appending the PO text to whatever is already in the box, can we instead overwrite whatever is in the box?

I find myself expecting it to do this, and being surprised when it just adds more text.

**Comment by KennyMonster** [comment]
@jennyhavah I pushed a change to overwrite instead of append: 0db88af7d240d46fa7d2f79e2422a2480b65df5a

**Comment by jennyhavah** [comment]
PASSED. Feature is working as expected.
