### ISSUE TITLE
Replace "N/A" with em-dash (—) in displays of empty values

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1313]
In particular, the use of em-dashes in `tola_management/models.py` throws a UnicodeError when exporting changelogs to excel

**Comment by jennyhavah** [comment]
@camgnostic I seem to recall you recently doing some refactoring on the Satsuma branch that addresses the N/A issue globally. Is that true?

If yes, I suggest we close this ticket in Papaya since it's already done in Satsuma.

**Comment by jennyhavah** [comment]
Closing because it was addressed in Cameron's IPTT refactor as part of Satsuma.
