### ISSUE TITLE
Reveal Projects and Stakeholders only to a few countries

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#132]
# Background
We are no longer training on Projects and all of their related components -- stakeholders, contacts, budget tracking, project-focused dashboards and reports, etc. As far as we know, only one country is actively using Projects, and we hope to prevent new countries from adopting them. For the vast majority of users, everything Project-related in the TolaActivity UI is irrelevant and competes for attention with the features they _are_ using. 

# Affected areas of the UI

## Top navigation bar

**BROWSE MENU**
- [x] Projects do not appear
- [x] Stakeholders do not appear
![image](https://user-images.githubusercontent.com/33670923/47746127-afc9f280-dc42-11e8-9bbf-5f257f74c298.png)

**REPORTS MENU**
- [x] "Project Report" does not appear
![image](https://user-images.githubusercontent.com/33670923/47746173-d8ea8300-dc42-11e8-9538-2e55eec334f1.png)

## Results form
- [x] Project menu does not appear 
![image](https://user-images.githubusercontent.com/33670923/47746355-2f57c180-dc43-11e8-8754-593d5e618dde.png)

## Django Admin and Migration path
1. D**jango admin:** Do we handle this through some sort of Projects ON/OFF toggle? If yes, what is that toggle associated with -- programs, countries, user accounts, other?
2. We want the default to be OFF for all new countries/programs/users. But what about those that are already in the system? How do we minimize the risk of inadvertently disconnecting access for the few people still using Projects?

**Comment by KennyMonster** [comment]
The nav and form elements detailed above will now be hidden from all users, unless the user has one of the 3 country codes set in their user profile:

* Afghanistan
* Pakistan
* Timor-Leste

Both the **Country** and **Accessible Countries** fields are checked on the user profile. If one or the other is set to one of the 3 countries above, the nav/form elements are revealed.
