### ISSUE TITLE
Edit text of warning messages

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1320]
We have a number of new warnings/prompts for rationale that use outdated terminology and/or have the potential to be misinterpreted. Hanna has reviewed and approved the following edits.

---

- [x] __Delete existing targets__

**Current:**
This action cannot be undone. Any result records already assigned to the targets you are deleting will need to be replaced. Please make sure your results data will not be lost. For future reference, please provide a rationale for deleting these targets.

**Replace with:**
This action cannot be undone. Any results assigned to these targets will need to be reassigned. For future reference, please provide a rationale for deleting these targets.

---

- [x] __Modify existing target value__

**Current:**
This action may affect the overall program results and should only be performed to correct an error in target creation. For future reference, please provide a rationale for modifying this target value.

**Replace with:**
Modifying target values will affect program metrics for this indicator. For future reference, please provide a rationale for modifying target values.

---

- [x] __Delete result record__

**Current:**
This action cannot be undone. This result value and the information associated with it will be permanently removed. For future reference, please provide a rationale for deleting this result record.

**Replace with:**
This action cannot be undone. The result value and any information associated with it will be permanently removed. For future reference, please provide a rationale for deleting this result.

---

- [x] __Modify result record__

**Current:**
This action may affect the target period achievements and should only be done to correct a previous data entry error. For future reference, please provide a rationale for why you are modifying the result information.

**Replace with:**
Modifying results will affect program metrics for this indicator and should only be done to correct a data entry error. For future reference, please provide a rationale for modifying this result.

---

- [x] __General rationale prompt__

**Current:**
Your changes will be recorded in an audit log. Please record your rationale for future reference.

**Replace with:**
Your changes will be recorded in a change log. For future reference, please share your rationale for these changes.

**Comment by KennyMonster** [comment]
I have manually updated the .po files to reflect the changes to these things in base.js.

See: 53e077657763dfdb6c77f3c1a64bd29a8d884614

**Comment by RickieT** [comment]
*QA - Failed* 
* I am not seeing the _new message for deleting targets_, though I am seeing the new message for the other items on the list

**Comment by axoplasm** [comment]
@RickieT do you mean Condition 1 (Delete existing targets)? 

This is what I see there:
![image](https://user-images.githubusercontent.com/169060/55504578-fcf12c80-5605-11e9-87b6-8bd520ef84ad.png)

(I fixed the related issue with superfluous text in 2e93ad2a)

**Comment by RickieT** [comment]
**QA - PASSED**
* I'm seeing that warning now, moving to ready for deploy
