### ISSUE TITLE
Add program name to changelog

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1322]
This should be easy, except React.

<blockquote>A detail you may have already caught on the IPTT web version of the change log: Let’s make sure to include the title “Change log” and the program name underneath. (I’m referencing a screen shot you sent that may be out of date.)

(Noticed it because I’m working on the change log for the results framework.)
(I’ll be borrowing all the patterns from the IPTT one.)
Maybe we should call it “IPTT change log” as opposed to “Results framework change log”.
Eh… I could go either way on that.

Paul Souders [15:30]
I suppose technically it’s the “Indicator change log”

jenny marx [15:32]
Even better
</blockquote>

**Comment by axoplasm** [comment]
Much trickier than you’d think!

![image](https://user-images.githubusercontent.com/169060/55500808-e34be700-55fd-11e9-987c-723bd395fed3.png)

**Comment by RickieT** [comment]
**QA - PASSED** 
* Checked a couple change log pages - Looks good: 
![Screen Shot 2019-04-04 at 9 19 28 AM](https://user-images.githubusercontent.com/23220180/55571661-ce815900-56ba-11e9-94b8-935eeb024e91.png)
