### ISSUE TITLE
Remove country borders file

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1323]
I'm putting this in Satsuma for now, but we should move it to Poblano if we decide to do it, even if part of Satsuma.  

Before the Sudan training we noted that there was a disputed border between Sudan and S. Sudan and since we didn't have time or the....something.... to tackle the disputed border issue, we just removed Sudan from the file that creates the country borders entirely.  

I'm wondering if we should find a better basemap, one with more prominent country borders.  This could potentially eliminate the need for our extra layer.  One alternative is to a more official set of borders than the really bad ones that we have right now.  The potential downside is that the couple that I've seen are much bigger files, and the current crappy border file is already one of the more time consuming ones that we load.  There may be ways to compress these files that we haven't explored though.  

This ticket is just a way of starting this conversation.

**Comment by jennyhavah** [comment]
@sanjuroj Why put it in Satsuma for now if it belongs in Poblano?

**Comment by sanjuroj** [comment]
Because I think it might disappear in Poblano.  I sort of wanted to see how priority it was before dropping it into the pile.

**Comment by kdubois22** [comment]
This work should be done as part of Sites (per Marie)

**Comment by sanjuroj** [comment]
This may already have been done.  @camgnostic  worked on the maps as part of levelup.

**Comment by kdubois22** [comment]
This will be done once Level Up launches.
