### ISSUE TITLE
All rationale prompts: Rationale field is required (was: OK button is disabled until I type something)

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1326]
# Issue

Right now, I'm allowed to submit the rationale form with no text, and get a confusing message about results being recorded.

If rationales are required, then it would be better to prevent users from even submitting the form.

# Request
<s>For all rationale prompts in the system, disable the OK button until I've typed something.</s>

__Edit 2019-04-05__

For all rationale prompts int he system, I can’t submit the form until I've entered a rationale. If I try to submit an empty field, I get the error message "Rationale is required."

**Comment by axoplasm** [comment]
just to clarify, this means making the rationale field "required," correct?

**Comment by jennyhavah** [comment]
@axoplasm Yes, I confirmed with Hanna that rationales are always required. This is consistent with rationale prompts we'll be introducing with the results framework as well.

**Comment by axoplasm** [comment]
The action of clicking on “OK” validates the rationale field, so we can’t (trivially) disable this button. 

We __can__ trivially make the rationale field required, and display an inline warning text. This warning text for changes to __both__ results and indicators was previously 

> “Results have been recorded. Rationale is required.“

Because both the results and indicators forms use this same PNotify popup, they must share error text. I’ve changed it to read:

> “Rationale is required.”

![image](https://user-images.githubusercontent.com/169060/55647986-ec6ebc80-5793-11e9-990e-3fbc908d8884.png)

**Comment by jennyhavah** [comment]
Sounds good.

**Comment by axoplasm** [comment]
These still need styling per #1187

**Comment by axoplasm** [comment]
I’m discovering a few unexpected edges in trying to address this. I don’t get a prompt for a rationale when I:

* __delete targets with no associated results.__ This requires no confirmation and does not produce a success message.
* __delete an indicator with no targets.__ This requires no confirmation but does produce a success message

**Comment by jennyhavah** [comment]
> I’m discovering a few unexpected edges in trying to address this. I don’t get a prompt for a rationale when I:

> delete targets with no associated results. This requires no confirmation and does not produce a success message.

This is expected behavior.

> delete an indicator with no targets. This requires no confirmation but does produce a success message

This should never be possible without a confirmation message, and we should absolutely prompt for a rationale if there are results linked to it. Today, you get the same confirmation page, regardless of results being linked or not.

![image](https://user-images.githubusercontent.com/33670923/55762774-184ea400-5a19-11e9-8ab3-02792ea1584d.png)

I will file a new ticket with the desired behavior. This is definitely a release blocker.

**Comment by axoplasm** [comment]
This only happens when there are no associated targets or results.

**Comment by axoplasm** [comment]
Setting aside the new bugs we found, I’ve changed the error message to “Rationale is required.” This field is strictly speaking required but you can subvert this by entering [space] or any other random thing.

**Comment by RickieT** [comment]
**QA - PASSED**
* Deleting an indicator w/ Targets
* Deleting an Indicator w/results
* Modifying an indicator
* Changing Program Period
* Attaching results
* Modifying Results
* Modifying results report date
* Deleting results

All these prompts under the above conditions were prompted, and could not be submitted WITHOUT entering text in the field before hand.
