### ISSUE TITLE
Result form: Site field weirdness

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1327]
I noticed some weirdness with the Site field on the Result form. The form field is tiny and the label is to the left of it rather than above.

![image](https://user-images.githubusercontent.com/33670923/55264807-de201e00-5232-11e9-88fe-f48cb71a9843.png)

**Comment by RickieT** [comment]
**QA - PASSED**
* I can no longer reproduce this issue on -dev2

**Comment by RickieT** [comment]
@axoplasm looks like this has regressed

go to https://tola-activity-dev2.mercycorps.org/program/572/#/

Click Plaza 122 Vacancy Rate, and click add result

**Comment by RickieT** [comment]
**QA - PASSED**
* Looks like this has been fixed, site field is of normal length and width now. I'll keep an eye out in further testing, and will check this again before final PA release.
