### ISSUE TITLE
IPTT: Placement of Change log button

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1329]
As discussed in Slack, I'd like to make the link to the change log less prominent, as it is not something people frequently visit. I am also rethinking my original button treatment, as it really is a simple link to a different page, not an "action" such as downloading an export or pinning something.

This is how it looks now: 
![image](https://user-images.githubusercontent.com/33670923/55346200-c6c97680-5466-11e9-9605-6021f9b263df.png)

Proposed: Wherever we have a change log, we position it in the lower left corner of the page, under the thing you're logging. On the IPTT, it'd look like this:

![image](https://user-images.githubusercontent.com/33670923/55346251-e6f93580-5466-11e9-8400-e6983d981af2.png)

And in the RF builder, it'll look like this:

![image](https://user-images.githubusercontent.com/33670923/55346289-fc6e5f80-5466-11e9-8268-fae667afbffa.png)

**Comment by camgnostic** [comment]
Addressed in partner-access (#1372) - this ticket needs to be moved to Satsuma or duplicated in Satsuma to ensure styling is also updated there - @jennyhavah should I just copy the ticket?  Or can we move it after QA?

**Comment by jennyhavah** [comment]
@camgnostic Can you please make a copy of the ticket in Satsuma, referencing this ticket and the need to ensure that the change is carried over? 

That way, Rickie can test and mark the ticket Done, and we don't risk the work falling off our radar because we forgot to move the ticket from one project to another.

**Comment by RickieT** [comment]
**QA - PASSED**
* Changelog link now sits at the bottom left corner of the table on IPTT pages, and directs user to the change log successfuly

**Comment by RickieT** [comment]
### NOTE: 
* This no longer applies. After demo feedback, the change log is now on the program page, and sits now below the filters on the iptt page
