### ISSUE TITLE
Growl notification titles may be superfluous

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1330]
The "Warning/Error/Success" title on growl-style notifications may be superfluous. A tighter design would omit these titles.

**Comment by axoplasm** [comment]
Per @jennyhavah : 

![image](https://user-images.githubusercontent.com/169060/55346501-84546980-5467-11e9-87c6-4a6ad24f0164.png)

> I’m wondering if we need the title “Warning”, as opposed to just putting the warning next to the icon. Most of the messages I write end up being more than one line, and it’s getting this kind of layered lasagna appearance. What do you think about this instead?

![image](https://user-images.githubusercontent.com/169060/55346514-8dddd180-5467-11e9-9cbe-077bb979a163.png)

in which case we might want to indent the warning text:

![image](https://user-images.githubusercontent.com/169060/55346553-a6e68280-5467-11e9-933b-bf828099bb47.png)

**Comment by jennyhavah** [comment]
@axoplasm As I work more with these notifications, the Warning title is growing on me -- I appreciate your point about it establishing a nice hierarchy of information.

I'd like to keep it as is. Unless you have any objections, please feel free to close this ticket as a "never mind".

**Comment by jennyhavah** [comment]
Closing, as I prefer the titles.
