### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1333]
This has all the parts but stinks:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/169060/55422755-37d56080-5531-11e9-913e-ac432671b38f.png">

**Comment by jennyhavah** [comment]
Comments on the mockup posted to Slack. Tagging @hannalcamp in case she has any concerns or additional feedback.

![image](https://user-images.githubusercontent.com/33670923/55514730-b3acd700-561d-11e9-8c52-a03f5360149a.png)

## Text changes

- [ ] 1. Mercy Corps Employees: Replace everything in that box with a single button or link:  
     ### Log in with a mercycorps.org email address

- [ ] 2. Partners: Replace everything in that box with a single button or link:

     ### Log in with Gmail

- [ ] 3. Django option: Replace "Or log in with another email address" with, "Log in with a username and password"

**Comment by axoplasm** [comment]
Ah, I missed the help text. Here's what I just pushed to dev
![image](https://user-images.githubusercontent.com/169060/55521224-b109ac00-5634-11e9-8ae9-34347c9d4f33.png)

**Comment by jennyhavah** [comment]
It's looking better and better! 

I have a lingering concern that people will be confused by the "Log in with a username and password" box, that they may even try typing in their mercycorps.org or Gmail login credentials in there.

Two ideas:

1) Insert the word "non-email" into the header, i.e. "Log in with a non-email username and password. "

2) _**Only if this is trivial to do:**_ If I enter a username whose format is detected to be an email, we return an error message under the username field: Please enter a username that is not an email address. (I don't know what kind of default error messaging is already in place, how smart it is in terms of differentiating different types of errors, etc.)

**Comment by axoplasm** [comment]
I decided to put the django login into a `collapse` element

![image](https://user-images.githubusercontent.com/169060/55572081-b1995580-56bb-11e9-83ed-273bc76210da.png)

![image](https://user-images.githubusercontent.com/169060/55572100-b9f19080-56bb-11e9-9293-a99d0aa2907e.png)

**Comment by jennyhavah** [comment]
Looks great! @RickieT this is ready for testing.

**Comment by RickieT** [comment]
**QA - PASSED**
* The last image posted my Paul displays the before and after, of clicking the log in with user name expando/collapse. 
* Aside from gmail login being borked and reported in another ticket, okta and regular username / password login works fine
