### ISSUE TITLE
Country disaggregations accordion styling

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1334]
crowded & messy:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/169060/55425361-28f1ac80-5537-11e9-8484-7355976ee3f4.png">

**Comment by axoplasm** [comment]
The accordion folding for disaggregations and strategic objectives should resemble those of disaggregations on the Indicator Results form.

#### Admin lite country disaggregations, 

#####...folded:

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/169060/56058377-19801980-5d16-11e9-971d-076d0609f0b1.png">

#####...unfolded:
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/169060/56058398-2bfa5300-5d16-11e9-9822-90d4f9e01fa0.png">

#### Indicator results disaggregations

##### …folded:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/169060/56058461-4cc2a880-5d16-11e9-9f33-f8006c74d3e7.png">

##### ...unfolded:

<img width="905" alt="image" src="https://user-images.githubusercontent.com/169060/56058482-5ba95b00-5d16-11e9-9cc4-8b28c652559e.png">

**Comment by RickieT** [comment]
**QA - PASSED**
* Can edit/remove items from fields
* Fields save when changed

![image](https://user-images.githubusercontent.com/23220180/56062138-53eeb400-5d20-11e9-8235-330a2b18b6b9.png)
