### ISSUE TITLE
Multi-select: Replace tag-style "pill" placeholders with raw count.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1335]
There is some additional work that will be required post-Papaya to make the multi-select work the way we really want it to.  But for now, just make it functional in time for the release.

#### Functional issues:
- [ ] Replace tag-style (“pill”) placeholders with a raw count (as for example on IPTT filters):

![image](https://user-images.githubusercontent.com/169060/54780183-586af580-4bd6-11e9-9349-69be22c0f91e.png)

**Comment by axoplasm** [comment]
Do you have more feedback on how they aren't functional? 

#1271 has both stylistic and functional issues. I've pulled the functional issue (show a count instead of “pills”) into this ticket

**Comment by sanjuroj** [comment]
I think this is more of a @jennyhavah  or @hannalcamp  question.

**Comment by jennyhavah** [comment]
@axoplasm Here's what I'm seeing on 1271:
![image](https://user-images.githubusercontent.com/33670923/55754610-f1d13e80-5a01-11e9-8877-d1f0f469983d.png)

I think this ticket is now supposed to cover changing the tag style selection with a raw count. We decided in the last backlog/planning meeting to only address stylistic issues for the initial partner access release.

**Comment by jennyhavah** [comment]
Reopening because we still need to do this work -- it's just not a Papaya release blocker. (See my comment above.)

I'll move it to To Do.

**Comment by camgnostic** [comment]
Do we want this also on multi-selects within the Admin edit pages?  For example, when editing an Organization, Sectors is a multi-select.  Pills or # selected?

**Comment by jennyhavah** [comment]
@camgnostic This ticket was for the admin console. I'm guessing you're implementing this in the IPTT, which is great.

We eventually DO want consistent behavior with these multi-selects across the app, but it is NOT a release blocker for Papaya.

If my assumption is correct and you're actually working on the IPTT multi-selects, I'd like to propose we move this ticket over to Satsuma. What do you think?

**Comment by jennyhavah** [comment]
Also, can whoever is running with this ticket at the moment please un-assign the other two devs? That'll make it easier to know who to go to with questions, etc.

**Comment by RickieT** [comment]
**QA - PASSED**
Looks like this is passing on Dev2
![image](https://user-images.githubusercontent.com/23220180/55991285-be3f2000-5c5e-11e9-8262-94477e98441c.png)

**Comment by jennyhavah** [comment]
@RickieT Your screenshot makes me think there may be a misunderstanding about what we're testing. We're testing the multi-select filters in the left column filter panels... Instead of the "pills" showing each and every thing you selected, spelled out, it's supposed to give you a count of how many items you selected.

But @camgnostic I think we need some clarity on exactly where you implemented the raw count in the Partner Access branch:

All multi-selects in all 4 Admin sections?
Multi-selects in the two types of IPTTS?

Both?

Moving this back to Testing until we have more clarity on what we need to test.

**Comment by RickieT** [comment]
@jennyhavah my mistake, thats not clearly spelled out here - in the screenshot it used to do the same thing there as well

**Comment by jennyhavah** [comment]
@RickieT So it sounds like there were also some updates made to form fields in the body of the page, which I didn't realize. 

I'd like to ask @camgnostic to give us a list of any places the multi-selects were updated, just so we know all the places to check.

**Comment by RickieT** [comment]
**QA - PASSED (Pending @camgnostic response)**
### Admin > Users:
![image](https://user-images.githubusercontent.com/23220180/56052118-7f17da00-5d05-11e9-80e5-b6bfb3e0d545.png)
### Admin > Programs
![image](https://user-images.githubusercontent.com/23220180/56052155-922aaa00-5d05-11e9-9517-67d3c119a8af.png)
### Admin > Organizations
![image](https://user-images.githubusercontent.com/23220180/56052213-b090a580-5d05-11e9-961a-b59f6383bdea.png)
### Admin > Programs
![image](https://user-images.githubusercontent.com/23220180/56052231-bc7c6780-5d05-11e9-8d2e-563fdf7e8283.png)

**Comment by camgnostic** [comment]
Sorry!!  Just the admin panes (filters) and admin panes (dropdowns) that were multi selects.  So Users page, Organizations page, Programs page, and Countries page the filters on the left that are multi-selects, also Program editing admin page: Countries and Sectors dropdowns, and Organizations editing admin page: Sectors dropdown.  I just realized I missed the multiselect for the Countries filter when editing Programs and Roles on the Users admin page, but I could add that one in also today if we want?  @jennyhavah what do you think?

**Comment by jennyhavah** [comment]
@RickieT Cameron is going to fix that last multi-select, so I'm moving this back to Doing. If you've tested all the other multi-selects, then there will be just one more to test after he merges those changes in.

**Comment by RickieT** [comment]
@jennyhavah sounds good, watching

**Comment by KennyMonster** [comment]
The multiselect for the Countries filter when editing Programs and Roles on the Users admin page has been updated.

**Comment by RickieT** [comment]
**QA - PASSED**
We've got the new multi select under roles now in users well:
![image](https://user-images.githubusercontent.com/23220180/56308042-2a0c0780-60fb-11e9-941a-d193eb09dbf5.png)
