### ISSUE TITLE
Make superuser permissions more clear

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1338]
Currently superusers have God permissions but also have the ability to deselect themselves from countries and programs.  This is misleading since they can still modify everything.  We need to make the user interface more clearly reflect what superusers can do.

**Comment by sanjuroj** [comment]
@axoplasm Is this being handled by a different ticket.  I know there have been a lot of conversations about it, but I don't know what was decided.

**Comment by axoplasm** [comment]
This is explicated in #1339, will close this ticket
