### ISSUE TITLE
Admin > Users > Phone number field is not saving when saving changes

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1344]
**Description**
Phone number field when editing a user will not save 

1. Login to dev2 PA staging environment as an admin 
2. Click Admin > Users
3. Click on any user, and proceed to the phone field
4. Enter a phone number, or anything for that matter
5. Click Save changes

**Results**
Save message displayed, phone number entered disappears

**Expected Result**
Phone number field is saved when changes are made

**Comment by camgnostic** [comment]
Closed by PR #1363 
NOTE: as of this point there is no validation on that field, so "123-456-7890" is a valid phone number, as is "this is a phone number I swear" and "       "

If we want validation please open a ticket, but due to the complications of international phone numbers that is a question I leave to @jennyhavah / @hannalcamp

**Comment by RickieT** [comment]
@camgnostic I'm not seeing the phone number field change still when changing/adding numbers to the phone field for users, I'm moving this back to dev

**Comment by RickieT** [comment]
**QA - PASSED**
* Due to some mystical background happenings, this is now working, and phone number field is saving changes as made in admin > Users phone field.

**Comment by hannalcamp** [comment]
Definitely think validation of phone numbers would be too complicated for now, I imagine we'd have to employ some kind of system for drop-down country codes with formatting for each type.

**Comment by sanjuroj** [comment]
Doing something like checking that the response contains only numbers and a couple of characters like "." and "-", and checking for a minimum length would be really easy to do.  Full fledged validation would obviously be more involved.
