### ISSUE TITLE
Project initiation form is inheriting some styling change fallout

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1345]
The sites and stakeholders fields have shrank!

1. Go to projects > add project
2. Create a project, by filling out request approval and originator name fields
3. Select the option for approval to > Awaiting approval
4. Click save
5. go back to the Executive Summary Page

![Screen Shot 2019-04-04 at 11 06 15 AM](https://user-images.githubusercontent.com/23220180/55578256-50c54980-56ca-11e9-9158-2942d651234a.png)

**Comment by axoplasm** [comment]
@RickieT This is "fixed" but the fix has potential global visual regressions. Anywhere we use this particular widget (the `select2` multi-select widget) could be affected. A quick grep shows this widget in use in these places:

- [ ] IPTT quickstart
- [ ] Indicator results forms (e.g. “add result”)
- [ ] Workflow: import form (might not be used any more?)
- [ ] The Program/Country menu at the top of every page
- Three workflow forms:
     - [ ] Project Complete
     - [ ] Stakeholder
     - [ ] Import project agreement

I’ve kind of skimmed through these, can you double check them more thoroughly?

**Comment by RickieT** [comment]
@axoplasm ill make sure to run through those and whatever else I can click about with that might look similar when I get to this

**Comment by RickieT** [comment]
**QA - PASSED**
![image](https://user-images.githubusercontent.com/23220180/56051982-2e07e600-5d05-11e9-9663-5399ba572940.png)

I also combed through the mentioned areas by @axoplasm, and saw no issues: 
 IPTT quickstart
  Indicator results forms (e.g. “add result”)
  Workflow: import form (might not be used any more?)
  The Program/Country menu at the top of every page
Three workflow forms:
 Project Complete
 Stakeholder
 Import project agreement
