### ISSUE TITLE
Program permissions should restrict indicator data view in Sites module

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1348]
When a user visits the Sites module (by clicking Browse > Sites at the top navbar) they should see:

- [ ] All sites associated with any country in which they have access to at least one program. (Note: Sites are country-specific, not program-specific)
- [ ] Each site entry contains a link labeled "Indicator data", which produces a new screen when clicked.
- [ ] The Indicator data screen for each site is populated _only_ with indicators associated with program(s) to which the user has access. If a user clicks on a site's Indicator data popup, and that site only contains results from a program to which that user does not have access, the user should see nothing in the Indicator data popup. 

Example of an an indicator data seen for a user who has access to the VISTA program in the United States:
![Screen Shot 2019-04-05 at 7 14 20 PM](https://user-images.githubusercontent.com/38020496/55641698-2e6d2200-57d7-11e9-8716-6e9850f84984.png)

To test, you could associate a TolaData Demo result with the Catholic Charities site, restrict user permissions to each program, and test whether they see indicators/results for programs they don't have access to.

**Comment by jennyhavah** [comment]
@RickieT Hey, when you have a chance, can you let us know if this one needs work? (Trying to figure out if this is already done by Parthenon or if we need to do some work ourselves.)

**Comment by RickieT** [comment]
@jennyhavah I was planning on working in this yesterday and got distracted by a lot of other tickets, so I'll put this one at the top of my list right now

**Comment by RickieT** [comment]
**QA - Failures and Testing Notes** 
* **FAILURE:** For user mctest.low@gmail.com, I gave permissions to _every_ program in Afghanistan. I then went to Sites, and then clicked indicator data for Afghanistan, and the page was blank. 
* PASS - The user only saw sites information for the countries in which they had program access, so in this case, Afghanistan / USA 
* I noticed with program access to USA/AFGH - China is listed as a site in there, not sure why

**Comment by RickieT** [comment]
@jennyhavah I'm gonna close this ticket, as  https://github.com/mercycorps/TolaActivity/issues/1383 covers the issue found in this test verification ticket
