### ISSUE TITLE
Results creation not working in latest PA code

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1353]
When I try to add a Result, I get the message below.  The response (from the dev console) is `{"rationale": ["This field is required."]}`.

![Screen Shot 2019-04-08 at 12 37 56 PM](https://user-images.githubusercontent.com/6685499/55752953-0ad7f080-59fe-11e9-9838-4a260c2e8df4.png)

**Comment by axoplasm** [comment]
This is a side effect of 52d3548e

**Comment by axoplasm** [comment]
This is a failure of implementation in #1326 . I'm going to reopen that ticket & address it there

**Comment by axoplasm** [comment]
This should be fixed in PR #1354

**Comment by RickieT** [comment]
**QA - PASSED**
* Was able to successfuly create/edit results and attach them in indicators.
