### ISSUE TITLE
History table of Organization Admin is not properly reactive

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1355]
The history panel of the organization admin is retentive and/or non reactive.  

Scenario 1:  I was working on one organization and switched to creating another one.  After creating the new organization I click on the "Status and History" tab of the new organization. 
 The history panel improperly shows me the history of the organization I was working on before.
![Screen Shot 2019-04-08 at 5 08 25 PM](https://user-images.githubusercontent.com/6685499/55764964-72079c00-5a22-11e9-97db-5f35b46cab54.png)

The history panel displays the correct history once I've reloaded:
![Screen Shot 2019-04-08 at 5 08 56 PM](https://user-images.githubusercontent.com/6685499/55764969-7633b980-5a22-11e9-9c25-04a9cb690de9.png)

Scenario 2:  When I update an existing organization's status, I would expect the history panel to reactively add a row for the new status change.  But it doesn't add a row until you've refreshed the page.  

![Screen Shot 2019-04-08 at 5 09 26 PM](https://user-images.githubusercontent.com/6685499/55764983-821f7b80-5a22-11e9-9831-e350bac70d40.png)

![Screen Shot 2019-04-08 at 5 09 47 PM](https://user-images.githubusercontent.com/6685499/55764994-88adf300-5a22-11e9-8f73-086a1e552347.png)

Tagging @RickieT for confirmation.

**Comment by RickieT** [comment]
**QA - PASSED**
* Saving inactive/active status added the status change to the history table immediately after clicking save
* Changes made in the profile tab were reflected immediately in the table after clicking save changes, no page reload necessary
