### ISSUE TITLE
Should filter lists update when new item is added?

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1359]
Not sure if this is a bug or just a nice-to-have - in admin, add a user, click save, get confirmation that user saves, then in the filters that user doesn't show until you refresh the page.  Is this a bug?

**Comment by jennyhavah** [comment]
Tagging @RickieT -- wondering if this should be folded into #1366.

**Comment by RickieT** [comment]
@jennyhavah Yeah lets note all issues like this in #1366

**Comment by jennyhavah** [comment]
@RickieT Is this ticket covered by #1380? Should we close this one as a duplicate, or does it need to remain a separate ticket?

**Comment by RickieT** [comment]
Yeah it is and we should close this I forgot to come back and do that, was jumping between a lot of tickets today

**Comment by jennyhavah** [comment]
Closing this ticket because it is now covered in #1380.
