### ISSUE TITLE
Add a site: Remove asterisk on fields that are not required

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1360]
There are some fields in the "Add a site" form that appear to be required even though they are not. We need to:

1. Remove the * in the label above these fields; and
2. Remove any validation associated with these fields.

Here are the fields:

## Location tab
- [ ] Latitude
- [ ] Longitude

## Demographic information tab
- [ ] Average household size
- [ ] Average landholding size.

**Comment by kdubois22** [comment]
Would this be part of Sites?

**Comment by sanjuroj** [comment]
Yup, part of Sites.

**Comment by jennyhavah** [comment]
I took a closer look at these fields, and it turns out they _are_ required fields. What threw me is that I don't have to enter anything in there. And that's because they put a default value of 0.00 in both cases. I question that approach, but... That's more of a UX issue, and not a validation bug. Closing this ticket as invalid.
