### ISSUE TITLE
Indicator setup modal on the Demo server: Fix TolaWiki link

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1361]
The following applies to the demo server, not Production.

From LJ and Marie in Slack:

In the Indicator Setup modal, there is a “Help” link in the lower right hand corner of the modal. This link needs to point to the TolaWiki and _not_ to the Google Doc.

The link is: https://learn.mercycorps.org/index.php/TOLA:Section_05/en#TolaActivity_Form_Guides

**Comment by RickieT** [comment]
**QA - PASSED** 
* On demo, I am taken to the wiki link, and not the google doc
![Screen Shot 2019-04-15 at 11 41 10 AM](https://user-images.githubusercontent.com/23220180/56157046-64e33380-5f73-11e9-9d9e-46ffa3ad3880.png)

**Comment by RickieT** [comment]
@jennyhavah this is fixed on the demo server, however, this ticket is flying in the PAPAYA project, so I'm not sure where we wanna stick this, I'm assuming this should be fixed in all environments at some point, and in production.

**Comment by jennyhavah** [comment]
@RickieT My understanding is that this only applies to Demo, and that it is fine in Production.

**Comment by RickieT** [comment]
@jennyhavah oh, okay then. nevermind
