### ISSUE TITLE
Check for reactivity in admin

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1366]
Based on the experience in #1355, it's possible that other features in the new admin panel are not reactive.  We need to do a broad check for reactivity in the admin panel.

**Comment by jennyhavah** [comment]
@RickieT Would you be able to take on this systematic review and let us know where else (if anywhere) we need to address a lack of reactivity in the admin?

I'm wondering if #1367 is an example of this.

If the workaround is always to refresh the page, then it becomes a question of: Will the user instinctively know to do this, or are they going to think it's broken and send us a support request? 

My criteria for whether this rises to the level of a release blocker would be whether or not it will create major training and support headaches. I think @hannalcamp should make the call, once we have a better sense of the scope of the problem.

**Comment by RickieT** [comment]
@jennyhavah Im going to move this into "doing". Any page where I find this to be an issue (just found one in the programs page) I will file a new ticket and add it to the "this release" column.

Once I've covered all the pages thouroughly, I will link any relevant tickets and close this. 

Let me know if you have other suggestions for handling this

**Comment by RickieT** [comment]
**Review Completed:**
Admin > Users: 
* User changes/creations were immediate upon saving
* New history was instantly available upon changing user information and clicking save
* ***User _could not_ be searched in filters until page reload

Admin > Programs:
* Could edit/create programs and see changes immediately when I click save
* ***(#1379 )History changes were not reactive, page reload required to see new changes
* *** Program not immediately searchable, required page reload

Admin > Countries:
* Profile: updated immediately when changing all fields
* Added a new country, and it showed up and was immediately editable, no page refresh
* ***_Could not_ be searched in country filter until page was reloaded, though. 

Admin > Organizations (recently fixed):
* Could update/edit org information, see it update immediately upon clicking save
* Could create a new org and see it available within the table upon clicking save
* Could view immediate changes to org in the history tab
* ***Page reload necessary to filter for new org created

Seems the re-occuring theme here is the issue that when created, the new item, is not immediatley searchable without reload, all other aspects seem reactive that have not already been documented. I'll create a new ticket to cover this issue for all pages.

**Comment by jennyhavah** [comment]
Sounds good, @RickieT. Does the new ticket cover everything Cameron reported in #1368, #1359, and #1367? Can we close them as duplicates?

**Comment by RickieT** [comment]
@jennyhavah #1368 and #1367 I am still trying to replicate at the moment
