### ISSUE TITLE
Indicators page > Data/evidence table not including project name when the data is entered from a project tracking form

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#137]
**ACCEPTANCE CRITERIA**

**Test the fix on all four of these**
~~Affects the indicator table at the top of the following:~~
~~1. Project initiation form -- long version~~
~~2. Project tracking form -- short version~~
~~3. Project tracking form -- long version~~

~~**Acceptance criteria for collected data record**
The Project menu only lists Project Tracking forms, no Initiation forms.~~

~~**Acceptance criteria for Initiation form (long version)**~~
~~1. There is no Add link at the bottom of the table.
2. There is no Edit or Delete link next to each indicator name.
3. There is no Targeted or Achieved column.
4. Any existing linked indicators still show up.~~

**Acceptance criteria for Tracking forms (Long and short versions)**
~~. There is no Add link at the bottom of the table.
2. There is no Edit or Delete link next to each indicator name.
3. There is no Targeted or Achieved column.
4. When I link a Collected Data record to a project tracking form, the associated indicator shows up on the tracking form.~~

~~**Acceptance criteria for Indicators page**~~
~~1. If a project only has an initiation form, it shows up in the Project column.
2. If a project has both an initiation and a tracking form, the tracking form shows up in the Project column.~~

**Don't do this now, wait to see if teams want it**
We may create a script to copy over any indicators from initiation forms to any existing tracking forms. This could save time, but also would overwrite any indicators people had manually added to tracking forms. So we want to check first and make sure that this is desirable.

**BACKGROUND**
See indicator https://tola-activity.mercycorps.org/indicators/indicator_update/4795/

![image](https://user-images.githubusercontent.com/33670923/37120335-f6d5d20a-220e-11e8-8f57-c82228adfaa5.png)

From Emily: I added the data above (7 actuals) via a project tracking form and it added it to this indicator but then it doesn't show which project the data record came from. The Project column is empty. Def not urgent but I wanted to flag nevertheless.

Note: We should make sure that the fix works for both Project Tracking and Project Initiation forms, as I believe you can add data from either one. We should also make sure it works for both short and long versions of the forms.

**Comment by mahmoodkhan** [comment]
Currently we only have a list of `Project Initiation` forms listed in the `Project`dropdown under the Data Record modal. So when a user links an indicator from the `Project Tracking` form, the indicator page does not display that. Another issue is that users can use the `Project Form` to report actuals against an indicator as an alternate method, which is problematic because it doesn't let users report data in disaggregate fashion and it also does not have the necessary checks and validations

**Comment by jennyhavah** [comment]
As it turns out, the collected data record form that you access from the Project form has serious issues. We already knew that it only shows a few fields, not the comprehensive record they get from the Indicators page. What I'm really worried about is that they are asked to manually select a target, where the system is supposed to automatically assign it based on the date... and THERE IS NO DATE FIELD!!!!

If we could simply swap out the shorter data form with the full form, that would be a quick way to resolve the issue. But for technical reasons Mahmood can explain, we can't do that. We certainly don't want to invest time rebuilding the exact same form in Workflow, with all of its complicated functions related to periodic targets.

I've been saying for a some time that we shouldn't even be adding/editing data from the Project form -- it's a very confusing task flow, and gives a mistaken impression that there is such an object as a "Project indicator" with its own data, separate from the program indicator.

Bottom line: We would like to remove the Add, Edit, and Delete functionality from all indicator tables on project forms. You'll still be able to see indicators that are added via data collected records... and going forward, you will always enter data from the Indicators page.

Emily, this will require some strategic communications with Afghanistan and Timor Leste... The gist of it is:
1. It's important that the data collection form be consistent and comprehensive, and that there be no confusion about where to enter data. 
2. The form they're currently using does not include all of the periodic targets functionality we've implemented, and it's currently possible to accidentally assign the wrong target, which is not a problem elsewhere.
3. Going forward, after this patch release it will ONLY be possible to add new data records by clicking on the Indicators page "New data" button.
4. We are going to remove the Add, Edit, and Delete links from all project forms.
5. They will not lose access to information about linked indicators -- it will still appear. That table will be automatically built as they add new data from the Indicators page. 
6. Going forward, they'll only be able to associated project TRACKING forms with indicators, not project initiation forms.
7. Mahmood will run a script to look for any initiation forms that have indicators associated with them, and automatically associate them to the same project's tracking form. This is actually a bonus, because they'll no longer have to re-assign projects to indicators when they approve a project.

**Comment by mahmoodkhan** [comment]
@jennyhavah @esinn So my understanding is that 
1. we will remove the "add/edit/delete" functionality for indicators data in project forms.
2. link `project tracking` instead of `project initiation` in the data record form in the indicators section
3. write a script that links the corresponding `project tracking` with indicators
