### ISSUE TITLE
Introduce password security rules

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1378]
Reported by Cameron: Should we have business rules for passwords? Partner passwords can be "123".

Suggested by Sanjuro: Doing something like checking that the response contains only numbers and a couple of characters like "." and "-", and checking for a minimum length would be really easy to do. Full fledged validation would obviously be more involved.

**Comment by jennyhavah** [comment]
@hannalcamp Would you consider the ability for external users to easily create insecure passwords to be a release blocker?

If yes, we'll need to huddle right away how strict the rules ought to be.  

If not, I would still recommend we flesh out requirements but would move the ticket to Poblano.

**Comment by hannalcamp** [comment]
I would not consider it a release blocker but I would place it at the top of the Poblano priority list, i.e. if we can get anything from the backlog into papaya prior to release let's make it this.

**Comment by jennyhavah** [comment]
I'm going to leave it in To Do in Papaya so it stays on our radar and someone can grab it as a stretch goal. I copied over @sanjuroj's suggestions for a minimal approach.

@sanjuroj or @camgnostic, if either of you decide to grab this, I'll leave it to you to flesh out the details of the ticket with your specific recommendations. (I think you're better placed to efficiently and thoroughly write the business logic on this one than I am.)

**Comment by sanjuroj** [comment]
There are two separate issues here.  One is phone number validation, the other is password strength validation.  My suggestion of minimal checking was for phone numbers.  I would suggest we try to time-box (<=1 hr?) some basic password strength validation for this release and improve it later if need be.  Django has some built in password validators that we can probably add quickly.

**Comment by axoplasm** [comment]
Here's a lead: https://docs.djangoproject.com/en/1.11/topics/auth/passwords/#password-validation

**Comment by axoplasm** [comment]
Per @RickieT:
> Resending the registraiton mail to a user essentially works as a password reset

**Comment by jennyhavah** [comment]
Carrying this over from Slack thread: https://mercycorps.slack.com/archives/C4SAGL55M/p1555446806140800

This is the page where an end user resets their password:
https://files.slack.com/files-pri/T02FWKRC6-FHY3JF2FP/screen_shot_2019-04-16_at_2.11.49_pm.png

We need to introduce password security rules to this page. @axoplasm has some ideas for this, including setting a minimum character length.

@axoplasm want to make a recommendation?

**Comment by axoplasm** [comment]
Peripheral issues here are related to #1411 . Perhaps we need to start an epic for login/auth flow.

The only salient problem for *this ticket as read literally* is 

> 2. What rules should we enforce?

I propose:

1. Minimum length (maybe 12 characters?)
2. Django’s attribute similarity filter (checks against username, email, other fields on user.auth & classes that inherit User)

It’s been a few years but the last time I had to do validation the usual thinking was that applying too many password rules led to LESS secure passwords bc 

1. ppl are more likely to reuse simple passwords that pass *everyone’s* rules
1. randomly-generated passwords e.g. from 1Pass or Keychain are more likely to violate those rules
2. they introduce predictability into possible brute force vectors (e.g. if I’m a black hat I know we don’t have to try all-numeric passwords because the SYSTEM TOLD ME SO)

**Comment by jennyhavah** [comment]
@hannalcamp Okay to defer this ticket, as it is related to 1411 that you moved to Deferred?

**Comment by hannalcamp** [comment]
Yep good to defer.

**Comment by axoplasm** [comment]
For the moment we'll resend the registration email for password resets. While I'm in here I can update this screen

![image](https://user-images.githubusercontent.com/169060/56381355-745bba00-61c9-11e9-8f1d-f4f05450f3b5.png)

**Comment by axoplasm** [comment]
This applies two security policies to passwords set either in the Django admin or the registration email (above). The policies are:

* At least 9 characters
* Not similar to email, first name or last name fields

 I had to write a custom error message for the second policy: *“The password is too similar to information in your user profile.”* Please advise if we'd like to do something a little different.

I think we should make a note of this in the login flow mini-epic (#1411) & revisit it then. The way the validations are handled here is not ideal & requires a trip to the server each time. you get the errors in order, so it could take up to three tries to get a valid password.

**Comment by jennyhavah** [comment]
@axoplasm Sounds good! My only suggestion is to be more specific in the warning for the second policy, because most end users don't know what's in their profile. (Only admins can see those.) Alternative suggestion: 

Please enter a password that does not include elements of your name or email.

**Comment by jennyhavah** [comment]
Moving back to Doing until @axoplasm takes a look at my suggested text tweak.

Also, Paul, how do I go about accessing this page to QA the validation?

**Comment by axoplasm** [comment]
1. With a superuser admin account, create a new user account with a throwaway email address that you have access to
2. New user should receive an email with a link to the reset page
3. log your superuser out and click on the link

If you need to test it again, you can click "resend registration email" on the status tab for the new user.

Try the following variations:

1. passwords don't match
2. password too short
3. password using one of the forbidden fields

**Comment by hannalcamp** [comment]
@axoplasm When I try to set a password of 111111111111 for an account, it gives me an error and says "Please choose a password that does not include elements of your name or email." This is after I did try to set a password that included elements of the name ("Tolatest Sharklasers"). Wondering if the error message isn't updating?

**Comment by axoplasm** [comment]
Because if the way this is coded (not ideal, but I’m kind of loathe to monkey with logins RN) we can't pass along the exact error message for that particular error. The default (i.e. “real”) Django error message is a little more useful, as it tells you which field it’s too similar to.
 
Did it accept your attempt to use parts of the username?

If this is a blocker, we could remove that requirement (“too similar”)

**Comment by hannalcamp** [comment]
Actually no password setting is working for me. I'm on incognito mode trying to set/reset it for email accounts tolatest@sharklasers.com & mctestnongmail@yahoo.com.

**Comment by axoplasm** [comment]
You're not able to change your password _at all_?

**Comment by hannalcamp** [comment]
Getting this error message for any password I try to set. 
![Screen Shot 2019-04-19 at 10 21 56 AM](https://user-images.githubusercontent.com/38020496/56433092-0678c680-628d-11e9-984f-c1c9478f1dce.png)

**Comment by axoplasm** [comment]
Gaaah. This totally worked yesterday. I'll need to get back into this today

**Comment by axoplasm** [comment]
Hey I'm working on this now and I notice something goofy, security-wise. We might want to rethink the entire "registration email" workflow. I'm going to ping the dev channel for their opinion.

**Comment by axoplasm** [comment]
Closing this loop: I've fixed this in such a way that we can change our password standards pretty much at whim.

**Comment by RickieT** [comment]
**QA - PASSED**
When resetting password, I could not:
* Set a password with less than 9 characters
* Set a password that was similar or the same as my email
* Set a password that did not match in both fields

I could login with my new password, and my old password no longer worked.
