### ISSUE TITLE
programs/users/countries/orgs created in admin pages are not immediately searchable via filter

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1380]
As part of #1366 investigations, also closes (#1366):

**Admin > Users:**

- [x] Newly created User could not be searched in filters until page reload

**Admin > Programs:**

- [x] New Program not immediately searchable, required page reload

**Admin > Countries:**

- [x] New Country could not be searched in country filter until page was reloaded

Admin > Organizations (recently fixed):

- [x] New Org not immediately searchable in filter until page is reloaded

**Comment by sanjuroj** [comment]
Programs, Orgs, and Countries should be fixed now.  @RickieT, I couldn't replicate the non-searchability for Users.  It gets added to the end of the list, so it's hard to scan but I can still search for it.  Can you confirm that this is an issue when creating Users?  If it's not, then this is ready for QA.

**Comment by sanjuroj** [comment]
Also, in the original description should this

> Admin > Countries:
> 
>   New Program could not be searched in country filter until page was reloaded
> 

be this?

> Admin > Countries:
> 
>   New **Country** could not be searched in country filter until page was reloaded

**Comment by RickieT** [comment]
> Also, in the original description should this
> 
> > Admin > Countries:
> > New Program could not be searched in country filter until page was reloaded
> 
> be this?
> 
> > Admin > Countries:
> > New **Country** could not be searched in country filter until page was reloaded

Yeah, typo there, should be country

**Comment by RickieT** [comment]
**QA - PASSED**
* Checked Programs/Countries/Orgs/Users and was able to filter without page reload.
