### ISSUE TITLE
Indicator Data not showing up on Sites

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1383]
**This closes** 1348

In production, Afghanistan site does show indicator data, as user mctest.low@gmail.com with access to all programs in Afghanistan, I clicked Indicator data for Afghanistan, and was not able to see the indicator data. 

In order to confirm indicator data is not showing up in indicator data through sites a user does not have access to, this issue needs to be resolved.

**Comment by KennyMonster** [comment]
@RickieT @hannalcamp Something to note with this view: only Programs->Indicators with Results that are directly linked to a Site will show up here. If no Results are linked to the Site, you may get an empty list even if you have access to all Programs.

The form field linking a Result to a Site:

![Screen Shot 2019-04-12 at 12 31 42 PM](https://user-images.githubusercontent.com/1278224/56063192-7209e380-5d23-11e9-8afb-6776458df19b.png)

**Comment by RickieT** [comment]
Hey, were seeing indicator data here now on sites. 
![image](https://user-images.githubusercontent.com/23220180/56065030-8dc3b880-5d28-11e9-9c2e-2f088e329d8e.png)

@KennyMonster are you referring to a bug or a limitation of some sort?

**Comment by KennyMonster** [comment]
It's not a bug, just an implementation detail that differs a bit with what Hanna was describing in #1348, namely that this is a view of Results (grouped by indicates and programs) linked to a site, and not a list of all indicators associated via programs to a site.

**Comment by RickieT** [comment]
**QA - PASSED**
Site data is now displayed, moving to ready for deploy
