### ISSUE TITLE
Weird wrapping of admin views on smaller screens

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1384]
I'm looking at the Admin on my laptop at 100%. Here's what I see:

![image](https://user-images.githubusercontent.com/33670923/55988467-cdbb6a80-5c58-11e9-9cbc-7bf07ea1bdff.png)

Scrolling down...

![image](https://user-images.githubusercontent.com/33670923/55988497-de6be080-5c58-11e9-99b2-d74e8b39917a.png)

This reminds me of a similar issue Paul fixed in the IPTT report during Winterhawks.

**Comment by RickieT** [comment]
**QA - PASSED**
* At 100% I am unable to reproduce this issue
