### ISSUE TITLE
IPTT: "Change log" should be sentence case

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1387]
"Change log" should be sentence case, like all of our text buttons

### ADDENDUM
we need to add a little vertical padding around this button as it can be covered by the horizontal scrollbar on some viewports

![image](https://user-images.githubusercontent.com/33670923/55989968-5cc98200-5c5b-11e9-88a2-89e0de82df03.png)

**Comment by jennyhavah** [comment]
@axoplasm I am putting this in Poblano because I don't consider it a Papaya release blocker, but wanted to bring it to your attention so you get to make the final call.

**Comment by axoplasm** [comment]
Let's leave it in Papaya bc that will be a good time to fiddle with the vertical space around that button

**Comment by RickieT** [comment]
@axoplasm I am not seeing this change on Dev2 right now

**Comment by RickieT** [comment]
**QA - Failed**

* Still reads "Change log"

**Comment by jennyhavah** [comment]
@RickieT That's what we want. It is now sentence case.

**Comment by RickieT** [comment]
Oh my mistake. Or course. In that case pass!
