### ISSUE TITLE
No error message for user with wrong U/P combo on login page 

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1390]
For the third option on login page, log in with username and password, if the user enters the wrong credentials, the page reloads and not provided with any error message:
![login_wrong_u_p](https://user-images.githubusercontent.com/23220180/56051816-aae69000-5d04-11e9-8ecc-07d9b486753d.gif)

**Comment by KennyMonster** [comment]
@RickieT I'm working on this now as part of #1342

**Comment by RickieT** [comment]
@KennyMonster my mistake, lets close this as a duplicate
