### ISSUE TITLE
Potential sorting issues in dropdowns.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1393]
There are two areas where sorting of dropdown lists might be improved:
- [ ] Organizations in filter panel on all four admin pages
- [ ] Country dropdown on program creation 

The filter dropdown list for Organizations is currently sorted by create date as far as I can tell. This is currently true for all four admin pages. 

<img width="1280" alt="Screen Shot 2019-04-12 at 2 00 39 PM" src="https://user-images.githubusercontent.com/6685499/56066084-9669be00-5d2b-11e9-911c-6e147ee458ee.png">

Country dropdown in Program create/edit pane
<img width="244" alt="Screen Shot 2019-04-12 at 3 20 26 PM" src="https://user-images.githubusercontent.com/6685499/56069170-a33fdf00-5d36-11e9-86d0-a0f942416a56.png">

**Comment by jennyhavah** [comment]
@sanjuroj Is this potentially a duplicate of #1336?

**Comment by sanjuroj** [comment]
Ah, yes, partially, I didn't notice #1336.   What may not be highlighted on #1336 (I can't quite tell what the second item on the list is) is the drop downs in the creation/editing of individual records.  How about I just add that to the list on #1336 and close this ticket as a dupe?

**Comment by jennyhavah** [comment]
@sanjuroj Sure, let's do that. Thanks!

**Comment by sanjuroj** [comment]
Closing in favor of #1336.  Relevant section of this ticket copied over to that one.
