### ISSUE TITLE
Collapse on save in when creating new Country?

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1395]
Unlike Program, User, and Org admins, when you add a new Country, the editing window collapses on save, which means you have to click on it to expand again to provide data for the other two tabs. It's possible that fixing the disappearing act the new country does (#1394) will change this behavior, but if it doesn't, would it be better to leave it expanded and enable the two other tabs on save?

**Comment by jennyhavah** [comment]
@sanjuroj To make sure I understand, is the expand/collapse behavior different in the other Admin areas, when you add a new thing?

**Comment by sanjuroj** [comment]
Yes, the other Admin areas stay expanded.

**Comment by jennyhavah** [comment]
@hannalcamp I'm going to defer to you on this one, not having spent much time in the Admin UI or having a sense of how annoying or confusing this would be. 

If you consider it a release-blocker, please move to This Release.
If not, please move to Deferred.

**Comment by hannalcamp** [comment]
Moving to deferred.

**Comment by axoplasm** [comment]
This is indeed related to #1394 and fixed on the same commit

**Comment by RickieT** [comment]
**QA - PASSED**
* New country stays open on creation now
