### ISSUE TITLE
status and history shows old data after Program and Org creation

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1396]
When creating an Organization or Program, after creation is successful, if you go to the Status and History tab, the history of the last thing you visited is shown, rather than the history of what you just created.  Examples are below. Users seems to function correctly but should probably be checked.

First visit an existing Organization
<img width="1280" alt="Screen Shot 2019-04-12 at 3 38 04 PM" src="https://user-images.githubusercontent.com/6685499/56069769-645f5880-5d39-11e9-8199-7052914fd2e1.png">

Then create a new Org
<img width="1280" alt="Screen Shot 2019-04-12 at 3 38 35 PM" src="https://user-images.githubusercontent.com/6685499/56069776-6aedd000-5d39-11e9-8f8d-a0c4dc1fc980.png">

Then visit the Status and History tab.  The prior Organization's history is still there.
<img width="1280" alt="Screen Shot 2019-04-12 at 3 38 46 PM" src="https://user-images.githubusercontent.com/6685499/56069790-7d680980-5d39-11e9-8caf-92b3b355c782.png">

Same is true of Program.  Switching to history tab right after creation shows wrong history.
<img width="1280" alt="Screen Shot 2019-04-12 at 3 30 32 PM" src="https://user-images.githubusercontent.com/6685499/56069550-6379f700-5d38-11e9-89ce-ae309141bb34.png">

**Comment by jennyhavah** [comment]
Yikes, the wrong history being shown in the history tab... sounds like something we ought to fix. Moving to This Release.

I wonder if this ought to be tested systematically on any other types of actions besides Creation, and if Users might be affected in some way as well.

Tagging @RickieT to investigate further and @hannalcamp who is back in town!!

**Comment by RickieT** [comment]
@sanjuroj @jennyhavah Yeah I reproduced this issue just now.

Note: This does not occur if when first landing on the page, you click Add Program.

**Comment by RickieT** [comment]
**QA - PASSED**
* I am no longer able to reproduce the issue as written.
