### ISSUE TITLE
No green success popup after Program or Country creation

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1397]
Users and Organizations have a green popup success message when a new entity is created.  Programs and Countries do not.

**Comment by jennyhavah** [comment]
Moving this one to This Release because it's important to have consistent system feedback when an object is created.

**Comment by RickieT** [comment]
**QA - PASSED**
Programs:
![Screen Shot 2019-04-15 at 10 34 55 AM](https://user-images.githubusercontent.com/23220180/56153016-1f6e3880-5f6a-11e9-8e02-90750bfa6e1f.png)

Countries:
![Screen Shot 2019-04-15 at 10 35 20 AM](https://user-images.githubusercontent.com/23220180/56153041-301eae80-5f6a-11e9-8d3a-8f59290b8a95.png)
