### ISSUE TITLE
Users: "Save and add another" button is broken

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1400]
Split off of #1399.

In the Users section, the Save and add another button doesn't result in a blank creation template the way the Organization Save and add another button does.

**Comment by RickieT** [comment]
@KennyMonster This is now fixed, but has regressed the fix for the reactivity on the users page in #1380 

After I create a few users, they can't be found in the list until the page is reloaded

**Comment by KennyMonster** [comment]
This should be fixed now as well. Turns out the codepath for the "Save and add another" was broken and out of sync with the normal save path :(

**Comment by RickieT** [comment]
**QA - PASSED**
* Reactivity returned
* Template now reset when clicking save and add another
