### ISSUE TITLE
Global for all PNotify confirmation and rationale prompts: Auto-scroll page down to make prompt visible

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1405]
# Affects
Any place in the app where we prompt for a rationale or for confirmation prior to destructive action.

# Issue
I think that a button is broken because the system doesn't appear responsive, when in fact, there is a warning confirmation or rationale prompt below the fold where I can't see it.

# Acceptance criteria
The form auto-scrolls down so that I can see the confirmation or rationale prompt in the following locations.

- [x] 1. Indicator setup form
- [x] 2. Result form

... I believe those are the only two forms where we have these prompts, but if you think of any others, please add to the ticket!

**Comment by jennyhavah** [comment]
Note: I'm adding this ticket to the release because otherwise, we are likely to get a flood of "THIS BUTTON IS BROKEN" complaints. I, myself, almost filed a "This delete button is broken" ticket just now because I didn't see the prompt and the "Delete all results" button appeared non-responsive.

@camgnostic thinks it will be a relatively easy fix.

**Comment by KennyMonster** [comment]
So I think I have this done but it's very possible I missed a confirmation box as I'm not super familiar with all of them. It should be easy enough to fix though if there is a case I missed.

**Comment by jennyhavah** [comment]
@KennyMonster Cameron is working on some prompts related to target deletion and indicator deletion. @camgnostic Can you let us know when those are all in place, so that we can make sure they scroll down as expected?

Moving this back to Doing until then.

**Comment by KennyMonster** [comment]
@jennyhavah It occurred to me that the scroll to bottom functionality is only working on the modal version of the indicator update form, and not the full page version. If I remember right, this full page version is going away in Satsuma. Would be ok to not implement this for the full page version?

**Comment by jennyhavah** [comment]
@KennyMonster I just now was testing deletion on that full page form and momentarily thought I had an unresponsive system... because the warning was out of sight.

If it is not more than 15-20 minutes to implement, I'd say it's worth doing. It could be end of June before Satsuma is released.

**Comment by KennyMonster** [comment]
I ended up implementing on the full page indicator form, so this can be tested now as well.

**Comment by RickieT** [comment]
**QA - PASSED**
* Indicator modal scrolls down
* Indicator page (when creating new) scrolls down as well for the confirmations
