### ISSUE TITLE
Possible to create multiple duplicate indicators by rapidly clicking “Save Changes“ on the interstitial (“Custom or DIG”) screen

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1408]
This is a bug on __all environments__ including __Production__.

Steps to reproduce:

1. Click on “Add indicator” on a program page
2. On the “Add indicator” page, provide a name and select “Custom indicator”
3. Rapidly click “Save changes” several times.

Result:

![image](https://user-images.githubusercontent.com/169060/56172702-878b4180-5f9f-11e9-9aab-b96d5d2cac91.png)

**Comment by jennyhavah** [comment]
Based on this Slack thread and the thumbs up on my suggestion, moving this ticket to Poblano. 

https://mercycorps.slack.com/archives/C4SAGL55M/p1555372916101300

**Comment by jennyhavah** [comment]
Closing ticket because this interstitial page no longer exists.
