### ISSUE TITLE
Bootstrap v4 UI styling: Top and bottom nav

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#141]
Note for Paul: This ticket includes reorganization of some navigation elements in addition to styling. Feel free to break out into separate stories if that's easier.

![topnav_winterhawks](https://user-images.githubusercontent.com/33670923/38451246-84f755ec-39e1-11e8-903b-4994289d721f.png)

# Top nav

## Reorganization of links and menus
- [x] Top nav link order should be Indicators, Browse, Reports
- [x] Under Browse should be these options in the following order: Documents, Projects, Sites, Stakeholders
- [x] Projects should take you to what we're currently calling **Program Index**…
- [x] …with that page title renamed to **Projects**
- [x] Change Firstname Lastname on the right side from a dropdown menu to a simple link that takes you straight to the profile page. 

## Styling
- [x] We talked about having the top nav be fluid across the app, not just the IPTTs.
- [x] Please take a look at the _Browse_ and _Reports_ drop down menus. They don't seem well integrated with the nav bar and kind of read like a pop-up dialogue. No strong opinions on how it should look, but here's what I mocked up, modeled on mercycorps.org 
![image](https://user-images.githubusercontent.com/33670923/40261263-6e5a0fac-5ab4-11e8-8af5-27ad2776b457.png)

# Bottom nav
![image](https://user-images.githubusercontent.com/33670923/37685881-62ce4288-2c52-11e8-90b6-e6c0e5282543.png)

- [x] Unstick the bottom nav. Let it be free!
- [x] Please take a look at the items on the right side separated by pipe characters. The spacing looks a bit tight to me, and the pipes look like they're darker than the text. If they're not going to match, my inclination would be to go a shade lighter instead of darker.

**Comment by axoplasm** [comment]
Renaming the __Program Index__ page to __Projects__ raises a couple of questions:

1. This is a global change, there are several pages with hardcoded breadcrumbs using “Program Index”. __Is is safe to do a global change for these locations?__
2. This string (and many others in breadcrumbs, navs, and page titles) are note localized. __Should I be localizing these strings?__

**Comment by axoplasm** [comment]
…To answer both my questions: 

1. Yes
2. Yes

**Comment by jennyhavah** [comment]
Can we make the top nav links higher contrast in resting state?

**Comment by jennyhavah** [comment]
The following is something that can definitely wait if it's more efficiently tackled as part of a systematic look at responsiveness -- just let me know either way.

When the browser is narrowed, the downward-facing arrows wrap to a new line:
