### ISSUE TITLE
Use email instead of username to log in

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1411]
# Steps to reproduce

1. In the new Admin console, go to any user profile for which you know the login email and password, update the email address and save changes. 

2. Open an Incognito window and try logging in with the new email and the old password.

You'll get an error message that the login or password were incorrect. The only way I was able to fix it was by finding the account in Django admin and manually updating the Username to match the updated email address.

The problem is that, as a Basic Admin managing external user accounts, I can update someone's email address but I cannot go into Django admin to update the Username. That means the Tola team (and eventually IT) is going to get contacted anytime this occurs.

# Proposed solution

If I update my email in the new admin, then Django automatically updates the username field to match.

Don't know how hard this is or if this introduces other potential issues...

**Comment by jennyhavah** [comment]
This _seems_ like an edge case that can be deferred, but I want to validate that with @hannalcamp. 

What it means for the time being is that if someone were to change their email address and have trouble logging in, a Tola team member would need to help then; their country's Basic Admin wouldn't be able to.

**Comment by axoplasm** [comment]
This is due to two issues:

1. Django admin only lets you log in with your username
2. Users created via admin lite automatically get their username assigned as the email given when the user is created. 

So I’m not logging in with my *email* I’m logging in with my *username* which just happens to be the exact same string of characters as my email. When an admin changes the email field they are not simultaneously changing my username.

Let’s spike this with a few possible solutions:

1. hack the Django login to use **email** not **username**
    * Is the email field unique?
    * Does everyone have a (valid) email address?
    * Legacy & Okta users too?
2. automatically change the username field when the email field changes
    * What happens to legacy/Okta users?

**Comment by axoplasm** [comment]
per @KennyMonster: Duplicate & empty emails:
![image](https://user-images.githubusercontent.com/169060/56231925-717b9080-6034-11e9-85ba-f670e519ce4b.png)

**Comment by axoplasm** [comment]
Looks like emails are required and there is some enforcement of uniqueness in `tola/admin.py`. Doesn’t mean those are enforced in the DB though. I’d guess those ~30 or so users were created before this was built into the admin.

```python
# use these form classes to enforce unique emails, if required
class UniqueEmailForm:
    def clean_email(self):
        qs = User.objects.filter(email=self.cleaned_data['email'])
        if self.instance:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.count():
            raise forms.ValidationError(
                'That email address is already in use')
        else:
            return self.cleaned_data['email']


class MyUserChangeForm(UniqueEmailForm, UserChangeForm):
    email = forms.EmailField(required=True)


class MyUserCreationForm(UniqueEmailForm, UserCreationForm):
    email = forms.EmailField(required=True)
```

**Comment by axoplasm** [comment]
OK. I think we can do this:

1. Clean up the ~30 addresses that violate uniqueness/nullness. I suspect these are all inactive.
2. Add DB constraints to enforce uniqueness and NOT NULL on the email field. This will probably require: 
    1. bypassing the ORM (?)
    2. adding error handling for the edges (e.g. `manage.py`) where users might be created outside the admin interfaces
3. Create a custom backend that validates on email per https://docs.djangoproject.com/en/1.11/topics/auth/customizing/

**Comment by axoplasm** [comment]
Here are the problematic emails per a recentish (about a month old) DB dump:

![image](https://user-images.githubusercontent.com/169060/56235610-9b38b580-603c-11e9-8dcd-289246321bd3.png)

Only users `iprayoga`, `flfatima`, and `ashoukat` have logins in the last 18mos

**Comment by hannalcamp** [comment]
I'm in favor of the solution you documented - I think there's a chance (small) that partner users will need to have their email changed, or corrected after initial entry by an admin. Having the email be the username to me is the simplest way to handle those edge cases. But I agree it's not a release blocker.

**Comment by axoplasm** [comment]
This is closely related to #1378. Maybe we should make this an epic & defer?

**Comment by axoplasm** [comment]
This comment from #1342 succinctly covers work we’ll need to do to smooth the Django auth flow:

@jennyhavah An error message on failed login should be easy enough.

Password reset workflow is a whole thing though, and wanted to verify that the stock Django workflow is desired and worth the time investment. From memory, I think the workflow is:

> * user clicks link that they forgot their password
> * they are taken to a form where they type in their email
> * user is sent to a page saying an email is sent (or something went wrong)
> * an email is sent to the user containing a link to a page where they enter in a new password
> * the user clicks the link, types in their PW twice, and submits
> * a success page is shown saying the reset succeeded

**Comment by axoplasm** [comment]
I have a partial solution to this problem, or at least one that doesn’t lie to users and admins. I’ve explicated the username in the Admin Lite interface:

![image](https://user-images.githubusercontent.com/169060/56473564-e4647d00-6421-11e9-90ad-405a6802a74d.png)

I've also changed the frontend behavior when creating new users. Admins will have to provide a username for the new user, instead of auto-generating a username based on the email address.

This partial solution has some advantages:

1. doesn't significantly affect backend logic
2. doesn't require changes to the database
3. doesn't require a new auth backend
4. is obvious if not particularly intuitive

**Comment by RickieT** [comment]
**QA - PASSED**
* Email field must be unique validated: 
![Screen Shot 2019-04-23 at 11 32 27 AM](https://user-images.githubusercontent.com/23220180/56606627-84094300-65bb-11e9-941f-dea79d0f36b3.png)
* Changed USERNAME field to thisISaTESTusername, and saved. I was able to login with the new username with my same password. I was also able to set the username field to the email without issue, and use that as my login username as well.
