### ISSUE TITLE
Add an event target: Prompted for a rationale

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1414]
This issue was discovered by @camgnostic as he was working on event deletion

# To reproduce the issue

1. Find (or create and save) an indicator with one or more Event targets.
2. Reopen the indicator and visit the Targets tab
3. Click "Add an event" button just underneath the target table.

**Expected behavior:** A new event row is added.
**Observed behavior:**

1. I'm prompted for a rationale, as if I had clicked the save button, like so:
![image](https://user-images.githubusercontent.com/33670923/56177536-dba02100-5fb3-11e9-96fe-19dbe17f6521.png)

2. If I fill out the rationale field and click OK, I get no system message, but the new event row is added.

# Acceptance criteria

- [ ] 1. If I click "Add an event", a new event row is added, just as it happens on Production
- [ ] 2. If I complete required fields -- event name and target value -- and click _Save changes_, then:
     - [ ] 2.1. IF there are no linked results, THEN I get the usual "Success, form data saved" message.
     - [ ] 2.2. IF there are linked results, THEN I am prompted for a rationale AND the change is logged in the program's change log, including the rationale.

**Comment by RickieT** [comment]
**QA - PASSED**

- [ ]  1. If I click "Add an event", a new event row is added, just as it happens on Production
- [ ]   2. If I complete required fields -- event name and target value -- and click Save changes, then:
- [ ]  2.1. IF there are no linked results, THEN I get the usual "Success, form data saved" message.
- [ ]  2.2. IF there are linked results, THEN I am prompted for a rationale AND the change is logged in the program's change log, including the rationale.
