### ISSUE TITLE
Resolving lingering issues around event target deletion

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1424]
This issue was raised by Cameron and Rickie in the process of developing and testing #1389. 

**Affects:** _**Saved**_ event targets with no result linked to them.

# Issue
When I delete an individual event, I am not prompted for confirmation. When I click "Remove all targets", I am prompted. This feels oddly inconsistent, since removing the last target is the logical equivalent of clicking "Remove all".

I'm struggling to remember why we implemented it like this, and my best guess is that it had something to do with Winterhawks-specific constraints and tradeoffs. In any case, we can do better.

# Acceptance criteria

## Revision to Scenario 4 in 1389: Deleting an UNSAVED Event target with NO results linked to it

The way it works now: If there are no linked results, I can delete an unsaved event target with no confirmation prompt and no rationale prompt.

Desired change:

- [x] 1. I get the same confirmation prompt I get if I click "Remove all"

     ![image](https://user-images.githubusercontent.com/33670923/56243598-d7294600-604f-11e9-9711-262dde9c9754.png)

- [x] 2. Clicking "Cancel" or the "X" closes the prompt with no change.

- [x] 3. Clicking "OK" deletes the event target row.

## Revision to Scenario 5 in 1389: Deleting a SAVED Event target with NO results linked to it.

The way it works now: I can delete a saved event target with no confirmation prompt and no rationale prompt.

Desired change:

- [x] 1. I get the same confirmation prompt I get if I click "Remove all"

     ![image](https://user-images.githubusercontent.com/33670923/56243598-d7294600-604f-11e9-9711-262dde9c9754.png)

- [x] 2. Clicking "Cancel" or the "X" closes the prompt with no change.

- [x] 3. Clicking "OK" deletes the event target row.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@RickieT Just filed this, based on your feedback. Cameron asked that I put it in a separate ticket from 1389.

This is NOT a release blocker, but @camgnostic just want to bring this to your attention on the off chance that 1389 is giving you headaches and this is actually easier to implement.

**Comment by camgnostic** [comment]
Implementing this I ran into a problem:
if you delete a SAVED event target, you get a prompt (no rationale) and clicking okay deletes it.  Then when you hit save, a different prompt from another part of our rationale logic detects that targets have changed and prompts for a rationale.  The target has already been deleted at this point, so even if you hit cancel and close, the target remains deleted.  So do we want a rationale prompt for deleting a target without linked results?  If so, do we want the prompt when you initially click "delete" on a saved event target?  and then no prompt when you save the whole indicator form? 
Prompt that I get clicking "save": 
![Screen Shot 2019-04-16 at 4 06 27 PM](https://user-images.githubusercontent.com/7941355/56249732-b0740b00-6061-11e9-9ee2-1a24a612fdd2.png)

**Comment by camgnostic** [comment]
Tagging @jennyhavah as this is confusing

**Comment by KennyMonster** [comment]
@camgnostic I think I may know how to work around the above wonkyness

**Comment by jennyhavah** [comment]
Holy hell was that confusing. First I'll share my conclusions, and then explain how I got there. So in the case of an event indicator with linked results to ANY of its targets:

1. We DO prompt for a deletion rationale at the time you delete an individual event, _regardless of whether or not that specific event is the one with the linked result._ 

2. If the specific event being deleted does NOT have linked results, we can use this wording in the rationale prompt: This action cannot be undone. For future reference, please provide a rationale for deleting this target. 

3. If the specific event being deleted DOES have one or more linked results, we can use this wording in the rationale prompt:  This action cannot be undone. Any results assigned to this target will need to be reassigned. For future reference, please provide a rationale for deleting this target. 

4. Even if no other changes are made after deleting event targets and I click “Save changes”, then at this point I would expect the yellow rationale prompt to show up even though it's meaningless and and then proceed to fail to save anything I type, because that’s ANOTHER bug we need to deal with. (I’ll file a separate ticket for that.)

And now the meandering thought process behind these conclusions, for the record.

1. Just to emphasize: This is a scenario where _at least one event target_ has a result linked to it. Because as a general rule, we don't prompt for rationales when there are no results linked to ANY of the targets.

2. The event target you're deleting is not necessarily the one that had results linked to it.

3. Even if the specific event target was NOT the one with the linked results, it is still true that you're modifying the performance metrics _of the indicator as a whole_ by deleting that target. So it makes sense to prompt for a rationale, regardless.

4. And SO, you ask, why not skip the confirmation prompt and just display that rationale prompt right as you're deleting the target, and not wait until you click _Save changes_? Good point! 

The only risk I can think of is that if you’ve made any OTHER changes to the indicator prior to deleting the event target — such as updating the LoP target — you might mistakenly think that the deletion prompt covers all changes and not bother to click “Save changes” on the indicator as a whole. 

However, I think that risk is outweighed by the risk of not capturing a rationale for the deletion at all, if we delay the prompt until you save changes to the indicator as a whole. 

In fact, we have the exact same risk with the “Remove all targets” button — in that you could conceivably make other edits prior to clicking that button and lose those changes if you don’t click “Save changes” afterwards. But again, I think it’s outweighed by the risk of allowing that deletion to proceed with no prompt.

**Comment by jennyhavah** [comment]
This ticket is no longer about "one weird little deferrable inconsistency" but more generally about tying up loose ends around event deletion. I've updated the title accordingly and -- after checking in with Cameron -- am moving it into This Release.

**Comment by camgnostic** [comment]
Moving this back to This Release while @KennyMonster works on the holistic "why are rationale prompts so wacky?" question

**Comment by jennyhavah** [comment]
PASSED.

1. Prior to saving an event target, I am prompted for confirmation before deleting it. (No rationale, as expected.)

2. After saving event targets, before linking results, if I delete one event, I am prompted for confirmation before deleting it. (No rationale, as expected.) This is true both in the full-page and modal versions.
