### ISSUE TITLE
Adding a program: GAIT ID does not have to be unique

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1429]
This ticket replaces #1409.

This issue was reported by Marie in Slack:

> "_ODP has one GAIT ID for both Ethiopia & Kenya which is  [GAIT ID: 7781] so when I tried to enter this ID the system says "Already exists" as the Kenyan team created with this ID. this also happens when we tried to add the project ID during our last in-country TolaData training and forced to use 1000 ID as a default for the training purpose. So we need your urgent support to sort out this issues ASAP._"

> This is a case of 2 countries working on the same grant / program, but have different management and tracking needs and therefore would like the program separated by country. Currently, the system only allows one GAIT ID per program. This is not a showstopper, despite Ethiopia's claims that this is urgent. However, we will see more of this with multi-country programs that *do not* want to share programs. And so, I would like to provide a workaround, solution or recommendation to the Ethiopia team (as well as any others that come up in the future). Perhaps, it is as simple as removing the restriction to one GAIT ID per program?

# Acceptance criteria

**Preconditions:** 
1. I've opened the Programs section of the new admin console and clicked "Add Program".
2. I've entered a GAIT ID shared by another program already in Tola.
3. All other required fields are complete.
4. I click "Save changes".

- [x] 1. I get a confirmation prompt with the following text:
     Warning
     The GAIT ID for this program is shared with at least one other program. View programs with this ID in GAIT.
     Are you sure you want to continue?

     ![image](https://user-images.githubusercontent.com/33670923/56318674-8596bf00-6114-11e9-9818-d552da677aa6.png)

- [x] 2. "View programs with this ID in GAIT" opens --  _in another tab_  -- the Search page of GAIT filtered on the GAIT ID. Here's an example of such a link: 

https://gait.mercycorps.org/search.vm?Mode=edit&sort_by=g.GrantTitle&q=&kw=&GrantNumber=&CostCenter=&GrantID=1112&GrantMin=&SSD=&USD=&SED=&UED=&Emergency=

![image](https://user-images.githubusercontent.com/33670923/56318766-b4ad3080-6114-11e9-958d-dfbdde24d20c.png)

Why go to this trouble, you ask? Because the person may or may not have access to the programs in Tola.

- [x] 3. If I click "Cancel" or the "X", the prompt closes and nothing else happens.

- [x] 4. If I click "OK", the form submits and I get the green "Successfully saved" message.

Open question: Do we need to do anything in the original Django admin as well -- to lift the no-duplicates requirement -- that I haven't captured in this ticket?

## Housekeeping

- [ ] Unit test/s written wherever applicable
- [ ] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
Note for prioritization purposes: Marie says that the current prohibition on duplicate GAIT IDs is "not a showstopper." However, if we do not implement this ticket, we're also not addressing the issue described in #1409.

@KennyMonster Can you give us a picture of how challenging / time consuming this will be to implement?

**Comment by KennyMonster** [comment]
@jennyhavah This is probably 1-3 hours assuming I'm not missing something. It would involve:

* Removing the DB unique constraint
* Verifying there are no other places in the code base assuming that gaitids are unique (for instance calling `Program.objects.get(gaitid=id)`)
* Adding in the confirmation prompt

**Comment by jennyhavah** [comment]
Chatted with @KennyMonster offline. He's going to see if he can take care of removing the restriction at a minimum -- the easier part. That also takes care of the dangling loose thread that is #1409.

If the link to GAIT turns out to be significant effort, we'll defer that piece of it.

**Comment by jennyhavah** [comment]
PASSED. I've tried adding several programs with duplicate GAIT IDs. The prompt is working as expected, and the link to GAIT brings up the correct program.

**Comment by jennyhavah** [comment]
Heads up to @axoplasm that this is a new prompt that will need styling along with the other PNotifys. Here's how it looks at the moment:

![image](https://user-images.githubusercontent.com/33670923/56402311-9711c100-6211-11e9-8a7a-759dd14adbf1.png)
