### ISSUE TITLE
Indicator setup form: I can't save changes to indicators without linked results

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1430]
Notes:
1. Can't reproduce the issue on Production -- it seems to be a Papaya problem.
2. This problem only appears to affect saved indicators with no results

# To reproduce the issue 

1. Be logged in as SuperUser or someone with High permissions for the Tolaland program called "QA Program --- No Results Here"

2. Visit the program page: https://tola-activity-dev2.mercycorps.org/program/612/#/

3. Without editing anything, click the Save changes button right away. Note the lack of response. Compare that with production where you get a success message even though you haven't changed anything.

4. Now try editing any field and clicking Save changes... I get no response at all.

**Comment by axoplasm** [comment]
I assume I'm editing an indicator, e.g changing its name?

**Comment by jennyhavah** [comment]
@axoplasm For me, it didn't matter what field I edited, I couldn't save.

**Comment by axoplasm** [comment]
Ken has fat fingers

**Comment by jennyhavah** [comment]
It's also harder to type with an adorable baby in the crook of one arm.

**Comment by RickieT** [comment]
**QA - PASSED**
* Clicking save changes on an indicator without making any changes provides a successful save message
* Editing fields / names/ etc and clicking save provides a successful save message

Looks like this one is fixed, can't reproduce any longer following the steps.
