### ISSUE TITLE
Indicator setup form: % sign oddities every other time you open the form 

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1433]
This is a contender for weirdest bug I've ever seen.

I was looking at a saved percentage indicator and noticed some % sign oddities when toggling between % and #. The % signs did not go away when I toggled to # and the LoP target had the number and % sign overlapping, like so:

![image](https://user-images.githubusercontent.com/33670923/56383689-4da08200-61cf-11e9-8cb0-8b925cd806f8.png)

I close and reopen _the same indicator_ and try again -- problem goes away!

I close and reopen the same indicator a 3rd time -- Boo, now I see the problem...

It's apparently happening every other time I open the form.

I tested this on multiple % indicators on Dev2 and Production and was able to replicate the error.

Is this a high priority bug that people will frequently encounter? Nope. Is it weird as heck? Yup.

**Comment by jennyhavah** [comment]
I can no longer reproduce this issue -- just tried a bunch of times. This ticket is pretty old, pre-Satsuma and all the work Ken did on the form at that time. It's likely that in the course of updating the form, the problem got resolved.

@kdubois22 can I confirm that you two didn't reproduce the issue during the meeting? If not, I'm going to assume it's no longer and issue and close it.

**Comment by kdubois22** [comment]
We did not test this during the meeting so I can't say for certain if it's still an issue.

**Comment by jennyhavah** [comment]
Ok! Since I'm unable to reproduce it and the form has undergone significant changes that may very well have resolved the issue, I'm closing this ticket.
