### ISSUE TITLE
Indicator setup: Low/medium users can't open multi-selects to observe what is selected

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1439]
**Affects:** Low- and Medium-access users viewing a program indicator setup form. 

# Issue

If I am someone with low or medium access to a program, I only have _view access_ to the indicator setup form. Disabled multi-select forms are currently inaccessible to me, even for viewing purposes, when more than one item is selected. I cannot open these menus to see what the options are and which of them are selected.

For example, I can't see what Program Objectives or Country Strategic Objectives were selected here:

![image](https://user-images.githubusercontent.com/33670923/56395316-f7dbd200-61ee-11e9-8302-c7b46069769f.png)

An example of how we handle this elsewhere is the "Measure against target" field in the result form -- that is determined by the result date and not manually settable. Here's what that looks like:

![image](https://user-images.githubusercontent.com/33670923/56395475-9ec06e00-61ef-11e9-8291-7520987ce115.png)

# Acceptance criteria

The following things are true for low- and medium-access users to a program.

## Summary tab

For the following multi-select menus, I -- Low/Medium access user -- can open the menu to **_view_** all available options, and see which ones are currently selected. I still cannot **_modify_** the selection.

- [ ] ~1. Sector~ (not a multi-select)

- [x] 2. Program Objectives -- _This menu is only visible in pre-Satsuma programs with "group by Results Framework box unchecked in Admin Lite Program section._ 

- [x] 3. Country Strategic Objectives

## Performance tab

- [x] 1. Disaggregation

- [x] 2. Indicator type

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@hannalcamp I'm thinking this is probably not a release blocker, but wanted to run it by you.

**Comment by hannalcamp** [comment]
Nope, can go to Deferred.

**Comment by sanjuroj** [comment]
Disabling options  rather than the drop down should be relatively easy.

**Comment by jennyhavah** [comment]
@sanjuroj Just to make sure we're talking about the same thing... _Options are already disabled_, to the extent that Low/Med users can't even open the menu. We need to keep the menus _unselectable_ for Low/Med users, but enable them to the extent that the menus can be opened to view what's inside, what's selected/not selected, etc.

**Comment by sanjuroj** [comment]
Right, so right now the dropdown itself is disabled.  Enabling the dropdowns but disabling the options (and selectability) will allow them to see the options but not select them.

**Comment by jennyhavah** [comment]
Perfect. I had a different definition of "enabled" in my head, but I get it now.

**Comment by camgnostic** [comment]
@jennyhavah this is done for CSO and PSO but for Sector, which isn't a multi-select, is this necessary?  If there is an option selected, it's visible without opening the drop down, and opening the drop down would only show _un_-selected options that the low or medium user can't pick anyways.

**Comment by jennyhavah** [comment]
@camgnostic I mistakenly thought Sector was a multi-select. Ticket updated.

**Comment by jennyhavah** [comment]
**Validated.** Logged in as a Low or Medium user, I can view, but not edit multi-selects.

Summary tab > Program objectives
![image](https://user-images.githubusercontent.com/33670923/71489365-16608700-27da-11ea-8117-1fc0992abae5.png)

Summary tab > Country strategic objectives
![image](https://user-images.githubusercontent.com/33670923/71489395-43149e80-27da-11ea-91d3-12baca98aa4b.png)

Performance tab > Type
![image](https://user-images.githubusercontent.com/33670923/71489475-9f77be00-27da-11ea-8b6e-f68884c0ed12.png)

Performance tab > Disaggregations

![image](https://user-images.githubusercontent.com/33670923/71489555-fd0c0a80-27da-11ea-8b2d-acabf5df9603.png)

Will need to keep an eye on this last one, as we refine the UI to have this open by default, to cap the widget height at a certain number of rows, etc.
