### ISSUE TITLE
Add program: Some funkiness around validating required fields

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1441]
When adding a new program, I found some validation oddities.

## Leave out the country

Fill out all required fields except for country and submit.

**Expected:** I get an error message telling me to complete the field.
**Observed:** The page briefly flashes but I get no error message or any other system response.

## Leave out the funding status

1. Fill out all required field except funding status and submit.
2. Note the "This field may not be blank" message. Complete the field and submit.

**Expected:** I get a success message
**Observed:** I get a success message BUT the error message does not go away.

![image](https://user-images.githubusercontent.com/33670923/56403276-63d13100-6215-11e9-9759-fc13ca9a0551.png)

**Note:** We have a brand new confirmation prompt on this page that appears when you enter a GAIT ID that is a duplicate -- described in #1429. Any work we do here needs to play nicely with that prompt.

**Comment by jennyhavah** [comment]
@hannalcamp I'm assigning this to you because I recall a similar issue popping up somewhere else... I'm thinking that before a dev takes this ticket, it might be a good idea to do a sweep through the Admin for any other validation issues of a similar nature, on required fields...

**Comment by hannalcamp** [comment]
@jennyhavah 's error for "Leaving out funding status" also occurs when adding an organization and leaving out the email field initially, then adding it. This resulted in the same behavior:

Expected: I get a success message
Observed: I get a success message BUT the error message does not go away.

(I wasn't quick enough to take the below screenshot before the green success message went away, but it was there)
![Screen Shot 2019-04-19 at 3 04 03 PM](https://user-images.githubusercontent.com/38020496/56444125-b7468c00-62b4-11e9-898d-7c36b98981f5.png)

**Comment by hannalcamp** [comment]
Same happens for any other field in the Add Organization form:

![Screen Shot 2019-04-19 at 3 08 31 PM](https://user-images.githubusercontent.com/38020496/56444223-14dad880-62b5-11e9-8b60-f5b40b7f6705.png)

**Comment by hannalcamp** [comment]
Same in the Add Countries form

![Screen Shot 2019-04-19 at 3 16 55 PM](https://user-images.githubusercontent.com/38020496/56444482-35576280-62b6-11e9-9f46-f5e4cc4cf05a.png)

**Comment by hannalcamp** [comment]
New error: When working with Strategic Objectives, the Objective field doesn't appear to be validated at all - I can save new SOs without filling it in and also delete the text in the field and save successfully on an existing SO.
![Screen Shot 2019-04-19 at 3 28 45 PM](https://user-images.githubusercontent.com/38020496/56444917-122db280-62b8-11e9-819b-1b724624c0bc.png)

**Comment by jennyhavah** [comment]
While all of this is irritating, I'm thinking it doesn't rise to the level of release blocker. Would you agree, @hannalcamp?

**Comment by hannalcamp** [comment]
Agreed. It can be dealt with later.

**Comment by jennyhavah** [comment]
@camgnostic Please see my update to the comment above regarding the Objective field. This change should be reverted, if you've already done some work on it.

**Comment by camgnostic** [comment]
Fix will now:
Actually display validation errors on multi-selects (i.e. the Country field) instead of flashing and doing nothing
Clear errors from program, organization, and country fields when the problem is fixed and the form resubmitted.

**Comment by RickieT** [comment]
**QA - PASSED**
* Checked that validation errors occur and disappear on forms as requirements are met. They are no longer static when filled out properly. Check User, program, country and org forms
