### ISSUE TITLE
Indicator Audit Log result link is shown even when link doesn't exist

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#1444]
I created a Result on an Indicator, but did not fill in any of the evidence name/url fields. The Audit log still shows a link to the result though which links to nowhere:

![Screen Shot 2019-04-19 at 11 25 56 AM](https://user-images.githubusercontent.com/1278224/56437930-11842480-6296-11e9-83f5-d89ac0bafbe9.png)

**Comment by jennyhavah** [comment]
This might be good to fix in tandem with #1421 -- since both issues are related to the Evidence portion of the log.

@hannalcamp I'm thinking this is probably not a release blocker, but let me know if you disagree.

**Comment by hannalcamp** [comment]
Agreed, not a release blocker

**Comment by RickieT** [comment]
### QA Passed:
* Issue no longer occurs as written:
![image](https://user-images.githubusercontent.com/23220180/56836755-fe8cc980-682c-11e9-99a2-7ff7d4e8b383.png)
