### ISSUE TITLE
Admin: Delete button disappears in the disaggregation form after saving

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1448]
**Note:** This ticket only covers the availability of the delete button. UI updates to the form are covered in #1503.

# Issue

**Affects:** Admin Lite > Countries > Country > Country disaggregations tab

When I open a blank disaggregation form in a country profile, there is a Delete button at the bottom. If I fill in a value for Type and hit save:

1. I get a "Successfully saved" message, and the accordion form collapses. Meaning, I can save without adding a single disaggregation option, an "empty" disaggregation that is unusable by the program.
2. When I open up the disaggregation again to add options, the Delete button is gone. There's no obvious way to delete a disaggregation created in error, even though it is not in use by any indicators in the system.

![Screen Shot 2019-04-19 at 3 50 55 PM](https://user-images.githubusercontent.com/38020496/56445654-96ce0000-62bb-11e9-8d70-f96c4223121f.png)
![Screen Shot 2019-04-19 at 3 50 47 PM](https://user-images.githubusercontent.com/38020496/56445653-96ce0000-62bb-11e9-887b-f2ce013a6f7f.png)

Note from Jenny: We need to ensure that deletion of an entire disaggregation type is ONLY possible if it is not "in use" -- meaning it has not been selected for any indicators in the system. Otherwise, it might be possible to wipe out a bunch of disaggregated results data by deleting the disaggregation type in Admin Lite. Also, we ought to have a basic confirmation prompt for a destructive action like deleting a disaggregation.

# Acceptance criteria

- [x] 1. As long as a disaggregation _**is not selected by at least one indicator in the system**_, the "Delete" button remains visible and active, even after saving.

![image](https://user-images.githubusercontent.com/33670923/62249031-60b21900-b39e-11e9-8343-99e04bd64c4c.png)

- [x] 2. When I click "Delete disaggregation" -- _before or after saving_ -- the following things happen:

     - [x] 2.1. I get a standard warning confirmation similar to deleting targets -- screenshot below. It says:

     Warning
     This action cannot be undone. 
     Are you sure you want to delete this disaggregation?

     ![image](https://user-images.githubusercontent.com/33670923/61901090-d9633200-aed3-11e9-935e-839e30cd8489.png)

     - [x] 2.2. If I click "Ok", the disaggregation is deleted from the system. <P>

- [x] 2. When a disaggregation is selected by at least one indicator in the system, it is no longer possible to delete it. The delete button is replaced by an Archive button. This functionality is covered in #1850.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by sanjuroj** [comment]
Another one that's on the low/medium border.  The notifications can sometimes be weird.

**Comment by jennyhavah** [comment]
**Verified:**

1. "Delete disaggregation" button remains available as long as the disaggregation is not in use. Once it's selected for an indicator, the button switches to "Archive disaggregation" as expected.

2. I cannot save a disaggregation with no categories.

3. When I click "Delete disaggregation" -- before or after saving -- I get the expected warning confirmation message.

**Comment by jennyhavah** [comment]
Request for UI refinement:

I noticed that currently on Prod and Dev2, we have inconsistent behavior when you click "Save changes". If you're saving a new disaggregation, it saves and collapses the form. But if you're editing a saved disaggregation, the form stays open.

Let's consistently leave it open -- whether you're saving for the first time or editing. This gives you the ability to review what you've done, reorder categories if you like, etc.

**Comment by jennyhavah** [comment]
@camgnostic Did you merge your latest updates? The form is still collapsing when I save a new disaggregation.

**Comment by jennyhavah** [comment]
It's now staying open after save!

@camgnostic I notice that when I save a disaggregation for the first time, it jumps me up to the top of the page, but not when I'm editing a saved disaggregation.

Can we have it stay put and NOT jump you up to the top when you first save?

**Comment by camgnostic** [comment]
short answer: no

long answer: it's not jumping you to the top of the page, it's removing the "new" disaggregation form and replacing it with an "Edit" disaggregation form (so you can edit the one you just added).  In the millisecond that it's removed the browser thinks the page is much shorter so scrolls up.  I can have it scroll back down, but that's a high effort ticket.  So if we want to do that, can we open a new ticket asking for that scroll functionality?

**Comment by jennyhavah** [comment]
Naw, it's not that serious. I thought it was a matter of _removing_ some extra code that was making it jump to the top. Definitely not worth a high level of effort. Moving to Passed.
