### ISSUE TITLE
Admin > Programs: Remove "Status" field from Profile page and automatically set to Funded

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1450]
**Affects:** Both tabs of the Program form in the new Admin section.

# Issues
1. Smaller issue: There are duplicates of the Status form field in the Profile and Status & History tabs. It's unclear why, other than that Parthenon wasn't sure what the default should be and you can't access the Status & History tab until you add the program. Redundancy isn't a problem if it's warranted. But in this case, there's no valid use case that Hanna and I can think of, for adding a Completed program. For one thing, you need it to be Funded in order to even see the program in Tola to set up periodic targets, view IPTTs, etc.

2. Larger issue: We need to decouple program status in the Tola sense, from program status in the GAIT sense. Right now we're trying to accomplish both things with one form field, and doing neither well. "Funded" and "Completed" are GAIT terms related to grant status. We are using the term "Funded" to determine whether or not a program appears in Tola to end users... This has resulted in programs remaining in "Funded" status indefinitely -- not because that accurately reflects their GAIT status, but because we want the program to be visible in Tola. 

**Solution:** Turn today's Funding Status field into an Active/Inactive field -- auto-set to Active for new programs. Add a second type of status field that pulls directly from GAIT and is not editable by end users. For now it will be purely informational. In the future, it could be used to create filters that allow users to view older programs without seeing them all the time.

# Acceptance criteria

- [x] 1. **Profile tab:** Remove the "Funding Status" field. It is a duplicate of the "Program status" field in the Status & History tab.

- [x] 2. **Status and History tab:** Rename the "Program Status" field to "Status" in the "Status and History" tab -- to be consistent with the label we're using for Users and Organizations. Keep the required asterisk in place.

     - [x] 2.1. Rename the two options from "Funded" and "Completed" to "Active" and "Inactive" -- again for consistent terminology. 

     - [x] 2.2. The _meaning_ of these two terms remains the same: "Active" means the program is displayed in Tola. "Inactive" means it is not.

     - [ ] 2.3. **Data migration:** We must preserve existing database values, even though we are relabeling them. This means any programs in the database that are currently set to "Completed" should be set to "Inactive". Any that are currently set to "Funded" should be set to "Active." 

- [x] 3. When I add a new program via the Profile tab, the Status field in the Status & History tab is automatically set to Active... Exactly the same behavior as when I add a User or an Organization.

![image](https://user-images.githubusercontent.com/33670923/56520279-e9e0c680-64f8-11e9-85f5-85bb83cd208b.png)

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by camgnostic** [comment]
Everything except DB Migration is cosmetic and rolling in a PR coming today.  Data migration I have some questions on.  From slack: 
> when you say we need to migrate the existing data - do you think we need to actually change every database value?  Or do we just need to display “funded” to the user as “Active”?

**Comment by jennyhavah** [comment]
As I mentioned on Slack, I was probably using the wrong term... I just mean that we don't want to modify any values assigned to existing programs -- only update the terminology.

**Comment by RickieT** [comment]
**QA - PASSED**
* Fund Code field is grayed out, users cannot edit
* Upon creation, status is automatically set to funded
