### ISSUE TITLE
New User: Organization field is required but does not produce the appropriate error

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1451]
When I create a new user, no Organization is selected. If I don't select an organization, the save will fail, but doesn't produce an error:

![image](https://user-images.githubusercontent.com/169060/56516227-bd27b180-64ee-11e9-8f05-1c41f59a32e9.png)

**Comment by axoplasm** [comment]
@hannalcamp is this a blocker? The form is still usable and validates correctly on the backend

**Comment by axoplasm** [comment]
This is a CSS failure, fixed in 915be8d

![image](https://user-images.githubusercontent.com/169060/56525250-932abb00-64ff-11e9-939e-f75a394a249b.png)

**Comment by hannalcamp** [comment]
If it's already being fixed, great. Otherwise I wouldn't consider it a release blocker.

**Comment by RickieT** [comment]
**QA - PASSED** 
* Tried to save without organization, and was presented with the proper error and highlight:
![Screen Shot 2019-04-23 at 11 23 55 AM](https://user-images.githubusercontent.com/23220180/56606072-52dc4300-65ba-11e9-89da-8fed3c228d3e.png)
