### ISSUE TITLE
Edit User Profile: changes to username are not tracked

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1452]
The username field is new in Admin Lite per #1443 & #1411.

**Comment by axoplasm** [comment]
Split tracking changes to organization into its own ticket: #1453

**Comment by axoplasm** [comment]
Also, stopped tracking the derived field "Name" and started tracking the original fields "Last Name" and "First Name"

**Comment by RickieT** [comment]
### QA Passed:
![Screen Shot 2019-04-29 at 2 41 05 PM](https://user-images.githubusercontent.com/23220180/56928824-d4d1dd80-6a8c-11e9-80f9-9386d82be774.png)
