### ISSUE TITLE
Add change log link to program page and move it on IPTT reports

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1457]
# Issue
Change log should be easier to find

# Acceptance criteria

## Program page

- [x] 1. In between the Indicator plan and GAIT link (when it exists) is a link called "Change log" <-- note sentence case along with the change log icon

![image](https://user-images.githubusercontent.com/33670923/56605178-5ff83280-65b8-11e9-9209-b79136db847f.png)

Just FYI, here's a sneak preview of how I imagine the list looking after Satsuma

![image](https://user-images.githubusercontent.com/33670923/56605220-769e8980-65b8-11e9-91bc-f903f3e21d50.png)

## IPTTs (both types)

- [x] 1. The Change log link appears just below the filter panel.

     ![image](https://user-images.githubusercontent.com/33670923/56605764-b3b74b80-65b9-11e9-8438-7216977b3933.png)

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [x] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by RickieT** [comment]
**QA - PASSED**
* Link is now on bottom of IPPT filter - and the link successfully directs to the relevant change log
![Screen Shot 2019-04-23 at 12 43 28 PM](https://user-images.githubusercontent.com/23220180/56610937-7ce73280-65c5-11e9-845a-31f6bc730117.png)
* Link is now on the program page between Indicator plan and GAIT - and the link successfully directs to the relevant change log
![Screen Shot 2019-04-23 at 12 39 30 PM](https://user-images.githubusercontent.com/23220180/56610941-7e185f80-65c5-11e9-8689-783e55d215b1.png)
