### ISSUE TITLE
Country Strategic Objective: Fix form labels and remove requirement on one field

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1459]
# Issue
We had some confusion over requirements, resulting in mislabeling of fields and the addition of a requirement to a field that should not be required.

# Acceptance criteria

- [x] 1. Change the label "Code" to "Short name" and _keep it required._

- [ ] 2. Change the label "Objective" to "Description" and _remove the requirement._ 

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@camgnostic Heads up that if you made this field required as part of 1441, we need to revert that change.

**Comment by axoplasm** [comment]
The field is not actually *required* in the code, it just got an asterisk somehow.

`models.py:85`
```python
    description = models.TextField(_("Description"), max_length=765, blank=True)
```

**Comment by jennyhavah** [comment]
PASSED. Two field names were updated and the asterisk was removed from the second form field.

![image](https://user-images.githubusercontent.com/33670923/56611726-5aeeaf80-65c7-11e9-8577-3bae3e86a6ea.png)
