### ISSUE TITLE
Footer fixes

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#146]
We need a couple of fixes in the TolaData footer in TolaActivity and TolaTables. 

1. TolaData logo currently links to Humanitec. Remove the link and leave the logo.
2. Update the License link to point to the correct license.

**Comment by jennyhavah** [comment]
Not fixed for TolaTables

**Comment by sanjuroj** [comment]
@jennyhavah Emily asked me to take that link out completely a while ago.  I can put it back in if needed.

**Comment by jennyhavah** [comment]
@sanjuroj As discussed, can you please remove the License link in the TolaActivity footer. We've decided to not display it in either app.

**Comment by jennyhavah** [comment]
@sanjuroj As long as you've removed the License link, the rest is styling. Should I close out this story to get it out of our queue?

**Comment by sanjuroj** [comment]
@jennyhavah I haven't done it yet, so let's leave it there.  As soon as it's done, I'll throw it into testing.  I'm trying to close out the long list of things for the Indicator Setup page.
