### ISSUE TITLE
Replace any mention of "Rationale" in the UI with "Reason for change"

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1460]
# Issue
The word "rationale" needs to be replaced with the easier-to-understand "reason for change" or "reason" in any user-facing text string. In places where "rationale" appears at the end of a sentence (or alone), it can be replaced with "reason for change". In places where "rationale" appears in full dialogue box sentences, it should be replaces with "reason".

_Note from Jenny: It's entirely possible there are some rationale dialogues we missed here. If there's an easy way to do a search for these, please do let us know if we haven't covered them all._

# Acceptance criteria

## Change log

![image](https://user-images.githubusercontent.com/33670923/56619495-8fb83200-65da-11e9-9a20-6ee0c4b0f364.png)

- [ ] 1.  **The title of the final column of the Change Log:** Replace "Rationale" with "Reason for change"

### Non-destructive

![image](https://user-images.githubusercontent.com/33670923/56616351-0997ed80-65d2-11e9-8e7a-dd3db97391db.png)

- [ ] 1. **The title of the non-destructive change log dialogue box:** Replace "Share your rationale" with "Reason for change"  <-- Sentence case, please!

- [ ] 2. **The change log dialogue string for a non-destructive change:** Replace "...please share your rationale for these changes" with "...please share your reason for these changes"). This string appears when the following changes are made:

  - [ ] 2.1. An indicator with results attached is modified (with the exception of the Name or Periodic Targets fields).

  - [ ] 2.2. An existing result value, date, or associated target period is modified.

- [ ] 3. **Error prompt if you try to submit it without typing anything in:** Instead of "Rationale required", it should say "A reason is required."

### Destructive

![image](https://user-images.githubusercontent.com/33670923/56616447-48c63e80-65d2-11e9-9c33-3a2cc023ab18.png)

- [ ] 1. **The change log dialogue strings for any destructive change:** Replace "...provide a rationale for [destructive thing]" with "...provide a reason for [destructive thing]". The dialogue strings appear when the following changes are made after results are linked to the indicator:

  - [ ] 1.1 An indicator is deleted.

  - [ ] 1.2. The program start/end date is modified.

  - [ ] 1.3. The Name field or Periodic Targets fields of an indicator with results attached are modified.

  - [ ] 1.4. The periodic targets of an indicator with results attached are deleted (clicking "Remove all targets")

       - [ ] 1.4.1. Individual event targets are deleted. (clicking the "X" next to an event -- easily overlooked deletion, just calling it out) 

  - [ ] 1.5 An existing result is deleted.

- [ ] 2. **Error prompt if you try to submit it without typing anything in:** Instead of "Rationale required", it should say "A reason is required."

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by RickieT** [comment]
**QA - PASSED**
* Change log new text:
![image](https://user-images.githubusercontent.com/23220180/56693701-010aea00-669a-11e9-961e-cacf1a341535.png)
* Non Destructive result change:
![image](https://user-images.githubusercontent.com/23220180/56693755-1f70e580-669a-11e9-9ca2-4d5249d7d454.png)
* Deleting a result:
![image](https://user-images.githubusercontent.com/23220180/56693803-30b9f200-669a-11e9-9e20-bd500677699c.png)
* Changing reporting period:
![image](https://user-images.githubusercontent.com/23220180/56693837-40393b00-669a-11e9-88ab-fad9599abd0e.png)
* Deleting an indicator:
![image](https://user-images.githubusercontent.com/23220180/56693862-4fb88400-669a-11e9-8b7f-dbe961267d09.png)
* Deleting targets:
![image](https://user-images.githubusercontent.com/23220180/56693899-6068fa00-669a-11e9-9e76-f8fe160a72a2.png)
* Non destructive change to indicator with results:
![image](https://user-images.githubusercontent.com/23220180/56693925-6d85e900-669a-11e9-8e91-4754c5b8de6b.png)
* Modifying target values with indicator with results attached:
![image](https://user-images.githubusercontent.com/23220180/56693971-842c4000-669a-11e9-935a-64219452f5bc.png)
* error text says change reason required (Destructive):
![image](https://user-images.githubusercontent.com/23220180/56693992-96a67980-669a-11e9-801a-5b2dd487d648.png)
* error text says change reason required (non destructive)"
![image](https://user-images.githubusercontent.com/23220180/56694026-a920b300-669a-11e9-8f9a-9d83437bf314.png)
