### ISSUE TITLE
Possible layout issue with User Admin

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1463]
When I navigate to the User admin, expand a user, and click on the "Status and History" link, the main body of the page drops down below the filter sidebar. This doesn't happen when I switch back and forth between the "Profile" and "Programs and Roles" links.  It's possible that this is partly due to the screen size on my little macbook, but wanted to flag it.

<img width="1392" alt="Screen Shot 2019-04-23 at 2 19 28 PM" src="https://user-images.githubusercontent.com/6685499/56616992-968f7680-65d3-11e9-8cfa-940d6511281c.png">

**Comment by jennyhavah** [comment]
Noticed that too, @sanjuroj ! I thought we'd caught all of those! I find that sometimes it depends on which tab you happen to have open on the individual row form.

@RickieT It might be worth going through all tabs on all screens of the Admin to see if there are any more of these wrap issues lurking...

**Comment by RickieT** [comment]
There is some funkyness where you need a specific browser window to see a different effect. Check this out - in the 1st image here, everything appears to show normally (resolution in image):
![image](https://user-images.githubusercontent.com/23220180/56677491-7dd79d00-6675-11e9-9e3a-251b4d827464.png)
* If I Squeeze the window size just a TAD smaller, it pops below the filter same as shown in @sanjuroj 's image in the ticket description:
![image](https://user-images.githubusercontent.com/23220180/56677545-9cd62f00-6675-11e9-89ed-ef93473e6db5.png)
* THEN, again, if I squeeze the resolution a bit smaller AGAIN, we see the table come back behind the filter: 
![image](https://user-images.githubusercontent.com/23220180/56677598-b7a8a380-6675-11e9-93fd-dcfc457974ef.png)

@jennyhavah

**Comment by jennyhavah** [comment]
My understanding from @axoplasm  is that this behavior -- while certainly not ideal -- is to be expected, from the fixes he has implemented thus far. 

Paul, can you confirm this? If yes, then I'm going to suggest that we either close this ticket as Won't fix, or -- if you have a different approach you'd eventually like to try -- we could move it into Deferred and turn it into a more general ticket, not specific to this one tab.

**Comment by axoplasm** [comment]
Jenny is correct. Given the way we're building the flyout filter AND ALSO that we have some table fields that need a minimum size, there will always be some combinations of viewport + table size that break the layout.

**Comment by axoplasm** [comment]
I could imagine other, much better ways to build our flyouts, but they would be a nontrivial effort. See https://foundation.zurb.com/sites/docs/v/5.5.3/components/offcanvas.html for an example

**Comment by jennyhavah** [comment]
Ok, I just filed a new ticket and will put it in Fruit Basket: #1472 Make flyouts fly out more gooder.

Closing this one as a "won't do"... at least for this release.
