### ISSUE TITLE
One asterisk in Add Program form isn't red

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1467]
The asterisk denoting "Required" is red for the Program Name and Funding status, but isn't red for Countries.

![Screen Shot 2019-04-23 at 5 24 37 PM](https://user-images.githubusercontent.com/38020496/56622329-d44cc900-65ec-11e9-8ef6-d8d1c69b0f05.png)

**Comment by jennyhavah** [comment]
I'm going to take a wild leap and say this isn't a release blocker... ;-)

But heads up, @axoplasm in case you happen to be in there for some other reason...

**Comment by axoplasm** [comment]
There are other issues with error display on this field. The error display isn't showing correctly, and if it would it would have the wrong styling applied:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/169060/56623903-1b39bf00-65eb-11e9-8d9a-bb1baa9fb8b9.png">

**Comment by axoplasm** [comment]
I pushed a partial fix for this that:

* makes the asterisk red
* shows the error text on error
* styles the error text

In order to get the element itself to be red, that will a little extra work. See dev note on the commit.

**Comment by RickieT** [comment]
**QA - PASSED**
* asterisk is now red, error text on error,
