### ISSUE TITLE
Admin Lite UI: Links to filtered lists of Organizations not working

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1477]
**Affects:** All links of the format "X organizations" in the Admin Lite UI

# Issue
As an administrator, when I examine lists of Programs or Countries, there is a link next to each object name with the format "X organizations". When I click on that link, I should be taken to a filtered list of organizations associated with that object, but I'm actually just taken to a list of all organizations.  

![Error1](https://user-images.githubusercontent.com/38020496/56688466-0a925300-6696-11e9-9a0f-aea3fb895386.png)
![Error2](https://user-images.githubusercontent.com/38020496/56688468-0a925300-6696-11e9-82f2-c5b8491d131a.png)

# Acceptance criteria

- [ ] 1. When clicking on an "X organizations" link from the Programs page, I am taken to a filtered list of those organizations for which at least one associated user can view that program. 

- [ ] 2. When clicking on an "X organizations" link from the Countries page, I am taken to a filtered list of those organizations for which at least one associated user works on at least one program in that country. 

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by KennyMonster** [comment]
@hannalcamp Can you paste the browser URL of the Organizations view when this happens?

**Comment by hannalcamp** [comment]
Yeah, the second screenshot is what happens when I click a "2 organizations" link.

**Comment by RickieT** [comment]
### QA Passed:
* Both links to orgs from countries and programs page, appear to link properly to relevant organizations
![1427](https://user-images.githubusercontent.com/23220180/56757275-b005ff00-6748-11e9-9a67-0dfdbfbbc771.gif)
