### ISSUE TITLE
Admin Lite UI: Program Status column and associated filter don't reflect new Active/Inactive binary

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1479]
**Affects:** Programs page in the Admin Lite UI.
**Related issue:** #1450

# Issue
We have changed the Program setup form so that admins no longer choose a GAIT status upon setup (e.g. Funded, Completed), and new programs are instead designated Active until an admin chooses to switch that to Inactive. But when I view the programs list in the Admin Lite UI, I see that the Status column contains entries from the old Django manual admin, like "funded", "Completed", "old", etc. The filter option to the left also lists "Active"/"Closed" as the options.

![Screen Shot 2019-04-24 at 1 45 29 PM](https://user-images.githubusercontent.com/38020496/56689205-cd2ec500-6697-11e9-9e9b-4352dd7a094e.png)

# Acceptance criteria

- [ ] 1. The program Status column only lists "Active" or "Inactive" as the status for each program. The migration rule should be that any variation on "Funded" (regardless of capitalization) should be Active, and all other statuses converted to "Inactive".

- [ ] 2. The Status filter options should be Active/Inactive, and should appropriately filter the Programs list.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by RickieT** [comment]
**QA - Verified**
* Multiple pages of programs were filtered, and status was reflected by Active / Inactive:
![Screen Shot 2019-04-25 at 9 43 53 AM](https://user-images.githubusercontent.com/23220180/56753127-bc855a00-673e-11e9-987c-cf805d69dc44.png)
* Filtering through inactive programs effectively:
![Screen Shot 2019-04-25 at 9 45 06 AM](https://user-images.githubusercontent.com/23220180/56753232-00785f00-673f-11e9-8cca-174c648d7e81.png)
![Screen Shot 2019-04-25 at 9 46 40 AM](https://user-images.githubusercontent.com/23220180/56753250-0b32f400-673f-11e9-8589-57fc1780f1ba.png)
