### ISSUE TITLE
Multiple locations: Replace unfamiliar phrases with commonly understood terms

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#148]
_From Marie: I took a first stab at going through TolaActivity and TolaTables for weird or confusing terminology. I am not sure on the "Proposed Alternatives." I think some of these definitely warrant a larger discussion._

**[Document is here.](https://docs.google.com/spreadsheets/d/1bvHx-ApC_sIf8fzUSbEU4lqIYII1NxOKNdvJI6Y-ahw/edit?ts=5acd1fba#gid=0)**

There are many locations in TolaActivity where we use unfamiliar phrasing where we could have used commonly understood terms that mirror the language of PM@MC. Marie is putting together a list of terms.

This is a placeholder ticket for a basic "search and replace text" story. It will affect multiple page and form views throughout the application. 

From the issues log:

On the Performance tab, change the “Number” label to something like “Indicator Code” or “Number of Indicator”. Several participants in training thought this was the Target or Actual field.

**Comment by kdubois22** [comment]
@mariebakke Please review :)

**Comment by mariebakke** [comment]
So... this document and ticket are almost 2 years old. We have made a lot of changes in that time, so much so, that the majority of this document is not applicable anymore / already done, and any remaining items will likely be addressed in other releases/tickets. FYI @kdubois22 @jennyhavah

**Comment by jennyhavah** [comment]
Thanks for reviewing, @mariebakke ! I will close this ticket, and if there is anything in there that you are not certain has been captured elsewhere, just let me know and I'll file a new ticket for it.
