### ISSUE TITLE
Indicator Disaggregation Report: Can't view as a Low/Medium access user

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1487]
# Issue
As someone with Low or Medium access to a program, I should be able to see the Indicator disaggregation report. Right now, I see it in the menu:

![image](https://user-images.githubusercontent.com/33670923/56701595-ca8e9880-66b4-11e9-84e5-e8b605435609.png)

But when I click it, I get this page:

![image](https://user-images.githubusercontent.com/33670923/56701606-d24e3d00-66b4-11e9-8a39-7a2aebf94c7e.png)

# Acceptance criteria

- [ ] 1. If I have Low or Medium access to a program, I can access the Indicator disaggregation report.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by RickieT** [comment]
### QA PASSED: 
* As low user, I was able to view indicator dis aggregation report for programs in the country I had access to (Afghanistan - mctest.low@gmail.com & mctest.medium@gmail.com)
![image](https://user-images.githubusercontent.com/23220180/56822641-87dcd580-6806-11e9-8ccc-f44f74fadb1e.png)
