### ISSUE TITLE
Deleting a user (and other objects?) in Django admin also deletes related changelog entries

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1489]
I have not explored the edges of this at all. I noticed it by accident when I was deleting a test user on my local.

![image](https://user-images.githubusercontent.com/169060/56751328-a07fb980-673a-11e9-99bd-38f0a255f6d8.png)

This deletes all the change log entries for that user.

__This only affects actions by Super Admins__

**Comment by axoplasm** [comment]
p/h note for deletions in the program (ie. indicator) changelogs

Before deletion:

![image](https://user-images.githubusercontent.com/169060/56751493-108e3f80-673b-11e9-91c1-5d1537733274.png)

![image](https://user-images.githubusercontent.com/169060/56751530-2c91e100-673b-11e9-920c-395506da2f7a.png)

After deletion (note that the change for “new indicator” is broken):

![image](https://user-images.githubusercontent.com/169060/56751589-4af7dc80-673b-11e9-8d05-086712500121.png)

**Comment by camgnostic** [comment]
To test: open the old and busted Django admin, find a user who has made some changes and added indicators (try it on yourself!) and hit delete.  Make sure the "are you sure" message indicates a reasonable number of follow-on deletions (your social auth and session tokens) and not everything you've ever touched on the site.  Go ahead and hit "cancel" (unless you're done testing for like ever I guess)

**Comment by RickieT** [comment]
### Failed QA:
I don't see a commit on this ticket, and I don't see this fixed, I created a user, made changes, and saw those changes disappear from the log when I removed the user via django admin.

**Comment by camgnostic** [comment]
The TolaUser or the Auth User?

**Comment by camgnostic** [comment]
Specifically the dispo from our conversation this AM was that: 
TolaUser gets marked Inactive, not deleted, and we don't mind a long list.
Removing an Auth.User (the actual authentication model in Django.auth) might be useful for compliance, so we want that capability in the django admin.  That's the one I unlinked (so deleting the auth.user for username cmcfee only deletes my login, session, and social auth info, but doesn't blow up every change I've ever made.

**Comment by RickieT** [comment]
@camgnostic ohh okay that makes sense. Let me try that

**Comment by RickieT** [comment]
### QA PASSED:
* I deleted user from Auth.User in django admin, and their changes remained within the change log for the programs they edited.
