### ISSUE TITLE
Looks like an errant tick mark got into the changelog template

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1490]
in the middle of tracking another bug (#1489) RN so I can't just fix it. see:

![image](https://user-images.githubusercontent.com/169060/56751435-eccaf980-673a-11e9-9baa-20eb3c06ea42.png)

**Comment by RickieT** [comment]
**QA - Verified**
* Checked a few different log tables, don't see any tick marks, looks clean:
![Screen Shot 2019-04-25 at 9 54 21 AM](https://user-images.githubusercontent.com/23220180/56753787-3538e600-6740-11e9-8137-eb7fd4dc2844.png)
