### ISSUE TITLE
Results: "Agriculture" appears as an option within the SADD disaggregation

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1492]
**Affects**: All SADD disaggregation tables in all Results forms.

Issue: "Agriculture" appears as the final option under the SADD drop down menu in the Results form.

![Screen Shot 2019-04-25 at 11 58 30 AM](https://user-images.githubusercontent.com/38020496/56757647-fc097180-6751-11e9-9e74-d2677a07d2cc.png)

Acceptance Criteria:
- [ ] Only Sex/Age cross-sections (Male/Female, 5-year intervals) appear in the disaggregation drop-down.

**Comment by jennyhavah** [comment]
Validated. No longer seeing "Agriculture" in the list of SADD categories.
