### ISSUE TITLE
Admin Lite UI: Change "User" to something more descriptive for whole-country access

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1494]
# Issue
As a super admin, when modifying the all-country status of a user, feedback suggests it's not immediately clear what "User" means (e.g. access to all programs, current and future, in that country). We could change this to "All-country access", or "All-programs access" as a quick fix:

![Screen Shot 2019-04-25 at 12 05 10 PM](https://user-images.githubusercontent.com/38020496/56759387-16dde500-6756-11e9-9d79-5e2c40032c7b.png)

# Design choice (pending)

- [x] 1. Note from Jenny: The fact that the country level role setting applies to all programs now and forevermore -- is not unique to the User role. It applies to Basic Admins as well. It is also important to retain some concept of a hierarchy of roles -- the difference between a plain old User and someone with admin permissions. For these reasons, I don't recommend replacing the word User with a phrase like "All-country access" or "All-program access".

Here's my suggestion for retaining the clear hierarchy of roles while also communicating that this role assignment applies to all programs in the country.

User (all programs)
Basic Admin (all programs)

- [X] 2. Add a column header to the checkbox column. Suggestion: "Access"

Copied over from #1500: As a stopgap, we could at least label that column:

![image](https://user-images.githubusercontent.com/169060/57098523-279ad780-6ccf-11e9-9612-0579e8141d77.png)

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [x] i18n strings included
- [x] Is accessible to people using screen readers

**Comment by axoplasm** [comment]
I addressed criterion 2 as a sideways stopgap for #1500:

![image](https://user-images.githubusercontent.com/169060/57098523-279ad780-6ccf-11e9-9612-0579e8141d77.png)

**Comment by axoplasm** [comment]
While I’m in here, I could relabel the “None” option for countries which is currently “” (blank):

![image](https://user-images.githubusercontent.com/169060/57102999-81a09a80-6cd9-11e9-9e8e-2abf36fa0432.png)

like maybe “no country access” or “Individual programs only”

![image](https://user-images.githubusercontent.com/169060/57103130-d3492500-6cd9-11e9-8d20-ff14e862094f.png)

**Comment by jennyhavah** [comment]
> like maybe “no country access” or “Individual programs only”

I really like "Individual programs only"! It contrasts nicely with "(all programs)" in the other options.

I get what you're saying with "no country access" but I think it will confuse users -- they have no concept of the database model or how you could possibly have access to programs in a country without having access to the country.

**Comment by jennyhavah** [comment]
PASSED. The checkbox column has a header called "Has access?" and the Roles and Permissions menu text is updated as shown below:

![image](https://user-images.githubusercontent.com/33670923/57164291-82543200-6da8-11e9-8f55-894caffb61a0.png)
