### ISSUE TITLE
I created a user with low - high access for one country that turned into a super admin when logged in with gmail

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1499]
I was creating an account to test this deletion of user removes change log entries issue -
I created a new account, and used the GMAIL option to login when I received my registration email. This user was set in the MERCY CORPS organization.

Upon logging in with this new user via GMAIL, I was immediately given super admin status?
Though, when I set a password, and login that way(u/pw), I do not have super admin status (edited) 
heres the account:
deletemeinaminute@gmail.com

This account when making changes to things like indicators, etc.. is showing in the change log as account test high (mctest.high@gmail.com)

**Comment by camgnostic** [comment]
So, I hate "unable to reproduce" as much as the next person, but I've just spent a couple hours working to reproduce this issue on a variety of browsers (Chrome, Chrome Incognito, Firefox, Firefox Private) and on both local and -dev2, with three different accounts, trying various combinations of logout, login, and login in a different window.  Can't get the issue to happen again.

Tentative diagnosis?  I think Chrome did a bait-and-switch with the google login (sessioned his login info, didn't update it with the new address on logging in with the new email address, and sent back the previously-authed credentials on the redirect back to Tola).  That's pretty speculative, but it's my best guess for now.

**Comment by hannalcamp** [comment]
I think until we see the same thing happen again to anyone else, we can't really move on it. I can write this scenario down for us to test out with the observational testing groups over the next few days?

**Comment by RickieT** [comment]
### QA Passed:
* Can no longer reproduce issue by simultaneous logins through gmail
* Other login options remain unaffected
