### ISSUE TITLE
Browse documents: Layout, labeling, and link modifications

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#150]
This ticket includes layout changes, column header edits, and link changes.

![image](https://user-images.githubusercontent.com/33670923/50929208-87fcc500-1411-11e9-9d0e-c851514eb95e.png)

# Acceptance criteria
- [x] 1. ~Update page title from "Documents" to "Records"~ **UNDO**
- [x] 2. Changes to _Date Created_ column
     - [x] 2.1. Change column header to "Date added" -- note sentence case.
     - [x] 2.2. Unlink the dates.
     - [x] 2.3. Move the column to the right of the Document Name column.
     - [x] 2.4. Localize the dates, as we already do on the similar Browse > Sites page. (This requirement is not reflected in the mockup at the bottom of this ticket -- just didn't seem like a great use of time to mock it up.)
- [ ] 3. Changes to _Document Name_ column
     - [x] ~3.1. Change column header to "Record"~ **UNDO -- change to "Document" instead**
     - [x] 3.2. The linked document no longer takes you to the document object form. Instead, it opens the actual link in a new tab.
- [x] 4. Change to _Actions_ column: Delete the column header "Actions". No column header is needed.
     - [x] 4.1. Column is no longer sortable either because what the heck does that even mean in this case.
- [x] 5. "Add document" button changes
     - [x] ~5.1. Relabel the button "Add result"~ **UNDO**
     - [x] 5.2. Right-align the button to make it more visible and consistent in its placement with "Add a thing" buttons elsewhere.

In the end it'll look something like this:
![image](https://user-images.githubusercontent.com/33670923/50995760-e2ab2500-14d4-11e9-8b53-7e2f54c33e61.png)

**Note:** Updating of the program filter is covered in ticket #834. Adding record search is covered in ticket #645

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [ ] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by KennyMonster** [comment]
@jennyhavah As part of this ticket, should all of the links throughout the app currently labeled "Documents" also be renamed to "Results"? For instance, in the nav menu, program page sidebar, etc.

**Comment by KennyMonster** [comment]
@jennyhavah There is still support for the "Project name" on this view for the few countries still using that part of the app. Do we want to continue to support this as part of the revamp?

**Comment by jennyhavah** [comment]
> As part of this ticket, should all of the links throughout the app currently labeled "Documents" also be renamed to "Results"? For instance, in the nav menu, program page sidebar, etc.

@KennyMonster I think you mean Documents > Records? Right now the text replacements are integrated into a bunch of other tickets, plus 823, 840, here, etc. If it's easier to tackle it as a global task, I'm open to creating a new ticket for that... But I would prefer to keep the current tickets as they are -- as QA reinforcement if nothing else.

**Comment by KennyMonster** [comment]
@jennyhavah 

> If it's easier to tackle it as a global task, I'm open to creating a new ticket for that...

I think this would be best as I'm seeing around 10 different places searching the code that would need to be updated.

> Would there be an easy way to only display that column if the country has access to Projects? What I'd like to avoid is an empty column with a header -- Projects -- that most of our users won't recognize.

I can keep it functioning as it does today. I think that also answers my next question of if it's worth keeping the "project" filter capability, which is utilized by a the project apps. Basically if you specify a project id in the 2nd number of the URL (e.g. /workflow/documentation_list/0/123/), it will only show you Records for that project.

As it stands today, there is no UI indication that the view is of records for a given project though.

**Comment by KennyMonster** [comment]
@axoplasm The Datatables table has been replaced w/ react-bootstrap-table2. The SCSS is now linked into `tola.scss`:

```
@import "components/react-bootstrap-table/react-bootstrap-table2";
@import "components/react-bootstrap-table/react-bootstrap-table2-paginator";
```

I'm thinking the name and project name column should be expanded while the date and actions column contracted. Right now they are all event width.

The 3 filters + add record link are using BS columns which also seems not ideal but I'm not sure how to do this better.

For markup, see the components that live in: `js/pages/record_list/components/record_list.js`

**Comment by RickieT** [comment]
I believe the UI elements in the documents page match the changes listed above. Functions on this page remain functional after said changes. Moving to Ready for Deploy

**Comment by RickieT** [comment]
**Deployment Verification** 
- [x] Confirming “Ready for Deploy” status
