### ISSUE TITLE
Admin: Country disaggregations: UI updates

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1503]
# Issues
This ticket covers a number of UI improvements. Some of these items were mocked up but not implemented during Papaya, and I've added some additional refinements. 

**Note:** The mockup in this ticket depicts disaggregation categories as re-orderable, and this is currently not the case. Because this is not a trivial level of effort, we've pulled that UI aspect into another ticket -- #1872.

# Acceptance criteria

## Small text and layout tweaks

![image](https://user-images.githubusercontent.com/33670923/71428989-20b73f80-2679-11ea-9fde-ddfa21d5f97e.png)

- [x] 1. Rename the "Add another option"  button to "Add a category".

- [x] 2. Change placeholder text "New Disaggregation type" to "New disaggregation". (Please note sentence case.)

- [x] 3. Change the list title "Labels" to "Categories" -- to be consistent with "Add a category".

- [x] 4. Move "Add country disaggregation" button to upper right corner

     I noticed that Paul's mockup shows the "Add country disaggregation" in a different location than where it is on Production. I think his mockup placement makes the button more visible, and is more consistent with the upper right placement of "add a thing" buttons globally -- users, programs, organizations, indicators, etc.

## Streamline process of adding the first option

- [x] 1. When I click "Add country disaggregation",  the first option row appears automatically. 

     Right now, I have to click two different add buttons to add my first disaggregation option. I'd like to see the flow be more similar to indicator setup; when you select the "Event" target frequency, we automatically display your first event row. We don't make you _also_ click "Add an event" for that first event.

## Housekeeping
* [ ] ~Unit test/s written wherever applicable~
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
The small text tweaks should be pretty easy but the Streamlining of first-category disaggregation could push the ticket into Medium territory.

**Comment by camgnostic** [comment]
Not automating tests for this one as it is >90% text tweaks.  Verified expected behavior in English/French/Spanish, and will add automated tests with #1872

**Comment by jennyhavah** [comment]
All elements are in place. Needs some styling tweaks. Here's a better snapshot of the mockup without the bottom cut off, for reference:

![image](https://user-images.githubusercontent.com/33670923/71383420-25a0c400-2591-11ea-93d5-34d7db81f1e3.png)

- [ ] 1. "Selected by default" should be a bit closer to the bottom of the disaggregation field above.

- [ ] 2. "Selected by default" should be the smaller font size -- same size used for the form label above.

- [ ] 3. Add space in between that check box and "Categories".

- [ ] 4. "Categories" should be larger font size (not a header size, just the normal body font size), bold, and dark gray.

- [ ] 5. Need roughly half the amount of space between the final category text box and the "Add a category" button.

- [ ] 6. Need a lot more vertical space between "Add a category" and "Save changes".

**Comment by jennyhavah** [comment]
Updated mockup in the main ticket to make it easier to compare before/after, and incorporated the new lock icon requested in the comment above.

**Comment by jennyhavah** [comment]
Looking much better! Just a few more small tweaks:

> 1. "Selected by default" should be a bit closer to the bottom of the disaggregation field above.

It's a little bit TOO close now, so that it feels a bit crowded. See how much space there is between the "Disaggregation" label and the top of the text box? Can we have the same amount of space between the checkbox and the bottom of the text box? (I know it's not an exact science, just trying to put into words the look I'm after.)

> 3. Add space in between that check box and "Categories".

Needs a bit more space, like about 50% more distance.

> 5. Need roughly half the amount of space between the final category text box and the "Add a category" button.

Vertical distance looks better. Can you make the "Add" icon more aligned with the reorder handles? Closer to how it looks in RF builder:

![image](https://user-images.githubusercontent.com/33670923/71492076-790d4f00-27e9-11ea-8164-b87c9c3e1baf.png)

>  7. "Order" label is missing, above reordering drop-downs. 

Is it fairly easy to have "Order" exactly flush left with the number dropdowns? Here's how it looks on my screen:

![image](https://user-images.githubusercontent.com/33670923/71492106-a659fd00-27e9-11ea-95e5-63e6fef412d3.png)

If it's NOT easy, having it centered over the dropdown column would also be fine.

> 9. When a "Remove" button next to a disaggregation category is disabled, I think people will need an explanation of why it's not editable or removable. Here's an idea: Instead of a disabled "Remove" button, we follow the pattern used in the RF builder and replace it with a lock icon, like so:

![image](https://user-images.githubusercontent.com/33670923/71425482-5b59b180-2652-11ea-93d9-4d8e2492dc68.png)

 On-click, the icon says, "This category cannot be edited or removed because it was used to disaggregate a result."

To be clear, this is _only_ for categories. The "Delete disaggregation" button should remain as is.

Not seeing this update yet... Happy to put it in a new ticket if you prefer -- just let me  know.

**Comment by jennyhavah** [comment]
After I fill out a field and move on to the next, it has a green outline around it, instead of returning to the previous gray.

![image](https://user-images.githubusercontent.com/33670923/71494294-df4e9d80-27fa-11ea-8acf-be68ea8f84e4.png)

And when I'm being corrected, I'd expect the relevant fields to have a red outline. Instead, it's green.

![image](https://user-images.githubusercontent.com/33670923/71494299-e5dd1500-27fa-11ea-8ce7-2581414c2e0c.png)

**Comment by jennyhavah** [comment]
Right now, the numbers are not all right-aligned, and pink background highlighting extends the entire width of the number field, like this:

![image](https://user-images.githubusercontent.com/33670923/71494597-1faf1b00-27fd-11ea-8aed-23dd5a028530.png)

In Paul's original design for this, he has the pink highlighting behind the number only -- which really draws attention to the delta -- and the numbers are all right-aligned, like this:

![image](https://user-images.githubusercontent.com/33670923/71494434-1ffae680-27fc-11ea-9ea4-7e683053bbca.png)

**Comment by jennyhavah** [comment]
> 3. Add space in between that check box and "Categories".

Needs a bit more space, like about 50% more distance.

**Comment by jennyhavah** [comment]
> 5. Need roughly half the amount of space between the final category text box and the "Add a category" button.

Vertical distance looks better. Can you make the "Add" icon more aligned with the reorder handles? Closer to how it looks in RF builder:

![image](https://user-images.githubusercontent.com/33670923/71492076-790d4f00-27e9-11ea-8164-b87c9c3e1baf.png)

**Comment by jennyhavah** [comment]
>  7. "Order" label is missing, above reordering drop-downs. 

Is it fairly easy to have "Order" exactly flush left with the number dropdowns? Here's how it looks on my screen:

![image](https://user-images.githubusercontent.com/33670923/71492106-a659fd00-27e9-11ea-95e5-63e6fef412d3.png)

If it's NOT easy, having it centered over the dropdown column would also be fine.

**Comment by jennyhavah** [comment]
> 9. When a "Remove" button next to a disaggregation category is disabled, I think people will need an explanation of why it's not editable or removable. Here's an idea: Instead of a disabled "Remove" button, we follow the pattern used in the RF builder and replace it with a lock icon, like so:

![image](https://user-images.githubusercontent.com/33670923/71425482-5b59b180-2652-11ea-93d9-4d8e2492dc68.png)

 On-click, the icon says, "This category cannot be edited or removed because it was used to disaggregate a result."

To be clear, this is _only_ for categories. The "Delete disaggregation" button should remain as is.

Not seeing this update yet... Happy to put it in a new ticket if you prefer -- just let me  know.

**Comment by jennyhavah** [comment]
There are a couple of scenarios where it would be nice if we focused on the first input field so I can just start typing:

1. I click "Add a new country disaggregation". It'd be nice if the Disaggregation field already had focus so I can start typing.

![image](https://user-images.githubusercontent.com/33670923/71496265-41150480-2807-11ea-999f-488eca8dbbc1.png)

2. I click "Add category". It would be nice if the new category field had focus so I can start typing. It looks like the button retains the focus -- stays highlighted, etc.

![image](https://user-images.githubusercontent.com/33670923/71496311-81748280-2807-11ea-8ee2-c5c073e3b7b2.png)

**Comment by jennyhavah** [comment]
Everything looks good except for one issue -- https://github.com/mercycorps/TolaActivity/issues/1503#issuecomment-569141703 -- and I created a new ticket for it.

Moving this to Passed!
