### ISSUE TITLE
Home page gauge charts: Random string appears in French

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1504]
**Affects:** Country page

I'm looking at country pages translated into French, _on Production_. Check this out:

![image](https://user-images.githubusercontent.com/33670923/56780212-4bbc5d00-6793-11e9-8996-6181a1a569df.png)

I do not see anything similar in Spanish or English -- only French.

**Comment by RickieT** [comment]
### QA Passed:
* Glossed over many programs on country pages in french, was unable to see error described in image attached to this ticket:
![image](https://user-images.githubusercontent.com/23220180/57109152-95ec9380-6ce9-11e9-8e17-f9e80407320c.png)
