### ISSUE TITLE
Nav bar: Add Firstname Lastname drop down menu with Settings and Logout

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1505]
# Issue
From Cameron in Slack: Hello UX/UI folks - quick question: we had a potentially one-off not-reproducible bug that maybe let Rickie log in as the wrong user.  I know that’s concerning.  We’re having trouble making it happen again though, so we thought maybe a way to help make sure it hasn’t happened again, and also as just good UI practice, would it be alright to add a username to the top right (like in the top right of the menu bar, replacing “Settings”, with a dropdown arrow, like on many other menu-bar sites)? could drop down to a menu containing “settings” and “log out”, addressing another UI concern that’s been raised a couple times, albeit mainly by Tola folks doing testing

# Acceptance Criteria

- [x] 1. Replacing the Settings menu is a drop-down menu comprised of the users full name: Firstname Lastname. 

- [x] 2. The menu styling is identical to other drop-downs in the nav bar.

- [x] 3. The first menu option is "Settings". It takes you to the Settings page.

- [x] 4. The second menu option is "Log out". It logs you out of TolaActivity and sends you to the login page.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by axoplasm** [comment]
Commit f4cdc6b1 narrowly addresses the criteria above. This raises the secondary issue of what to do with the profile page (this is where “settings” takes you), which right now only lets you change language. 

![image](https://user-images.githubusercontent.com/169060/56829573-f62a9380-6818-11e9-9578-61ecd85ac362.png)

We could let end users change all kinds of things here, like username, email and other stuff. Or at least display it:

![image](https://user-images.githubusercontent.com/169060/56829610-14908f00-6819-11e9-9399-5521babeb2e3.png)

**Comment by RickieT** [comment]
### QA Passed:
There we go: 
![image](https://user-images.githubusercontent.com/23220180/56831084-12303400-681d-11e9-9c5b-63ff2752881b.png)
