### ISSUE TITLE
Document Form: Name and URL are not required

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#151]
**Problem:** It is possible to save the Document Form with no name or URL. In addition to littering the system with garbage document forms, saving a document form with no name actually breaks access to indicator configuration data for the entire program! 

**Acceptance criteria**
1. "Name of document" and "URL" fields are required, with an asterisk next to the label.
2. If you try to save the form with either of those two fields empty, you are prompted with our standard "Please complete this field" message.

**Comment by jennyhavah** [comment]
Please remove the "required" asterisk (and any associated form validation) from the Description and Project form fields.

**Comment by jennyhavah** [comment]
Program should be required, but we need multi-select capability. (Sonia and Marie pointed out a couple of scenarios where it makes sense to associate the same piece of evidence with more than one program -- i.e. secondary data or an indicator tracked at the country level.)

**Comment by mahmoodkhan** [comment]
Changing program to multi select has much wider implication for permissions and else where. I suggest we first understand the scope of this change before implementing it.

**Comment by jennyhavah** [comment]
![image](https://user-images.githubusercontent.com/33670923/40259678-051b9c52-5aac-11e8-8103-d6199ff85388.png)

I'm not seeing a validation message for "Name of Document" when the field is left empty.

Also, the Gdrive button grows taller (see image above) when the validation message appears. It should stay the same size.
