### ISSUE TITLE
Navigation menu options are inconsistent with page titles and breadcrumbs are a mess

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#152]
This ticket is related to #129 -- Simplify page titles and consistently say "Add thing" instead of "new thing"

We have a number of instances where the navigational menu option does not match the page title you land on, so that you have to memorize which menu option takes you to which page. In a somewhat related issue, our navigational breadcrumbs are confusing and unhelpful. This is partially due to confusing naming of things. But it also has to do with how they're structured.

**Comment by jennyhavah** [comment]
When I click on "Add project", it's the correct page but the breadcrumb and page title say "Project Dashboard". I'd expect them both to say "Project".

**Comment by axoplasm** [comment]
I missed this one BUT on investigation it's a complicated fix. The same template is used for "Add project" and "Project Dashboard" (i.e. after the project is initiated)

**Comment by jennyhavah** [comment]
All page titles and breadcrumbs validated, including "Add project" and "Project dashboard".
