### ISSUE TITLE
Password reset email uses bare mercycorps.org link, omits hostname

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1521]
Currently the "sites" setting on all our servers (QA, dev2, production) is set to "mercycorps.org" which redirects to www. We need to set this explicitly to [hostname].mercycorps.org if only for the sake of our password reset email:

![image](https://user-images.githubusercontent.com/169060/56923208-d4324a80-6a7e-11e9-9985-d2c05250c34d.png)

**Comment by axoplasm** [comment]
Update: per conversation with @sanjuroj I am going to extend the auth view that sends this email so it can get a proper hostname using `request.build_absolute_uri()` or a global setting

**Comment by RickieT** [comment]
**QA Passed:**
* **Dev 2: Both gmail and password page links were accessible as expected**
![Screen Shot 2019-04-30 at 9 20 39 AM](https://user-images.githubusercontent.com/23220180/56977069-3a73a780-6b29-11e9-9f8a-23725c4335ad.png)
* **QA: Both gmail and password page links were accessible as expected**
![Screen Shot 2019-04-30 at 9 21 37 AM](https://user-images.githubusercontent.com/23220180/56977127-5e36ed80-6b29-11e9-9637-641fe191c3f9.png)
