### ISSUE TITLE
Papaya missing/weird translations (Spanish & French)

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1523]
# Issue
Missing translation strings in the new Admin UI and change log

- [ ] 1. "Add User" button (Spanish & French) and "Apply" button don't translate on Users Page

![Screen Shot 2019-04-29 at 2 00 46 PM](https://user-images.githubusercontent.com/38020496/56923519-fd0b0d80-6a87-11e9-8217-3fdb8e9f2c66.png)

> __Paul__: AFAICS this is marked correctly and in the js .po file. It’s marked `fuzzy`

- [x] 2. "Profile" next to user name in the Profile drop-down.

![Screen Shot 2019-04-29 at 2 00 38 PM](https://user-images.githubusercontent.com/38020496/56923518-fd0b0d80-6a87-11e9-94aa-8f37dfbe9095.png)

> __Paul__: fixed in 476a800e

- [ ] 3. Bulk action secondary select box

![Screen Shot 2019-04-29 at 2 04 13 PM](https://user-images.githubusercontent.com/38020496/56923522-fd0b0d80-6a87-11e9-9c88-edb3e4eb4276.png)

> __Paul__: There is a related styling issue, now in ticket #1529

> __Paul__: There was no explicit placeholder for this, so it was using the library’s default. I added a placeholder in 049d96d8 . We will need to add this to the .po file.

5.  French translations have <tab> in place of an apostrophe

![Screen Shot 2019-04-29 at 2 04 28 PM](https://user-images.githubusercontent.com/38020496/56924365-f2ea0e80-6a89-11e9-8d99-b12ba80e0a97.png)

**Comment by axoplasm** [comment]
Program landing page: “Indicators missing ___”

![image](https://user-images.githubusercontent.com/169060/56980556-862a4f00-6b31-11e9-9c4f-fbb2fc485c42.png)

**Comment by axoplasm** [comment]
Program landing page: “Program metrics for target periods completed to date”
![image](https://user-images.githubusercontent.com/169060/56980606-a0fcc380-6b31-11e9-9cd7-c5dda897b6e1.png)

**Comment by axoplasm** [comment]
Program landing page: “Change log” button
![image](https://user-images.githubusercontent.com/169060/56980658-c38edc80-6b31-11e9-8f85-0b390c508d9d.png)

**Comment by camgnostic** [comment]
I'm running down the reports section.  Starting with IPTT:
None selected in filters (translated but showing english)
Excel (shouldn't be translated as a verb)
Change log (translated but showing english)

Change log:
Date and time (translated but showing english)
Indicator change log (translated but showing english)
Change type (translated but showing english)
Previous entry (translated but showing english)
New entry (translated but showing english)
Reason for change (translated but showing english)

Disaggregation report:
Show X entries (not translated)
No data available in table (not translated)
Showing X to X of X entries (not translated)
Previous (translated but showing english)
Next (translated but showing english)

Project report:
Project statuses (translated but showing english)
Export to CSV (translated but showing english)
All headers (translated but showing english)
Edit and View buttons (translated but showing english)
Show X entries (not translated)
Search: (translated but showing english)
Showing x to x of x entries (translated but showing english)
Previous (translated but showing english)
Next (translated but showing english)

**Comment by axoplasm** [comment]
- [ ] Results modal: “This may be a badly formatted web address…”
![image](https://user-images.githubusercontent.com/169060/56982639-a14b8d80-6b36-11e9-8780-0e8fa5382d2d.png)

**Comment by KennyMonster** [comment]
"Program or country" isn't translated in ES in the nav bar

![Screen Shot 2019-04-30 at 10 56 28 AM](https://user-images.githubusercontent.com/1278224/56983010-71e95080-6b37-11e9-8018-d90c63164790.png)

**Comment by KennyMonster** [comment]
"No options" is inside a JS library and not translated ATM. This can be fixed by overriding it with a translated string.

![Screen Shot 2019-04-30 at 11 31 23 AM](https://user-images.githubusercontent.com/1278224/56984777-abbc5600-6b3b-11e9-8e63-d3a6cdc00e4f.png)

**Comment by KennyMonster** [comment]
The change log field names are always in english, as the translated strings call gettext during the class instantiation, instead of on a per-request basis.

![Screen Shot 2019-04-30 at 12 31 22 PM](https://user-images.githubusercontent.com/1278224/56988020-e2966a00-6b43-11e9-9cb3-8cfe76221bc9.png)

**Comment by axoplasm** [comment]
- [ ] Admin lite, Program page: “users” is not translated:

![image](https://user-images.githubusercontent.com/169060/56988156-343ef480-6b44-11e9-8237-06bac96c4ac7.png)

**Comment by RickieT** [comment]
### QA Passed:
* FRENCH:
![image](https://user-images.githubusercontent.com/23220180/57108880-e44d6280-6ce8-11e9-94bc-7d41e058fc09.png)
* Secondary Select box FRENCH:
![image](https://user-images.githubusercontent.com/23220180/57108934-03e48b00-6ce9-11e9-8450-b5d7c8ce6b09.png)
* SPANISH:
![image](https://user-images.githubusercontent.com/23220180/57109011-35f5ed00-6ce9-11e9-802f-bded435498f4.png)
