### ISSUE TITLE
Home page: Restore % program period complete info and link to program period modal for Low and Medium access users

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1538]
**Affects:** People with Low and Medium access to programs

# Reproduce the issue

![image](https://user-images.githubusercontent.com/33670923/57043674-1c876f00-6c1d-11e9-837a-bdc7fecbe53a.png)

1. Log in as a user with Low or Medium access to programs.

2. Visit the home page.

3. Note that in each program block, there is no % program period complete info and no link to the program period modal in the upper right corner.

4. Note that if you click to the program page, these elements are implemented as expected, with the correct view-only permissions when you open the modal.

# Acceptance criteria

On the home page, in the upper right corner of each program block, the following things are true for all access levels -- Low, Medium, and High:

- [x] 1. I can see the program % complete graphic.

- [x] 2. When I click on the graphic, it launches the program period modal.

- [x] 3. I have the correct permissions in the modal -- View-only for Low and Medium, and View/Edit for High.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by KennyMonster** [comment]
@RickieT The change to make this work required changing how the Program period modal handles disabling itself based on permissions. Since this modal is used on both the home page and program page, but in slightly different ways, it would be good to test the permission cases on both pages.

**Comment by RickieT** [comment]
### QA Passed:
On program and home page with low/medium user, program period modal appeared, could not be changed. 
![image](https://user-images.githubusercontent.com/23220180/57258042-0f4cf480-7010-11e9-8967-bd3fe2f6239a.png)
