### ISSUE TITLE
"Mercy Corps" appearing as a User organization selection for Basic Administrators

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1541]
# Issue
Logged in as a Basic Administrator, I can set external users' Organization to Mercy Corps. Only Super Administrators should have this ability.

![Screen Shot 2019-05-02 at 8 09 55 AM](https://user-images.githubusercontent.com/38020496/57082026-22c82a80-6cb3-11e9-9b90-62c4daf014fe.png)

# Acceptance criteria

- [ ] 1. **Front end:** Logged in as a Basic Administrator, I am NOT able to set external users' Organization to Mercy Corps. Ideally, I don't even see that option in the menu. If that's hard for some reason, then it should at least be grayed out / un-selectable.

- [ ] 2. **Back end validation:** Prevent Basic Admins from being able to select Mercy Corps as an Organization. (We don't want Basic Admins to be able to grant country status using Organization selection as a kind of back door.) The system message can say: Mercy Corps users are managed by our Single Sign On provider and cannot be manually assigned. 

## Housekeeping (where applicable)
- [ ] Unit test/s written
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by KennyMonster** [comment]
@hannalcamp @jennyhavah 

> Front end: Logged in as a Basic Administrator, I am NOT able to set external users' Organization to Mercy Corps. Ideally, I don't even see that option in the menu. If that's hard for some reason, then it should at least be grayed out / un-selectable.

It's easy enough to do this either way (hiding the whole element vs graying it out). Having set it to be hidden though, I'm thinking graying it out would be preferable, otherwise a basic admin will have no idea what organization a given user belongs to.

**Comment by jennyhavah** [comment]
> Edit: I just realized you meant remove "Mercy Corps" from the list of options, and not the entire list widget itself... the coffee is finally kicking in.


Lol... Yes, I'm suggesting we keep the menu, just hide Mercy Corps as an option.

**Comment by RickieT** [comment]
### QA Passed:
Confirmed: Basic admin cannot set user to mercy corps org
![image](https://user-images.githubusercontent.com/23220180/57258138-5935da80-7010-11e9-87f2-38890247bf6a.png)
