### ISSUE TITLE
Admin Lite Users Page: One or two blank names appear at the top of the Users list

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1542]
# Issue
Periodically, blank names have appeared at the top of the Users list. Brad Goettemoeller is consistently among them, his profile contains his name, but for some reason it does not render in the list. Currently the tolatesttwo@mercycorps.org account also appears as blank, even though it too has a name in the profile.

![Screenshot17](https://user-images.githubusercontent.com/38020496/57094231-49935a80-6ccd-11e9-9b38-b24e51209985.png)
![Screenshot18](https://user-images.githubusercontent.com/38020496/57094232-4a2bf100-6ccd-11e9-8696-d54f820799f2.png)

## Housekeeping (where applicable)
- [ ] Unit test/s written
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by RickieT** [comment]
### QA Passed:

* Brad now showing up in search and list appropriately
![image](https://user-images.githubusercontent.com/23220180/57108239-f75f3300-6ce6-11e9-9415-eb5c0c0b60c7.png)
* New users logging in through okta were populated in user list and were searchable as expected, and did not appear with blank names.

**Comment by sanjuroj** [comment]
Some of these were from a bug in the Okta login function, one is due to pre-existing incomplete data.
