### ISSUE TITLE
Multi-select fields on Indicator Form fail to save

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#1554]
# Indicator form

On the Indicator Form, the following fields use a multi-select dropdown:

* Program Objective
* Country Strategic Objective
* Disaggregation
* Indicator Type

Select multiple values in the pulldown for any of these fields, press "Save Changes", then close and re-open the form. Notice that only 1 value is selected, instead of all the values you just selected.

Before save:

![Screen Shot 2019-05-08 at 1 51 19 PM](https://user-images.githubusercontent.com/1278224/57407607-74cbed00-7198-11e9-879a-b175d1472428.png)

After save:

![Screen Shot 2019-05-08 at 1 51 38 PM](https://user-images.githubusercontent.com/1278224/57407625-7990a100-7198-11e9-80c0-67c953451689.png)

# Result form

The same issue occurs with the Sites multi-select on the Result form.

# Admin lite

Any issues with multi-selects here?

# Data loss?

Did we lose any previous selections?

**Comment by KennyMonster** [comment]
RE: Admin lite - the multi-selects there should be fine. The issue with the Indicator and Result forms were the snapshot code that was tacked on at the end for the rationale prompts. Basically it was squashing the multi-select values down to the last one.

Re: Data loss - If anyone edited an Indicator or Result, that had multiple items selected in a multi-select field, and then hit save, there would have been data loss.

For the sake of search/recovery of said data, I think these changes would have actually been logged in the change log.

A fix to correct handling of multi-select fields has been pushed.

**Comment by jennyhavah** [comment]
PASSED. 

Here's what I tested. I logged in as a High permission user and:

1. On the Summary tab, added multiple POs and CSOs to existing indicators of various target frequencies, saved, closed and re-opened. **_My multi-selections were preserved._**

2. On the Performance tab, ditto with Disaggregations and Types. **_My multi-selections were preserved._**

Sanjuro asked that I pay special attention to any unexpected side effects on target creation, So I did a bunch of target creation -- adding new indicators of a particular target frequency, deleting those targets and re-adding targets of a different frequency. I added midline/endline and event targets... **_Didn't run into any problems with the _Create targets_ button becoming inactive, or any other unexpected behaviors around target creation._**

**Comment by sanjuroj** [comment]
Those tests sound good to me, moving to Read to Deploy
