### ISSUE TITLE
RF Builder level tier picker

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1567]
Refers to the level picker component on the left rail of the RF Builder:
![image](https://user-images.githubusercontent.com/169060/57649090-29d91d80-757c-11e9-9cb4-a9eeb5cc9bf1.png)

**Comment by jennyhavah** [comment]
@axoplasm A few things:

1. Template name shouldn't be in all caps, and it should say "Results framework template".

2. I suggest using the smaller form label style for the above, to make it less likely that it'll wrap en français.

3. Need a character or two of space between the word "template" and the question mark icon.

What I'm seeing:

![image](https://user-images.githubusercontent.com/33670923/58841166-88deff00-861d-11e9-961c-4f51c9ba73ad.png)

**Comment by jennyhavah** [comment]
Looks good! Here's what I see on Firefox:

![image](https://user-images.githubusercontent.com/33670923/58920895-091e6680-86e9-11e9-8f07-21a2534c1c14.png)
