### ISSUE TITLE
RF Builder title

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1569]
Refers to the title of the RF builder page:

![image](https://user-images.githubusercontent.com/169060/57661904-b9dd8e00-75a1-11e9-859e-675aa7588b06.png)

- [x] Title links to Program page
- [x] Subtitle of "Results Framework" with icon
- [x] Link to LogFrame

**Comment by jennyhavah** [comment]
@axoplasm I noticed that the logframe icon to the right of the button text instead of the left, like other icon buttons. I'm wondering if that was intentional?

![image](https://user-images.githubusercontent.com/33670923/58840028-048a7d00-8619-11e9-8479-545c3a4d354d.png)

**Comment by axoplasm** [comment]
almost certainly not. I'll fix

**Comment by jennyhavah** [comment]
Passed. Logframe button looks good. I added a comment to 1570 to consider how that button vertically aligns with the rest of the title when the title wraps.
