### ISSUE TITLE
RF Builder Level(s) (collapsed)

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1571]
![image](https://user-images.githubusercontent.com/169060/57661863-83a00e80-75a1-11e9-916c-7b0349e7cb0d.png)

**Comment by jennyhavah** [comment]
@axoplasm when there's a Delete button, the label is closer to the Edit icon than it is to the Delete icon.

![image](https://user-images.githubusercontent.com/33670923/58987335-25c3a880-8794-11e9-9334-bedb3ca45b46.png)

I know there's a responsiveness-related reason why there's generous padding between the icons and the labels. But can we add more space between the two buttons?

**Comment by jennyhavah** [comment]
Looking much better.

![image](https://user-images.githubusercontent.com/33670923/59059488-f5dbda00-8853-11e9-8fc9-398a83d9ca30.png)
