### ISSUE TITLE
Give more informative message to Low/Medium users seeing a program with no indicators

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1576]
# Issue
_After_ a new program is added by an admin, but _before_ indicators are added, anyone with Low/Medium access to that program should see a message in the country home page which will inform them that no program page exists until a High-level user adds an indicator. Currently they see this message:

![image](https://user-images.githubusercontent.com/38020496/57790004-27e79980-76f7-11e9-984d-ea94f8baf48e.png)

But the message is not fully informative and "initialize" is too jargony.

## Improvements
Suggested improved message: "A program staff member with a High user role must add an indicator before you can access the program page."

In any other page where we're using similar wording, "initialize" should be replaced with something else. If other strings like that exist we can give additional replacement strings in the comments.

## Housekeeping

- [ ] Unit test/s written wherever applicable
- [ ] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
Independently came across this issue during Satsuma and updated the text. Here's what a Low/Medium user sees if a program is added but no indicators have been added yet.

![image](https://user-images.githubusercontent.com/33670923/61481219-88d85b80-a94c-11e9-9039-82f2adb79b8a.png)

Meanwhile, this is what a High or SuperAdmin sees:

![image](https://user-images.githubusercontent.com/33670923/61481272-b6250980-a94c-11e9-87d3-a3478d320d8b.png)

**Comment by jennyhavah** [comment]
Closing because fixt.
