### ISSUE TITLE
Change log: Order of indicator fields in log entries is weird

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1591]
# Issue

Logged in as a High user on a program, when deleting or modifying multiple fields of an indicator, the fields in Previous Entry and New Entry that are changed (or in the case of deletion, all fields) will appear in the change log in a strange order, which is not reflective of their actual order in the indicator form.

Example from deleted indicator:
![Screen Shot 2019-05-28 at 2 25 40 PM](https://user-images.githubusercontent.com/38020496/58513628-14a7e580-815d-11e9-8727-c99264f103e0.png)

# Suggested changes

Any tracked fields appearing in the change log should follow this ordering:
- Name
- Unit of Measure
- Unit of Measure type
- LOP target
- Direction of change
- Baseline
- Baseline N/A
- (Periodic targets)
- Is Cumulative

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah The order of diff entries is essentially being handled as part of #1520.  Should we just track it there?  Or would you prefer to have this broken out.

**Comment by jennyhavah** [comment]
@sanjuroj This ticket covers all form fields in the result form, whereas the other one focuses on disaggregations specifically. 

Even if it's the same bundle of work from a dev standpoint, this ticket is still useful to me for QA purposes.

**Comment by sanjuroj** [comment]
Ok, then just one thing to note is that there have been some changes to the form since Hanna posted the ticket, so the form's field order is a little different than the one she listed.  I've used the current Indicator form's field order in the audit log.

**Comment by jennyhavah** [comment]
Looks good! I'll describe what I did and post screenshots of the change log at each step. The updated correct order of fields is:

- Indicator
- Result level
- Unit of measure
- Unit of measure type
- Baseline
- Baseline N/A
- Direction of change
- Periodic targets
- LoP target
- Cumulative or Non-cumulative

# Created new indicator

![image](https://user-images.githubusercontent.com/33670923/74197852-08918480-4c15-11ea-8a4d-f71b71fdd84c.png)

# After adding a result, changed all tracked fields except for Unit of measure type

![image](https://user-images.githubusercontent.com/33670923/74197906-23fc8f80-4c15-11ea-9523-760465c5166e.png)

# Changed some but not all tracked fields

![image](https://user-images.githubusercontent.com/33670923/74198000-5e662c80-4c15-11ea-9ad4-450c3ee9eeaa.png)
