### ISSUE TITLE
Indicator dialogue: UI improvements

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#16]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Tuesday Dec 12, 2017 at 00:04 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/6_

----

_The following changes apply globally across all tabs of the Indicator dialogue._

**User story:** When I'm setting up my targets, I'm guided through the process with clear calls to action each step of the way.

**Background:** The UI design of the current Indicator dialogue does not afford clear calls to action. The strongest visual element is the _Form Help/Guidance_ button, and there is no way to visually differentiate target setting actions from the act of saving the entire dialogue.

**ACCEPTANCE CRITERIA**
1. **Indicator name appears at the top of the dialogue:** It's a general usability best practice to clearly communicate where you are in the system. If you momentarily step away from the task, it would be easy to lose track of which indicator you're working on.
2. **Indicator names are capped at three lines with a ... if it runs over.** (Indicators names can get quite lengthy. We want to show enough of the name to make it instantly recognizable, but not so much that it pushes the important contents of the page too far down.)
2.1 Title is formatted [Indicator type]: [Indicator name]
2.2 Font color is standard MC gray #94979C.
3. **A new footer area appears at the bottom of the dialogue:** The footer visually differentiates the "save this entire dialogue" action from target configuration actions taken inside the dialogue.
3.1 Footer has the same fill color and font treatment as the global "sticky footer" in TolaActivity, but it should not be sticky.
4. **The _Save_ button is more visually prominent than the _Reset_ action:** We do this by lengthening the button label to Save changes and making the Reset button more muted.
5. **The help link is relocated to the new footer:** Today's _Form Help/Guidance_ button dominates the dialogue and is awkwardly positioned near the X icon. Also, Form Help/Guidance is a cumbersome label that may not be intuitive to a non-technical audience. Your essential activity here is not to fill out a form; It's to set up an indicator.
5.1 The heavy blue button is replaced with a simple text link.
5.2 The button is renamed _Help_.

![indicatordialogueuiimprovements](https://user-images.githubusercontent.com/33670923/33860539-380f79a2-de8e-11e7-918f-4d4c74170f80.png)

**Comment by jennyhavah** [comment]
> Indicator name appears at the top of the dialogue…

Styling refinements to reconcile implementation with the original mockup:
![image](https://user-images.githubusercontent.com/33670923/34855272-8e1a22fc-f6f3-11e7-9454-4b99664de587.png)
1. Indicator font size is too large. Reduce from 24pt to 21pt.
2. Indicator font color is too dark. It should be MC standard gray #94979c.
3. Too much white space above the indicator name. Reduce by about 20 pixels.
4. Remove extra gray line between the indicator name and the navigation tabs.
4.1. There should be about 38 pixels between the bottom of the indicator name and the top of the currently selected tab.

**Comment by jennyhavah** [comment]
> Indicator names are capped at three lines with a ... if it runs over. (Indicators names can get quite lengthy. We want to show enough of the name to make it instantly recognizable, but not so much that it pushes the important contents of the page too far down.)

Looks like this is not implemented yet. Here's an example of an indicator that was not capped at three lines:

![image](https://user-images.githubusercontent.com/33670923/34855364-04bc4a66-f6f4-11e7-8569-70d40fbb6537.png)

**Comment by jennyhavah** [comment]
> Title is formatted [Indicator type]: [Indicator name]

Looks like this is not implemented yet. We're only displaying the name, not the type.

**Comment by jennyhavah** [comment]
> Footer has the same fill color and font treatment as the global "sticky footer" in TolaActivity, but it should not be sticky.

![image](https://user-images.githubusercontent.com/33670923/34855634-a91f30b8-f6f5-11e7-8ef3-362031c6def0.png)

1. The medium gray background should be #d7d7d7. (It's currently #cccccc.)
2. The light gray border should be #f5f5f5. (It's currently #e5e5e5
3. The light gray border is twice as thick as it should be.

**Comment by jennyhavah** [comment]
> The Save button is more visually prominent than the Reset action: We do this by lengthening the button label to Save changes and making the Reset button more muted.

1. The Reset button should have no fill, or a fill color that matches the background #d7d7d7.
2. Reset button border color is MC gray #B8BABD
2. Reset button font color is MC gray #71757B.

**Comment by jennyhavah** [comment]
Help link color is #888888 -- to match gray used in the Reset button.

**Comment by jennyhavah** [comment]
Can we set the margins to 20px on both sides? That is, the "Save changes" button is indented 20 pixels from the left, and the "Help" icon is 20 pixels from the right.

**Comment by jennyhavah** [comment]
The gray "Save changes/Reset" bar needs to be 75 pixels high in both the modal and non-modal version. The non-modal version is quite a bit shorter and the modal version is just a little bit off.

![image](https://user-images.githubusercontent.com/33670923/35199002-2e9a6038-feac-11e7-805c-1c44193172bf.png)

**Comment by jennyhavah** [comment]
Both modal and non-modal versions

If you choose the Midline and endline type of target frequency, there is no space between the bottom of the table and the top of the gray "Save changes" bar. In the non-modal version, the table even covers up part of the bar.

Right now the spacing is perfect in the MODAL version for all target types except Midline/Endline -- about 30 pixels between the bottom of the "Add a target" button and the top of the gray "Save changes" bar. What we're after is to always have that 30 pixels breathing room regardless of whether or not there is an "Add target" button.

Here's what I'm seeing for the modal version:
![image](https://user-images.githubusercontent.com/33670923/35199075-7ef926ee-fead-11e7-9ad0-80f87519d7c6.png)

And the non-modal version:
![image](https://user-images.githubusercontent.com/33670923/35199076-86f0463e-fead-11e7-855d-59d5058d60d6.png)
