### ISSUE TITLE
Fix RF testing program creation script (and incorporate with QA script?)

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1603]

**Comment by jennyhavah** [comment]
@camgnostic I now see the program "RF Program -- Mercy Corps Framework" on the Tolaland country page and IPTT landing page.

For some reason, it's not showing up in the "Program or country" search box in the top nav bar.

I often use that to quickly get to a QA program... If it's easy, can you make sure it appears there?

**Comment by jennyhavah** [comment]
Program is there! We'll learn more about what we need from it as I start to use it to test other tickets.
