### ISSUE TITLE
IPTT: Make the dashes consistent

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1604]
# Issue

**Affects:** Any column in the IPTT where it's possible to have a "nothing to see here" dash

Here's how the dashes look on QA right now -- with the exception of the No. column

![image](https://user-images.githubusercontent.com/33670923/58666083-43ea5e00-82e7-11e9-82ec-29a90a98e9b3.png)

This symbol closely resembles the negative sign we use in the Direction of Change column.

I'd prefer to see the dashes look the way they do on the program page, like this:

![image](https://user-images.githubusercontent.com/33670923/58666012-0c7bb180-82e7-11e9-92f3-db3ec789bd40.png)

**Comment by jennyhavah** [comment]
@camgnostic There are several columns where we do NOT want the dashes, where "N/A" is an actual choice in the menu, and so N/A in the IPTT is appropriate:

1. Direction of change
2. Cumulative/non-cumulative
3. Baseline

We need to restore the N/As for those columns.

Dashes everywhere else look 👍

**Comment by jennyhavah** [comment]
@camgnostic Direction of change and baseline now look good -- I see the N/As.

Regarding number 2 in my last comment: There is actually an edge case where we need to see N/A in Cumulative/Non-cumulative -- that is when the target frequency is LoP only.

If you run an IPTT on Prod for the Haitian program Ann viv Ansanm, look at the C/NC column and note that some of them are N/A -- those are LoP only.

On QA, it's defaulting to "Non-cumulative" for LoP-only indicators.

**Comment by camgnostic** [comment]
Got it!  I missed that piece of logic.  Should be addressed in this latest commit!

**Comment by jennyhavah** [comment]
Looking good! I now see the N/As for LoP-only indicators. Passed.
