### ISSUE TITLE
Update Home Page to use new Indicator creation form modal (old programs) or direct you to the RF builder (new programs)

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#1611]
# Scenario 1: A program is using OldLevels

- [x] 1. If the reporting start and end dates are missing, you see this:

     ![image](https://user-images.githubusercontent.com/33670923/59318490-194fbc00-8c7c-11e9-916b-3b91eaea464a.png)

- [x] 2. If there are no indicators, you still see this, and can access the indicator modal as we'd originally envisioned.

     ![image](https://user-images.githubusercontent.com/33670923/59318521-2ec4e600-8c7c-11e9-905f-53b82ad03a0c.png)

# Scenario 2: A new program was just added, and has no RF levels (HIGH PERMISSION)

- [x] 1. You see a message that is linked to the RF builder page: Start building your results framework and adding indicators.

# Scenario 2a: A new program was just added, and has no RF levels (LOW OR MEDIUM PERMISSION)

- [x] You see the following -- note that I've crossed out the "Add indicator" button since they can't. It's purely informational.

![image](https://user-images.githubusercontent.com/33670923/59545121-fff27e00-8ece-11e9-8790-16f07ea17979.png)

# Scenario 3: A program has at least one RF level but no indicators.

- [x] 1. You see a message that is linked to the RF builder page: Start adding indicators to your results framework.

**Comment by jennyhavah** [comment]
@KennyMonster copying your comment from Slack: 

> So I got the indicator form modal on the home page, but after trying to create an indicator, I’m not sure it makes sense to have it here. The reason being is that the Result level is required, but the levels have not been configured yet, so the form is kinda useless at this stage. What’s worse is there’s not link to the program page to get to the RF builder.

What do you think about this approach?

# Scenario 1: A program is using OldLevels

- [ ] 1. If the reporting start and end dates are missing, you see this:

     ![image](https://user-images.githubusercontent.com/33670923/59318490-194fbc00-8c7c-11e9-916b-3b91eaea464a.png)

- [ ] 2. If there are no indicators, you still see this, and can access the indicator modal as we'd originally envisioned.

     ![image](https://user-images.githubusercontent.com/33670923/59318521-2ec4e600-8c7c-11e9-905f-53b82ad03a0c.png)

# Scenario 2: A new program was just added, and has no RF levels

- [ ] 1. You see a message that is linked to the RF builder page: Start building your results framework and adding indicators.

# Scenario 3: A program has at least one RF level but no indicators.

- [ ] 1. You see a message that is linked to the RF builder page: Start adding indicators to your results framework.

**Comment by KennyMonster** [comment]
![Screen Shot 2019-06-13 at 3 03 04 PM](https://user-images.githubusercontent.com/1278224/59470787-b120e780-8ded-11e9-9d52-c0181231d831.png)

What the links ended up looking like.

**Comment by jennyhavah** [comment]
@KennyMonster I just thought of a role/permissions edge case:

As described in #1246, people with Low or Medium access to a program are only supposed to see the results framework after at least one level has been saved. 

Please check out Scenario 2a that I just added to the ticket, and let me know if that is easy to do. And if not, what you'd recommend.

**Comment by KennyMonster** [comment]
@jennyhavah I think this permissions case is already taken care of. If there are 0 indicators on a program, and a user does not have "high" level permissions, the following message is displayed:

"Your program administrator must initialize this program before you will be able to view or edit it"

**Comment by jennyhavah** [comment]
@KennyMonster That sounds like a system message authored by Parthenon. I mean... "initialize"???  ;-)

It's also not particularly helpful for someone with Low or Medium permission.

If we updated it to the text I suggested in 2a, would it be wacky for other scenarios in which that message is used?

**Comment by KennyMonster** [comment]
@jennyhavah 

> If we updated it to the text I suggested in 2a, would it be wacky for other scenarios in which that message is used?

It looks like this message is only used in 2 places, and it has been copy n pasted, so there is no danger in updating it to reflect the message above. 

In case you are wondering and are wanting to change it in the other place as well, the "Your program administrator must initialize this program before you will be able to view or edit it" message shows up also if the program reporting period start and end dates have not been set AND the user does not have a high access level.

**Comment by KennyMonster** [comment]
Msg for the no indicators for low/med user has been updated to "No indicators have been entered for this program."

**Comment by jennyhavah** [comment]
> In case you are wondering and are wanting to change it in the other place as well, the "Your program administrator must initialize this program before you will be able to view or edit it" message shows up also if the program reporting period start and end dates have not been set AND the user does not have a high access level.

@KennyMonster If we can rewrite that message in 2 seconds and have it _only_ appear in that exact circumstance, I'd prefer to say: Before you can view this program, an administrator needs to set the program's start and end dates.

An Admin with High permission should still see the message about identifying program start and end dates, with a link to the modal.

**Comment by jennyhavah** [comment]
> Msg for the no indicators for low/med user has been updated to "No indicators have been entered for this program."

Validated.
