### ISSUE TITLE
IPTT: Pin/Excel buttons need styling

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1630]
The Pin and Excel buttons look a little wonky.

- [x] 1. _Almost_ joined together but not quite.

- [x] 2. The Excel buttons use secondary style -- I'd expect primary. (See #346 for background and mockup.)

     **Pin button -- primary button**

     ![image](https://user-images.githubusercontent.com/33670923/58921223-7da5d500-86ea-11e9-95ae-2fd97987dbdb.png)

     **Excel button -- secondary buttons, even though they're not secondary to Pin**

     ![image](https://user-images.githubusercontent.com/33670923/58921135-459e9200-86ea-11e9-93fb-1b55b85836b0.png)

- [ ] 3. Popovers are not docked to buttons, the way they are for the Pin button on Production. On Prod, if you readjust the window, the popover moves along with the button. But on QA, I get this:

     ![image](https://user-images.githubusercontent.com/33670923/58921390-4b48a780-86eb-11e9-99aa-66787abcb242.png)

**Comment by axoplasm** [comment]
This is a little mixed up with the IPTT work which is apparently not yet merged(?) but that's not Jennÿ’s  problem.

**Comment by axoplasm** [comment]
For the excel buttons, there is an established UI widget for this kind of thing, the [dropdown button](https://getbootstrap.com/docs/4.3/components/dropdowns/#single-button)

**Comment by axoplasm** [comment]
Criterion 3 (popover placement) is a bigger issue. I notice this is no longer using the Bootstrap Popover  component (as it was on production.) It looks like the React widget has some layout issues. It also doesn't get our uniform styling.

**Comment by axoplasm** [comment]
@camgnostic what would it take to backport this into the BS popover?

**Comment by jennyhavah** [comment]
Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/33670923/59119315-5a0ba600-8907-11e9-8d2d-7d47df359e61.png)

@axoplasm Is this what you want to see -- in particular, the secondary gray color? It's okay by me, just want to check before marking this done.

**Comment by axoplasm** [comment]
Yes they should (still) be secondary buttons, but secondary buttons are now solid gray instead of outlined

**Comment by jennyhavah** [comment]
Cool. Passed.
