### ISSUE TITLE
Program or country menu: Program with no indicators appearing (edge case)

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1638]
On QA, the program "[DRC_32953] FSP - USAID South Kivu Food Security Project (FSP)" appears in the "Program or country" search box in the top nav, even though there are zero indicators linked to it. 

![image](https://user-images.githubusercontent.com/33670923/59061462-7270b780-8858-11e9-9227-f05307fe72cf.png)

Our rule is that programs with zero indicators should not appear here, so that you don't end up on a sad and empty program page like this: https://tola-activity-qa.mercycorps.org/program/504/#/

I've only noticed this with one program so far. All other programs with no indicators that I tried typing in, do NOT show up. But because it's on QA and not Prod, I want to make sure it isn't a Satsuma related regression with wider reaching implications.

**Comment by camgnostic** [comment]
Found - this is a papaya bug!  It's because you created and then deleted an indicator, but safedelete meant it still showed up as having one indicator.  That safedelete is still sticking with us...

**Comment by jennyhavah** [comment]
PASSED! I no longer see the DRC program with safedeleted indicator in the "program or country" menu.  🎉
