### ISSUE TITLE
Use of validity classes causes red X or green check to appear in text box

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1650]
As of the Bootstrap 4.3 upgrade, using the "is-invalid" class adds a red "X" to the end of the text box.  Also, using "is-valid" class causes green checkmark to appear in the same position.  Both need to be banished.

**Comment by jennyhavah** [comment]
@sanjuroj How can I test this? Can't quite tell what this is about, from the description.

**Comment by sanjuroj** [comment]
When we upgraded to Bootstrap 4.3, it came with the unwelcome addition of default X and check mark images on invalid/valid form fields (if you click on the "Submit form" in [this section](https://getbootstrap.com/docs/4.3/components/forms/#custom-styles) of the Bootstrap docs you can see what that looks like).  Paul figured out how to turn those off, so they should no longer be appearing.  In the RF builder, if you enter a level name and then delete it, the validation highlighting gets triggered.  You should see the red border and the error message, but not the red "X" in the right side of the text box that shows up in the bootstrap docs.

**Comment by jennyhavah** [comment]
Thanks, @sanjuroj 

PASSED. Here's what I'm seeing in the case you described:

![image](https://user-images.githubusercontent.com/33670923/59391418-0e9f3080-8d29-11e9-95f6-e7ce4caf4f43.png)
