### ISSUE TITLE
disabled "0 indicators" buttons are no longer aligned properly 

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1651]
Note the different alignment of the buttons on the two cards in the image below

![Screen Shot 2019-06-10 at 5 13 02 PM](https://user-images.githubusercontent.com/6685499/59234764-1634cd00-8ba3-11e9-9c53-ae693ca847d2.png)

**Comment by jennyhavah** [comment]
Looks good! Right aligned in all 5 RF levels I tested.

![image](https://user-images.githubusercontent.com/33670923/59780434-d8086f00-926e-11e9-8e16-b9106f65fd69.png)
