### ISSUE TITLE
RF builder indicator list - long indicator names distort order dropdowns

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1659]
Long indicator names make the order dropdowns smaller than the ones with short indicator names.

<img width="692" alt="Screen Shot 2019-06-11 at 4 41 11 PM" src="https://user-images.githubusercontent.com/6685499/59313969-03d09700-8c68-11e9-9a30-231e07077ad5.png">

**Comment by jennyhavah** [comment]
I see that we're now truncating the indicator names.

![image](https://user-images.githubusercontent.com/33670923/59537491-98770700-8eab-11e9-999f-33f56b0a87d6.png)

I like that the indicators will all be the same thickness and easier to reorder. But oftentimes indicators will begin with similar phrasing and you need to see the whole thing to be able to differentiate them.

Here's an idea. @sanjuroj could you insert the indicator number and a colon before the indicator text, like so?

1a: Christie test: #1606 
1b: Result Tester

**Comment by sanjuroj** [comment]
@jennyhavah This is easy to do, but note that with the levels further down the hierarchy this can get long, and it's already possible to see the whole ontology in the title card, so I'm not sure how much the ontology adds.  There are a couple of other possibilities.  One is we just plan for an extra line of text and make sure the formatting doesn't get wonky when it does that.  Another is that we change the hover text to trigger faster and be larger so it's easier to just read that.  But I can certainly add the ontology if that's the way we go.

**Comment by jennyhavah** [comment]
@sanjuroj I'm inclined to agree that adding the numbers doesn't add much... Since the numbering reflects the order of indicators more than anything... which you can see visually and with the reordering drop-downs.

I see that each indicator row is actually allowed to wrap to two rows, which is good:

![image](https://user-images.githubusercontent.com/33670923/59734835-d8215400-9207-11e9-9803-4745fbba1ae2.png)

> Another is that we change the hover text to trigger faster and be larger so it's easier to just read that. But I can certainly add the ontology if that's the way we go.

I actually thought the hover text was missing because it was pretty slow to load. If there's a way to make it load more quickly, that'd be great.

**Comment by sanjuroj** [comment]
@jennyhavah Hmmm, actually, if you make the viewport small, the text will go to many rows.  The text is truncated with a character limit, not a row limit.  However, Paul must have fixed the funny formatting that used to be there, so I think it's ok?

The current hover text is done with native HTML.  I think I'll need to use a JS library to make it behave differently (it's not possible to adjust the timing on the native HTML one).  But that's no big deal, I think JQuery UI has one, and we already load that whole library.

**Comment by sanjuroj** [comment]
@jennyhavah Turns out the hover text is going to be a bit more complicated than I thought.  I tried the regular bootstrap JS library and it doesn't react to changes in the indicator name.  There's a React-bootstrap library that will, but it will require a reconfig of the the indicator table, with potential impacts on the reordering, formatting etc... It's doable, but I wonder if it can be deprioritized for now.

**Comment by jennyhavah** [comment]
@sanjuroj Faster hover text definitely can wait. 

I no longer see the original issue described in the ticket, so I consider it Passed.

**Comment by sanjuroj** [comment]
I figured out a way to make the bootstrap tooltip work.  But there's an accessibility caveat, which is only tangentially related to bootstrap.  First, this is from the Bootstrap docs:

> Making tooltips work for keyboard and assistive technology users

> You should only add tooltips to HTML elements that are traditionally keyboard-focusable and interactive (such as links or form controls). Although arbitrary HTML elements (such as <span>s) can be made focusable by adding the tabindex="0" attribute, this will add potentially annoying and confusing tab stops on non-interactive elements for keyboard users. In addition, most assistive technologies currently do not announce the tooltip in this situation.

We are doing exactly that, putting a tooltip on a `<span>` element that isn't really supposed to be interacted with.  If we add the `tabindex=0` property, the name is clickable and the tooltip will only disappear if you click on it again.  Clicking on the name also adds a border, though I suspect the visual could be eliminated with a bit of css. 

<img width="705" alt="Screen Shot 2019-06-19 at 4 12 13 PM" src="https://user-images.githubusercontent.com/6685499/59807897-baf39080-92ae-11e9-96cc-99603cdc27db.png">

This is what it looks like when I eliminate the `tabindex=0`, which removes the ability to select/focus.
<img width="694" alt="Screen Shot 2019-06-19 at 4 13 24 PM" src="https://user-images.githubusercontent.com/6685499/59807921-d3fc4180-92ae-11e9-9624-9c74a2d4b929.png">

So at the moment, I've left it looking like that second image, which is not as accessible but a bit cleaner. I feel like I'm running down a rabbit hole here, so I'm going to stop.  Maybe **now** it can be deprioritized.

**Comment by jennyhavah** [comment]
@sanjuroj I find the current state to be distracting / annoying. The tooltip pops up if I just move my mouse across it -- even when I can see the full text perfectly well.

I'm having a bit of trouble following what is and isn't best practice.

If it IS good Bootstrap/accessibility practice to make it so that if you click on the indicator, it looks like your first mockup, and then you click again to dismiss -- that would be my preference.

Second choice would be to go back to the way it was before.

**Comment by jennyhavah** [comment]
@sanjuroj As per our conversation, going to see how it feels with the delay of .9s. So far so good, so I'm going to mark this Passed.

Also, for handy reference from your Slack message: https://ux.stackexchange.com/questions/358/how-long-should-the-delay-be-before-a-tooltip-pops-up/119975#119975
