### ISSUE TITLE
Error message treatments: Use consistent styling across the app

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#166]
The goal is to address error scenarios where the message is unreadable or isn't obviously an error.

## Indicator Setup
- [x] **Targets tab:** Choose Event frequency and then either clear the field and tab out, or type a number greater than 10 in the _Number of events_ field. The box enlarges and slides under the "Create targets" button.
![image](https://user-images.githubusercontent.com/33670923/40259788-7f38b150-5aac-11e8-930a-c3ca858ca24c.png)

## Results form (aka Collected data record): 
- [x] No messaging under "Date collected" if you leave it empty. It should say, "Please complete this field." Here's how it looks on production:
![image](https://user-images.githubusercontent.com/33670923/41563845-c31e8086-7305-11e8-8c2e-e3160b729c19.png)
- [x] (Event and Midline/Endline only) Measure against target error message has a typo: "Please" is spelled "Pleae".
![image](https://user-images.githubusercontent.com/33670923/41563833-b7677f22-7305-11e8-8d1c-825441e36608.png)
- [x] No red outline around asterisked required form fields that are left empty. (This one I can live without if it's at all risky.) These include:
- [x] 1. Date collected
- [x] 2. Measure against target (Midline/Endline and Event indicators only)
- [x] 3. Actual value

**Comment by jennyhavah** [comment]
![image](https://user-images.githubusercontent.com/33670923/38281820-8503ae00-3761-11e8-84b3-49f134c8930c.png)

1. The "Not applicable" text size is changing from normal to small when it is highlighted in red. It should stay the same size. 
2. There should be more space between the error message, "Please complete this field. Your baseline can be zero." and the drop-down menu below.

Here is how it looks on production, for comparison:

![image](https://user-images.githubusercontent.com/33670923/38281878-c867caa0-3761-11e8-99c6-ecb11ef228de.png)

**Comment by mahmoodkhan** [comment]
Put a gray-shaded box around baseline and baseline_na checkbox to show these two fields are grouped

**Comment by jennyhavah** [comment]
The text is no longer changing size. I moved this to the UI column to remind myself to work with @sanjuroj on font sizes -- exactly what % of the default size to use when we want a smaller font.

**Comment by axoplasm** [comment]
I've addressed the simplified checklist above. Front-end error handling has some broader issues we need to refactor. For that I have a ticket (#409) in the "perpetual" project

**Comment by jennyhavah** [comment]
All fixes validated.
