### ISSUE TITLE
IPTT: Restrict RF level rows to those that have linked indicators

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1661]
# Issue
Including RF level rows that have no linked indicators, adds a lot of visual noise to the IPTT.

# Acceptance criteria

IPTT only shows gray RF level rows for those RF levels that have at least one linked indicator.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by camgnostic** [comment]
Tested on both web view (time and tva) and excel (time, tva, and tva full report) - only levels which have indicators attached are shown.  One question: if I sort by Outcome chain, and I don't have any indicators attached to one outcome, but I do have indicators attached to levels below that outcome, is it confusing not to show it?  For example, I have Outcome 2, with no indicators, but Output 2.1 and 2.2 have indicators.  So when I sort by Outcome chain, is this right?  
![Screen Shot 2019-06-14 at 8 27 13 PM](https://user-images.githubusercontent.com/7941355/59546475-f115c680-8ee2-11e9-98cd-41a020f3d57e.png)

**Comment by jennyhavah** [comment]
@camgnostic I had similar thoughts, but then was like... won't it be _even more_ confusing if we sometimes show RF level rows without indicators and sometimes not? My inclination is to leave as is, open to the possibility that when we demo to PaQ, they'll have a different take. (The Slack conclusion was to _not_ show them, but it may be a different story once they start directly interacting with it.)

**This reminds me of one important exception, though:** We ought to always display the Goal row -- or whatever the top tier is. I'm told it's common and acceptable not to have Goal level indicators because they can be so high level as to be more descriptive than measurable. "Goal: Achieve world peace" "Indicator: ???" 

So if we don't force-display the Goal, then it will never be included in IPTT exports.

The same is not true of the 2nd tiers on down, though. If it's part of your results framework, you darn well better have indicators to measure those results.

**Comment by jennyhavah** [comment]
PASSED. I now see the top level, regardless of whether or not it has an indicator linked to it.
