### ISSUE TITLE
IPTT and Program Page react to indicator deletion - update level order

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1669]
On the Program Page, in an RF-active program, if I delete an indicator, the other indicators in that level are temporarily displaying an incorrect level (i.e. if I delete 1.2.1a, then I still see 1.2.1b and 1.2.1c).  Refreshing the program page updates their level to 1.2.1a and 1.2.1b as expected.  Make program page reactive so a delete updates those indicators' numbers.
Same issue on IPTT.  (Same steps to reproduce - delete indicator, levels don't update, refresh page, levels update)

**Comment by KennyMonster** [comment]
The Program page portion of this ticket should now be fixed.

**Comment by camgnostic** [comment]
The IPTT Portion of this is being moved to a follow on ticket (#1788) moving to acceptance testing for only the Program Page portion

**Comment by jennyhavah** [comment]
Testing deletion of Goal b indicator.  Before deletion:

![image](https://user-images.githubusercontent.com/33670923/61087244-f6830580-a3e9-11e9-9e29-e4baeb3081b6.png)

After deletion:

![image](https://user-images.githubusercontent.com/33670923/61087266-04388b00-a3ea-11e9-8d9f-0b7ec003eb0b.png)

Looks good!
