### ISSUE TITLE
Program page: % Met rounded to one place, extra zeroes

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1671]
From the Wiki:

> LoP targets, periodic targets, result values (including disaggregated values), and % Met are rounded to two decimal places, but without extra zeroes -- i.e. 22.00 gets rounded to 22 and 22.10 to 22

Right now on the program page, % Met displays extra zeroes and is only rounded to one place.

**Comment by camgnostic** [comment]
Addressed in PR #1735

**Comment by jennyhavah** [comment]
Looking good. Some examples from the VISTA program.

![image](https://user-images.githubusercontent.com/33670923/60133534-68085600-9752-11e9-8a41-6789bd01e4ee.png)
