### ISSUE TITLE
RF builder: Order drop down menus are non-responsive

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1674]
**Affects:** RF builder drop down ordering thingies

![image](https://user-images.githubusercontent.com/33670923/59546616-a34e8d80-8ee5-11e9-8255-560b6295621a.png)

# Issue

Nothing happens when I select numbers in the drop down menus.

**Comment by KennyMonster** [comment]
@jennyhavah When testing, selecting a number seems to cause the indicator to re-order. The only time it doesn't change is when selecting the number of the level it's currently on (e.g. selecting 1 on the first indicator causes nothing to happen).

**Comment by sanjuroj** [comment]
Ack sorry, forgot I fixed this a bit ago.  They were broken.  They shouldn't be broken any more.

**Comment by jennyhavah** [comment]
Working!
