### ISSUE TITLE
Group by Chain not working when I switch from one program to another

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1678]
This issue affects both types of IPTT.

I'll run a report on a program using the RF, and it'll be grouped by Chain as expected. But when I switch to a different program (also using the RF), it will sort by Level, while the Group Indicators menu still says "[RF tier] Chain".

**Comment by camgnostic** [comment]
Can't reproduce - can you give me a specific program switch it was happening in?

**Comment by jennyhavah** [comment]
Just tried to reproduce and am no longer seeing it. Will let you know if it happens again!
