### ISSUE TITLE
RF builder: Reassigning indicator to different result level -- unexpected confirmation prompt

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1689]
# Issue

1. Open up an RF level that has indicators linked to it.
2. Change the result level and click "Save and close".
3. Now attempt to visit the result level to which you just assigned the indicator.

Expected behavior: Since I haven't made any changes to the original result level, it should close and the new one should open.

Observed behavior: I get this warning and am not sure what it means...

![image](https://user-images.githubusercontent.com/33670923/59728519-43126100-91ef-11e9-9764-bf1e60479f50.png)

I try clicking "OK" and THEN it does what I originally expected it to do... But what exactly was I confirming just now?

**Comment by sanjuroj** [comment]
@jennyhavah Somewhere along the way, this may have been fixed.  I tried to reproduce but couldn't. Can you take another look?

**Comment by jennyhavah** [comment]
I can no longer reproduce it either! Woo!
