### ISSUE TITLE
RF builder: Reassigning indicators -- number order is incorrect

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1690]
# To reproduce

1. Open up a result level with indicators.
2. Reassign one of the indicators to a different result level.
3. Go to the new level and check out the numbering of the indicators.

On two different occasions, the numbering wasn't what I expected. I wonder if it's remembering what it used to be instead of updating to reflect the new result? 

![image](https://user-images.githubusercontent.com/33670923/59728674-ea8f9380-91ef-11e9-9e07-3cde32afd739.png)

![image](https://user-images.githubusercontent.com/33670923/59728683-f2e7ce80-91ef-11e9-9f19-0711a7584796.png)

**Comment by jennyhavah** [comment]
@sanjuroj So, the order number in the drop-downs looks good. But I see a discrepancy between that order and what's in the "# indicators" list.

![image](https://user-images.githubusercontent.com/33670923/59937546-919a4800-9407-11e9-9e25-db099e63b8eb.png)

versus

![image](https://user-images.githubusercontent.com/33670923/59937553-99f28300-9407-11e9-90c2-88040c4a378a.png)

**Comment by sanjuroj** [comment]
@jennyhavah Good catch, I didn't think of this.

**Comment by jennyhavah** [comment]
Fixed!
