### ISSUE TITLE
Saving changes to an RF level: No growl of success

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1691]
This is something I think I just forgot to specify. Right now, you don't get any system feedback when you save changes to an RF level, other than the form closing. We need a growl of success.

# Acceptance criteria

Preconditions:
1. I've clicked "Edit" on a saved RF level.
2. I've made changes to the RF level text, Assumption, or re-ordered the indicators. (Does NOT apply to anything related to editing indicator settings.)
3. I've clicked "Save and close"

- [x] 1. When the RF level closes, I get a growl of success similar to what we're showing when you save changes to indicators. Here's how that looks:

     ![image](https://user-images.githubusercontent.com/33670923/59729051-7bb33a00-91f1-11e9-8cd3-ae193df98cfe.png)

- [x] 2. The text is: 
Success
[RF level][RF number] updated.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah For #3 above, should the "Save and link...", "Save and add another", and "Save and add Indicator" buttons be treated the same way as the "Save an close" button?

**Comment by jennyhavah** [comment]
@sanjuroj Yes, good catch! Looks like you already made this happen.

I see the expected growls of success with all three types of save -- save and close, save and add another, and save and link.
