### ISSUE TITLE
canceling the cancel confirm doesn't reenable the expanded level card buttons

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1694]
The level card buttons are disabled when a cancel confirmation is created.  They should be reenabled when you decide not to cancel after all but they are not.  [Ignore color of the pnotify, I was experimenting when I found it, so it will look different once I finish experimenting]

![Screen Shot 2019-06-18 at 9 22 03 PM](https://user-images.githubusercontent.com/6685499/59736591-3271e300-920f-11e9-9204-acb92e6d96bf.png)

![Screen Shot 2019-06-18 at 9 22 20 PM](https://user-images.githubusercontent.com/6685499/59736585-300f8900-920f-11e9-913f-5d28991cfc28.png)

**Comment by sanjuroj** [comment]
@jennyhavah Disabling these buttons while the confirmation notice is active wasn't in your original spec but it seemed like a good idea (you may notice that I also disabled the edit buttons on all of the collapsed cards). It's to prevent any other action being taken on the card before the confirm is resolved.  I've removed the disabling for now because I realized I need to do it in a different way, however, if you'd prefer to have the buttons remain active, I can leave them active.

**Comment by jennyhavah** [comment]
Great catch. I agree that all actions should be disabled in the card while you're addressing the confirmation prompt.

**Comment by jennyhavah** [comment]
@sanjuroj As per our conversation just now: We also need to delete all saved level buttons (Delete, Edit) and indicator links while you're interacting with an "Are you sure you want to delete this result level" prompt.

I just got into a weird state where I rapidly deleted a bunch of result levels, and a single prompt is stuck on the screen:

![image](https://user-images.githubusercontent.com/33670923/59865584-3a7c7080-933e-11e9-82f5-9dad6f440b64.png)

**Comment by sanjuroj** [comment]
@jennyhavah Unfortunately, I read your note after coding this up.  I didn't delete the links and buttons while the confirm was showing, I just disabled them.  Let's see how this seems to you, if you want them removed, it's not much more work to do so.

**Comment by jennyhavah** [comment]
@sanjuroj I _totally_ meant to say "disabled", not "deleted".

Just checked on QA and don't see the change. Are you sure it's merged?

**Comment by sanjuroj** [comment]
Initiating delete or cancel (i.e. edit one card and try to edit another without saving) should disable all buttons now.

**Comment by jennyhavah** [comment]
@sanjuroj Found _one_ leetle edge. I can start editing and indicator and then click Delete on another. Clicking Cancel doesn't let me back out. I'm stuck.

While we do want to keep all the Edit buttons active so you can jump from one to another, what do you think about disabling Delete buttons if you've got a level open?

**Comment by jennyhavah** [comment]
@sanjuroj When I attempted to delete an RF level, the Cancel button didn't work.

The "X" button does, though.

**Comment by jennyhavah** [comment]
PASSED. The cancel button now works when I click "Delete".

While I am interacting with a Pnotify confirmation dialogue, all Edit and Delete buttons are disabled.

**Comment by jennyhavah** [comment]
@sanjuroj  Not sure if it's always been this way or if I'm just now noticing, but...

If I edit an RF level and click Edit on a different RF level, I can still type all I want in the first form's two text boxes.

Should we disable those as well, until you make a decision whether to proceed or cancel?

**Comment by sanjuroj** [comment]
I don't remember having disabled those, but yeah, I think we probably should.  It's a pretty easy change, but I wouldn't say it's low risk for the demo.  Shall I do it after the demo?

**Comment by jennyhavah** [comment]
It can definitely wait until after the demo. Thanks!

**Comment by sanjuroj** [comment]
This is what it looks like when I disable the assumptions and name fields when the cancel prompt is up.  The weird thing is that the indicator box looks enabled (even if the drag handles and ordering dropdowns are disabled.  Should that whole section get the disabled treatment?  And I'm assuming the program objectives dropdown should be disabled as well?

**Comment by jennyhavah** [comment]
@sanjuroj Yes -- anything we don't want users interacting with, we should disable.

**Comment by jennyhavah** [comment]
Looks great. Everything is inactive while I'm interacting with the warning dialogue. Here's what it looks like:

![image](https://user-images.githubusercontent.com/33670923/60206948-a90f7180-9809-11e9-8ba1-774e8e1195dd.png)
