### ISSUE TITLE
LoP-only indicators: Field should not be editable for Low/Medium users

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1697]
# Issue

If I am logged in as a Low or Medium access user, I am able to type in the new version of the Life of Program target field.

![image](https://user-images.githubusercontent.com/33670923/59789419-b5805100-9282-11e9-935f-efcac8eed33e.png)

That field should be grayed out, just like all other types of target fields when you're Low/Medium.

**Comment by KennyMonster** [comment]
This should be fixed:

![lop_only_fixed](https://user-images.githubusercontent.com/1278224/59800547-bf627e00-929b-11e9-9cd2-b08edaba67b8.png)

I also noticed the event fields were not completely disabled, and the delete buttons were clickable. Clicking one resulted in the visible error msg (yay backend validation). I also fixed these.

Before:

![events before](https://user-images.githubusercontent.com/1278224/59800586-ddc87980-929b-11e9-9334-bafb82b539a7.png)

After:

![Screen Shot 2019-06-19 at 2 06 33 PM](https://user-images.githubusercontent.com/1278224/59800598-e456f100-929b-11e9-9852-30781a2d81ea.png)

**Comment by jennyhavah** [comment]
@KennyMonster Good catch re. events! I noticed one other thing that shouldn't even be visible to Low or Medium users: The "Add an event" button.

**Comment by KennyMonster** [comment]
Fixed!

**Comment by jennyhavah** [comment]
PASSED. Tested with both Low and Medium permissions:

**Event indicators:** Add event button is gone. Event names and targets are not editable. 
**LoP only indicators:** Can't edit the target.
