### ISSUE TITLE
Programs grouping by RF but no RF levels set yet: Don't show Group by menus in Indicator Plan or IPTT

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1698]
# Issue

I believe this is an edge case I simply failed to account for... I'm tagging it "bug" only because it's _experienced_ as a bug.

**Preconditions**
1. This is an existing program set to "Group by RF" -- OR -- a post-Satsuma-deploy new program that can't NOT group by RF.
2. There are **_zero ~levels~ tiers or only one RF ~levels~ tier set._** (Even if there is one, the system doesn't know what to call the "Chain" option, since it's based on Tier 2, and besides, you need two of a thing before you can reorder them.)

For illustration purposes, here's a program with just a Goal. Since there are no Outcomes yet, the menu doesn't say "by Outcome chain"... And even if it did, it wouldn't be helpful if there's only one RF level.

![image](https://user-images.githubusercontent.com/33670923/59805918-84fede00-92a7-11e9-9421-b9e402be3c4a.png)

# Acceptance criteria

- [x] 1. I do not see "Group indicators by" options on the Program page.
- [x] 2. Ditto both types of IPTT.
- [x] 3. Ditto Indicator plan.

**Comment by camgnostic** [comment]
> There are zero or only one RF levels set.

Levels or Tiers?  If I have set up my framework (so the system knows to call it "Outcome chains") but haven't added any actual outcome levels, do we see the options?

**Comment by jennyhavah** [comment]
@camgnostic I meant tiers -- updated. It's true that if you've picked a template and have saved at least one tier, the system should know what the second tier is called. However, without levels saved on at least two tiers, there's nothing to sort... So if you flip between the two options, the system will appear unresponsive... even if technically something is happening on the back end.

**Comment by camgnostic** [comment]
PR #1733 addresses these three changes (IP, IPTT, PP)

**Comment by jennyhavah** [comment]
All acceptance criteria met. Tested with the program "Support to High-Value Perennial Horticulture Value Chains (Grapes, Pistachio, and Saffron) in Kandahar Province (UNODC Phase-2 AWAL-in-South)". When there were zero or one tiers, I did not see the "group by" menus in the IPTTs, program page, or indicator plan.
