### ISSUE TITLE
RF level form: Text box styling issue

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1705]
# Issue

Is there anything low-effort we can do to improve the styling when you copy and paste large blocks of text into the result level or assumptions text box -- which will be super common as people transfer their logframes from Google Sheets/Excel into Tola.

Best: Somehow, when you paste, it vertically aligns to the top rather than the bottom.
Better: It realigns to the top as soon as you tab out, rather than having to close and reopen to see it nicely aligned.

Here's what I see now:

![image](https://user-images.githubusercontent.com/33670923/59875701-4a07b380-9356-11e9-893b-899875eecb2a.png)

After saving and reopening:

![image](https://user-images.githubusercontent.com/33670923/59875710-525fee80-9356-11e9-948f-ae729705a8c1.png)

**Comment by sanjuroj** [comment]
@jennyhavah We might be able to do this.  Would it be better to have the textbox autosize so you can see the whole thing?

**Comment by jennyhavah** [comment]
@sanjuroj Sure, that sounds good too!

**Comment by sanjuroj** [comment]
Added autosizing textboxes.

**Comment by jennyhavah** [comment]
Looks great!
