### ISSUE TITLE
Saved level: More room for buttons, shorten result level text part?

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1706]
Can we make the text section of the saved level a bit narrower, to allow more breathing room for buttons? What I'm seeing now -- even on the widest row, Goal.

![image](https://user-images.githubusercontent.com/33670923/59876180-c353d600-9357-11e9-989e-5c3b95d48da1.png)

![image](https://user-images.githubusercontent.com/33670923/59876130-a15a5380-9357-11e9-9ce9-0d2680072ed4.png)

**Comment by sanjuroj** [comment]
@jennyhavah I gave enough space for the "3 indicators" to always be on one line.  But I just noticed that when a delete button is there, both the edit and the delete button scrunch up a bit.  I can give it more space if you want.  The min width is set to 100px right now, 150px would allow the top buttons to be all on one line too.

**Comment by jennyhavah** [comment]
@sanjuroj The fact that the Delete and Edit buttons sometimes wrap doesn't bother me. But the lack of right-alignment does. How easy/hard would it be for you to fix it so that the Edit buttons always right align with each other, and so do the Delete buttons, without variable widths in between them?

![image](https://user-images.githubusercontent.com/33670923/59937149-8eeb2300-9406-11e9-9135-a7b8dbc5b48a.png)

**Comment by sanjuroj** [comment]
@jennyhavah  You remember we noticed that the "x indicators" popover link was up near the Edit and Delete buttons when I was showing you some options?  I thought it had been pushed to the bottom of the card but I actually had to add some formatting to make it that way, so I wonder if it was just because we weren't using long values for the level names?  In any case, see if this works.

**Comment by jennyhavah** [comment]
Looks great, @sanjuroj !

A real program example:

![image](https://user-images.githubusercontent.com/33670923/59954169-3765ab00-9438-11e9-8e12-9730a698b256.png)

Fake worst case scenario, at the _fifth_ level:

![image](https://user-images.githubusercontent.com/33670923/59954296-d68aa280-9438-11e9-9ddc-92726d39ec62.png)

**Comment by sanjuroj** [comment]
Yeah, if there is a six level program, that's going to be rough.

**Comment by jennyhavah** [comment]
I still think it's okay! It'll encourage people to be concise, if anything. :-)
