### ISSUE TITLE
IPTT: Programs using the old levels should be sorted by level, then number

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1708]
This is on QA only, not Prod.

If a program is using the old levels, both type of IPTT should be sorted by level first, then number.

_Possibly_ but not necessarily related: When I assign indicators still using the old result levels -- i.e. they haven't yet checked the box in the Admin -- to the new result levels, the indicator changes order. It shouldn't do that -- it should stay the same order -- OldLevel and then manually entered number -- until I check the box.

**Comment by jennyhavah** [comment]
Still seeing sorting issues. I noticed something interesting in the Old Levels form, that might be a useful clue:

Check this out -- on QA, Old Level menu:

![image](https://user-images.githubusercontent.com/33670923/59896372-2caa0800-939d-11e9-8f7a-f6ee6fecdc50.png)

Here's the correct order -- from Prod:

![image](https://user-images.githubusercontent.com/33670923/59896390-3fbcd800-939d-11e9-85e2-7cad75109ef7.png)

**Comment by camgnostic** [comment]
When @jennyhavah does all the investigative work, these bugs practically fix themselves.  Exactly right - I copied ids and fields from the old database of levels, didn't realize they were put in the database in a semi-random order and we must have had logic to resort them that got cut away with the move to Satsuma.

Re-ordered levels, sorting fixed.

**Comment by jennyhavah** [comment]
Looks great! The ordering of old levels is as expected in the IPTT and indictor setup form menu.
