### ISSUE TITLE
Indicator form result level field: Not sorted correctly

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1710]
The result level field should be sorted according to the result framework -- Goal, Outcome 1, Output 1.1, Activity 1.1.1. Etc.

Instead it's sorted like this:

![image](https://user-images.githubusercontent.com/33670923/59878286-beddec00-935c-11e9-9a0b-39a817beb126.png)

**Comment by KennyMonster** [comment]
As they now appear on QA:

![Screen Shot 2019-06-20 at 4 13 48 PM](https://user-images.githubusercontent.com/1278224/59887061-abd81580-9376-11e9-85a5-d714568212fe.png)

**Comment by jennyhavah** [comment]
Validated!
