### ISSUE TITLE
Logframe export view: Make it gorge like the Indicator plan (stretch goal)

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1740]
# Issue

In our Logframe export, if we could match the styling of the indicator plan -- fonts, row colors, etc. -- it will be _just that much more thrilling!!!_

Here's how it looks now:

![image](https://user-images.githubusercontent.com/33670923/60306660-e3563d00-98f5-11e9-9d57-3f0c8156d052.png)

Compared to the Indicator plan:

![image](https://user-images.githubusercontent.com/33670923/60306680-f832d080-98f5-11e9-9d2c-faf0a9348959.png)

**Comment by KennyMonster** [comment]
Not sure if this is strictly "done", in that the styling is not an exact match. I'm not sure how far to push tweaking things like cell borders, spacer columns, etc.

**Comment by jennyhavah** [comment]
@KennyMonster It looks great!

How fast/easy/low risk would it be to do either of the following:

1) Left align the two red header rows
2) Extend the black vertical column lines divider lines through the full length of the columns, rather than just in the header row:

![image](https://user-images.githubusercontent.com/33670923/60849280-e1666680-a19e-11e9-8ae3-0108ace1ee8d.png)

**Comment by jennyhavah** [comment]
Chatted with Ken -- the vertical lines are non-trivial, and I just noticed that we center the title row on the Indicator plan.

So, no further changes needed.
