### ISSUE TITLE
Ensure translation of LevelTiers is working as expected

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1743]
Because LevelTier text is being stored as English in the database, ensuring that the values get translated into non-English will require some extra effort.  This is true for any place that saved LevelTiers are displayed.

- [x] IPTT web and export -- make sure to include:
     - [x] "by ____ chain" in the "Group by" menu. (Right now, "Level" is translated but not the chain option.)
     - [x] Level menu: Tiers and RF levels
     - [x] Indicators menu: Tiers. (RF levels are translated.)
- [x] Program Page (Sanjuro)
- [x] Indicator modal
- [x] Logframe view and export
- [x] Results framework builder (Sanjuro)

**Comment by KennyMonster** [comment]
On the Program Page, I think "Outcome" in the Group indicators pulldown is untranslated:

![Screen Shot 2019-07-02 at 2 00 06 PM](https://user-images.githubusercontent.com/1278224/60546485-42d79280-9cd2-11e9-9c72-bb903b7ef35d.png)

**Comment by KennyMonster** [comment]
2 places needed on Indicator modal

![Screen Shot 2019-07-02 at 2 08 09 PM](https://user-images.githubusercontent.com/1278224/60546827-022c4900-9cd3-11e9-9b16-f0b9e98fc60e.png)

**Comment by sanjuroj** [comment]
I think the program page Outcome non-translation will be fixed once we copy the template translations over to the djangojs.po file.  I think it's marked for translation.

**Comment by sanjuroj** [comment]
@jennyhavah I'm wondering if you want the old style levels to be translated as well?  They would also need to be treated somewhat differently since they're database values too, just like the RF levels.

**Comment by KennyMonster** [comment]
Tier name translations look good on logframe web view, and should now be working in XLS export as well.

**Comment by jennyhavah** [comment]
@camgnostic @sanjuroj  Examples of untranslated areas, just added to the ticket under the IPTT header -- not intended to be a comprehensive list of everything in the IPTT.

![image](https://user-images.githubusercontent.com/33670923/60906609-5a5fcf80-a22c-11e9-8ea5-3af29d3cfac2.png)

![image](https://user-images.githubusercontent.com/33670923/60906643-75324400-a22c-11e9-857b-9b37fc0207e9.png)

![image](https://user-images.githubusercontent.com/33670923/60906646-7a8f8e80-a22c-11e9-8b4e-600cd48344fc.png)

**Comment by jennyhavah** [comment]
@sanjuroj I see a change to the translation in the IPTT level menu, but it's not quite there. Here's what I see:

![image](https://user-images.githubusercontent.com/33670923/61066663-d0923c80-a3ba-11e9-90b1-6dcde07a60a3.png)

It appears to be a mishmash of languages, and grammatically incorrect. For example, in French I would expect something like "chaîne de résultats" if RF tier 2 is called "Résultat", "chaîne d’objectifs" if tier 2 is "Objectif", etc.

**Comment by camgnostic** [comment]
Got the iptt ones handled.  I used a previous translation for "and sub-levels".  I also used the existing (for the program page) translation for "by result chain".

**Comment by jennyhavah** [comment]
@sanjuroj @camgnostic Almost there in the filter menu! Just need to translate tiers in the Level menu.

![image](https://user-images.githubusercontent.com/33670923/61145458-55995680-a48c-11e9-8a56-e09bfd843ac4.png)

**Comment by jennyhavah** [comment]
> @jennyhavah I'm wondering if you want the old style levels to be translated as well? They would also need to be treated somewhat differently since they're database values too, just like the RF levels.

@sanjuroj Sorry, just now seeing this. If it will not add a significant amount of delay, it would be great to translate old levels. But I don't see it as a must have / release blocker.

**Comment by jennyhavah** [comment]
What I'm seeing now:

![image](https://user-images.githubusercontent.com/33670923/61158853-0d3f6000-a4af-11e9-89d0-5b19fcd12155.png)

Based on what's in the "Group by" menu, I think it should be "CHAÎNE RÉSULTAT" instead of RÉSULTAT CHAINS"

**Comment by jennyhavah** [comment]
Looks good! This is what I see for the level menu:

![image](https://user-images.githubusercontent.com/33670923/61160937-75457480-a4b6-11e9-8e9a-e0fa90b94a4f.png)

Here's the Indicators menu:

![image](https://user-images.githubusercontent.com/33670923/61160944-7d9daf80-a4b6-11e9-8ff6-62f6fffd79d4.png)

**Comment by jennyhavah** [comment]
@sanjuroj Regarding translation of old levels, if you decide to go ahead and make that change, please create a new ticket for it. (To be clear, I do not consider it high priority.)

**Comment by sanjuroj** [comment]
I actually think we shouldn't translate the old level values.  They appear in a lot of places so it would take a relatively high level of effort, but we're phasing them out so it would be for something that is relatively short-lived.  I think we've given them a much better translated option in the RF levels.

**Comment by jennyhavah** [comment]
I agree, @sanjuroj ! Thanks for checking in, though.
