### ISSUE TITLE
Remove or expand char limit on Indicator name.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1749]
# Issue

**Affects:** New indicator / indicator setup form.

Currently, the front-end allows you to enter an Indicator name that is longer than 255 chars, but the backend does not.  Result:  MJ.

Indicator names can be long so the char limit should either be expanded or eliminated.

# Acceptance criteria

- [x] 1. I can type no more than 500 characters in the indicator field.

- [x] 2. When I attempt to type in the 501st character, I see a red warning message in our standard warning message format, under the indicator field: Please enter an indicator with fewer than 500 characters.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@sanjuroj I see no reason to limit indicators to 255 characters.

After a quick scan of logframes and indicator plans, the longest indicator I found was roughly 260 characters. To be extra generous, let's use the same limit we're using for RF levels: 500.

Ticket updated to reflect the desired behavior. If we need to peel off the messaging part, let me know. At a minimum, I'd prefer to prevent entry beyond 500 characters, rather than allowing people to enter more (like you can today) and then firing an error.

**Comment by jennyhavah** [comment]
@sanjuroj Is everything merged in? I'm able to type as many characters as I want into an existing indicator, and when I save, I get a 400 server error:

![image](https://user-images.githubusercontent.com/33670923/61068627-5617eb80-a3bf-11e9-9a30-677d8c060565.png)

**Comment by camgnostic** [comment]
I pre-emptively moved this ticket before jenkins got around to updating the server (*shakes fist at jenkins*) it's there now, sorry about that.

**Comment by jennyhavah** [comment]
Mostly looking good! Here's what I see when I type past 500 characters

![image](https://user-images.githubusercontent.com/33670923/61075657-4ef8d980-a3cf-11e9-94f6-8836970a6696.png)

However, when I submit without fixing the character length, I see this:

![image](https://user-images.githubusercontent.com/33670923/61075717-7354b600-a3cf-11e9-971c-836a6834ef91.png)

It doesn't let me save it, but the messaging isn't helpful. Preferred behavior: No red box at the top. Retain the red message and highlighting around the indicator field.

**Comment by jennyhavah** [comment]
@camgnostic Sending it back to Failed because of the jumpy button thing I just showed you.

**Comment by camgnostic** [comment]
Addressed in #1789

**Comment by jennyhavah** [comment]
Looks good!
