### ISSUE TITLE
(test) Write tests to test periodic_targets date ranges for accuracy

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#175]
Tests should test the following for accuracy:

- Create Periodic Targets (annual, semi-annual, Tri-annual, quarterly, and monthly) and ensure that the date ranges associated with each target is correct.
- Create a single Periodic Target initially and then add one target at a time and test the date ranges for accuracy.

**Comment by kurtwall** [comment]
@mahmoodkhan For the first bullet point, is this the algorithm you have in mind? The pseudo-code uses annual targets as an example, but it would be the same for all the targets.

+ Create a new indicator
+ Set frequency to annual
+ Set first period to current month
+ Set number of targets to 2
+ Set other required values
+ Save changes
+ Validation:
  + first period start date is the one we set
  + first period end date is one year later
  + each subsequent period is one year long
  + each subsequent period begins the day after the previous one ended
  + each subsequent period ends one year after its start date

**Comment by kurtwall** [comment]
@mahmoodkhan For the second bulleted test, the algorithm looks like:
+ Create a new indicator
+ Set a frequency
+ Set the first period to the current month
+ Accept the default number of periods (1)
+ Set other required values
+ Save changes
+ Verify the date range is correct
+ for n additional periods:
  + Add a period
  + Save
  + Verify the date range is correct
