### ISSUE TITLE
Add an expand all button to RF Builder

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1750]
During testing, Marie found that she would have liked to have been able to see the entire hierarchy, like you can when you first load the page.  An expand all button would be welcome.

From Jenny: Paul suggested we repurpose the Expand all / Collapse all functionality from the change log. Here's what that could look like:

![image](https://user-images.githubusercontent.com/33670923/61091897-cc850f80-a3f8-11e9-89e5-ded4cc1e6215.png)

# Acceptance criteria

- [x] 1. The Expando/Collapso ideally only appears after you have saved your first second-tier level and there's something to collapse. 

Next best would be for it to appear after you've saved your top tier level, but grayed out until you save your first second tier level and there's something to collapse.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by axoplasm** [comment]
I think I might have caught this in b90c083d1

**Comment by axoplasm** [comment]
But now that I'm in there, I notice that there's some opacity stuff I can't see. For example on the changelog, when everything is expanded, Expand all is dimmed:

![image](https://user-images.githubusercontent.com/169060/62902322-1cb30280-bd14-11e9-966c-853f20946276.png)

But in the RF Builder I'm not seeing it:

![image](https://user-images.githubusercontent.com/169060/62902340-2a688800-bd14-11e9-8347-8ee3f58665b0.png)

**Comment by sanjuroj** [comment]
Buttons are now disabled if list is already fully expanded or collapsed.

**Comment by jennyhavah** [comment]
@axoplasm It's working like butta! Just a small UI question: 

What do you think about reducing the vertical space between the expando-contracto thing and the first RF level, so that it's roughly the same distance as the RF levels are to each other? It feels a little disconnected at the moment.

![image](https://user-images.githubusercontent.com/33670923/63229488-88ceb400-c1b5-11e9-88b7-5a0a45968acb.png)
