### ISSUE TITLE
JS error when viewing Logframe page

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#1751]
Viewing any Logframe page throws some JS errors, causing the page to be blank. Example: https://tola-activity-qa.mercycorps.org/program/618/logframe/?groupby=1

**Comment by jennyhavah** [comment]
Anything specific I should do to test this aside from clicking on a bunch of Logframe links for different programs? @KennyMonster

**Comment by KennyMonster** [comment]
This particular issue was caused when a Level had 0 indicators associated with it, so it would be ideal to test a program with an empty Level.

**Comment by jennyhavah** [comment]
PASSED. I've opened up a number of logframes for programs, where not all RF levels have indicators linked to it. I even tried opening a logframe with a single tier and no indicators yet created. I have not encountered any errors.
