### ISSUE TITLE
IPTT Excel Exports should take less than 3s

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1752]
IPTT Excel exports currently all take 5-30s.  Reduce query duplication, leverage caching, and eliminate redundant results fetching to reduce export time to 3s or less.

**Comment by jennyhavah** [comment]
Reminder to self to re-test this:

![image](https://user-images.githubusercontent.com/33670923/60836625-f4ffd600-a17a-11e9-8ce7-70f3d5b4cfe9.png)

**Comment by jennyhavah** [comment]
It's much speedier now, yay!

**Comment by jennyhavah** [comment]
Also, retested export all feature, and it's fine.
