### ISSUE TITLE
TvA export not working.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1755]
From [Slack](https://mercycorps.slack.com/archives/GKZ1TUD45/p1562104667010000), "error message when I tried Exporting the TvA Report with “all the program data"

![Screen Shot 2019-07-02 at 5 57 05 PM](https://user-images.githubusercontent.com/6685499/60550345-8f27d000-9cdc-11e9-82c6-35efe86489f4.png)

**Comment by jennyhavah** [comment]
@KennyMonster What did you find here, and any testing tips?

**Comment by KennyMonster** [comment]
@jennyhavah This is a little fuzzy, but I think the issue was caused by exporting TvA reports with either French or Spanish as the active language, as one of those languages was causing an accented character in the filename.

**Comment by jennyhavah** [comment]
@KennyMonster  Just got the error when I set the language to French and then exported the VISTA TvA IPTT "all data" to Excel.

![image](https://user-images.githubusercontent.com/33670923/60924114-3bc1fe80-a255-11e9-9749-f80de115e99c.png)

**Comment by jennyhavah** [comment]
Actually, getting an error for English too. I wonder if it's just temporarily broken because of work in progress. @camgnostic is that the case?

**Comment by jennyhavah** [comment]
TvA "export all data" is working for me now, in all three languages.

It's a much faster download, too! Go, @camgnostic !
