### ISSUE TITLE
Indicator Plan: Goal indicators disappear when indicator plan is grouped by results chain.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1757]
From [Slack](https://mercycorps.slack.com/archives/GKZ1TUD45/p1562105019010600), Goal indicators disappear when indicator plan is grouped by Results chain. 

![Screen Shot 2019-07-02 at 6 02 25 PM](https://user-images.githubusercontent.com/6685499/60554488-a1aa0580-9cec-11e9-99bd-f79e4ae9849b.png)

**Comment by jennyhavah** [comment]
I am consistently seeing indicators for the top level, regardless of how I group them in the indicator plan.
