### ISSUE TITLE
RF builder: Users should be able to reorder RF Levels

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1760]
Note: We are waiting for additional input before going forward with this change. We have concerns about the complexity it would add to the UI, relative to the value added.

From Marie on [Slack](https://mercycorps.slack.com/archives/GKZ1TUD45/p1562103286008100), the current system that doesn't allow users to reorder levels, as they can with indicators, is too rigid.  

"I think this is something we should really consider in a future spillover release. The existing functionality feels a little rigid and particular. If we allow the reordering of Indicators, then I don’t see why we wouldn’t apply this same flexibility with the results."

**Comment by sanjuroj** [comment]
@jennyhavah I know this was considered, but I don't know whether you envisioned this for a future release or whether you decided it was a bad idea.  Might be a good conversation to have with Marie.

**Comment by jennyhavah** [comment]
@sanjuroj Thanks for filing this! During the early design phase, we discussed reordering. It makes intuitive sense that you'd want to be able to reorder levels, but we need to proceed with caution, balancing out convenience with UI complexity. For example, to make it accessible, we'd want to do something similar to our indicator reordering, with the numbered drop-down menus... which would add quite a bit of visual noise. And I'd push hard to only allow reordering within a tier -- i.e. reordering the three Outputs under Outcome 2 -- as opposed to being able to drag levels _across tiers_ -- turning an Output into an Outcome. With the latter, the potential for error would be high -- dragging to the wrong place with unexpected effects -- and it would be difficult to recover from. And again, not sure how we'd make such a feature accessible without adding a ton of visual noise.

I'd prefer not to tackle this for the initial Satsuma release, but to consider a reordering-of-siblings feature for a follow up release.

**Comment by jennyhavah** [comment]
@sanjuroj This issue has not been brought up in a long time, and we now have the Master Request Log to track "maybe, maybe not, we'll see" kinds of issues. Okay to close this ticket?

**Comment by sanjuroj** [comment]
Yup
