### ISSUE TITLE
Leading and trailing 0s in logframe ontology display

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1762]
From [Slack](https://mercycorps.slack.com/archives/GKZ1TUD45/p1562175972003200), There should be no leading (i.e. Goal indicators) or trailing 0's in the ontology display in the logframe.  Currently those 0's are being displayed.

![Screen Shot 2019-07-03 at 1 41 40 PM](https://user-images.githubusercontent.com/6685499/60615471-0b292300-9d84-11e9-8e68-5cdfe7259778.png)

**Comment by jennyhavah** [comment]
@sanjuroj Any testing suggestions? Was this language specific, etc?

**Comment by sanjuroj** [comment]
No, it was language agnostic.  I'm about to push fix for #1764, maybe check that the combo doesn't revert or accidentally pull in ontologies where there's no indicator, etc...

**Comment by jennyhavah** [comment]
Not seeing any leading or trailing zeroes in the logframe.
