### ISSUE TITLE
Logframe: Levels with no indicators don't appear in the logframe.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1764]
I'm opening this ticket jus so it doesn't get lost in the [Slack](https://mercycorps.slack.com/archives/GKZ1TUD45/p1562175359001500) conversation.  It's possible that this is intended behavior.

When a level doesn't have any associated indicators, it doesn't appear at all in the logframe.

**Comment by sanjuroj** [comment]
@jennyhavah Is this the intended behavior?

**Comment by jennyhavah** [comment]
@sanjuroj No, this is not the intended behavior for the logframe.* The logframe should include all RF levels, regardless of whether or not there are indicators associated with them.

*It IS the intended behavior for the IPTT.

**Comment by sanjuroj** [comment]
Ok, thanks, I'll start working in it then.

**Comment by jennyhavah** [comment]
@sanjuroj To test this, I created a brand new results framework for a program still using the old levels. I created one of each tier and linked no indicators to any of them. 

When I go to the logframe page, I would expect to see all the tiers, even though there are no indicators linked to any of them. But right now I'm not seeing any tiers: https://tola-activity-qa.mercycorps.org/program/455/logframe/?groupby=1

If I switch the program settings to "Group by results framework", I _do_ see the levels. But... I don't see any reason not to also show them if you don't have that box checked. Teams will create RFs while still using the old levels.

**Comment by sanjuroj** [comment]
Note that reasons this didn't pass review before may no longer be valid given the updated spec in #1315.

**Comment by jennyhavah** [comment]
PASSED.

As per changes to #1315, we are no longer providing access to the logframe when programs are still using the old levels. So the issue I reported earlier is no longer relevant.

For programs using the RF to group indicators, I am consistently seeing RF levels in the Logframe, even when they have no indicators linked to them.
