### ISSUE TITLE
Reformat indicator plan elements to resemble Logframe elements

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1766]
It was bugging me that Indicator Plan didn’t have an icon on the the Program page, which led me down the (shallow) rabbit hole of reformatting the Indicator Plan page to resemble the Logframe page

**Comment by jennyhavah** [comment]
@axoplasm Sweet!

Minor detail: There's no space between "Group indicators:" and the selection menu. (It looks fine in Logframe view.)

![image](https://user-images.githubusercontent.com/33670923/60835130-41e1ad80-a177-11e9-96f2-9d76749ce24c.png)
