### ISSUE TITLE
IPTT: Refinements to when we display the top tier

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1772]
We received this feedback from Marie:

![image](https://user-images.githubusercontent.com/33670923/60906756-c7736500-a22c-11e9-902f-092018f88d4d.png)

We do need to continue showing the top tier by default -- an intentional exception to ensure that it appears even when it has no indicators linked to it, which is common for the top tier.

The refinement I suggested, that Marie approved, is this: If you explicitly filter on a level-related filter, we do NOT automatically display the top tier. Two examples:

- [x] If I filter by Level, and don't select the top tier, I don't see that top tier row in the IPTT.

- [x] If I filter on specific indicators, and none of them are linked to the top tier, I don't see that top tier row in the IPTT.

**Comment by camgnostic** [comment]
Does this also include filtering by an Outcome Chain?

If I select "Outcome 1 and subchains" should I see the goal tier above?  Should I see its indicators (if it has any)?

**Comment by jennyhavah** [comment]
@camgnostic Good question. Because it is an _indicator_ filter -- not a _tier_ filter like the Level one -- I do not think we should display the Goal/top tier and its indicators when you select an Outcome/2ndtier chain.

**Comment by jennyhavah** [comment]
PASSED. The Level and Indicator filters now only show the Goal if you explicitly select either the Goal level or an indicator associated with a Goal.
