### ISSUE TITLE
Include Jest testing in travis

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1774]
We should run the Jest tests as part of the Travis build

**Comment by sanjuroj** [comment]
Moving this to testing.  The test will be when @camgnostic merges in his new Jest tests and they all pass.

**Comment by sanjuroj** [comment]
@camgnostic This is working as expected right?  I think we can move the ticket over?

**Comment by jennyhavah** [comment]
Confirmed with Cameron on Slack that it's fine to move the ticket over.
