### ISSUE TITLE
IPTT landing page: target period options are not translated

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1776]
# Issue

On the IPTT landing page, the target frequency selection menu options are not translated.

![image](https://user-images.githubusercontent.com/33670923/60924381-e76b4e80-a255-11e9-81fe-82cf359ce6f7.png)

**Comment by camgnostic** [comment]
Also in the IPTT report proper

**Comment by jennyhavah** [comment]
PASSED.

![image](https://user-images.githubusercontent.com/33670923/64270960-4e715080-cef1-11e9-9303-04ca7a04838b.png)

![image](https://user-images.githubusercontent.com/33670923/64270997-6052f380-cef1-11e9-9143-8edeeec0f75a.png)
