### ISSUE TITLE
Indicator setup form: PO and CSO fields overlap 

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1783]
# Issue

Some programs will continue to see Program Objectives as long as they are still grouping by the old levels. For programs that also have Country Strategic Objectives, the fields can overlap like so:

![image](https://user-images.githubusercontent.com/33670923/61069241-b0fe1280-a3c0-11e9-902b-17aad18d1385.png)

For examples of this, visit this Colombian program page: https://tola-activity-qa.mercycorps.org/program/581/#/

**Comment by axoplasm** [comment]
Fixed this in commit b4da9ef57. that introduces a global visual regression, where BS multiselects will now resemble regular selects on some browsers:

![image](https://user-images.githubusercontent.com/169060/61152623-ce54de80-a49d-11e9-8a81-67e583e0498d.png)

Putting a pin in this with #1270 / #1271 : tickets to globally conform our many multiselect elements

**Comment by jennyhavah** [comment]
Looks good, thanks!
