### ISSUE TITLE
Result form: View button is a bit funky

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1796]
# Issue

The button styles have been updated in Satsuma, and it's looking a little funky:

![image](https://user-images.githubusercontent.com/33670923/61090830-d9076900-a3f4-11e9-9fe2-5006aa518167.png)

For comparison, here is how it looks on Prod:

![image](https://user-images.githubusercontent.com/33670923/61090852-ed4b6600-a3f4-11e9-9ab7-1f51fd1ed2d0.png)

**Comment by axoplasm** [comment]
This is actually due to the "Browse google drive" button wrapping. This could be happening elsewhere. Have you see it anywhere else?

**Comment by jennyhavah** [comment]
So far, that's the only place I've noticed it, but will keep an eye out.

**Comment by jennyhavah** [comment]
Looks good. Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/33670923/61153550-66ec5e00-a4a0-11e9-8418-d528e28daaf5.png)
