### ISSUE TITLE
Indicator modal doesn't warn user about blank value in required field

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1797]
The indicator modal isn't alerting the user when all required fields have not been completed.  I would expect to see a message like "Please complete the required field on the Performance tab" or somesuch.  

One path to reproduce:  Go to the program program page of a program that pre-existed Satsuma and so had access to old-style levels (the QA programs are good examples because none of the old levels are set).  Click on a gear icon to update any indicator.  Change something and try to save.  It looks like nothing has happened.  If you go to the Performance tab and select an old-style level, the save button acts as expected.

**Comment by jennyhavah** [comment]
@sanjuroj I was seeing these "incomplete" warnings as expected, as recently as yesterday afternoon. Are they all failing now, or only a subset, based on program settings? Do you need me to dig into this?

**Comment by sanjuroj** [comment]
@jennyhavah It was a simple fix, I didn't bother to see when/how the change happened.  I can dig into it if you want but I think it's working now.

**Comment by jennyhavah** [comment]
@sanjuroj Using the program https://tola-activity-qa.mercycorps.org/program/581/#/:

I am able to clear out the baseline field -- remove any value and uncheck N/A -- and it saves successfully, despite it being a required field. I can then reopen and it's empty.

**Comment by sanjuroj** [comment]
That was a completely different issue which I've queued up a fix for.  There's another issue I found while testing:  If you have LOP target selected in the Indicator Modal, delete the target value, trigger the error message, enter a number and directly click the Save button, the error clears, but the form doesn't save.  You have to click the save button again to get it to save.   Fixing that now.

**Comment by jennyhavah** [comment]
PASSED. When I attempt to edit a QA program that doesn't have OldLevels set, I see this:

![image](https://user-images.githubusercontent.com/33670923/61163363-5d73ed80-a4c2-11e9-897b-a85e7b3c0f1b.png)

I am also unable to save if I clear out the baseline field.
