### ISSUE TITLE
Title of indicator modal contains the word "None"

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1798]
When an indicator has not been assigned to an RF level, the title of the Indicator modal becomes "None Indicator".

**Comment by sanjuroj** [comment]
@jennyhavah What is the correct behavior here?

**Comment by jennyhavah** [comment]
@sanjuroj It can say "Indicator setup" like on Prod.

**Comment by sanjuroj** [comment]
If there is a RF level, do you want it to say e.g. "Goal indicator setup"?  Or will it be "Goal Indicator" vs. "Indicator setup"

**Comment by jennyhavah** [comment]
@sanjuroj This is fine as is, though I would prefer not to have the colon after the word "indicator" since the indicator name is on a new line.

![image](https://user-images.githubusercontent.com/33670923/61143596-7ca15980-a487-11e9-87f5-6c703a242405.png)

**Comment by jennyhavah** [comment]
And just as a reminder, this is what we want when the indicator IS assigned to an RF level -- it's fine as is -- i.e. I do not want to reintroduce the word "setup" anywhere.

![image](https://user-images.githubusercontent.com/33670923/61143664-b7a38d00-a487-11e9-8cac-39d3b26abb5a.png)

**Comment by sanjuroj** [comment]
@jennyhavah, all of the above is good.  Just wanted to let you know of an assumption I made.  The current code checks to see if the Indicator Grouping switch has been flipped.  If it has it uses the RF level info for the title.  This of course doesn't work if the switch has been flipped but the indicator hasn't been assigned to a level.  In this case, if the indicator has an old level, which it probably does, I use that instead of the non-existent RF level.  If it has neither, I'm using "Indicator setup".  The slightly odd thing about using the old level is that they can't actually see that field on the indicator modal any more, once the IG switch has been flipped.  

If you want to just default all the way to "Indicator setup" if the IG switch has been flipped, let me know, it's an easy change.

**Comment by jennyhavah** [comment]
@sanjuroj When the IG switch is flipped, as a general rule, we shouldn't be displaying the old levels anywhere. So I would prefer to just say "Indicator setup" in that case, and not display the old level.

The only scenario where we should display old levels is when that IG switch is unchecked.

**Comment by jennyhavah** [comment]
PASSED.

When an older program using OldLevels is NOT grouping by RF, I see this:

![image](https://user-images.githubusercontent.com/33670923/61161193-a70b0b00-a4b7-11e9-8bc3-6da5536d9b82.png)

When I flip the RF switch, but have not yet assigned an indicator to an RF level, I see this:

![image](https://user-images.githubusercontent.com/33670923/61161180-978bc200-a4b7-11e9-857a-e08f7ffe6710.png)
