### ISSUE TITLE
Indicator dialogue > Targets tab: Baseline field is required

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#18]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Tuesday Dec 12, 2017 at 05:03 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/8_

----

**User stories:** 
1. When I'm setting up an indicator, I should be required to enter a baseline value so that this important context is displayed in my indicator tracking reports.
2. When I enter a baseline, the system should only accept a numeric value so that it can be used for calculations.
3. When a baseline is not applicable, I should be required to communicate this, so that people reviewing our measurement plan know that the omission was intentional. 

**Background:** The _Baseline_ field already exists in the Targets tab, but it is optional and accepts non-numeric values. 

**ACCEPTANCE CRITERIA**
1. The _Baseline_ field is required.
1.1. An asterisk identifies the field as required.
2. There is a "Not applicable" check box next to the field. (Please spell out "Not applicable", don't abbreviate.)
3. The _Baseline_ field is considered complete if:
3.1. A numeric value is entered (including zero); or
3.2. The "Not applicable" check box is checked.
4. The _Baseline_ field only accepts a numeric value. It does not accept letters or special characters such as %.
4.1. If you attempt to save with a non-numeric value, you receive a prompt near the field, "Please complete this field. Your baseline can be zero."
4.2. Any existing baseline value that does not meet the criteria is preserved.
4.3. However, if you attempt to edit a non-numeric baseline value, you are only allowed to replace it with a numeric value.
5. If you attempt to save without completing the Baseline field, you are prompted: "Please complete this field. Your baseline can be zero."
6. It is not possible to save the form with a numeric value in the _Baseline_ field -AND- the "Not applicable" box checked.
6.1. If you fill in the numeric field and then check the box, the system automatically clears the numeric field.
6.2. If you check the box and then enter a numeric value in the _Baseline_ field, the system automatically unchecks the box.

![baselinerequired](https://user-images.githubusercontent.com/33670923/34586487-07703dc6-f159-11e7-85da-993ac58b0d95.png)

**Comment by jennyhavah** [comment]
Functionality works great. I noticed that the error message is more verbose/jargony than I intended, and then I saw that I had several variations of it in the story, and you probably went with an earlier version. I updated the story so it's consistent, and this is the one I'd like to use: ""Please complete this field. Your baseline can be zero."

**Comment by jennyhavah** [comment]
![image](https://user-images.githubusercontent.com/33670923/35413143-5fa38b26-01d3-11e8-9c1b-403ba9a1bd76.png)

@mahmoodkhan We have feedback that this message is too jargony. Let's change it to: Please enter a number with no letters or symbols.
