### ISSUE TITLE
RF Builder:  Untranslated string in deletion confirmation

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1804]
Might as well put some space between the ! and the header text while there.

<img width="357" alt="Screen Shot 2019-07-12 at 11 55 50 AM" src="https://user-images.githubusercontent.com/6685499/61152026-37d3ed80-a49c-11e9-904a-801ded9390e5.png">

**Comment by jennyhavah** [comment]
Full message is now translated, and there's a bit of space between the ! icon and the text next to it.

![image](https://user-images.githubusercontent.com/33670923/61164397-92d00980-a4c9-11e9-9742-1b95db184ed4.png)
