### ISSUE TITLE
IPTT: First time I open result table, get an unexpected warning message when dismissing it

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1815]
To reproduce:

1. Visit any IPTT. Try this one: https://tola-activity-qa.mercycorps.org/indicators/iptt_report/636/targetperiods/?frequency=1&groupby=1

2. Click on the little blue table icon for any indicator.

3. Now click outside the area or the "X" in the upper right corner.

Here's what I'm seeing:

https://tola-activity-qa.mercycorps.org/indicators/iptt_report/636/targetperiods/?frequency=1&groupby=1

It takes a few tries to dismiss it. Once I do, I can open and close the tables as expected -- even the same one that caused the problem. It's just that first attempt that brings up the warning.

**Comment by jennyhavah** [comment]
No longer seeing the warning when I open and close a results table from the IPTT.

**Comment by camgnostic** [comment]
In the case of an indicator that is not fully set up, the warning message is back

**Comment by jennyhavah** [comment]
@camgnostic I still can't reproduce this error.
