### ISSUE TITLE
Migration spike: Indicators with disaggregation types selected from the "wrong" country

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1822]
As described in #1849, it is currently possible to select country-level disaggregations for an indicator, from countries other than the one/s in which the program is based. After Goat Tree, this will no longer be possible. 

We need to figure out what, if anything, to do about existing programs that already have assigned disaggs from other countries. 

First, it would be helpful to know how many programs and indicators are affected. Let's run a query to find them. Columns in the query output could include:

1. Country
2. Program
3. Quantity of indicators that have disagg types selected that are from a country other than the one to which the program is linked. 
4. ID numbers for those indicators.

**Comment by sanjuroj** [comment]
This is an easy query.

**Comment by camgnostic** [comment]
Query results:  (what do we do with these ones?)
[wrong-country-disaggregations.xlsx](https://github.com/mercycorps/TolaActivity/files/3773800/wrong-country-disaggregations.xlsx)

**Comment by jennyhavah** [comment]
Of the programs listed, only four are active. None of the four are multi-country programs and there's no discernible pattern to why a disaggregation might have been pulled from a particular country.

- **Nigeria pulling a disaggregation from Uganda:** ALMRI - Agricultural Livelihoods and Market Recovery Intervention
- **Kenya pulling disaggregations from Jordan, Ethiopia, and Liberia:**  Collaboration in Cross-Border Areas - Cluster 1 S. Omo/Turkana (Omo Delta Project)
- **Nepal pulling a disaggregation from Lebanon:** Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)
- **DRC pulling disaggregations from Somalia and the USA:** [DRC_91229] FARM - Food Security and Inclusive Access to Resources for Conflict Sensitive Market Development

@camgnostic What would be helpful to know next would be ... For these four active programs:

1. Quantity of _indicators_ that have disaggregation types selected that are from a country other than the one to which the program is linked.
1.1. ID numbers for those indicators.
2. How many of these indicators have results reported against them _that include disaggregated values._
2.1. ID numbers for that subset of results.

**Comment by camgnostic** [comment]
@jennyhavah 
25 indicators total, IDs: 4816, 1237, 1253, 1254, 1953, 6469, 1184, 1311, 1312, 1955, 1956, 2001, 2002, 2003, 2004, 5989, 6088, 6094, 6102, 6273, 6326, 6470, 6471, 6472, 1990

with results, 7 indicators with IDs: 4816, 1953, 1312, 1955, 6088, 6094, 6102

these results have IDs: 5095, 5096, 2739, 2331, 2814, 7885, 7927, 7886

So not a huge number of indicators or results being handled here - if there's a by-hand solution (changing them to match country or duplicating the disaggregationtype it's not hard to write in the bespoke fix to the migration)

**Comment by jennyhavah** [comment]
@camgnostic Would you be able to run a query that shows me, for the 25 indicators:

Country | Program | Indicator name?

(I thought I could derive this info from poking around, opening forms in separate tabs, etc... But couldn't quite figure out how to do it.)

**Comment by camgnostic** [comment]
ID | Country | Program ID | Program Name | Program Status | Indicator Name
-- | -- | -- | -- | -- | --
4816 | United States | 442 | TolaData TEST Program | Funded | Midline-endline firebreak check
1237 | Syrian Arab Republic | 340 | NE - Emergency Humanitarian Assistance to Conflict Affected Population in NE Syria | Funded | New arrival kits distributed
1253 | Syrian Arab Republic | 340 | NE - Emergency Humanitarian Assistance to Conflict Affected Population in NE Syria | Funded | 9
1254 | Syrian Arab Republic | 340 | NE - Emergency Humanitarian Assistance to Conflict Affected Population in NE Syria | Funded | Number of consumeable NFI kits (150 kits in five round) distributed
1953 | Syrian Arab Republic | 443 | SC - OB Capacity Building | Funded | Indicator 2: Percentage of individuals demonstrating increased technical skills and knowledge
6469 | Kenya | 586 | Collaboration in Cross-Border Areas - Cluster 1 S. Omo/Turkana (Omo Delta Project) | Funded | Increased wealth locally for youth & women in particular.
1184 | Nepal | 375 | Promoting Agriculture | Health and Alternative Livelihoods (PAHAL) | Funded
1311 | Syrian Arab Republic | 340 | NE - Emergency Humanitarian Assistance to Conflict Affected Population in NE Syria | Funded | Total X number of amount (USD) paid to all people employed through CfW activities
1312 | Syrian Arab Republic | 414 | SC - OFDA - Emergency Humanitarian Assistance to Conflict Affected Population in South and Central Syria | Funded | Total number and per item USD cost of NFIs distributed
1955 | Syrian Arab Republic | 443 | SC - OB Capacity Building | Funded | Indicator 1.2: # of people attending the training
1956 | Syrian Arab Republic | 443 | SC - OB Capacity Building | Funded | Indicator 2.1: # of trainings done
2001 | Syrian Arab Republic | 444 | SC - DFID - IHR 91061S021 | Funded | Indicator 1.1.a.: # of beneficiaries who are being visited by a veterinarian at least once a week
2002 | Syrian Arab Republic | 444 | SC - DFID - IHR 91061S021 | Funded | Indicator 1.1.b.: # of beneficiaries who visit the Vet Centre each month
2003 | Syrian Arab Republic | 444 | SC - DFID - IHR 91061S021 | Funded | Indicator 1.2: % of beneficiaries who have increased awareness and knowledge about sheep farming
2004 | Syrian Arab Republic | 444 | SC - DFID - IHR 91061S021 | Funded | Indicator 2.1:  # of beneficiaries who benefit from quality milk production on a monthly basis
5989 | United States | 442 | TolaData TEST Program | Funded | Number of liters of water provided
6088 | Nigeria | 560 | ALMRI - Agricultural Livelihoods and Market Recovery Intervention | Funded | Number of group-members receiving training on VSLA methodology and business skills
6094 | Nigeria | 560 | ALMRI - Agricultural Livelihoods and Market Recovery Intervention | Funded | Number of input supply networks mapped
6102 | Nigeria | 560 | ALMRI - Agricultural Livelihoods and Market Recovery Intervention | Funded | Number of direct beneficiaries
6273 | Kenya | 586 | Collaboration in Cross-Border Areas - Cluster 1 S. Omo/Turkana (Omo Delta Project) | Funded | Number of youth who accessed business incubatory services as a result of the project
6326 | United States | 442 | TolaData TEST Program | Funded | Christie test: # of times I go to the kichen for coffee and the pot is empty
6470 | Kenya | 586 | Collaboration in Cross-Border Areas - Cluster 1 S. Omo/Turkana (Omo Delta Project) | Funded | ODP Output 1.1: Number of youth employed or self-employed based on their skills as a result of the project.
6471 | Kenya | 586 | Collaboration in Cross-Border Areas - Cluster 1 S. Omo/Turkana (Omo Delta Project) | Funded | Output 1.2: Access to business incubatory services (finance
6472 | Kenya | 586 | Collaboration in Cross-Border Areas - Cluster 1 S. Omo/Turkana (Omo Delta Project) | Funded | ODP Output 1.2: Number of youth who accessed business incubator services as a result of the project
1990 | United States | 442 | TolaData TEST Program | Funded | TD 1

**Comment by camgnostic** [comment]
Updated with fresh data from production:

Program ID | Program Name | Program Country(s) | Program Status | Indicator ID | Indicator Name
-- | -- | -- | -- | -- | --
560 | ALMRI - Agricultural Livelihoods and Market Recovery Intervention | Nigeria | Funded | 6088 | Number of group-members receiving training on VSLA methodology and   business skills
560 | ALMRI - Agricultural Livelihoods and Market Recovery Intervention | Nigeria | Funded | 6094 | Number of input supply networks mapped
560 | ALMRI - Agricultural Livelihoods and Market Recovery Intervention | Nigeria | Funded | 6102 | Number of direct beneficiaries
618 | Resilient Market Systems Development: ReHope BRIDGE | Uganda | Funded | 7379 | Net attributable income change (NAIC)
623 | NU-TEC Development and Provision of Financial Products for Agribusiness   in Uganda | Uganda | Funded | 7456 | Number of households in northern Uganda with real increase in income
623 | NU-TEC Development and Provision of Financial Products for Agribusiness   in Uganda | Uganda | Funded | 7462 | Total number of people employed by supported businesses (a) with regular   full-time/part-time employment
623 | NU-TEC Development and Provision of Financial Products for Agribusiness   in Uganda | Uganda | Funded | 7475 | Number of Equity Bank staff (or partners) who have received capacity   building or training on agriculture lending
623 | NU-TEC Development and Provision of Financial Products for Agribusiness   in Uganda | Uganda | Funded | 7476 | Percentage of Equity Bank staff (or partners) with proven increased   understanding of agriculture lending
623 | NU-TEC Development and Provision of Financial Products for Agribusiness   in Uganda | Uganda | Funded | 7477 | Number of new staff hired or reallocated to deliver financial services to   businesses operating in the agricultural sector in Northern Uganda
671 | Projet d'appui √† la s√©curit√© alimentaire  la r√©conciliation et la r√©silience   (PASERREL) | Mali | Funded | 7844 | Number of hectares under improved agricultural methods

**Comment by jennyhavah** [comment]
See the Notes column I just added. There are only two indicators where (a) a disaggregation from another country was selected AND (b) there are results entered for that indicator. In both cases, they borrowed the "Sex" disaggregation from Uganda -- just two categories, Male and Female. Both results are from spring of 2018, some time ago and they actually entered disaggregated data into the borrowed categories. In all other cases, disaggs from other countries are selected but there are no results submitted for the indicator yet.

I'll check in with Marie about how to handle this. My instinct is to duplicate the Sex disaggregation for Nigeria and reassign the indicators to the duplicate, preserving all data already entered.

For the others, it's a little less straightforward. Do they really want to "borrow" those disaggregation categories from another country, without any modification? If yes, we can duplicate. If no, then we should deselect them, and the country team can create new disaggregations from scratch.

**Comment by camgnostic** [comment]
(per Slack): @jennyhavah all the indicators above are now fixed with the exception of the two from TolaData TEST program.  Disposition on those would be helpful as they may become difficult to edit once the country rule for disaggregations is better enforced in the UI.  Other than those two, this migration is complete (thanks to Marie!)

**Comment by jennyhavah** [comment]
@camgnostic Do you mean TolaData Demo? 

TolaData TEST is just for QA on Prod -- you can do whatever you like with those indicators, up to and including deleting them. In fact, I'm almost positive I fixed those indicators on Prod.

If there are also issues with indicators from TolaData **Demo**, that's another story, and we'll need to reach out to Marie for clarification.

**Comment by camgnostic** [comment]
Since the two indicators that weren't covered by the above fixes are toladata TEST (NOT demo) I'm moving this to AT

**Comment by jennyhavah** [comment]
@camgnostic What do you recommend, at this point for acceptance testing this ticket?

**Comment by camgnostic** [comment]
I think that checking a couple of indicators from the list (removed from GH tix because of PII, can resend if you need) to make sure that they have the disaggregations they should would cover this ticket, @jennyhavah.

**Comment by jennyhavah** [comment]
I checked indicators from two programs in the spreadsheet with active status, looking at the country disaggregation options provided in the indicator setup form. I did not see any options from the "wrong" country displayed, which means they couldn't be selected.
