### ISSUE TITLE
Change log entries related to RF level

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1823]
# Issue

The field label "Name" is problematic -- while it's fine to call it that in the database, we shouldn't be surfacing the term to end users. (Based on field feedback, it doesn't make sense to have indicator "names" or outcome "names"... They're just indicators and outcomes.)

![image](https://user-images.githubusercontent.com/33670923/61394433-f070a700-a877-11e9-8a30-7caffbfb1d62.png)

# Acceptance criteria
Since we already display the result level in a dedicated column, can we just hide the string "Name:" entirely in the Previous/new entry columns?

**Comment by axoplasm** [comment]
I'm unable to find RF entries in the change log (on my local machine at any rate) How do I get to that?

**Comment by axoplasm** [comment]
To answer my own question: the changelog only tracks changes to RF levels that have indicators!

**Comment by jennyhavah** [comment]
PASSED: I no longer see "Name:" in the previous/next columns when I modify the text of a result level.

![image](https://user-images.githubusercontent.com/33670923/61554025-d0c0b680-aa10-11e9-87aa-6481ec82861a.png)
