### ISSUE TITLE
Remove link to indicator setup on result table modal

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1824]
From an IPTT report, when you click on the result table, there is a link with the text "Start by selecting a target frequency".  Remove the link (but preserve the red warning text next to it).

<img width="804" alt="Screen Shot 2019-07-17 at 11 19 31 AM" src="https://user-images.githubusercontent.com/6685499/61400390-ffaa2180-a884-11e9-8ed7-1ce24f265331.png">

**Comment by jennyhavah** [comment]
PASSED. I no longer see the link to set up targets:

![image](https://user-images.githubusercontent.com/33670923/61417326-a6091d80-a8ab-11e9-8599-316b45eb26b7.png)
