### ISSUE TITLE
Sorting-test program(s) added to qa script

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1828]
While the spec on sorting is implemented as written, in order to ensure it isn't broken by follow-on changes, it would be useful to generate a "manual-numbers" QA program to test in upcoming releases.  To this end, we should detail a super-edge-case numbering/sorting situation(s) and add them to the QA script.

**Comment by camgnostic** [comment]
@jennyhavah if you can help brainstorm this one, since you have the clearest idea of the ideal for the sorting algorithm, it will make sure we're not compounding errors (my error in interpreting your specs made permanent by enshrining it in a test case).

**Comment by camgnostic** [comment]
As an example, currently a program with old levels sorts the following way:
| Sort Order  | Level | Number |
| ---------- | ------ | ------- |
| 1 | Outcome | 1 |
| 2 | Outcome | 2 |
| 3 | Outcome | 3 |
| 4 | Outcome | 1a |
| 5 | Outcome | 1b |

And... I _think_ that's wrong

**Comment by jennyhavah** [comment]
@camgnostic In the example above, I would expect Outcomes 1a and 1b to come after Outcome 1 and before Outcome 2.

BUT.... Tola has never supported (or claimed to support) any manual numbering scheme a donor might require. Now that we have introduced an elegant auto-numbering solution, I'm even _less_ inclined to invest development effort in sorting manually entered numbers. We even go out of our way to call out in the admin, that manually entered display numbers _have no effect on sort order_, and are for display purposes only.

I consider this very low priority -- not even a strong candidate for the follow up release.

**Comment by camgnostic** [comment]
Closing as unit tests made this unnecessary
