### ISSUE TITLE
IPTT exports: Baseline column width clips French

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1838]
In IPTT (any type, any program, any frequency) in French, the baseline column is too narrow for the word "baseline" in French:
<img width="332" alt="Screen Shot 2019-07-17 at 3 56 13 PM" src="https://user-images.githubusercontent.com/7941355/61417279-7eb25080-a8ab-11e9-880d-1c5bbe675b77.png">

**Comment by jennyhavah** [comment]
PASSED. 

![image](https://user-images.githubusercontent.com/33670923/64270915-326daf00-cef1-11e9-9aef-d27842d051ba.png)
