### ISSUE TITLE
(Firefox only) Logframe web view: Horizontal lines appear inconsistently

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1843]
In Firefox, horizontal gray lines don't appear consistently -- can't discern the pattern. Zooming in or out has no effect.

Here's what it looks like in Firefox:

![image](https://user-images.githubusercontent.com/33670923/61426937-18402900-a8d1-11e9-9d1f-a9d6eabe59f1.png)

Compared to Chrome:

![image](https://user-images.githubusercontent.com/33670923/61426955-23935480-a8d1-11e9-8db4-4ddc249db5a9.png)

**Comment by axoplasm** [comment]
This was happening on Levels with no indicators or changes, they were incorrectly getting rowspan=0

**Comment by jennyhavah** [comment]
Logframe lines looking good on Firefox!

![image](https://user-images.githubusercontent.com/33670923/61551705-b683da00-aa0a-11e9-88d6-147963c81df7.png)
