### ISSUE TITLE
Translation: "par niveau" in French -> "par Niveau"

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1845]
Translation: "par niveau" in French -> "par Niveau"

**Comment by jennyhavah** [comment]
@sanjuroj Is this the string in question?

![image](https://user-images.githubusercontent.com/33670923/62984853-9a950d80-bde9-11e9-9053-72aaecfcfae0.png)

**Comment by sanjuroj** [comment]
That's the one.
