### ISSUE TITLE
Top nav: Remove "Indicator disaggregation report" from Reports menu

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1846]
# Story

With disaggregation being incorporated into the IPTT as part of Goat Tree, we can :fire: navigation links to the old report. The only one I'm aware of is the one in the top nav bar Reports menu.

_Note: This ticket only covers removing navigation to the old report. If we also want to permanently rip out the code for that report, let's file a separate ticket for it, and make sure to check the analytics to see what kind of traffic it's gotten in the last year or so._

# Acceptance criteria

- [x] 1. In the top nav bar's Reports menu, there is no longer a link to the Indicator disaggregation report.

**Comment by jennyhavah** [comment]
@camgnostic I just realized we now have a menu with only one item on it. 

Can you please remove the drop-down caret thingie and make that a simple link to the IPTT landing page? Same font treatment, just a link instead of a menu.

**Comment by camgnostic** [comment]
Done, but this looks a little weird at least in French (IPTT is a loooong word in french, blows out the menu box)
![image](https://user-images.githubusercontent.com/7941355/71487533-c3ce9d00-27d0-11ea-8254-449aa96ac2ca.png)

**Comment by jennyhavah** [comment]
As discussed on Slack, it should say "Reports" -- just changing from a menu to a link.

**Comment by jennyhavah** [comment]
Looks good! Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/33670923/71492306-03a27e00-27eb-11ea-8280-4380dbc633f0.png)

When I click that link, it takes me to the IPTT landing page.
