### ISSUE TITLE
IPTT Excel export does not sort by old level for non-RF programs (satsuma release)

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1847]
Excel export of IPTT with a non-RF program sorts by number only, not number and level

**Comment by jennyhavah** [comment]
On QA, I tried exporting all data for VISTA, Target vs Actuals report. First checked for regressions when "Group by RF" was checked, and it looked good.

When I group by old levels, I noticed a difference in the sort order for Quarterly targets -- between the export and web versions.

Web version:
https://tola-activity-qa.mercycorps.org/indicators/iptt_report/550/targetperiods/?frequency=6&start=0&end=10

Export:

![image](https://user-images.githubusercontent.com/33670923/61502001-dec9f500-a986-11e9-938a-6c2c5d6731b8.png)

Also see some differences in sorting with the Recent progress IPTT, same program.

Web version: https://tola-activity-qa.mercycorps.org/indicators/iptt_report/550/timeperiods/?frequency=7&start=29&end=30

Export:
![image](https://user-images.githubusercontent.com/33670923/61502059-12a51a80-a987-11e9-8208-c21603ddb5b6.png)

**Comment by camgnostic** [comment]
This is that messy old number sorting the other ticket was about.  For the immediate fix, is the web version canonical and the export should match?  (tagging @jennyhavah)

**Comment by jennyhavah** [comment]
Ah, got it, @camgnostic. I'm not concerned by exactly _how_ the system is sorting manually entered numbers. But I would expect that the export sort order in the export mimic what you're seeing in the web version... 

_However,_ if getting the export to match the web view is more than a trivial effort, and it only affects programs entering unusual manual numbers, then I'm okay letting it go, as long as it's sorting by level first, then number.

**Comment by jennyhavah** [comment]
I exported several IPTTs for programs grouping by old levels. It sorted as expected -- levels first, then numbers.
