### ISSUE TITLE
Admin: Archiving global and country disaggregations 

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1850]
# Issue

The primary goal is to keep the list of disaggregations in indicator setup menus manageable over time -- preventing the list from becoming overloaded with highly specialized disaggregations used by a single program, or older versions of disaggregation categories that country or global leadership would prefer teams stop using. As an example, Mercy Corp's own SADD sex and age brackets are periodically revised. 

When a disaggregation is "archived", we must keep those categories intact for results already entered, while preventing new programs from utilizing them.
 
## Country disaggregations (Admin Lite)

- [x] 1. Prior to a disaggregation being selected by at least one indicator in the system, there is no archive option. There is a Delete option, as shown below. (Interactions with this button are covered in #1448.)
     
     ![image](https://user-images.githubusercontent.com/33670923/62248095-234c8c00-b39c-11e9-8d2c-fef0246a8c25.png)

- [x] 2. As soon as the disaggregation is selected by at least one indicator in the system, the Delete button is replaced by an Archive button, like so.

     ![image](https://user-images.githubusercontent.com/33670923/62248236-7cb4bb00-b39c-11e9-8ea8-ae1f0ed78d10.png)

- [x] 3. When I click "Archive disaggregation", I get a yellow PNotify warning confirmation that says:

     Warning
     New programs will be unable to use this disaggregation. (Programs already using the disaggregation will be unaffected.)
     Are you sure you want to continue?
     
     ![image](https://user-images.githubusercontent.com/33670923/61915226-6a4c0480-aef8-11e9-94f6-372f3cd79352.png)

     - [x] 3.1. While I am interacting with this dialogue, all form fields are inactive. (See #1859 -- establishing this as a global pattern.)

- [x] 4. When I click OK, the following things happen:

     ![image](https://user-images.githubusercontent.com/33670923/62248444-f8166c80-b39c-11e9-8ccb-212e391266f1.png)

     - [x] 4.1. Next to the accordion link, it says, "(Archived)" so that I don't need to open it to know that it's archived.

     - [x] 4.2. All form elements are inactive except for an "Unarchive disaggregation" button that appears where the "Archive" button used to be.

- [x] 5. I can unarchive the disaggregation by clicking... wait for it... "Unarchive disaggregation". When I do so, I get a yellow PNotify warning confirmation that says:

     Warning
     All programs in [CountryName] will be able to use this disaggregation. 
     Are you sure you want to continue?

- [x] 6. If I click OK, the following things happen:

     - [x] 1. All form elements are restored to an active state.

     - [x] 2. The "Unarchive" button changes back into an "Archive" button.

## Global disaggregations (Django)

Global disaggregations are managed in Django Admin. Super Admins will occasionally be asked to archive these, so we need to provide a mechanism to do so.

- [x] 1. There is an archive / unarchive function for global disaggregation types.

- [x] 2. I get the same warning prompts and behaviors described above when I click Archive or Unarchive -- or as close as you can get without excessive tinkering because Django.

## Effects on indicator setup form when a disaggregation is archived

When I archive a disaggregation, the following things happen:

- [x] 1. Any programs that already had at least one indicator in the system with the disaggregation selected are _unaffected._ 

     - [x] 1.1. When I open a _**saved**_ indicator, the disaggregation is still an option to be viewed (all roles) and edited (High role only).

     - [x] 1.2. When I add a **_new_** indicator to the program, the disaggregation is still an option to be viewed (all roles) and edited (High role only).

- [x] 2. For any programs that did NOT already have at least one indicator in the system with the disaggregation type, I no longer see that disaggregation as an option in the indicator setup form, for either new or saved indicators.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by sanjuroj** [comment]
None of the individual elements here are difficult but there are a bunch of them and the admin-lite is always a bit iffy, so it could take longer.

**Comment by jennyhavah** [comment]
**Validated**

1. Archive/unarchive function works as expected in the Admin.
2. Archive/unarchive function has the expected behaviors on indicator forms and results.
3. There is an archive/unarchive option in Django admin for global disaggregations that works as expected. (I tested with SADD.)
