### ISSUE TITLE
Data endpoint for Margeaux

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1854]
Margeaux needs an endpoint (can be a URL manually typed in after logging in) that produces in JSON:
- Real and actual TVA values (all indicators)
- GAIT ID
- Count of indicators
- Count of indicators with targets
- Count of indicators with results
- Count of results
- Count of results with evidence
- Count above/on/below target (scope)
- Country code

this should be organized by GAIT ID and should pull for all programs that the user has access to (associative JSON array, keys are GAIT ID)

As a reach goal an adjacent endpoint can address #969

**Comment by jennyhavah** [comment]
@camgnostic Ok to pass this ticket, or are we still testing with Margaux?

**Comment by camgnostic** [comment]
@jennyhavah - should be good.  We have moved any further development on this ticket to its own larger ticket: #1937
