### ISSUE TITLE
Regression-proof (testing/refactored) serializers (IPTT, Program Page, Logframe, Indicator Plan)

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1855]
IPTT, Program Page, Logframe, and Indicator Plan all pull very similar data but code is duplicated, meaning updates to level display / number display / ordering need to be repeated in multiple places and tested in multiple places.

To fix:
 - inherit serializers from base serializers for Program, Indicator, and Level that maximize query prefetching and have methods for producing number output, level output, etc.
 - write tests for output that test: correct formatting of tier/level names, number display, ordering, and translations
 - remove outdated/unused code from serializers/renderers

**Comment by jennyhavah** [comment]
@camgnostic What kind of testing, if any, shall we do on this one?

**Comment by camgnostic** [comment]
The above tickets are all, basically, testing this one.  The object of this rewrite was to be transparent, so if we've cleared all the bugs from the QA pass, then this one can clear as well

**Comment by jennyhavah** [comment]
Ok, gonna pass it to get it out of the queue, and we can always un-pass it if we need to.
