### ISSUE TITLE
Admin: Disaggregation "select by default" option

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1861]
# Issue

As a country level manager or M&E advisor, I am able to promote specific country disaggregations that I want all programs to use. These are disaggregations that are relevant to all programs regardless of sector -- similar to SADD at the global level.

As a program level M&E person setting up indicators in Tola, I am still able to exercise my professional judgment and unselect disaggregations on an indicator-by-indicator basis, based on the context. 

## Admin Lite > Country disaggregations form

![image](https://user-images.githubusercontent.com/33670923/62248966-35c7c500-b39e-11e9-9cd5-dc11e4c99f73.png)

- [x] 1. Under the required Disaggregation field is a checkbox with the label "Selected by default".

- [x] 2. This checkbox is UNselected by default.

- [x] 3. Next to the field label is a question mark icon. When clicked, the tool-tip tells me:
 
     When adding a program indicator, this disaggregation will be selected by default. (It can be unselected for specific indicators.)

     This option is recommended for disaggregations that are required for all programs in a country, regardless of sector.

## Effects on the indicator setup form

- [x] 1. When the box is UNchecked, the disaggregation is _unselected_ by default whenever I ADD a new indicator.

- [x] 2. When the box is CHECKED, the disaggregation is _selected_ by default whenever I ADD a new indicator.

- [x] 3. ~Any changes I make to this field only affect NEW indicators. It has no effect on SAVED indicators.~ Please see refinements to rules for SAVED indicators below:

     - [x] 3.1. When I toggle the “select by default” option from UNCHECKED to CHECKED, the automatic selection should only apply to NEW indicators, and not to saved ones.

     - [x] 3.2. When I toggle the “select by default option from CHECKED to UNCHECKED:

          - [x] 3.2.1. All NEW indicators have the option unchecked.

          - [x] 3.2.2. If a SAVED indicator has NO results using the disaggregation, the option is unchecked.

          - [x] 3.2.3. If a SAVED indicator HAS results using the disaggregation, the option remains checked and inactive. I cannot de-select it.

## Global disaggregation exception to the rules

- [x] The Global disaggregation SADD ought to be selected by default -- the Django admin equivalent of having the "select by default" box checked.

- [x] Because SADD has always been hard-wired to apply to all indicators in the past, we should make an exception -- in this one instance -- to the rule that "selected by default" only applies to new indicators. We should retroactively check that box for all indicators in the system.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by sanjuroj** [comment]
Touches both the admin form and the indicator modal, and probably involves some database changes, so medium.

**Comment by jennyhavah** [comment]
I realized I may not have called out that SADD needs to be selected by default. Added it to the original ticket.

**Comment by jennyhavah** [comment]
Sorry, I just realized I made a hash out of the requirements for saved indicators. Please see updated criteria.

**Comment by jennyhavah** [comment]
**All criteria met.** I am going to file a separate ticket for some refinements requested by Carly, involving confirmation warnings and an option to retro-apply disaggregations to already-saved indicators for specific programs.
