### ISSUE TITLE
IPTT: Display disaggregated results

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1865]
# Issue

When I want to compare the impact of an intervention across multiple categories of participants, I examine disaggregated results in the IPTT.

Note: Excel exports of disaggregated data are covered in #1867.

# Acceptance criteria

## Table layout

The mockup below shows an example of an indicator that is disaggregated two ways in parallel -- by sex/age categories and by ethnic groups. 

![image](https://user-images.githubusercontent.com/33670923/72390751-60a19d80-36e0-11ea-81ac-42279625b85d.png)

Note: At the moment, we are only displaying disaggregated _actuals_. All other columns should have our standard dashes. **_Please note that we may, someday, tackle the display of disaggregated baselines and targets._**

- [x] 1. Individual indicator rows can be expanded and collapsed to show or hide disaggregated data associated with that indicator. 

     - [x] 1.1. The expando icon is not displayed when an indicator has no disaggregations selected in indicator setup. (The disaggregation menu appears in the Performance tab. See #1213 for details.) This will be relatively rare because all indicators have SADD checked by default.

- [x] 2. All indicator rows are _**collapsed**_ by default. <P>

- [x] 3. There is an expand all/collapse all widget immediately above the table, similar to what's on the Change Log page. It allows me to expand and collapse all disaggregated data rows. (It has no effect on indicators without disaggregations.)

     - [x] 3.1. This widget only affects indicators _currently on display._ (In other words, "Expand all" doesn't clear any filters.)

- [x] 4. When an indicator row is expanded -- either individually or collectively -- all disaggregation category rows are displayed, _regardless of whether or not any results are reported for them._ Some UI details I'll call out:

     - [x] 4.1. The disaggregation column is aligned with the indicator number column, and it spans all disaggregation category rows. The text is bold.

     - [x] 4.2. The disaggregation categories are in line with the Indicator column. These cells are _right aligned_, to bring them in closer visual relationship with the data they relate to.

## New disaggregation filter

![image](https://user-images.githubusercontent.com/33670923/71697029-87b8b080-2d6b-11ea-93b3-2a8b2aa53c31.png)

This menu filters indicators based on how they are disaggregated, allowing me to quickly create a report that includes all indicators disaggregated a particular way. It also allows me to selectively hide disaggregations in an edge case where some indicators are disaggregated more than one way.
 
- [x] 1. The _Disaggregations_ filter appears after the _Levels_ filter.

- [x] 2. The default is "None selected", meaning that no indicators are being filtered out, based on their disaggregations.

- [x] 3. Disaggregations are clustered and sorted the same way they appear in the indicator setup form. See #1213 for details. 

- [x] 4. If I select one or more disaggregations, only indicators with those disaggregations selected in Indicator setup (Performance tab) show up.

     - [x] 4.1. All returned indicator rows are automatically _expanded_ as if I'd simultaneously hit the "Expand all" widget... the assumption being that if I'm using that particular filter, I'm interested in looking at disaggregated results. 

- [x] 5. This is an -OR- filter. So if I pick SADD and Geography in the Disaggregations filter, I get indicators disaggregated by SADD and/or Geography.

- [x] 6. In a case where an indicator is disaggregated multiple ways, but I have not selected all of those options, _we only show the selected disaggregations._  For example: If I have an indicator disaggregated by both SADD and Geography, and I've only selected SADD in the disaggregations filter, we should _hide the Geography rows._

- [x] 7. Disaggregation filtering is preserved when the report is pinned to the program page.

## Housekeeping (where applicable)
- [x] Unit test/s written 
- [x] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by camgnostic** [comment]
Note: the disaggregations filters are also to be saved in the pin URL (need to be query parameters)
(@jennyhavah this is testable by: pinning a report with no disaggregation filters, with 1 disaggregation selected, and with multiple selected, and ensuring in each case that the report when loaded from the pin link displays the correct behavior - filter menu with the right selections, correct filters applied, and expanded/collapsed disaggregation rows as expected)

**Comment by jennyhavah** [comment]
@camgnostic In the Disaggregations filter menu, can you please add the word "Disaggregations" after the country name? Like so:

![image](https://user-images.githubusercontent.com/33670923/72653522-27ffff00-3940-11ea-8f9d-27fb62311dee.png)

This is to be consistent with how we're labeling them in the indicator setup menu:

![image](https://user-images.githubusercontent.com/33670923/72653531-34845780-3940-11ea-9f4b-fc6f5397643f.png)

**Comment by jennyhavah** [comment]
Regarding this criteria:

> All returned indicator rows are automatically expanded as if I'd simultaneously hit the "Expand all" widget... the assumption being that if I'm using that particular filter, I'm interested in looking at disaggregated results.

This is working as expected for the most part, but I found one edge case where some rows are inconsistently opened or left closed.

1. Run an IPTT on QA - Jenny.

2. In the disaggregations filter, check the box for "A 2-category disaggregation" and then the one for "A 3-category disaggregation."

I can't quite make out the pattern, but some rows are remaining closed. Some of the closed indicator rows have both disaggregations and some only have one of the two. Here's a screenshot:

![image](https://user-images.githubusercontent.com/33670923/72654498-b9717000-3944-11ea-9e1b-5cb74d2aaee4.png)

**Comment by jennyhavah** [comment]
Fixes validated with a 🎉.
