### ISSUE TITLE
IPTT: Export disaggregated data

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1867]
# Issue

Dependent on #1865 being completed.

My disaggregated values export to Excel as expected.

# Acceptance criteria

## Recent progress IPTT

- [x] 1. All disaggregation rows appear in the Excel export, in the same order they appear in the web view.

- [x] 2. All disaggregation rows are _collapsed_ in the export, regardless of what's on the screen. 

- [x] 3. Double check the edge case of an indicator with multiple disaggregation types, where I've filtered out one of the types using the Disaggregation filter. Put another way, if it doesn't show up on the screen, it shouldn't show up in the export.

## Target vs Actuals IPTT

- [x] 1. All disaggregation rows appear in the Excel export, in the same order they appear in the web view.

     - [x] 1.1. This is true regardless of whether I'm exporting current view or the entire workbook. <P>

- [x] 2. All disaggregation rows are _collapsed_ in the export, regardless of what's on the screen. 

- [x] 3. Double check the edge case of an indicator with multiple disaggregation types, where I've filtered out one of the types using the Disaggregation filter. Put another way, if it doesn't show up on the screen, it shouldn't show up in the export.

## Both types of report

- [x] 1. When a column is checked in the "Hide columns" menu, it is also hidden in the IPTT Excel export. (I can then unhide the columns if I wish, using Excel's standard "hide/unhide columns" feature.)

- [x] 2. Disaggregation category rows hidden in the web view are also hidden in the export. (from #2167)

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
Getting an error when I try to download the Excel version of the "Current View" from here:
https://tola-activity-dev2.mercycorps.org/indicators/iptt_report/533/targetperiods/?frequency=1&disaggregations=hide-categories
