### ISSUE TITLE
Results: When disagg category text is updated, the category disappears from saved indicators

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1869]
This ticket may be connected to #1213.

# Issue

Before results are submitted to a disaggregation category, we permit the text to be edited. Those edits ought to appear in saved as well as new indicators. Right now, when I edit the text, the category disappears from saved indicators.

# To reproduce

1. Go to Admin > Countries > Tolaland > Country disaggregations and add a new category to Dumplings.

2. Add a result to any indicator in a Tolaland program. _Do NOT enter anything into the new disaggregation category value box_. (That will make the text non-editable, as it should.)

3. Go back to the Admin and change the text of your dumpling category.

4. Open up the saved result again.

**Expected:** Category text is updated to reflect edits.

**Observed:** Category is no longer displayed. Poof!

**Comment by camgnostic** [comment]
Tagging Low because it is included in the High work estimate for #1868

**Comment by jennyhavah** [comment]
Validated. When I edit a disaggregation category, the edits show up in a saved result for an indicator using the disaggregation.
