### ISSUE TITLE
Admin > Countries: Disaggregation categories appear editable after they are in use

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1871]
As a rule, a disaggregation category should not be editable after there is result data associated with it. Today, categories appear to remain editable after they are in use. 

# Steps to reproduce

1. In Admin > Countries > Tolaland > Country disaggregations, add a new category any of the existing disaggregations.

2. Submit a new result for any Tolaland program, entering data into the new disaggregation category you just created.

3. Navigate back to the admin page where you added the category.

Expected: Category text field is inactive.

Observed: It is active. You can edit the text and submit it, and see a green success message. In fact, the changes are NOT saved. It's all lies.

# Acceptance criteria

- [x] 1. When a disaggregation category is in use by at least one saved result, you cannot edit its text in Admin > Country. The text field is inactive.

**Comment by sanjuroj** [comment]
It's probably just a UI store setting somewhere that got missed.

**Comment by jennyhavah** [comment]
@camgnostic It looks like ALL categories become non-editable after any category is used in any result. My intention was that the specific **_category_** used would become non-editable and non-deletable, not that ALL categories for the entire disaggregation be non-editable and non-deletable.

**Comment by jennyhavah** [comment]
**Working as expected.** After I disaggregate a result, the categories I used are no longer editable in the Admin. I also see a lock icon with a tool-tip explaining why.

![image](https://user-images.githubusercontent.com/33670923/71531128-26dc3480-28a2-11ea-9958-314cb071eef4.png)

**Comment by jennyhavah** [comment]
Couple of UI tweaks:

1) Vertically center-align lock icon with number menus.

2) Reduce gap between lock icon and tool tip.

![image](https://user-images.githubusercontent.com/33670923/71531263-bb469700-28a2-11ea-8fc1-576d1b5eb3ee.png)

**Comment by jennyhavah** [comment]
Looks good!

Here's what I'm seeing now -- everything in alignment, no gap.

![image](https://user-images.githubusercontent.com/33670923/71692536-05c28a80-2d5f-11ea-945f-275cf871bd51.png)
