### ISSUE TITLE
Admin > Countries: Make disaggregation categories reorderable

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1872]
# Issue

Currently, disaggregation categories (labels) in Admin-lite->Country->Country Disaggregations are not re-orderable. 

<img width="593" alt="Screen Shot 2019-08-06 at 4 49 21 PM" src="https://user-images.githubusercontent.com/6685499/62584690-7d50c400-b86a-11e9-8881-cd6104dff8aa.png">

Users should have the ability to reorder the categories by either selecting the position or dragging the categories around.  This is similar to how indicators can be reordered in the RF builder.

# Acceptance criteria

## UI details

![image](https://user-images.githubusercontent.com/33670923/62640242-0234ef80-b8f6-11e9-8abb-d889c5624d4c.png)

- [x] 1. I can reorder disaggregation categories with a drag-and-drop interaction.

- [x] 2. I can reorder disaggregation categories by selecting a numeric position in a drop-down menu.

 - [x] 3. I can reorder disaggregation categories regardless of whether they are "in use" or not. (Doesn't matter if I can't edit the text or delete, I can always reorder.)

- [x] 4. Exception: I canNOT reorder disaggregation categories when the disaggregation is archived. (See #1850.)

## Where reordering shows up

When I reorder disaggregation categories and save changes, the change is reflected in the following places:

- [x] 1. Indicator setup form > Performance tab > Disaggregation options > Category flyouts

     ![image](https://user-images.githubusercontent.com/33670923/62640642-e3832880-b8f6-11e9-8c47-45199d25a6e4.png)

- [x] 2. Result form

     ![image](https://user-images.githubusercontent.com/33670923/62640687-fbf34300-b8f6-11e9-913d-ede3e06a875b.png)

- [x] 3. IPTT web view and Excel exports

     ![image](https://user-images.githubusercontent.com/33670923/62640825-4248a200-b8f7-11e9-94ba-b324a5492a4a.png)

Note: Reordering is only expected to have an effect on disaggregation related change log entries that are generated _after_ the reordering happens. We don't expect categories to be rearranged for disaggregation changes already logged in the system.

## Housekeeping
* [x]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
The draggable elements can in the RF builder can be used as a model, but the admin-lite system is more complicated than the RF builder and it's possible that this could take more than a medium effort.

**Comment by jennyhavah** [comment]
All criteria met.
