### ISSUE TITLE
View Custom Option without scroll on RF builder 

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1881]
Jenny's comment on #1331.  Minor usability request, only if it's easy: Any simple adjustments you could make to the templates menu, such that the Custom option is more likely to be visible without needing to scroll? 

Here's what I see now:

![image](https://user-images.githubusercontent.com/33670923/63229133-05f82a00-c1b2-11e9-846d-13a51bcc7961.png)

**Comment by sanjuroj** [comment]
@jennyhavah What sort of solution would you prefer?  We could make the dropdown box droppier downer, or font smaller, etc...  Or should I just hand this off to @axoplasm .

**Comment by jennyhavah** [comment]
I'm inclined to adjust the length of the menu so that more items can be seen, rather than do anything non-standard with the fonts. (I tried not to be too prescriptive, since I don't have a sense of what adjustments would be straightforward versus what would require hackery.)
