### ISSUE TITLE
Expando/collapso should be inactive while editing custom tiers and RF levels

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1892]
There are a couple of scenarios where the Expando/collapso buttons need to be inactive:

- [ ] 1. While editing custom tiers. (Getting to this state requires setting up a program with a custom template, then saving some RF levels, and then hitting the "Settings" button. Here's one already done: https://tola-activity-qa.mercycorps.org/indicators/results_framework_builder/489)

     ![image](https://user-images.githubusercontent.com/33670923/63730963-63c7ea00-c822-11e9-8765-1ded8df4ce83.png)

- [ ] 2. While editing any RF level form.

     ![image](https://user-images.githubusercontent.com/33670923/63730930-37ac6900-c822-11e9-96a5-58fbce290757.png)

**Comment by sanjuroj** [comment]
@jennyhavah #2 makes sense to me.  But I'm curious if you think there might be interest in navigating the level hierarchy while editing the custom tiers.  It seems like that could be a useful thing to be able to do.  If it's not, should we also disable the expandos on each card, not just the Expand all and Collapse all?

**Comment by jennyhavah** [comment]
@sanjuroj Glad you called that out... The more I think about it, the more I think we should inactivate ALL expando-collapso icons when you are:

1) Editing Custom Template settings; and

2) Editing an RF level.

Here's where it gets weird for me, in either case: I have all levels expanded. I click "Edit" on an RF level somewhere in the middle. I click a _collapso_ for the level I'm editing or one of the ones _above._ Weird stuff happens. 

I think we should treat editing as a true modal experience and not let you navigate the hierarchy -- neither using the expand/collapse all (which you've fixed) OR the individual expando collapso icons (still operative). Thoughts?

**Comment by sanjuroj** [comment]
Agreed, it would get really weird if you collapso'd the card you were editing.  I work on disabling the individual card expandos/collapsos.

**Comment by jennyhavah** [comment]
PASSED. I can no longer expando or collapso while editing custom tiers or rf levels.
