### ISSUE TITLE
Even more QA program script improvements

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1914]
# Acceptance criteria

- [x] 1. All post-Satsuma QA programs (i.e. all but one of them) have every indicator assigned to a result level. (We don't permit unassigned indicators in the post-Satsuma world.)
- [x] 2. Use a obscured password entry field when entering user passwords and prompt for confirmation instead.
- [x] 3. Add a few Sites, Types, and Sectors only to named QA program indicators.  The others should be left without any associated Sites, Types, or Sectors, so filters can be evaluated for appropriate disabling.
- [x] 4. Put password prompt at the beginning of the script's run rather than the end.  That way you can walk away from the run and have it complete without you.
- [x] 5. Update the cleaning portions of the script.  --clean_test_users does not seem to work.

**Comment by sanjuroj** [comment]
@jennyhavah Creating sites seems like a good idea to me but I'm not sure about assigning results to them.  Would it be better to leave the results without sites so that we can make sure the filters are working the way we want (i.e. disabled because there are no sites associate with any of the indicators)?  Or would it be better to remove the site links to test for disabled IPTT filters.  

And I have the same question about the other filter values.  Should I apply Sectors and Types to indicators so those filters are active by default in the QA programs?

**Comment by jennyhavah** [comment]
@sanjuroj I think that's a good thing to keep an eye on -- whether filters are disabled as expected, etc. At the same time, it's also useful to be able to quickly test a bunch of filters without having to go into results and indicators to activate them. It seems like there are a lot more QA use cases involving active filters than disabled ones.

How about this:

1. For our _named_ programs, we assign a couple of Tolaland sites to some results and assign an assortment of Sectors and Types to indicators.

2. For the rest, we leave as is -- no sites, types or sectors assigned.

**Comment by sanjuroj** [comment]
@jennyhavah I updated the criterion.  Feel free to tweak.

**Comment by camgnostic** [comment]
Note: @jennyhavah noticed that MC-Medium users do not in fact have a permission level of `medium` in practice.  The code (lines 634-638 and 683-689 of create_qa_programs.py) suggests they should.

- [ ] Ensure medium test users are created with medium permissions which translate to an in-effect medium permission level on the site.

**Comment by jennyhavah** [comment]
@camgnostic It's a bit broader, in that it seems to affect all medium _and high_ type QA test users -- the mc ones, the external ones, the gmail ones... Specifically for Tolaland, they don't have the right level of program permission.

**Comment by jennyhavah** [comment]
> Use a obscured password entry field when entering user passwords and prompt for confirmation instead.

@sanjuroj Can you explain this one to me?

**Comment by sanjuroj** [comment]
This is a totally behind the scenes thing.  When running the script that creates the QA programs, the person running it needs to enter a password (at the command line).  This password shows up as plain text while it's being typed.  It would be more secure to show just "****" or nothing when entering the password.

**Comment by sanjuroj** [comment]
Committed to the dev branch, currently testable on QA and Dev servers.

**Comment by jennyhavah** [comment]
> 1. All post-Satsuma QA programs (i.e. all but one of them) have every indicator assigned to a result level. (We don't permit unassigned indicators in the post-Satsuma world.)

Looks like a good chunk of the QA programs have four indicators that are unassigned -- the named ones and some of the others as well.

**Comment by jennyhavah** [comment]
> 3. Add a few Sites, Types, and Sectors only to named QA program indicators. The others should be left without any associated Sites, Types, or Sectors, so filters can be evaluated for appropriate disabling.

Was this done or should we move to a different ticket? (Not seeing the changes on Dev2 or QA.)

**Comment by sanjuroj** [comment]
@jennyhavah Ok, try now, the script was actually run.  QA or Dev servers.

**Comment by jennyhavah** [comment]
**Validated:**

1. Spot checked a bunch of QA programs and all indicators appear to be assigned to result levels, except for the pre-Satsuma one.

2. QA program indicators now have assigned sectors, types, and sites.

I don't know how to validate the other criteria. @sanjuroj if you can validate those, feel free to move to Passed when done.

**Comment by sanjuroj** [comment]
Other items are completed.  Moving to Passed.
