### ISSUE TITLE
Add new indicator: Possible to add duplicates by mashing the URL bar

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1917]
To duplicate on Chrome (have not tested other browsers):

1. Click "add indicator" and fill out all required fields.

2. Hit "Save and close" and _very very quickly_ click into the URL bar and mash the return key a bunch.

This is what I get:

![image](https://user-images.githubusercontent.com/33670923/64283517-76ba7880-cf0c-11e9-9c79-1f703bc6d77b.png)

**Comment by camgnostic** [comment]
Applied rate limiting to indicator creation on the backend.  It should now be impossible to create multiple indicators from one save form, even if the front-end doesn't stop you.  To test this, try mashing reload and any other method to get the form to submit again (mash the submit button, hit reload right after it disappears, hit reload after saving, etc.) - it should only create one indicator

**Comment by jennyhavah** [comment]
No longer able to replicate this error because we've fixed the spinning wheel issue from #1793. So I can't move quickly enough to mash the URL bar.

Chatting with Cameron: In an area with a slow internet connection, it might be possible to mash the URL bar while an indicator is in the process of saving. It will no longer save duplicates; in a worse case scenario, a user might get a 400 error message that encourages them to reload the page; in any case, the indicator will only be saved once.
