### ISSUE TITLE
Change log: Updates to export of disaggregation values

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1919]
(See #1520 for web version)

Change log export currently contains raw JSON data for disaggregation values.  To do:

- [ ] ~change label of disaggregation_values to sentence case, no underscores, and translated~
- [ ] format display of disaggregation values to match criteria in #1520
- [x] datetime stamp of log entry should be consistent across web and Excel.  The timestamps on the web matched those in the database but the ones in Excel were adjusted for timezone.  Timestamps should be displayed as they appear in the database.

(Related issues that could be solved simultaneously: individual target values are labeled with an untranslated target name/label in export but not web, similarly the labels for `sites`, `id`, and potentially others - could be a simple solution to all of the labels, to investigate while working on this ticket and annotate below)

**Comment by sanjuroj** [comment]
@jennyhavah I noticed that the timestamps on the log entries on the web and in the Excel file were different.  I'm assuming we want to display whatever is in the database without adjusting for timezone, but let me know if you'd prefer something else.  I'm also assuming they should be consistent, regardless of whether there is a timezone adjustment or not.

**Comment by jennyhavah** [comment]
@sanjuroj Ideally we _are_ adjusting for time zones AND the time stamps are consistent in web and export versions.

This feels more like a separate bug than an incidental fix to some other ticket. If you agree, can you create a new ticket for it? If it's low LOE, let's keep it in Goat Tree. If it's higher LOE, shall we make it a high priority Poblano ticket?

**Comment by sanjuroj** [comment]
@jennyhavah Making them consistent is easy, and we should at least do that.  We just have to decide wether to use Portland time or UTC. 

Localizing the timezone for the web view is pretty easy but doing so for the Excel download less so.  I think that should be a separate ticket if we want to do it.  

So I'm proposing that we make the two outputs consistent, set at PDX time, but I file another ticket to make them both localized time.

**Comment by jennyhavah** [comment]
@sanjuroj Agree about making them consistent for now and filing a separate ticket for the localization work.

One thing regarding the short term solution: I seem to recall that when we had to pick a single time zone to use for determining when target periods end, we picked GMT, not PDX. I'd like to keep the change log consistent with that. So can we double check what we're doing there and do the same thing for the change log?

**Comment by sanjuroj** [comment]
Yeah, there was that whole "When is a period considered closed?" discussion as part of #1143.  I'll set both values (web and Excel) to UTC.

**Comment by jennyhavah** [comment]
Great. To recap the chat @sanjuroj and I just had:

1. We want to use a single time stamp to avoid confusing conversations when the changelog reviewer in DRC is talking to the changelog reviewer in London. We do _not_ want to localize time stamps.

2. We want to include the abbreviation UTC in the time stamp, so that people are not confused as to why it doesn't match their local time zone.

**Comment by jennyhavah** [comment]
@camgnostic In the course of Paul styling the change log for #1520, we made a decision to get rid of the sub-header "Disaggregated values" in the web view. It doesn't add any useful information and was frustrating our attempts to improve the visual hierarchy.

I crossed out that criteria in the original ticket. Can you please remove the "Disaggregated values" sub-header from the Excel version of the change log?

**Comment by jennyhavah** [comment]
Looks good. No longer seeing "Disaggregated values" sub-header in the export.

![image](https://user-images.githubusercontent.com/33670923/73694586-331b9480-468d-11ea-8012-ef2e96c86eb5.png)
