### ISSUE TITLE
Auto-generated LoP values between zero and 1 should be acceptable as LoP targets

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1922]
# Issue
It should be possible to have an LoP target that is greater than 0 but less than 1. Today, this works fine for LoP only indicators, when you manually enter a value such as .73. The problem arises with all other target frequencies where LoP values are now _automatically generated_, since the Satsuma release. If your periodic targets add up to an auto-generated LoP value of less than one, you are unable to submit the form. Here are a couple of examples where the Indicator form refuses to save because of a decimal LoP target.

![Screen Shot 2019-09-05 at 3 38 32 PM](https://user-images.githubusercontent.com/6685499/64377656-bf8f3180-cfdf-11e9-84af-84c784e11dbf.png)

![image](https://user-images.githubusercontent.com/33670923/64379346-8e186500-cfe3-11e9-8b0b-b4e89244cbd0.png)

# Acceptance criteria

**Affects:** Applies to indicators of every target frequency except for LoP only, _for both # and % indicators, cumulative and non-cumulative._

When my periodic targets result in a LoP value that is greater than zero but less than one, I do not see any warning messages and am able to submit the form. Be sure to test the following combinations of options:

- [x] 1. Number indicator, cumulative
- [x] 2. Number indicator, non-cumulative
- [x] 3. Percentage indicator, cumulative
- [x] 4. Midline/endline
- [x] 5. Event
- [x] 6. Time-aware

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
Passed -- tested all the combinations listed in the original ticket. Each time, LoP values were accepted and displayed as expected when between 0 and 1. Example screenshot below.

![image](https://user-images.githubusercontent.com/33670923/69570036-ce004000-0f73-11ea-9d06-39f43e47617e.png)
