### ISSUE TITLE
Blank page when I click on default pin to Recent Progress report

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1924]
To reproduce on QA:

1. Go to a program page like VISTA: https://tola-activity-qa.mercycorps.org/program/550/#/
2. Click on the auto-generated pinned report link, here: 
![image](https://user-images.githubusercontent.com/33670923/64382321-434e1b80-cfea-11e9-9d0a-df69d2984c9c.png)

I get a blank page and the URL looks a little suspect with a NaN: https://tola-activity-qa.mercycorps.org/indicators/iptt_report/550/timeperiods/?frequency=NaN

**Comment by jennyhavah** [comment]
Looks okay for manually created pins -- so far only happening with that auto-generated one.

**Comment by jennyhavah** [comment]
@camgnostic So what was the issue here? Wondering if there are other places I should look for something similar...

**Comment by jennyhavah** [comment]
Issue is fixed.

**Comment by camgnostic** [comment]
Issue was that we have gone through 3 iterations of the query parameters for the IPTT - originally there was `?timeframe=1` meant show all, and `?timeframe=2` meant most recent, and sometimes it put the whole date into the query (`?start_period=2018-01-23`) and I simplified and streamlined it as part of the move to React.  I caught 2 of our previous versions of query parameters in this latest refactor, but somehow missed one chunk of them.  So it wasn't recognizing those query parameters, and erroring out.  The fix involved _both_ adding those query parameters in (so if it gets an old-style url like `?timeperiods=7&timeframe=2&numrecentperiods=2` it converts it to the new style and displays the right report, but _also_ adding in better error handling so if for some reason that fails in the future, or someone just types gobbledygook into the address bar, it will at _worst_ show the right selected program and the rest of the select boxes fallback to defaults.  Testing would be to look at program pages that have old saved pins, and make sure those pins go to the right reports.
