### ISSUE TITLE
Program page and IPTT: White box effect on clicking certain elements

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1925]
I've noticed a new white box effect in a few places:

- [x] 1. **Program page:** 

     - [x] 1.1. Clicking on an indicator to expand or contract the row:

     ![image](https://user-images.githubusercontent.com/33670923/64385988-ca9c8e80-cfec-11e9-9157-7c44f472f479.png)

     - [ ] ~~1.2. Clicking on "Add result" when it's low enough on the page to be visible once the modal is open.~~

     ![image](https://user-images.githubusercontent.com/33670923/64386266-7a71fc00-cfed-11e9-8304-8a3259c4bf0d.png)

- [ ] 2. **IPTT**

     - [ ] ~~2.1. Clicking on table icon to see result table~~

     ![image](https://user-images.githubusercontent.com/33670923/64386042-f4ee4c00-cfec-11e9-81d3-c79c10316888.png)

     - [ ] ~~2.2. Clicking on gear icon when it is in a position to be viewed once the modal is open. (This does NOT happen on the program page.)~~
     
     ![image](https://user-images.githubusercontent.com/33670923/64386093-164f3800-cfed-11e9-9458-da38f468c8d0.png)

**Comment by camgnostic** [comment]
@jennyhavah  and @axoplasm  this is an accessibility issue / global design issue - can we bump this from "regression hotfix" to "discussion needed" - button highlighting is part of keyboard accessibility as it indicates which button a user has "tabbed" to, and will activate when they press spacebar (an important part of keyboard-user access) but it also is visually distracting (an important part of all user access) wondering if you two can come up with a design solution that meets both criteria.

**Comment by jennyhavah** [comment]
Thanks for the additional context -- didn't realize it was a deliberate choice related to accessibility. 

There's just one element of what I reported that's bugging me enough to pursue further, which is that the indicator name appears to be editable.

@axoplasm Is there a way to make it appear "selected" and meet accessibility guidelines without giving it the appearance of being editable?

**Comment by axoplasm** [comment]
Yes I can address its appearance. We are also loading a lot of expectations on “buttons” that I can review

**Comment by jennyhavah** [comment]
Looking good! The change from a white background to gray makes all the difference.

![image](https://user-images.githubusercontent.com/33670923/64569044-2e86c600-d311-11e9-8f9e-6287547a134f.png)
