### ISSUE TITLE
Regressions related to ticket 1772

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1927]
We have some regressions related to work done on #1772, regarding when the top tier shows up in IPTTs, and the use of the Levels filter.

- [x] 1. When I select a **level** other than Goal, Goal still shows up on QA, but not Dev2. 

Dev 2 is on the left, QA on the right:

![image](https://user-images.githubusercontent.com/33670923/64386850-0e909300-cfef-11e9-9d21-669efbf00c0d.png)

- [x] 2.  When I select a **result chain**, the top tier still shows up on QA, but not on Dev2. (Result chains start at the 2nd tier.)

Dev 2 on the left, QA on the right:

![image](https://user-images.githubusercontent.com/33670923/64386918-47306c80-cfef-11e9-8cf0-d4c916f4b015.png)

**Comment by camgnostic** [comment]
best case regression - not accidental, just missed the furthest update on level filter expected behavior from satsuma spec.  Updated code to match the accurate specs.

**Comment by jennyhavah** [comment]
Top tier is now appearing as expected on QA, when I use the Level filter.
