### ISSUE TITLE
Hyperlink program page text in headers

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1933]
- [ ] Make the program name that is a title towards the top of the IPTT page a hyperlink to the program page.
- [ ] Make the program name in the title of the change log page a link to the program page

**Comment by camgnostic** [comment]
This is done in LevelUp

**Comment by jennyhavah** [comment]
@camgnostic Can we make the styling of the page header consistent with the Logframe? 

Right now it looks like this:

![image](https://user-images.githubusercontent.com/33670923/67607229-a2055b00-f738-11e9-93f5-c3f4707d2aca.png)

Can we make it look like this -- in terms of the order (program first, then page title), font size, space between the colon and the text after the colon, etc?

![image](https://user-images.githubusercontent.com/33670923/67607250-b0537700-f738-11e9-8227-ac3e688f774c.png)

**Comment by jennyhavah** [comment]
Looks good! Here's what I see for the change log:

![image](https://user-images.githubusercontent.com/33670923/67819519-b0be7b80-fa72-11e9-8df5-58ba4cb2faac.png)

I also validated that the program link works on the IPTT page.
