### ISSUE TITLE
IPTT filters are only active if there are two values

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1934]
This may be completely intentional, but the sectors, types, and sites filters are all inactive until there are at least two values to chose from (the Level filter does allow for just one value).  This is different that the current production code where one value is sufficient to activate the dropdown.  By inactivating the dropdown if there is only one value, users are prevented from filtering out e.g. indicators that haven't been assigned a sector.

**Comment by camgnostic** [comment]
definitely a bug and not intentional - turns out integers test positive for having a length of 0 in JS  - who knew?

**Comment by sanjuroj** [comment]
PASSED, single value filters are now available.
