### ISSUE TITLE
Most recent field: I'm able to type letters and special characters

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1941]
The following is true on QA but not Production: I can type letters and special characters into the Most recent period. 

It doesn't appear to blow anything up, but as a general rule, always best not to allow people to type in weird @$*!!

Update: This bug applies to Firefox and Safari, but not to Chrome.

**Comment by sanjuroj** [comment]
Just a note, I can reproduce this on Firefox but not on Chrome.

**Comment by jennyhavah** [comment]
Aha, it's also true on Safari. Will update the ticket.

**Comment by jennyhavah** [comment]
Fixed on Safari and Firefox.
