### ISSUE TITLE
Update French translations

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1944]
There are several French translations that have been identified as needing revision.  It should be sufficient to make the changes to the French .po file.  The list of changes is being kept here:
https://docs.google.com/document/d/1zMxJ4GcmVkg_nu-hWfQ5gkOYNq5mvUwj3bqA_mQbp1Q/edit#heading=h.oakof1mgiv2g

**Comment by jennyhavah** [comment]
@sanjuroj I need some guidance on how to test this ticket. I've never worked with a PO file.

**Comment by sanjuroj** [comment]
@jennyhavah Testing for this particular ticket would just be to go through the system to see if the translations outlined in the Google doc have actually been updated to the French translations that were requested.

**Comment by jennyhavah** [comment]
@sanjuroj Please check out the document again -- everything that's done, I grayed out. Everything not yet done (that I can see on QA), I marked as such.

**Comment by jennyhavah** [comment]
@sanjuroj Given that Marie is in DRC for several weeks, I'd like to propose that we go ahead an merge the translation fixes you've already done, so I can get the ticket passed. And move the remaining translation issues requiring clarification from Marie to 310 in Confluence.

**Comment by sanjuroj** [comment]
Ok, I merged the changes I had and updated Tola-310 as a reminder.

**Comment by jennyhavah** [comment]
Looks like "Baseline" is still untranslated on the targets tab -- it should be "Mesure de base"

![image](https://user-images.githubusercontent.com/33670923/76153700-5ff40a80-6084-11ea-8e33-604c85eb6a8b.png)

**Comment by jennyhavah** [comment]
Please make "Fréquence de Rapportage" sentence case to match the other form labels on that tab:

![image](https://user-images.githubusercontent.com/33670923/76153728-cb3ddc80-6084-11ea-9f20-7fe96c23bf45.png)

I'm aware that there's a ton of variability in terms of title vs. sentence case, depending on your language setting and what tab of the indicator form you're looking at. My preference is sentence case everywhere, but I am not filing tickets every time I notice it because we'll be replacing this whole form pretty soon with Swift.

In this particular case, it jumps out more since it's the only label in TC on the tab. So thought I'd mention it.

**Comment by jennyhavah** [comment]
@sanjuroj Moving back to "in dev", since she responded to the remaining open questions on that doc -- seems like we have enough time to get those updates in...

**Comment by sanjuroj** [comment]
@jennyhavah Testing note:  Marie provided two slightly different translations one item.  An earlier translation of "Cible de la **de** vie du programme" and a later one of "Cible de la vie du programme...".  I used the later one.

**Comment by jennyhavah** [comment]
@sanjuroj As we discussed on Slack, I agree that the "La" should be removed in one place, to be consistent with "Vie du programme" in the sum row:

![image](https://user-images.githubusercontent.com/33670923/76576310-fa868c00-647e-11ea-936f-0d896561aa68.png)

**Comment by sanjuroj** [comment]
@jennyhavah This particular translation is different from the others.  It is shared with any translation that uses this type of indicator frequency (e.g. the target frequency dropdown on the indicator modal).  To change just this one, I would need to break our normal pattern of translations.  I think it might be better to open a separate ticket for this to see if we can find a differentiating English phrase, "_A_ Life of Program..." vs "Life of Program..." or see if getting rid of the "La" everywhere would actually be better.  Thoughts?

**Comment by jennyhavah** [comment]
@sanjuroj I'm going to ask Marie to review what we have and clarify any additional changes she'd like to see. It's entirely possible that it's fine as it is. I'll pass this ticket and put any additional refinements in a new ticket.
