### ISSUE TITLE
Migration spike: Investigate disaggregated results data and make a plan

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1950]
Find out which programs and indicators have disaggregated RESULTS entered. 

Create a plan to preserve this data. Account for the following edge cases: 

1. If disaggregated values do not add up to the LoP value (number indicators only), we should display the values as they are now in the IPTT and result form. If you edit the result without fixing and submit, the system will not let you save until you correct the discrepancy.

2. Letters and special characters -- won't preserve, all fields converted to numeric.

3. Disaggregated values entered, where the disaggregation type is not selected for the indicator. Could potentially happen if a disaggregation was assigned from the "wrong" country. (This work may be covered by #1822)

**Comment by jennyhavah** [comment]
@cameron Two query requests to help test this ticket -- ideally I'd prefer a Slack link to a spreadsheet with results, as opposed to the raw output in the Slack comment.

1. Please resend me the query output you produced some time ago that had a list of indicators from the "wrong" country. Having trouble locating it. 

2. Would you be able to run a query that gives me a handful of Prod data examples of the first scenario described, so I can validate that we're handling it as intended? Please share via Slack or email.

**Comment by camgnostic** [comment]
both sent via email

**Comment by cameron** [comment]
glad it's been taken care of ;)

**Comment by jennyhavah** [comment]
Sorry about that, @cameron!

**Comment by jennyhavah** [comment]
I tested results from multiple indicators and several different programs. In all cases, when I tried to re-submit the result without fixing anything, the appropriate warning messages appeared.
