### ISSUE TITLE
Country page: Replace "Change country" menu with a "Browse sites" link to the Sites landing page

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1952]
UPDATE: With #1205 we are removing the entire Browse menu, so that we don't end up with a menu that has a single option: Sites. We are expanding this ticket to not just remove the Country menu but replace it with a link to Browse all sites

# Issue

On the Country page, the "change country" menu above site map is pretty fidgety. You have to click it just so, and it's difficult to switch to more than one country in sequence. You have to un-focus on the menu, then re-focus. Sometimes it reacts before I've had a chance to make a selection. It's just... not good. That menu is redundant at this point, now that we have a much more user-friendly Country and Program search box in the top nav bar, immediately above the "change country" menu.

For reference, here's the current site map with "Change country" menu.
![image](https://user-images.githubusercontent.com/33670923/64886392-f5a16680-d61a-11e9-8893-487966527d80.png)

# Acceptance criteria

![image](https://user-images.githubusercontent.com/33670923/65547346-2ceefd80-dece-11e9-94ed-c721fa930fdc.png)

- [x] 1. There is no longer a "change country" menu above the site map, next to the Country name.

- [x] 2. There is a new "Browse all sites" link in line with the Country name. It takes me to the same place our top nav "Browse > Sites" option used to take me.

**Styling note:** I mocked up the "Browse all sites" link to be right-aligned with the map rather than immediately after the country name. While I think this makes the link more visible, it might cause problems with a longer country name like Democratic Republic of the Congo. If that's the case or it's otherwise problematic, it's fine to place it where the "Change country" menu currently lives.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
It does seem pretty redundant.

**Comment by jennyhavah** [comment]
Removed estimate because the scope of the ticket has changed.

**Comment by camgnostic** [comment]
I did this with the right aligned setup per mockups, looks fine with DRC:
![image](https://user-images.githubusercontent.com/7941355/65732429-be04d680-e07e-11e9-809d-7dd33755dd01.png)

I worry that the CSS on this is.... jaw-droppingly ugly.  If @axoplasm has a chance to look at it (it's on 663d86d) it could probably be done in a less horrifying way.

**Comment by jennyhavah** [comment]
Here's what I see after Paul's updates -- looks fine.

![image](https://user-images.githubusercontent.com/33670923/69470162-bc3b5480-0d49-11ea-9e49-c6aa116ab849.png)

**Comment by jennyhavah** [comment]
The link also goes where it is supposed to go.
