### ISSUE TITLE
Results table on Program Page Reactivity broken

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1953]
As a user with results-editing privileges (country admin, program high, program medium) if I open the program page and
- [x] select "add result" fill out the form correctly, and save, the modal should close and the results table (and any other previously open results tables) should still be expanded and display the added result, and any filters applied to the indicators list should remain the same
- [x] click a result date in a results table, make changes to the form, and save, the modal should close and the results table (and any other previously open results tables) should still be expanded and display results including the changes made to the updated result, and any filters applied to the indicators list should remain the same
- [x] click a result date in a results table, click "delete result" and save, the modal should close and the results table (and any other previously open results tables) should still be expanded and the deleted result should not be visible in the table, and any filters applied to the indicators list should remain the same

No change but regressions checks:
- [x] As a low-permissioned user, if I open a result table and click the link to view the modal I should (still) see the modal without save options, and should (still) see no change to the program page including displayed results tables and filters when I close the modal.

**Comment by camgnostic** [comment]
Question for @jennyhavah - there's a lack of visual feedback on this reactivity, and I wonder if that's something to consider for a release (less GP, more Poblano) - to see what I'm seeing:
- open a results table from the program page,
- edit a result
- change the date and hit save
- watch the results table: after a quick round trip to the server to verify updated info, the page instantly changes in place to the new date.  

Wanted to get your UX eye on that.

**Comment by jennyhavah** [comment]
@camgnostic I'm thinking this ticket would address the visual feedback issue while also making the save flow more consistent with the conventions introduced in Satsuma: https://github.com/mercycorps/TolaActivity/issues/1821.

**Comment by sanjuroj** [comment]
PASSED.  Program page now responsive to create/udpate/delete operations on results.  High and med users can affect results, low users can't.
