### ISSUE TITLE
Untranslated text

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1957]
1. In the RF Builder, when I click the "Indicators" link on a level card, the popup is titled "Track indicator performance" (untranslated) and the first two options in the list are also untranslated.
![image](https://user-images.githubusercontent.com/7941355/64997846-c0a14800-d896-11e9-8770-eaacb76959ca.png)

2. When creating a new program, if the GAIT id can't be fetched from MCAPI, the first part of the warning message is untranslated: "Failed to sync GAIT program start and end dates"

<img width="898" alt="Screen Shot 2019-12-20 at 3 16 10 PM" src="https://user-images.githubusercontent.com/6685499/71298208-df065c00-233b-11ea-8e5d-55b77125ce8f.png">

**Comment by jennyhavah** [comment]
@camgnostic I am not seeing the fix yet. Here's what I see on QA with my language set to French.

![image](https://user-images.githubusercontent.com/33670923/73400989-1a7f3900-429f-11ea-8c34-d11fb2f78ec3.png)

**Comment by jennyhavah** [comment]
@camgnostic How can I make the system generate that error to check the translation of the error message?

**Comment by camgnostic** [comment]
@jennyhavah  - to reproduce the error message, go to Admin > Programs > Add new Program, and enter a program with a nonsense GAIT id, and hit save.
![image](https://user-images.githubusercontent.com/7941355/73568336-0e20ea80-441d-11ea-9a85-f5085f907b9e.png)

**Comment by jennyhavah** [comment]
Looks like the first sentence is still not translated.

![image](https://user-images.githubusercontent.com/33670923/73571106-b2f1f680-4422-11ea-8561-3dc77f4e7b21.png)

**Comment by jennyhavah** [comment]
Results framework translation issue is fixed.

![image](https://user-images.githubusercontent.com/33670923/76020889-20d58600-5ed9-11ea-8414-83f66ac295b1.png)

![image](https://user-images.githubusercontent.com/33670923/76020925-3185fc00-5ed9-11ea-9987-9ee28beabd53.png)

**Comment by jennyhavah** [comment]
@camgnostic Here's what I'm seeing for the GAIT ID error message:

![image](https://user-images.githubusercontent.com/33670923/76021089-7742c480-5ed9-11ea-8ee7-ea7098df23de.png)

Looks like the first sentence is still not translated.

**Comment by sanjuroj** [comment]
If something ends up needing professional translation at a later date, can you add it to the list in Jira ticket 310?

**Comment by jennyhavah** [comment]
@sanjuroj So are you saying that this has not yet been translated, and therefore not a technical issue (adding/fixing tags, etc.) that we can resolve for Goat Tree?

**Comment by jennyhavah** [comment]
Added the untranslated string to JIRA 310, so we can consider the ticket passed for Goat Tree.
