### ISSUE TITLE
Indicator Form GET request for RF-framework program fails 500

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1963]
- [x] clicking "add indicator" from program page of a program that has migrated to RF should open the indicator form
- [x] clicking "add indicator" from an open level card in the RF builder of a program that has migrated to RF should open the indicator form
- [x] clicking "update indicator" (gear icon) from program page of a program that has migrated to RF should open the indicator form
- [x] clicking "update indicator" (gear icon) from the IPTT of a program that has migrated to RF should open the indicator form
- [x] Tests written to cover this case for future regressions

**Comment by jennyhavah** [comment]
I am presuming that "migrated to RF" refers to a pre-Satsuma program that has checked the "Group by RF levels" box. So I tested this by checking the "group indicators by RF" box on our Pre-Satsuma QA program and then going through the acceptance criteria. All interactions worked as described.

@camgnostic let me know if I misunderstood the purpose of the ticket and should have tested a different way.
