### ISSUE TITLE
Program Page sorting (chain/level) appears to be broken for manually-numbered RF programs

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1964]
- [x] Program Page for RF program with manual numbering display turned on shows indicators in chain order when chain order is selected (despite level ontology not being displayed due to "manual numbering" selection)

- [x] Program Page for RF program with manual numbering display turned on shows indicators in level order when level order is selected (despite level ontology not being displayed due to "manual numbering" selection)

- [x] Tests written to cover this case for regressions

**Comment by jennyhavah** [comment]
Validated that when programs are using RFs AND manual numbering, the "group by" function sorting works as expected on the program page.
