### ISSUE TITLE
SiteProfile form pages render

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1977]
- [x] When I click "add site" from the program page I go to the site create form
- [x] When I click "add site" from the site list page I go to the site create form
- [x] When I click the site date or name in the site list page I go the site update form
- [x] When I click the delete site link in the site list page I go to the site delete confirmation form
- [x] Tests written for the above

**Comment by jennyhavah** [comment]
All front end interactions validated.
