### ISSUE TITLE
Update and speed up maps

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1999]
Map on home (country) page should:
- [x] color active country blue
- [x] color all other Mercy Corps countries gray

Map on siteprofile list page should:
- [x] color all Mercy Corps countries gray

Both pages:
- [x] Hovering over a Mercy Corps country that I have access to at least one program in (i.e. country page for that country should not be blank for me) should result in a darker gray highlight of the country
- [x] Clicking on one of the above countries should take me to that country's country page
- [x] A control in the top right should show the layers clip art, clicking this control opens a list of "sites with results" and "sites without results" checkboxes.
- [x] Unselecting a checkbox removes that item type from the map
- [x] Clicking anywhere in the map outside of the checkbox list collapses the checkbox list back to a layers icon

**Comment by jennyhavah** [comment]
All acceptance criteria are validated.
