### ISSUE TITLE
Collected Data form: Update two labels

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#20]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Tuesday Dec 12, 2017 at 16:53 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/10_

----

**Affects:** Collected Data form

**ACCEPTANCE CRITERIA**
1. The form field _**Periodic target**_ is changed to _**Measure against target**_.
1.1. **Why?** Not all targets are periodic. The original form label is confusing if you're using midline, endline, or event-based targets that are not defined by date ranges.
2. The form field **"Achieved"** is changed to **"Actual value**".
2.1 **Why?** "Achieved" is a confusing term in this context because it implies success or analysis of progress towards the LoP. "Actuals" is a more common term used in reports -- i.e. target versus actual values.

![updatefields](https://user-images.githubusercontent.com/33670923/34279805-2270e6b2-e668-11e7-9e90-4e5a137a55ef.png)

**Comment by jennyhavah** [comment]
![image](https://user-images.githubusercontent.com/33670923/35191547-8eeadc4e-fe32-11e7-9d29-8cd2e2c8285b.png)

Can we give the label column enough space so that the "Measure against target*" label doesn't wrap? (Looks like we've got plenty of room, given how wide the disaggregation table is.)
