### ISSUE TITLE
(test) Write functional test verifying feature parity between page and popup version of Event "period" deletion

### ISSUE THREAD

**Issue by kurtwall** [mercycorps/TolaActivity#200]
From #183:
>The delete a target period function does not work in the full page version on the dev server. When I click the red X, it is non-responsive.
>
> In the modal window, it appears to be okay

Feature parity between full-page and popup functionality needs analysis (see #199). In the meantime, this particular bug can be get its own test.

**Comment by jennyhavah** [comment]
Note: After ticket #263 is done, the only type of target period you'll be able to manually delete is Events.
