### ISSUE TITLE
Program page: Low- and medium-access users see the "Add indicator" button

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2002]
**Affects:** Users with Low or Medium level access to a program

# Issue

I see the "Add indicator" button above the indicator list. I should not see this button because only High level users are allowed to add, edit, and delete indicators.

It does not appear that I can actually save a new indicator because required form fields are grayed out. 

From Sanjuro: The commit date is Aug 21, so it happened a little while ago.  It’s a super easy fix for that one item, though I’ll need to check whether there could be other things affected.

# Acceptance criteria

- [x] 1. When I have Low or Medium access to a program, I don't see the "Add indicator" button .

- [x] 2. Ensure that the Aug 21 commit didn't cause other issues related to roles and permissions.

**Comment by jennyhavah** [comment]
@sanjuroj Assigned the issue to you because you've already begun investigating.

I added it to Ghost Pepper not because it's catastrophic but because it affects a significant percentage of users who are seeing a call to action that they shouldn't see. If the problem turns out to be isolated and low-risk to fix, it seems worth considering a patch release.

I don't feel strongly about this, though, if you'd prefer to wait for LevelUp.

**Comment by sanjuroj** [comment]
I think a patch release makes sense.  That said, as far as I can tell, there are no other effects outside of that visible Add Indicator button.

**Comment by jennyhavah** [comment]
As mentioned in Slack, this looks good to go!
