### ISSUE TITLE
Number indicators: Switching from non-cumulative to cumulative results in wacky table

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#203]
This only appears to be an issue for number indicators, not percentage. Here's what I did:

1. Clicked "New indicator" button to add a new indicator to TolaData Test on the dev server.
2. Unit of measure is set to Number. Created 3 annual targets and entered target values.
3. Switched from Non-cumulative (default) to Cumulative and clicked Save Changes.

This is what I see:
![image](https://user-images.githubusercontent.com/33670923/38841609-1aa11870-419a-11e8-8fdb-87e5dc528fae.png)

Problems I see:
1. Table layout is messed up.
2. There is still a Sum of targets row even though I've chosen Cumulative.

Everything looks okay on the Indicators page -- results are displayed Cumulatively. However, when I open the indicator modal, go to the Targets tab and switch from Cumulative back to non-cumulative, I see this:

![image](https://user-images.githubusercontent.com/33670923/38841726-aa196412-419a-11e8-9626-dc7019943649.png)

It's correctly displaying the sum of targets row, but the layout is messed up. From there on out, if I toggle back and forth, I get the messed up table.

**Comment by sanjuroj** [comment]
The same thing happens with pre-existing targerts.  In [this indicator](https://tola-activity-dev.mercycorps.org/indicators/indicator_update/8913/#targetsTab), changing to non-cumulative targets has the same result.  The problem is with the display type being used on the Sum of Targets row element.

**Comment by jennyhavah** [comment]
No longer seeing the wacky table.
