### ISSUE TITLE
Browse all sites page: Indicator data button goes to non-existantant custom dashboard page.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#2036]
The Indicator data button on each Site row has gone to a "custom dashboard".  Those don't exist any more so it's throwing and error.  Do we reconstitute the custom dashboard or go with something else as a placeholder until we can replace the Sites functionality?

<img width="1242" alt="Screen Shot 2019-11-13 at 4 26 52 PM" src="https://user-images.githubusercontent.com/6685499/68816173-75a37700-0632-11ea-97d3-14ab8b5609c9.png">

**Comment by camgnostic** [comment]
Pinging @jennyhavah to weigh in on this UX decision (welcome back :)

**Comment by jennyhavah** [comment]
The term "custom dashboard" in the URL is a little misleading, in that it's not some sort of wacky Projects-specific dashboard with donut charts and stuff. Here's an example of what we're currently displaying on Prod:

https://tola-activity.mercycorps.org/workflow/site_indicatordata/4526/

![image](https://user-images.githubusercontent.com/33670923/69079397-bdd5e700-09ee-11ea-8898-ccac1594eb12.png)

To get this view, I selected "TolaData Demonstration Program" from the program menu on the Browse Sites landing page. I do not understand what's going on here and doubt it's useful or used much. And according to Google Analytics, they've gotten almost no traffic in the last year.

I'm happy to ask Marie if we can 🔥this feature, but first want to confirm that there would be more than a trivial level of effort to restore the current functionality. Is that the case?

**Comment by camgnostic** [comment]
it should be non-trivial to restore, if we can get a pretty good handle on what all the current functionality entails, yes

**Comment by jennyhavah** [comment]
@camgnostic Given the low usage and utility, I'm questioning whether it's even worth investigating. If this isn't blocking anything else, can we postpone work on it for now? I'll check in with MEL and make sure they want to keep this feature.

**Comment by camgnostic** [comment]
Errant link now goes to program page instead of non-existant customdashboard, rest of indicator-site-data page remains as on production

**Comment by jennyhavah** [comment]
Indicator data page is now loading when I click on "indicator data". From that page, you can click links to the program pages.

@camgnostic I'm unclear on which link you're referring to here:
> Errant link now goes to program page instead of non-existant customdashboard

Can you clarify?

**Comment by camgnostic** [comment]
The problem with that page loading was this link: 
<img width="490" alt="Screen Shot 2019-11-25 at 1 07 56 PM" src="https://user-images.githubusercontent.com/7941355/69578125-acf41b00-0f84-11ea-8a0d-67a29b7da072.png"> was trying to go the "custom dashboard", but the site couldn't find where that should lead so it just broke the whole page.  I've repointed that link (the program name in the indicator data page) to send the user to the program page.

**Comment by jennyhavah** [comment]
Perfect. Passed!
