### ISSUE TITLE
Project data button should be removed from each row of the site listing.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#2037]
Since projects are no more, the project link is a bore.

**Comment by jennyhavah** [comment]
Total bore! I no longer see project links or a project column header on the "browse all sites" page.

@sanjuroj is there any dead code we want to delete to wrap up this ticket? Like, is it still doing a check to see if you have access, etc?

**Comment by sanjuroj** [comment]
@jennyhavah No need for further changes, Cameron took care of it.
