### ISSUE TITLE
DB: make DisaggregationValue.value a Decimal Field, and migrate old values to be numeric (null=True)

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#2039]
1) `indicators_disaggregationvalue`.`value` is a VARCHAR at the moment.  While most countries have not strayed from the result constraints of a 2-digit decimal number, there are some (for example WIT in Jordan) which have longer decimals and/or percent values.  These need to be migrated (and saved for reference in the case of archived values)

2) there are many loose disaggregationvalue entries which do not have an indicator, a result, or a program.  Remove these orphans.

3) An orphan prevention method is needed to ensure disaggregationvalue instances die with their parents

4) Migrate the disaggregation table so value is a Decimal field.

**Comment by camgnostic** [comment]
Additional criteria:
- change the reverse ManyToMany relationship from Result to DV into a Foreign Key from DV to Result (any DV has, at most, one result which it is disaggregating), and a FK from DV to DL/category (any DV has at most one category into which it is disaggregating the result).  This should eliminate the orphan problem, and simplify lookups.

**Comment by jennyhavah** [comment]
@camgnostic Can I get some guidance on how to thoroughly test this one?
