### ISSUE TITLE
Potential issue with Sites search

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#2049]
@jennyhavah, @camgnostic, The search feature on the Site listing page has always been, shall we say, less than useful.  However, with the elimination of results based on the admin levels, I'm concerned that there could be a perception that the search is functioning differently, when in fact it is pretty much functioning as expected.  The current search function searches site name, site type, all the admin levels (including office), and all the projects. The only things left after all the LevelUp deletions is site name and and type.  This could be perceived as a change to the search results.  I initially though there was something wrong with the system because I was getting only two results where I got a dozen before.  However, that's only because it's searching a reduced surface area. I'd like to propose two pretty easy changes to the site search functionality:

1.  Make the search case insensitive. 
2.  Allow it to search for countries along with site name and site type.  This way, if you search for e.g. "Nepal", you will get all of the sites in Nepal, provided you have access to Nepal as a country.  

I think these simple changes will make the search more useful and would be appropriate for the LevelUp release since the results of the search are already significantly affected by the loss of admin levels and projects.

**Comment by jennyhavah** [comment]
I think these are both great ideas, and turns what could be perceived as a negative into something positive. Only Afghanistan would have been searching by Projects, and are very likely going to switch over to using Sites on their Workflow installation, anyhow.

For everyone else, we're making it easier to search by name and type. We could even mention this in the release notes.

**Comment by jennyhavah** [comment]
Validated that site search is now case insensitive, and that I can search by country. Will add to release notes!
