### ISSUE TITLE
Add "no data" message to site indicator data page

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#2050]
If you click on the "Indicator data" link on the sites listing page, and there is no indicator data, the result is just a blank page with a header that provides the site name.  @jennyhavah Would it make sense to put some default text in there, something like "There are no Indicators/Results linked to this site."?

**Comment by jennyhavah** [comment]
Great idea to put some default text in there, Sanjuro. How about: There is no indicator data for this site.

That way we're consistently using the phrase "indicator data" and are not implying a direct relationship between indicators and sites.

**Comment by jennyhavah** [comment]
Boom.

![image](https://user-images.githubusercontent.com/33670923/69761145-5bca5f80-111b-11ea-8d33-3d8880fa50f0.png)
