### ISSUE TITLE
Prevent users from opening result form in a separate tab or window

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2053]
# Issue

Right now, it is possible to open the result form in a new tab or new window. The form you see is totally unstyled, like so: 
![image](https://user-images.githubusercontent.com/33670923/69768663-40b91900-1136-11ea-9267-e519cab5601b.png)

This is problematic not not only because it's visually unappealing but because it's not a functional page; the logic around auto-assigning target periods is not preserved, etc. As far as I can tell, it's not possible to submit a result from here. But it would better to simply prevent people from getting here in the first place.

# Acceptance criteria

- [x] 1. If I attempt to open the result form in a new tab, I'm redirected to the program page, similar to how it behaves when I attempt to open the indicator modal in a new tab.

- [x] 2. If I attempt to open the result form in a new window, the window opens, but redirects immediately to the program page -- again, similar to the behavior when I try to open the indicator modal in a new window.

**Comment by jennyhavah** [comment]
I decided to add this to Goat Tree rather than tossing it into the overflowing bin that is Poblano. It's arguably relevant, as much of the work we're doing involves results entry.

**Comment by axoplasm** [comment]
It looks like PR #2154 fixes this **BUT** could we *also* open the results modal on the new page when it loads? If I intend to open the results modal in a new window (for example: to enter related results from a single source, for several indicators at once), having it explicitly *not do this* would be really frustrating.

**Comment by camgnostic** [comment]
Pinging @jennyhavah for design thoughts

**Comment by jennyhavah** [comment]
@axoplasm @camgnostic I have some concerns with allowing results to be opened in a new tab.

1. It becomes less obvious what is going to happen when you submit, and potentially introduces new complexity. What would I expect to happen if I edit or add a new result and then submit? Would I get a confirmation message and then have to navigate somewhere? Would it be intuitive to be bounced back to the program page... even if I wandered off to lunch somewhere in between? What if I inadvertently opened the same result multiple times and tried to edit in one place and then came across one of the other tabs and thought my edit hadn't been saved? Etc. Etc. 

2. If I recall correctly, all of the UI logic and validation was not carried over to the full-page version. For example, I think it lost some of the logic around auto-assigning periodic targets based on the result date. We'd need to go through all of the logic and potentially redo some of it, then QA it, etc. 

3. We definitely want to make it more efficient to enter multiple results from similar data sources. But I don't think opening the result form in multiple tabs accomplishes that. What we really need to do is 🔥the pop-up entirely and replace it with an editable IPTT -- the ability to tab across cells, bulk-apply shared values, etc. That's what we'll be tackling in Swift.

For these reasons, my preference is still to prevent opening results in new tabs, and then take a totally different approach with Swift and do it _right._

**Comment by axoplasm** [comment]
Approved the PR (#2154)

**Comment by jennyhavah** [comment]
I can no longer open the result form in a new tab or window. 

@axoplasm I can still see the form briefly in some cases, but it quickly goes away. I do wonder if on a really slow internet connection, someone might start trying to fill it before it bounces you to the program page. Not sure what, if anything, can be done about that.

**Comment by jennyhavah** [comment]
@axoplasm Yoohoo!

**Comment by axoplasm** [comment]
@jennyhavah I might need you to demonstrate this, as I can’t replicate it.

**Comment by jennyhavah** [comment]
Ok, will move to Failed for now just to get it out of my queue, then show you next time we're both in the office. I'm holding down the ctrl key and selecting "Open in new Tab/Window." In both cases, I'll see the unstyled form for somewhere between 1-2 seconds, before it bounces me back to the program page.

@axoplasm  If I do the same thing with the gear icon, the browser window goes blank for a second before I'm taken to the program page. I never see the indicator form.

If it's a low LOE, I'd like to replicate whatever we're doing there.

**Comment by jennyhavah** [comment]
@camgnostic Paul thought that you might have an idea how to tackle this with a minimal LOE. Can you let me know? Again, I do NOT consider this high priority, so if it's more than 15 minutes or so, I'm okay letting it go.

**Comment by camgnostic** [comment]
I think I might know a quick way to do it, I'll look at it today

**Comment by camgnostic** [comment]
@jennyhavah  I _think_ what @axoplasm  was advocating for [here](https://github.com/mercycorps/TolaActivity/issues/2053#issuecomment-578936337) was for the redirect to the program page just like the ticket specifies, but to have that program page already have the results form open on it.  So I click "open in new tab" on "add new result" under indicator X, and what I get is a new tab with the program page, indicator X expanded, and the result form open (which I think answers at least points 1 and 2 from your response [here](https://github.com/mercycorps/TolaActivity/issues/2053#issuecomment-578970324).  

Either way, I've addressed the speed issue, and we can definitely circle back to the "what to do on the program page you are redirected to" issue if we need to later.

**Comment by jennyhavah** [comment]
@camgnostic I interpreted Paul's suggestion as allowing the form, by itself, to be openable and editable in a new tab or window, as a full-page experience. I'm more comfortable with your suggestion, _but_ it would still require extra testing, etc. and I'm not 100% sure it would meet user expectations. It's possible they're actually expecting and hoping that the form will open as a full page on its own.

If we were planning to keep this form long term, I'd want to explore this more. But given that we're about to 🔥that form entirely as part of Swift Results, my inclination is to just address the speed issue for now, so that users are less likely to see the unstyled page while waiting for the redirect.

**Comment by camgnostic** [comment]
👍 - implemented on QA with a mild improvement to speed.  There is a medium LoE improvement I could add on top if this is still too slow (I'm getting about .5s of visible form before it redirects) - the improvement involves checking in the back-end whether it's a full-page or async request - but it's more than the 15min timebox, so I'm moving the current fix to Acceptance Testing for your review.

**Comment by jennyhavah** [comment]
This is good enough! This is an edge case, so no need to optimize for speed. My main concern was that I was seeing the unstyled page in the meantime. That is no longer the case.
