### ISSUE TITLE
New disaggregations don't show up on saved results as soon as a single disaggregated value is entered

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2054]
# Issue 

It is sometimes the case that new disaggregations are added after a program begins collecting results. In that case, it may be necessary to return to saved results and add some new disaggregated values to them.

Right now, if I select a new disaggregation in the indicator setup form, the following things are true:

1. The new categories show up under Custom Disaggregations for any saved results that do NOT have disaggregated values entered.

2. For any saved results that DO have at least one disaggregated value entered, the new categories do not show up.

# Acceptance criteria

- [x] It is possible to add a new disaggregation and have the categories show up in all saved results.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by camgnostic** [comment]
Labeled Low as this should already be in place with other updates to disaggregations (just requires verification and tests to prevent regression)

**Comment by jennyhavah** [comment]
Steps taken to test:

1. Added a new disaggregation to a saved indicator with results.
2. Opened up a saved result.

The new disaggregation shows up as expected.
