### ISSUE TITLE
Indicator setup form: Help link to Form Guides is missing.

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2059]
I noticed that the "Help" link is missing in the lower right corner of the indicator setup form. Here's a screenshot from Prod.

![image](https://user-images.githubusercontent.com/33670923/70950992-05b05400-2017-11ea-8701-658c870efe76.png)

Sanjuro poked at it real quick and found this related commit: https://github.com/mercycorps/TolaActivity/commit/586df24acaa8df12f1b10a35b484d0884e89e42f#diff-6148caa7524916dd87fc7ce6e8ed60c2

**Comment by camgnostic** [comment]
added help text link back into indicator setup form to match production

**Comment by jennyhavah** [comment]
Cameron validated this and I also did a quick check -- the link worked in all 3 languages.
