### ISSUE TITLE
Indicators page: Data/evidence tables displayed before target values are submitted

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#206]
# Issue
If you close out of the target setup form without completing the process, you get unexpected and potentially misleading system feedback on the Indicators list page.

# Affects the following target frequencies
- Annual, semi-annual, tri-annual, quarterly, monthly
- Event

# To reproduce
1. Find an indicator that has no targets set up, with messaging and instructions like so:
![image](https://user-images.githubusercontent.com/33670923/42708365-ee836f94-8691-11e8-89dd-09aed218455b.png)
1.1. **Note:** This messaging appears when you create a new indicator and don't complete your targets, or if you already have targets set up, delete them all, and then close the window instead of adding new targets.
2. Click the _Create targets_ button.
3. Choose any of the affected target frequencies
3.1. If you choose _Event_, fill out the first event name and quantity fields
4. Click the _Create targets_ button.
5. Close the window _without doing anything else._

## Expected behavior
I see the original messaging and instructions because I intentionally backed out of the process of setting up targets. (We can assume that sometimes users will not complete the target setup process, whether it's intentional or unintentional.)

## Observed behavior
This is what I see:
![image](https://user-images.githubusercontent.com/33670923/42708880-6dfc4a4c-8693-11e8-971c-28e1de03f0b4.png)

The system displays a results table with only the LoP target row and no intermediate targets. If you reload the page, you do see the expected messaging and instructions.

While nothing may technically be wrong, this experience may be confusing or scary to users who aren't aware of the system logic; they may worry that the system saved target preferences that they didn't intend to save.

**Comment by jennyhavah** [comment]
For Midline/Endline and Event target frequencies, I'm seeing some unexpected behavior.

On Production, if I delete all my targets and close out, the Indicator page shows me one of two variations of the feedback that I have no targets (depending on whether or not I already have data records).

On Dev, there is no visible system feedback when I close out -- my old target periods remain and I don't get the message that I need to set up targets.

**Comment by jennyhavah** [comment]
The above issue was fixed. But now the original problem is back. I tested both Annual and Semi-annual, and I'm seeing the table depicted under "Observed behavior" above.

**Comment by mahmoodkhan** [comment]
OK. will look into it.

**Comment by jennyhavah** [comment]
Can no longer reproduce. Looks like I just forgot to close the ticket.
