### ISSUE TITLE
Check all form field types and pNotify rationale prompts for transparency 

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2078]
Rather than me filing individual tickets, I'm wondering if you could first do a sweep and make sure all form fields that should stay white when typing, do so?

Some I've noticed so far:

Textarea boxes go transparent when I start typing:

![image](https://user-images.githubusercontent.com/33670923/71496201-e7acd580-2806-11ea-8aca-afdcfddc54e1.png)

Pnotifys go transparent when I start typing:

![image](https://user-images.githubusercontent.com/33670923/71496196-dc59aa00-2806-11ea-9d65-c9dacb0e22f3.png)

**Comment by camgnostic** [comment]
I undid the global change that caused this and made a much more narrow slice change to just expando links (to remove white background on focus) this should revert these fields.  I've done a sweep for all fields in indicator setup, results framework, and result form, and pNotify's in each place.  All looks good now.

**Comment by jennyhavah** [comment]
Passed. No longer seeing transparency in the rationale prompts...

![image](https://user-images.githubusercontent.com/33670923/71681459-9d18e500-2d41-11ea-9872-2865d3f17886.png)

![image](https://user-images.githubusercontent.com/33670923/71682213-ccc8ec80-2d43-11ea-8723-0224cb268c50.png)

... or in form fields:

![image](https://user-images.githubusercontent.com/33670923/71682243-e23e1680-2d43-11ea-8786-d7b12035b681.png)
