### ISSUE TITLE
Disaggregated values table: Styling/interaction tweaks

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2088]
Disaggregation table needs a bit more attention to styling and interaction details.

## Remove type-ahead suggestions

- [x] 1. Please remove type-ahead suggestions from the disaggregated value fields. (It doesn't make sense for the system to "remember" values here, and we don't do this in the Actual value field.)

![image](https://user-images.githubusercontent.com/33670923/71683170-a3f62680-2d46-11ea-9432-c23164d57b65.png)

## Styling

![image](https://user-images.githubusercontent.com/33670923/71683215-c0925e80-2d46-11ea-8d96-a82564e7efe3.png)

- [x] 1. Formatting of disaggregation table should generally mimic formatting of target table in terms of padding, consistent line thicknesses, shades of gray, etc. 

I also prefer the target table's open rows with horizontal lines above and below but not on the sides. Right now the disagg table has boxes drawn around the rows.

Here's what I'm seeing now:

![image](https://user-images.githubusercontent.com/33670923/71690551-e5440180-2d59-11ea-98b3-bd7baf19ee24.png)

versus the target table:

![image](https://user-images.githubusercontent.com/33670923/71690567-f42ab400-2d59-11ea-800a-6af04702e652.png)

## Styling of deltas

- [x] 1. Sum number is out of alignment with the other numbers in the column and should be bold. Here's what I'm seeing now:

![image](https://user-images.githubusercontent.com/33670923/71691828-36092980-2d5d-11ea-89d6-968e0fc8a45b.png)

Versus the mockup: 

![image](https://user-images.githubusercontent.com/33670923/71691877-55a05200-2d5d-11ea-90c8-5c29ca6aa288.png)

**Comment by axoplasm** [comment]
@jennyhavah:

> Formatting of disaggregation table should generally mimic formatting of target table in terms of padding, consistent line thicknesses, shades of gray, etc.

These tables are drawn by two completely different methods (targets are a `<table>` with a bunch of custom classes, disaggregations are a `list-group`). We should refactor them to use the same markup. Markup-wise they are a tossup, so don’t worry about which method is better. Focus on _appearance_. (Of course this will cause some functionality to break, _Because Javascript_. I have adjusted LoE accordingly)

So the question is: 

__for all places that we render a table with inputs, do you prefer such elements look like:__

- the targets table
- the disaggregated results table

**Comment by axoplasm** [comment]
To answer ^^^, Jenny prefers the appearance used by the `list-group` method!

**Comment by axoplasm** [comment]
FFR this refactor breaks the custom event labels:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/169060/74055814-9e1ee100-4995-11ea-9a48-b85271537fa8.png">

**Comment by jennyhavah** [comment]
> FFR this refactor breaks the custom event labels:

@axoplasm Do we need a new ticket for this or will it be addressed in another ticket?

**Comment by axoplasm** [comment]
working on it now

**Comment by jennyhavah** [comment]
@axoplasm Seeing some dramatic styling issues with percentage indicators. 

![image](https://user-images.githubusercontent.com/33670923/74263859-7640bd80-4cb4-11ea-995c-7d648432f5aa.png)

In addition to the alignment issues, I notice what appears to be arbitrary thick gray lines in the table -- for both # and % indicators. It is affected by zoom level. BUT, I don't see this problem with the IPTT thick lines -- it's consistently placed and not affected by zoom level.

![image](https://user-images.githubusercontent.com/33670923/74263974-b6a03b80-4cb4-11ea-9166-0ed594c2d04c.png)

**Comment by axoplasm** [comment]
I have fixed the width & percentage symbol issues on the results modal: 

![image](https://user-images.githubusercontent.com/169060/74276491-ad21ce00-4cca-11ea-80eb-8fb39577637d.png)

 … do we have this anywhere else?

**Comment by jennyhavah** [comment]
@axoplasm The targets table, if you select % under the indicator name.

**Comment by axoplasm** [comment]
In re: the extra width borders at non-100% zoom levels, this is a bug (sort of…) in Bootstrap’s `list-group` utility. It sets a 1px negative bottom margin (see screenshot). When you zoom out (for example) to 90% you change this margin to 0.9px ([a pixel is not a pixel](https://www.quirksmode.org/blog/archives/2010/04/a_pixel_is_not.html) … but border widths are (generally) *not* affected by browser zoom. This is a weird mix of things that I’m a little worried about trying to “fix” this as it might introduce other display bugs elsewhere.

![image](https://user-images.githubusercontent.com/169060/74276987-99c33280-4ccb-11ea-94f7-3215bebcbc64.png)

**Comment by jennyhavah** [comment]
> In re: the extra width borders at non-100% zoom levels, this is a bug (sort of…)

@axoplasm Agree, let's not address the "extra width borders" in this ticket.

**Comment by jennyhavah** [comment]
@axoplasm The width of the numeric field grows when an error message is present. This happens in both Chrome and Firefox.

![image](https://user-images.githubusercontent.com/33670923/74558746-b2c02380-4f17-11ea-9c78-94b933a0bb45.png)

**Comment by jennyhavah** [comment]
@axoplasm You mentioned above that you updated the target table to match the styling of the disaggregated values table. I'd like to request some styling refinements to get the new version closer to production. Specifically:

- [ ] Move the "x" buttons closer to the left edge, approximately the same amount of padding as there is between the right edge of the number field and the right edge of the table.

- [ ] Lengthen the event name field relative to the number field.

- [ ] Reduce space between the event and number fields.

Here's how it looks on Prod:

![image](https://user-images.githubusercontent.com/33670923/74559241-c61fbe80-4f18-11ea-8da4-3e71cb06a4ae.png)

Here's what I'm seeing on QA:

![image](https://user-images.githubusercontent.com/33670923/74559323-f8c9b700-4f18-11ea-92b9-a922d11f7d2d.png)

**Comment by jennyhavah** [comment]
@axoplasm Can you please reduce the amount of padding between the disaggregation header and the table below? Like, roughly half the amount of padding? This way, when there are parallel disaggregations, it'll be more visually obvious which table is linked to which header.

![image](https://user-images.githubusercontent.com/33670923/74559532-886f6580-4f19-11ea-8649-ca953a461979.png)

**Comment by axoplasm** [comment]
>  The width of the numeric field grows when an error message is present. This happens in both Chrome and Firefox.

I've fixed the widths of those inputs so they are uniform across visually similar forms. This kind of fixes this issue, but the tradeoff here is that error messages will be constrained to the width of the input:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/169060/74574810-b369b180-4f39-11ea-8d97-c2bc891e89e7.png">

OTOH I'm not sure how often *this exact error* will display, with our new localized numeric input. I had to hack the DOM a bit to make the screenshot above

**Comment by jennyhavah** [comment]
@axoplasm This error could appear frequently if people are moving between fields, cutting/pasting, etc. So I'd suggest making the number field wider -- even doubling it -- so that the error message doesn't wrap to 4-8 lines depending on the language.

Will that throw off the target setup table? Are we limited to one set of proportions across all forms that use this table style?

**Comment by axoplasm** [comment]
The remaining issue here is whether I should remove *from the code* the hint text for the condition where a user enters a single `.` or `,` in the new numeric field. @camgnostic I believe you have updated this error handling, so that such input will delete silently? And @jennyhavah, do we still need this text, if it's not possible enter any non-valid numeric data into one of the new number fields?

**Comment by jennyhavah** [comment]
> And @jennyhavah, do we still need this text, if it's not possible enter any non-valid numeric data into one of the new number fields?

@axoplasm If it's no longer possible to enter a non-valid numeric value into that field, I see no reason to keep the error message text in the code -- as long as it isn't being used anywhere else.

**Comment by jennyhavah** [comment]
@camgnostic As discussed on Slack: When I submit a result without disaggregating it, I’m getting prompted to “fix” the disaggregations… Even though they’re not supposed to be required. To reproduce:

1. Click "Add result" under any indicator's results table.
2. Fill in a result date and actual value but don't disaggregate the result.
3. Hit Submit.

Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/33670923/74791686-0e6c1300-5270-11ea-8bb4-e5433a00aa98.png)

**Comment by camgnostic** [comment]
Re: last comment - a recent update changed the return for a blank cell from `false` to `null` and that needed to be followed through to the validation here.  Addressed in PR #2225

**Comment by jennyhavah** [comment]
@camgnostic It's now letting me save results without any disaggregation. But I found an odd edge case I'm having trouble replicating so far... I made some edits to disaggregated values and then submitted. First I saw this -- note the red outline around one box and the message saying values don't add up... but there's no "update value to match" option in the sum row.

![image](https://user-images.githubusercontent.com/33670923/74859340-a6630e80-52fb-11ea-825c-0de342828fbd.png)

I then tried clearing out all values, submitting, and got the same red outline around one particular field and a message about reconciling values even though there are no longer any to reconcile.
![image](https://user-images.githubusercontent.com/33670923/74859362-b4189400-52fb-11ea-9f1a-8fd36869f342.png)

I experienced this with the 8 Jan value for the very first indicator listed in QA - Jenny
![image](https://user-images.githubusercontent.com/33670923/74859772-68b2b580-52fc-11ea-9cc9-ad4f73a18595.png)

Again, can't seem to reproduce the steps but thought you might have some idea of what's happening?

**Comment by camgnostic** [comment]
I have put a check in place to make sure than any cell that looks blank is made actually blank for counting - it looks like a rounding error happened because the values we're tracking (the actual numbers) and the values we're displaying (with , or . depending on language) diverged.  Put checks in to prevent this and tried many routes to recreating (could not recreate)

**Comment by jennyhavah** [comment]
All issues resolved.
