### ISSUE TITLE
Update UI of Indicator creation page and editing modal for Bootstrap 4

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#209]
Update the [Indicator creation page](http://localhost:8000/indicators/indicator_update) and the Indicator modal subsequent to the Bootstrap 4 migration and to be consistent with some new design templates.

## Summary tab
![indicatormodalsummarytab](https://user-images.githubusercontent.com/33670923/39487922-8e107e76-4d35-11e8-99cd-fdba950c552f.png)

## Targets tab empty state
![indicatormodalemptystate](https://user-images.githubusercontent.com/33670923/39607903-b50e8bb2-4ef2-11e8-88b9-442b712632c1.png)

## Targets tab -- ready to create targets
![indicatormodalreadytocreatetargets](https://user-images.githubusercontent.com/33670923/39607907-ba9676b2-4ef2-11e8-8093-f27b475e4cf1.png)

## Targets tab -- targets created
![scenario1noncumulativenumber](https://user-images.githubusercontent.com/33670923/39607912-c2277462-4ef2-11e8-876d-6f431f959d6b.png)

**Comment by sanjuroj** [comment]
## **Changes needed:**

### Summary Tab
- [ ] 1.  space between title and menu
- [ ] 2. Boldness of the title.  color of title.
- [ ] 3. Low priority:  remove rounded fields everything except dropdowns
- [ ] 4. change footer background grey color to DBDCDE
- [ ] 5. All caps for buttons
- [ ] 6. Horizontal spacing between buttons in footer
- [ ] 7. readonly program field should be like bootstraps
- [ ] 8. bold the input labels and get to the right shade of grey 54585A
- [ ] 9. on target tab confirm grey is f5f5f5 and remove border from the fieldsets
- [ ] 10. remove breadcrumbs
- [ ] 11. see about tabs becoming a dropdown if the screen is narrow
- [ ] 12. make tabs on indicator page responsive
- [ ] 13. different mouseover state for buttons

### Performance tab
- [ ] 1. update the multiselect 
- [ ] 2. how is the height of the multiselect boxes set

### Targets tab
- [ ] 1. responsiveness of LOP direction of change cuts off text
- [ ] 2. alignment of labels are aligned right when the window is narrowed enough for them to stack.  They should be aligned left in that case.
- [ ] 3. Get rid of success message when targets successfully created

### Footer:
- [ ] 1. all caps
- [ ] 2. more vertical space for the grey box

### Indicator name:
- [ ] 1. Indicator name should not be bold
- [ ] 2. close modal "X" should be equidistant from the side and top
- [ ] 3. different icon for close modal
- [ ] 4. Multiselect isn't using the modal jenny found, are we replacing it? 
- [ ] 5. If the widget is right, then improve styling

**Comment by sanjuroj** [comment]
## **Changes needed for the modal indicator edit:**

### Summary Tab
- [ ] 1.  space between title and menu
- [ ] 2. Boldness of the title.  color of title.
- [ ] 3. Lower priority:  remove rounded fields everything except dropdowns
- [ ] 4. change footer background grey color to DBDCDE
- [ ] 5. All caps for buttons
- [ ] 6. Horizontal spacing between buttons in footer
- [ ] 7. readonly program field should be like bootstraps
- [ ] 8. bold the input labels and get to the right shade of grey 54585A
- [ ] 9. on target tab confirm grey is f5f5f5 and remove border from the fieldsets
- [ ] 10. remove breadcrumbs
- [ ] 11. see about tabs becoming a dropdown if the screen is narrow
- [ ] 12. make tabs on indicator page responsive
- [ ] 13. different mouseover state for buttons

### Performance tab
- [ ] 1. update the multiselect 
- [ ] 2. how is the height of the multiselect boxes set

### Targets tab
- [ ] 1. responsiveness of LOP direction of change cuts off text
- [ ] 2. alignment of labels are aligned right when the window is narrowed enough for them to stack.  They should be aligned left in that case.
- [ ] 3. Get rid of success message when targets successfully created

### Footer:
- [ ] 1. all caps
- [ ] 2. more vertical space for the grey box

### Indicator name:
- [ ] 1. Indicator name should not be bold
- [ ] 2. close modal "X" should be equidistant from the side and top
- [ ] 3. different icon for close modal
- [ ] 4. Multiselect isn't using the modal jenny found, are we replacing it? 
- [ ] 5. If the widget is right, then improve styling

**Comment by sanjuroj** [comment]
@jennyhavah I think this is ready for testing now.  There are a few remaining items that have been moved to their own stories:
- Overall form responsiveness needs improvement (#247)
- Tabs layout on small screens still not good (#229)
- Periodic target spacing and dates need some work (#267)
- Selected radio button color needs to be done (#244)

As you find stuff to change, if you want to add checkboxes to the comment with checkboxes, feel free.  Or whatever you way you prefer to document the required changes.

**Comment by jennyhavah** [comment]
Page title (Indicator setup) and both page title and indicator name styling appear to be different depending on whether you're in the modal or full page version:
![image](https://user-images.githubusercontent.com/33670923/40089691-e8aeaf6a-5861-11e8-96fb-4442f8530e85.png)

**Comment by jennyhavah** [comment]
Since we've made the global background gray, we need to add a white background to the tabular area -- see red box outline:
![image](https://user-images.githubusercontent.com/33670923/40089914-3f19210e-5863-11e8-8479-b245fdf879c4.png)

**Comment by jennyhavah** [comment]
> 3. Get rid of success message when targets successfully created

Not sure what this refers to -- I still see success messages and that's fine. However, I am rethinking our decision to not bounce people to the top after saving changes on this form. Seeing it in practice, while it _was_ annoying to have to scroll down again after saving, it's more problematic from a usability standpoint not to have any visible system feedback at all when you hit Save Changes. 

Ultimately we need to move the messages to the bottom. But for now, can you please restore the behavior in production where clicking Save changes does take you back to the top so that you see the success message?

**Comment by jennyhavah** [comment]
Please add a space between the word "target" and the percent sign.
![image](https://user-images.githubusercontent.com/33670923/40090635-dbca26a2-5867-11e8-961f-514eceda67a8.png)

**Comment by jennyhavah** [comment]
Just noticed this discrepancy. If it takes less than 15 minutes, please round the corners of the box underneath the target table in both # and % flavors. This helps to visually differentiate it from the table.

Here's how it looks in the mockup:
![image](https://user-images.githubusercontent.com/33670923/40090770-bb64579c-5868-11e8-8785-be575d12fa08.png)
