### ISSUE TITLE
Indicator setup > Disaggregation selection > UI tweaks

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2091]
This ticket is branched off #1213.

Some additional UI refinements:

![image](https://user-images.githubusercontent.com/33670923/71496354-c7c9e180-2807-11ea-8d6c-7ebb316a99ad.png)

- [x] 1. Add space between global and country level disaggregation "clusters".

- [x] 2. Add space between Disaggregation and Type fields.

- [ ] 3. Add border and scrollbar to disaggregation list, so it's more obvious that it's a scrollable list. The original mockup has the thing partially obscured by the tooltip. Here's a mockup without the tooltip so you can see everything more clearly:

![image](https://user-images.githubusercontent.com/33670923/71496434-22fbd400-2808-11ea-84b9-74136cce6e87.png)

---

**Reminder to keep an eye on:** 

- [x] Even if I am a Low/Medium access user without permission to edit disaggregations, I should still be able to scroll the list and see the current selection/s.

**Comment by axoplasm** [comment]
> Add border and scrollbar to disaggregation list, so it's more obvious that it's a scrollable list. 

We discussed this elsewhere (on #2096), & I think we decided not to style these. Here’s a basic attempt:

![image](https://user-images.githubusercontent.com/169060/73890372-ad335100-4826-11ea-868e-f02f282abfb8.png)

(note that, without some extra effort, disaggregations would have a border, regardless of whether they are scrollable or not)

**Comment by jennyhavah** [comment]
Yep! Here's the last comment I made on the subject, from #2096 

> Just chatted with Paul and he said it could be upwards of a day to make the shadowing only appear when the list is long enough to be scrollable.

> I find the shadowing useful only if it serves as a differentiator. If it shows up on all lists, not so much. However, I'm not convinced it's a big enough issue to warrant a day's worth of effort.

> Let's leave as is, with no shadow effect. If we get user feedback that the lack of scrolling affordance is bothersome, we can revisit in the future. Passing the ticket as is.

**Comment by jennyhavah** [comment]
Looks good. No border for now, but it's (hopefully) clear there's more to the list in the way the last visible disaggregation is cut off... Plus, it's alphabetized, so if someone is looking for a disaggregation that starts with "P", it follows that you'd need to scroll to get there.

![image](https://user-images.githubusercontent.com/33670923/74183681-4503b700-4bfa-11ea-92c6-748056ca824c.png)

When I login as mc-low or mc-medium, I can't edit but can still scroll:

![image](https://user-images.githubusercontent.com/33670923/74183842-9ad85f00-4bfa-11ea-8308-4d1e6661695a.png)
