### ISSUE TITLE
Indicator dialogue > Targets > Life of Program field is required

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#21]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Thursday Dec 14, 2017 at 00:37 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/11_

----

**User stories:** 
1. When configuring an indicator, I should be required to enter a Life of Program (LoP) target because it is an essential value for calculating progress in indicator tracking reports. 
2. When I enter a LoP target, the system should only accept a numeric value so that it can be used for calculations.
3. As a new user to Tola, I should not be expected to know what LOP means.

**Background:** A LOP field already exists in the Targets tab, but it is optional and accepts non-numeric values. LOP is not a familiar acronym outside of Tola.

**ACCEPTANCE CRITERIA**
1. The Life of Program target is required.
1.1. The field label is "Life of Program (LoP) target" instead of "LOP Target".
1.2. An asterisk identifies the field as required.
2. The field only accepts a numeric value. It does not accept letters or special characters such as %.
2.1. If you attempt to save with a non-numeric value, you receive a prompt near the field, "Please enter a number."
2.2. Any existing Life of Program value that does not meet the criteria is preserved.
2.3. However, if you attempt to edit a non-numeric LoP value, you are only allowed to replace it with a numeric value.
3. If you attempt to save without completing the Life of Program, you are prompted: "Please complete this field."

![loprequired](https://user-images.githubusercontent.com/33670923/33969739-d3e87f54-e023-11e7-8db7-6b4dfdfa0886.png)

**Comment by jennyhavah** [comment]
Based on a review of existing LoP targets, I'd like to be a bit more verbose with this error message:
> The field only accepts a numeric value. It does not accept letters or special characters such as %.
2.1. If you attempt to save with a non-numeric value, you receive a prompt near the field, "Please enter a number."

Can we change that to: "Please enter a number. If your target is a percentage, describe it in the unit of measure field.”

**Comment by kurtwall** [comment]
Dropping this note to indicated I have reviewed this issue for potential test cases.

**Comment by jennyhavah** [comment]
![image](https://user-images.githubusercontent.com/33670923/35413239-a1ad59d4-01d3-11e8-8ab0-4d634595d007.png)

@mahmoodkhan We have feedback that this message is too jargony. Please change to: Please enter a number larger than zero with no letters or symbols. If your target is a percentage, describe it in the unit of measure field.
