### ISSUE TITLE
Update http links to https

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#2101]
There is at least one link (cartodb) that is linked as http rather than https, which is raising a warning in the browser console.  This link should be updated and the site should be checked for other http links.

**Comment by jennyhavah** [comment]
@sanjuroj I'm assuming you're the best person to acceptance test this one. Let me know if I can help, and how.

**Comment by sanjuroj** [comment]
PASSED.  Warning is gone from the console and a search of the codebase shows no significant use of http: (i.e. there's some in comments).
