### ISSUE TITLE
IPTT: Visually differentiate four columns with pale gray background

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2110]
# Issue

**Affects:** Both types of IPTT report -- target vs actuals and recent progress

There is a lack of visual differentiation between the columns of data that apply to the entire program, and those that apply to time or target periods. (We used to shade those columns in a pale gray, but that styling detail was lost somewhere along the way.) 

With the introduction of disaggregated data rows, this lack of visual differentiation becomes more pronounced, making it more challenging to scan the table.

# Acceptance criteria

![image](https://user-images.githubusercontent.com/33670923/72390393-7cf10a80-36df-11ea-8048-d572ee05b6d3.png)

- [x] 1. The following four columns under "Life of Program" should have a light gray background -- not as dark as the result level rows.

     - [x] 1.1. Baseline

     - [x] 1.2. Target

     - [x] 1.3. Actual

     - [x] 1.4. % Met

- [x] 2. All of the above updates are applied to both type of IPTT -- Target vs Actuals and Recent Progress.

**Comment by jennyhavah** [comment]
@axoplasm FYI, I just removed a criteria related to right-aligning a column and added it to a new ticket that's all about alignment -- #2116.

**Comment by axoplasm** [comment]
I believe I fixed this incidentally with #2116 in commit 858cb53c2

**Comment by jennyhavah** [comment]
@axoplasm I can't see any gray shading. Here's what I'm seeing: 

![image](https://user-images.githubusercontent.com/33670923/73412739-7907df80-42be-11ea-82f0-a892e7896dcb.png)

**Comment by axoplasm** [comment]
@jennyhavah This might be in between states right now bc of work around #2141. I'll show you on my machine where it's headed

**Comment by axoplasm** [comment]
I think this was fixed with #2141: 

![image](https://user-images.githubusercontent.com/169060/73684113-5e47b900-4678-11ea-9af3-4ab667d2e747.png)

**Comment by jennyhavah** [comment]
I see the shading now. Looking good!

![image](https://user-images.githubusercontent.com/33670923/73684281-b383ca80-4678-11ea-9f78-7d66e15a9fb8.png)

**Comment by axoplasm** [comment]
In dealing with #2141 (rebuilding the IPTT <table>), it might make sense to move the Baseline column out of the LoP group. This will reduce the number of column groups where we have to maintain accurate column counts, and simplify development.

**Comment by jennyhavah** [comment]
> In dealing with #2141 (rebuilding the IPTT <table>), it might make sense to move the Baseline column out of the LoP group. This will reduce the number of column groups where we have to maintain accurate column counts, and simplify development.

I have no issues with moving the Baseline column out of the LoP group that has background shading.
