### ISSUE TITLE
Clean up styling of the Expando / Collapso row

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2112]
This is a styling ticket that came out of the expando-collapso portion of #1865 

# Issue

**Affects: ** Both types of IPTT, all time and target period variations

The header rows of the IPTT got jostled around with the introduction of the Expando-collapso widget. The widget itself needs styling as well.

# Acceptance criteria

- [x] 1. Style the expando-collapso widget to look more consistent with expando-collapsos elsewhere (results framework, change log) and tweak the alignment.

     ![image](https://user-images.githubusercontent.com/33670923/72391403-df4b0a80-36e1-11ea-864c-a819b760ab8f.png)

- [x] 2. Vertically re-align time/target period names and date ranges (where applicable) so that there is not a white rectangle in between them and the table row with all the column headers in it. I've taken screenshots of all the permutations below.

### Time period with date range

This issue occurs with all time period options options except for Months

![image](https://user-images.githubusercontent.com/33670923/72391081-1a007300-36e1-11ea-86dc-e762d4bd5ab0.png)

### Months 

Reminder: For months, we intentionally do not display the date range.

![image](https://user-images.githubusercontent.com/33670923/72390971-dad22200-36e0-11ea-8fbc-32a14b8d3f68.png)

### LoP only

![image](https://user-images.githubusercontent.com/33670923/72390906-b9713600-36e0-11ea-9a43-6631b4d39f02.png)

### Midline/Endline

![image](https://user-images.githubusercontent.com/33670923/72390869-a65e6600-36e0-11ea-8670-086131e942b7.png)

### Time-aware target frequencies

This applies to all time-aware target frequencies except for months.

![image](https://user-images.githubusercontent.com/33670923/72391140-3b615f00-36e1-11ea-868e-904ef5ed9b8b.png)

### Months

Reminder: For months, we intentionally do not display the date range.

![image](https://user-images.githubusercontent.com/33670923/72391195-59c75a80-36e1-11ea-9079-343808a775bf.png)

**Comment by axoplasm** [comment]
I think the second criterion was fixed incidentally with #2141

**Comment by jennyhavah** [comment]
Looks great. Here's what I see when all rows are collapsed:

![image](https://user-images.githubusercontent.com/33670923/74183383-b2631800-4bf9-11ea-8cfa-7fe15525e602.png)

And expanded:

![image](https://user-images.githubusercontent.com/33670923/74183412-c0189d80-4bf9-11ea-8ae1-904ff6ffb037.png)
