### ISSUE TITLE
Add disaggregated data to Tolaland programs for QA purposes

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2113]
**Affects:** All Tolaland programs except for:

- No Indicators Here
- No Results Here
- No Targets Here
- Pre-Satsuma

# Issue

It will be time-consuming to submit enough disaggregated data to test various scenarios, and it would need to be redone each time we refresh the database.

# Acceptance criteria

- [x] 1. Tolaland has two country level disaggregations (to easily test the new disaggregations filter). They should NOT have "Selected by default" checked.

- [x] 2. For each program, some indicators have the country disaggregations selected. 

     - [x] 2. 1. Some have ONE of the two country disaggregations selected.

     - [x] 2.2. A few indicators in each program have BOTH country disaggregations selected.

     - [x] 2.3. Some have NEITHER selected.

     - [x] 2.4. A variety of indicator configurations are represented in the indicators that have the disaggregation selected -- # / %, cumulative / non-cumulative, different target frequencies including LoP-only, Midline/Endline, and Event.

- [x] 3. Some indicators have disaggregated results.

     - [x] 3.1. Some should only have SADD disaggregations while others have parallel SADD and country level disaggregations.

     - [x] 3.2. For # indicators, the disaggregated values should add up to the total result value (since you can't submit it otherwise.)

     - [x] 3.3. For some of the indicators, there should be more than one result per target period.

**Comment by sanjuroj** [comment]
Few questions for you @jennyhavah.
1.  Is the exclusion of a few programs from this request intentional (i.e. you want some programs where results aren't disaggregated at all)?  Or is it just to save work.  If the latter, It's actually easier to apply it to all programs.
2. Cameron has already done some work on the script and has included a pre-Goat Tree disaggregation, which seems like a good thing to test.  Do you want to have this in the mix? If so, should the total country level disaggregations still be 2?  Or bump it up to 3?
3. When only a portion of the disaggregations are used, I've picked the one to use randomly.  Is that ok?
4. How would you like to apportion the result value across disaggregation?  Evenly?  Randomly?  All categories?  Only some?

**Comment by jennyhavah** [comment]
> Is the exclusion of a few programs from this request intentional (i.e. you want some programs where results aren't disaggregated at all)? Or is it just to save work. If the latter, It's actually easier to apply it to all programs.

- I excluded No Indicators Here, No Results Here, and No Targets Here because I assume we don't currently have results in the database for these programs and so it didn't make sense to request disaggregated results data.
- I excluded Pre-Satsuma only because I thought it'd be extra work. If it's not, then by all means let's include it!

> Cameron has already done some work on the script and has included a pre-Goat Tree disaggregation, which seems like a good thing to test. Do you want to have this in the mix? If so, should the total country level disaggregations still be 2? Or bump it up to 3?

Do you mean a Pre-Goat Tree program similar to Pre-Satsuma? That sounds great. I'm having trouble visualizing what this looks like exactly, so why don't we go with whatever Cameron implemented as a starting point, and if I have additional requests, I'll add another comment to this ticket or file a separate ticket.

> When only a portion of the disaggregations are used, I've picked the one to use randomly. Is that ok?

Yep.

> How would you like to apportion the result value across disaggregation? Evenly? Randomly? All categories? Only some?

I'd prefer:
- Some, not all categories.

- Random, not all even. (By this I assume you mean that for a result of 10, some would have 3 and 7, others 2 and 8, 9 and 1, 10 and 0, etc. It's fine for some to have 5 and 5 if it occurs randomly, but don't want them all to be split equally in this way.

- Some of the entries should be zero. (Again, doesn't mean I want all categories filled. I'll want to test that we're allowing users to enter zero in a disagg category AND leave a disagg category empty, even within the same result.)

**Comment by jennyhavah** [comment]
Passed and very helpful!
