### ISSUE TITLE
Fix alignments and dashes in disaggregated data columns

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2116]
# Issue

Having trouble scanning disaggregated data in the IPTT because of (what appear to be) the mismatched cell alignments. Also, noticed a discrepancy in dashes used for fields where there is no entered value.

# Acceptance criteria

![image](https://user-images.githubusercontent.com/33670923/72551383-9d3cd880-3849-11ea-9d39-45d89f914911.png)

## Alignments

- [x] 1. **# / %** column is consistently right-aligned.

- [x] 2. **Baseline** column is consistently right-aligned.

- [x] 3. **Target** column is consistently right-aligned.

- [x] 4. **Actual** column is consistently right-aligned.

- [x] 5. **% Met** column is consistently right-aligned.

## Dashes

- [x] 1. Dashes used to indicate "nothing entered in this field" are consistently the longer style of dash.

- [x] 2. When data is unavailable for a time or target period, we always display a long dash in the Target and % Met columns, in addition to the Actual column. (Right now we show it in the Actual columns but not the other two.)

![image](https://user-images.githubusercontent.com/33670923/72653215-ba070800-393e-11ea-8d27-3d44d8a170d5.png)

**Comment by jennyhavah** [comment]
@axoplasm This could be an optical illusion but it appears as though the # / % and Baseline **_table headers_** might still be left-aligned. (The rest of the columns are clearly right-aligned.)

![image](https://user-images.githubusercontent.com/33670923/73402028-3aaff780-42a1-11ea-8abd-05b5a742321f.png)

**Comment by jennyhavah** [comment]
Acceptance criteria #2 under "Dashes" is not done. @axoplasm let me know if you'd rather that be in a different ticket.

**Comment by axoplasm** [comment]
I believe this is fixed along with #2141:

![image](https://user-images.githubusercontent.com/169060/73683951-14f76980-4678-11ea-96e7-4e6f843a561f.png)

**Comment by jennyhavah** [comment]
Right alignments look good and I am consistently seeing gray em-dashes where there is no number available.
