### ISSUE TITLE
Numeric inputs and displays: Standardization based on language settings

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2125]
This ticket was branched off of this comment: https://github.com/mercycorps/TolaActivity/issues/1214#issuecomment-569149946

I noticed some inconsistencies in what we accept in the Actual value field and in the disaggregated value fields. Turns out we need to standardize our rules for numeric inputs and displays in all languages, platform-wide. After sharing several options with the MEL team, we landed on the following criteria.

# Acceptance criteria

All of the following rules apply anywhere we input or display numbers:

- [x] Result form
- [x] Target setup
- [x] Baseline field in targets tab -- while preserving current logic that a baseline can be zero
- [x] Program page (display only)
- [x] IPTT (display only)
- [x] Change log (display only)
- [x] Indicator plan (display only -- Baseline and LoP target fields)

##

# Inputs

- [x] **English:** Require an American English style floating point (period).

- [x] **Spanish:** Require a Spanish style floating point (comma).

- [x]  **French:** Require a French style floating point (comma).

- [x] No letters and no other special characters ever allowed besides . and , 

# Displays

- [x] **English:** Numbers are displayed in American English style numbers, with a **decimal floating point**. Ideally, we apply other common conventions such as the **comma** as thousands separator. 

- [x] **Spanish:** Numbers are displayed in Spanish style numbers, with a **comma floating point**. Ideally, we apply other common conventions such as the **period** as thousands separator. 

- [x] **French:** Numbers are displayed in French style numbers, with a **comma floating point**. Ideally, we apply other common conventions such as the **empty space** as thousands separator. 

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by axoplasm** [comment]
Can this be a `number` input type instead of `text`?

**Comment by camgnostic** [comment]
Moving to Ready pending a conversation with @axoplasm and @jennyhavah about best practices here

**Comment by camgnostic** [comment]
#2025 can be rolled into this ticket (actual field validation for result form)

**Comment by camgnostic** [comment]
@jennyhavah confused by "Ideally, we apply other common conventions" under display - do we want to display _all_ numbers with the thousands-separator appropriate for the language?  Or only certain ones?  (We have the IPTT, Program Page, Indicator Setup Form, and Results Form, currently all showing numbers with no thousands separator - should all of them move to a locale-aware thousands separator?)

**Comment by jennyhavah** [comment]
Target setup:

I can enter < and > into target fields. This is true of LoP, Midline/Endline, time aware and Event targets. It's true on Chrome and Firefox, and in all 3 languages.

![image](https://user-images.githubusercontent.com/33670923/74558450-31689100-4f17-11ea-8131-acf6b1f247ef.png)

**Comment by jennyhavah** [comment]
Not seeing language-specific thousands separators for displays. (Not a release blocker, but we'd discussed including this if it is not a high LoE.)

**Comment by jennyhavah** [comment]
Looks like change log does not include language-specific number display settings. For example, not seeing a , as a floating point separator in French.

![image](https://user-images.githubusercontent.com/33670923/74561730-ffa6f880-4f1d-11ea-87d8-5efaa79981a7.png)

**Comment by camgnostic** [comment]
Tagging @sanjuroj for the change log element

**Comment by jennyhavah** [comment]
Display issue, Spanish: Looks like the period separator is not appearing on the program page. 

It does appear on the IPTT and changelog.

The expected thousands separator does appear on the program page for English and French.

**Comment by jennyhavah** [comment]
Display issue, Indicator Plan: I'm not seeing any thousands separators in either of the 3 languages.

I forgot to list this one in the original issue description -- just added it.

**Comment by jennyhavah** [comment]
Display issues, Change log:

Thousands separator missing for Baseline and for LoP target, though it does show up in the target frequency field -- in this example a LoP-only target frequency.

![image](https://user-images.githubusercontent.com/33670923/76132349-67a1a980-5fc7-11ea-9bf4-4a0d071cf9a9.png)

This example is in Spanish but the pattern is the same for French and English. For French, a space separator is missing in the same spots. For English, a comma separator.

**Comment by jennyhavah** [comment]
@camgnostic Still seeing issues with the thousands separator in French and Spanish. English looks good.

French:
![image](https://user-images.githubusercontent.com/33670923/76576044-2fdeaa00-647e-11ea-9582-9ee44dad2191.png)

Need a space thousands separator for Target, Actual, and Result values. Looks good everywhere else.

Spanish:
![image](https://user-images.githubusercontent.com/33670923/76575958-f4dc7680-647d-11ea-8c50-ddf971258584.png)

Need a period thousands separator for Target, Actual, and Result values. Looks good everywhere else.

**Comment by sanjuroj** [comment]
@jennyhavah I'm not seeing the same problem for the change log any more.  On QA (just ignore the two language thing from TOLA-313):
![image](https://user-images.githubusercontent.com/6685499/76798973-e77d0000-678d-11ea-8771-628eab06e808.png)

Can you point me to where you're seeing the non-separated numbers?

**Comment by jennyhavah** [comment]
> I'm not seeing the same problem for the change log any more. On QA (just ignore the two language thing from TOLA-313):

The change log is fine -- I put a 🎉 under that one. The only remaining issues have to do with the result table.

**Comment by jennyhavah** [comment]
Thousands separators look good!
