### ISSUE TITLE
IPTT: Vertical space appearing/disappearing when I expando/collapso.

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2130]
To reproduce the issue, play with the Expand all / Collapse all function. Note the difference in spacing between rows when expanded vs. collapsed. Screenshots below.

I think we should remove the spacing between indicator rows when expanded -- looks a bit awkward and comes across as uninentional. But I would actually like to keep the spacing between disaggregation _types_ -- it's actually quite effective for separating parallel disaggregations. (If that's high LOE to remove space in one place but not the other, then my preference would be to remove all spacing.)

![image](https://user-images.githubusercontent.com/33670923/72640818-85368900-391d-11ea-8103-7d4ce582832d.png)

**Collapsed**
![image](https://user-images.githubusercontent.com/33670923/72640619-1e18d480-391d-11ea-9c59-dc26a87fd26d.png)

**Expanded**
![image](https://user-images.githubusercontent.com/33670923/72640640-26710f80-391d-11ea-875c-4a043e240fb1.png)

**Comment by axoplasm** [comment]
> (If that's high LOE to remove space in one place but not the other, then my preference would be to remove all spacing.)

To figure out the LOE on this one would be almost as work as fixing it. Not sure how to estimate that…

**Comment by axoplasm** [comment]
This was addressed incidentally with #2141. The extra rows have been replaced with extra-wide borders:

![image](https://user-images.githubusercontent.com/169060/73683833-d82b7280-4677-11ea-8310-dd6a23b8ff6f.png)

**Comment by jennyhavah** [comment]
@axoplasm Noticing some line thickness variation in the leftmost column:

![image](https://user-images.githubusercontent.com/33670923/73684528-373db700-4679-11ea-9100-c3e8697ad1cd.png)

**Comment by axoplasm** [comment]
Fixed in PR #2183

**Comment by jennyhavah** [comment]
Looks good! The thicker border now extends to the edge.

![image](https://user-images.githubusercontent.com/33670923/73694410-d0c29400-468c-11ea-827c-fed57994b02a.png)
