### ISSUE TITLE
IPTT expando-collapso widget: When applying filters, the "Expand all" no longer de-activates upon click

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2133]
To reproduce the issue:

1. Load up one of the named IPTT programs and, play around with the Expand all / Collapse all function _without_ touching any of the filters. Note that when you click "Expand all", it grays out, like this...

![image](https://user-images.githubusercontent.com/33670923/72652639-6dbac880-393c-11ea-9cea-a554f35143b2.png)

... and vice versa with "Collapse all."

So far, behaving as expected.

2. Next, apply any of the multi-select filters in the bottom section of the filter panel.

3. Now try using the "Expand all" function again. What I'm noticing is that while it continues to work in terms of expand all rows, it no longer grays out when I click on it. I'm no longer getting that visual feedback that I've expanded everything there is to expand, and it's grayed out because there are no more rows to expand.

**Comment by axoplasm** [comment]
I think @camgnostic can probably tackle this one much more efficiently than me

**Comment by axoplasm** [comment]
It’s probably orthogonal but you might want to review PR #2188 before taking this one

**Comment by jennyhavah** [comment]
Expando-collapsos are now behaving as expected and giving visual feedback, before and after filters are applied.
