### ISSUE TITLE
Creating disaggregation labels with the same name in the same type should not be possible?

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#2153]
Users can currently create disaggregation labels with the same name while creating/updating disaggregation types in the country admin interface.  I think this should not be possible?

**Comment by sanjuroj** [comment]
@jennyhavah I'm assuming this is correct?

**Comment by jennyhavah** [comment]
Yes, correct: We should prevent people from saving duplicate disaggregation labels within the same type, using a similar error handling pattern to what we do if you try to save duplicate RF levels in the same template.

This probably goes without saying, but it is fine for the same label to be used in _different_ disaggregation types.

**Comment by sanjuroj** [comment]
@jennyhavah I have a couple of questions/comments about ensuring there are no duplicate disagg labels in the system.  The same questions apply, somewhat, to #1913.  Also pinging @camgnostic since he did the backed work to prep for the new disagg system and is more familiar with the data migrations in GT.

1.  The best way to ensure no duplicates are created is to put a database-level restriction in place.  The bad news is that there are already duplicated labels in the database and we can't put the restriction in the database until we eliminate the existing duplicates.  The good news is that there is only one duplicated label with values associated with it (there are several others with no associated values).  So I believe we could do a data migration before putting putting the database restriction in place with minimal disruption to existing data.  However, the fine points of this may still need to be worked out with HQ MEL and/or country MEL programs, which could take time.  I would like to propose that for GT, we put front-end and some non-database backend validation in place while we work out exactly what kind of data migration we need to do for the database restriction.  Once we have those details we can do a data migration and put the db-level restrictions in place as part of a Poblano ticket.  Does this sound reasonable to you?

2.  Does a change in capitalization but not spelling constitute a duplicate?  So is "Thingy" the same as "thingy"?  I'm going to assume yes?

**Comment by jennyhavah** [comment]
> Does a change in capitalization but not spelling constitute a duplicate? So is "Thingy" the same as "thingy"? I'm going to assume yes?

Yes. Thingy = thingy.

**Comment by jennyhavah** [comment]
> he best way to ensure no duplicates are created is to put a database-level restriction in place. The bad news is that there are already duplicated labels in the database and we can't put the restriction in the database until we eliminate the existing duplicates. The good news is that there is only one duplicated label with values associated with it (there are several others with no associated values). So I believe we could do a data migration before putting putting the database restriction in place with minimal disruption to existing data. However, the fine points of this may still need to be worked out with HQ MEL and/or country MEL programs, which could take time. I would like to propose that for GT, we put front-end and some non-database backend validation in place while we work out exactly what kind of data migration we need to do for the database restriction. Once we have those details we can do a data migration and put the db-level restrictions in place as part of a Poblano ticket. Does this sound reasonable to you?

Just huddled with Sanjuro. We are going to attempt to resolve the dupes, consulting MEL where any existing indicators or results would be affected. This, as opposed to coming up with special rules to handle conditions we are going to prevent going forward.

**Comment by jennyhavah** [comment]
Found some edge cases. To reproduce:

1. Create a disaggregation with duplicate categories and submit. Here's what I see -- good so far:

![image](https://user-images.githubusercontent.com/33670923/74991448-cfb69400-53fa-11ea-969d-5ce779f530b8.png)

2. Now add another category that's NOT a duplicate. Before saving, move it in between two of the duplicates, using the reorder handles. Here's what I see:

![image](https://user-images.githubusercontent.com/33670923/74991554-14dac600-53fb-11ea-8ab4-00b4d7c31e3e.png)

Also... If I then delete all the categories and start over by clicking "Add a category", I see this, before I even typed anything:

![image](https://user-images.githubusercontent.com/33670923/74991609-363bb200-53fb-11ea-8dc8-5126278745f5.png)

Even weirder... I deleted the _entire disaggregation_ and started over, and got this, before even giving the Disaggregation a name:

![image](https://user-images.githubusercontent.com/33670923/74991634-4fdcf980-53fb-11ea-8cb2-055034dbf280.png)

**Comment by jennyhavah** [comment]
I'd like to rephrase the warning message to: Categories must have unique names.

(A little softer, consistent with phrasing in RF Builder.)

**Comment by jennyhavah** [comment]
@sanjuroj I am now able to reorder categories with the duplication warning message appearing under the correct categories.

However, I'm still experiencing the issue where, if I delete all the categories (after creating duplicates and shifting the order) and then click "Add a category" to start over, I see the warning message, before I've typed anything:

![image](https://user-images.githubusercontent.com/33670923/75081525-52575600-54c4-11ea-8bb2-8091e46f1ae6.png)

**Comment by jennyhavah** [comment]
@sanjuroj There's an extra period after "names".

![image](https://user-images.githubusercontent.com/33670923/75081546-669b5300-54c4-11ea-92f6-cd4790adf19a.png)

**Comment by sanjuroj** [comment]
Eighth time's the charm?

**Comment by jennyhavah** [comment]
Issues described above are fixed.
