### ISSUE TITLE
IPTT Level Labels interpolate bug

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#2169]
The interpolated translated string "%s and sublevels" is not being fed the correct object array on the IPTT filter menu listing levels/outcome chains for an RF-aware program, resulting in variable names visible and wholly untranslated strings on display in the filter.

![image](https://user-images.githubusercontent.com/7941355/73498510-60f19800-4372-11ea-8995-c252943c2e50.png)

**Comment by jennyhavah** [comment]
Working as expected. Here's what I see for Jordan's WIT program:

![image](https://user-images.githubusercontent.com/33670923/73682073-7e757900-4674-11ea-9211-cdb18196851d.png)
