### ISSUE TITLE
Admin > Users: Error when modify status from Active to Inactive

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2197]
I discovered this on QA but turns out it's also doing this on Prod. Whatever is wrong here, we should also make sure it's behaving as expected for Programs and Organizations, that also have a concept of "Active" and "Inactive". (Update: Did a quick check on QA -- looks ok for programs, not for orgs. Didn't try Prod for those two.)

# Users

To reproduce, try changing a user's status from Active to Inactive. This is the error message I get:

![image](https://user-images.githubusercontent.com/33670923/74199552-58724a80-4c19-11ea-8936-6e19b779d1ff.png)

## Programs

Not getting this error in Programs when I change from Active to Inactive and vice versa.

## Organizations

Get a different error message: It just says "Saving Failed."

![image](https://user-images.githubusercontent.com/33670923/74200219-28c44200-4c1b-11ea-84a3-65b225181c04.png)

**Comment by sanjuroj** [comment]
@jennyhavah  The issue for Users is dead easy to fix, just a few seconds.  I'm not having the same problem with Organizations on Staging or QA.

**Comment by jennyhavah** [comment]
@sanjuroj I think I know what happened with Organizations. I was updating the status of a test organization already in the system that was somehow added without all required fields complete -- maybe added directly to the database? In any case, the failure had to do with incomplete fields, not an inability to save the status change. Once I filled in all required fields, the status changes registered as expected.

Our error messages in the admin could use some work... but that's a whole Poblano ticket or five.

**Comment by sanjuroj** [comment]
Ok, glad Orgs are working.  So. Many. Admin. Things. To. Fix.  

Let me know if you want to Ghost Pepper this.

**Comment by jennyhavah** [comment]
@sanjuroj Since user status is an important thing to be able to manage, I think it's GP-worthy, as long as it's isolated and low-risk. Moving to GP.

**Comment by sanjuroj** [comment]
It's quite isolated and fairly low risk.  The important thing to test will be security; right now _nobody_ can change status.  Since we're enabling updates, we should make sure that _everyone_ can't update.

**Comment by jennyhavah** [comment]
@sanjuroj Meaning, only Basic Admins and Super Admins? Once you have a fix in place, please let me know what you recommend for testing.

**Comment by sanjuroj** [comment]
Testing from the frontend should probably focus on ensuring that the restrictions on which users can be inactivated remain in place.  Only users in the a non-MC org should have the inactivation dropdown enabled.  Essentially everything should function as it does on production, except that inactivating a user should no longer error out.

**Comment by jennyhavah** [comment]
Clarified with Sanjuro that the restrictions to be tested are:

1. Only basic admins should have access to the admin pages.

2. Only users in non-MC orgs should have the inactivate dropdown available.  Those are the two I can think of related to Users.

Tested on DEMO:

- I do not see the Admin section if I am not a Basic Admin.
- When I login as a Basic Admin: 
     - I can see the status menu for Mercy Corps users, but it is not editable.
     - I can edit the status menu for users from organizations other than Mercy Corps.
     - When I inactivated external-high, the change appeared to save successfully, and was logged in the Status and History tab.
     -  When I then tried to login as external-high, I got this error: Please enter a correct username and password. Note that both fields may be case-sensitive. Did you forget your password? Click here to reset it.
     - When I (as Basic Admin) switched that same user back to Active, I was able to login.
- When I login as a Super Admin:
     - Status menus shows up for all users. 
     - I can make users active and inactive, regardless of whether or not they're linked to Mercy Corps. 
     - Status changes show up in the history tab.
     - When a user's status is changed to Inactive by a SuperAdmin, they can't login, _even if they're MC users._ (I think this is actually fine.)
