### ISSUE TITLE
Dashboard: Map layers icon and dialogue poke through Filter by Program menu

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#22]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Thursday Dec 14, 2017 at 00:59 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/12_

----

**Affects:** Dashboard map and _Filter by Program_ menu

1. When I open the _Filter by Program_ menu, the map layers icon pokes through. 
1.1. When I hover over that icon, the actual layers dialogue pokes through.
2. The map footer also pokes through the menu.

![scrap](https://user-images.githubusercontent.com/33670923/33970265-fdd99002-e026-11e7-9a3e-c3dbbd7a1af0.png)

![scrap](https://user-images.githubusercontent.com/33670923/34424881-fc7fb964-ebdb-11e7-9366-3fd9087826a0.png)

**Comment by jennyhavah** [comment]
Fixed on Chrome. Still experiencing the issues in Firefox and Safari.

**Comment by mahmoodkhan** [comment]
I'm not able to replicate it in either Chrome, Firefox, or Safari.

**Comment by jennyhavah** [comment]
You know what, I may have been looking at Demo instead of Dev. Looks good to me now.
