### ISSUE TITLE
Results framework: Add two levels

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2206]
# Issue

Nigeria has reported that having only 6 levels in our custom results framework template is a barrier to using that feature, and therefore Tola as a whole. This ticket adds two additional levels to the custom RF template.

**Affects:**
- RF builder custom template 
- All places in which RF levels are displayed (needs QA to ensure no unintended effects)
   - Logframe
   - Indicator plan
   - Indicator setup form (result level field)
   - IPTT table and filters

# Acceptance criteria

## RF builder custom template

![image](https://user-images.githubusercontent.com/33670923/74286683-24f8f400-4cdd-11ea-8826-7176c45b49ec.png)

### Adding RF tiers

This section refers to defining the hierarchy with custom labels.

- [x] 1. I can add up to 8 levels instead of 6.

- [x] 2. When I reach the 8th level, the "Add level" button is hidden. (Currently this occurs when you reach the 6th level.

- [x] 3. New levels show up in the mini-tree, and look okay from a styling standpoint -- indentation, etc.

### Saving RF levels

- [x] 1. I can add 7th and 8th tier RF levels and link indicators to them.

- [x] 2. Auto-numbering of RF levels follows established conventions.

- [x] 3. Auto-numbering of _indicators_ follows established conventions

- [ ] 4. Tier names are displayed as expected:

     - [x] 4.1. Title of RF level form

     - [x] 4.2. "Save [RFtier] and add indicators" button before the first indicator is added.

     - [x] 4.3. "Indicators linked to this [RFtier]" above list of indicators after first one is added.

     - [x] 4.4. "Save and add another [Rftier] button.

     - [x] 4.5. "Save and link a [Rftier] button -- _only for level 7, hidden for level 8_

- [x] 5. Styling review of RF level form elements including indicators: Indentation, wrapping, alignments, etc. all look okay?

## Logframe

- [x] 1. New tiers display as expected in the web view.

- [x] 2. New tiers display as expected in export.

## Indicator plan

- [x] 1. New tiers display as expected in the web view.

- [x] 2. New tiers display as expected in export.

## Indicator setup form

- [x] 1. New tiers display and behave as expected in the result level menu when accessed from RF builder.

- [x] 2. New tiers display and behave as expected in the result level menu when accessed from program page.

- [x] 3. New tiers display and behave as expected in the result level menu when accessed from IPTT.

### IPTT table

- [x] 1. New tiers display as expected in the web view.

- [ ] 2. New tiers display as expected in export.

### IPTT filters

- [x] 1. New tiers display and function as expected in the "Levels" filter.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
Estimated as a range between LoE Medium on the optimistic end (a few days) and High on the pessimistic end (couple weeks).

**Comment by jennyhavah** [comment]
>  1. I can add up to 8 levels instead of 6.

@sanjuroj Regarding this criteria: I noticed that your new QA Program -- Levels all the way down -- has 9 levels.

I then tried creating a custom template and was only able to add 8 levels... So I _think_ it's working as expected but wanted to flag the weird extra level in the QA program in case it could somehow be possible for a user to do that.

**Comment by jennyhavah** [comment]
There is one export view where the order of levels are not showing up as expected. To reproduce:

1. Run a Target vs Actuals IPTT on QA Program -- Levels all the way down.
2. Set the "Group by" filter to "Levels".
3. Click "Export" and select "All program data.
4. In the export, go to the Annual tab and compare with what's on the screen. It appears to be grouping by result chain instead of Level.

**Comment by sanjuroj** [comment]
@jennyhavah Couple of things: 
1.  You might not have seen my question on Jira.  I have question about an edge case.  Say a program has 8 levels and we reduce the max levels to 6.  If they want to delete a single level, are there any warnings around having more than the max level?  Do we let them reduce the number of levels to 7?  Or do we insist on going all the way to 6? 

2.  I don't think the problem with ordering of the indicators by level is specific to the expanded tier depth.  I tried the export as you instructed with my personal QA program and got the wrong order.  Cameron just rewrote this whole Export functionality as part of GT.  I'm wondering if we can wait to fix until the GT release.  I don't know what kind of effort it would take to fix the ordering of the old code.

**Comment by jennyhavah** [comment]
> You might not have seen my question on Jira. I have question about an edge case. Say a program has 8 levels and we reduce the max levels to 6. If they want to delete a single level, are there any warnings around having more than the max level? Do we let them reduce the number of levels to 7? Or do we insist on going all the way to 6?

I don't understand this question. Let's chat about it in the dev team meeting.

**Comment by jennyhavah** [comment]
Regarding the above question, we discussed in our dev team meeting and decided not to take action at this time. Moving the ticket to Passed.
