### ISSUE TITLE
Improve error handling when user enters a , or . and no number

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2218]
# Issue
I discovered an error message connected to the disaggregated result value field that seems unnecessary:

![image](https://user-images.githubusercontent.com/33670923/74578333-e6677180-4f48-11ea-8582-e6ef47f8514d.png)

I am able to induce the above error by typing a . or , in a disaggregation value field and tabbing or clicking out of the field. Since this is not a required field, and the system has already removed the offending lone character, it seems unnecessary to display an error message. There's nothing for the user to "fix" at this point.

# Request
If a user types a , or . and tabs or clicks out of the field, simply remove the offending character. Do not throw an error.

Question for @camgnostic: Are there any other ways you can think of, to induce an error in the disaggregated value field? If so, let's see what we can do to avoid it. (Among other things, it distorts the layout of the table.)

**Comment by camgnostic** [comment]
I can't find a way to make the error message appear now that it handles only comma or only period the right way.

**Comment by jennyhavah** [comment]
Validated. Error message no longer appears if I type a . or , into a disaggregated value field and tab/click out of the field.
