### ISSUE TITLE
Script: For all existing indicators, update the Unit of Measure to Number or Percentage

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#222]
## The issue
We now have a required field under the Unit of measure: Every indicator must have either Number or Percentage selected. The question is, what to do with existing indicators? In most cases, the default of Number will be appropriate. However, we do have a significant number of existing indicators that are described as percentages in the name and/or unit of measure field. These indicators, we should automatically assign as Percentages.

## Script requirements
1. Look for indicators with the following characteristics:
1.1. The indicator name has a % sign or the words "percentage" or "percent".
1.2. The unit of measure field has a % sign or the words "percentage" or "percent".
2. For these indicators, mark the Unit of Measure as Percentage and the type of calculation as Cumulative.
3. For all other indicators, mark the Unit of Measure as Number and the type of calculation as Non-cumulative.

**Comment by sanjuroj** [comment]
Probably the easiest way to test this is to create or identify several indicators where you have an expectation of what the cumulative and percent values should look like after the script is run.  Then I could run the script and you could see if the actual result matches what you expected.

**Comment by hannalcamp** [comment]
This ticket is so validated, it's parking is free for a month. :P
