### ISSUE TITLE
Program indicators page: Results table

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#223]
# Before/after

Here is what we have at the moment.
![image](https://user-images.githubusercontent.com/33670923/39148610-98022e06-46f1-11e8-86df-9e2563ce2f2c.png)

Here's what I have in mind.
![image](https://user-images.githubusercontent.com/33670923/39151736-fba8644e-46fa-11e8-81b4-772589b4a803.png)

# Content, labeling, legibility
- [x] 1. % Met column: Can we reduce the likelihood that the % Met column header wraps by giving it a slightly higher proportion of the table width?
- [x] 2. Change the table header "Data collected" to "Results".
- [ ] ~3. Put the target period results in its own column, flush right. (Right now it is in the same column as the date range, which leads to wonky behavior with a narrower browser.)~
- [x] 4. View project: We do not want to give projects a dedicated column because only a handful of programs use them, so it's wasted space in the vast majority of cases. That's why you'll sometimes see a "View project" link in the Evidence column. The only thing I'd like to fix is the awkward wrapping. Idea: We place the "View project" link _below_ the evidence, with a line break, flush _left_ instead of right.
- [x] 5. Remove the column with trash can and edit icons.
5.1. Edit icon is redundant with the date link. We don't need to replace it with anything.
5.2. Removing the delete button is contingent on moving the function into the Results form itself -- covered in #295
- [x] 6. Remove the "New data" button. Immediately under the table, right-aligned, is an "Add results" button that does exactly what the "New data" button did.

# General styling
The following are suggestions based on my mockup, not requirements. In general, my goals were to increase information density, remove visual clutter, and improve legibility. I do not have strong opinions on how exactly we go about achieving those goals.
1. Background color: I used #F5F5F5 to give more depth and a stronger hierarchy to the page.
2. The header row has a transparent background and no borders.
3. The data rows have a white background to make them stand out from the background, with top and bottom borders but no side borders.
4. The Life of Program row has a transparent background, with top and bottom borders but no side borders.
5. I added more horizontal padding between the edge of table cells and its contents. 
6. I'm using small (.875 rem) text for the whole table including column headers and the Life of Program row.
7. Target period column: I reduced the gap between the target period name and the date range.
8. Life of Program row: Text is bold and all caps for the phrase "Life of Program", as well as the Target, Actual, and % Met total numbers.
9. Project link: In my mockup, I differentiated between the evidence link and the project link by replacing "View Project" with a Fontawesome glyph followed by the word "Project". The glyph is called clipboard-list: https://fontawesome.com/icons/clipboard-list?style=solid.

**Comment by jennyhavah** [comment]
> Put the target period results in its own column, flush right. (Right now it is in the same column as the date range, which leads to wonky behavior with a narrower browser.)

I can see how that request was problematic, because we definitely don't want this to happen, with the results totally detached from their associated record dates:

![image](https://user-images.githubusercontent.com/33670923/41500839-32fcbdaa-714e-11e8-9a85-352ebbfcf85b.png)

@axoplasm Should we bring them back into the same column and use some other method for making it less likely that they'll wrap?

**Comment by jennyhavah** [comment]
> 6. Remove the "New data" button. Immediately under the table, right-aligned, is an "Add results" button that does exactly what the "New data" button did.

Right now the "Add results" button appears to be in the same row as the Life of Program results and the notes about cumulative/non-cumulative.
![image](https://user-images.githubusercontent.com/33670923/41500976-79bc7422-7150-11e8-881b-bbcbd304077a.png)

I was hoping to see it below that row, where it'll be more visible and remove some of the busy-ness from the LoP row.

**Comment by jennyhavah** [comment]
Right now, the results table is kind of blending into the Indicator rows, and I'm struggling to differentiate them -- I almost want to line up the columns of the Results table with the columns above and below.

My mockup solution was to put a generous amount of padding above and below, and to make the Results table noticeably narrower to make it "indented" from the row above.

**Comment by jennyhavah** [comment]
Just noticed that when targets are not set up for the indicator, I see some old styling, such as the column with edit icons:

![image](https://user-images.githubusercontent.com/33670923/41501644-41421cc0-715d-11e8-97f3-707585dc28b1.png)


Same deal when records are not assigned to targets, which can happen for Midline/Endline and Event based targets. To reproduce, add some results to an indicator with a LoP only target frequency, then switch targets to Midline/Endline or Events and save changes.
![image](https://user-images.githubusercontent.com/33670923/41501674-b7811ea4-715d-11e8-81d2-cb2005c9424c.png)

**Comment by axoplasm** [comment]
We are not going to be able to do much with this table without rebuilding it. It is fragile.

I’ve addressed the bug with edit button showing up. The error condition also exposes a bug in the construction of the table: there is an errant rowspan somewhere that leads some cells to "bleed" into others (as you can see with the border sneaking off to the right in your screenshot). I did an end-run around this bug by using a background color. __This is not my preferred solution__

![screen shot 2018-06-16 at 1 39 51 pm](https://user-images.githubusercontent.com/169060/41502248-03de2fbe-716b-11e8-9a27-3242e5f8b9fc.png)

**Comment by axoplasm** [comment]
I’ve used background colors to establish some visual hierarchy. Again, this is __probably not my preferred solution__ which would require rebuilding this screen to give a lot more structure and space to the page. In particular, I can't easily add spacing to the expanded rows, and it's hard to do vertical lines with these rowspans in a way that doesn't look broken.

#### Rolled up:

![1-rolledup](https://user-images.githubusercontent.com/169060/41502770-c72ae6b4-7176-11e8-8480-c4644d73e525.png)

#### Indicator with no targets:

![2-no-targets](https://user-images.githubusercontent.com/169060/41502772-cfe9683e-7176-11e8-87ba-27ab8b74e15d.png)

#### More-complex indicator:

![3-more-complex](https://user-images.githubusercontent.com/169060/41502775-da37f7a6-7176-11e8-9a7a-22d705492138.png)

#### Indicator with verbose evidence column:

![4-verbose-evidence](https://user-images.githubusercontent.com/169060/41502778-e6764be4-7176-11e8-9b9d-34742ea49ef0.png)

**Comment by axoplasm** [comment]
I’ve merged these changes, should see them on demo with the next deployment
