### ISSUE TITLE
Admin: Edge case where I can save a disaggregation with no categories

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2247]
I stumbled upon a way to save a disaggregation with no categories -- something we don't want to allow. 

If I click "Add a disaggregation" and attempt to save it without any categories, I get a warning message as expected:

![image](https://user-images.githubusercontent.com/33670923/75084743-111c7180-54d7-11ea-81f0-b49914c00a93.png)

But if I delete that category and then hit Save again, it saves.

Alternately, if open up a saved disaggregation that doesn't yet have any locked down categories and delete all the categories, I'm allowed to save.

# Acceptance criteria

The basic premise is similar to RF builder where we don't let you delete all tiers. Once you get to the last tier, you can't delete it, only edit it.

![image](https://user-images.githubusercontent.com/33670923/75084915-9c4a3700-54d8-11ea-8ecc-a31d477bfc45.png)

## Adding a new disaggregation, before saving

- [x] 1. When click "Add country disaggregation", there is no delete button to the right of the single category row displayed.

- [x] 2. If I delete the next-to-last category -- regardless of whether it's the first or second one in the list -- the delete button is hidden for the remaining single category.

## Editing a saved disaggregation

- [x] 1. If I delete the next-to-last category -- regardless of whether it's the first or second one in the list -- the delete button is hidden for the remaining single category.

- [x] 2. This bug fix does not have any unintended effects on _locked_ categories. The lock with tool-tip appears as expected and the category is not editable or delete-able.

**Comment by sanjuroj** [comment]
@jennyhavah This is a ridiculous edge case, but what if there is only one category remaining and it's in use (which means it would get a padlock symbol.  Would you prefer the padlock or the complete absence of an icon in that position?

**Comment by jennyhavah** [comment]
@sanjuroj Definitely want to keep the padlock whenever a category is locked. The padlock is never combined with the delete "X" button -- it's one or the other.

That's what I was trying to convey by "This bug fix does not have any unintended effects on locked categories. The lock with tool-tip appears as expected and the category is not editable or delete-able."

**Comment by sanjuroj** [comment]
@axoplasm I'm tagging you on this.  For both code review and design sandwich.  The one thing I noticed design-wise is that the padlock and trash can are out of alignment.  I fiddled with it a bit to see if I could fix it but I couldn't.

**Comment by jennyhavah** [comment]
@sanjuroj The padlock and trash can icon should never appear together, because you should never be able to delete a locked category. If that's possible, can you file a bug describing how you made it happen?

**Comment by sanjuroj** [comment]
Here's the screen shot:

![image](https://user-images.githubusercontent.com/6685499/75302471-c0688980-57f2-11ea-8c9e-ffa7b8d82e34.png)

**Comment by axoplasm** [comment]
I bet the padlock needs to be in a button to get aligned correctly

**Comment by jennyhavah** [comment]
Acceptance criteria PASSED. I am no longer able to save a disaggregation with no categories.

Waiting for confirmation that Paul is done working on the layout issue.

**Comment by axoplasm** [comment]
looks good to me!
