### ISSUE TITLE
Settings page: Add explanation of number inputs and displays

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2248]
# Issue

Carly suggested that we add information to the Settings page about how number inputs and displays are affected by language settings. This won't mitigate confusion for people who set their language long ago and suddenly can't enter a particular character. But it gives us a place to point them for an explanation, in addition to any documentation we provide via TolaWiki.

# Acceptance criteria

![scrap](https://user-images.githubusercontent.com/33670923/77206801-1dcfbd80-6ab5-11ea-8228-ebb3ca462078.png)

- [ ] 1. Below the language menu (with vertical space in between) is a paragraph: Your language selection determines the number format expected when you enter targets and results. Your language also determines how numbers are displayed on the program page and reports, including Excel exports.

- [ ] 2. Below the paragraph is a table.

| Number formatting conventions | English | French | Spanish |
| :--- | :--- | :--- | :--- |
| **Decimal separator** <BR> Applies to number entry and display | **Period**<BR>1.23 | **Comma**<BR>1,23 | **Comma**<BR>1,23 |
| **Thousands separator** <BR> Applies only to number display | **Comma**<BR>1,000 | **Space**<BR>1 000 | **Period**<BR>1.000 |

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah Is it important to have the submit button after the explanatory text?  If so I'm going to have to rewrite the main part of the form a bit.  The form is rendered as a big blob, including the submit button, so putting something in the middle will mean breaking the form into pieces first.

**Comment by sanjuroj** [comment]
@jennyhavah Actually, never mind, I went ahead and updated the form.  It's a small form.

**Comment by jennyhavah** [comment]
@sanjuroj If it's turning out to be tricky, it's fine to have the button above the explanatory text.

**Comment by jennyhavah** [comment]
@sanjuroj Looks great. There's just one missing word -- "only" in the description under "Thousands separator": Applies only to number display.

I included that "only" in there to really emphasize the difference.

**Comment by jennyhavah** [comment]
Looks good!
