### ISSUE TITLE
Global disaggregation is no longer trasnslated

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#2250]
Because the global disaggregation (Sex and Age Disaggregation (SADD)) is no longer hard-coded into the html for display purposes, it is also no longer translated through the normal translation process.   

SADD should be translated in the following places:
- [x] Result form
- [x] IPTT Filter panel
- [x] IPTT disaggregation column
- [x] Indicator setup > Performance tab
- [x] Change log

Solution should be flexible enough that we can add another translated global disaggregation relatively easily.

**Comment by jennyhavah** [comment]
PASSED.

The name of the disaggregation is now translated on the result form:

![image](https://user-images.githubusercontent.com/33670923/76019343-693f7480-5ed6-11ea-8691-55b4adc4d098.png)

![image](https://user-images.githubusercontent.com/33670923/76019391-7e1c0800-5ed6-11ea-8acb-3df68d91555f.png)

It is also translated in the IPTT filter panel and result table:

![image](https://user-images.githubusercontent.com/33670923/76019543-bae7ff00-5ed6-11ea-9e60-5f80ef05b774.png)

![image](https://user-images.githubusercontent.com/33670923/76019574-c9ceb180-5ed6-11ea-8ac5-be101a0b6737.png)

Known remaining issue: SADD (or any global) disaggregation _**categories**_ are still not translated, but that is out of scope for this ticket.

**Comment by jennyhavah** [comment]
@sanjuroj I found one more place where SADD is not translated -- the Performance tab of the indicator setup form:

![image](https://user-images.githubusercontent.com/33670923/76027096-e70a7c80-5ee4-11ea-9db8-e81b08c244d2.png)

**Comment by sanjuroj** [comment]
Should be fixed now.

**Comment by jennyhavah** [comment]
@sanjuroj Issue is fixed in French but not Spanish.

French
![image](https://user-images.githubusercontent.com/33670923/76103876-4caf4500-5f87-11ea-9c86-f3a75f5ec6ed.png)

Spanish
![image](https://user-images.githubusercontent.com/33670923/76103949-68b2e680-5f87-11ea-8192-54bce8561b36.png)

**Comment by jennyhavah** [comment]
Oh wait, that's _baseline_ that's not. translated. Covered in a different ticket. This issue is fixed for Spanish.

![image](https://user-images.githubusercontent.com/33670923/76104069-939d3a80-5f87-11ea-88aa-4c6ba2db235a.png)

**Comment by jennyhavah** [comment]
@sanjuroj  Found another place where it's not translated -- change log:

![image](https://user-images.githubusercontent.com/33670923/76123542-b04c6900-5fad-11ea-8587-c9867d5fc3f5.png)

**Comment by sanjuroj** [comment]
Man, I should have noticed that since I was right there.  Should be fixed.

**Comment by jennyhavah** [comment]
Looks good! 
![image](https://user-images.githubusercontent.com/33670923/76150044-f3b0e100-605a-11ea-8b70-04dec643a1f4.png)
