### ISSUE TITLE
Existing SADD disaggregated values migrated out of order

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#2258]
In the initial version of the migration, indicators with existing SADD disaggregations were migrated without concern for order, resulting in values inaccurately assigned to categories.

Expected:
- [x] any value entered for an indicator with the SADD disaggregation type before migration should have the same values in the same categories after the migration.

**Comment by jennyhavah** [comment]
@camgnostic Clarification: Does this only affect global SADD values? Is there any possibility of something similar happening with country disaggregations (formerly known as "custom"?

**Comment by camgnostic** [comment]
Correct - the error was in the code that handled global SADD disaggregations specially (to assign it to existing indicators)

**Comment by jennyhavah** [comment]
Data is appearing in the right categories now. Couple of examples -- left side is prod, right side QA:

**Program: Promoting Entrepreneurship and Digital Financial Services for Rural Youth**

![image](https://user-images.githubusercontent.com/33670923/76118920-26979e00-5fa3-11ea-9135-2b8a3c3f63ab.png)


**Program: 33050 - CROPS : Climate-smart Resilience Opportunities through Post-Harvest Storage**

![image](https://user-images.githubusercontent.com/33670923/76119306-04525000-5fa4-11ea-8316-ee24a6a9909c.png)
