### ISSUE TITLE
Saving an indicator with event targets: 500 Internal Server Error 

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2268]
I attempted to create an event indicator. I completed all required fields. When I click "Save" or "Save and add another", I get a 500 internal server error. I'm unable to save the indicator.

![image](https://user-images.githubusercontent.com/33670923/76133802-e51ce800-5fce-11ea-9d2b-845eb936e4a9.png)

I have a screenshot of the developer tool console -- let me know if that would be useful.

**Comment by sanjuroj** [comment]
`periodic-target-input` class was missing from the target field in the event creation html snippet.  This class is used to build the server request, and so the server request was missing the target data (but still pass down the event name).

**Comment by jennyhavah** [comment]
Verified that I'm able to save an event now. @camgnostic, just for peace of mind (since you've spent a lot of time on these event edge cases) I'm wondering if you could help track down the history of what might have led to this issue? I thought I'd tested all the target frequencies quite thoroughly for LevelUp with extra attention to Events, so just would feel better if we knew exactly what might have triggered this change, and that it's not indicative of a bigger issue with event indicators.

**Comment by camgnostic** [comment]
looks like between paul and me going back and forth adding and changing CSS classes that serve both a style and "identify this for the logic to validate" changes, we missed updating the section of the code that adds a new event target field.  Risks that led to this regression:

- the jury-rigged way that CSS is used to both style and do logic/validation (which is a subset of)

- the super-complicated but all-in-one-file and untested nature of the indicator setup modal form (in combination with)

- the overlapping areas we were working on resulting in one area being QA'd but then changed by a future update (for example, the logic on saving indicators was tested when it was updated, but wasn't retested when Paul made some styling changes, etc.)

at the heart of the error was a dev mistake (mine) - a class got added to 7 of the 8 places that a form input is supposed to be labeled as "a periodic target input", but the 8th one was a very specific case (an event target that had been added during the current editing session)

is that what you're looking for, postmortem wise, @jennyhavah?  Or is there more detail I can go into / plan for avoiding in the future?

**Comment by jennyhavah** [comment]
Thanks for this explanation, @camgnostic. Passing this ticket, and I'll spend some extra time hammering on events during the final QA push.
