### ISSUE TITLE
Admin > Country disaggregations: Add warning messages when "Selected by default" box is checked and update tool-tip text.

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2285]
# Issue
We need to warn admins of the implications of checking or unchecking the “selected by default” option for new and existing indicators, and confirm their decision before proceeding. 

Carly also requested some refinements to the tool-tip associated with this option.

# Acceptance criteria

## Scenario 1: Checking the "Selected by default" checkbox

_Precondition: I'm adding a new country disaggregation OR editing a saved disaggregation where the "Selected by default" checkbox has NOT been checked._

- [x] 1. After completing all required fields, checking the "Selected by default" checkbox, and clicking "Save changes", I get a yellow PNotify warning confirmation message. It says:

Warning
This disaggregation will be automatically selected for all new indicators in [COUNTRY]. Existing indicators will be unaffected.
Are you sure you want to continue?

![image](https://user-images.githubusercontent.com/33670923/76894772-02ae4500-684c-11ea-90c1-dad2dc7fb977.png)

- [x] 2. If I click "Cancel", the PNotify closes and no changes are saved. 

- [x] 3. If I click "OK", changes are saved and I get a green success message.

## Scenario 2: Unchecking the "Selected by default" checkbox

_Precondition: I'm editing a saved disaggregation where the "Selected by default" checkbox is already checked._

- [x] 1. After UNchecking the "Selected by default" checkbox, and clicking "Save changes", I get a yellow PNotify warning confirmation message. It says:

Warning
This disaggregation will no longer be automatically selected for all new indicators in [COUNTRY]. Existing indicators will be unaffected.
Are you sure you want to continue?

![image](https://user-images.githubusercontent.com/33670923/76894794-0d68da00-684c-11ea-867b-0592f35af60c.png)

- [x] 2. If I click "Cancel", the PNotify closes and no changes are saved. 

- [x] 3. If I click "OK", changes are saved and I get a green success message.

## Text changes to tool-tip

- [x] 1. Please update the tool-tip text to say:

When adding a new program indicator, this disaggregation will be selected by default for every program in [COUNTRY]. The disaggregation can be manually removed from an indicator on the indicator setup form.

![image](https://user-images.githubusercontent.com/33670923/76894867-2ec9c600-684c-11ea-9889-d5953d22f61a.png)

## Housekeeping (where applicable)
- [ ] Unit test/s written
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah The text color of the the warning and the main message are different than what you have in your ticket.  They're the same as the warning used in the RF builder, when you have unsaved changes and hit the edit button on a different level card.  Let me know if you want the colors changed, and if so, whether they should be consistent across all of these types of warning alerts.

**Comment by jennyhavah** [comment]
@sanjuroj Please ignore the styling differences between my PNotify mockups and the current state of things. My mockups reflect early visual patterns Paul developed awhile back, that we have not yet implemented. Right now it's a mishmash of styles, so I decided to keep using my mockups that represent where we eventually want to go.

We have a Poblano ticket (#1187) for global styling of these messages.

**Comment by jennyhavah** [comment]
@sanjuroj I'm seeing the wrong message for Scenario 2 that involves UNchecking the "select by default checkbox.

![image](https://user-images.githubusercontent.com/33670923/76889694-46e91780-6843-11ea-86c8-a1fca3b573b0.png)

**Comment by jennyhavah** [comment]
@sanjuroj I don't see the updates to the tool-tip.

**Comment by sanjuroj** [comment]
@jennyhavah Sorry about that, I don't know how I missed those.  Hopefully it's all good now.

**Comment by jennyhavah** [comment]
@sanjuroj For Scenario 1, it's working as expected when I **edit** a disaggregation. But if I create a **new** disaggregation that has the "selected by default" box checked, I'm not seeing the warning. It goes ahead and saves it

**Comment by jennyhavah** [comment]
All criteria are met.
