### ISSUE TITLE
Multiple locations: Final tweaks to French translation of LoP

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2289]
After consulting with Marie, we need to make just a few tweaks to our French translation of LoP -- Life of Program -- in a few locations

## Program page results table

Vie du programme --> La vie du programme

![image](https://user-images.githubusercontent.com/33670923/76879239-3892ff80-6833-11ea-8b65-5b8799e3fca2.png)

## IPTT landing page

Remove brackets but keep the parentheses so that it says: La vie du programme (LoP) seulement

![image](https://user-images.githubusercontent.com/33670923/76879353-5ceedc00-6833-11ea-9674-b9f2be11ba2f.png)

## IPTT filter panel

Remove brackets but keep the parentheses so that it says: La vie du programme (LoP) seulement

![image](https://user-images.githubusercontent.com/33670923/76879389-69733480-6833-11ea-898b-a5829f27343f.png)

**Comment by sanjuroj** [comment]
@jennyhavah What about in the IPTT header.  Should I make that "La vie du program"?
![image](https://user-images.githubusercontent.com/6685499/76880427-e0f59380-6834-11ea-9712-126f5e9dd10a.png)

**Comment by jennyhavah** [comment]
Good catch @sanjuroj. Yes, as Marie requested consistent use of the article, let's change it to: 

La vie du programme <-- think you have a typo in your comment.

**Comment by jennyhavah** [comment]
All updates were made.
