### ISSUE TITLE
Allow submission of results when disaggregations do not add up to the total actual value

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2293]
# Issue
The MEL team's thinking has evolved, and they no longer wish to require disaggregated values to add up to the total actual value, in order to submit a result. This has to do with the practical realities of data collection in the field, and concern that being too strict may have unintended consequences such as teams not disaggregating their data in Tola -- the perfect being the enemy of the good, essentially.

# Acceptance criteria

**Affects:** Cumulative and non-cumulative number indicators only. (Does not affect % indicators.)

**Precondition:** I submit a result with disaggregated values that do not add up to the total actual value, for one or more disaggregations. **_The following criteria apply, whether I'm submitting a new result or editing a saved result._**

Upon submitting, the following things happen:

![image](https://user-images.githubusercontent.com/33670923/76909602-dead2c80-6868-11ea-883b-a7fa7a80a74a.png)

- [x] 1. The result is saved, despite the numbers not adding up.

- [x] 2. I see the same yellow message at the top of the result form, that I see when I submit a result with a badly formed evidence URL: Result saved - however please review warnings below.

- [x] 3. The "Needs attention!" messages we display today remain exactly as they are.

- [x] 4. **_We preserve all of the following functionality as is:_** The red number telling you how much you need to add or subtract; the "update actual value" button; and the red warning message under the table that says, "The sum of disaggregated values does not match the actual value."

![image](https://user-images.githubusercontent.com/33670923/76909680-259b2200-6869-11ea-8f97-a9e5d4f36413.png)

- [x] 5. All of the previous criteria are met both when I submit a new result AND when I edit a saved result.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
Under the following conditions, I'm getting some unexpected behavior:

1. I'm editing a saved result.

2. I am modifying a disaggregation _that already has some values_ in some but not all categories.

3. I add a value _to an empty category_ -- as opposed to editing one of the existing values. 

When I submit under those circumstances, the result is not accepted and I don't see the yellow "yes but" header message. I just see the red warnings to fix my disaggregations.

If I then click "Save changes" a _second_ time, I am prompted for a reason for change. Once I submit THAT, my submission is accepted and I see the expected yellow warning.

**Comment by jennyhavah** [comment]
No longer able to reproduce the error. I consistently see the prompt for rationale. @sanjuroj would you mind adding a note about what you discovered, for future reference?

**Comment by sanjuroj** [comment]
We're not 100% sure of what was happening but it was likely a race condition between the change event of the value field and the submit event of the "Save changes" button.  We think it was probably a race condition because I was only able to reproduce when I changed values in disaggs that had many categories.  The change event seems to block the submit event in only a semi-predictable way.  

The solution was to convert the change event handler to a blur event handler, check if the new target was the "Save changes" button, and if so trigger the form submission.
