### ISSUE TITLE
Results: When disaggregated values do not add up to total, I am prompted to give a reason for the discrepancy

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2295]
This ticket was peeled off of the work described in #2293.

# Issue

From the MEL team -- related to their request to allow results to be submitted when the disaggregated values don't add up to the total actual value: _We spoke about how it may be useful to track how this is working. Would it be possible to track this in something like the change log? If the change log isn't appropriate, then maybe another method? If people have to put in a reason for why the numbers don't match it could give us a better idea of how the system is being used. If people don't provide substantive reasons then it at least gives us a bunch of cases to dig into with teams so we can spot check and better understand the trend in use._

# Acceptance criteria

Affects:
1. Results submitted for number indicators only, not % indicators.
2. Submission of new results AND edited results.

## Scenario 1: The user creates OR edits a saved result and submits the form with one or more invalid or incomplete required fields

- [x] 1. Regardless of whether or not the disaggregated values match the total, the user sees the exact same warnings and instructions they see today. We do not show any special prompts related to disaggregation discrepancies until the other issues are resolved.

## Scenario 2: The user **_creates a new result_** with all required fields complete and valid AND the disaggregated values do not add up to the total. _The fact that this is a newly created result is a notable distinction; today we do not have any rationale prompts associated with a new result._

- [x] 1. We display a yellow rationale prompt. It says:

Warning
The sum of disaggregated values does not match the actual value.
For future reference, please share your reason for these variations.

![image](https://user-images.githubusercontent.com/33670923/77006531-d8c65280-691f-11ea-963a-e77d5f71e9de.png)

_Please ignore the styling differences between my mockup and the current implementation of PNotify warnings. We have a Poblano ticket to update styles globally._ 

- [x] 1.1. If I click "Cancel", changes are not saved and the PNotify prompt goes away.

- [x] 1.2. If I attempt to submit without entering anything into the text field, I see the standard red message: A reason is required.

![image](https://user-images.githubusercontent.com/33670923/77006711-2d69cd80-6920-11ea-8591-43a92310953e.png)
 
- [x] 2. If I type something in the text field and click "OK", the following things occur:

     - [x] 2.1. We maintain the same behavior described in #2293 -- the submission is accepted, with a warning message:

     ![image](https://user-images.githubusercontent.com/33670923/77006918-8afe1a00-6920-11ea-9476-ee188202e413.png)

     - [x] 2.2. Whatever the user typed into the "reason for change" text box appears in the "Reason for change" column of the change log.

## Scenario 3: The user _**edits a saved result**_ in any combination of ways, WITHOUT creating any disaggregation discrepancies.

- [x] 1. We show the following reason for change prompt: Modifying results will affect program metrics for this indicator and should only be done to correct a data entry error. For future reference, please provide a reason for modifying this result.

_NOTE: We are currently displaying the wrong message as per #1320. Please replace with the above message._

## Scenario 4: The user _**edits a saved result**_ in any combination of ways, INCLUDING a disaggregation discrepancy.

- [x] 1. We display a yellow "reason for change" prompt. It says:

     Warning
     The sum of disaggregated values does not match the actual value.
     Modifying results will affect program metrics for this indicator and should only be done to correct a data entry error. For future reference, please provide a reason for modifying this result.

     ![image](https://user-images.githubusercontent.com/33670923/77682406-1fd1ca80-6f54-11ea-8d68-ab5a7b5b09c2.png)

     - [x] 1.1. If I click "Cancel", changes are not saved and the PNotify prompt goes away.

     - [x] 1.2. If I attempt to submit without entering anything into the text field, I see the standard red message: A reason is required.
 
- [x] 2. If I type something in the text field and click "OK", the following things occur:

     - [x] 2.1. We maintain the same behavior described in #2293 -- the submission is accepted, with a warning message:

     ![image](https://user-images.githubusercontent.com/33670923/77006918-8afe1a00-6920-11ea-9476-ee188202e413.png)

     - [x] 2.2. Whatever the user typed into the "reason for change" text box appears in the "Reason for change" column of the change log.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah The basics of presenting the modal and creating the log entry are pretty quick and easy.  The place it could get bogged down is in the diffing in and display.  The diffing in particular is under-tested and therefore fragile. 

I'm assuming that we're not making any changes to the structure of the change log.  It's meant to show previous and new entries, which is not really what we're doing.  If we decide to change the structure of the change log to accommodate this new type of rationale prompting, this will become a bigger project.

**Comment by jennyhavah** [comment]
@sanjuroj By "structure" do you mean layout? No, the only change I'm suggesting is really to the logic -- a new situation where a prompt would appear. The rationale itself would be stored in the same place that we store all other change log rationales -- in the Comments column.

**Comment by jennyhavah** [comment]
@sanjuroj Ticket updated, including a new scenario where the user edits a saved result in multiple ways, including disaggregation changes that cause a discrepancy. 

Please let me know if you see any other gaps.

**Comment by sanjuroj** [comment]
@jennyhavah Looks good.  I think I know the answer but just to be sure, in Scenario 4, I assume the warning message should be "Your changes will be recorded in a change log. **_For_** future reference...", rather than "Your changes will be recorded in a change log. future reference..."

**Comment by jennyhavah** [comment]
>  I assume the warning message should be "Your changes will be recorded in a change log. For future reference...", rather than "Your changes will be recorded in a change log. future reference..."

@sanjuroj Thanks for catching that -- mistake fixed.

**Comment by sanjuroj** [comment]
@jennyhavah As I was looking through the code, I realized that there is a different warning message if the user changes the date:
>Modifying results will affect program metrics for this indicator and should only be done to correct a data entry error. For future reference, please provide a reason for modifying this result.

This seems a little strange since it doesn't actually reference that the date has changed, though it is a bit stronger than the message provided if the user changes the value or the evidence link:
>Your changes will be recorded in a change log. For future reference, please share your reason for these changes.

Does this change the scenarios listed above?

**Comment by jennyhavah** [comment]
@sanjuroj I thought it was weird that this message was tied to a change in the result date, so did a bit of digging and realized that we should be using this messaage...

> Modifying results will affect program metrics for this indicator and should only be done to correct a data entry error. For future reference, please provide a reason for modifying this result.

... for _any_ type of result modification, not only for the result date. This is not a Goat Tree regression -- there was just a misunderstanding or oversight related to the "modify result record" section of ticket #1320. 

I updated scenarios 3 and 4 to include the correct text anytime a result is changed, with or without a disaggregation issue.

**Comment by jennyhavah** [comment]
@sanjuroj The PNotify behavior all works as expected. However, for Scenario 2, my reason is not showing up in the change log. It says "N/A".

**Comment by sanjuroj** [comment]
@jennyhavah I've fixed the problem of the rationale not appearing but there are a couple of edge cases I hadn't considered.  

1.  Start with an existing result with a disagg/value mismatch.  The user changes the value to match the disagg sum.  Only the changed value will appear in the change log, not the disaggs since they haven't changed.  But it's significant that the value has been changed to match the disaggs (and this might be reflected in the rationale).  Do we want to show the disaggs values in the change log, even though they haven't changed?

2. Again start with an existing result with a disagg/value mismatch. The user changes the evidence link.  Once again, they may reference the disagg mismatch in the rationale (as they are prompted to), but neither the actual value nor the disaggs will appear in the change log because neither has changed.  

These seem fairly unlikely but just wanted to make sure we handled them if needed.

**Comment by jennyhavah** [comment]
> 1. Start with an existing result with a disagg/value mismatch. The user changes the value to match the disagg sum. Only the changed value will appear in the change log, not the disaggs since they haven't changed. But it's significant that the value has been changed to match the disaggs (and this might be reflected in the rationale). Do we want to show the disaggs values in the change log, even though they haven't changed?

@sanjuro In general, I think it's best to have consistent rules for what fields we show in the change log -- either show every field regardless of whether or not it's been changed... or only show fields that have changed. I remember you and I going back and forth over whether we ought to always show the total value even if it has not changed... and in the end we thought it might be more confusing than helpful to make that one exception. I lean the same way for disaggregation values... Why are we showing them all in this particular case, but not showing them all when you edit a bunch of disaggregation values while keeping the total the same? 

Let's leave it as is for now. Just to be safe, I'll double check with Marco to make sure we're on the same page about only showing total and disagg values that have changed, generally speaking.

> 2. Again start with an existing result with a disagg/value mismatch. The user changes the evidence link. Once again, they may reference the disagg mismatch in the rationale (as they are prompted to), but neither the actual value nor the disaggs will appear in the change log because neither has changed.

In this case, I'm not sure that displaying the fields adds any clarity... They're still providing an explanation for a discrepancy that occurred in the past... not something related to what they're editing in the present. If we include all the fields, then the auditor is going to be looking for what's different and may wonder if something got mis-logged. So again, I think it boils down to needing consistent rules -- show everything or only show what's changed, always.

**Comment by jennyhavah** [comment]
My rationale is now saved, for Scenario 2. Passing this ticket. @sanjuroj I will open a new ticket if Marco wants to change any behavior around what values we display in the change log, as discussed above.
