### ISSUE TITLE
Potential release hazards

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#2301]
Trying to list things to check or watch for when goat-tree is eventually released.

- .po file merge may be tricky, depending on how many strings get updated
- migrations, of course
- npm packages are currently showing a lot of vulnerabilities, mostly minor.  May need to update.

**Comment by camgnostic** [comment]
- db script being run on all our staging/dev/qa servers
- bootstrap version in the package file not being updated until we've done that intentionally (occasionally gets reset to ^ in a merge conflict resolution)
- package.json conflicts causing weird jest test fail errors

**Comment by jennyhavah** [comment]
ok to close this ticket?

**Comment by sanjuroj** [comment]
yep
