### ISSUE TITLE
Editing saved result: Not prompted for rationale when increasing a total or disaggregated result by less than one (maybe language related)

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2314]
Issue: When editing a saved result, I am not prompted for a "reason for change" under certain circumstances. I discovered this **while the language was set to Spanish**. So far have not been able to reproduce in English, but I CAN reproduce in French... Might potentially be related to the type of decimal separator?

To reproduce:

1. Set your language to Spanish or French.
2. Find or create a saved result that is a _whole number_.
3. Edit the result by tacking on a decimal value under one. For example, change 100 to 100,3 or 100,33.
4. Save.

I would expect to be prompted for a reason for change in this case, but I am not.

Same thing happens if I modify a _disaggregated_ value from a whole number to a number plus fraction.

**Comment by jennyhavah** [comment]
@sanjuroj Just noticed the "needinfo" tag. Were you having trouble reproducing this issue, or were there questions?

**Comment by sanjuroj** [comment]
No, that's was more of an indication that we're semi-blocked on this until we figure out the number formatting library (referenced above as 2315).

**Comment by sanjuroj** [comment]
@jennyhavah This should now be fixed but it required certain conditions to recreate, which I couldn't quite nail down.  So if you manage to recreate it again, please try to note the context in which it happened (e.g. had you already edited the same result?  Was it a new result?).

**Comment by jennyhavah** [comment]
No longer able to reproduce the issue. I am consistently prompted for a rationale as expected.
