### ISSUE TITLE
IPTT landing page: Unexpected behavior related to zeroes in "enter number" field

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2352]
_Not a release blocker. Let's only fix for Goat Tree if it's low effort and not risky._

I stumbled on this by accident when I accidentally typed a zero instead of a 2 in the "Most recent X" numeric field. 

1. Go to IPTT landing page, select a QA program and Annual for target frequency.

2. Type a zero in the "enter number" field.

3. Try to backspace to clear out the zero. For me, the cursor is unresponsive when I backspace.

4. Try selecting and then replacing the zero with 2. That works.

5. But just out of curiosity, try hitting backspace again. I would expect the cursor to clear out the 2. For me, it doesn't. It replaces my 2 with a zero! And I can't backspace-clear that either.

Hopefully this is a localized problem. So far I don't see anything like this in the indicator form or result form.

**Comment by camgnostic** [comment]
(This is the behavior on qa and production as well)

What's expected behavior if I delete whatever number is in the field?  Should the "view report" button become disabled again?  What if I type in a number larger than the available number of periods?  Should it immediately change to the correct number or should it wait till the user clicks out of the field?  These behaviors are a result of us limiting the choices for that box to the actual number of "recent" periods available for a given program, but it looks like the behavior outside of those bounds wasn't clear.

**Comment by camgnostic** [comment]
Assuming a program is selected that has 3 annual periods that have passed (so 3 should be the maximum value for "show recent") and annual is the frequency selected:

- if I select "show recent" the box initially has "2" in the text box
- if I delete the "2" then there is nothing in the text box and the "view report" button is disabled and there is nothing in the text box (but the cursor remains there)

if I have an empty text box:
- if I try to type a 0 nothing happens (input is ignored)
- if I try to type a , or . nothing happens (input is ignored)
- if I try to type a 1, 2, or 3 I see that number displayed and the view report button is enabled
- if I try to type a number greater than 3, the number is displayed, but the view report button remains disabled, and as soon as I click out of the text box the number changes to 3 (the max)

if a text box has a number in it:
- if I try to type another number that brings it over the maximum number of periods, the number is displayed, but the view report button remains disabled, and as soon as I click out of the text box the number changes to 3 (the max)
- if I try to type a 0 or . or , nothing happens (input is ignored)
- if I select the numbers currently displayed and type a 0 , or . the input is ignored
- if I select the numbers currently displayed and type a 1, 2, or 3, the number is displayed and the view report button is enabled
- if I select the numbers currently displayed and type a number greater than 3, the number is displayed but the view report button remains disabled, and as soon as I click out of the text box the number changes to 3 (the max)

**Comment by jennyhavah** [comment]
Recapping what @camgnostic wrote in Slack, with an update to this piece:

> if I try to type another number that brings it over the maximum number of periods, the number is displayed, but the view report button remains disabled, and as soon as I click out of the text box the number changes to 3 (the max)

So leading 0  and any , or . is just not accepted as input (like you didn’t type anything, or like you typed a letter in a number field, also I’ll make sure we block e  and - cause I know sometimes number fields allow those) .  but other than that if I enter “1000”, the box will show “1000" and I can hit view report, but the report (and the most recent field in the sidebar) will be for the max recent periods.

**Comment by jennyhavah** [comment]
Cameron will also be fixing (and Jenny will QA) a couple other "most recent" issues:

Displaying the number in the IPTT sidebar version of "most recent" field. 

Showing the correct "most recent period" -- Cameron found an instance where it showed the last period of the program (in the future) instead of the most recent one.

**Comment by camgnostic** [comment]
Another bug to check when QAing: in a program that has completed, selecting a most recent value that is equal to or greater than the number of periods in the program, and ensuring that "most recent" is selected in the displayed report's filter bar (rather than show all)

**Comment by jennyhavah** [comment]
@camgnostic These issues are resolved:

1. I can comfortably clear out the "most recent" value field using the backspace key or highlighting and deleting.

2. I cannot type a period, comma, or zero as my "most recent" value.

3. When I enter a number of periods greater than the total, the IPTT loads with the total number of periods, and this number is reflected in the "Most recent" field within the filter panel.

I noticed one more (hopefully small) detail we need to fix on the IPTT landing page:

If I enter a value in "most recent and then toggle back to "show all", the "most recent" value field should be cleared.

**Comment by jennyhavah** [comment]
> If I enter a value in "most recent and then toggle back to "show all", the "most recent" value field should be cleared.

Issue fixed!
