### ISSUE TITLE
A couple of IPTT export errors

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2358]
The first error, we probably need to address. The second error, I'm thinking maybe not.

# KeyError at /indicators/iptt_api/iptt_excel/

For this Target versus Actuals report, I can download "This view" but get an error when I try to download all program data:

https://tola-activity-dev2.mercycorps.org/indicators/iptt_report/700/targetperiods/?frequency=3&start=0&end=4&groupby=1

Screenshot of the error:

![image](https://user-images.githubusercontent.com/33670923/81623841-7c286680-93a9-11ea-9e9d-1017a0660c31.png)

# 502 Bad Gateway

I suspect that it is **_an extreme edge case_**. Sharing this FYI but do not think we should go to extraordinary measures to address it if it is, in fact, as extreme as I suspect it to be.

So if I try to export the following Recent Progress report to Excel, I get a 502 Bad Gateway Error. BUT, please note that it is set to "Show all" and "Months" AND has an unusually high number of disaggregation categories. If I select fewer periods or choose Years instead of Months -- i.e. 3 time periods instead of 35 -- I am able to download the report.

https://tola-activity-dev2.mercycorps.org/indicators/iptt_report/585/timeperiods/?frequency=7&start=0&end=35

**Comment by camgnostic** [comment]
@jennyhavah  for the first one (crashing on the audit log) I'm submitting a fix right now (related to data entered before we changed what information we store being unexpectedly different) but the second one is that issue I mentioned where we're limited by openpyxl's _ridiculously inefficient_ merge cells algorithm (specifically their ridiculously inefficient "have we previously merged this cell" algorithm) and I can't get that faster without a pretty significant library change.

**Comment by jennyhavah** [comment]
@camgnostic In case it's helpful, I just encountered what appears to be the same bug when I tried to download all program data for the TolaData demonstration program.

This report: https://tola-activity-dev2.mercycorps.org/indicators/iptt_report/542/targetperiods/?frequency=2&groupby=1&columns=0&columns=1&columns=2&columns=3

![image](https://user-images.githubusercontent.com/33670923/81756958-1bb12c00-9472-11ea-8611-60aee88d8ff4.png)

**Comment by camgnostic** [comment]
super helpful - added a bit to the fix to catch this follow-on issue, should be up later today.

**Comment by jennyhavah** [comment]
One more example. This is a Recent Progress report (unlike other examples) for this program: https://tola-activity-dev2.mercycorps.org/indicators/iptt_report/665/timeperiods/?frequency=7&start=9&end=10&groupby=1

No filters applied.

![image](https://user-images.githubusercontent.com/33670923/81874879-c76e8080-9533-11ea-8918-5e58a6fe93fb.png)

**Comment by jennyhavah** [comment]
One more -- this is a program that HAS a results framework but is not grouping indicators with it.

https://tola-activity-dev2.mercycorps.org/indicators/iptt_report/614/timeperiods/?frequency=7&start=12&end=13

![image](https://user-images.githubusercontent.com/33670923/81876241-08b45f80-9537-11ea-969a-2dd0d5f2cd2b.png)

**Comment by camgnostic** [comment]
with the exception of the 502 bad gateway (this is the "you've hit the timeout limit of the server while waiting for your report to finish merging cells" error) all of the crashes on this page have been found, addressed, and re-tested (with successful downloads)

**Comment by jennyhavah** [comment]
Passed! No longer experiencing the KeyError crashes. Still getting timeout limits, but we are not addressing those for this release.
