### ISSUE TITLE
Program assignment from multiple countries breaks permission check

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#2362]
Reported by Barbara Willett, though Marie on Slack.  

Barbara was assigned a "high" permission level to a program from two different countries.  She was trying to access the RF builder for a new program but it kept booting her back to the country page.  

Turns out that the permission check that was being used to determine the access level a user has to a program failed when permissions were set from more than one country.  Short term fix is to use the maximum access level set from a country to see if the user has access to the RF level machinery.  In the long term, need to decide if the maximum level strategy is appropriate or if we need to track which country the user is trying to access different parts of the Tola functionality from.

**Comment by sanjuroj** [comment]
To test the fix, create a new program and assign it to two countries.  Assign a test user to that program through both countries, at a medium level.  If you navigate to one of the two country pages, you should get a "No indicators have been entered for this program." message.  If you then change the permission to "high" and refresh the page, the link "Start building your results framework and adding indicators." should appear, regardless of which country you're in.

**Comment by jennyhavah** [comment]
@sanjuroj Works as expected!
