### ISSUE TITLE
Excel layout issue for programs not grouping indicators by rf level

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2370]
Best I can tell, this Excel layout issue has to do with the fact that for programs not organizing indicators by rf level, we include an additional IPTT column with the OldLevel.

To replicate the issue, run a Recent Progress IPTT on the program Ann Viv Ansanm, that is not using the results framework. Export to Excel and unhide all disaggregation rows. Also try this with various combinations of columns hidden.

Note the alignment of the disaggregation rows.

Here are some examples of what I'm seeing:

![image](https://user-images.githubusercontent.com/33670923/81874276-685c3c00-9532-11ea-9ccc-6dfde8c6529e.png)

![image](https://user-images.githubusercontent.com/33670923/81874254-609c9780-9532-11ea-9ec9-fc6df93fdd92.png)

**Comment by camgnostic** [comment]
@jennyhavah I'm not sure what the problem is with this layout - I thought the disaggregation label was supposed to be right aligned next to the baseline column (or, if the baseline column is hidden, the LoP target column), and that's what I'm seeing here, unless I misunderstood specs?

**Comment by jennyhavah** [comment]
@camgnostic You're right! I was disoriented by the appearance of that "extra" column, but it is not wrong. Closing as it's not a bug.
