### ISSUE TITLE
Non-RF programs: Indicator rows appear to be missing in export and "only show categories w/results" ignored

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2371]
Testing programs not using the results framework and manual numbering, I ran a TvA report on this program:

https://tola-activity-dev2.mercycorps.org/indicators/iptt_report/552/targetperiods/?frequency=3&start=0&end=1

and did an export of the current view. When I do a side by side comparison, it looks like some indicators are missing in the export. For example, I don't see indicators 2 and 3:

![image](https://user-images.githubusercontent.com/33670923/81875394-07823300-9535-11ea-9901-8b4e340a4ef7.png)

Same problem with missing indicators for this program: https://tola-activity-dev2.mercycorps.org/indicators/iptt_report/585/timeperiods/?frequency=3&start=0&end=2&disaggregations=hide-categories&mr=1&columns=0&columns=1&columns=2&columns=3&columns=4

In addition, I selected "Only show categories with results" option, but this was ignored in the export. 

![image](https://user-images.githubusercontent.com/33670923/81875799-f685f180-9535-11ea-920b-d09a2521338c.png)

**Comment by jennyhavah** [comment]
@camgnostic Noticing similar issues with the system ignoring the "only show categories with results" filter when I export programs not using the results framework. (Maybe just coincidence, but so far I can't replicate with a program using the RF.)

Let me know if this ought to be a separate ticket.

**Comment by camgnostic** [comment]
these should be fine as a single ticket, it's almost certainly a related problem (but either way it's the same function in the code)

**Comment by camgnostic** [comment]
Sorting for non-RF programs fixed (for future dev reference: sort was on level_pk but not level_order)

Hide categories moved from disaggregation-level to category-level.

**Comment by jennyhavah** [comment]
@camgnostic I re-ran the examples from the original ticket and they look good. I found one additional discrepancy that may have to do with how we treat zeroes. 

Try running this report and then exporting: https://tola-activity-dev2.mercycorps.org/indicators/iptt_report/560/timeperiods/?frequency=7&start=0&end=29&disaggregations=hide-categories&columns=0&columns=1&columns=2&columns=3&columns=4

I have "only show categories with results selected. On the screen, it's including results of 0. In the export, it's not.

![image](https://user-images.githubusercontent.com/33670923/82080346-387b7880-9699-11ea-8be6-2668af6944fc.png)

**Comment by jennyhavah** [comment]
All issues fixed!
