### ISSUE TITLE
Inappropriate warning message on IPTT results form

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#2380]
To reproduce:
- open any IPTT (recent or TvA)
- open any indicator setup form (gear wheel) but do not save changes (click "x" or "cancel")
- open any results ~form~ table
- close that results ~form~ table (x in top right)
- behold the nonsensical pNotify warning message: 
![image](https://user-images.githubusercontent.com/7941355/82107542-7a2e1280-96dd-11ea-8fca-432e7f69d796.png)

**Comment by jennyhavah** [comment]
I'm unable to reproduce this error.
