### ISSUE TITLE
UI styling for IPTT landing page

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#239]
# This ticket should be tackled after #318 is done, because we're making significant changes to the layout and interaction for one of the report types.

You get to this page by opening the Reports menu in the top nav and selecting "Indicator Performance Tracking Table"
![image](https://user-images.githubusercontent.com/33670923/40456124-9ff3d78e-5ea4-11e8-8a99-8fa34e42d559.png)

## Show all/Most recent options (Periodic targets vs. actuals report)
- [x] 1. Right now, the Show all/Most recent toggle are inactive until you select something from both the Program and Period dropdowns. But they _appear_ to be active. All elements in that row need to look inactive when that is the case -- form elements and text labels. (Generally speaking, even in the mockups, I've been struggling to balance the two objectives of indicating inactive status while keeping the text reasonably legible.)
- [x] 2. When the Show all/Most recent _is_ active, you should be able to click in the text box and enter a number, and have the corresponding radio button auto-select. You should not have to first click "Most Recent" before you can enter a number.
- [x] 3. For all 3 dropdowns, I wonder if there needs to be that much space between the labels and their respective drop-down menus. Looks a little disconnected.
- [x] 4. Show all/Most recent: Add a bit more horizontal space between the two toggle options. (The label "show all" is too close to the radio button for "most recent".
- [x] 5. Can we make the Show all/Most recent toggle options more obviously connected to the Target Periods dropdown? Either by reducing the vertical distance between the menu and the sub-options, or by increasing the distance between the Program and Target Periods sections?

**Comment by jennyhavah** [comment]
@axoplasm Styling all looks good! Just wondering if there is an easy way to make the program menus respond more gracefully? Here's what I see now.

![image](https://user-images.githubusercontent.com/33670923/41620408-7d285390-73be-11e8-9ca2-d75481f4e60d.png)

**Comment by axoplasm** [comment]
OH UGH YUCK

I hate this stuff, can't believe I missed it

**Comment by axoplasm** [comment]
Oh it's that horrible old select2 plugin, there’s your problem

**Comment by jennyhavah** [comment]
Show all/Most recent are looking better:

![image](https://user-images.githubusercontent.com/33670923/41628064-b9d2f21e-73d7-11e8-9c3b-e244d73cbaaf.png)

We'll wait until after Winterhawks to address the program menu issue.
