### ISSUE TITLE
Indicators > Targets: Select target frequency option and sub-options

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#24]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Thursday Dec 14, 2017 at 05:22 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/14_

----

**Story:** When I select a target frequency option, the system asks me for any additional details it needs to generate the appropriate periodic targets.

![emptystate](https://user-images.githubusercontent.com/33670923/34121691-c10ca4f0-e3de-11e7-9830-a55c52098dbc.png)

**ACCEPTANCE CRITERIA**

1. In the Targets tab, underneath the Baseline field, is a **_Target frequency_** selection menu. 
1.1. I can type the first character (or ideally multiple characters) to quickly select the option I want.
1.2. **_Target frequency_** is a required field.
1.3. If I try to save changes without selecting a target frequency, I get a prompt: Please select a target frequency. If you have no intermediate targets, choose "Life of Program (LoP) target only."
2. The menu contains 8 target frequency options: Life of Program (LoP) only; Midline and endline; Annual; Semi-annual; Tri-annual; Quarterly; Monthly; and Event.
3. Depending on the option I select, the system either accepts the field as complete or generates additional required fields.
4. When I select _**Life of Program (LoP) only**_, the system accepts the target frequency field as complete.
4.1. Please spell out the full phrase followed by the acronym -- "Life of Program (LoP)" -- because the acronym is unfamiliar to many users, especially newer employees.
5. When I select _**Midline and endline**_, the system accepts the target frequency field as complete.
6. When I select _**Annual**_, **Semi-annual**, **Tri-annual**, **Quarterly**, or **Monthly**, the system requests the following:
6.1. **First target period begins:** Standard calendar-based date picker UI.
6.2. **Number of target periods:** This field is auto-populated with a 1.
6.2.1. The upper limit for this field is 12. If I type in a value higher than 12 and try to save, the system prompts me, "You can start with up to 12 targets and add more later."
6.3. All of these fields are required. If I leave one empty, I'm prompted to "Please complete this field."
7. When I select _**Event**_, the system requests the following:
7.1. **First event name:** Open text field
7.2. **Number of events:** This field is auto-populated with a 1.
7.2.1. The upper limit for this field is 12. If I type in a value higher than 12 and try to save, the system prompts me, "You can start with up to 12 targets and add more later."
7.3. All of these fields are required. If I leave one empty, I'm prompted to "Please complete this field."
8. With the exception of the Life of Program (LoP) only option, you cannot edit targets once you've saved changes. In all other cases:
8.1. The _Target frequency_ menu shows your current selection but is grayed out and inactive.
8.2. Sub-options are NOT displayed.
8.3. The only way to replace saved targets is to click the _Remove all targets_ link. 
8.4. For additional details about the LoP only exception, see ticket #30

| Target frequency options  | Illustration |
| ------------- | ------------- |
Frequency options menu  | ![image](https://user-images.githubusercontent.com/33670923/33978227-8e625254-e053-11e7-9b4f-2eb385b58dbb.png) 
Life of Program (LoP only)  | ![image](https://user-images.githubusercontent.com/33670923/33977711-f7572f30-e050-11e7-9540-3f2f2a2a8ad5.png) 
Midline and endline  | ![image](https://user-images.githubusercontent.com/33670923/33977978-72da884a-e052-11e7-90e1-6f8287c60820.png) 
Annual  | ![annualconfig](https://user-images.githubusercontent.com/33670923/34342557-b130ecf0-e968-11e7-889d-fb8600c2a891.png)
Semi-annual  | ![semiannualconfig](https://user-images.githubusercontent.com/33670923/34342558-bd9e719c-e968-11e7-84f1-5296bfee5e53.png)
Tri-annual  | ![triannualconfig](https://user-images.githubusercontent.com/33670923/34342559-c757f8c0-e968-11e7-8040-1c86e5874dbf.png)
Quarterly  | ![quarterly](https://user-images.githubusercontent.com/33670923/34342562-d2702656-e968-11e7-969d-443cf7853eef.png)
Monthly  | ![monthlyconfig](https://user-images.githubusercontent.com/33670923/34342563-dbed3d68-e968-11e7-8147-7159dce51207.png)
Event  | ![eventconfig](https://user-images.githubusercontent.com/33670923/34342565-e6cd6974-e968-11e7-960a-78db91bc4242.png)

**Comment by jennyhavah** [comment]
**Error handling**
1. When a tab is incomplete, display an error message: “Please complete all required fields in the [tabName] form.”
    1. Display a separate error message for each incomplete tab. (This is a note for future reference; right now Targets is the only one with required fields.)
2. Display this error message _above_ the indicator name instead of below it, with a small amount of vertical padding between the bottom of the error box and the indicator name.
3. All form field-specific validation error messages should be displayed in-line with the relevant fields. 
3.1. Please reference the wording in the ticket for each error message -- some are specific to the field while others are more generic. (e.g. “Please complete this field” instead of “‘Number of target periods’ is a required field.” (Note: I understand why you added the name of the field at the top of the page; we will no longer need that additional context if the message is in-line.)
4. Inconsistent capitalization of form fields: Only capitalize the first word. “Unit of measure”, not “Unit of Measure”. Exception is made for Tola- and MEL-specific jargon: Life of Program (LoP) target. When in doubt as to when something should be capitalized, you can always refer to mockups as a reference.
5. Right now, there is not much horizontal space for the form labels. Allow more characters for form labels, so that “Life of Program (LoP) target" does not wrap when your browser zoom level is set to "Actual Size."

**Comment by jennyhavah** [comment]
Please replace the form field "LOP Target" with the full phrase followed by the acronym -- "Life of Program (LoP)" -- because the acronym is unfamiliar to many users, especially newer employees.

**Comment by jennyhavah** [comment]
**Number of target periods:** This is a weird little thing. I was checking to make sure it doesn't accept letters. It doesn't let me type any letters _except_ for the letter "E". Only E! Not a big deal, just thought it was odd.

**Comment by sanjuroj** [comment]
In some cases the error message doesn't appear.  To recreate:
1. Create several periodic targets.  
2. Go to any target except the last one, enter a number, and hit the "Save Changes" button.  You should see the "Please enter a target value..."  error appear at the bottom of the table.  
3. Delete the number you just entered.
4. Now enter a number in the last row and hit the Save button.  The "Please enter a target value..." error message does not appear.

It doesn't matter what order you do this in, the bottom row seems to be a special case.

**Comment by jennyhavah** [comment]
> When I select Annual, Semi-annual, Tri-annual, Quarterly, or Monthly, the system requests the following:
~~6.1. First target period begins: Standard calendar-based date picker UI.~~
**6.2. Number of target periods: This field is auto-populated with a 1.**

I'm pretty sure this was working before. At this time, the "Number of target periods" field is no longer auto-populated with a 1 except in one specific and edge-casey scenario: I pick Midline and endline first, click "create targets" but don't save, then reopen the window and select any of the periodic options -- annual, quarterly, etc. The second time around, the "Number of target periods" field _is_ auto-populated with a 1.
