### ISSUE TITLE
Make radio button fill same blue color as links

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#244]
According to some sources, even in HTML5 it's not straightforward to do this.

https://stackoverflow.com/questions/45327086/how-change-the-color-of-the-radio-button

It's not difficult to set up the way the SO answer does, but setting the style so specifically could have unforeseen implications for other radio button displays.

**Comment by jennyhavah** [comment]
This is not at all important, certainly not worth any extra development attention. Closing the ticket.
