### ISSUE TITLE
IPTT filter panel and Indicators page: Replace select2 multi-select widget with a bootstrap widget

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#248]
**Affects:** IPTT filter panel and Indicators page.

This is the widget we'd like to use: http://davidstutz.de/bootstrap-multiselect/ with an example implementation here that I like: http://www.itidabhoi.org/demo/bootstrap-multiselect-dropdown/.

We need to make sure it is capable of replacing the existing widget in all places where it is currently used. (Only reports we need to worry about is Disaggregation -- the rest are going away very soon.)

## Desirable UI refinements
1. I'd like to use the includeSelectAllOption function.
2. Can the menu be styled to look more similar to our standard dropdown? Specifically -- text is left aligned while arrow is right-aligned.
3. Use #3366cc for checkboxes in selected state.
4. Use #0645ad for the row color when an item is selected.
5. Is it possible to have long options (such as long program names) wrap at some point, instead of stretching out the widget until it's huge?

## Where to deploy the widget of awesome?
In addition to replacing the multi-select drop-down menus currently used at the top of the home page, Program Indicators page, etc... ~Let's also take a look at replacing multi-select functions within our forms. For example, on the Indicators Setup form, we use several different flavors of multi-select. Can we replace some or all of these with the widget of awesome?~

**Comment by axoplasm** [comment]
@sanjuroj & @mahmoodkhan: There’s a block in `base.html` called `extra_js_in_header` but it seems to contain libraries that might need to be applied universally. (Every template I could find that overrides the base block includes at least `leaflet.js`)

I've been loathe to get into template structure so not sure what my question here is, other than what is the intent of `extra_js_in_header`?

**Comment by axoplasm** [comment]
Also todo:
- [ ] Find all instances of multiselect/select2 and standardize on this widget
- [ ] Fix the __reset__ button on filters (e.g. IPTT)

**Comment by jennyhavah** [comment]
@axoplasm For Winterhawks, we do not need to find all instances of multiselect/select2 and standardize on this widget. I've broken that out into a new ticket and assigned it to the Spillover project. #343

**Comment by axoplasm** [comment]
I'm not sure what last issue is above (`Check out the issue where all filters in the bottom section open and close when you click Apply`) — is this a browser flash before the multiselect “appears”?

I also welcome some thinking about what exactly “reset” should do on this screen. RN I'm thinking it should remove (actually “select all”) the filters in the light gray area

**Comment by axoplasm** [comment]
To answer my own question: we have determined that clicking “reset” will return the filter panel to the state that produced the current data display. __This is exactly the same as refreshing the page.__

**Comment by jennyhavah** [comment]
@axoplasm One remaining issue related to the Site filter. Sites are associated with indicators by way of the Results form; when you are adding results, you can select one or more sites in which the data was collected. This means that a single indicator can have multiple sites associated with it. Here's what that looks like:
![image](https://user-images.githubusercontent.com/33670923/41006406-35bb8ec0-68d6-11e8-9c13-7e62be0b98a6.png)

Right now, indicators with multiple sites are only returned if you check off _all_ the sites associated with it. We need it to return indicators as long as _any_ of its associated sites are checked.

**Comment by axoplasm** [comment]
I can make the “Site” field into a multiselect if we want. I’m worried about playing whack-a-mole with multiselects though.

As for the filtering problem, this sounds like something that needs to be fixed in the view. Maybe a job for @mahmoodkhan or @sanjuroj ?

**Comment by jennyhavah** [comment]
Looks like it's already multi-select with check boxes. Maybe it is just a filtering issue -- if you're not able to pull the kinds of results we need when users pick more than one site.

**Comment by axoplasm** [comment]
Everything but the filter are ready for testing

**Comment by jennyhavah** [comment]
I added task #364 to track the non-UI-related issue related to the results returned by the site filter, so that we can close this ticket.
