### ISSUE TITLE
Results pop-up: Remove Add a Disaggregation link

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#249]
We have some unresponsive links in the Collected Data form.

1.<s> Import Evidence from Tola Tables link: Does not launch the expected pop-up.</s> (see #396)
- [x] 2. Remove _Add a Disaggregation_ link.
~3. Add a Disaggregation link (also broken in production): Right now, it takes you to the full-page version of the Summary tab. I _think_, though I'm not sure, it's supposed to show you the disaggregation options we currently display in the Performance tab. Let's ask Mahmood what the original behavior was.~

**Comment by mahmoodkhan** [comment]
The consensus is to remove the link for adding 'disaggregation' from the date collected modal window.

**Comment by jennyhavah** [comment]
Link is gone!
