### ISSUE TITLE
Indicators > Targets: Create periodic targets (annual, semi-, tri-, quarterly, monthly)

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#25]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Thursday Dec 14, 2017 at 07:02 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/15_

----

**Story:** After I configure a periodic target frequency (Annual, Semi-annual, Tri-annual, quarterly, or Monthly), I can review all of my target periods and enter a target value for each one. This allows me to later associate collected data records with the correct periodic target.

**Note:** There are three other target frequency options that are addressed in other tickets: Life of Program (LoP) only (#33) , Midline/Endline (#35), and Event (#37).

**CONFIGURATION PRE-CONDITIONS**

![scrap2](https://user-images.githubusercontent.com/33670923/34457479-38eeb13a-ed66-11e7-9dd0-d5e32bf33280.png)

1. Open Targets tab of an indicator
2. Complete all required fields.
3. For _Target frequency_, select one of the periodic target options: Annual, Semi-annual, Tri-annual, Quarterly, or Monthly.)
3.1. Choose a start month for the first target period.
3.2. Enter a number between 1 and 12 for _Number of target periods_.
4. Click _Create targets_.

**ACCEPTANCE CRITERIA**

![annual2](https://user-images.githubusercontent.com/33670923/34457485-69b62dac-ed66-11e7-8492-6b4f09ec805f.png)

For additional illustrations of the target tables in the different configuration scenarios, [please visit the design wiki. ](https://learn.mercycorps.org/index.php/Tola:Indicator_Target_Configuration#Configuration_scenarios)

1. The _Target frequency_ menu displays my selection but is no longer editable. (I can see the other options but can't select one.)
2. _Target frequency_ sub-options are no longer displayed.
3. Under _Target frequency_, a table is generated with correct title: Annual targets, Semi-annual targets, Tri-annual targets, Quarterly targets, or Monthly targets.
4. Every periodic target has a dedicated table row. 
5. The syntax for periodic target names are correct: 
5.1. **Annual:** Year 1, Year 2, Year 3, etc.
5.2. **Semi-annual:** Semi-annual period 1, Semi-annual period 2, etc.
5.3. **Tri-annual:** Tri-annual period 1, Tri-annual period 2, etc.
5.4. **Quarterly:** Quarter 1, Quarter 2, etc.
5.5. **Monthly:** Spell out the full names of the month followed by the year (July 2018, August 2018, etc.)
6. Under each periodic target name is the correct date range, starting in the correct month and year. (Jul 1, 2018 - Jun 30, 2019). 
6.1. **Exception:** Monthly targets don't require date ranges, only the month and year.)
6.2. Date formatting respects local system preferences.
7. There is a target value field next to each period. 
7.1. Before a target value is entered, the form field displays placeholder text, "Enter target". You don't have to manually select the text to replace it with the number.
![scrap](https://user-images.githubusercontent.com/33670923/34176752-f9be447a-e4b5-11e7-8316-c9d0b5e2c1da.png)
7.2. The target value field only accepts numeric values.
8. All periodic targets must have a target value associated with them.
8.1. If you click _Save changes_ with one or more target fields left empty, you are prompted: "Please enter a target value for every period. Your target value can be zero."
8.2. This is a strict requirement. You must enter values in all target fields, or _none_ of your targets will be saved.
8.3. If you ignore the warnings or for whatever reason fail to enter all required target values, then the next time you open the Targets tab, the following things are true:
8.3.1. There is no table of targets. 
8.3.2. Target frequency is reset to its empty state, with all sub-options and _Create targets_ button hidden.
9. Life of Program target is displayed in the bottom row.
10. When you enter targets and save changes, the sum of targets is recalculated. 
10.1. **Note:** We do _not_ want to enforce the reconciliation of periodic target values with the LoP target value. For longer programs, it is unrealistic to forecast precise target values all the way out to year 4 or 5. A team may begin by setting targets for the first year or two, then add additional targets later on. In that case, it is expected that the sum of periodic targets won't match the LoP target for some time. 

**UI details**
1. Gray shade behind the table: #F5F5F5.
1. Table title is MC gray #54585A
2. All table borders are: #DBDCDE.
2.1. Ideally, only use horizontal borders in the table, not boxes.
3. All table rows have a white #FFFFFF background except for the bottom _Life of Program (LoP)_ target row which has no fill color (or a fill identical to background color #F5F5F5.)
3.1. Column containing red delete button has no fill color (or fill identical to background color #F5F5F5.)
3. _Add a [period name]_ plus button color and label text is #0083c0

**Comment by jennyhavah** [comment]
> Target frequency sub-options are no longer displayed.
This is not working yet.

**Comment by jennyhavah** [comment]
> Under Target frequency, a table is generated with correct title: Annual targets, Semi-annual targets, Tri-annual targets, Quarterly targets, or Monthly targets.

Looks like this isn't implemented yet.

**Comment by jennyhavah** [comment]
**Some aesthetic requests:**
1. Please add a gray line at the top of the first row.
2. Add a gray line between Sum of targets row and Life of Program row.
3. Add a gray line below Life of Program row. (The Sum of targets and Life of Program rows are the same height.)
4. Please left-align the periodic target names, Sum of targets, Life of Program.

![graylines](https://user-images.githubusercontent.com/33670923/34801709-f81aabf2-f61e-11e7-9dda-f0ee2f996de5.png)

![alignment](https://user-images.githubusercontent.com/33670923/34801865-9579dd96-f61f-11e7-9b83-c4dfb607bf96.png)

**Comment by jennyhavah** [comment]
> All periodic targets must have a target value associated with them.
8.1. If you click Save changes with one or more target fields left empty, you are prompted: "Please enter a target value for every period. You can enter a target value of zero."

It's important to include all of this context. Right now we're using the standard "Please complete this field" messaging immediately below the row. There isn't enough room to elegantly display the longer message, and it looks a little weird when the text box moves up to accommodate the message. I believe I've seen a small pop-over in use somewhere else in the UI -- it allows for more text and doesn't displace the form field. Is that something we could employ here? If not, let's brainstorm other options.

**Comment by jennyhavah** [comment]
Unexpected behavior: Additional targets are generated if I edit the Life of Program target after saving target periods. To reproduce:

1. Create some periodic targets, enter values, and save.
2. Now, edit the LoP target up or down and save.

**Expected behavior:** The new LoP target value is saved. Nothing happens to the periodic targets table.
**Observed behavior:** 
1. The system generates additional periods. 
2. It seems to be generating the same number of periods initially created. If originally create 2 periods, it'll add 2 every time I change the LoP.
3. The original periods are duplicated, names and all I.e. it goes Year 1, Year 2, Year 1, Year 2, Year 1, Year 2.
3. There is no workaround. Even if you close the window without saving, it saves the unexpectedly auto-generated periods. You can't edit the LoP back to its original value.

**Comment by jennyhavah** [comment]
**Visual UI details:**
1. Target values should be right-aligned. (They're currently left-aligned.)
2. Please add a gray line at the top of the first row.
3. Add a gray line between Sum of targets row and Life of Program row.
4. Add a gray line below Life of Program row. (The Sum of targets and Life of Program rows are the same height.)
5. Please left-align the periodic target names, Sum of targets, Life of Program.
6. Don't capitalize "target" in the phrase "Life of Program (LoP) target". ("Life of Program" is an acronym-ized catchphrase, which is why the word "Program" is capitalized, but "target" is not.)

![graylines](https://user-images.githubusercontent.com/33670923/34801709-f81aabf2-f61e-11e7-9dda-f0ee2f996de5.png)

![alignment](https://user-images.githubusercontent.com/33670923/34801865-9579dd96-f61f-11e7-9b83-c4dfb607bf96.png)

**Comment by mahmoodkhan** [comment]
@jennyhavah I gave "thumbs up" to the comments that are addressed and fixed.
