### ISSUE TITLE
Program Indicator List view: Setting reporting period start and end months

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#258]
## Background context
See #227: Pull program start and end dates from GAIT and use them to set reporting start and end months.

## UI changes to Program Indicator List view
In order to afford the interactions required in this story, we need to update the "program container" that users click to reveal and hide the program's list of indicators.

Here is how it looks today:
![image](https://user-images.githubusercontent.com/33670923/39640979-812dbbd0-4f81-11e8-9e93-238fabddfceb.png)

Here is the updated UI:
![image](https://user-images.githubusercontent.com/33670923/40021652-4d7cb506-577a-11e8-96db-b8ef7c1ccb4e.png)

## Acceptance criteria
The program container still has two rows, but I've moved some items between rows, made some adjustments to the layout, and added a new "Reporting period" link.

### Top row

- [x] 1. There are two columns. The left column is much wider than the right column, in order to give long program names more room.
- [x] 2. Left column includes the program name that is permitted to wrap instead of being truncated as it is today.
- [x] 3. Right column includes only the New Indicator button, which I've renamed "Add indicator". (Label change is based on Fruit Basket feedback.)
- [x] 4. The top row no longer includes a "Grid/Print report" button.

### Bottom row
- [x] 1. The bottom row now has two columns.
- [x] 2. In the left column, instead of a button, the "# Indicators" open/close interaction is now more like a tree behavior, with a right-facing arrow next to the number of indicators when the container is closed, and a downward-facing arrow when it is open. Like so:
![image](https://user-images.githubusercontent.com/33670923/39641467-1fc0e226-4f83-11e8-959b-e147cd2ffd9a.png) ![image](https://user-images.githubusercontent.com/33670923/39641470-22f15f20-4f83-11e8-906a-4f4ff4f89f68.png)
(Incidentally, we will use this same type of interaction for opening and closing disaggregations in the Collected Data record.)
- [x] 3. In the right column are two links separated by a pipe sign.
- [x] 3.1. The left link says "Indicator plan" and links to what we were formerly calling "Grid/Print Report." (We had feedback that the current phrasing is not intuitive to users.)
- [x] 3.2. "Reporting period" opens up our new reporting period modal, described below.

### Reporting period modal
Clicking the "Reporting period" link launches a configuration modal that communicates reporting period options and permits the adjustment of program reporting start and end dates.
![image](https://user-images.githubusercontent.com/33670923/40947677-d105391c-6818-11e8-9ce5-cdce0d8c613e.png)

- [x] 1. Here is the descriptive text under the "Reporting period" page title: The program reporting period is used in the setup of periodic targets and in Indicator Performance Tracking Tables (IPTT). TolaActivity initially sets the reporting period to include the program’s official start and end dates, as recorded in the Grant and Award Information Tracker (GAIT) system. The reporting period may be adjusted to align with the program’s indicator plan.
- [x] 2. Here is the descriptive text under the start and end dates _BEFORE any annual, semi-annual, tri-annual, quarterly, or monthly targets are set up_: While a program may begin and end any day of the month, reporting periods must begin on the first day of the month and end on the last day of the month. Please note that the reporting start date can only be adjusted before periodic targets are set up and a program begins submitting performance results. The reporting end date can be moved later at any time, but can't be moved earlier once periodic targets are set up.
- [x] 2.1. Here is the descriptive text under the start and end dates _AFTER any annual, semi-annual, tri-annual, quarterly, or monthly targets are set up_: While a program may begin and end any day of the month, reporting periods must begin on the first day of the month and end on the last day of the month. Please note that the reporting start date can only be adjusted before targets are set up and a program begins submitting performance results. Because this program already has periodic targets set up, only the reporting end date can be moved later.
- [x] 3. GAIT program dates are auto-populated directly from GAIT and may not be modified.
- [x] 4. The **reporting start date** can only be modified _before any targets are set up._
- [x] 4.1. When the reporting start date can no longer be modified, that form field is disabled, while the end date is still editable, like so:
![image](https://user-images.githubusercontent.com/33670923/40947683-deefb4c6-6818-11e8-81ed-eda835391a1e.png)
- [x] 5. Changing the **reporting end date** will be restricted if any annual, semi-annual, tri-annual, quarterly, or monthly targets are set up. In this case, the reporting end date can be moved to no earlier than largest start date of all of the periodic targets associated with that program.  (That's because once targets are set up, moving the end month earlier will "cut off" existing target periods.) ~~The **reporting end date** can only be moved _earlier_ BEFORE any annual, semi-annual, tri-annual, quarterly, or monthly targets are set up. (That's because once targets are set up, moving the end month earlier will "cut off" existing target periods.)~~
- [x] 5.1. The date picker prevents users from moving the end month earlier after periodic targets are set up. 
- [x] 6. The reporting end date may be moved _later_ at any time. This has repercussions for the Program indicators list page and target setup views that will be addressed in one or two separate tickets.
- [x] 7. Upon clicking "Save changes", our standard green confirmation bar appears with the message, "Success. Reporting period changes were saved."

# Additional error conditions and edge cases
## User attempts to enter a reporting end date that occurs prior to the start month
- [x] Can we handle this similarly to how we handle it in the filter panel? That is, you only see the months available for the currently selected program year?

## Either or both program dates are missing in GAIT
- [x] 1. In the GAIT program dates section, replace the date or dates with the word "Unavailable" in our standard red error color -- #DD0000
- [x] 2. Start month and End month fields are empty ~and disabled~ but still editable.
2.1. Note: The plan is to prompt users to complete these fields on the Indicators page. (See ticket #350.)

# Testing
Some of the scenarios to test are outline below.  Please add to them as needed. Note that the term "dated periodic target" refers to any periodic target frequency type with start or end dates (Monthly, Quarterly, Tri-annual, Semi-annual, and Annual). The other types of period frequencies (LOP, Mid/End-line, and Event) aren't associated with dates.

## Reporting start date
- [x] Start period is disabled if there are any dated periodic targets for any of the indicators associated with the program.
- [x] The datepicker prevents users from entering a start date greater than the end date, if one exists.  

## Reporting end date
- [x] If there are no dated periodic targets, the datepicker should prevent users from entering a value that is less than the start date, if one exists.
- [x] If any indicator associated with the project has dated periodic targets, the datepicker should prevent users from entering a date the is less than the maximum start date of all of the target periods.

Here's an example for the two tests above.
- A program is created with a reporting start date of Jan 1, 2018 and a reporting end date of June 30, 2019.  At this point, a user should be able to select any reporting end date >= Jan 31, 2018.
- An indicator is created with annual targets.  Two periods should be automatically created (Jan 1, 2018 to  Dec 31, 2018, Jan 1, and 2019 to Dec 31, 2019).  At this time, the user should be able to select a reporting end date any time >= Jan 31, 2019 (i.e. they could move the reporting start date up by 5 mos).  
- A second indicator is created with quarterly targets. Six periods should be automatically created with the last one being Apr 1, 2019 to Jun 30, 2019.  Now the user should be able to choose a reporting start date no earlier than April 30, 2019.  This is because April 1, 2019 is the new maximum start date across all of the periodic targets.

**Comment by jennyhavah** [comment]
Note: We may need to remove the sentence "The reporting end month can still be extended." and update the prior sentence to read "start and end months". It depends on what happens with tickets #263  and #264.

**Comment by jennyhavah** [comment]
@sanjuroj I no longer seem to be able to access the reporting start and end date pickers. I remember seeing it a little while ago. But now when I click into the box, the date picker does not appear -- regardless of whether there is already a date in there or it is empty. 

I also notice some auto-select type behavior. If I merely tap into a field and then tap or tab out, it auto-populates the fields with what appears to be a random date, but what I'm guessing is a date from a different program. I get the same auto-populated date regardless of program. Similarly, if I don't do anything except click "RESET" in a program, it auto-populates _both_ date field with what I assume are dates from some other program.

While you're in there, please make the calendar icon active if that's easy to do. (Please don't spend more than 5 or 10 minutes on it though -- it's low priority.)

**Comment by jennyhavah** [comment]
The reporting start and end date fields should not auto-select the current month. It should behave similarly to the date picker in the Indicator Targets tab, in that I can back out of interacting with the date picker and not have it auto-populate if I do the following:

Click Esc key
Click Tab key
Click the mouse anywhere outside the date picker field.

**Comment by jennyhavah** [comment]
We don't need the "Today" button. (Due to the auto-select being turned on, I can't see the date picker anymore in the Targets tab to check if the Today button is included in that instance, but I don't recall it being there.

![image](https://user-images.githubusercontent.com/33670923/41139040-14298544-6a9a-11e8-83a9-f87a8f531024.png)

**Comment by jennyhavah** [comment]
Still having issues with the Reset button.

**Comment by hannalcamp** [comment]
Everything except the Reset-related issues is validated.
