### ISSUE TITLE
Indicator setup Targets tab: Updates related to new reporting date ranges

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#263]
**Related issues:** 
#258 Program Indicator List view: Setting reporting period start and end months
#227 Pull program start and end dates from GAIT and use them to set reporting start and end months

## Annual/Semi-annual/Tri-annual/Quarterly/Monthly targets
**Precondition:** Complete all required fields on the targets tab and select Annual, Semi-annual, Tri-annual, Quarterly, or Monthly from the Target frequency menu.

- [x] 1. There is no longer a "First target period begins" field. (The system already knows the reporting start month for all indicators in the program.)
- [x] 2. There is no longer a "Number of target periods" field.
- [x] 3. The only thing left under the Target frequency menu is the _Create targets_ button.
- [x] 4. When I click the _Create targets_ button, the system generates all target periods between the program reporting start month and end month.
- [x] 4.1. The correct number of periods is generated.
- [x] 4.2. The date ranges for all target periods are correct.

## LoP only, Midline/Endline, and Event targets
- [x] 1. There are no changes to how these targets are generated.
- [x] 2. Sub-options are preserved for Event targets. The "First event name" and "Number of events" fields are still available.

## Adding and deleting target periods: Updated rules
Going forward, we are not permitting indicators to have varying numbers of target periods. Any target period can have a value of zero if there is no measurement occurring. But target periods must exist for the duration of the reporting period, for all indicators. Following are the effects on all target frequency types.

### LoP only
No changes. It is not possible to add or delete target periods.

### Midline and Endline
No changes. The following should be checked for regressions:
- [x] 1. It is not possible to add or delete target periods. 
- [x] 2. The "Remove all targets" option remains available.
- [x] 3. UI detail: Please add some padding between the bottom of the table and the top of the box below for both # and % variations. (Right now there is not enough space.) Make sure this doesn't mess up the spacing for other target frequencies.

### Event targets
No changes. The following should be checked for regressions:
- [x] 1. Red X icons still appear for all Event targets and you can manually delete them one at a time. 
- [x] 2. The "Add an event" button still appears, and you can manually add events one at a time. 
- [x] 3. The "Remove all targets" option remains available.

### Annual/Semi-annual/Tri-annual/Quarterly/Monthly targets
- [x] 1. Remove the "Add a period" button. It is no longer possible to manually add targets one at a time. (This is now done at the program level.)
- [x] 1.1. UI detail: Please make sure there is enough spacing between the bottom of the target table and the top of the #/% options box below for both # and % indicators. (Once we remove the "Add" button, I'm guessing we'll have a similar spacing issue as Midline/Endline.)
- [x] 2. Remove the red X button inside the targets table. It is no longer possible to manually delete individual targets. (Note: This feature will return in the future if we introduce the ability to move the program end month earlier after target periods are already added.)
- [x] 3. The "Remove all targets" option remains available.

**Comment by hannalcamp** [comment]
Validated for all the target periods (where relevant) and indicator scenarios.
