### ISSUE TITLE
Indicator setup > targets tab > Dates formatted differently depending on where that portion of the table is rendered

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#267]
# Double check if this is still an issue

Broken off from another story:
- [ ] The portion of the table that is created as a result of a Create Targets click is rendered by the server but the portion created by an Add new thing click is rendered by the browser.  Can / should they  be unified?
- [ ] The dates being rendered by the server are being displayed with a leading 0 for the days.

**Comment by jennyhavah** [comment]
(Capturing a bit more detail on the dates item here, so I can close a duplicate issue.) We seem to have a recurrence of issue #79 on the Targets tab of the Indicator setup form

Here is a recent snapshot from indicator 1991 on the demo server; note the difference in formatting between the 5th and 6th period (that was manually added.

![image](https://user-images.githubusercontent.com/33670923/39953256-9389685c-555c-11e8-88ba-37e4efee3c42.png)

**Comment by jennyhavah** [comment]
Now that we automatically generate time-aware periods, there's no such thing as "adding a year" anymore. Closing as no longer relevant.
