### ISSUE TITLE
Analysis of indicators: non-numeric entries for LoP target and baselines

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#27]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Thursday Dec 14, 2017 at 18:23 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/17_

----

We have two fields in the Indicators setup dialogue that we hope to change so that they only accept integers -- no letters or special characters. We need to do some analysis on existing indicators to figure out how many have non-integer values that need to be updated. 

The Excel file is attached. It includes all indicators currently in the system: 
[indicators.xlsx](https://github.com/mercycorps/TolaActivity/files/1623261/indicators.xlsx)

For an example of the output we need from this ticket, please see https://docs.google.com/a/mercycorps.org/document/d/1Uvvu-51Qf2UzSR7oqJ-GaN5a3RLdYJ6d-AXns48tCmQ/edit?usp=sharing

**These are the questions we need to answer:**
1. How many indicators have a **Baseline** entry that is not an integer?
1.1. What are the formatting conventions of these non-integer entries? (See examples in notes.)
1.2. How many indicators use each of these formats?
2. How many indicators have a **LOP target** entry that is not an integer?
2.1. What are the formatting conventions of these non-integer entries? (See examples in notes.)
2.2. How many indicators use each of these formats?

**NOTES**
1. Here are some examples of formatting conventions: 01, 40%, number and unit of measure, N/A, description of calculation, $50,000, 0.2. 
1.1. The goal of cataloguing formatting conventions is to consider how we could batch-convert some of these. For example, the convention $50,000 could be converted to 50,000 in the LOP target field and "currency" in the unit of measure field.
2. The goal of counting the frequency of each formatting convention is to identify those with the highest frequencies that would be most worthwhile to address with batch processing scripts and such.

**Comment by sanjuroj** [comment]
@esinn @jennyhavah I've updated the Google doc above with the analysis. I think it would be possible to automatically convert many of these numbers.

**Comment by jennyhavah** [comment]
Thanks, @sanjuroj. I am closing the issue.

**Comment by kurtwall** [comment]
Dropping this note here to indicated I've reviewed this for inclusion in the test suite.
