### ISSUE TITLE
Analysis of old targets that were associated with individual data collection records

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#28]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Thursday Dec 14, 2017 at 18:42 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/18_

----

We have a number of targets associated with individual data collection records, that I'll refer to as OLD_TARGET. We no longer display the individual targets in TolaActivity, but need to figure out what to do with their values, if anything.

The .xlsx file is attached. 

[OLD_PERIODIC_TARGETS.xlsx](https://github.com/mercycorps/TolaActivity/files/1612411/OLD_PERIODIC_TARGETS.xlsx)

For an example of the output we need from this ticket, please see https://docs.google.com/a/mercycorps.org/document/d/1Uvvu-51Qf2UzSR7oqJ-GaN5a3RLdYJ6d-AXns48tCmQ/edit?usp=sharing

**These are the questions we need to answer:**
1. How many data records have old_targets associated with them? (Column B.)
1.1. How many _indicators_ are these records associated with? 
1.2. How many _programs_ are these records associated with? 
2. In what percentage of cases is the OLD_TARGET value identical to the LOP target? (Column B equals column F.)
2.1. These are the records we can ignore, since there is nothing to convert into periodic targets.
3. In what percentage of cases is the OLD_TARGET value identical for every record associated with the indicator? 
3.1. These are records that might present opportunities for batch-processing.

**Comment by sanjuroj** [comment]
@jennyhavah @esinn I've updated the Google doc linked above with the results of the analysis.  There's a bit more I could do (i.e. count how many of the targets have collection dates), but I've probably spent more time than I should on these and wanted to move on to other things.  If we decide to try to make use of the target values, I can complete the analysis and create a script to do the work.

**Comment by jennyhavah** [comment]
Thanks, @sanjuroj. I am closing the issue.
