### ISSUE TITLE
Program Indicators page: Indicator rows

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#284]
**Note:** The results table is tackled separately in #223.

## Before/After

Here's what we have now:
![image](https://user-images.githubusercontent.com/33670923/41174854-1b6f1492-6b10-11e8-9958-5a3afc5a8fb5.png)

Here's what I have in mind:
![indicatorbrowse](https://user-images.githubusercontent.com/33670923/40073835-d4c3c0a6-582c-11e8-8ffc-faa62f1ed38f.png)

## Opening and closing the Results table
Within the indicator rows, how do we handle opening and closing of the enclosed Results table? 
- [x] 1. Instead of using the indicator name to open up the indicator setup modal, I'd like to use the same gear icon we're using on the IPTT report.
- [x] 2. Instead of the teal results (#) button, I'd like to use the indicator number and name as a large click area to open and close the Results table. (It is not important to know the number of results ahead of time.)
2.1. In my mockup, to make this open/close function obvious, I use open/close arrows next to the indicator number. The challenge with this approach is that indicators are not required to have numbers and frequently do not. And yet, if there _is_ a number, we always want it to appear first before the indicator name. So... How do we avoid awkwardness when there's no number and a gap between the icon and the indicator name?

# Updated order and content of Indicator rows
![image](https://user-images.githubusercontent.com/33670923/39150600-b9fc40f4-46f7-11e8-8ac0-c9150bb28f14.png)
- [x] 1. The desired order and labeling of columns mimics that of our IPTT report: No., Indicator, Level, Unit of measure, Baseline, Target, Actual, % Met.
1.1. Actual and % Met require calculations on the back end, and were move into stretch goal ticket #390. Not a release blocker.
- [x] 2. I've removed the Type and Sector columns; they are superfluous metadata in this context.

# Styling details
- [x] 1. In my mockup, I've attempted to tighten up the layout and increase information density while keeping everything legible. By "tighten up" I mean playing with the spacing to allow more rows to be visible without scrolling, while still paying attention to white space, adding enough to differentiate columns and rows. I also removed a number of (what I consider to be) extraneous boxes around things.
- [x] 2. I'm using white for the background of indicator rows, to make them stand out from the F5F5F5 gray background. 

# Indicators without targets
When there are no targets set up, this is what you see: 
![image](https://user-images.githubusercontent.com/33670923/41175262-5c0ba212-6b11-11e8-867e-82b66e84da11.png)
- [x] Fix the extra floating line above target
- [x] Background color should be consistent with F5F5F5 color we're using for these rows generally. (It's white right now.)

**Comment by axoplasm** [comment]
@jennyhavah What happens when you click on a link (not "View Project" or "Project") in the Evidence column? @sanjuroj thinks that should open the evidence document

**Comment by jennyhavah** [comment]
@axoplasm Correct, the evidence appears in the form of a link directly to the document. Here's what it currently looks like in production:

![image](https://user-images.githubusercontent.com/33670923/41371529-7a8872c8-6eff-11e8-9487-5ec846f371e1.png)

The link is taken from the URL field of the Document form:
![image](https://user-images.githubusercontent.com/33670923/41371563-98140b2c-6eff-11e8-8297-7209a1787472.png)

**Comment by axoplasm** [comment]
Re item 2:

> 2. Instead of the teal results (#) button, I'd like to use the indicator number and name as a large click area to open and close the Results table. (It is not important to know the number of results ahead of time.)

I punted on this and put the toggle to the left of the column name and left the no. field alone. There's a slightly-tricky jQuery problem here in having two targets (the no. column and the name column) driving a single event (unrolling the indicator targets v actual table)

(The styling is still unlovely and I'd like to have that toggle hang so plz disregard visual styling)

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/169060/41383015-8094d020-6f23-11e8-9267-d2a4843ab662.png">

**Comment by jennyhavah** [comment]
@axoplasm What if, instead of putting the No. in a dedicated column, we treat the number as a variable that we concatenate with the title, like so:

► {indicatornumber}{indicatortitle}

And if there's no number, then you'll only see the title. This would allow the arrow to be flush left at all times and address the ugly gap problem when there's no number.

**Comment by axoplasm** [comment]
That would work. I was also thinking about scannability on the No. column, do you think that will be an issue?

**Comment by jennyhavah** [comment]
@axoplasm Not sure I understand how it would affect scanning, since the No. column would be gone entirely, so there wouldn't be a ragged edge with empty blocks of space. Here's what I envisioned:

## Before 
No. has a dedicated column
![image](https://user-images.githubusercontent.com/33670923/41423678-cf253148-6fb0-11e8-99cc-725d202bbb29.png)

## After (Indicator with a number)
No. column is gone. Number is inserted into the string of the Indicator column.
![image](https://user-images.githubusercontent.com/33670923/41423801-2d7374c6-6fb1-11e8-8cae-7d70668d079e.png)

## After (Same indicator if it had no number)
![image](https://user-images.githubusercontent.com/33670923/41423823-3a001384-6fb1-11e8-8991-914055f4fa75.png)

**Comment by axoplasm** [comment]
I’ll push this for review in a bit, here’s what it should look like:

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/169060/41482829-ae13b2fa-708b-11e8-8627-1192053ef050.png">

**Comment by jennyhavah** [comment]
When I save changes in the indicator setup form, the open/close arrow disappears. (It reappears upon reloading the page.)

![image](https://user-images.githubusercontent.com/33670923/41490116-6db9edca-70a7-11e8-9891-0dc0eecc9a5e.png)

**Comment by axoplasm** [comment]
The “disappearing arrows” bug should be fixed in the next deployment.

**Comment by jennyhavah** [comment]
Disappearing arrow bug is fixed!
