### ISSUE TITLE
IPTT report: UI refinements

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#285]
This ticket addresses UI refinements to the IPTT table only. Refinements to the filter panel are addressed in #298.

# UI refinements
- [x] 1. Always bottom-align the header row. It appears to be bottom-aligned for the Actuals-only version, but that's not the case for the Periodic Targets version. Here's the worst-case example for Midline/Endline that has no date ranges:
![image](https://user-images.githubusercontent.com/33670923/41310238-d18477fe-6e35-11e8-88ae-0311f629c36f.png)
- [x] 1.1. Not sure if the program name is part of the table header row or not; if it is, seems like it'd be good to bottom-align it as well.
- [x] 2.  Add some vertical space between the top nav bar and the page title ("Indicator Performance Tracking Table")? Feels crowded.
- [ ] ~3. Add some padding between the right edge of the table and the right edge of the browser to make it more obvious when you've reached the last column of data.~
- [x] 4. The page title is appearing a second time underneath the table, for unclear reasons. Mahmood says, "I don’t know if it will be accessible if it’s hidden. That’s the default implementation from bootstrap. There might be ways to make it work without it being visible. Other elements also have accessibility tags that I have started to incorporate but they’re hidden. For some reason, the table caption is not."
- [x] 5. Thoughts on an icon to replace the three vertical dots, that better communicates "Yummy data details here, click on meee?"

# Original mockups for reference

## Program indicator overview
![ipttprogramindicatoroverview](https://user-images.githubusercontent.com/33670923/40074346-3bae10b8-582e-11e8-86f7-debb1a134458.png)

## Periodic target overview
![ipttperiodictargetoverview](https://user-images.githubusercontent.com/33670923/40074360-4324d958-582e-11e8-8e7b-9202f8b35e99.png)

**Comment by axoplasm** [comment]
> 5. Thoughts on an icon to replace the three vertical dots, that better communicates "Yummy data details here, click on meee?"

I went with a little table icon:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/169060/41626247-78783dd0-73d0-11e8-987d-321c939db547.png">

**Comment by axoplasm** [comment]
> 3. Add some padding between the right edge of the table and the right edge of the browser to make it more obvious when you've reached the last column of data.

Due to some overflow issues (related I think to the sliding filter panel), I can't add horizontal space around the table. basically, the table IS the page. Can we defer?

**Comment by jennyhavah** [comment]
Yep yep yep! Any other changes coming, related to this ticket?
