### ISSUE TITLE
Adding evidence to a percent indicator in non-chronological order results in wrong value being used

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#290]
For an indicator with a UOM type of percent, from the indicator list page, if I add results in non-chronological order, the last result I entered is being used for the period's Actual value, rather than the result that is chronologically last.
<img width="921" alt="non-chron" src="https://user-images.githubusercontent.com/6685499/40156258-2af5eb0e-594d-11e8-9a8f-02eb188ff46a.png">

**Comment by mahmoodkhan** [comment]
This is how it is supposed to work. I remember having it in chronological order but then had to spend a bit of time to get it to work this way :)

**Comment by jennyhavah** [comment]
I think we may have a misunderstanding here... The data records should always be displayed in chronological order, AND you should always see the latest available result, _chronologically speaking_. It doesn't make sense that June 1 comes after June 22. It will sometimes be the case that records are back-dated, and they still need to appear in chronological order.

**Comment by mahmoodkhan** [comment]
Sorry, I had not yet deployed changes to demo yesterday. I just did. Should be fixed.

**Comment by jennyhavah** [comment]
Fix validated.
