### ISSUE TITLE
Move "delete data record" function into the Results form itself

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#295]
Also see #304 -- may make sense to do these together. Also, in case you noticed how sucky the deleting flow is right now, I have a separate ticket #339 that deals with the usability issues around deleting. We don't have to address those issues for Winterhawks.

Deleting results data shouldn't be a highly visible and trivial action. My thinking is that we treat deleting data the same way we're treating deleting an indicator, as described here: #143. Instead of a trash can in every data row, we put a "Delete results" on the Results form itself.

Here's how it currently looks on the Indicator setup form, for context:
![image](https://user-images.githubusercontent.com/33670923/40688549-59b9ba0a-6353-11e8-8c06-2d539774c925.png)

**Comment by axoplasm** [comment]
I have a stub for this design BUT! I’m not (easily) able to wire the actual delete action onto the form itself. (Ironically this would be easy for me to figure out on the screen where we are removing the delete button). Tag @sanjuroj or @mahmoodkhan for help 

Final product will look like this:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/169060/41259286-ef0534fc-6d87-11e8-98f6-0e5963edfba1.png">

**Comment by jennyhavah** [comment]
@axoplasm Please change the wording to "Delete these results". (The page is being renamed "Results", as per #304)

**Comment by sanjuroj** [comment]
In concept it's similar, I'll take the issue.

**Comment by jennyhavah** [comment]
> Instead of a trash can in every data row, we put a "Delete results" on the Results form itself.

@axoplasm Please change "Delete this result" to "Delete results".

**Comment by mahmoodkhan** [comment]
The "Delete this result" link in the collected_data modal was breaking because line 361 was trying to create a url with `id` but it is not defined since it is a new record and the `id` is not yet generated. I made a temporary fix to get the modal to load at least by removing the link. See 787cec75fe4faeecde6c7d269fdd0105012f5e6e

**Comment by sanjuroj** [comment]
I'll take another look at it.

**Comment by jennyhavah** [comment]
@sanjuroj While you're in there, can you change "Delete this result" to "Delete results"?

**Comment by sanjuroj** [comment]
Will do.

**Comment by jennyhavah** [comment]
Link text says "Delete results" and consistently takes me to the delete confirmation page. Validated.
