### ISSUE TITLE
IPTT filter panel: UI refinements

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#298]
This ticket addresses UI refinements to the IPTT filter panel. Refinements to the table itself are covered in #285.

1. It should look and feel as if you are sliding the filter panel open and closed, with the table following along for the ride.* Right now, the table appears to be sliding _over_ the filter panel. 
1.1. *Important: We do not want the filter panel sliding _over_ the table instead, because it will hide the indicator names, and we want people to immediately see the results of their filtering without repeatedly opening and closing the panel. The idea is that the filter panel appears to exit stage left, with the table following along, sliding into position at the left edge of the page. And vice versa, if you click to open the filter panel, the data table slides right, with the filter panel chasing it.
2. Table should not disappear when the filter panel is open and the browser window is narrowed. (It appears to be wrapping onto a new row underneath the filter panel.
3. If you reload the page with the filter panel open, it should stay open. If you close the filter panel and reload the page, it should stay closed.
4. The current gear icon in its own row is from an older version of the design, and we got feedback that it's too subtle and too hard to click on. I updated to a large square gear button, but it could be something else entirely -- just needs to be highly visible with a large click surface.

# Filter panel open: Program indicator overview
![ipttprogramoverviewfiltersopen](https://user-images.githubusercontent.com/33670923/40074350-3ead4c98-582e-11e8-8687-568758600226.png)

# Filter panel open: Periodic target overview
![ipttperiodictargetoverviewfiltersopen](https://user-images.githubusercontent.com/33670923/40074364-45059e10-582e-11e8-9694-85c564e29ca9.png)

**Comment by axoplasm** [comment]
Comments re tasks above:

1. The Bootstrap **collapse** component works by reducing the width of the collapsing element, element’s contents remain the same width. This is what produces the illusion of the non-collapsing elements “sliding over” the collapsing ones. I agree it would be preferable to push the sidebar off-canvas (or simulate the same), and I think this is a global problem with Bootstrap’s collapse component. This would require stubbing in our own collapse component for Bootstrap’s. Probably a 4-hr task. My 20min fix was to hasten the transition for collapse elements so the illusion is not so apparent. I created a parking lot (fruitbasket? backlog?) task for this, #311

2. is a big bug & related to other issues with the table specifically. I will track progress on #299 

3. Not sure how to implement persistence for this element with Bootstrap collapse out of the box. Might be nice to add to the backlog ticket

4. I changed the gear to an animated chevron icon and expanded the target area. See committ c9a530e

**Comment by jennyhavah** [comment]
This all sounds good, @axoplasm. Regarding 3: Thinking about it some more, I actually don't expect it to be a frequent use case that someone is commonly refreshing this page -- and especially not with the filter panel closed. I found myself doing that because I was editing things in the indicator to test sort order and whatnot. Definitely an edge case.

Closing the ticket.
