### ISSUE TITLE
Collected data form Evidence section: Unresponsive text field in several combo-boxes

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#3]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Friday Dec 01, 2017 at 23:30 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/2_

----

**This issue affects the following combo-boxes:**
1. Collected data form > Evidence section > Project Initiation
2. Collected data form > Evidence section > Evidence Document or Link
3. Collected data form > Evidence section > Tola table
4. Import Tola Table Evidence dialogue > Tola Tables

**Precondition:** There needs to be at least one item in the menu to reproduce the issue.

**Steps to reproduce:** 
- Click on any of the above menus to open the combo-box.
- Attempt to type in the text field of the combo-box.
  - **Expected:** I can type characters and see type-ahead suggestions. (It should work exactly like the _Site_ combo-box on the same page.)
  - **Observed:** The text field is unresponsive.

**Tested in:** Chrome browser

![unresponsive_combobox](https://user-images.githubusercontent.com/33670923/33507957-8ba5d492-d6ac-11e7-8085-8bb4a9300020.png)

**Comment by jennyhavah** [comment]
Can't access "Import Evidence from Tola Tables" dialogue. I get a gray screen and no pop-up.

**Comment by mahmoodkhan** [comment]
@jennyhavah That should be fixed now.

**Comment by jennyhavah** [comment]
I can now access the form, but the bug has returned: I can't type into any of the four combo-boxes.
