### ISSUE TITLE
IPTT filter panel: What happens if you set dates manually and then go back to Show All or Most Recent

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#303]
_This ticket applies to both versions of the IPTT report._

If I manually adjust my IPTT report date ranges and then want to switch to one of the built-in date ranges -- _Most recent_ or _Show all_ --  I should not have to start all over again.

# Preconditions
1. On the IPTT landing page, I choose a program.
2. I choose one of the target or time period options.
3. I choose either Show all or Most recent
4. I click the _Create report_ button.
5. ~I manually change the date range.~ I constrain or expand the period range.

# Acceptance criteria

- [x] 1. As soon as I manually constrain or expand the period range -- _Show all_ and _Most recent_ are deselected.
- [x] 2. When I click _**Show all**_ and then **_Apply_**, _Start_ and _End_ periods automatically adjust to reflect the program's first and last period.
- [x] 2.1. The IPT table displays data for the correct reporting period, with the correct column headers.
- [x] 3.  When I click **_Most recent_**, enter a number, and then **_Apply_**, the  _Start_ and _End_ the correct _Start_ and _End_ periods are displayed, based on where we currently are in the program cycle.
- [x] 3.1. The IPT table displays data for the correct reporting period, with the correct column headers.

**Comment by jennyhavah** [comment]
As soon as I constrain the range and click _Apply_, I cannot expand the range in any direction; I don't even see the options in the menus.

**Comment by jennyhavah** [comment]
Sometimes "Show all" immediately resets the _Start_ and _End_ menus and sometimes it doesn't. Right after I land on the report from the IPTT landing page, _Show all_ is responsive. I think it stops responding after I modify the period range in some way and apply changes.

**Comment by jennyhavah** [comment]
I noticed some odd behavior with the Most Recent menu. Sometimes it behaves as expected and sometimes it doesn't. Here's where it _doesn't_ work.
 
1. Create a report with TolaData Test, Years, and Show all. It's a 4 year program and we're in the middle of Year 2.
2. Enter 3 in the Most Recent field and click Apply.

**Expected:** I see Year 1 and Year 2 -- the current year and the last year. 
**Observed:** I only see Year 2. Year 1 is missing.

The odd thing is, if I enter a 1, 2, or any number 4 or higher, it behaves as expected.

When I enter 1, I see Year 2 -- the current year, as expected.
When I enter 2, I see Year 1 and Year 2, current and last year, as expected.
When I enter 4 or 5 or any number higher than that, I see Year 1 and Year 2, as expected -- that's all the available data going back to the beginning of the program.

It's only when I enter a 3 that I get an unexpected result.

Some other examples of unexpected results with Quarters. We're in Q5 right now.

1. Choose Quarters and Most Recent 6. I should see Quarters 1-5, but I only see Quarter 5. 
2. Choose Quarters and Most Recent 7. Again, should see Quarters 1-5. This time I see Quarters 4 and 5.
3. 8 gives me 3, 4, and 5 instead of 1-5.
4. 9 gives me 2, 3, 4, 5 instead of 1-5.
5. 10 and up behaves as expected -- I see 1-5.
6. It works as expected if I enters number 1 through 5. It's when I enter anything between 6 and 9 that I get unexpected results.

**Comment by mahmoodkhan** [comment]
The "Show all" always resets to whatever options are available in the period's start/end dropdowns.

**Comment by jennyhavah** [comment]
> The "Show all" always resets to whatever options are available in the period's start/end dropdowns.

Capturing expectations after our chat:

1. The intention is for "Show all" to always return the program's entire reporting period, from start date to end date.
2. The intention is that you should always be able to see all of your period options in the Start and End menus -- not a continually narrowing subset of options.

**Comment by jennyhavah** [comment]
All fixes validated for the Actuals-only report. Still want to test with the periodic targets version, and right now there's a bug where I can only see TolaData test that doesn't have date going far enough back to test.

Also, remember to recheck the issue where it's automatically selecting LoP only, with the _View Report_ button still disabled. Mahmood is updating it to have nothing selected by default.
