### ISSUE TITLE
Collected data record: General UI refinements

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#304]
Starting a UI refinements checklist for this page. Some other open tickets involving this page are #294  #295 and #264. 

* [x] 1. Page title should be H2.
* [x] 2. Change the page title from "Collected Data" to "Results".
* [x] 3. For helpful context, let's include "(Level) indicator: Indicator name" underneath the page title, just like we do in the Indicator setup form, like so:
![image](https://user-images.githubusercontent.com/33670923/40333536-d390f47a-5d0d-11e8-9d5c-4697a0e7b297.png)
* [x] 4. Move the "Project" dropdown menu out of the Evidence section, to the section above. (No idea why it's in the Evidence section, but it doesn't belong there.)

#### 5. "Standard Disaggregations" updates
* [x] 5.1. Change to sentence case -- Standard disaggregations.
* [x] 5.2. Turn "Standard disaggregatoins" into an expandable/collapsable interaction similar to what we use to open and close program indicator rows, like so:
![image](https://user-images.githubusercontent.com/33670923/40333661-7a50e0fe-5d0e-11e8-9d2e-aa91f79bb020.png)

* [x] 6. Action bar at the bottom should be consistent in styling with Indicator setup form:
![image](https://user-images.githubusercontent.com/33670923/40333679-999e9eb0-5d0e-11e8-886d-125b0bb77ffb.png)

**Comment by jennyhavah** [comment]
> For helpful context, let's include "(Level) indicator: Indicator name" underneath the page title, just like we do in the Indicator setup form, like so:

@axoplasm Please add the word indicator between the level and the colon. For example:

Activity indicator: Blah
Output indicator: Blah
Intermediate outcome indicator: Blah
etc.

**Comment by jennyhavah** [comment]
Can you align the check box with its corresponding label, and move both under the form field immediately above it? (It is a secondary option related to the TolaTable menu.)

Here's how it looks to me now:
![image](https://user-images.githubusercontent.com/33670923/41382279-572fbbb2-6f20-11e8-9e34-e9b06b90c9d3.png)

Versus in production -- in that example there's too big of a vertical gap between the drop down menu and the check box, but the basic alignment of the check box with the menu above is what we're going for.
![image](https://user-images.githubusercontent.com/33670923/41382333-91dbc6de-6f20-11e8-9988-caa972bee68d.png)

**Comment by jennyhavah** [comment]
Wondering why the _Measure against target_ label is a different size. Is there a hot fix to make it match?

**Comment by jennyhavah** [comment]
![image](https://user-images.githubusercontent.com/33670923/41382463-1a6812f0-6f21-11e8-932d-9e8938768565.png)

As discussed in Slack, the correct spelling for this field label is TolaTable. 

If it's a quick fix, can we also align the label with the drop down menu?

**Comment by axoplasm** [comment]
haha there are no easy fixes in this markup! 

Re: *Measure against target* label… this looks the same size to me. Can you send a screenshot?

<img width="326" alt="image" src="https://user-images.githubusercontent.com/169060/41383310-f113b8f6-6f24-11e8-9f18-2e6d7d550b4b.png">

**Comment by axoplasm** [comment]
here's where I'm at with the Evidence form elements __but__ what is supposed to happen when I click "Import evidence from TolaTables?" It looks like it might be trying to open a modal behind this modal.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/169060/41383908-d0e324f6-6f27-11e8-8f0b-6a3555c39769.png">

**Comment by jennyhavah** [comment]
> here's where I'm at with the Evidence form elements but what is supposed to happen when I click "Import evidence from TolaTables?" It looks like it might be trying to open a modal behind this modal.

Good question! Maybe you can knock off #239 while you're at it. If you try clicking that link on production, right now it launches a modal that looks like this:
![image](https://user-images.githubusercontent.com/33670923/41424558-3a005252-6fb3-11e8-8450-ac08c1087273.png)

Here's what that looks like in the code:
![image](https://user-images.githubusercontent.com/33670923/41424639-7bf7e580-6fb3-11e8-846f-5ca01e8e8831.png)

**Comment by axoplasm** [comment]
I split the modal z-index issue into #396

**Comment by jennyhavah** [comment]
Oops, I included the wrong link... I had captured it in #249 not 239. I'll close one of them as duplicate.

**Comment by jennyhavah** [comment]
@axoplasm Ah, found an example -- I wonder if the smaller text happens when there is a message under the dropdown?

![image](https://user-images.githubusercontent.com/33670923/41489410-dbd8c4dc-70a4-11e8-82f0-63f14844edcb.png)

**Comment by axoplasm** [comment]
This was the clue I needed! The `has-error` class has font-sizing in it & there are a few other problems there. Hot fixed with #5bdcda8

**Comment by jennyhavah** [comment]
Bam! Validated.
