### ISSUE TITLE
IPTT Results table: layout, overflow & responsiveness

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#315]

**Comment by axoplasm** [comment]
This ticket only addresses global layout issues with the IPTT table. Issues with individual elements inside the table are #285. Issues with the filter panel are in #298. Other css issues on this page are in #299 

#### UI display weirdness to fix: 

- [ ] Current implementation breaks on small screens — “jumps” below the filter panel
- [ ] x-axis overflow should scroll inside element, not viewport
- [ ] implement or mimic behavior of Boostrap `table-responsive` class

#### Add-on improvements:
- [ ] Sticky table header
- [ ] *n* sticky columns, probably "No." and "Indicator"

**Comment by jennyhavah** [comment]
Add-on improvements captured elsewhere.

1. Sticky table header is captured in #211.
2. _n_ sticky columns is captured in #316

**Comment by axoplasm** [comment]
Scroll behavior is the same regardless of the target element with the scroll property, and regardless of your input device, _as long as that element has focus._ So if I'm hovering over the table with a scroll mouse and shift-scroll with my mouse wheel for example, the table element will scroll horizontally. The catch is that if multiple stacked (or nested) elements have scroll property, only the top or innermost one gains focus. If I want to scroll the entire viewport I need to get my focus out of the table, i.e. by moving my pointer over that part of the page

**Comment by jennyhavah** [comment]
Just showed Mahmood how you can horizontally scroll with arrow keys. Sanjuro has a mouse and was able to shift+scroll but only using the wheel. Someone without a wheel in their mouse wouldn't be able to. None of us intuitively knew how to do it, so we're just concerned that the average user in the field who is less tech savvy might not figure out how to make sure the area has focus, or know that they can use their keys, etc. Any thoughts on how to make it a bit more obvious? For example, does Bootstrap allow you to display some sort of visible scrollbar?

**Comment by axoplasm** [comment]
I'm not sure this is a web issue at all. Scrollbars are OS dependent regardless of the item being scrolled. So these are issues whether you're scrolling the entire viewport or just the IPT table. If I can't (don't know how to) scroll just the table, I won't be able to scroll the whole viewport either.

The correct metaphor here is not "scrolling a webpage" but "scrolling a Google Sheet." I guess we could try to implement something like Google's nifty scrollbars? They are _not_ OS scrollbars

**Comment by jennyhavah** [comment]
If we go with the viewport -- which all of us like! -- then we do need to take the extra time to implement some scrollbars like Google Sheets has. We can't assume that the majority of TolaData users have laptops with trackpads or even a mouse with a wheel. 

Can you estimate the level of effort to add scrollbars to the viewport? If it's in the realm of a few hours, let's go ahead and include it as part of this story. If it's a higher level of effort, let's create a new ticket for it, and put it off for now. Worst case scenario, we can always remove the viewport if we don't get to it.
