### ISSUE TITLE
IPTT table: mobile-responsive sidebar filter panel, incl. toggle & panel form elements

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#317]
This is probably a side effect of #315.
![screen shot 2018-05-23 at 2 58 31 pm](https://user-images.githubusercontent.com/169060/40453488-3202bf92-5e9a-11e8-93f5-77141435c80b.png)

**Comment by jennyhavah** [comment]
@axoplasm This is what I'm seeing:

![image](https://user-images.githubusercontent.com/33670923/40565627-25cb59d0-6022-11e8-914f-72380a66f12f.png)

It's more or less identical to the screenshot in the ticket, so I'm wondering if the changes have been merged? I notice that that while the sidebar width doesn't seem to change even when the browser is as narrow as I can make it... the toggle options still stack on top of each other and the text box wraps and expands in such a way that it no longer looks clearly connected to the Most Recent toggle.

**Comment by jennyhavah** [comment]
I also notice that that while the sidebar width doesn't seem to change even when the browser is as narrow as I can make it... the toggle options still stack on top of each other and the text box wraps and expands in such a way that it no longer looks clearly connected to the Most Recent toggle.

We closed our main filter panel UI styling ticket -- should I open a new one for stuff like this?

**Comment by axoplasm** [comment]
There should be a visible toggle to the right of the panel _(screenshot from my machine:)_

![filter-sidebar](https://user-images.githubusercontent.com/169060/40621175-90ebf1cc-6250-11e8-8083-58186cda80a0.png)

I merged the code but I don't know how it is deployed. Does @mahmoodkhan or someone else need to deploy this manually on demo?

As to widths of individual elements, this is probably the most appropriate place to track that. I'll change the name of the ticket to reflect this.

**Comment by mahmoodkhan** [comment]
@axoplasm and @jennyhavah I just pushed the changes to demo. @axoplasm if you need changes pushed to demo, please tag @sanjuroj as well in case I am unavailable, he can also push changes to demo. Sorry for the delay. I was OFF on Friday. We should setup continuous deployment mechanism for demo server.
