### ISSUE TITLE
The Form Guidance Google Doc is "in the owner's trash folder" It says that we will soon lose access. I am not sure who owns it but can we move it outside of the Trash folder

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#32]
To reproduce the issue:

1. On the TolaActivity production server, [visit the Indicators page](https://tola-activity.mercycorps.org/indicators/home/0/0/0/).
2. Open any indicator.
3. Click on the blue _Form Help/Guidance_ button in the upper right corner.
4. Note the error message. (Screenshot below.) @esinn -- if you're not getting the message, it could be that you have permission to access the document that the average MC employee doesn't have. (Maybe you're a co-owner, or it was shared directly with you?)

![image](https://user-images.githubusercontent.com/33670923/34182170-00ce2cc6-e4ca-11e7-8c14-f1ec4d0da39c.png)

**Comment by esinn** [comment]
I recovered the file and confirmed it matches the current form. Please replace with this link: https://docs.google.com/document/d/1Qe3RYY955D8jtrMxe5Xk8TtdQhqI67oFyIcFI8oFRXI/edit

Also, the following other Indicator Form Guide links need to be updated with this same link: 

- On the create a new indicator page: https://tola-activity.mercycorps.org/indicators/indicator_create/231/ 

- And once you've created a new indicator from the link above and pressed save, this page also needs to be updated: https://tola-activity.mercycorps.org/indicators/indicator_update/4719/

**Comment by mahmoodkhan** [comment]
this task is done.
