### ISSUE TITLE
Actuals-only report > Months option: Column headers say Month 1, 2, 3 instead of the month names

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#323]
This is how Monthly column headers currently show up for the Actuals-only report:
![image](https://user-images.githubusercontent.com/33670923/40496591-fab3331a-5f2e-11e8-8925-8002c2a3b61b.png)

Instead, the column headers should be formatted the same way we do for the Periodic Targets report, like this:
![image](https://user-images.githubusercontent.com/33670923/40496632-14583c2a-5f2f-11e8-9cf3-3130cab3735a.png)

**Comment by hannalcamp** [comment]
Validated with multiple programs; months now appear in "Monthname YYYY" format.
