### ISSUE TITLE
Indicators > Targets: Choose Life of Program (LoP) only option

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#33]
**Story:** When my indicator doesn't require any intermediate targets, I select the _Life of Program (LoP) only_ option from the _Target frequency_ menu so that all data collection records I associate with the indicator are automatically assigned to the LoP target.  

**TARGETS TAB ACCEPTANCE CRITERIA**

![scrap](https://user-images.githubusercontent.com/33670923/34186382-07c2486c-e4e0-11e7-8189-43ccfb50b9ce.png)

1. When I choose the _Life of Program (LoP) only_ option, no sub-options appear.
2. When I click _Save changes_ I receive system confirmation that my changes were saved.
3. However, no table of targets is generated in this case.
4. The _Target frequency_ menu is NOT grayed out in this case. (This is an exception to the rule. In all other frequency options, you must remove all targets before switching to a different frequency. In this case, there are no targets to remove.)
5. If you change from "Life of Program (LoP) target" to a different target frequency, configure sub-options and click Save changes, the system checks to make sure there are no data records associated with the single LoP target.
5.1. If there are no data records associated with the LoP target, the system proceeds to generate the new targets.
5.2. If there ARE data records associated with the LoP target, the system asks for confirmation: "If we make these changes, _n_ data record/s will no longer be associated with the Life of Program target, and will need to be reassigned to new targets. Proceed anyway?"
5.3. If the user declines, no changes are made. If the user confirms, the system dis-associates data records from the LoP target and generates the new targets.

**Comment by jennyhavah** [comment]
> However, no table of targets is generated in this case.
I got a table after selecting "Life of Program (LoP) only" and clicking "Save changes". Here's a screenshot:
![image](https://user-images.githubusercontent.com/33670923/34900317-afb04c46-f7b3-11e7-8812-a7dc1902758b.png)

**Comment by jennyhavah** [comment]
> 5.2. If there ARE data records associated with the LoP target, the system asks for confirmation: "If we make these changes, n data record/s will no longer be associated with the Life of Program target, and will need to be reassigned to new targets. Proceed anyway?"

I tried setting an indicator with 1 data record to LoP only, and then switching to annual targets. I did not get the prompt.

**Comment by mahmoodkhan** [comment]
1/16 5.3 @jennyhavah Only the LOP option gets all of the collected_data records associated. The other targets don't get associated.

**Comment by jennyhavah** [comment]
> 5.2. If there ARE data records associated with the LoP target, the system asks for confirmation: "If we make these changes, n data record/s will no longer be associated with the Life of Program target, and will need to be reassigned to new targets. Proceed anyway?"

Let's add a sentence to the beginning of this message:  Warning: This action cannot be undone. 

(I see that you can't back out of this change by closing the window. This is okay, but we should be more explicit about it.)
