### ISSUE TITLE
IPTT reports: Add scrollbars to the viewport

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#332]
We need some sort of obvious scrolling mechanism for the viewport that doesn't require a mouse with a click wheel or a laptop with a trackpad. (We can't assume that the majority of TolaData users have these things.)

**Comment by axoplasm** [comment]
We should discuss/demo this in person tomorrow. If a user can't scroll inside an individual DOM element with the scroll property I don't think they'll be able to scroll inside _any_ window on their device.

**Comment by axoplasm** [comment]
I'm going to spike this for 2hrs to see if I can find a library that does this with minimal cost.

I think a higher-value fix is to rethink interactivity on the IPTT. It's clearly a flagship feature!

**Comment by axoplasm** [comment]
OK this is not even a two hour spike. I found a nice library ([Perfect Scrollbar](https://github.com/utatti/perfect-scrollbar))that can slap in a scrollbar, but I'm not sure now which elements appropriately need to scroll. I will have to sketch out the problem to express it entirely but the short version is: if we want to see a *horizontal* scrollbar we need to lock the table’s *height* which will mean several other elements on the viewport (header, footer, potentially sidebar) will need to be fixed.

**Comment by jennyhavah** [comment]
Folded into #316 including Paul's comments. Just consolidating.
