### ISSUE TITLE
IPTT filter panel: UI tweaks

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#333]
Gathering small UI tweaks to the filter panel in one place.

- [x] Throughout the filter panel, bring labels closer to their respective form fields. This includes all labels sitting above a menu, as well as bringing the "Most recent" label closer to its text input box.
- [x] Top section background is not high contrast enough for text under 18pts. (I used the same Mercy Corps brand dark gray as the header: #54585A.)
- [x] Labels in bottom section should also be higher contrast. I used #54585A.
~- [x] Let's use black for the text inside the multi-select widget, again for maximum contrast.~
- [x] Make Apply and Reset buttons stretch to fill the width of the panel -- for larger click surface and symmetry. 
- [x] Most recent:
1. I can click directly into the "Most recent" text box and start typing. I don't have to first select the radio button.
2. When I choose "Most recent" and apply changes, I can immediately click into the text box to enter a different number. (Right now I have to toggle the radio buttons back and forth before I can enter a different value.
3. Make sure there isn't a big gap between the "Most recent" label and its text box. (Remember that this label will be translated.)

---

## Mockup for reference

![image](https://user-images.githubusercontent.com/33670923/40674784-aae6a466-632a-11e8-9e2e-519be51edb6c.png)

**Comment by axoplasm** [comment]
> Let's use black for the text inside the multi-select widget, again for maximum contrast.

@jennyhavah : I’m trying to emulate the appearance of select2 widgets. I’ll change this globally

**Comment by jennyhavah** [comment]
Sounds fine, @axoplasm -- I momentarily forgot that we need to implement a CSS framework like SASS for these kinds of global changes to be easy.

**Comment by jennyhavah** [comment]
@axoplasm Sorry I was unclear, I meant the two buttons -- Apply and Reset -- appear side by side and the two _together_ stretch to fill the width.

**Comment by axoplasm** [comment]
I fixed the apply/reset buttons, they will appear with the next PR & should look like:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/169060/41057648-85e96204-697c-11e8-94ac-6b8746396bf2.png">
