### ISSUE TITLE
Data collection records displayed without dates

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#34]
**To view the issue:**
1. On the production server, set profile to Afghanistan and open the Indicators page.
2. Open the program "Assessing the Links between Economic Interventions and Stability: An impact evalua..." that has 9 indicators. (Second program from the top.)
3. Click the _Data 3_ button for the indicator "Well refined research design that ensures rigorious techniques are used and quality assurance processes are in place".
4. **Observed:** There are no dates displayed for these three records. If you click _Edit_ for any of them, the _Date collected_ field is empty. Was there originally a date that was removed? How did this happen?

I did not want to mess with real data records, so I tried to reproduce the issue in the following ways:
1. I created a new data record under one of the Tola Rollout indicators and attempted to save without a date. I was not permitted to save the record.
2. I tried opening a data record associated with one of the Tola Rollout indicators that already had a date, deleting the date, and saving. Again, I was not permitted to save.

Not sure what else to try!

**Comment by mahmoodkhan** [comment]
My guess is that those records with missing Collected_date were entered using a browser that does not have support for HTML5 validations. However, this issue is mute because we're now validating this field ourselves.
