### ISSUE TITLE
IPTT reports: Design Export buttons

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#344]
We need two buttons to initiate exports to PDF and Excel. 

Here's what I mocked up as a starting point, but I have no strong feelings about styling. My only concern is that they be noticeable in such an information-dense view. I also think we should use the full word "Excel" instead of the file extension which varies depending on the version you have.

![image](https://user-images.githubusercontent.com/33670923/40453355-cdb2d0e0-5e99-11e8-8e55-a77b3bdcc2b4.png)

![image](https://user-images.githubusercontent.com/33670923/40453363-d289d50a-5e99-11e8-924c-07c969c074ec.png)

**Comment by axoplasm** [comment]
I'm not seeing these buttons, are they implemented on another branch? Or do I need to implement the export functionality first?

**Comment by axoplasm** [comment]
TO answer myself: this is dependent on #123
