### ISSUE TITLE
Override Program save  method to pull GAIT dates and set program and reporting dates

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#349]
When a program is saved in the admin page, the GAIT start and end dates should be fetched and saved.  If program dates already exist, do not overwrite them.

**Comment by sanjuroj** [comment]
A note about testing:

Some of the testing is probably best done as a code review or by working with one of the devs and manipulating the database manually.  However, one test that can be done without dev help is to create a program that you know has a GAIT date (of status "Funded" or "Complete") and see if the dates populate.  To do this, you may have to delete an existing program because Tola will not allow you to use the same ID twice.  Also some of the usual things can be tested, like saving a program that doesn't have a GAIT date to make sure one doesn't magically appear when the program is saved.

Pulling from GAIT and saving the data is supposed to be non-destructive, so if reporting dates already exist, saving the Program shouldn't overwrite what's already in the database.  This could be tested by e.g. entering a reporting date value through the reporting period modal and then hitting save on the admin page.  GAIT dates themselves can't be tested that way, since they are not editable anywhere in the system.  That's where you may need dev help.

**Comment by esinn** [comment]
When I go to add a program in from GAIT, would we expect that all of the program's info be added over if I only include the GAIT ID in the admin console? Specifically, I went to admin deleted a program (PAHAL from Nepal) then went to re-add it but only entered in the GAIT ID (#5803) and selected a country. The program was added to admin (but no other meta data was pulled in) and the program did not appear within TolaActivity. 
![image](https://user-images.githubusercontent.com/13574772/41313690-76079e92-6e3f-11e8-89f1-0e8660b37b32.png)

**Comment by esinn** [comment]
When I run a search in GAIT of all funded programs for Haiti, a total of 12 programs come up. However, when I look at the list of programs on TA Indicators page (https://tola-activity-demo.mercycorps.org/indicators/home/0/0/0/) I only see a total of four programs. I'm assuming this should match the number in GAIT, no?

**Comment by sanjuroj** [comment]
Regarding comment #1, populating the rest of the program information wasn't part of this issue and from what I understand, not something we're doing from Winterhawks (@jennyhavah can confirm).  We've talked about using more of the GAIT in a future release.  The purpose of this ticket was for the GAIT dates to be added to a program without waiting for a nightly background script to run that fetches the GAIT dates.  

Regarding comment #2, maybe I'm misreading your comment but it sounds like you're thinking that GAIT programs should all be present in Tola, based on the GAIT pull.  That's not the case.  The only thing that this issue covers is when someone save a program in Admin, the program and rerporting dates should be fetched from GAIT.  It's doesn't do a wholesale import of programs into Tola.

**Comment by jennyhavah** [comment]
> Regarding comment #1, populating the rest of the program information wasn't part of this issue and from what I understand, not something we're doing from Winterhawks (@jennyhavah can confirm). 

Confirmed. @esinn You made a number of good suggestions of features to consider adding to Tola Admin. Let's figure out where to track them so they don't get lost. (I'll start a thread on Slack.)
