### ISSUE TITLE
Datepicker: Auto-suggestions are covering up the calendar picker UI

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#360]
**Affects:** Collected data record and anywhere else we use this widget

The browser's built-in auto-suggestions are now covering up the date picker's month/year UI, making it inaccessible. I've been interacting with these date pickers for awhile, and am reasonably sure that this is new behavior.

Example from the Collected Data record:
![image](https://user-images.githubusercontent.com/33670923/41126392-34a82494-6a5c-11e8-8e4b-091325b4ba41.png)

Example from the Targets tab of the Indicator setup form -- this one doesn't need to be fixed because it's going away as part of ticket #263. I'm using it to illustrate a worst case scenario:
![image](https://user-images.githubusercontent.com/33670923/41126436-5974833a-6a5c-11e8-9c2a-6015291b8696.png)

**Update the following**:
- [x] "Collected Data" modal (appears when the "Add results" button is clicked from the Indicator list page)
- [x] In a shared DatePicker widget that, I believe, mostly affects the Projects page (e.g. Project Initiation Form "Expected start date" and "Expected end date"

_Obsolete_
_- [x] ~On the Indicator setup modal (and page), "First Target Begins" field.~ Obsolete as of #263_
_- [x] ~Reports->Indicator Data Report Start and End dates~ Obsolete as of #294_

**Comment by jennyhavah** [comment]
We have a problem with the date picker widget moving around the page such that they appear detached from the form field or don't appear at all.

**Comment by jennyhavah** [comment]
In the Indicator setup form we have a month/year picker. But when you click _Done_, the calendar briefly flashes open. (This has happened before...)

**Comment by sanjuroj** [comment]
@jennyhavah As of #263 the entire date field in the indicator setup form is gone, so maybe this is ready to test?

**Comment by jennyhavah** [comment]
@sanjuroj yep yep. No longer seeing the auto-select in the collected data record or the project forms. Validated.
