### ISSUE TITLE
Simplify Page Titles

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#362]
(This is split from task #129)

This ticket is connected to #152 -- Navigation menu options are inconsistent with page titles and breadcrumbs are a mess. 

Please note the change from title case (**All Capitalized**) to sentence case (**Not all capitalized**) for page titles and buttons. (As a general usability rule, sentence case is easier to scan and parse.)

This story also results in our top nav dropdown menu labels being consistent with the page titles they link to... with one notable exception, Program Index. (We'll address that in a separate story.)

While we are in there, we want to move the buttons to a consistent location and make them more easily discoverable.

### PAGE TITLES
Our page titles are more complex than they need to be, which in turn makes our navigation breadcrumbs and menus harder to parse.

* [x] Document List --> Documents
* [x] Document Form --> Document
* [x] Site Profile List --> Sites
* [x] 3.1. While we're here, change some column headers to match. Change "Profile Name" to "Site name". Change "Profile type" to "Site type".
* [x] Site Profile Form --> Site
* [x] Stakeholder List --> Stakeholders
* [x] Stakeholder Form --> Stakeholder
* [x] Program Index --> Projects --> Project dashboard
* [x] 7.1. Please make sure the "Projects" title change also appears in the Workflow menu.

### PROFILE PAGE
* [x] Change the page title from "User Registration/Profile" to "Profile"

**Comment by axoplasm** [comment]
@jennyhavah — I am cleaning up a **lot** of page titles incl. the <title> tag. I’m not sure what the page title should be for:

* [Collected Indicator Data Report](https://tola-activity-demo.mercycorps.org/indicators/collecteddata/0/0/0/)

**Comment by axoplasm** [comment]
ALSO! I added the page title and name of the site to the `<title>` tag thus: `Documents | TolaActivity`

**Comment by jennyhavah** [comment]
@axoplasm Regarding reports -- we are getting rid of most of them -- see #294. There will only be 2 reports left over -- Indicator Performance Tracking Table and Indicator Disaggregation Report.

Regarding title case vs sentence case, I should note that I've deliberately made an exception for report titles. It started with the Indicator Performance Tracking Table, because people often reference the abbreviation IPTT. And I figured it'd be odd to have one report in title case and the other in sentence case.

**Comment by jennyhavah** [comment]
Page titles validated.

**Comment by axoplasm** [comment]
As I was already partway down this road, I changed the titles of pages we are deleting [(per #294).
