### ISSUE TITLE
Indicators > Targets > Choose Event option

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#37]
**Story:** When my indicator requires one or more targets associated with an event, I select the _Event_ option from the _Target frequency_ menu so that I can assign data collection records to the correct event target.

**TARGETS TAB ACCEPTANCE CRITERIA**

![event1](https://user-images.githubusercontent.com/33670923/34457376-c9045002-ed63-11e7-9de5-7986a1dbf518.png)

1. When I choose the _Event_ option, I am asked to provide the name of my first event and the number of events I want. Both of these fields are required.
2. The upper limit for the "Number of events" field is 12. If I type in a value higher than 12 and try to save, the system prompts me, "You can start with up to 12 targets and add more later."
3. When I click _Create targets_, the system generates a table of event-based target/s for me.

![event2](https://user-images.githubusercontent.com/33670923/34457380-d3dee4ce-ed63-11e7-8394-5d1a5135be42.png)

1. The system automatically generates a table with at least one event target row.
2. The first row includes the name of my event and a target value field with placeholder text "Enter target value".
2.1. The event name is editable.
3. There is an empty target row for any additional events I requested in addition to the first one that I have already named.
3.1. Empty rows include a text field with placeholder text "Enter event name" in addition to the empty target value field with placeholder text "Enter target value".
4. I can add another empty event row by clicking the _Add an event_ button under the table.
5. There is a "Remove all targets" link as defined in issue #30.
6. I am allowed to remove any event except the first one. See ticket #30 for additional details.

**Comment by jennyhavah** [comment]
The form field label says "Number of target periods" instead of "Number of events".

<img width="428" alt="scrap" src="https://user-images.githubusercontent.com/33670923/34901238-7aa4a1a6-f7bc-11e7-81ff-ca61bd70f3da.png">

**Comment by jennyhavah** [comment]
If I create more than one event, they're all given the same name. Only the first period should have the name. The rest of the name fields should be empty, except for placeholder text "Enter event name"

<img width="869" alt="scrap" src="https://user-images.githubusercontent.com/33670923/34901253-cabef092-f7bc-11e7-98ba-6d98862d2d92.png">

**Comment by sanjuroj** [comment]
An event can currently be saved with nothing in the event name field (i.e. only the value is entered).

**Comment by jennyhavah** [comment]
Looks like it's validating properly with the red box highlight. Can we also display an error message in the same place and formatting as the one we're using for missing targets? It can say: "Please enter an event name."

Some oddities I noticed:
1. If I neglect to enter a target value, am prompted to fix it, then tab out, the gray line thickens to 2 pixels. It may only be the final row affected. I can't consistently reproduce it.
2. When I leave an event name empty, it highlights properly. But when I fix it and tab out, the red box stays put. It should ideally turn gray again, like the numeric fields do.

**Comment by jennyhavah** [comment]
@sanjuroj Can you please take a look at the UI styling of the error handling? Here's what I'm seeing:
If I neglect to enter a target value, am prompted to fix it, then tab out, sometimes the line thickens to 2 pixels. It doesn't always happen, but happens frequently. Sometimes I end up with thick gray borders and sometimes thick red. Here are some examples:
![image](https://user-images.githubusercontent.com/33670923/35314628-418a2418-007c-11e8-889e-b49137574a21.png)
![image](https://user-images.githubusercontent.com/33670923/35314635-5123c19a-007c-11e8-81ac-6751e65e157e.png)

**Comment by jennyhavah** [comment]
There are some strange things happening with error messages if you have errors in both the event name field and the target field, fix one but not the other, and then save changes. Try the following sequence:
1. Remove an event name. Correct error message appears.
2. Now remove a target field. Correct error message appears.
3. Now fix the target. There's no longer any error message, even though the event name is still missing.
4. Now click Save changes.
5. The wrong error message appears.
![image](https://user-images.githubusercontent.com/33670923/35314782-31d57cba-007d-11e8-9d1d-64e0b39328b2.png)

**Comment by jennyhavah** [comment]
Sanjuro has a good idea to simplify the messaging by only displaying a single message that covers both types of problems. Let's say: Please enter an event name and number for every target.

Let's also left-align the message.
