### ISSUE TITLE
Upgrade Script for Winterhawks

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#374]
Add anything that needs to be done for upgrading the production server to Winterhawks to the list below, in the appropriate order.

## Restore deleted data with database backup
- [x] Backup current database with `mysqldump`
- [x] Log into mysql 
- [x] Delete the current database
- [x] Create a database with the same name `CREATE DATABASE <database name> /*!40100 DEFAULT CHARACTER SET utf8 */`
[Note: the demo server is set up slightly differently: ` CREATE DATABASE <database name /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */`.  The default collation for the utf8 character set is `utf8-general-ci`.]
- [x] Manually enter the data entered since the 22nd.

## Upgrade to Winterhawks
- [x] Update code with git
- [x] Update python modules with requirements.txt.
- [x] Run database migrations
- [x] Run management command fetch_gait_dates.  **Preserve the output log.**
- [x] Update program id 541 (HQ IT) reporting period to 2018-05-01 - 2020-04-30
- [x] Update program id 452 (Tola Rollout) reporting period to 2015-10-01 - 2019-09-30
- [x] Update program id 442 (Tola Test) reporting period to 2017-05-01 - 2020-07-31
- [x] Run management command update_uomtype_cumulative.  **Preserve the output log.** (#222)

**Comment by mahmoodkhan** [comment]
Excellent checklist.  Just needed to collect static files at the end.
