### ISSUE TITLE
Indicators: Improvements to data record tables

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#38]
Here is a summary of issues to address:
![indicators_problems](https://user-images.githubusercontent.com/33670923/34315995-6353d260-e740-11e7-8a6a-1a30a984f6b5.png)

Here is how we propose to address those issues:

![indicatorsphase1](https://user-images.githubusercontent.com/33670923/34623826-a6ac0290-f207-11e7-9147-136131979289.png)

1. Remove the LOP  target column from the indicators row and incorporate the LOP target into the bottom row of the data records table.
2. Do not display anything in the target column for individual data records -- only the LOP target.
3. Display the sum of actuals next to the LOP target.
4. Display "% Met", i.e. sum of actuals divided by the LOP target.

**Comment by jennyhavah** [comment]
Some styling details. (Sorry, I will try to always include these in the original stories going forward.)

1. Bold the text in the bottom row -- Life of Program and the three sums.
2. Right align Target, Actual, and % Met columns.
3. Take whatever steps are reasonable to reduce the likelihood that table contents wrap in the following columns:
3.1. Target
3.2. Actual
3.3. % Met
3.4. Date Collected. (This one is less important, it would just be more space efficient if we can collapse that header row into one line instead of two.)

**Comment by jennyhavah** [comment]
> Right align text in the Target, Actual, and % Met columns.
![image](https://user-images.githubusercontent.com/33670923/35246403-6e118820-ff7b-11e7-98f9-ee6c30825a37.png)

Looks like the bottom row is right aligned, but not the rest of these three columns.

**Comment by jennyhavah** [comment]
Some requests regarding Target values. (This affects both the Life of Program total in the data table on the Indicators page, and the Life of Program total in the Targets tab of the indicator configuration modal.)
1. Can we automatically append a .00 if the user has not manually entered a fractional decimal?
2. If the user _has_ entered a fractional decimal in the LoP field, we should of course preserve it, as we do today.
3. If it's an old indicator where the user left the LoP field empty or entered something invalid (special characters, etc.), we should leave the LoP total field empty. (I think we are already doing this if it's empty. I'm not sure what we're doing if the person entered a long invalid string with special characters. I haven't found an example yet. Can you let me know?

**Comment by jennyhavah** [comment]
Please reformat the Date Collected column to be consistent with the format we're using in the Collected Data record and Targets tab? I.e. Jun 16, 2016 rather than 2016-06-16.

**Comment by jennyhavah** [comment]
@mahmoodkhan, I requested feedback from Emily and Sanjuro on our changes so far. They both found the Target column to be problematic. Emily immediately thought she had found a bug, assuming that there should be a target next to every data record. 

Of course, if we simply put the target for each period next to each data record, that will also result in confusion and misunderstandings, because people will interpret it as a return to what we had before, which was a target associated with each data record. The sum will not make sense. It also will be unclear why the LoP target is not a sum of the numbers above.

I came up with a concept to address these issues that they thought was a significant improvement. Please take a look and let me know what you think, and how much work it would be to implement. I made an example of what it would look like for three scenarios -- periodic target, LoP only, and non-periodic (event or midline/endline):
![concept](https://user-images.githubusercontent.com/33670923/35254467-30198c9c-ff9f-11e7-8fd2-1654d0a06e03.png)

What I've done:
1. Added a target period column that includes the period name and the date range (for periodic targets only).
1.1. Text is flush left.
2. Rearranged the columns: Target period; Target; Date collected; Actual; % Met; Evidence; then Project.
3. **This is the most critical thing:** We only display the target name and value once for each period, instead of repeating it for every data record. The target name and value span all rows of data associated with them. This eliminates the confusion we introduce by repeating the target.
4. The Life of Program row is transparent (or has a fill color that matches the gray background.) This sets it apart from the rest of the table, like we do in the Targets tab.

**Comment by jennyhavah** [comment]
It's not displaying the period names for Midline/Endline. This is an indicator from TolaData Test:
![image](https://user-images.githubusercontent.com/33670923/35296829-1e15aa56-0032-11e8-8e0b-2cab1b71e2fd.png)

**Comment by jennyhavah** [comment]
Please reverse the order of icons in the rightmost column and add a bit of additional padding around them so that it's harder to accidentally click the delete button and easier to access the edit button. (Fitt's law for the win.)

![image](https://user-images.githubusercontent.com/33670923/35296892-49c2dbc4-0032-11e8-89d6-e6a68431258a.png)

**Comment by jennyhavah** [comment]
Please change the column header "Periodic Target" to "Target Period". I used this phrase on purpose to make the subtle distinction that we have several target types that are not "periodic" in the sense of repetition. "Target period" is also a term used in budgeting and other contexts, less jargony.

**Comment by jennyhavah** [comment]
Please right align Target header:

![image](https://user-images.githubusercontent.com/33670923/35298656-b6b797d8-0037-11e8-85ce-f0ea40eb7a97.png)

**Comment by mahmoodkhan** [comment]
If these changes do no show up for you, then you may need to clear your cache or shift+reload the page.
