### ISSUE TITLE
Multi-select widget: Selected text and down arrow extend past edge of the menu

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#383]
The text and down arrows sometimes extend past the edge of the menu, like this:

![image](https://user-images.githubusercontent.com/33670923/41306512-3b85feb2-6e2b-11e8-93ea-e6138cdf1874.png)

The pattern I'm seeing is that it only switches to "# selected" when there are more than 3 items. When there are fewer than 3, it is determined to display the names, even if there isn't enough room.

Here is an example where I have only one item selected, but it's too long to fit:
![image](https://user-images.githubusercontent.com/33670923/41306852-47e740a2-6e2c-11e8-86c5-b688ea32835e.png)

I would be open to any of the following, and maybe you'll have a better/easier to implement solution that I haven't thought of:
1. If the selection is too long to fit inside the menu, it switches to "# selected", even when only 1,2, or 3 options are selected." 
2. The menu _always_ displays "None selected" or "# selected" and doesn't even try to display the current selection. So in the above example, it would say "1 selected"
3. We do some sort of truncation with a ...

**Comment by axoplasm** [comment]
I propose:

If one item is selected, show `[item name]1. 

Truncate if necessary, probably visually (so not with a `...`, just text getting severed at the edge of the element)

If more than one item is selected, show `# selected`

**Comment by jennyhavah** [comment]
@axoplasm It's looking different on my screen than it did on yours.

![image](https://user-images.githubusercontent.com/33670923/41628229-714337e2-73d8-11e8-81ad-ef676f9ab8a1.png)

**Comment by axoplasm** [comment]
I'm seeing this on demo. Can you test again?

**Comment by jennyhavah** [comment]
Fixed! Now I see this:
![image](https://user-images.githubusercontent.com/33670923/41673235-22743df2-7471-11e8-95ee-b1cc9bb757b2.png)

**Comment by axoplasm** [comment]
👍
