### ISSUE TITLE
IPTT table: Click to highlight/un-highlight row

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#384]
Mahmood had a good suggestion for improving the usability of the IPTT report, that he thinks would be super quick to implement.

Right now, we use an on-hover highlight to make it easier to keep track of which row you're on, like so:
![image](https://user-images.githubusercontent.com/33670923/41307143-3c7ecba8-6e2d-11e8-8f7c-185883c00041.png)

However, it's easy to accidentally hover over a different row and lose your place as you're reading horizontally. Mahmood's idea is to add a select/unselect function for one row at a time. We'd keep the hover behavior, but you could also click a row once to highlight it, and click again to un-highlight it.

**Comment by jennyhavah** [comment]
This looks good to me! @axoplasm could you also take a quick look and give us feedback also from an interaction design standpoint? Specifically, when you UN-highlight a row, we have it briefly darkening onClick, so that you get some visual feedback. But the row stays highlighted until you actually move your cursor away -- because you're still hovering over it. Is that okay? Any suggestions for refinement?

**Comment by axoplasm** [comment]
This looks great. My *only* suggestion (see 6222273) would be to add a hover state (slightly darker light teal) to rows highlighted via a click (i.e having `.row-highlight`)
