### ISSUE TITLE
IPTT: When time/target periods are set to "nothing selected", returns an error page

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#385]
**Affects:** Both versions of the IPTT.

The _Time periods_ and _Target periods_ menus each have a "nothing selected" option, that look like this:

**Actuals-only report (line with dashes)**
![image](https://user-images.githubusercontent.com/33670923/41318880-be6322ba-6e4e-11e8-8b85-8b65d4dda57f.png)

**Target vs actuals report (empty line -- ideally has the same dashes) **
![image](https://user-images.githubusercontent.com/33670923/41318890-c99f9c26-6e4e-11e8-82f4-01d42c7d47ab.png)

These "nothing selected" options results in error pages being returned in a couple of scenarios I discovered, and you may think of others.

# Scenario 1: Manual selection of "nothing"
To reproduce, create either version of the IPTT, and then manually choose the "nothing selected" option. ~It should not be possible to manually select "nothing".~ Do not include the "nothing selected option" in the Target or Time periods dropdowns in the filter panel.

# Scenario 2: Switching to a program that has no indicators with the selected target frequency
This scenario only applies to the _Target vs actuals_ variation of the IPTT. To reproduce:

**Step 1.** Create a TvA IPTT, choosing TolaData Test and Midline/Endline. 
**Step 2.** Switch to a different program that you know does not have any Midline/Endline indicators. You'll see that all filters are reset and the Target Periods menu is set to "nothing selected", which is what we want.
**Step 3.** Now switch to _any other program_. You get an error page -- presumably because there is no target period selected -- just as if you'd manually chosen "nothing" as in Scenario 1.

~What I would expect in this case, is for all filters to reset and the _Target periods_ menu to be set to nothing... Same as what I described in Step 2.~ Instead of setting to nothing, we decided to automatically display the first available option, whatever that happens to be for the program.

# Scenario 3: Switching to a program that has only one available target frequency
Note: This scenario describes an inconvenience rather than a bug. If it would take more than 15 minutes to implement, we can bump it to the Spillover project.
This scenario only applies to the _Target vs actuals_ variation of the IPTT. To reproduce:
Step 1. Create a TvA IPTT, choosing TolaData Test and Midline/Endline
Step 2. Switch to a program that only has one target frequency available that is NOT Midline/Endline, such as "INVEST 3 in Kandahar, a program with indicators all set to LoP-only.

**Expected:** The report loads with the only available target frequency -- in this case, LoP only.
**Observed:** The _Target periods_ menu is set to "nothing selected" and I have to manually choose the only available option.

**Comment by mahmoodkhan** [comment]
Making it work such that "nothing" cannot be selected manually but should be selected when you select a program that does not have the target_frequency that was there before its selection is going to be considerable amount of work at least a day's worth of work. Another problem with having the empty option selected for programs that don't have the previously selected target_period is that what should the report show? The report needs a target_frequency. If we are showing only LOP data in the report then shouldn't we select LOP as the selected option.

**Comment by jennyhavah** [comment]
> Do not include the "nothing selected option" in the Target or Time periods dropdowns in the filter panel.

@mahmoodkhan I still see the "nothing selected" option in the Actuals-only version of the IPTT. I thought we decided to remove it for both versions of the report?
![image](https://user-images.githubusercontent.com/33670923/41369242-362fa386-6ef9-11e8-8454-4f5ef7d3ad77.png)

**Comment by jennyhavah** [comment]
**Scenario 2** Fix is validated.

**Comment by jennyhavah** [comment]
**Scenario 3**
Validated. If I switch to a program with only one target frequency option, it is automatically selected.
