### ISSUE TITLE
Indicators without targets: Empty state

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#39]
**PRECONITIONS**
1. Indicator has no data records associated with it.
2. No targets are configured for the indicator.
2.1. It is not enough to enter a value in the Life of Program text field. There must be a selection made in the _Target frequency_ menu, any sub-options must be configured and any target value fields completed. (A target of zero is fine, just can't be empty.)

**ACCEPTANCE CRITERIA**
1. When I click the green _Data 0_ button, the white row immediately underneath the indicator row expands to 125 pixels high.
2. No data table is displayed.
3. The target icon is shown along with a message, "Organize your data for this indicator. Set a target frequency."
3.1. PNG version of the target icon is attached. SVG vector format also available -- ask Jenny.
4. "Set a target frequency." is a link. Clicking the link opens the Indicator configuration modal with the _Targets_ tab displayed.
5. After changes are saved, the system checks again to see if periodic targets are properly configured.
5.1. If yes, the empty state is replaced with today's data table including the _New Data_ button.
5.2. If no, the empty state is displayed again.
6. **UI styling details:**
6.1. Font size for "Organize your data..." is 21px.
6.2. Font color is MC gray #54585A.
6.2. Icon is scaled to 85px wide.
6.3. There's 10 pixels in between the target image and the word "Organize".

![dataemptystate](https://user-images.githubusercontent.com/33670923/34368443-e5fdfcf6-ea68-11e7-81bb-b78f051593c0.png)

![targeticon](https://user-images.githubusercontent.com/33670923/34367184-093c0e36-ea5c-11e7-8042-67f08bee5217.png)

**Comment by jennyhavah** [comment]
@mahmoodkhan Added styling details to the story.

**Comment by jennyhavah** [comment]
Currently when you click the green "Data [number]" button to access data records, you see the empty state with the target icon, before it loads the records. It's brief but noticeable.

**Comment by jennyhavah** [comment]
Can we make the empty state row 10 pixels taller without changing the padding for the entire table? For example, could we add 5 pixels of padding to the target image to increase the row height by 10? (If we take this approach, we would need to reduce the space between the target image and the word "Organize" accordingly, so there isn't a big gap.)

**Comment by jennyhavah** [comment]
Please make the background of the empty state row white.

**Comment by jennyhavah** [comment]
![scrap](https://user-images.githubusercontent.com/33670923/35241213-96cb5824-ff6a-11e7-8412-7a233ca305f2.png)

1. Empty state row is attached to the indicator row to which it applies.
2. There is a gray spacer row between the empty state row and the next indicator.

**Comment by mahmoodkhan** [comment]
All of this HTML is generated dynamically and there is some built-in functionality from bootstrap. This customization is possible but would take 2 - 3 hours. As we talked, for now, I have increased the space and aligned the icon+msg to the top to indicate that it belongs to the indicator above it.
