### ISSUE TITLE
Add Results form for Indicators: Program displayed becomes incorrect after targets are deleted and readded

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#392]
Affects: Program displayed in Add Results form.

To reproduce:

1. Create targets for an indicator in Demo.
2. Return to the indicator results view and click "Add Results", then check that the program displayed in the pop-up is correct.
3. Go to indicator details, and delete all existing targets, then re-create them.
4. Return to the indicator results view and click "Add Results".
Expected: The correct program originally displayed in Step 2 will still be displayed in the Add Results pop-up.

Observed: A new (incorrect) program is displayed in the pop-up. The incorrect programs displayed in all tests according to GAIT were very old programs (e.g. "Veterinary program", or "Fruit tree nursery production").

Example:
Indicator displayed under its correct program
<img width="974" alt="screen shot 2018-06-14 at 4 19 50 pm" src="https://user-images.githubusercontent.com/38020496/41481309-a961de46-708e-11e8-884b-ccbff786a6fb.png">

Add-results pop-up for the indicator after the targets were deleted and re-added
<img width="981" alt="screen shot 2018-06-14 at 4 19 41 pm" src="https://user-images.githubusercontent.com/38020496/41481341-c088fdde-708e-11e8-92dc-004031d850d7.png">

**Comment by hannalcamp** [comment]
Validated that bug is fixed.

**Comment by sanjuroj** [comment]
Commenting just in case of regression.  When the indicator setup modal is closed and something has been changed, the indicator list page is updated with new values.  The bug was that the program id was being reset with only the first digit of the actual program id, rather than the full program id, which is usually 2-3 digits.
