### ISSUE TITLE
Refine the close triggers of the reporting date modal

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#395]
The current behavior for the reporting date modal is to refresh the underlying list page only if one of the reporting period input fields was blank.  This was done to enable the user to enter indicators for the program.  This is already not ideal behavior, as it would be better to have the prompt change without a page refresh.  

Now we are displaying a prompt to create additional target periods if the reporting end date is moved out far enough to no longer be covered by a reporting period.  If a user moves the reporting date out far enough that they should see this message, they shouldn't need to refresh the page for the message to appear.  

The closing behavior of the reporting date modal should trigger the updates of the appropriate page elements without requiring a refresh.

**Comment by sanjuroj** [comment]
As far as I can tell, there are three things that could be affected if the reporting end date is changed in the reporting date modal. 1) The region just below the Program name (indicator count, Indicator plan and Reporting period links), 2) The "Some indicators have missing targets..." text under the indicator count and 3) The "Missing targets" text just below the indicator name . 

All of these sections are currently conditionally generated within the template (i.e. not by JS).  This means that updating them when the reporting date modal closes will require either a refresh (because the relevant elements have not been generated yet), generating all of them and then doing a show/hide where appropriate, or doing them in JS instead of the template.  Or some combination of those.  Another possibility that @jennyhavah  has mentioned might be to refresh the page but to have the same set of programs with expanded indicator sections as when the modal was opened.  

@mahmoodkhan Is my assessment correct?  Do you have a suggestion about which approach or combo of approaches would be most appropriate?

**Comment by mahmoodkhan** [comment]
@sanjuroj it is probably not a frequent event where program end dates are changed. I agree that it would be a nice enhancement to make but given the deadline for this release I think it wouldn't be unreasonable to reload the page and let the user expand to the appropriate section manually. If we do need to resolve this issue, then I think it might be simpler to reload the page and then expand the sections that were already expanded as @jennyhavah had mentioned. However, if the user has multiple sections expanded then would it still be helpful to expand all of the sections that were expanded?

**Comment by sanjuroj** [comment]
@jennyhavah With the last update, the page will refresh if either reporting date is different from what was the value when the modal was opened. We talked about doing this as a safe place to start that would insure that the messaging on the the underlying indicator list page was updated if the reporting date was updated.  

Additional changes to update the messaging without updating the whole page will take additional work.

**Comment by jennyhavah** [comment]
@sanjuroj Though I don't know what's happening on the back end, the page doesn't _appear_ to reload until I manually close the window by clicking the "x" or clicking outside the area. So I'm left thinking, "Now what"?

Would it be much extra work to have that particular modal reload _and close_ when you click "Save changes"? (I know that's not how our Indicator setup modal behaves, but in that case you get lots of visual reinforcement by immediately seeing the effects of your changes on the Indicator rows. In the case of the Reporting period modal, it just looks like nothing happened.)

**Comment by sanjuroj** [comment]
That should be pretty easy, I'll work on it.
