### ISSUE TITLE
Import TolaTable Evidence modal loads behind collected data modal

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#396]
Split from #304. 

When I click on "add results" then "import evidence from TolaTables" on the Indicators page, the modal doesnt load, or it (more likely) it loads behind the collected data modal

**Comment by axoplasm** [comment]
Ok this is much hairier than I thought. That modal is empty

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/169060/41489181-e4f98516-70a3-11e8-891e-04d4b239e921.png">

**Comment by sanjuroj** [comment]
I'm struggling a bit to figure this out.  A modal on top of a modal feels like something out of the movie Inception to me.  

I can confirm that the modal doesn't seem to load at all, I can't find the div id's from the modal on the page after clicking the link.  I also found this [reference](https://getbootstrap.com/docs/4.0/components/modal/#how-it-works) that bootstrap 4 doesn't support modals on top of modals.  Are we going to have to launch this one the old-fashioned way?

@axoplasm, @mahmoodkhan, any suggestions?

**Comment by jennyhavah** [comment]
@sanjuroj Did you already check how it works on Production?

If that doesn't help, another idea: On Production, open a data record with periodic targets and choose a date outside the range. You'll see this: 
![image](https://user-images.githubusercontent.com/33670923/41502077-dc2994e4-7166-11e8-8f0e-b7d2ccf4e6e2.png)

Then click "create additional target periods." You get a modified version of the indicator modal with a Back link at the top:
![image](https://user-images.githubusercontent.com/33670923/41502080-f52a8cbe-7166-11e8-920b-0d64b4f73a03.png)

Could we plagiarize this interaction?

**Comment by mahmoodkhan** [comment]
@sanjuroj Let's see if we use http://jsfiddle.net/CxdUQ/2092/ as.a reference.
