### ISSUE TITLE
Problems accessing date picker in Reporting period modal and Results pop-up

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#399]
This ticket was peeled away from #258

# Reporting period pop-up
My ability to open the date picker is inconsistent. The first time I click into a text box, it's usually fine. But as I click back and forth between the Start date and End date fields, or switch between clicking on the calendar icon and clicking in the date field, the date picker does not consistently open. And sometimes it gets detached, like so:
![image](https://user-images.githubusercontent.com/33670923/41491510-685bd918-70ae-11e8-81e6-949094a80b95.png)

# Results pop-up
In general, the date picker seems to open a bit more consistently. But this sometimes happens. 
![image](https://user-images.githubusercontent.com/33670923/41491666-770eaaac-70af-11e8-969a-a09a8014fa25.png)

**Comment by axoplasm** [comment]
per our conversation just now I removed the calendar icons. Should be visible on demo in the next deployment

**Comment by jennyhavah** [comment]
I am still having problems with both date pickers, and can reproduce on both machines I use at work. However, I seem to be the ONLY person experiencing this, so I'm going to move to the Backlog for now to see if anyone else experiences it.

**Comment by jennyhavah** [comment]
I've now replicated the date picker on a third machine -- my home laptop. 
![image](https://user-images.githubusercontent.com/33670923/41577642-e8a19694-7342-11e8-8605-4b3362f77db4.png)

**Comment by axoplasm** [comment]
Are you logging into your Google Chrome account on all three machines? 

When we have a chance, I'd like you to try to replicate the bug in these conditions on all your machines:

1. In incognito mode
2. after logging out of Google Chrome
3. using [Canary](https://www.google.com/chrome/browser/canary.html) _without_ logging into your Google Chrome account, 
4. …and then again _with_ logging in

**Comment by jennyhavah** [comment]
# Home laptop
## Incognito
1. Reporting period modal: **FAIL** (meaning after I go back and forth between the two date fields a few times, the date picker stops showing up.)
2. Results "date collected" field: **FAIL**

## Logging out of Google Chrome
1. Reporting period modal: **FAIL**
2. Results "date collected" field: **FAIL**

## Using Canary without logging into Google Chrome
To be continued...

## Using Canary after logging into Google Chrome
To be continued...

# Work laptop
To be continued...

# Work desktop
To be continued...
