### ISSUE TITLE
Collected Data form: Type-ahead function doesn't prioritize items beginning with typed letter/s

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#40]
To replicate: Try using any of the type-ahead menus in the Collected Data form:
1. Site
2. Project
3. Evidence Document or Link
4. Tola table
5. Import Evidence from Tola Tables > Tola Tables menu

Enter a letter towards the middle or end of the alphabet, then a second letter. Try different combinations.

**Expected behavior:** Menu items that _begin_ with the typed letter/s are prioritized, followed by items that _contain_ the typed letter/s.

**Observed behavior:** The menu does _not_ prioritize items that begin with the typed letters. You'll see a menu item with the letter/s somewhere in the middle, followed by items that begin with those letter/s.

**Comment by mahmoodkhan** [comment]
The dropdown are already sorted (mostly in alphabetical order) and the auto-complete feature does not re-sort the field's data. it just filters the data based on the typed characters. Re-sorting the field every time a character is typed is going to be a significant effort and expensive if it is a long list esp. esp. on mobile devices that operate on battery.

**Comment by jennyhavah** [comment]
No need to fix this -- high LOE, no complaints from users about this.
