### ISSUE TITLE
Add personal testing programs

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#404]
Add personal testing programs for each potential tester through the admin interface.

**Comment by jennyhavah** [comment]
Let's call the programs so-and-so's program, like: Jenny's Program.

**People who have volunteered to test**
Hoping a couple more will join, but here's who we have so far:
- [ ] Sonia
- [ ] Christie
- [ ] LJ
- [ ] Marie

**Comment by esinn** [comment]
@jennyhavah And they'll be testing on the demo server yeah?

**Comment by esinn** [comment]
Done. If more are needed, I can add more.
