### ISSUE TITLE
Indicators list page: Can't access results pop-up in certain conditions

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#408]
**Affects:** Access to Results pop-up in certain conditions

# Stuff to try
1. Find or set up an indicator with LoP only target frequency, and add a couple of records to it.
2. Switch the frequency to Midline/Endline or Event, add some targets, then save changes.
3. You'll see an error condition where records are no longer assigned to targets. Click on one of the record dates to open the modal.

I couldn't open the results pop-up after repeated tries, reloading the page and trying again, etc.
![image](https://user-images.githubusercontent.com/33670923/41556450-aa994ab6-72ef-11e8-842b-c5d0f565919c.png)

# Other examples
For awhile, I could not open Results records for 1a {LoP Only} Scenario 1: Non-cumulative number.

Then I could. But as soon as I refreshed the page, I couldn't. Refreshing the page seems to reliably return the error for the affected indicators.

--

**From Sanjuro in Slack:** The problem is that a date is being compared to nothing when the target frequency is undated (LOP, etc….).  Line 864 of views_indicators (`if self.get_object().program.reporting_period_end > target_period_last_end_date:`) is failing. 

 I’m trying to figure out what the default should be in the case of non-dated targets but you probably know off the top of your head.

**Comment by jennyhavah** [comment]
From Sanjuro in Slack: The problem is that a date is being compared to nothing when the target frequency is undated (LOP, etc….).  Line 864 of views_indicators (`if self.get_object().program.reporting_period_end > target_period_last_end_date:`) is failing.  I’m trying to figure out what the default should be in the case of non-dated targets but you probably know off the top of your head.

**Comment by mahmoodkhan** [comment]
This issue should now be fixed

**Comment by jennyhavah** [comment]
I was able to open a bunch of records without a problem, including some I was having trouble with earlier.
