### ISSUE TITLE
Reporting period modal: Reset function is unpredictable

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#411]
This ticket was pulled out of #258.

## Miscellaneous issues related to Reset
- [ ] If you enter a date into an input, save, hit the reset reset button, your original values should return (there have been difficult to replicate issues with this, so watch everything carefully as you move through the test)
- [ ] Test for reversion: When a date is picked, the Reset button is pressed, and the user clicks in the same input field, the displayed date should not switch to the previous date selection, it should reflect the currently displayed date.

**Comment by hannalcamp** [comment]
After trying on multiple programs, I've seen the same pattern:
1. Click on a program reporting period and note the original start and end dates.
2. Change ONLY the end date and click "Save changes".
3. Click "Reset".
4. The end date reverts to the original, BUT the start date (which was never changed) reduces by one day.

I initially thought this was only happening with programs that have available GAIT start and end dates, but I've now seen it happen with programs that do and don't have them. It doesn't seem to matter whether you're changing the end date to be pre- or post- of the original end date
<img width="510" alt="screen shot 2018-06-18 at 7 32 38 pm" src="https://user-images.githubusercontent.com/38020496/41571163-2840cce8-732f-11e8-80cd-014e5ec4519e.png">
<img width="422" alt="screen shot 2018-06-18 at 7 32 50 pm" src="https://user-images.githubusercontent.com/38020496/41571172-2eac6a38-732f-11e8-9935-10552c5a2314.png">
<img width="391" alt="screen shot 2018-06-18 at 7 33 02 pm" src="https://user-images.githubusercontent.com/38020496/41571179-372c0150-732f-11e8-9e72-5f7eded9c9d2.png">

.
