### ISSUE TITLE
Actuals wrong in IPTT

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#412]
The actual values on the IPTT aren't the same as the actuals displayed on the indicator list page.  Current example is what is in the TolaData Test program, Sanjuro test dates indicator.  The first two years have actuals values of 3 and 4, respectively.  In the IPTT report, the only actual value that appears is 20 in the first year.

@mahmoodkhan I'm trying to trace this bug but haven't found the source yet.

**Comment by jennyhavah** [comment]
Here are some examples:

# TvA report

## Scenario 1 non-cumulative #
**Indicator results table** -- values correct for the targets that are completed. (Note that targets are missing -- I did not fill these in, just checking what exists already).

![image](https://user-images.githubusercontent.com/33670923/41568076-8559b848-7318-11e8-9177-90b75ac19089.png)

**Corresponding row in the IPTT**
![image](https://user-images.githubusercontent.com/33670923/41568101-a126fd7e-7318-11e8-851d-dcc44eec7b20.png)

## Scenario 2 Cumulative number:

**Indicator results table**
![image](https://user-images.githubusercontent.com/33670923/41568133-d474d566-7318-11e8-84f7-fbe45a6071bb.png)

**IPTT**
![image](https://user-images.githubusercontent.com/33670923/41568153-eea18a2e-7318-11e8-9995-3b5d5063cdd2.png)

## Scenario 3 cumulative %

**Indicator results table**
![image](https://user-images.githubusercontent.com/33670923/41568176-081f4fc2-7319-11e8-8c17-bb70cec2ccb0.png)

**IPTT -- this one looks correct**
![image](https://user-images.githubusercontent.com/33670923/41568191-192366b4-7319-11e8-81a4-abf952fe603d.png)

**Comment by jennyhavah** [comment]
@mahmoodkhan I'm seeing a problem with Most Recent and Cumulative # indicators.

Check out Hanna's test program, [Annual] Scenario 2: Cumulative #. Here's the period/results table:
![image](https://user-images.githubusercontent.com/33670923/41638114-628604d0-740c-11e8-888d-f7beea3d1ecb.png)

Now run a TvA IPTT report with "Annual" and "Most recent 2". Here's what I see (look at the highlighted row):
![image](https://user-images.githubusercontent.com/33670923/41638144-8ad29124-740c-11e8-8e3a-632f61ed18d9.png)

I would expect the Actuals and % Met to be the same as what's in the results table.

**Comment by jennyhavah** [comment]
Retested, looks good.
