### ISSUE TITLE
IPTT results table popover: Super stretchy

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#413]
Since the recent updates to the results table, the popover version on the IPTT reports have become super stretched out, to where they take over most of the page and veer off the right edge of the window. We don't want to touch the fragile results table layout, but could we make the popover a fixed width?

![image](https://user-images.githubusercontent.com/33670923/41578446-3cc6c3f8-7347-11e8-8338-47aa6d4f3fd6.png)

![image](https://user-images.githubusercontent.com/33670923/41578470-600b9e2e-7347-11e8-8590-687c9f225e34.png)

Also, see the pointy thing on the far right edge... I'd expect it to be flipped so that it's pointing at the dots you use to activate the popover:
![image](https://user-images.githubusercontent.com/33670923/41578577-dcffccd4-7347-11e8-8c8a-d93bcf82305a.png)

**Comment by jennyhavah** [comment]
@axoplasm Can you please remove the "Add results" button from the popover? We had intentionally hidden it before. (The IPTT isn't intended to compete with the Indicators List page as a place to add results, and it links to version of the form that isn't user-friendly.)

![image](https://user-images.githubusercontent.com/33670923/41628315-c718e216-73d8-11e8-9e9c-8813b7c6bdad.png)

**Comment by jennyhavah** [comment]
In a similar vein, this "Add targets" link takes you to a full-page version of the Indicator setup form, and out of the context of the IPTT report.

![image](https://user-images.githubusercontent.com/33670923/41628382-1f6e54f0-73d9-11e8-9ff4-e9085b5e71c6.png)

Ideally, it would launch the pop-up version of the form, with the Targets tab open. If that's difficult to do from the popover doodad, then let's chat about alternatives.

**Comment by jennyhavah** [comment]
I like the blue table icon! More intuitive and easier to click on than the three dots.

What do you think about using the icon to either open or close the popover? My instinct was to click it once to open, again to close.

**Comment by axoplasm** [comment]
I worked out the stretchy issue as a side effect of 1a54242 (in #285) which I think is deployed now. You might need to dump your cache to see the change.

This popover is the *exact same* code as the results popup on the indicators table. So if we don't want "add results" here it won't be there either. I can hide it with css. Not sure how to resolve the issue of it taking you to another page.

**Comment by jennyhavah** [comment]
We're changing the error messaging "Organize your data for this indicator" to "This indicator has no targets."

And then hiding the "Add targets" button in the popover.

**Comment by jennyhavah** [comment]
Wording updated. "Add results" hidden in the IPTT popover.
