### ISSUE TITLE
Targets generated by extension of program end date: Mis-numbered periods

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#416]
Affects: Annual, semi-annual, tri-annual, quarterly, monthly periodic targets

Issue: When new targets are generated by extending the program end date, you see this in the indicator rows that require target values to be completed.
![image](https://user-images.githubusercontent.com/33670923/41612752-a96b6584-73a8-11e8-8ce5-21c90793cb62.png)

Clicking on "Missing targets" opens the indicator's Targets tab and scrolls it to the area where you need to fill in missing values. The newly generated periods have correct date ranges, but incorrect period names. Here are some examples:

![image](https://user-images.githubusercontent.com/33670923/41612799-cb9ae814-73a8-11e8-8364-15d366b1b0e7.png)

![image](https://user-images.githubusercontent.com/33670923/41612811-d1e6b964-73a8-11e8-8fad-03f90b3d8cfe.png)

![image](https://user-images.githubusercontent.com/33670923/41612819-d7d48ad6-73a8-11e8-957a-ec288f9356fb.png)

**Comment by mahmoodkhan** [comment]
When generating missing target periods, the method responsible for generating the target periods (date ranges and period_name) had to start from after existing target periods. The bug was that the variable was getting incremented twice only after the first run because the loop value starts at 0
