### ISSUE TITLE
Fix TolaTables modal in Results modal 

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#421]
This issue appears on the TolaTables picker modal that is reached through the "Import evidence from TolaTables" link n the Results modal.  A prior fix for #396, re-enabled the TolaTable picker modal, but some work still needs to be done to make it functional.

- [ ] If the an empty value is saved, an error alert appears, which is proper.  However, if this alert is dismissed and an empty value is saved again, no alert appears.  The overall alerting process needs work.  

- [x] The ability of the TolaTables picker modal to actually pull information in from TolaTables has not been tested.

**Comment by jennyhavah** [comment]
@sanjuroj Can we close this ticket? (We decided to remove the "import evidence from TolaTable" feature in Huckleberry, as we no longer need it for row count, and you can simply paste a link directly to the table.)
