### ISSUE TITLE
Projects list page: Styling improvements

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#427]
This ticket covers the page you get to when you click Browse > Projects

# Styling ideas

- [x] Use H3 for program names and make its row more header-row-like
- [x] Replace program dashboard button with a button that says "Program dashboard"
- [x] Replace project dashboard button with a button that says "Project dashboard"

**Comment by axoplasm** [comment]
- [ ] Workflow filters jump around & need style love

![image](https://user-images.githubusercontent.com/169060/41784685-4ae20cb2-75f5-11e8-84f8-208b24119c5f.png)

**Comment by axoplasm** [comment]
Workflow filter also appears on *reports > project report*, where else?

**Comment by jennyhavah** [comment]
@axoplasm I can't find any other examples of that status menu.

**Comment by jennyhavah** [comment]
All updated buttons appearing. Status menu no longer moves around on the Projects page or in the Project Report.
