### ISSUE TITLE
IPTT Results popover: When there are lots of periods and data, popover doesn't fit

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#428]
Here's what happens with an indicator that has lots of target periods and data -- the top portion is cut off.

![image](https://user-images.githubusercontent.com/33670923/41676779-5bf0bd4e-747b-11e8-9581-b58f7a4d011f.png)

**Comment by axoplasm** [comment]
This might be fixed as a side effect of the fix in #437 (?)

**Comment by hannalcamp** [comment]
This works in Chrome now, but I get no popover at all when clicking the tables in Firefox.

**Comment by jennyhavah** [comment]
Ah, @hannalcamp this is a known issue, tracked separately in #327. But good that it's working on Chrome! I consider this ticket done.
