### ISSUE TITLE
New indicator: Fields not auto-populating from the DIG and External Indicator Service table missing

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#431]
# Issue
When adding a new indicator, if you select an option from the DIG, certain fields are supposed to auto-populate. This no longer happens. Also, the "External Indicator Service" table is missing from the Summary tab.

# To reproduce
1. Select add a new indicator, choose the service template The DIG and search for indicator "number of people receiving emergency relief services"
2. Click save and the indicator is created but none of the fields are populated from the DIG (as it should/expected)

# Fields that auto-populate in production:

## Summary tab
- [x] Indicator name
- [x] Sector
- [ ] ~External Indicator Service table. Looks like this:~
![image](https://user-images.githubusercontent.com/33670923/41734218-26279c4e-753b-11e8-8820-6b3df2ef07aa.png)

## Performance tab
- [x] Level
- [x] Source 
- [x] Definition
- [x] Indicator type

**Comment by jennyhavah** [comment]
Double checking the table -- I think we intended to remove it.

**Comment by jennyhavah** [comment]
I talked with Marie, and I don't think we intentionally removed it. We did intend to MOVE it to the Summary tab... which apparently holds true in the full-page version, but not the modal. Can we add it back to the modal?

**Comment by mahmoodkhan** [comment]
There is a bug in the system, which causes this value to not get saved in the database. It is buggy in production too.

**Comment by jennyhavah** [comment]
Turns out there is a bug in production, where you see the table when you first create the indicator, but never see it again after saving it.

What I think we should do is simplify the design of this and fix the underlying bug. Will file a new ticket for this, to be addressed post-Winterhawks.

**Comment by jennyhavah** [comment]
See ticket #438.
