### ISSUE TITLE
New multi-select widget: Current selection displays apostrophes and ampersands as special characters

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#432]
When there is an apostrophe in a selection option, it is rendered as a special character. We should also test with double quotes.

![image](https://user-images.githubusercontent.com/33670923/41733222-1390a7ea-7538-11e8-9690-3869d74d91c4.png)

Also happens with the ampersand:
![image](https://user-images.githubusercontent.com/33670923/42001327-8597d7a2-7a18-11e8-8059-bf72ec175b9b.png)

**Comment by axoplasm** [comment]
A little more detail: this doesn't happen in the select list proper. It's the prepopulated/placeholder text in the data-toggle _after_ the filter has been applied
![image](https://user-images.githubusercontent.com/169060/41800136-0851be40-7629-11e8-862a-879f5fb61c41.png)

**Comment by jennyhavah** [comment]
No longer relevant.
