### ISSUE TITLE
Midline/endline, LoP, Event indicators: We permit results to be submitted that are outside the program period

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#436]
**Affects:** Results form

## Issue
For LoP, Event, and Midline/Endline indicators, it is possible to enter results with a _Date collected_ date outside the program reporting period. The system does not validate the date to ensure that it is inside the program's reporting date range. 

(This is automatically prevented for other types of indicators -- annual, quarterly, etc. -- because we auto-assign results to targets based on the date and return an error message if the date is outside the reporting date range.)

## Proposed solution
- [x] If a _Date collected_ date is entered outside the program reporting period, display an error message: "Please select a date between {Reporting start date} and {Reporting end date}." 
- [x] Do not permit the form to be saved until the date is inside this range.

**Comment by hannalcamp** [comment]
Tested in dev for Midline/Endline, Event, and LoP targets, behavior is as expected.

**Comment by jennyhavah** [comment]
This is already done, forgot to close it.
