### ISSUE TITLE
Multi-select in IPTT filter panel: Difficult to scroll long lists

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#437]
The selection menu gets cut off at the bottom of the filter panel, like this:

![screen shot 2018-06-21 at 3 44 26 pm](https://user-images.githubusercontent.com/33670923/41742956-828c95a2-7554-11e8-8a88-0abd319b673b.png)

**Comment by axoplasm** [comment]
I need a little more info on this:

1. browser/OS
2. Monitor size — only very large monitors?
2. It looks like this might only happen when the results pane is shorter than the filter pane?

**Comment by jennyhavah** [comment]
I've been testing on Chrome and Marie on Firefox. I'm testing on iMac with High Sierra version 10.13.5. Marie has a MacBook Air... not sure about the OS version.

**Comment by hannalcamp** [comment]
Tested in both Chrome and Firefox, selection menu properly formats to different results pane sizes and is easily usable.
