### ISSUE TITLE
Indicators > Targets > First target period month and year selector

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#44]
**Story:** When I am asked to identify when the first target period begins, I can select a calendar month and year. I am not distracted by calendar elements I can't select -- i.e. days of the month.

**Note:** This story applies only to periodic targets -- annual, semi-annual, tri-annual, quarterly, and monthly targets. It does not apply to midline/endline, LoP-only, or event-based targets.

**PRECONDITIONS**
1. Open an indicator that does not already have target periods set, and navigate to the Targets tab.
2. Select one of the _periodic_ target frequency options -- Annual, Semi-annual, Tri-annual, Quarterly, or Monthly.

**ACCEPTANCE CRITERIA**
1. I see a UI widget that enables me to select a calendar month and year.
2. The current calendar month and year are displayed by default.
3. I do not see calendar days -- only months and years.
4. The widget is efficient. It doesn't force me to click a "next" arrow dozens of times if I need a month several years in the future. In that case, I can type the date and jump ahead.

Here is an example of a month/year calendar widget that is modified in a single instance, not affecting other calendar widgets in the product: http://www.jquerybyexample.net/2013/04/show-only-month-and-year-in-only-one-jquery-datepicker-multiple.html

**Comment by jennyhavah** [comment]
> The widget is efficient. It doesn't force me to click a "next" arrow dozens of times if I need a month several years in the future. In that case, I can type the date and jump ahead.

1. Operating the UI with a mouse works great.
2. I'm struggling with typing in a few ways:
2.1. I actually can't figure out how to type in a month and year. Like, if I type "2019-05" and hit tab or return, the system doesn't a my entry.
2.2. The date formatting is unforgiving. YYYY-MM-DD is not an intuitive thing to type in countries like the USA where MM/DD/YYY is a more common format. Can we make it more forgiving? Ideally, I should be able to type 3-2018 or 03-2018 or 2018-3 or 2018-03.
2.3. If I type a day, the full calendar pops out. I can't pick anything, but it shouldn't appear at all. Here's a screenshot:
<img width="477" alt="scrap" src="https://user-images.githubusercontent.com/33670923/34900988-a2940e48-f7b9-11e7-9eec-6f1a671bd12c.png">

**Comment by sanjuroj** [comment]
We found another widget, [bootstrap-datepicker](https://github.com/uxsolutions/bootstrap-datepicker), that looks pretty nice.  However, it would mean adding another ~70k of CSS and JS to the App for just one small feature.  The jquery-ui library is currently used for both the date picker and the data tables, so unless we also find a different library for data tables, the bootstrap-datepicker would add size and another dependency, since we would need both.  

For this release, it might make sense to continue to use the current jquery-ui library for the date picker, making it function as close as possible to what we want.  Then, when we are updating our jquery and bootstrap libraries at a later date, we could revisit making a change to the date picker.

**Comment by jennyhavah** [comment]
That sounds reasonable. @mahmoodkhan, why don't we keep this story open for now, as a place to track any improvements you make to address the usability issues I raised above? 

We can then create a separate ticket to investigate the bootstrap-datepicker and add it to this new project I created to track global UI improvements: https://github.com/mercycorps/TolaActivity/projects/2.

**Comment by jennyhavah** [comment]
For this release, we've settled on having the date picker field display the first day of the month in the format we're using elsewhere, i.e. Jan 1, 2018. We are not making further changes to the UI. I'm marking this done and will file a new story as needed, in a future release.
