### ISSUE TITLE
Results form: Form validation missing for actuals with over two decimal places

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#442]
**Affects:** Actual value field of the Results form.

Here's what we do in Production if you enter an Actual value with over 2 decimal places, like 4.5555.

![image](https://user-images.githubusercontent.com/33670923/41758957-9f16ce3a-75a0-11e8-917e-908ff175b0ec.png)

But on Demo, you don't get an error message, and the value is not saved.

Let's restore the behavior from Production.

**Comment by mahmoodkhan** [comment]
This is the browsers's default validation error message in Chrome, this validation behavior may vary in different browsers.

**Comment by jennyhavah** [comment]
Let's automatically round Actuals to two decimal places, as we do in the Target setup form.

**Comment by jennyhavah** [comment]
Automatic rounding is happening for Actual value. It doesn't happen for disaggregated results, but would take considerably greater effort to fix now. I don't think it's worth it, as we plan to start all over with disaggregations after Partner Access.
