### ISSUE TITLE
UI refinement: Indicators > Target period tables

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#45]
These UI refinements have to do with the table of target periods generated by the system after you select a target frequency and click _Create targets_ button. See [design wiki](https://learn.mercycorps.org/index.php/Tola:Periodic_Targets#System_generates_table) and Issue #25 for background context.

![allthethings](https://user-images.githubusercontent.com/33670923/34843218-afdfceb8-f6c2-11e7-9759-33e8fd9c3b5e.png)

1. Add gray lines in the following places:
1.1. Top of the first row.
1.2. Between Sum of targets and Life of Program rows.
1.3. Below Life of Program row.
2. Right-align target values. This includes both the placeholder text ("Enter target") and the numeric value.
3. Horizontal table line styling:
3.1. All table lines should be Mercy Corps gray #DBDCDE. 
3.2. Is it possible to have the horizontal gray lines extend all the way to the edges of the table, without having the table contents also butt up against the edges? Ideally there is 10px padding between the left edge and the text (or delete icon), and 10px between the right edge and the text box... But the gray lines reach the edge. Like this:
![marginalia](https://user-images.githubusercontent.com/33670923/35016880-634ffabc-facf-11e7-9673-74836d8e86f9.png)
4. Lighten up text field boxes. (Wherever practical, the following styling changes should be applied universally throughout the app. It's not our intention to create a unique style that applies only to this table.)
4.1. Text box border weight reduced to 1. (Looks like it's 1.5 or 2 now.)
4.2. Border color should be MC gray #DBDCDE.
4.3. Placeholder text is MC gray #DBDCDE. (Jan 19: Too faint. Bumping this up to #b8babd.)
4.4. Remove interior drop shadow.
5. Row height should be 10px higher, so that there is an additional 5 pixels vertical padding above the periodic target name and below the date range.
6. Fix font styling inside table rows.
6.1. It looks like the periodic target title font is larger than the date range font. Bump up the size of the date range.
6.2. The vertical line spacing between the title row and date row looks a bit tight. Is that the default spacing?
7. Don't capitalize "target" in the phrase "Life of Program (LoP) target". ("Life of Program" is an acronym-ized catchphrase, which is why the word "Program" is capitalized, but "target" is not.)
8. Left-align the text of the periodic target rows with the Sum of targets and Life of Program rows.

**Comment by sanjuroj** [comment]
There is currently an issue with the red X delete button.  If you generate 3 targets and try to delete one of them, the button shifts to the left a bit.  I think it's because the button is given an inline style rather than a block style but I haven't figure out where that's being set yet.

**Comment by jennyhavah** [comment]
@sanjuroj I'd like to request two UI tweaks to the event name field. Here's what I'm seeing:
![image](https://user-images.githubusercontent.com/33670923/35203703-65f35e22-fede-11e7-897e-5c55a33d47b6.png)

Here's the mockup, for comparison's sake:
![image](https://user-images.githubusercontent.com/33670923/35203722-82b2c50c-fede-11e7-9929-eb6cc5559000.png)

These are the changes I'd like:
1. Make the event name field wider. In my mockup there's about 12 pixels between the two fields.
2. Give the event name field border the same treatment as the number field border. (Looks thicker and a darker shade of gray.)
