### ISSUE TITLE
Modal forms not launching

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#452]
Several project-related modals are not launching.  When they are re-enabled, the formatting needs to be fixed, including label layout, save button context formatting and close button position/style.

- [ ] On the project initiation form, clicking the Add Component button launches the modal but doesn't add content.  Check that both the short and long form work.

**Comment by axoplasm** [comment]
On the Project tracking form, it appears subsequent modals are not being destroyed? For example,  components tab > Edit a component shows the Components form. 
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/169060/42001495-fa2d99ee-7a18-11e8-8594-7bf9443305d3.png">

Then if I click out of the modal to close it (NOT the close button), click Budget Contributions > Add Budget Contribution I see the __same__ modal
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/169060/42001542-1e44a624-7a19-11e8-91b9-ad03c2c3deaa.png">

**Comment by axoplasm** [comment]
…and if I close the Add Component modal with the __close__ button, subsequent modals open blank

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/169060/42001622-6378039e-7a19-11e8-8dae-6ba1c005f998.png">
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/169060/42001641-74334c8e-7a19-11e8-8a96-e7b301b1e20b.png">
