### ISSUE TITLE
TolaAdmin: Limit access to all but 6 functions

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#459]
If we can scope admin access to a user's country, then we plan to give "basic" (non-super-user) TolaActivity admins access to the following limited set of functions:

1. Assign user permissions. (Doesn't include super-user permissions.)
2. Manage offices.
3. Manage country strategic objectives.
4. Manage program objectives.
5. Manage disaggregations.
6. Add program.

**Comment by mahmoodkhan** [comment]
In order fo this work, the following needs to happen:
A super admin needs to configure the "Admin User" group in the admin interface to have the following permission:

auth | user | Can change user

indicators | disaggregation label | Can add disaggregation label
indicators | disaggregation label | Can change disaggregation label
indicators | disaggregation label | Can delete disaggregation label

indicators | disaggregation type | Can add disaggregation label
indicators | disaggregation type | Can change disaggregation label
indicators | disaggregation type | Can delete disaggregation label

indicators | Program Objective | Can add objective
indicators | Program Objective | Can change objective
indicators | Program Objective | Can delete objective

indicators | Country Strategic Objective | Can add  strategic objective
indicators | Country Strategic Objective | Can change  strategic objective
indicators | Country Strategic Objective | Can delete  strategic objective

workflow | Office | Can add office
workflow | Office | Can change office

workflow | Program | Can add program


Once the `User Admin` group is set u with the above permissions,  then any user who needs to have admin access will need to be a member of this group  and  the"Staff  Status" checkbox selected.

**Comment by sanjuroj** [comment]
@mahmoodkhan, @jennyhavah  On demo, when I update the tolatest user's country access from my own account, I can see the changes when I look directly at the database.   and then log in as tolatest from a different browser, the database values revert back to where they were before the initial change.  Couldn't replicate locally.

**Comment by jennyhavah** [comment]
@mahmoodkhan Because of the issues Sanjuro described above, I paused testing until they are resolved and did not ask other Tola team members to review.

**Comment by mahmoodkhan** [comment]
@sanjuroj @jennyhavah this is working as expected. Tola-activity-demo is behind cosign and part of of the cosign module functionality is to assign the country you belong to in cosign added to your Tola-activity profile.

**Comment by hannalcamp** [comment]
Tested in tola-activity-demo using Tolatest logins, permissions include the 6 outlined in this ticket, but include several others under the "Workflow" heading that are not outlined (e.g. checklist items). 

However I think we may however wish to retain many of these anyway - such as management access to sites, stakeholders. @jennyhavah did you mean to exclude those?

**Comment by hannalcamp** [comment]
Screenshot of test view:

<img width="480" alt="screen shot 2018-07-19 at 2 36 48 pm" src="https://user-images.githubusercontent.com/38020496/42968822-a81b8788-8b61-11e8-934d-7326972457fb.png">

**Comment by hannalcamp** [comment]
Tested in dev with the same tolatest logins, admin now correctly shows only 6 options:

<img width="485" alt="screen shot 2018-07-24 at 2 05 37 pm" src="https://user-images.githubusercontent.com/38020496/43163212-b003e570-8f4a-11e8-837a-b82daceea3f7.png">

**Comment by jennyhavah** [comment]
@sanjuroj Can we close and archive this?

**Comment by sanjuroj** [comment]
Archived and closed.
