### ISSUE TITLE
Home page: Queries for program-level metrics

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#463]
This ticket describes queries we will need for our Fruit Basket redesigned home page and new program pages. They will be displayed with some combination of text and (hopefully) graphics, like so:

![image](https://user-images.githubusercontent.com/33670923/48166664-159b2780-e29e-11e8-8033-fe6ce9032ebe.png)

# Context to consider in queries

## Program status
We should only display programs that have the word "Funded" typed into the program status field in TolaAdmin. _(In the future, we may explore a more robust set of status options -- Active/Closed/Archived/etc., programs active during a particular time span, etc. At that point, we might offer some program filtering options to the user in the UI.)_

### Annual/Semi-annual/Tri-annual/Quarterly/Monthly indicators
These indicators have target periods defined by date ranges.
- [ ] In determining whether **_indicators_** are meeting targets, we want to look at results from the program reporting start date up to and including the most recently _completed_ target period. (It would not be fair to include the current target period in this context, because the indicator will be flagged as "not on track" simply because results were not yet reported.)

### Lop-only indicators
The target period is identical to the program reporting period.
- [ ] For these indicators, we don't include performance results until after the reporting end date. 

### Midline/endline and Event indicators
- [ ] For these types of indicators, we want to start measuring performance _as soon as a result is associated with its target._ 

**Explanation:** Midline/endline and Event-based target periods do not have defined date ranges, so we have no way of detecting when it's "over". Our assumption is that -- in the majority of cases -- these types of indicators will tend to have only one result per target period. Or, if there _are_ multiple results, the team will be reporting all of them shortly after the midline survey or the training takes place, in a single batch. So the risk is low that programs will be unfairly "penalized" for these indicators because results are trickling in over an extended period of time. 

# Query Set 1: Indicators within target range
For each indicator, we want to answer the following questions:
- [x] 1. For all completed target periods to date, what is the target value? 
- [x] 1.1. Calculation takes into account cumulative vs non-cumulative and # vs %
- [x] 2. For all completed target periods to date, what is the actual value?
- [x] 2.1. Calculation takes into account cumulative vs non-cumulative and # vs %
- [x] 3. For all completed target periods to date, what is the _percentage variance_ of the actual value from the target value?
- [ ] 4. _Which_ indicators are INSIDE the plus or minus 15% variance range?
- [ ] 3.1. _How many_ indicators?
- [ ] 3.2. What _percentage_ of indicators?
- [ ] 4. _Which_ indicators are ABOVE the 15% variance range?
- [ ] 4.1. _How many_ indicators?
- [ ] 4.2. What _percentage_ of indicators?
- [ ] 5. _Which_ indicators are BELOW the 15% variance range?
- [ ] 5.1. _How many_ indicators?
- [ ] 5.2. What _percentage_ of indicators?

# Query Set 2: Reported results backed up with evidence
Evidence is defined as a link to a file (aka a "document") or a link to a TolaTable
- [ ] 1. Within a single program, which reported results have associated evidence? (Group by indicator.)
  - [ ] 1.1. How many results have evidence?
  - [ ] 1.2. What percentage of results have evidence?
- [ ] 2. Within a single program, which reported results do NOT have associated evidence? (Group by indicator.)
  - [ ] 2.1. How many results have evidence?
  - [ ] 2.2. What percentage of results?

# Filter overlays

## Short term
In the short term, the only filters we'll need to overlay on these query results are:
1. Funded status (see details above)
2. Country

## Long term
Just a heads up that we eventually hope to offer some sort of "portfolio" feature that enables users to easily access the group of programs they want to include on their home page, that are not necessarily defined by country or program status. We could approach this in one of two ways:
1. **Basic:** We build a very rudimentary "portfolio" feature that allows users to save groupings of programs with a custom name. This would essentially be a multi-select list of all the programs you have access to, grouped by country. 
2. **Pie in the sky:** We link a user's GAIT account to TolaActivity so that any GAIT portfolios created by the user can be used to derive a list of Tola programs that are part of a portfolio, that you have permission to see.

## Housekeeping
- [ ] Unit test/s written
- [ ] i18n tags included wherever applicable

**Comment by jennyhavah** [comment]
@sanjuroj I want to call out that we're still fine tuning the visual representation of indicator performance, and share a few thoughts.

![image](https://user-images.githubusercontent.com/33670923/44566771-34206680-a724-11e8-9433-e60754171c7f.png)

There are three bands representing:
- More than 15% _above_ target (yellow)
- Within 15% _above or below_ target (green)
- More than 15% _below_ target (green). 

However, the accompanying text expresses "inside the range" and "outside the range", the latter being the sum of the two yellow bands.

I'd like to actually display all 3 percentages in the chart, which is why I requested all three percentages. But it'll take a while to figure out how to represent all 3 numbers without it getting crazy busy, and I'm passing the baton to @axoplasm for further exploration.

**Comment by camgnostic** [comment]
Pull request #712 addresses Query Set 1 from this list completely

**Comment by hannalcamp** [comment]
Question: This indicator is showing up in the QA program created for me as being >15% above target?:

![screen shot 2018-11-29 at 1 14 26 pm](https://user-images.githubusercontent.com/38020496/49249146-b92cb300-f3d8-11e8-92cc-5bb26c23490a.png)

**Comment by hannalcamp** [comment]
1. @camgnostic 
2. Indicator is trying to achieve an increase according to the settings.
3. I didn't add any results.

**Comment by camgnostic** [comment]
Still tracking this down - estimating delivered tomorrow end of day (but that's a rough estimate, this is difficult to reproduce behavior)

**Comment by camgnostic** [comment]
tracked down! This program is in the future.  The logic from the refresh of "what does complete mean" as part of Huckleberry defined "% towards target" as counting all results from all periods _that have been completed by today_ - and since the only completed period in this program is year 1, it's calculating 90% based on only year 1.  @jennyhavah and @sanjuroj are looking at adjusting the QA data we're testing with to avoid this (totally impossible in the real world) edge case, but for now I'm marking this ticket as complete as the only case where it fails is an invalid test case.

**Comment by camgnostic** [comment]
followup- the targets sum on the same "only through the most recently completed period" logic for the progress measurement (so the "progress" target as of today on this indicator is 100, as that's the only period completed as of today - per @jennyhavah's ticket criteria explaining that we don't want to evaluate an indicator against targets they've set for themselves years in the future) but the data for a non-cumulative indicator currently sums all data (because the system is built assuming no data is entered for the future) - so right now this qa program is reporting a target of 100, and an overall data of 540.  We _could_ limit the data used in the "overall data" part of the progress report to data that has been recorded up to today, but that will raise additional complications.  Instead, I think the current plan is to address data date validation in Huckleberry (overhaul of result/record entry).  Moving (again) to in testing.

**Comment by hannalcamp** [comment]
Eliminated future results from some indicators, and their status as above/below/within targets became correct. Going to consider this validated.
