### ISSUE TITLE
Install & run local versions of externally-loaded resources

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#465]
First tier goal is to install & use local copies of resources currently hosted on CDNs, e.g. `bootstrap.min.css`

For the time being, I'm loading these all via npm tasks through `package.json` with a long chain of `cpx` tasks. The resultant files are all in source control. __There is no need to run `npm copy` on your local development machine__

My immediate target is to replace these externally loaded resources __at the same exact version__ as in the current dev branch

I’m putting static files into a /static/ directory inside /tola/ . These will need to be collected in non-dev servers via `manage.py collectstatic` as usual. (See Goal 3 below)

My ultimate goals:

1. Maintain all resources at their __latest__ stable version
2. Dynamically build & pack resources via a __watch task__ through npm, yarn, grunt etc.
    * Would be *extra* cool to hook this task into a management command in `manage.py runserver`
3.  Manage built/packed resources as modules for individual apps or tasks instead of globally. To this end I intend to retire the `/static/` directory in the project root in favor of __app-specific `/static/` directories__
    * This would theoretically lighten the frontend payload a lot

**Comment by axoplasm** [comment]
@sanjuroj I would appreciate a second smoke test on this task. Pull the `frontend-refactor` branch & clear caches. The site should look/behave exactly the same as the current dev site.

**Comment by sanjuroj** [comment]
@axoplasm - Will there be a round 2 of this?  Or should we close it.

**Comment by axoplasm** [comment]
Let's close it
