### ISSUE TITLE
Indicator list page: Display updates to unit of measure, baseline, target, KPI, number, without reloading page

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#471]
This is a continuation of issue #68 -- we've introduced some new fields to the indicator rows, that we'd like to auto-refresh just like other fields.

# Issue
When I edit the following elements in the Indicator setup modal, I want to see those changes reflected immediately on the Indicator list page, without having to reload the page:

**Targets tab**
- [x] Unit of measure
- [x] Baseline value
- [x] LoP target value

**Performance tab (not new, just forgot to do it)**
- [x] KPI checked or unchecked ("KPI" appears after the indicator name, or doesn't)
- [x] Number (We intentionally appended it to the indicator name instead of putting into its own column. The placement is behaving as expected, but changes to the number are not reflected.)

**Comment by hannalcamp** [comment]
Tested in dev and all functionality behaves as expected, updates in the popup to all 5 listed elements appear in the indicator list page without refreshing.

**Comment by jennyhavah** [comment]
@sanjuroj Just a heads up that I'm closing this ticket. I have no idea why it's still open. Need to close it in Poblano as well.
