### ISSUE TITLE
Add document: GDrive button doesn't appear to be functional

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#478]
To reproduce, add a new document and attempt to fill in the URL using the GDrive button.

When I select a file in Gdrive, nothing happens.

Marie discovered this bug and can give more details on what she expects to happen. (I haven't used the feature much.)

**Comment by hannalcamp** [comment]
In dev the GDrive button now works perfectly with the first file selection (meaning the google drive popup automatically exits out after the file is selected and displays the correct link in the URL field). 

However if I click the button again to select a different file, after selecting that file the popup stays up (and grayed out) and the cursor spins for some time. If I manually exit out of the popup then the new correct link is entered in the URL field, however I don't think we want the popup to behave like this upon second selections.

I'm working in Chrome.

**Comment by jennyhavah** [comment]
Closing because the issue was fixed.
