### ISSUE TITLE
Change Apache config alias for static files to assets instead of static

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#487]
We need to update the puppet process on the server so the Apache static files alias points to the assets directory rather than the static directory.  

It's not really part of this codebase, however, the changes being made in the frontend refactor require this change to be made before any changes from the dev branch are merged into master and deployed.

**Comment by jennyhavah** [comment]
@sanjuroj This is Done. Ok to close?

**Comment by sanjuroj** [comment]
yes
