### ISSUE TITLE
(PROBABLY WON'T DO) Record and Results forms: Non-Gdrive File picker would be useful for the Add Document form

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#490]
STILL VETTING THIS ISSUE. IT MAY BE A BIT OF A PANDORA'S BOX. SEE COMMENT THREAD

Issue: There is a file picker for Google Drive in the Add document form, but if a file is not stored in Drive, users must directly enter a text string into the URL box.

<img width="390" alt="screen shot 2018-07-17 at 11 45 33 am" src="https://user-images.githubusercontent.com/38020496/42835803-f300d5e8-89b6-11e8-9343-6f7a6e60cc25.png">

Use case: At least 1 office is using Windows-based Synology for document storage in-country, not Google Drive. They will need to enter filepaths into the Add Document form. It would help them if a file picker was available for documents stored in their internal networks, but is not critical.

Priority: Low

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [ ] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
One approach would be to add a second type of browse button (in addition to the Gdrive one) that would simply launch the operating system's file navigator, like this: 
![image](https://user-images.githubusercontent.com/33670923/48730866-6ee54e00-ebf0-11e8-825e-c079374ca035.png)

That way, we don't go down the path of adding new Browse buttons for every type of file storage system. (I think it's ok to keep the Gdrive one since it's the file management system we're currently trying to get most teams to use.)

Thoughts @hannalcamp and @sanjuroj ?

**Comment by hannalcamp** [comment]
Being able to just launch the file navigator would be great.

**Comment by jennyhavah** [comment]
Thinking about it some more, my concern is that if we launch a generic file browser, it might encourage people to choose local files, implying that Tola is uploading and storing them.

@sanjuroj This might be wacky, but is there any way to instruct a button to "launch file navigator but only include shared directories"?  

![image](https://user-images.githubusercontent.com/33670923/48805288-cd332f00-eccb-11e8-86fd-afe352b6b415.png)

**Comment by sanjuroj** [comment]
@jennyhavah I'm not sure.  I'm assuming most users will be using PCs, which is why we set a warning on low drive letters.  But there's no way to tell which drive letters are shared and which ones aren't, as far as I know.

**Comment by jennyhavah** [comment]
@sanjuroj a couple of scenarios for you...

**Happy path:** Let's say we launch the file browser, and they choose a file on a shared directory. Can we easily extract the file path and insert into a TolaActivity form field?

**Sad path:** The user picks a file on their desktop or some wacky destination... Can we easily validate that it's a TolaActivity no-no, and nope them with a PNotify message?

I'm starting to think this might be a fairly complex thing to implement...

**Comment by jennyhavah** [comment]
From Cameron on Slack:

> if someone open the file navigator by clicking “choose file” and navigates to “C:\My Documents\some_file_name.doc” the browser will _never_ be able to get the “C:\My Documents\” part of that.  And by “the browser” I mean “our app” - we have no way to ever discover the location of the file the user picked - that’s a very intentional security feature included in all modern browser standards

and

> yeah, I think this is an insoluble problem because “need for security” (web pages being able to see the contents of your hard drive is horrifying from a security perspective) trumps “ease of use” in this case

Given all of this, closing the ticket.
