### ISSUE TITLE
IPTT TvA reporting displaying actuals not in database

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#492]
The IPTT reporting is showing actuals that are not in the database.  Reported by the Colombia team.

**Comment by sanjuroj** [comment]
This may be a data problem rather than a problem with the report code.  It turns out there are actuals in the database but they are not showing up on the indicator list page.  The problem is that the collected data records have a nonexistent periodic target ids associated with them.   There are only 5 collected data records where this is the case, all associated with Columbia.  

All of the problematic collected data records were entered before the Winterhawks release, so it could be a non-recurring issue that is most easily fixed by directly deleting the periodic_target_id's in the collected data records.  I tested creating periodic targets in a new indicator, adding a result, and deleting the targets.  The periodic target id associated with the collected data record was correctly deleted.

This is the SQL used to find the records in question.
`select 
	id as collecteddata_id, 
	achieved,
	indicator_id,
	periodic_target_id
from 
indicators_collecteddata 
where 
periodic_target_id not in (
select id from indicators_periodictarget
)`

**Comment by jennyhavah** [comment]
We are moving this ticket to Fruit Basket, with the plan to re-run Sanjuro's SQL script to see if there is any recurrence of the problem.

**Comment by jennyhavah** [comment]
@sanjuroj Given how much work has been done on the IPTT since this ticket was filed, I suspect that this issue has been addressed or is no longer relevant. Ok to close?

**Comment by sanjuroj** [comment]
yep
