### ISSUE TITLE
Update the links in the footer section to point to MC URLs.

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#5]
<a href="https://github.com/mahmoodkhan"><img src="https://avatars3.githubusercontent.com/u/717661?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mahmoodkhan](https://github.com/mahmoodkhan)**
_Monday Dec 04, 2017 at 17:03 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/4_

----

As per slack conversation dated 11/30/2017 update links to:
•Documentation: https://sites.google.com/mercycorps.org/tolauserguide/home
•Feedback: https://goo.gl/forms/VuG2UjlBeTAGdJ503
•FAQ: https://thehub.mercycorps.org/page/7271

**Comment by mahmoodkhan** [comment]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jennyhavah](https://github.com/jennyhavah)**
_Monday Dec 04, 2017 at 17:05 GMT_

----

@mahmoodkhan Did you see my comment in Slack about not being able to access the Form Guidance page from Indicators? Not sure if that is connected with this issue or if we should file a separate one?

**Comment by mahmoodkhan** [comment]
@jennyhavah that is a separate issue that needs to be addressed unrelated to this. This issue was about updating links at the bottom of the site to point to MC URLs instead of TolaData

**Comment by esinn** [comment]
@jennyhavah I was able to open all Form Guides for Indicators, Sites and Stakeholders. What specific Form Guide were you unable to open?
