### ISSUE TITLE
UI > Periodic targets table: "Add new" button label varies depending on type of targets being created

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#50]
**Story:** When I need to add a new target period, the "Add new" button reflects the type of targets I am adding.

**CONFIGURATION PRE-CONDITIONS**

![scrap2](https://user-images.githubusercontent.com/33670923/34457479-38eeb13a-ed66-11e7-9dd0-d5e32bf33280.png)

1. Open Targets tab of an indicator
2. Complete all required fields.
3. For _Target frequency_, select any periodic target option _except_ for LoP-only or Midline/Endline.
4. Configure any sub-options and click _Create targets_.

**ACCEPTANCE CRITERIA**

![nexttarget](https://user-images.githubusercontent.com/33670923/34741512-b529854e-f537-11e7-87d9-9aee41f5c969.png)

1. A button appears under the table, aligned with the left edge that enables you to add the next target period in the sequence, just above the _Sum of targets_ row. The syntax of the button is as follows:
1.1. Annual: Add a year
1.2. Semi-annual: Add a semi-annual period
1.3. Tri-annual: Add a tri-annual period
1.4. Quarterly: Add a quarter
1.5. Monthly: Add a month
1.6. Event: Add an event
2. Regression testing: Check to make sure the new target row displays the correct target period label and date range.

**Comment by jennyhavah** [comment]
Phrasing is correct for all target frequencies. However, the plus icon is missing:

![image](https://user-images.githubusercontent.com/33670923/35889589-1256022c-0b51-11e8-90b9-43697111ce89.png)

It should look like this -- please note the vertical and spacing above and below! Sanjuro worked VERY HARD on it. :-)

![image](https://user-images.githubusercontent.com/33670923/35889629-4699ef76-0b51-11e8-945c-19527b7bc8f5.png)

**Comment by jennyhavah** [comment]
Button is there now, but there is now an extra 10 pixels between the bottom border of the table and the top of the orange button. Please reduce that space by 10 pixels (or as close as you can get):

![image](https://user-images.githubusercontent.com/33670923/35945772-281d1012-0c16-11e8-8fac-c5f158d9cb86.png)

**Comment by jennyhavah** [comment]
While you are making a UI tweak in the area of the table, can you please add a space after the word "target"? I think there used to be a space, but now it butts right up against the border.

![image](https://user-images.githubusercontent.com/33670923/35945905-abcbf202-0c16-11e8-93af-2056cc201d87.png)

**Comment by mahmoodkhan** [comment]
The text shifted to the right because we removed the spinners from the numeric field. But I'll add some padding to account for it.
