### ISSUE TITLE
Collected data form: Measure against target drop-down menu details

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#52]
The following details were inadvertently lost when I was pulling out the Collected Data details from various issues related to creating targets. 

**ACCEPTANCE CRITERIA**
~~1. We do NOT display the target value in the "Measure against target" drop-down menu. We received feedback from the PaQ team that including the value of each target is unnecessary and actually confusing in this context. It makes you stop and worry about whether your data record actuals are somehow being calculated against the targets.~~
2. For annual, semi-annual, tri-annual, and quarterly targets, we show the target period name and date range with a bit of space in between each target -- similar to how we display it in the table itself. Here's a mocked up example. Others can be found [in the design wiki](https://learn.mercycorps.org/index.php/Tola:Periodic_Targets#Data_Collected_View).
![scrap](https://user-images.githubusercontent.com/33670923/35083593-c4905f8c-fbd4-11e7-912a-908182ce4162.png)
3. For monthly targets, display the month and year, like so:
![scrap](https://user-images.githubusercontent.com/33670923/35083642-f8746fdc-fbd4-11e7-8423-521d22a00607.png)

**Comment by mahmoodkhan** [comment]
According to the W3C standards at https://www.w3.org/TR/2011/WD-html-markup-20110113/option.html , the option tag for a select element is is limited to "Normal character Data". The definition of "Normal Character Data" is https://www.w3.org/TR/2011/WD-html-markup-20110113/syntax.html#normal-character-data.  So creating multi-line options within a select box isn't really doable unless we use a third-party library, which will add to the loading time of the page.

**Comment by jennyhavah** [comment]
Thanks for looking into this, @mahmoodkhan. I think we can put this aside for now, as the current solution is readable and we have many other higher priority UI issues to tackle. I'm going to close this story.
