### ISSUE TITLE
Program page: Queries for program summary metrics

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#543]
This ticket describes queries we'll need at the top of our new program pages. They will be displayed using some combination of text and (hopefully) graphics, like so:

![image](https://user-images.githubusercontent.com/33670923/48166258-e59f5480-e29c-11e8-86ce-e635a63ec699.png)

### Please see ticket #463 for important context related to program status, time periods, and filtering options. The same context applies to these queries.

# Acceptance criteria

## Query 1: Indicators on track
- [x] This pair of metrics is identical to Query Set 1 described in ticket #463 -- this checkbox  is just to ensure that we display it here as well.

## Query 2: Indicators with targets
These metrics are essentially a program-level version of Query 1 described in ticket #542.
- [x] 1. What percentage of indicators **have targets defined**, meaning that the indicator:
- [x] 1.1. Has a **target frequency** selected.
- [x] 1.2. Has **target values** completed for all periods.
- [x] 1.2.1. In the case of **LoP only** target frequency, the LoP field must have a saved value.
- [x] 2. What percentage of indicators **are missing targets** -- in that they fail the above criteria.
- [x] 3. **Which indicators** are missing targets? (This will be used to filter the list)

## Query 3: Indicators with results
These metrics are essentially a program-level version of Query 2 described in ticket #542.
- [x] 1. What percentage of indicators in this program has _at least one reported result?_
- [x] 2. What percentage of indicators in this program do NOT have any reported results?
- [x] 3. **Which indicators** do not have any reported results? (This will be used to filter the list)

## Query 4: Results with evidence
These metrics are essentially an actionable version of Query Set 2 described in ticket #463. On the home page, we only need the percentage of _results_ that have evidence. On the program page, we ALSO need to know _what indicators_ are involved in order to generate a highlighted list.
- [x] 1. What percentage of **results** have evidence? (Similar to home page)
- [ ] 2. What percentage of **results** do NOT have evidence? (Group by indicator.)
- [x] 3. Which **indicators** have at least one reported result that is lacking evidence?
- [ ] 3.1. **How many indicators** have at least one reported result that is lacking evidence?

## Housekeeping
- [ ] Unit test/s written
- [ ] i18n tags included wherever applicable

**Comment by camgnostic** [comment]
Pull request #712 addresses Query 1

**Comment by camgnostic** [comment]
These are up and in branch 561, being tested then merged in tomorrow

**Comment by camgnostic** [comment]
This is wired up from the backend in branch 561, will update ticket when it's merged in (in refinement/testing)

**Comment by hannalcamp** [comment]
@jennyhavah What are the rounding rules that were set? In my QA program, if I add about 1-3 results with no evidence, the metric stays at "100% have evidence", I assume because of rounding. Would we want to include some % above 0 if even one result has no evidence attached?

**Comment by hannalcamp** [comment]
Same also goes for the reverse - If I have even one result with evidence attached, the metric should not say "No evidence" in red.

**Comment by jennyhavah** [comment]
@hannalcamp Just to be sure: Did you refresh the program page after adding results? Because the charts up top do not (yet) automatically update when you make changes. Ken's working on a solution for that.

**Comment by hannalcamp** [comment]
@jennyhavah I did refresh - the issue (I think) is that when you have a lot of results reported with no evidence, adding 1 with evidence still rounds down to 0% and you get the "no evidence" sign. Same with the reverse - removing one or sometimes even two or three pieces of evidence from a program with lots of results and 100% results with evidence still leaves the metric at 100%.

**Comment by jennyhavah** [comment]
Gotcha. Hmm... It sounds like we need to introduce some new rounding logic to address these situations. What do you suggest, @camgnostic ?

**Comment by camgnostic** [comment]
I could add a rule that maxes out at 99% if there's even one without evidence, reserving 100% for strictly 0 have missing evidence?

**Comment by jennyhavah** [comment]
That makes sense. Should we do the same for the reverse scenario Hanna mentioned, where 0% is reserved for strictly 0 results having evidence?

(This pair of rules would apply to all filters, not just evidence.)

**Comment by camgnostic** [comment]
Estimating this as delivered by tomorrow ~ noon

**Comment by hannalcamp** [comment]
Validated through testing that:
1. Having even one piece of evidence on a program will result in a 1% on the metric
2. Having even one result that is missing evidence will prevent the program from reaching 100% results with evidence.

Thanks guys!
