### ISSUE TITLE
Indicators page: Applying filter to indicator list page results in wrong caret position

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#546]
When the indicator link page is loaded, it loads all programs available to the user.  Clicking on the "X program indicators" link expands the indicator list and rotates the caret symbol to a downwards position.  

When program and indicator filters are applied, the program caret points left but the indicator selected is shown below.  Clicking on the "X program indicators" link causes to caret to rotate to a downward position but hides the indicator list.  Subsequently selecting --All-- in the indicators filter results in a similarly discordant caret direction and indicator shown/hidden state.

**Comment by jennyhavah** [comment]
We no longer have an Indicators page.
