### ISSUE TITLE
Home page: Visual design refinement

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#547]
**Task:** Refine the visual design of the Fruity home page. Most recent mockup attached. 

![image](https://user-images.githubusercontent.com/33670923/44610578-9c695980-a7b1-11e8-9c1e-943e055348e5.png)

**Comment by jennyhavah** [comment]
@axoplasm Regarding the indicator performance chart, I know this approach has issues. For example, here's what would happen if nothing was > 15% above target but there were lots below:

![image](https://user-images.githubusercontent.com/33670923/44596172-239dd980-a780-11e8-87d3-61eed50005d3.png)

While I'm sorely tempted to keep working on this, I need to move on... Look forward to seeing what you come up with!

**Comment by axoplasm** [comment]
This task is now captured as EPIC #180

**Comment by jennyhavah** [comment]
This ticket is no longer needed -- visual designing is happening alongside component development and general UI refactoring.
