### ISSUE TITLE
Program page: Visual design refinement

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#548]
**Task:** Refine the visual design of the Fruity program page. Most recent mockups below.

## Indicator rows all closed
![image](https://user-images.githubusercontent.com/33670923/44610611-bacf5500-a7b1-11e8-849d-081512f7c185.png)

## One indicator row open
![image](https://user-images.githubusercontent.com/33670923/44610604-b3a84700-a7b1-11e8-9512-71047356b608.png)

**Comment by axoplasm** [comment]
This is now captured as EPIC #545

**Comment by jennyhavah** [comment]
This ticket is no longer needed -- visual designing is happening alongside component development and general UI refactoring.
