### ISSUE TITLE
Chart: Visually represent % of program period completed to date

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#549]
We want to represent the percentage of program period completed to date. By "Program period", we mean the date rate from the reporting start date to the reporting end date. This graphic appears on both the home page and program pages.

# Early visual exploration

People struggled to interpret my original donut chart design that looked like this:

![image](https://user-images.githubusercontent.com/33670923/44498665-b3367180-a634-11e8-8148-4828153f39d1.png)

They were puzzled by the use of the term "reporting period" -- wondering if it had something to do with donor reporting timelines, or if it was the same thing as a target period. And the circular graphic didn't seem to evoke a clock as I hoped it would. 

I propose we ditch the chart in favor of an icon that evokes time, and use plain text to communicate the percentage, something like this:

![image](https://user-images.githubusercontent.com/33670923/44498540-edebda00-a633-11e8-97ca-f3e10d9fe60e.png)

The language -- _Program period is XX% complete_ -- removes ambiguity, and the icon strongly evokes time. The icon is also way less effort than generating a donut chart.

# Placement of the graphic

## Home page
Every "program blob" displays the "program period completed" graphic near the program name.

![image](https://user-images.githubusercontent.com/33670923/48167732-86900e80-e2a1-11e8-8e9d-33d7597f6f12.png)

## Program page
Again, we position the graphic in line with the program name at the top of the page.

![image](https://user-images.githubusercontent.com/33670923/48167800-c8b95000-e2a1-11e8-8e7f-eaadc809c610.png)

## Link to Reporting period modal > Rename "Program period"
In both places, the graphic should link to the reporting period modal. 

While we're at it, I propose we rename this page "Program period" -- to be consistent with the link wording and to remove the term "reporting period" that is confusing people.

## Housekeeping
- [ ] Unit test/s written
- [ ] i18n strings included
- [ ] Information contained in the graphic is accessible to people using screen readers

**Comment by camgnostic** [comment]
This is complete and wired up in branch 561 - will update to staging when that branch completes testing/merging

**Comment by hannalcamp** [comment]
Validated in both country and program homepages, completed programs only show 100%, programs in progress are reflected correctly for programs checked in Guatemala, Jordan, and Iraq.
