### ISSUE TITLE
Home page: Program empty state/s

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#552]
# Story
When the system is unable to display metrics on the home page, I am told why not and how I can change that.

# Monitoring and Evaluation Status
![image](https://user-images.githubusercontent.com/33670923/48389698-8f268180-e6b3-11e8-824d-7cfd2a18a110.png)

- [ ] For any of the country-level M&E metrics where the result is zero, we simply show the 0% percent empty gas tank. (The only time this is likely to occur is when a country is rolling out its very first programs -- no need for sadfaces.

# Program blob

## Scenario 1: Reporting start and end dates missing
![image](https://user-images.githubusercontent.com/33670923/48389999-cea19d80-e6b4-11e8-96a5-9563c47b53b0.png)
For an example, look at Pakistan's programs.
- [x] The message says: Before adding indicators and performance results, we need to know your program's reporting start and end dates.
- [x] The link opens up the reporting period modal.

## Scenario 2: No indicators added
![image](https://user-images.githubusercontent.com/33670923/48435153-9dff4980-e730-11e8-8c57-40fcaeca7651.png)

For an example, look at Pakistan's programs.
- [x] The message says: No Indicators have been entered for this program.
- [x] The "Add indicator" button takes you to the new indicator form. (Upon saving the indicator, you'll end up on the program page.)

## Scenario 3: There is at least one indicator in the program, but no targets are set up for any indicator.
![image](https://user-images.githubusercontent.com/33670923/48435168-a9527500-e730-11e8-8377-d672ddf2aff2.png)
Post-Winterhawks, the only way a program can have indicators without targets is if you save the indicator with targets and then delete all the targets. Sadface earned.
- [x] Sadface icon with the message: All indicators are missing targets.
- [x] Underneath, it says: Visit the program page to set up targets. 
- [x] The phrase "program page" links to the program page.

## Scenario 4: Targets are set up for at least one indicator, but no results are reported.
![image](https://user-images.githubusercontent.com/33670923/48435783-1ca8b680-e732-11e8-83a7-e74f1171e95c.png)
- [x] On track: Sadface icon with the message: Unavailable until results are reported. (Regarding the sadface: Emily points out that we want to encourage teams to report results throughout the target period and not wait until the end of the program to enter results. 
- [x] Results and evidence gas tanks are gray and empty.
- [x] Red text "No results" and "No evidence" instead of a percentage
- [x] No percentages displayed for "Have results" and "Have evidence".

Here's a mockup with all varieties of empty state.
![image](https://user-images.githubusercontent.com/33670923/48435837-35b16780-e732-11e8-8d4f-261e991536b8.png)

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [ ] Functionality is accessible to people using screen readers
- [ ] i18n tags included wherever applicable

**Comment by axoplasm** [comment]
This is strictly speaking a component but I think it only has one instance. It might be better handled as a special state of #559

**Comment by axoplasm** [comment]
Screenshots of this build from [555-homepage-scaffold](https://github.com/mercycorps/TolaActivity/commits/555-homepage-scaffold). _These should reflect the mockups above_

### Scenario 1: Reporting start and end dates missing

*__Note:__ This is more accurately start __or__ end dates missing*

![image](https://user-images.githubusercontent.com/169060/48440189-17049e00-e73d-11e8-9b8a-69d2bc2dd01a.png)

### Scenario 2: No indicators added

![image](https://user-images.githubusercontent.com/169060/48440225-2f74b880-e73d-11e8-8db1-513f367e3f79.png)

### Scenario 3: Indicators missing targets

![image](https://user-images.githubusercontent.com/169060/48440278-5b903980-e73d-11e8-89a9-5cbadeeb7f0d.png)

### Scenario 4: Targets are set up for at least one indicator, but no results are reported.

![image](https://user-images.githubusercontent.com/169060/48440315-6fd43680-e73d-11e8-9822-fbc46c5e60ae.png)

**Comment by axoplasm** [comment]
One interesting side effect of the new Program pages is that it's possible to create a route to Program page without start or end dates, but the page itself can't render without those dates. I will ping the development slack channel with deets

**Comment by esinn** [comment]
Overall, this passed all of the acceptance criteria outlined above. Only comment is above.

**Comment by axoplasm** [comment]
@esinn that's easy enough. I added a hotfix. I can revert the hotfix if @jennyhavah or others don't like the emboldening

**Comment by jennyhavah** [comment]
This is the red text, "No results", "No evidence?" Bolding sounds fine -- will take a peek once it is merged.

But that leads me to notice something else: @axoplasm  Why does "Indicators with targets" not say "No targets" in red? Instead, it has the 0 percentage.

**Comment by esinn** [comment]
Looks good!
