### ISSUE TITLE
Program page: Indicator list with results tables

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#559]
The heart of the new program page is the indicators list, that is essentially extracted from today's Indicator list page. Most of the acceptance criteria have to do with catching regressions.

![image](https://user-images.githubusercontent.com/33670923/44065415-5456226c-9f1f-11e8-9c6f-5bcb340d35a6.png)

# Acceptance criteria

## Immediately above the indicator rows
- [x] In the upper left corner above the indicator table is the number of program indicators
- [x] In the upper right corner above the indicator table is the _Add indicator_ button.
- [x] We no longer want the "program container" expansion and contraction mechanism. The indicator rows should always be there.

## Indicator rows
- [x] Indicator rows open and close as expected, revealing the results table
- [x] When you make changes to the indicator name, level, unit of measure, baseline, or target and save changes, your updates are reflected in the indicator row without needing to reload
- [x] Gear icon works as expected

## Results table
- [x] All columns appear as expected and display the expected content
- [x] Pay special attention to the evidence links and project links that appear in the Evidence column
- [x] All rows appear as expected -- be sure to check the full array of target frequencies
- [x] Add results button works as expected

## Empty states and error conditions
The easiest way to check this will be to have the QA database match the Dev database, and to make sure the Dev server has examples of all the following conditions, for comparison purposes.
- [x] When there are no indicators, you see this:
![image](https://user-images.githubusercontent.com/33670923/44066087-49779174-9f23-11e8-8ebd-30b5863f2a7d.png)

- [x] When GAIT dates are unavailable and/or there is an issue with the reporting period, you see this and the link works:
![image](https://user-images.githubusercontent.com/33670923/44066055-23b69110-9f23-11e8-8e08-6409cb8cc427.png)

- [x] If a program reporting period is extended after targets are set up, you see this
![image](https://user-images.githubusercontent.com/33670923/44065993-e164a59a-9f22-11e8-8d3d-0fbee6dbe51a.png)
and within the indicator rows you see this, for any indicators needing additional targets:
![image](https://user-images.githubusercontent.com/33670923/44066006-f2dd5380-9f22-11e8-878a-45291e8764f0.png)

- [x] When no targets are set up, you see this and the button works:
![image](https://user-images.githubusercontent.com/33670923/44066043-127c67ee-9f23-11e8-88d9-729912b69810.png)

- [x] When all targets are deleted after results were already added, you see the message under the table, the link works, and the "Add results" button is inactive, like so:
![image](https://user-images.githubusercontent.com/33670923/44066146-9c6fb9ce-9f23-11e8-8c24-903248eed176.png)

- [x] Midline/endline and event indicators: When a result is not assigned to an indicator, you see an alert under the table, like so:
![image](https://user-images.githubusercontent.com/33670923/44066201-e8457744-9f23-11e8-8f8d-ce3df0e33ae4.png)

## Housekeeping
- [ ] Unit test/s written
- [ ] i18n tags included wherever applicable

**Comment by axoplasm** [comment]
This is strictly speaking a Component, it has a variant in #552

**Comment by sanjuroj** [comment]
@axoplasm This is a page for a single program, so it will be the same DB hit as opening an accordion to show all the indicators for a program.  Provided I'm interpreting her comment right.

**Comment by jennyhavah** [comment]
@axoplasm What I mean is that -- because it's only one program -- there is no utility in having an expandable/contractable enclosing container like this one: 
![image](https://user-images.githubusercontent.com/33670923/46546312-8a350d80-c87d-11e8-98eb-65e038b30c5e.png)

Yes, we need the _content_ inside that container to be incorporated into the program page -- program name, link to indicator plan, etc. But we don't need the expanding/contracting container itself.

**Comment by axoplasm** [comment]
Per conversations today: I am removing the "indicators" link and stopping work on the Indicators List page (https://tola-activity-demo.mercycorps.org/indicators/home/0/0/0/) See #663. All other changes on this ticket & [its related branch](https://github.com/mercycorps/TolaActivity/tree/574-559-sidebar-indicators) refer only to the indicators table on the program landing page

**Comment by axoplasm** [comment]
_this page will still exist at the link above and looks like this now:_

![image](https://user-images.githubusercontent.com/169060/46637883-0431f480-cb13-11e8-8a4b-373f77ffb99c.png)

**Comment by jennyhavah** [comment]
@axoplasm Just to make sure I understand, are you saying that the Indicators page will still exist with the newer layout, but that we won't link to it? Just want to make sure we're not introducing any redundant content to the Program page. For example, all of the things here are already incorporated into the design, so we don't need to repeat them at the top of the indicator list:

![image](https://user-images.githubusercontent.com/33670923/46638081-09437380-cb14-11e8-861e-457b25ab2f34.png)

**Comment by hannalcamp** [comment]
Having trouble reproducing the scenario where you have a result for a midline/endline indicator which isn't associated to either midline or endline. When I add a result it requires me to specify. Other than that, the ticket is validated - I've gone through and changed each listed component and checked that the correct behavior happens for all the indicator rows and results elements, then found existing incomplete or past programs with no indicators/results/reporting period elsewhere to check that the correct warnings are shown.

**Comment by sanjuroj** [comment]
@hannalcamp You can probably achieve that by putting in results against the midline/endline, deleting the targets, and recreating midline/endline targets.  I think you'll wind up seeing unassigned results.

**Comment by hannalcamp** [comment]
Yep that worked - message appeared as expected.
