### ISSUE TITLE
Program page: Filter and highlight indicators with no targets

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#560]
NOTE: This ticket is dependent on queries described in ticket #463. This is an instance of the Percentage Component #550

## Story 
When I learn the percentage of program indicators that do not have targets defined, I want to zoom in on the indicators that do NOT have targets defined, so that I can efficiently remedy the situation.

![image](https://user-images.githubusercontent.com/33670923/48165600-d9b29300-e29a-11e8-94c8-2661aa1820f5.png)

## Acceptance criteria
Near the metric, there is a link that says "Add missing targets". When I click the link, the following things occur:
- [x] The list of indicators refreshes to display only the ones that meet the criteria.
- [x] The filtered list is visually connected to the metric, so that it's obvious you're looking at a subset of the total, and how that subset was determined. (Doesn't need to be a yellow box of course -- just my 2-second solution.)
- [x] The "# indicators" header refreshes to read "# indicators have no targets".  I suggest we use the same warning icon up top and next to this string, to further reinforce the visual connection.
- [x] The "Add indicator" button is replaced with a "Show all indicators" button that restores the full list.

## Housekeeping
- [ ] Unit test written
- [ ] i18n strings included

**Comment by camgnostic** [comment]
This is wired up from the backend in branch 561 - just needs front-end polish (highlight selected filter, change header, add "clear filter" button)

**Comment by hannalcamp** [comment]
@camgnostic @axoplasm I'm seeing the following happen for the program “Autonomia y Empoderamiento Económico de las Mujeres Rurales del Sur del Cauca” in Colombia: 

There are results reported for 45% of indicators, but the “On track” metric looks like this:
![screen shot 2018-11-20 at 11 34 38 am](https://user-images.githubusercontent.com/38020496/48796018-bab0f980-ecbb-11e8-9aeb-e1afdfda8a70.png)

Is this how it is supposed to work? If so I'm thinking something about the formula isn't working as we'd want.

**Comment by jennyhavah** [comment]
As long as there is at least one reported result, I would expect the Indicators on track chart to show up.

**Comment by hannalcamp** [comment]
If I need to move this comment to #543 I can do that, realizing it probably belongs there better.

**Comment by hannalcamp** [comment]
@jennyhavah Clicking one of the buttons for the acceptance criteria above clicked all of them and locked it - can you reset?

**Comment by axoplasm** [comment]
@camgnostic this might be a rounding (or ceil/floor) error. The template tests `scope_percents.nonreporting == 100`

**Comment by hannalcamp** [comment]
For the final acceptance criterion in the list, the "Show all" button appears, but it does not replace the Add Indicator button as the ticket suggests. If this is what we want to happen, then no issue.

**Comment by jennyhavah** [comment]
@hannalcamp Regarding the checkboxes "locking" -- When I do this, it briefly appears to go inactive, but then if I wait a sec, it comes back and I can check/uncheck again. Worst case scenario, you can edit the checkboxes inside the ticket -- i.e. 

`- [x] becomes - [ ]`

**Comment by jennyhavah** [comment]
@hannalcamp Regarding the placement of "Show all". Looks like my mockup doesn't reflect the most recent changes. The placement sounds fine -- no need for it to displace the "Add indicator" button. The one thing to make sure of, though, is that "Show all" only appears when the list is filtered. It doesn't make sense for it to appear when you are, in fact, seeing all. :-)

**Comment by hannalcamp** [comment]
@jennyhavah Yeah the checkbox issues resolved themselves after a couple refreshings - could've also been internet.

On the Show all issue, sounds like things are working as they should, then.

**Comment by hannalcamp** [comment]
Validated. again with new deployment.
