### ISSUE TITLE
Top nav: Program menu

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#564]
# Story
**Someone monitoring lots of programs:** Wherever I am in TolaActivity, I want quick access to program pages so that I don't need to scan the home page every time I want to switch my focus to a different program.

## Important context
- Some TolaActivity users have access to many programs across multiple countries. Senior managers may have access to _all_ programs, spanning the globe.
- Today, we display programs by country on the home page and you can only view one country "portfolio" at a time.
- We may eventually introduce other types of portfolios based on region, sector, potentially even custom portfolios similar to what you find in GAIT.

# Acceptance criteria
- [x] **UPDATED:** I can access the program menu ~~on the right edge of~~ where the Indicators link used to be in the top nav bar.
- [x] To make a long list of programs easy to scan, they are grouped according to the portfolio currently selected on the home page, with the group headers in alphabetical order. _Right now, we only have country portfolios, so programs will always be grouped by country._
- [x] As an alternative to scanning the list, I can search for a program by keyword.
- [x] I can only pick one program at a time.
- [x] Selecting a program takes me to its program page.

## Housekeeping
- [ ] Unit test/s written
- [ ] i18n tags included wherever applicable

**Comment by axoplasm** [comment]
I think either Sanjuro or myself could do this

**Comment by axoplasm** [comment]
quickie spec for the behavior of this menu:

**IF** I have programs in exactly one country in my portfolio:
> The program menu is an alphabetical list of program names, truncated at [x] characters

**ELSE IF** I have programs in more than one country in my portfolio:
> The program menu is organized hierarchically by country

There are two possible options to build that hierarchical menu:
1. Countries are the first-level menu item, with a right-opening menu that expands to show all the programs in that country in my portfolio (preferred option)
2. Programs are all shown in a single menu list, regrouped by Country

**Comment by jennyhavah** [comment]
@axoplasm Wanted to call out this idea from the original ticket:

> As an alternative to scanning the list, I can search for a program by keyword.

If we use the multi-select widget, this would be built-in. (There may be stronger arguments for using a different approach, just wanted to point this out for consideration.)

**Comment by axoplasm** [comment]
Build option 1 is going to be tricky. Submenus were deprecated in Bootstrap 3 as a UX antipattern: https://github.com/twbs/bootstrap/issues/21026

Possible solutions:
-- Accordion folding (https://getbootstrap.com/docs/4.1/components/collapse/)
-- https://codepen.io/surjithctly/pen/PJqKzQ

**Comment by axoplasm** [comment]
Some notes on progress:

Per conversation with Jenny last week, we have abandoned the notion of nested submenu, or any other showy/hidey functionality for this menu. We settled instead on a “Github-style” combo search box. It has this expected functionality:

* Its placeholder text reads “Go to program or country…”
* Clicking in this text box begins searching all __programs__ and __countries__ in my portfolio
* This search should be case insensitive and search the entire program/country name (so “afg” or “fgh” will both reveal “Afghanistan”) 
* __ideally__: it’s fuzzy enough that a typo will still return a close match (e.g. “ag” will return “Afghanistan”)
* __ideally__: it will begin searching on the first letter typed
* __possibly__: the search box will search other strings, for example if I type “Afghanistan” it will show me all the programs in Afghanistan, even if “Afghanistan” is not in the program name
* __possibly__: we might want to truncate very long program names (to around 85 char?)
* I can arrow up/down to choose a menu item, and hit return to trigger it

![program-search-20181025](https://user-images.githubusercontent.com/169060/47517375-d819b180-d83c-11e8-80e4-7ba161f69dfd.png)

**Comment by axoplasm** [comment]
@KennyMonster I've started building this using Bootstrap-Multiselect on [564-program-menu](https://github.com/mercycorps/TolaActivity/tree/564-program-menu). I'm using a templatetag called `program_menu` which is defined in `workflow/templatetags/menu_tags.py.` Feel free to *not* build this using a template tag if you prefer. I am at the point now of starting to hack a multiselect into a search box. Feel free to abandon any or all of this branch. I can work on style or layout so don't sweat that (yet).

**Comment by jennyhavah** [comment]
@axoplasm Looks good! A few comments:

1. **Placement:** Instead of putting it in the middle of the nav bar, I'd prefer to see it as the first menu item on the left after the logo. (Where "Program" is right now in the above mockup.)
2. **Truncation:** I'd like to see what it looks like without truncation before deciding on a character limit. Sometimes the most descriptive text in the program name is not the first few words, so I want to be as generous as possible, within reason.

**Comment by KennyMonster** [comment]
@axoplasm @jennyhavah I finished a select2 based nav menu that I think fulfills the criteria above. It's in the branch ready for testing and feedback.

Still on my todo list getting the internal select2 strings to use translations.
