### ISSUE TITLE
IPTT TvA report doesn't filter on Type

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#568]
The IPTT Target vs. Actual report does not filter by type.  Even after applying a filter, all indicators, regardless of Type, are still shown.  

Steps to reproduce:
1.  Go to IPTT Quickstart page
2.  Select TvA report for TolaData Demo for the program and Annual for the Target Periods.  
3.  Try to filter on TYPES.  There should be only one indicator left in the panel but there are still 5 there.

**Comment by kurtwall** [comment]
In *indicators/views/views_reports* we have this bit o' code:
```
 497         try:
 498             filters['indicator_type__in'] = data['ind_type'] if isinstance(data['ind_type'], list) else [
 499                 data['ind_typ']]
 500         except KeyError:
 501             pass
```
The key on line 499 is mispeeled: `ind_typ` should be `ind_type`. I'll put up a PR.

NB: When I finish the IPTT tests, at least one of them will be a regression test for this.
