### ISSUE TITLE
Bug: disaggregation report Export to PDF doesn't show any data

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#571]
1. Go to a disaggregation report with data, e.g. https://tola-activity-demo.mercycorps.org/indicators/disrep/541/ .
2. Select "Export to PDF"
3. PDF has headings but no data

hint: The template for this page (disaggregation_print.html) is perhaps not well formed

**Comment by jennyhavah** [comment]
Made moot by Goat Tree -- see #1846.
