### ISSUE TITLE
Chart: Visually represent indicators above, within, and below, a 15% "band of variance"

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#577]
We need to create a data visualization expressing program indicator performance for all completed target periods to date. We need to:

1. Refine the visual design of these charts.
2. Figure out how to generate these charts.

The graphic needs to express all of the following:
1. The percentage of indicators _within target range_ where the range is defined as the target plus or minus 15%.
2. The percentage of indicators that are more than 15% _above_ the target.
3. The percentage of indicators that are more than 15% _below_ the target.

![image](https://user-images.githubusercontent.com/33670923/49176649-1e60a580-f300-11e8-813c-86b7cb291046.png)

## Housekeeping
- [ ] Unit test/s written
- [ ] i18n strings included
- [ ] Information contained in the graphic is accessible to people using screen readers

**Comment by camgnostic** [comment]
Pull request #712 is the backend query setup for this indicator display, pending merge to wire up to views

**Comment by jennyhavah** [comment]
Some usability/design feedback for @axoplasm regarding the program page graphs...  Because I am able to click individual links on the "Indicators on track" chart, I find myself repeatedly trying to click on the individual metrics on the other charts as well -- the "x% no targets" or the "91% have evidence", etc.

I do NOT think we should change how any of the graphs function, in terms of what you can/can't filter. But I had an idea for visually differentiating "On track has several different filters" from "This whole thing is a filter". What if, for the three charts EXCEPT for on track, the entire background highlights in yellow, on-hover and on-click, to suggest "this whole thing is a single clickable area? Then once you've clicked, it settles into the yellow outline. We would NOT do that with the Indicators on track one, to communicate that it's NOT one big clickable target.

**Comment by axoplasm** [comment]
FTR here's what I built y.day & will merge this am

![577](https://user-images.githubusercontent.com/169060/49238647-aeacf200-f3b5-11e8-8597-66f4c226f581.png)

**Comment by jennyhavah** [comment]
So much betta!
