### ISSUE TITLE
Task: One-time script to associate existing data records with Life of Program target

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#59]
**This is a task spun off from issue #36:**

The script will look at each indicator and check to see if there are any data records associated with it. Prior to pushing the new release to production:

1. Run a query to find all indicators with manually created custom targets. Document the following:
1.1. Country, program, and indicator number.
1.2. Custom target names
1.3. Values associated with each custom target.
2. Find all indicators that only have a "Temp label for periodic target".
2.1. Dis-associate data records from "Temp label for periodic target".
2.2. Remove the original Periodic Targets table from the Targets tab.

1. If there are NO data records associated with an indicator, then remove all existing targets.
2. If there ARE data records, do the following:
2.1. Set target frequency to "Life of Program only".
2.2. Save this target frequency _even if other required fields have errors or are incomplete_.
2.2. Assign all data records to the Life of Program target.*

*This portion of the script is a one-time courtesy to avoid blocking program teams from accessing existing data records and from adding data to indicators they're already measuring. They can then choose a different target frequency, if desired, and proceed from there.

**Comment by mahmoodkhan** [comment]
This task does not say whether we should delete all existing targets for indicators prior to creating the "Life of Program Only" target?

**Comment by mahmoodkhan** [comment]
For indicators that have non-numeric LOP values we cannot create a "Life of Program Only" target but we sill still dis-associate all collected_data records from existing targets and then remove existing targets.
