### ISSUE TITLE
Fix the "Add Quantitative Output" form for PI and PT by showing Periodic Target and the ability to select a periodic target.

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#6]
<a href="https://github.com/mahmoodkhan"><img src="https://avatars3.githubusercontent.com/u/717661?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mahmoodkhan](https://github.com/mahmoodkhan)**
_Monday Dec 04, 2017 at 17:17 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/5_

----

**Comment by jennyhavah** [comment]
I *cannot* access the dialogue from the Impact tab of the *Long Project tracking form*. I click "Add Quantitative Outputs" and get a gray screen with no dialogue.

I can access the outputs form dialogue from the M&E tab of the Long Project Initiation form and the *short* version of the Project Tracking form.
