### ISSUE TITLE
translation bugs on "Stakeholders" page

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#608]
http://127.0.0.1:8000/workflow/stakeholder_list/0/0/

Stakeholders - nothing on this page has been translated but if I recall, we didn’t send this text to be translated since we aren’t training on it

**Comment by axoplasm** [comment]
@jennyhavah @esinn, IIRC Stakeholders is one of the "workflow" objects we purposely excluded from translation?

**Comment by esinn** [comment]
Correct, we can exclude stakeholders given we are no longer training on it. No need to translate it at this point.
