### ISSUE TITLE
translation bugs on IPTT target vs actual report

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#609]
Once generated, the level titles aren’t translated, e.g. Quarter 1, Quarter 2

![image](https://user-images.githubusercontent.com/169060/45379859-1b360300-b5b6-11e8-85a9-b8c1070f7ae9.png)

When you click on the table to get the detailed results, Target Period titles aren’t translated, e.g. Quarter 1, Quarter 2 

![image](https://user-images.githubusercontent.com/169060/45379876-25f09800-b5b6-11e8-8627-ecd8c09800b3.png)

**Comment by axoplasm** [comment]
This bug has the same cause as #598, please see note there

**Comment by sanjuroj** [comment]
Closed in favor of #598
