### ISSUE TITLE
Collected Data form: date picker error messaging when invalid date is entered 

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#61]
_Note: I'd like to apply this enhancement wherever we use the date picker we're currently using in the Collected Data record form._

**Affects:** "Date collected" field in the Collected Data form.

**Story: When the user types in an invalid date format, the system highlights the error and suggests corrective steps.

**ACCEPTANCE CRITERIA**
When I type an invalid format into the "Date collected" field, the following things happen:
1. The form field is highlighted in red.
2. Underneath the form field, an error message appears: Please enter a valid date such as YYYY-MM-DD, DD-MM-YYYY, or Jul 1, YYYY.

**Comment by mahmoodkhan** [comment]
@jennyhavah Can this issue be closed now? I think we took care of it in the last release.

**Comment by jennyhavah** [comment]
@mahmoodkhan I was aware that we'd made the field more forgiving in terms of the date formats it accepts. What is now considered invalid? The reason I ask is, I'd like us to be as descriptive as possible when giving an "invalid" message. What's wrong, and how do I fix it? 

For example, I entered Dec 5, 1000 and got the message, "Please enter a valid date." The format is fine, so it must be exceeding a date range. Are there some rules we can share in the messaging?

**Comment by mahmoodkhan** [comment]
@jennyhavah Yes, so if the date is 100 years later than the current year or smaller than 1980 then it is considered an invalid date.

**Comment by jennyhavah** [comment]
@mahmoodkhan Is date formatting no longer an issue we'd want to mention in the error message? Does it now accept all commonly used formats?

**Comment by mahmoodkhan** [comment]
@jennyhavah Yes, it should accept all commonly typed date formats.

**Comment by jennyhavah** [comment]
Okay, I think we can leave it alone then. If someone types a date that far out of range, the problem will be obvious to them without us pointing it out. I'll assign to 1.9.3. and close.

**Comment by jennyhavah** [comment]
Oops, don't think I have the ability to assign to a closed project. @mahmoodkhan can you do that or tell me how?

**Comment by mahmoodkhan** [comment]
I will do it.
