### ISSUE TITLE
Update program page metrics when collected data is submitted or targets updated

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#626]
When a new collected data record is added via the collected data modal, the metrics on the page should be updated to reflect the new results.  Similarly, if periodic targets are added or edited through the indicator setup modal, the metrics should be updated accordingly.

**Comment by camgnostic** [comment]
Added an AJAX endpoint to update metrics (in branch 561) - passed to paul to wire up to gauge update on modal close

**Comment by jennyhavah** [comment]
This ticket is dependent on implementation of the React front end framework, that will not be launched with Mangosteen. I am moving this ticket, at least temporarily, to the rolling UI project until we find a better home for it.

**Comment by jennyhavah** [comment]
The React program page was implemented shortly after Mangosteen, solving the issues described here.
