### ISSUE TITLE
Update Help link on Indicator page

### ISSUE THREAD

**Issue by esinn** [mercycorps/TolaActivity#63]
The link to the Form Guide needs to be updated in a few places. Please use the following link to update all locations below: https://docs.google.com/document/d/126B9zmnMhS-KYrmoyswrG2PGglIJPtkSVhkDX4NsMoM/edit 

First, when you go to create a new indicator. The link on the top right, button titled Form Guide
![image](https://user-images.githubusercontent.com/13574772/35251561-ad57847a-ff90-11e7-9a16-85ace9a12fb8.png)

Second, after you successfully create a new indicator and it takes you to the full indicator page. Form Guide button on top right. 
![image](https://user-images.githubusercontent.com/13574772/35251699-3c6653f8-ff91-11e7-9b78-08edc7b0a8c5.png)

Third, from the indicator navigation header after click on an existing indicator. Form Guide button on top right. 
![image](https://user-images.githubusercontent.com/13574772/35251729-69b3d24a-ff91-11e7-8cbb-9cc635b048c4.png)

**Comment by mahmoodkhan** [comment]
I updated the link on the New Indicator page; however, the other links can be updated through the admin interface of the app. Those links are not in the code.

**Comment by esinn** [comment]
Looks good! I'm making a reminder to update the other links in the admin console on Monday.

**Comment by sanjuroj** [comment]
@esinn You may also want to look at the Document that is linked from the Indicator Update page (by clicking on an existing indicator). 

The current link points to a [document](https://docs.google.com/document/d/11Vx8prx3Zod-fJOV1EFBzHOLGnzXazaw37CARNxRVic) that is in the trash.

**Comment by esinn** [comment]
@sanjuroj I was going to wait until we deploy to update those other links but maybe better just to update now instead.
