### ISSUE TITLE
Date picker in French and Spanish: Measure against target field does not react as expected when a valid date is selected.

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#638]
To reproduce on production or demo servers:

1. Set your language to French or Spanish.
2. Go to the Indicators page and click the "Add results" button for an indicator with annual, semi-annual, tri-annual, quarterly or monthly targets.
3. In the Date collected field, pick a date inside the program date range.

**Expected behavior:** Correct target period is selected in the measure against target field.

**Observed behavior:** I get the "This date is outside the target range, please select a date between X and Y" warning.

**Comment by axoplasm** [comment]
Possibly related (?): the warning for your date shows the wrong beginning and end dates

<img width="675" alt="image" src="https://user-images.githubusercontent.com/169060/46238137-24f19180-c33e-11e8-8443-2d4f89c30a2e.png">

vs.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/169060/46238144-33d84400-c33e-11e8-8753-a819e6a1987b.png">

**Comment by axoplasm** [comment]
(to clarify: error text shows the acceptable range is 2017-04-01 to 2022-04-30 when the actual acceptable range is 2017-04-01 to 2023-03-31)

**Comment by jennyhavah** [comment]
When I click "Add results", the "measure against target" field automatically defaults to the first period. I've tested with Semi-annual, Midline/Endline, and Event-based indicators.

This may or may not be related to the fact that selecting a date in the calendar picker doesn't seem to trigger a change in assignment to the target period. It just stays stuck on the first period.

**Comment by jennyhavah** [comment]
For midline/endline and event based targets: It is possible to save the results form without selecting a target.

**Comment by jennyhavah** [comment]
Results are now being assigned to targets when a date is selected. I am no longer seeing the "This date is outside the target range, please select a date between X and Y" warning, when I choose a date with a day > 12.
