### ISSUE TITLE
Date collected field in Results modal shows NaN-NaN-NaN

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#639]
The Date collected field in Results modal shows NaN-NaN-NaN when the language selected has a localized date format that displays day before month and the day is greater than 12.

Example: Spanish is used as the language selection and there is an collected data record in the system with a date collected of September 17th, 2018.  The correct display format is 14 Sept. 2018, which is what appears on the indicator list page.  However, when the modal link is opened for that record, the date appears as NaN-NaN-NaN.

The hypothesis is that the javascript date formatter only really processes english formatted dates and gets confused by what it considers a month number greater than 12.

**Comment by axoplasm** [comment]
See notes alongside commits, also this SO issue https://stackoverflow.com/questions/25193923/localizing-datefield-output-format-in-django-modelform

**Comment by jennyhavah** [comment]
When I click "Add results", the "measure against target" field automatically defaults to the first period. I've tested with Semi-annual, Midline/Endline, and Event-based indicators.

**Comment by jennyhavah** [comment]
Tested on Chrome and Firefox -- both modifying existing results and adding new results with dates that contain days > 12. I am not seeing the NaN-NaN-NaN message in the Date Collected field.
