### ISSUE TITLE
Help program teams update indicator fields with problems

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#64]
We need to contact our Tola-using program teams and them to fix any invalid fields of the following type:
1. Unit of measure
2. LoP target
3. Baseline

To facilitate the process, we are going to email each country a spreadsheet of all fields for any indicators that have problems. We will create a script to update all fields for them. The spreadsheet is here: https://docs.google.com/spreadsheets/d/1ZjjAPthnGKTW6Mqw3YeshKXJiPSl13wr4FhCZVS1bks/edit?usp=sharing

@esinn We would ideally prefer to have one spreadsheet per country, rather than a spreadsheet for every program, so maybe we should send this to the regional or country-level MEL person and have them coordinate with the program teams.

@mahmoodkhan, when you fill in the spreadsheet, please populate any empty field with the word "(empty)" so people know what the problem is.

**Comment by esinn** [comment]
@jennyhavah I don't think it will be a problem to have one spreadsheet per country. A couple of questions: 
What's the difference btwn indicator ID and indicator number? 
What does program number refer to? Is this a backend code? 
Both of those might confuse people a bit. I'm assuming some of those we don't want users to edit or change. If so, perhaps shade that color differently and make a note to update.

 Also, will we be able to run this script at different times for each country?

**Comment by jennyhavah** [comment]
@esinn 

The idea is that Mahmood will generate a spreadsheet that has the indicators with problematic fields already listed out. All the teams need to do is edit the fields with problems -- the columns with red headers.
> What's the difference btwn indicator ID and indicator number?
The indicator ID is a back end code. Mahmood said he might hide this column because it won't mean anything to the teams. The indicator number is an optional field in the indicator configuration modal.

> What does program number refer to? Is this a backend code?
Oh I think this may have been a mistake on my part. I've been looking at a lot of programs that have numbers as part of their naming convention. I somehow interpreted that as "Programs have unique numbers." Which they may, but not relevant here. I'll delete that column.

> Both of those might confuse people a bit. I'm assuming some of those we don't want users to edit or change. If so, perhaps shade that color differently and make a note to update.
The only columns Mahmood will be using for the scripts are the Indicator ID and any corrections they've made to problem fields. The other fields are there just to help the teams recognize which indicators they're editing.

> Also, will we be able to run this script at different times for each country?
I'm not sure how this works -- we can ask Mahmood. My assumption was that we'd do one country at a time, rather than wait for all countries to be done.

**Comment by jennyhavah** [comment]
Pakistan is done -- only a couple of indicators missing valid LoP fields in the updated spreadsheet, that the script couldn't process. The rest looks good.

**Comment by mahmoodkhan** [comment]
@jennyhavah Pakistan, Afghanistan, and Lebanon are done

**Comment by jennyhavah** [comment]
Closing this ticket, because we are tracking this work in a Trello card:

https://trello.com/c/95DstV3S/662-status-of-countries-that-have-submitted-updates-on-their-google-sheets-for-periodic-targets-release-post-to-gh
