### ISSUE TITLE
Browse documents: Add Find a document select widget

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#645]
# Story
When I know exactly which document I'm looking for, I can search for it by keyword instead of browsing and scrolling.

NOTE: Need to see if it's currently constraining documents to ones associated with programs you have access to. (if not, consider implementing this as a separate ticket.)

**Acceptance criteria** 
- [x] 1. Next to the "Filter by indicator" menu is a single-select "Find a document" menu.
- [x] 2. You can start typing the name of the document and get type-ahead suggestions.
- [x] 3. When you pick a document from the menu, the list reloads with the single selected document.
- [x] 4. If you select a document and then switch programs, the "Find a document" menu clears. The list shows you all documents associated with the newly selected program.
- [x] 5. If you select a document and then switch indicators, the "Find a document" menu clears. The list reloads with all documents associated with the newly selected indicator.

![image](https://user-images.githubusercontent.com/33670923/50926806-c478f280-140a-11e9-843b-397e5e85c2b9.png)

**Testing:**
- [ ] IF results provide enough to paginate, ensure Pagination functions properly.
- [ ] Type-ahead function provides results as text is input into search field
- [ ] Results properly reflect information being searched
- [ ] Multiple searches need to be completed to confirm functional implementation based on acceptance criteria. 

**Estimated Test Time w/ Acceptance:**  
1 - 1.5 hours

**Housekeeping** 
- [ ] Unit test/s written wherever applicable
- [x] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@KennyMonster I replaced the term "Record" with "Document" throughout this ticket. So we just need to ensure that the correct term is used for any work you did on it.

**Comment by KennyMonster** [comment]
#1039 Everything should be now back to document hopefully

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 11 58 24 am](https://user-images.githubusercontent.com/23220180/52739871-ae6ccd80-2f86-11e9-9137-cc14cf3c3541.png)
