### ISSUE TITLE
Assist countries in setting up new targets

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#65]
This spreadsheet will facilitate the process of setting up program indicator targets. We need to populate: https://docs.google.com/spreadsheets/d/1ldQAUT8hl8nnmLpURYVx9nJlVL3dPYq17-VXUmUjKcQ/edit?usp=sharing

1. For every country we want to assist, @mahmoodkhan needs to populate columns A-E with existing indicators.
2. @esinn will contact countries and work with them to fill out the spreadsheet. Ideally we would like one spreadsheet per country, so it might be best to coordinate with a country-level staff person rather than program-level.

After we get the spreadsheet back, Mahmood will run a script to set up the requested targets.

**Comment by mahmoodkhan** [comment]
The script is almost done; however, to create targets there has to be target values. For now, I am just setting target_values to zero.

**Comment by jennyhavah** [comment]
As Mahmood pointed out, we need periodic target values to create a useful script. We believe that filling out this spreadsheet would be more work for program teams than setting up the targets themselves. Our goal is not to create extra work, so we're closing this ticket.
