### ISSUE TITLE
Can't save Midline/Endline targets.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#651]
When a midline/endline target period frequency is selected in the indicator setup modal, and the target values entered, the target values can't be saved.  The saving process hangs.

**Comment by jennyhavah** [comment]
When I click "Add results", the "measure against target" field automatically defaults to the first period. I've tested with Semi-annual, Midline/Endline, and Event-based indicators.

**Comment by jennyhavah** [comment]
I am able to both save target values for Midline/Endline indicators. I tried setting up new Midline/Endline targets and modifying existing ones.

It's a tad bit slow on QA, but the changes do eventually save.

**Comment by jennyhavah** [comment]
When I switch from LoP-only to Midline/Endline and click "Create targets", I am no longer seeing the warning message about the effects on data records.
