### ISSUE TITLE
Top nav menu: Remove Indicators link

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#663]
Remove the Indicators link from the top nav.

**Comment by jennyhavah** [comment]
@axoplasm @sanjuroj Given what we discussed in the developer summit -- that we're going to regularly push Mangosteen features into production but be selective about what end users see --  how will we handle this, from a testing perspective? 

For example, I want to make sure that we separate out any top nav related tickets -- i.e. this one and #564 -- and test those somewhere, without setting them on a path to be merged into production.

**Comment by mariebakke** [comment]
@jennyhavah : What does this mean. "without setting them on a path to be merged into production"?

**Comment by jennyhavah** [comment]
@mariebakke I wrote that back when we were thinking of releasing Mangosteen to Production in stages. That's no longer a concern. So if the ticket is looking good, it can go into Done!
