### ISSUE TITLE
Program page: Add single-indicator search 

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#664]
# Background
We are replacing the Indicators link in the top nav menu with the Programs menu. There is one feature from that page that we need to carry over to Program pages: Filtering indicators.

**Story:** When I know exactly what indicator I want to look like, I can quickly access it without a lot of scrolling and filtering.

# Acceptance criteria
- [x] 1. There is a search function immediately above the indicator list, that shows me type-ahead results.
- [x] 2. I can only select a single indicator from the list.
- [x] 3. When I select an indicator, the following things happen:
     - [x] 3.1. Any other filters are cleared -- i.e. the four gauge filters -- with the yellow highlight box around the chart removed.
     - [x] 3.2. The list is reduced to the single indicator I selected.
     - [ ] 3.3. The indicator row is open to expose its results table.
     - [x] 3.4. The _n indicators_ string says "1 indicator" or "1 of _n_ indicators"

**Comment by jennyhavah** [comment]
@axoplasm Regarding the last item about cascading filters... I think there's room for improvement in how we treat cascading, but for now am just suggesting that we keep the cascading behavior consistent across the site... then improve it everywhere in the future.

**Comment by axoplasm** [comment]
Per conversation earlier today, these filters are getting kind of lost on the sidebar. I will try moving them to the top of the indicators list

**Comment by axoplasm** [comment]
There's some confusion about how these filters are nested with the gauge filters. Our proposal is to make this more of a "search for Indicator X" function.

1. Eliminate "levels" filter
2. No checkboxes on "indicators" filter (single select)
3. Clears any other filter (i.e. from Gauges)
4. Displays indicator even if it's been filtered out
4. shows only the filtered indicator
5. Opens results table

**Comment by jennyhavah** [comment]
@axoplasm Ticket is updated to reflect the changes we discussed.

**Comment by axoplasm** [comment]
@jennyhavah the sixth criterion ("Opens results table", which is 3.3 in the original ticket) will be trickier than I expected. Is this a blocking feature? If not, I can make a PR

**Comment by jennyhavah** [comment]
> @jennyhavah the sixth criterion ("Opens results table", which is 3.3 in the original ticket) will be trickier than I expected. Is this a blocking feature? If not, I can make a PR

@axoplasm Not a blocking feature. @KennyMonster would this be easier to implement in React?

**Comment by KennyMonster** [comment]
@jennyhavah It believe it will be easy enough in React.

**Comment by jennyhavah** [comment]
Looks like the "Find an indicator" field is not empty like we discussed. It's constistently displaying the first indicator.

![image](https://user-images.githubusercontent.com/33670923/49171011-61b41780-f2f2-11e8-9304-af2b33f0d39e.png)

**Comment by axoplasm** [comment]
Here's an object lesson in writing down every requirement: I thought this *was* the behavior we agreed on! 

This is `multiselect`'s default behavior (select the first `<option>` in the `<select>` list) and we're trying to work around it. We removed that first option ("Find an indicator…") in commit 3b18c2f as it would be selectable & would filter on `""` (blank string) — returning an empty list. That's why we added the "Find an indicator" label.

There might be a JS workaround to print a string like "none selected" into the multiselect when it loads. If I can't wire that up quickly, is this a blocking feature?

**Comment by jennyhavah** [comment]
Ah, my understanding was that we were moving "Find an indicator" out of the select box and that box would therefore be empty, which is what I'd hoped for.

I find it disorienting to have the first indicator selected. I don't understand what that's telling me. If an indicator is selected, I expect the list to be filtered on it. So I'm getting cognitive dissonance between the selected indicator and the list of multiple indicators below it.

I do think the current state of the "Find an indicator" function is a release blocker. We would need some way to not have an indicator auto-selected, or at least visually simulate that state. If that's going to take a substantial amount of throwaway work, then I suggest temporarily removing the feature until we can build it in React.

**Comment by jennyhavah** [comment]
Validated. When there is no selection, I see the phrase "None selected", like so:

![image](https://user-images.githubusercontent.com/33670923/49240493-23822b00-f3ba-11e8-9294-bd48d6a38252.png)
