### ISSUE TITLE
Use ID or NAME attributes on any UI element that will require testing

### ISSUE THREAD

**Issue by kurtwall** [mercycorps/TolaActivity#67]
The single best development practice that helps QA testing the most is to **use either the _id_ or _name_ attributes on all UI elements which require, which _might_ require, or which you are even thinking about using for user interaction.** These attributes make it easy to select, interact with, and test because they have to be unique per page. They are also less likely to change than most other parts of a web page. Finally, SeleniumHQ claims that element lookups by _id_ or _name_ is faster than any other access strategy.

**Comment by mahmoodkhan** [comment]
This issue is going to be a work in progress. As I edit/change HTML files I will continue adding id/name attributes.
