### ISSUE TITLE
Indicator setup > Targets tab: Convert LoP target to a numeric field

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#672]
Converting the LoP target to a numeric field will afford a number of future enhancements related to periodic target setup (for example, automatically calculating the LoP instead of manually entering it) and disaggregation of results.

## Step one: Back up non-numeric values
- [ ] Just to be cautious, preserve a backup copy of all non-numeric LoP field values along with the associated indicator, program, and country.

## Step two: Execute a script that does the following
- [x] 1. Check to see if the LoP value contains non-numeric values
- [x] 2. If YES, the following happens:
- [x] 2.1. Append a string ABOVE any existing text in the _Rationale for target_  field, so that it's noticeable and easily deleted, "The original LoP target value was: [value here]. (The LoP target must be a number larger than zero, and cannot include letters or punctuation.)"
- [x] 2.2. Any original text in the _Rationale for target_ field is preserved under the update message. 
![image](https://user-images.githubusercontent.com/33670923/48574440-09c5eb80-e8c4-11e8-83a4-3ed6a528fda9.png)
- [x] 3. The non-numeric value is removed from the LoP target field.
- [x] 4. Because the field is empty, the validation message we already have in place should appear, "Please enter a number larger than zero."

## Step three: Convert the LoP field to numeric
- [x] 1. I can only enter a number.
- [x] 2. Important: I am prevented from entering any symbols, including mathematical symbols like ~positive and~ negative sign. (We prefer to capture this detail in the direction of change field.)

**Comment by camgnostic** [comment]
@jennyhavah  is moving this to Mangosteen as it is a larger ticket than Ghost Pepper.

**Comment by sanjuroj** [comment]
@jennyhavah I've listed below the counts of each category of what the LoP target could be.  The ones that would require some work to figure out are the "Other" and "Float" categories which represent difficult to interpret text and floating point numbers respectively.  
  Other: 117
  Float: 99
  Integer: 3119
  Number with comma/space: 122
  Null in DB: 110
  Percent: 52
  Empty String: 489
  Entered N/A: 80

**Comment by jennyhavah** [comment]
@sanjuroj I did a bit of digging in Slack, and it turns out Mahmood did a bunch of work to automatically fix as many baseline and LoP fields as he could with a script, back in February. See https://mercycorps.slack.com/archives/G4NT6MJ15/p1519145422000399 

I'm surprised to learn that we still have a bunch of LoP values with percent signs. Just a guess, but I wonder if Mahmood's script successfully converted those indicators to the percent type but did not update the LoP field to remove the percent signs.

In addition to Mahmood's script, we ran queries and created custom spreadsheets for each country that the team sent out with detailed instructions to fix invalid fields (including LoP fields and quick links to the indicators involved. 

Given all of the development and communications efforts we've already put into this, and the very long grace period since Winterhawks was released, I don't think we should invest additional time and effort trying to figure out and fix these LoP fields. It's likely that many of these programs are no longer being tracked; in fact, Emily made it a point to reassure teams that fixing those fields was only essential for programs they were still tracking. So they may made a very intentional decision not to put in that work.

As I see it, we can go one of two routes:

1) Preserve the queries you ran in a format that would allow us to easily track down old LoP values if teams reach out to us about it. Go ahead and convert the field to numeric and wipe out the invalid values.

2) We go with the solution I described in the ticket -- quite a bit more involved, but it preserves the values in the interface rather than in a spreadsheet somewhere.

Thoughts?

**Comment by esinn** [comment]
If teams haven't gone through an update the values already I highly doubt that they are active programs or that they're actively tracking their indicators in Tola. I agree that we should move forward with option 1 and let's just make sure that everyone, esp Marie and Hanna, know what will happen and where they can find the original values in case a user asks about them.

**Comment by jennyhavah** [comment]
Following up on this acceptance criteria:

![image](https://user-images.githubusercontent.com/33670923/49690428-c0914200-fae5-11e8-9d77-be27fcb766fb.png)

Right now, I get the expected validation message when I enter a negative sign like -5. But I don't get it when I enter a plus sign like +5. It doesn't actually save the symbol, but it _appears_ to accept the value, and we want people to use the direction of change option to express positive direction of change. They might overlook it if the system appears to be accepting the +.

I'd like to request the following IF they won't take more than 15 minutes:

1. Show the validation message if I enter a + sign. 
2. I'd like to simplify the validation message which is a bit out of date. Right now it says:

> Please enter a number larger than zero with no letters or symbols. If your target is a percentage, describe it in the unit of measure field.

I'd like it to just say: Please enter a number larger than zero with no letters or symbols.

**Comment by camgnostic** [comment]
Per Slack - the validation of the "+" sign as non-numeric is a bigger lift and may appear as a GP ticket later.  For this ticket updated the validation messaging https://github.com/mercycorps/TolaActivity/pull/958
