### ISSUE TITLE
Reporting period modal date picker opens on wrong date

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#674]
Noticed this while trying to change the reporting period end date.  When the modal opens, the end date field shows the correct date.  However, when the end date field is clicked and the date picker is triggered, the end date field is overwritten with the wrong date.  Haven't yet detected a pattern to what the new date is.  Sometimes it's today's date, other times it is not.  

This probably happens with the reporting start date field too, it should be checked.

![before click](https://user-images.githubusercontent.com/6685499/46975422-6773d780-d07b-11e8-9330-4d5cfe45b426.png)

![after click](https://user-images.githubusercontent.com/6685499/46975440-7064a900-d07b-11e8-8bcd-13975cbee20e.png)

**Comment by camgnostic** [comment]
Near as I can tell the pattern is the latest existing periodic target

**Comment by jennyhavah** [comment]
The date is no longer changing when I click into the date picker. 

However, @sanjuroj and @camgnostic I noticed that I am able to do the following on QA:
1) Modify the start date after target periods are set up.
2) Move the end date earlier after target periods are set up.

We tested that behavior pretty thoroughly before the Winterhawks release, so I'm wondering if we have regressions -- that may or may not be related to this specific ticket. Here are the relevant tickets from Winterhawks in no particular order:

#258 Program Indicator List view: Setting reporting period start and end months 
#349 Override Program save method to pull GAIT dates and set program and reporting dates
#227 Pull program start and end dates from GAIT and use them to set reporting start and end months

**Comment by sanjuroj** [comment]
Upon trying again, Jenny couldn't replicate this problem, nor could Cameron or Sanjuro.  So this will be considered fixed.  The previous problem that Jenny saw may have been caching problem.
