### ISSUE TITLE
Extending reporting period duplicates period names

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#675]
When time-aware target periods already exist for an indicator, and the reporting period end date is pushed out beyond the last target period, additional target periods are automatically generated when the indicator modal window is opened.  The numbering for these target periods is reset to 1, so duplicate Year 1, Year 2, etc... would be created for annual periods.  The time values themselves are correct, just the label is incorrect.  

The new label numbering should follow in sequence from the last existing period.  

![image 1](https://user-images.githubusercontent.com/6685499/46977644-8ffed000-d081-11e8-9103-ea071fa318a0.png)

**Comment by camgnostic** [comment]
Note - clicking the datepicker in the reporting period modal resets the date to current (losing the information that prepopulated the field)

**Comment by jennyhavah** [comment]
I extended the reporting period by one year, from 2021 to 2022, like so:
![image](https://user-images.githubusercontent.com/33670923/47240379-fabf4c80-d39c-11e8-901f-6b9b00e9c4d1.png)

- Annual periods numbered correctly: Year 5 added after Year 4. Date ranges look good.
- Semi-annual periods numbered correctly: Periods 9 and 10 after period 8. Date ranges look good.

I couldn't find quarterly, tri-annual, or monthly examples, so I set those up and extended the period from 2022 to 2023

- Tri-annual periods numbered correctly: Period 19 after 18, date ranges look good.
- Quarterly periods numbered correctly: Q21 after Q22. Date ranges look good.
- Monthly periods numbered correctly: May 2023 after Apr 2023, date ranges look good.

**Comment by jennyhavah** [comment]
@sanjuroj Something I noticed that may or may not be expected behavior:

If I extend the reporting period, I have to enter values for ALL newly generated periods before those periods will show up in the Target vs Actuals IPTT.

I feel like this may be just fine, but want to validate that nothing has changed in this regard.

**Comment by sanjuroj** [comment]
We should see if there are existing indicators with duplicated labels in the production database.
