### ISSUE TITLE
Approval of project tracking form should lock the form

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#689]
When a Project Initiation form gets approved, it is locked so no more changes can be made.  This doesn't happen for the Project tracking form, it remains open and can be modified even after it is approved.  We should prevent changes to the project tracking form once it has been approved.

Need to check with other Projects users if this workflow is suitable for them.

- [ ] Lock the tracking form in the same way as the initiation form is locked.
- [ ] Send an email notification that the project tracking form has been approved.

**Comment by jennyhavah** [comment]
Closing because we're no longer working on Projects.
