### ISSUE TITLE
Collected Data Modal: date values are assigned to the proper periods

### ISSUE THREAD

**Issue by kurtwall** [mercycorps/TolaActivity#691]
For annual, semiannual, triennial, quarterly, and monthly target periods, validate that a given date value is assigned to the correct target period iff that value falls within the program's lifetime.

Covers these test cases:

- Collected data datepicker
  - using clicked dates
    - it('assigns data to correct period of annual program if collected in program lifetime')
    - it('assigns data to correct period of semiannual program if collected in program lifetime')
    - it('assigns data to correct period of triannual program if collected in program lifetime')
    - it('assigns data to correct period of quarterly program if collected in program lifetime')
    - it('assigns data to correct period of monthly program if collected in program lifetime')
  - using keyed dates
    - it('assigns data to correct period of annual program if collected in program lifetime')
    - it('assigns data to correct period of semiannual program if collected in program lifetime')
    - it('assigns data to correct period of triannual program if collected in program lifetime')
    - it('assigns data to correct period of quarterly program if collected in program lifetime')
    - it('assigns data to correct period of monthly program if collected in program lifetime')

**Comment by kurtwall** [comment]
Implemented by @camgnostic at 0f2b62c

**Comment by sanjuroj** [comment]
It's unclear what we will be doing with front-end testing now.  We'll either reopen this or recreate it if we start on this kind of testing again.
