### ISSUE TITLE
Reporting period modal: I am able to modify dates I shouldn't be able to modify

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#699]
# Issues
1) On the QA server, for a number of programs in Afghanistan, I can modify the **start date** after target periods are set up. <-- Sanjuro just reminded me that this is okay as long as ALL of the indicators are NOT time-aware frequencies -- i.e. it's okay if they're all LoP only, midline/endline, and/or event indicators.
2) I can move the end date **earlier** after target periods are set up. 

We tested that behavior pretty thoroughly before the Winterhawks release, so I'm wondering if we have regressions. Sanjuro suggests taking a look at recent date picker updates.

## Related tickets
To understand the desired behaviors and what this modal is all about, check out the following tickets from Winterhawks:
#258 Program Indicator List view: Setting reporting period start and end months 
#349 Override Program save method to pull GAIT dates and set program and reporting dates
#227 Pull program start and end dates from GAIT and use them to set reporting start and end months

**Comment by sanjuroj** [comment]
According to Marie, Myanmar was participating in the SEA training so the date difference noticed for Myanmar's programs/indicators may have been related to simultaneous changes made during training.

I think we can close this ticket as not being a problem we see in real world situations, unless we see it outside of a training.
