### ISSUE TITLE
Program does not show up in the dashboard filtering menu

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#7]
**Reported by:** Amisial Ledix in Haiti
**Affects:** TolaActivity dashboard for Haiti, not sure if it's unique to this program/country or if it affects others in other countries

**How to reproduce issue:**
1. Visit the dashboard for Haiti in TolaActivity. Note that the program called Ann viv Ansanm does not show up in the Program filtering menu
2. Visit the Indicators page. Note that the program _does_ show up there.

![missingprogram](https://user-images.githubusercontent.com/33670923/33570296-335fb46a-d8e1-11e7-8ba7-9db22f538478.png)

**Comment by mahmoodkhan** [comment]
It seems like the reason that program "Ann Viv..." does not show up under dashboard is because there is nothing associated with it. I mean, there is no projects or indicator data associated with it.

**Comment by jennyhavah** [comment]
Thanks, I'll let Amisial know. Seems like we can resolve the issue as "not a bug".

**Comment by jennyhavah** [comment]
@mahmoodkhan Can you create a new program in the demo site that has no projects? That will allow me to verify that this issue is fixed. Right now it looks like all programs have projects.

**Comment by mahmoodkhan** [comment]
@jennyhavah Created a program called "MC Tola Test" with nothing in it.
