### ISSUE TITLE
Create dummy user to execute tests on practice sessions

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#70]
From Marie: We will need a dummy user to execute tests on practice sessions. This will need to be completed next week, no later than Feb 6th.

@mahmoodkhan I don't really know what's involved, so this is just a placeholder task with no details.

**Comment by sanjuroj** [comment]
@mahmoodkhan I can probably do this.  I'm wondering if we should also have a google user to replicate new Tola users?  Maybe we already have one?

**Comment by jennyhavah** [comment]
This may or may not be helpful: https://docs.google.com/document/d/1vAyp5oRv4IZU4wh8JUxD196kIIzbxun-Kl_hpEgtybM/edit#

**Comment by mahmoodkhan** [comment]
@sanjuroj I already had created a test account in ldap/sso so I am just going to use that one. I can give you credentials for it in person later.
