### ISSUE TITLE
Record form: Verify file is accessible via link provided

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#702]
When creating a document, the user puts a link to the file into the field provided.  It would be nice to check if the link is valid, via the front-end, as much as possible, since the resource may not be available from the Tola server.  

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [ ] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@sanjuroj I am creating a new ticket #820 that addresses this issue and connects it to several others. Don't want you to get a bajillion notifications as I keep updating the ticket.
