### ISSUE TITLE
Introduce a success indicator near the "Save changes" button

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#707]
We are introducing a new, consistent pattern for handling success messages. Instead of this...

![image](https://user-images.githubusercontent.com/33670923/47381877-dd98bf80-d6b5-11e8-8340-8aafdcb0232e.png)

... @axoplasm suggested a text-free visual indicator such as a check mark near the Save changes button.

Another potential approach would be to use a PNotify notification, as described in #707. This approach gives us the optoin to include text and links where it's helpful, without needing to worry about where everything will fit, since it's above the page.

Open questions:
1. Where are all the places this needs to change?
1.1. Does this include _all_ submit type buttons? For example, do we need it with the Apply button at the bottom of the IPTT filter panel, or is the reloading of the IPTT itself enough system feedback?
2. Do we include or exclude errors related to Project-related forms?

**Comment by KennyMonster** [comment]
The PNotify growler library was added as part of mangosteen (#708) and can be used to replace these one-off success messages if desired.

**Comment by jennyhavah** [comment]
Folded this into 706, as I think we should look at these patterns in tandem, not as separate explorations.
