### ISSUE TITLE
Collected data record and Home: Format "Achieved value" numbers consistently (without the .00)

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#72]
We removed the extraneous .00 from Target numbers unless the user manually entered fractional decimals. We'd like to also do this with Actual value number the Collected Data record form as well.

In the following example, note that the Achieved value field in the image below currently has the .00.
![image](https://user-images.githubusercontent.com/33670923/35486050-30c848ae-041d-11e8-8bd6-ead433dce036.png)

Let's also fix the discrepancy in the table at the bottom of the Home page. Note that the LoP target column has no extra decimals, but the Actuals column does:
![image](https://user-images.githubusercontent.com/33670923/35486259-38878cf0-0420-11e8-9494-09f1192b2e08.png)

**Comment by jennyhavah** [comment]
Validated that extra .00 are not shown for previously entered records. 

Question, @mahmoodkhan: Going forward, if someone _manually_ enters a .00, it seems like we should display it, don't you think? Imagine a program is tracking data for an indicator where every target and actual value is carried out to two decimal places. They may want the .00 so that it all lines up neatly.

Currently if I manually enter .00 it is not preserved. Can we display .00 as long as it's manually entered?

**Comment by mahmoodkhan** [comment]
@jennyhavah Currently, It is a decimal field with decimal places. To differentiate from the user entered .00 vs the system generated ones is going to be high level of effort. I am not sure many users would even notice It unless there is a UX person like yourself.

**Comment by jennyhavah** [comment]
> I am not sure many users would even notice It unless there is a UX person like yourself.

JUST WHAT ARE YOU TRYING TO SAY.  ;-)

Ok, I'll move this to Done.
