### ISSUE TITLE
Indicator number is duplicated when the indicator is changed.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#748]
Whenever you make a change to an Indicator, in indicator setup, in Production, the system duplicates the Indicator Number in the indicator list. Screen shot provided.

![screen shot 2018-11-07 at 10 12 14 am](https://user-images.githubusercontent.com/6685499/48150981-f9cf5b80-e274-11e8-9965-06cca2b653df.png)

**Comment by mariebakke** [comment]
@camgnostic : I am having trouble testing this ticket. I cannot get my Indicator to save changes.
![screen shot 2018-11-29 at 5 07 39 pm](https://user-images.githubusercontent.com/45101655/49255222-5a2b6600-f3f9-11e8-92cb-aca31e9d57a5.png)

**Comment by mariebakke** [comment]
PASS. Confirmed that changes made to indicator details does not result in a duplicated Indicator Number. (See Indicator 1.1.3)
![screen shot 2018-11-29 at 5 29 05 pm](https://user-images.githubusercontent.com/45101655/49256257-606f1180-f3fc-11e8-8827-b081e657ba20.png)
