### ISSUE TITLE
Add indicator name field to indicator creation form

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#749]
Add a field for indicator name to the indicator creation form.  Doing this will discontinue our current practice of using "Temporary" as a placeholder name.

**Comment by esinn** [comment]
The only issue I found is when I went to add an indicator from the DIG. I selected the service template, the DIG, and then searched for a specific indicator in the DIG and tried to create it but it said I needed to give it a name. When I did it didn't use the custom name I entered in in the indicator name field, it used the correct DIG name, but ideally I think if you select a DIG indicator the name field shouldn't still be required.

**Comment by sanjuroj** [comment]
The preferred behavior is that as soon as the user selects a DIG indicator, the value of the selection should be copied to the Name field.  This field should still be editable, because they might want to modify it.  Also the name field should probably be moved below the DIG selectors so they don't try to manually enter something first.

**Comment by esinn** [comment]
Selected custom indicator, added name and hit save and received the following 404 error :(
![image](https://user-images.githubusercontent.com/13574772/48518480-94eca600-e81e-11e8-9c05-6c4f464af67d.png)

**Comment by esinn** [comment]
My profile is set to Timor Leste but b/c my base location is US I always see the US too.

When I selected add an indicator for a program, TolaData Test or Demo, that's a US program however it showed up under country Timor Leste.

**Comment by esinn** [comment]
On the indicator create page consider changing the following text:
Current: "Are you adding a custom indicator an indicator from the Design for Impact Guide (DIG)?"

Change to: "Would you like to add a custom indicator or an indicator from the Design for Impact Guide (DIG)? 

Tagging @jennyhavah to review language.

**Comment by sanjuroj** [comment]
@camgnostic When I get to this page locally, the program and country fields are blank.  It works fine on the Demo server, but not locally.  I'll run through the code to see if I can figure out why.

**Comment by sanjuroj** [comment]
The issue I mentioned above was just a local server issue.

**Comment by esinn** [comment]
Looks great! Nothing I can find to comment on .
