### ISSUE TITLE
Result form: Link target for evidence broken in some cases (when TolaTable is used as evidence)

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#753]
Evidence section of Result form: When a TolaTable has been selected as evidence, convert it into a usable link as a regular Record, rather than as a Tola Table record.  Since we are deprecating Tables links, the special field on the Results table for Tables evidence can also be removed.

**Comment by jennyhavah** [comment]
See my comment on ticket #1040. This might be better addressed as part of the script being written in that ticket.

**Comment by jennyhavah** [comment]
@sanjuroj Ok to close this ticket, based on the discussion in #1040?

**Comment by sanjuroj** [comment]
Yep.
