### ISSUE TITLE
Indicator list and setup modal: Indicator name changes no longer automatically refresh upon saving changes.

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#767]
To reproduce, change the name of an indicator and click "Save changes".

Expected: The name updates immediately without having to reload the Indicator list page. (It is working as expected on Production.
Observed: It does not update.

**Comment by jennyhavah** [comment]
Did we already make changes to the name field in order to make it a required field? If so, wonder if that work could somehow have triggered this regression.

**Comment by KennyMonster** [comment]
Neither Jenny or I were able to reproduce this, so it's probably safe to go out for GP.
