### ISSUE TITLE
Home and program page: Explanations of metrics

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#769]
## Story
If I'm unclear on how home page or program page metrics are calculated, I can learn more without needing to consult TolaWiki.

## Format
I don't have a strong opinion on the formatting. I'm thinking question mark icon with some sort of pop-up or pop-over similar to what we're using to pin an IPTT report.

#### TEXT
**Programs have targets defined for all indicators:** Each indicator must have a target frequency selected and targets entered for all periods. 

**Indicators have reported results:** Each indicator must have at least one reported result.

**Reported results are backed up with evidence:** Each result must include a link to an evidence file or folder.

#### TEXT
**On track:** The actual value matches the target value, plus or minus 15%. So if your target is 100 and your result is 110, the indicator is 10% above target and on track. 

Please note that if your indicator has a decreasing direction of change, then “above” and “below” are transposed. In that case, if your target is 100 and your result is 200, your indicator is 50% below target and not on track.

**Unavailable:** The indicator has no targets, no completed target periods, or no results reported.

#### MOCKUP
![image](https://user-images.githubusercontent.com/33670923/48449971-35789280-e759-11e8-9e62-0e5f285180d1.png)

## Program page

I propose we only repeat the "Indicators on track" description. The others seem pretty self-explanatory, and I'm wary of littering the blob with lots of question marks.

![image](https://user-images.githubusercontent.com/33670923/48450043-84262c80-e759-11e8-8f13-de108a05121f.png)

**Comment by jennyhavah** [comment]
@axoplasm A bit of usability feedback for you. I find myself constantly trying to click the question mark icon to dismiss the tooltip. 

Can we make it so that you can dismiss it by clicking anywhere outside the area OR by clicking on the icon again?

**Comment by axoplasm** [comment]
@jennyhavah without some extra work, this is an either/or situation. 

__EITHER__
clicking on the little question mark (and only on this icon) will dismiss the popover
__OR__
clicking anywhere _except_ the little question mark will dismiss it

**Comment by jennyhavah** [comment]
@axoplasm Are we talking hours, days, or infinity? And would the extra work be easily re-used wherever we have a ? popover?

**Comment by axoplasm** [comment]
> hours, days, or infinity? 

Days

> And would the extra work be easily re-used wherever we have a ? popover?

Yes!

Not impossible but also not a "can you just do this real quick" type problem either.

**Comment by jennyhavah** [comment]
Hmm, ok in that case, let's keep as is -- clicking anywhere _except_ the little question mark will dismiss it. I can file a ticket if it continues to bug me and (more importantly) if anyone else complains.

**Comment by jennyhavah** [comment]
For "programs have all targets defined", please add a period at the end of the sentence. (It's the only one without a period, others are fine.)

![image](https://user-images.githubusercontent.com/33670923/49188678-82936180-f320-11e8-8ec0-c438ee3ba94b.png)

For "XX% are on track", would it be easy to break this big blob of text into two paragraphs? The second paragraph would start with "Please note..."

![image](https://user-images.githubusercontent.com/33670923/49188832-f6ce0500-f320-11e8-9911-b8ee40c5db79.png)

**Comment by axoplasm** [comment]
I fixed the text edits in commit 238da3a .

For the (?) icons, what is your browser? I can't replicate in Safari, Firefox or Chrome

OTOH this lets me put a spike in something I've been wanting to do for a long time (see #653)

**Comment by jennyhavah** [comment]
Text changes validated. No need to address the question marks as part of this ticket.
