### ISSUE TITLE
Profile page: Remove everything except the language field

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#792]
This ticket was originally about the Accessible Countries field on the Profile page, but now I am recommending we get rid of everything on that page except the language menu.

# Recommended changes
- [x] 1. Remove every field on the Profile page except for the language selection menu.
- [x] 2. Remove the "required" asterisk after the word "Language". (It's impossible to save the form without a selection, so the asterisk is meaningless.)
- [x] 3. In the top nav, replace the user's name with the word "Settings" -- with translation tags around it.

![image](https://user-images.githubusercontent.com/33670923/48593075-16683500-e900-11e8-8601-7064fd472306.png)

# Back story
On the profile page, the Accessible Countries list is mislabeled and misleading. It does not actually control access to countries; those permissions are managed in the Admin console, by an admin, not the end user. What that field actually does is give you a way to choose only a sub-set of countries from which to display programs on the Home and Indicators list page. Both of those pages currently show programs across multiple countries; both of those programs are going away with Mangosteen. Our new Home page only displays programs from a single county at a time, and you can switch countries using two different methods -- the menu above the site map or the menu in the top nav bar. 

With the release of Mangosteen, the "Accessible Countries" field serves no discernible purpose, so I'd like to get rid of it.

Come to think of it, with the exception of the language field, every field on that profile page is either useless or problematic. Useless: Seeing my own employee information redundant with The Hub, Workplace, etc. Problematic: As an end user (not an Admin) being able to edit my employee number, country, and... edit the User? What in the actual heck... 

# Incidentally...
This ticket reminds me of a prototype I saw for a user-friendly TV remote control.
![image](https://user-images.githubusercontent.com/33670923/48596346-87621980-e90d-11e8-98e7-b72f7672e026.png)

**Comment by esinn** [comment]
Maybe my favorite ticket yet @jennyhavah!! 

I don't see any issues with removing all fields except language. My only comment is why do we even need a profile page then? Couldn't we just put the language selection in the top nav somewhere so it's more accessible?

**Comment by jennyhavah** [comment]
@esinn I'm reluctant to add the language menu to the top nav because for most people it will be a one-time set-and-forget item. You don't translate page by page, like a Google plugin.

So this rarely-used menu would compete for space and attention with the much more frequently used items such as program/country search, reports, etc.

**Comment by esinn** [comment]
Aha got it. That makes sense 👍

**Comment by jennyhavah** [comment]
@axoplasm Sounds good! Just added that to this ticket as the third item.

**Comment by axoplasm** [comment]
This is ready in PR #849:

![image](https://user-images.githubusercontent.com/169060/49175780-31727600-f2fe-11e8-8e16-e87063a9fa6b.png)

![image](https://user-images.githubusercontent.com/169060/49175810-40f1bf00-f2fe-11e8-8ce7-56c57f9f5ee5.png)

**Comment by axoplasm** [comment]
That's correct, "Settings" has not yet been translated
