### ISSUE TITLE
Upon saving a new indicator: Update success message for easy return to program page

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#796]
# Story
After I add a new indicator to a program, I want an easy way to return to the program page to check out my new indicator and continue on to any other program-related work.

## Affects 
Add indicator page, upon clicking the "Save changes" button.

# Acceptance criteria
![image](https://user-images.githubusercontent.com/33670923/49318916-4a6e5900-f4af-11e8-8f48-3aa73ae4d900.png)

- [ ] 1. I no longer see the temporary success banner between the "Indicator setup" title and the name of the indicator.
- [ ] 2. Instead, I see a PNotify success message in the lower left corner (where my attention is, having just clicked "Save changes" that includes a link to the program page.
- [ ] 3. The notification is NOT temporary; it stays put. It can be manually dismissed in any of the following ways:
     - [ ] 3.1. Click the X, which closes the notification and keeps you on the page if you want to keep editing the indicator there.
     - [ ] 3.2. Click anywhere outside the notification area -- same deal, closes the notification, keeps you on the page.
     - [ ] 3.3. Click "View your new indicator on the program page." This closes the notification and takes you to the program page. 

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by KennyMonster** [comment]
@jennyhavah I think this should be relatively easy to implement.

For the modal version, we can try it both ways and see which way looks/feels better.

**Comment by jennyhavah** [comment]
Addressed in #884 as part of Mangosteen.
