### ISSUE TITLE
Indicator page: no title for programs without indicators

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#799]
This page is not actively linked but is useful to keep around as 

1. a list of all "my" indicators in one list
2. it doesnt run any aggregating queries so it is very fast

Jenny noticed the bug in the ticket title. I also noticed the indicators on this page don't link to the program page

**Comment by axoplasm** [comment]
Per @jennyhavah 
![image](https://user-images.githubusercontent.com/169060/48725024-c4652f00-ebdf-11e8-8faf-65aa3af2831b.png)

**Comment by axoplasm** [comment]
As built in 2decead:

![image](https://user-images.githubusercontent.com/169060/48725141-1a39d700-ebe0-11e8-9c45-258aa32f30d8.png)

**Comment by jennyhavah** [comment]
Updates validated. When a program has no indicators, I still see the program name along with the appropriate messaging.

**Comment by axoplasm** [comment]
@sanjuroj raised the points that 

1. this page might not be so useful now that the program and country pages are fast
2. superusers will have a gazillion indicators so this page will get v slow for them

If we keep this page post-Mangosteen we should add sorting, filtering, and/or pagination
