### ISSUE TITLE
Indicators: Make it easier to locate an indicator I've just configured

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#80]
**Affects:** What happens after saving changes in the indicator config modal.

**Usability issues**
1. After making changes to an indicator and closing its modal, it can be difficult to locate the indicator again if the program has a large number of indicators. This is especially true if I've inadvertently scrolled the Indicators page in the background during the configuration process. 
2. ~~Target-specific issue: I initiate the process of configuring indicator targets by clicking its name or the Edit button on the Indicators page. It doesn't matter whether or not the data for that indicator is exposed, and that is okay. The problem occurs after setting up new targets or editing existing targets; when I save changes and close the modal, I miss valuable system feedback when the data section happens to be closed for that indicator.~~

**ACCEPTANCE CRITERIA** 
1. When I open the indicator modal, the page is locked in the background, so that I can't accidentally scroll while configuring some of the longer forms in that modal. 
1.1. The background page should remain locked regardless of what tab I'm on within the modal.
2. ~~In cases where the indicator row is "closed" (i.e. data not showing): When I save changes in the Targets tab and close out of the modal, the indicator row pops open.
2.1. This is true when I've set up targets for the first time.
2.2. This is true when I make an edits to the Targets tab.~~

**Comment by mahmoodkhan** [comment]
It is quite a bit of work to expand the row to show data records ONLY IF something on the targets tab has changed. It will be a lot simpler to always show the data records if you clicked the save button on the indicator modal window.

**Comment by jennyhavah** [comment]
@mahmoodkhan Let's go ahead and fix the scrolling issue, but rethink our strategy for addressing the issue of what to do when the row is closed. I'm concerned that it will feel like unexpected (and possibly undesirable) behavior if we always open the data area, even if your change has nothing to do with data or targets.

**Comment by jennyhavah** [comment]
> When I open the indicator modal, the page is locked in the background, so that I can't accidentally scroll while configuring some of the longer forms in that modal.
1.1. The background page should remain locked regardless of what tab I'm on within the modal.

Validated.
