### ISSUE TITLE
Restore link to indicators page, as item under "browse" menu

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#800]
As noted in #799, it might be handy to have a link to the indicators page.

This page is not actively linked but is useful to keep around as 

1. a list of all "my" indicators in one list
2. it doesnt run any aggregating queries so it is very fast

This would partially reverse #663

**Comment by jennyhavah** [comment]
@axoplasm Just curious -- is that menu automatically sorted alphabetically, or was that manually organized -- which wouldn't work in all languages?

**Comment by jennyhavah** [comment]
The Indicators option appears in the Browse menu and loads the "master indicator list" as expected.
