### ISSUE TITLE
Hiding projects: Two more places to hide projects -- Browse documents and add doc form

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#803]
For countries that shouldn't have access to Projects, we need to hide them in a couple more places.

# Acceptance criteria

## Browse > Documents
- [x] I no longer see the Project column.
![image](https://user-images.githubusercontent.com/33670923/48729650-fa5ce000-ebec-11e8-91a9-e440727f7e8e.png)

## Add document form
- [x] I no longer see the Project menu
![image](https://user-images.githubusercontent.com/33670923/48729709-1a8c9f00-ebed-11e8-9c40-3e098c5e6d4f.png)

**Comment by hannalcamp** [comment]
Validated both components in Demo, both with the overall Documents menu and filtered to different programs.
