### ISSUE TITLE
Delete result, and delete indicator confirmation page redirects to wrong page

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#807]
When you are on the Program Page, and choose to delete a result, or delete an indicator from the relative dialog modal, you are redirected to a confirmation page. When you confirm the delete, you are then redirected to the Indicators list page (which is now deprecated) instead of the Program Page.

Expected behavior:

Redirect back to the program page you were viewing prior to the delete result/indicator link was clicked.

Ideally this would be superseded by #339 which would just use a confirmation box.

**Comment by jennyhavah** [comment]
@KennyMonster Just to make sure we're on the same page, I think we need to go ahead and make this fix for Mangosteen, and tackle 339 in a future release.

**Comment by mariebakke** [comment]
PASS - Indicator setup form: Deleting an indicator should take you back to the program page 
PASS - Collected data form: Deleting a result should take you back to the program page
