### ISSUE TITLE
(NO LONGER VALID) Record form: UI updates to page title, form fields, and links

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#809]
## Before
![image](https://user-images.githubusercontent.com/33670923/49118884-fec37180-f25a-11e8-842d-9c9e9f92f3b6.png)

## After
![image](https://user-images.githubusercontent.com/33670923/49119105-d7b96f80-f25b-11e8-89f3-c019a0e5d6f9.png)

# Acceptance Criteria

## Breadcrumbs
- [x] Change "Documents" to "Records"
- [x] Change "Document" to "Record"

## Page title
- [x] Change from "Document" to "Record"

## Form field labels
- [x] 1. Name of Document* --> Record name*
- [x] 2. Link to document, document repository, or document URL* --> Link to file or folder*

## Changes covered by other tickets
- #818 Replace project and program menus with newer select widget
- #816 View button
- #821 TolaData records link
- #808 Changes to Gdrive button

## Reword success message for consistency
- [x] Upon submit, today you see "Success, Documentation Created!". Instead, let's say, "Success! Record saved."
![image](https://user-images.githubusercontent.com/33670923/48805900-88a89300-eccd-11e8-9f6f-2b70d4de9f68.png)

## Validation regression check
- [x] Validation of required fields is preserved. If you leave one empty and try to submit the form, you get a "Please complete this field" message.

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [x] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by KennyMonster** [comment]
Abandoning `record_form` branch and closing.
