### ISSUE TITLE
Result form: Easily validate / access file or folder path

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#816]
# Stories
1. When entering a file path to evidence, I want to quickly test the path to make sure it works and opens the expected file or folder.
2. When I'm reviewing a result, I want to access the file or folder that was entered as evidence in a single click instead of five -- i.e. clicking into the field, copying, opening a new tab or window, pasting, and hitting return.

# Acceptance criteria

![image](https://user-images.githubusercontent.com/33670923/50995178-2f8dfc00-14d3-11e9-86c9-907fc1cf1cb9.png)

- [x] 1. Next to the _Link to file or folder*_ field is a button labeled "View".
- [x] 2. The button is disabled when the field is empty.
- [x] 3. The button becomes active when the field is filled in.
- [x] 4. Clicking the button opens the file path in a new tab.
- [x] 5. Security issues (XSS vulnerabilities) are considered and addressed.

## Testing:
- [x] Run through all fields that accept input, ensure required fields react to improper/missing text & info appropriately
- [x] Ensure built to spec, acceptance criteria is met
- [x] Add improper file links, attempt to view
- [x] Access files/folders entered as evidence multiple times, ensures heavy use / multiple uses. 
- [x] Tooltip's provide relevant and proper information related to field 

## Estimated Test Time (Acceptance): 
1 - 2 hours

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [x] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by RickieT** [comment]
**Deployment Verification**
- [x] Confirmed “Ready for Deploy” status
* Verified: 
## Acceptance criteria

* [x]  1. Next to the _Link to file or folder*_ field is a button labeled "View".
* [x]  2. The button is disabled when the field is empty.
* [x]  3. The button becomes active when the field is filled in.
* [x]  4. Clicking the button opens the file path in a new tab.
* [x]  5. Security issues (XSS vulnerabilities) are considered and addressed.

## Testing:
* [x]  Run through all fields that accept input, ensure required fields react to improper/missing text & info appropriately
* [x]  Ensure built to spec, acceptance criteria is met
* [x]  Add improper file links, attempt to view
* [x]  Access files/folders entered as evidence multiple times, ensures heavy use / multiple uses.
* [x]  Tooltip's provide relevant and proper information related to field
