### ISSUE TITLE
(NO LONGER NEEDED) Record form: Validate record name and file path to prevent duplication of records

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#822]
## Stories
1. When I inadvertently enter a file path already used by a record in TolaData, I am prevented from duplicating the record object. 
2. When I inadvertently enter a record name used by an existing record -- _but it's legitimately a different file or folder requiring that a new record object be created -- I am prompted to use a different name, rather than creating records that are difficult to differentiate when browsing.

## Preconditions
1. The user has clicked the "Save changes" button.
2. The system has already validated that all required fields are completed with valid values.

# Acceptance criteria

The system checks the **Record name** and **Link to file or folder** to see if a record object has already been created with identical values in either of those two fields.

## If there is no duplication
Then the form submission is completed and the system creates a new record object. I get the usual success message.

## If record name is duplicated
- [x] 1. Red error text appears immediately under the **Record name** input box. It says "A record already exists with this name. View the record."
- [x] 2. The phrase "View the record" opens up the **_record object_** (not the actual file or folder) in a new tab.

## If record name is duplicated
- [x] 1. Red error text appears immediately under the **Record name** input box. It says "A record already exists with this link. View the record."
- [x] 2. The phrase "View the record" opens up the **_record object_** (not the actual file or folder) in a new tab.

**Comment by KennyMonster** [comment]
@jennyhavah My memory is fuzzy, but I think at a meeting we said that these unique constraints for the name and file path were specific to a given program, correct?

**Comment by KennyMonster** [comment]
There are existing duplicate names and file paths per program in the DB. If we want to add a DB uniqueness constraint to guarantee no duplicates in the DB going forward, we would need to clean up the existing duplicates.

I've attached CSV exports of the existing duplicate names and file paths.

[Duplicates.zip](https://github.com/mercycorps/TolaActivity/files/2734437/Duplicates.zip)

**Comment by jennyhavah** [comment]
@KennyMonster As discussed, we need to revert this work. As soon as you've done that, please go ahead and close the ticket.

**Comment by KennyMonster** [comment]
Abandoning `record_form` branch and closing.
