### ISSUE TITLE
NO LONGER VALID: Top nav Browse menu and Program page sidebar: Change the term Documents to Records

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#823]
# Background
We are renaming "Documents" to "Records" throughout the application, because it is a more all-inclusive term. (Evidence may be in other file formats besides documents -- such as photos, spreadsheets, etc.)

# Acceptance criteria

## Top nav Browse menu

- [x] In the Browse menu of the top nav bar, we replace the term "Documents" with "Records"

![image](https://user-images.githubusercontent.com/33670923/48875955-a3a00380-edb0-11e8-8c66-6346f0036de6.png)

## Program page sidebar

On the program page sidebar, there are a few places where we need to replace the word "document" with "record"

- [x] 1. Change section header "Documents" to "Records"
- [x] 2. Change "View program documents" to "View program records"
- [x] 3. Change "Add document" to "Add record"

![image](https://user-images.githubusercontent.com/33670923/49114488-2e6b7d00-f24d-11e8-9859-ba885f32dfc5.png)

**Comment by axoplasm** [comment]
Also change `Documentation` to `Record` in the codebase

**Comment by axoplasm** [comment]
- [ ] See also #839

**Comment by KennyMonster** [comment]
This work was performed and can be tracked through #1039. Closing and unlinking.
