### ISSUE TITLE
Improve sort order of indicator list

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#826]
On the program page, the indicator list is sorted by indicator number, which is a charfield.  Improve the sort order so that:
1.  If every indicator number field is numeric, sort numerically
2. If every indicator number field is numbers separated by periods, sort numerically by period-separated section
3. Fall through to sort alphabetically.

**Comment by hannalcamp** [comment]
This fix seems to have solved most of the ordering issues I know of - though looking at one program (VISTA, under the US) I'm not sure how it's working. Is it the presence of letters in some of them that's throwing it off? @camgnostic 

![screen shot 2018-11-29 at 11 40 05 am](https://user-images.githubusercontent.com/38020496/49243861-a364c100-f3cb-11e8-8780-8907916e630c.png)

**Comment by camgnostic** [comment]
yes according to the logic in this ticket those are sorted correctly (alphabetical is last) - if we want to make number 2 into "if every number is numbers _or letters_ separated by periods" then we can, but that's gonna be more than a quick fix so I'd love to make sure that's the behavior we want.  As of right now this matches the ticket criteria.  Ping @jennyhavah  - criteria update?

**Comment by jennyhavah** [comment]
Ultimately we want to do away with manual numbering altogether, as part of our upcoming release-to-be-named. So I hesitate to put much effort into perfecting manually entered number-letter combos at this time.

@hannalcamp Would you be okay not addressing the number-letter combo issue in the short term?

**Comment by hannalcamp** [comment]
Yeah, I think it's good enough as is for now - it takes care of the problem program that caused me to log the issue in the first place.
