### ISSUE TITLE
Result form: Add explanatory messaging

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#827]
# Story
When I'm confused about some of the more abstract or technical required fields on the Results form, I can quickly access contextual help instead of combing through TolaWiki.

![image](https://user-images.githubusercontent.com/33670923/50995285-872c6780-14d3-11e9-92f9-c82fde1e7d95.png)

# Acceptance criteria

**Note:** These tooltips should follow the same design pattern we're using for tool tip on Program page graphs.

**Tool tip text**
- [x] 1. **Result date:** "This date determines where the result appears in indicator performance tracking tables. If data collection occurred within the target period, we recommend entering the last day you collected data. If data collection occurred after the target period ended, we recommend entering the last day of the _target period in which you want the result to appear._" 

(Please note the use of italics for emphasis.)

- [x] 2. **Measure against target:** 
     - [x] 2.1. If the indicator's target frequency is annual, semi-annual, tri-annual, quarterly, or monthly, then the tool tip says, "The target is automatically determined by the result date."
     - [x] 2.2.  If the target frequency is midline/endline or event, then the tool tip says, "You can measure this result against the Midline or Endline target."
     - [x] 2.3.  If the target frequency is Life of Program (LoP) only, then the tool tip says, "All results for this indicator will be measured against the Life of Program (LoP) target."

- [x] 3. **Record name:** "Give your record a short name that is easy to remember."

- [x] 4. **Link to file or folder:** "Provide a link to a file or folder in Google Drive or another shared network drive. Please be aware that TolaActivity does not store a copy of your record, _so you should not link to something on your personal computer, as no one else will be able to access it._"

(Please note the use of italics for emphasis.)

## Mockups
Please note that the most recent text updates in this ticket are not reflected in these mockups.

![image](https://user-images.githubusercontent.com/33670923/50995254-6f54e380-14d3-11e9-88f0-fb81e1b2dc09.png)

![image](https://user-images.githubusercontent.com/33670923/50995273-7a0f7880-14d3-11e9-82ca-aecf892850a3.png)

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [x] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@hannalcamp Would you mind reviewing the tool tip language for clarity of phrasing?

**Comment by hannalcamp** [comment]
Some suggestions, not definitive: 
1. "If data collection occurred after the target period ended, we recommend entering the last day of the _target period in which you want the result to appear_."
4. "Provide a link to a file or folder in Google Drive or another shared network drive. Please be aware that TolaActivity does not store a copy of your record, _so you should not link to something on your personal computer, as no one else will be able to access it_."

**Comment by jennyhavah** [comment]
Thank you @hannalcamp!

For whoever takes this ticket: I updated the text in the ticket to reflect Hanna's edits. I did not bother updating the tooltip mockup, so it doesn't reflect the most current wording. (I'm sure it's easier to copy/paste the text directly from the ticket anyhow.)

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Verified text matches Acceptance Criteria:
 1. Result date: "This date determines where the result appears in indicator performance tracking tables. If data collection occurred within the target period, we recommend entering the last day you collected data. If data collection occurred after the target period ended, we recommend entering the last day of the target period in which you want the result to appear."
(Please note the use of italics for emphasis.)

  2. Measure against target:

 2.1. If the indicator's target frequency is annual, semi-annual, tri-annual, quarterly, or monthly, then the tool tip says, "The target is automatically determined by the result date."
 2.2. If the target frequency is midline/endline or event, then the tool tip says, "You can measure this result against the Midline or Endline target."
 2.3. If the target frequency is Life of Program (LoP) only, then the tool tip says, "All results for this indicator will be measured against the Life of Program (LoP) target."
  3. Record name: "Give your record a short name that is easy to remember."

  4. Link to file or folder: "Provide a link to a file or folder in Google Drive or another shared network drive. Please be aware that TolaActivity does not store a copy of your record, so you should not link to something on your personal computer, as no one else will be able to access it."
