### ISSUE TITLE
Delete a result: Replace full page confirmation with Pnotify dialogue

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#830]
**Note:** This ticket is peeled off of #339 that describes deletion-related usability issues across the app. Whatever solution we implement should be easy to replicate elsewhere.

# Usability issue
When I click "Delete this result" on the Result form, I am taken to a full page confirmation. This is surprising and disorienting. I've "lost my place" and am not sure what will happen once I confirm.

# Acceptance criteria
- [x] 1. When I click _Delete this result_, I get a PNotify notification positioned in the lower left corner, like so:
![image](https://user-images.githubusercontent.com/33670923/50943109-eb9de700-143f-11e9-8ffe-0e57ce39f4ed.png)
     - [x] 1.1. The title of the notification is "Warning" with our standard warning icon to the left of it.
     - [x] 1.2. The warning message says: This action cannot be undone. Are you sure you want to delete this result?
     - [x] 1.3. There is a _Delete result_ button and a _Cancel_ button
- [x] 2. If I click _Cancel_, the notification closes and nothing else happens.
     - [x] 2.1. Similarly, if I click the X or anywhere outside the notification, it closes and nothing else happens.
- [x] 3. If I click _Delete result_, I am returned to the Program page. Ideally the page is exactly as I left it -- with any filters preserved -- minus the indicator row for the indicator I just deleted.

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [x] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by KennyMonster** [comment]
@jennyhavah  I ended up making the delete confirmation a modal (the background is translucent grey) and top/center positioned as opposed to lower left corner of first modal. I think this looks a lot better visually and prevents the user from carrying forward with a "are you sure you want to delete?" confirm box open in the corner.

The downside is there is a modal over a modal...

![screen shot 2019-01-24 at 4 14 37 pm](https://user-images.githubusercontent.com/1278224/51716792-2a609f00-1ff3-11e9-9e37-d8c448ba74c0.png)

**Comment by jennyhavah** [comment]
@KennyMonster My thinking with regards to positioning the notification in the lower left corner of the _Result form_ (not the lower left corner of the screen), is that it will appear immediately where the user has just clicked, where their eyes and attention are already focused. In the option you shared, you would end up scanning the screen to figure out what happened and what to do next.

Also, the full-on, grayed out background style modal feels a bit dramatic. I think that style works nicely for a larger, more complex modal where you'd otherwise be struggling to differentiate foreground from background. But for basic warnings and prompts, I'd like to establish a lower-key pattern. (I'm thinking ahead to our upcoming batch of warning/change logging notifications where we prompt for a rationale, etc.)

**Comment by KennyMonster** [comment]
@jennyhavah  Here it is with it in the lower left corner of the modal.

![screen shot 2019-01-28 at 10 03 44 am](https://user-images.githubusercontent.com/1278224/51856246-1616ed80-22e4-11e9-821e-d8beddc26888.png)

Does this work?

**Comment by jennyhavah** [comment]
Speaking of buttons, heads up to @axoplasm that I'd like to explore a text-only button style that could become a pattern for the numerous types of notifications we'll be introducing not only for deleting things, but also for Partner Access change logging. (See mockup in the original ticket.)

**Comment by KennyMonster** [comment]
With pnotify popover pushed to the corner

![screen shot 2019-01-28 at 11 53 32 am](https://user-images.githubusercontent.com/1278224/51862566-b9bbca00-22f3-11e9-98c2-5762f90eda1a.png)

**Comment by axoplasm** [comment]
We have a text-only button style, (called `btn-link`.) We use it now for the "Delete result" button above (trash can icon is optional)

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 3 34 31 pm](https://user-images.githubusercontent.com/23220180/52751604-de2ace00-2fa4-11e9-8126-94eea8f093f1.png)

**Comment by axoplasm** [comment]
Additional styling on this ticket is in #1187
