### ISSUE TITLE
Browse documents: Replace Program menu with newer select widget

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#834]
We eventually want to have just one select widget library instead of two or three, and remove the old one/s. (See #343) So as we work on various areas of the app, let's replace the older select widgets with the same widget we use on the IPTT form. 

There is currently one single-select menu on the Browse > Records page. 
![image](https://user-images.githubusercontent.com/33670923/49106903-40dbbb80-f239-11e8-9c8e-eeabcb69c5f1.png)

# Acceptance criteria
- [x] 1. Program menu widget is updated to the newer select widget.
- [x] 2. Type-ahead is enabled.
- [x] 3.  Multi-select is disabled.
- [x] 4. Ideally we have faux-placeholder-text that says "Filter by program". If that's not possible, we can use a separate label like we do above the Program page's indicator list.

**Testing:** 
- [x] All places where old widget exists, is replaced new widget, which criteria is listed above 
- [x] New function allows user to search programs by type ahead. 
- [x] No more than one selection allowable. (old function gone) 

**Risks:** 
None

**Estimated Test Time:** 
.30 min - 1 hr

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 11 56 40 am](https://user-images.githubusercontent.com/23220180/52739774-7bc2d500-2f86-11e9-801a-b9adf645964f.png)
