### ISSUE TITLE
Consider Font Awesome as an alternative to Glyphicon

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#84]
As I understand it, Bootstrap gives us access to a sub-set of Glyphicons that are available to use under our open source license.

However, the full set of Glyphicons is not available to us because the company that makes them has explicitly stated on their website, "You must not include icons in open-source projects, since this license is not compatible with most of the open-source licenses." (http://glyphicons.com/license/)

As we update our UI framework, I'd like us to consider the possibility of switching to Font Awesome: http://fontawesome.io/license/ -- fully open source and GPL friendly. In addition, the icon set appears to be about 3 times larger than Glyphicons. The library of icons is also easy to use with Sketch.

If we do make the switch, I'll create a ticket for release Winterhawk to implement the change -- which will include some sort of process for identifying icons in the system and selecting new ones.

**Comment by mahmoodkhan** [comment]
Especially since BootstrapV4 does not ship with the limited set of glyphicons anymore. So might as well move to Fontawesome.

**Comment by jennyhavah** [comment]
Sounds good! When the timing is right, it would be helpful if you could somehow generate a list of the icons we use so that I can quickly go through them and select replacements. (If possible, I'd like to avoid manually going through every page of the UI to look for icons -- inefficient and I'm likely to miss some.)
