### ISSUE TITLE
Update text from "results" plural to "result" singular in a few places

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#840]
In discussing some upcoming Huckleberry work, I discovered that there are a few places where we are term "results", plural, when we should be referring to "result", singular.

# Acceptance criteria

## Results table on the Program page and Browse > Indicators page
- [x] Under the results table, change "Add results" button to "Add result"
- [x] Instead of "No data collected", say: No results reported
![image](https://user-images.githubusercontent.com/33670923/49770222-540a7480-fc98-11e8-9649-8f42782f212d.png)
- [x] Change "Add results" button to "Add result".
![image](https://user-images.githubusercontent.com/33670923/49114703-b8b3e100-f24d-11e8-893c-9a773cf840cb.png)

## Result form
- [x] Change the form title from "Results" to "Result"
- [x] Change "Delete results" to "Delete this result"
![image](https://user-images.githubusercontent.com/33670923/49770212-4523c200-fc98-11e8-8434-dd3402c9abf8.png)

**Comment by camgnostic** [comment]
Closed with #1132

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 2 20 38 pm](https://user-images.githubusercontent.com/23220180/52748153-9ef77f80-2f9a-11e9-945a-bf7158e2c864.png)
