### ISSUE TITLE
Deletion of indicator redirects to old indicator list page

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#846]
When an indicator is deleted from the indicator setup modal, users are redirected to the old indicator list page (indicators/home/0/0/0/), rather than back to the program page they came from.

Deletion should either redirect back to the program page or shortcut the indicator deletion page and stay on the program page.

Codebase should be checked for any other references to the indicator page.

**Comment by KennyMonster** [comment]
Duplicate to #807
