### ISSUE TITLE
Translation error on homepage & program page

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#850]
### On my local machine only:

When I change my language to Spanish or French, then visit either the homepage or a program page, I get a TypeError:

```
Exception Type: TypeError at /program/442/0/0/
Exception Value: Plural value must be an integer, got str
```

Do any other devs see this?

**Comment by axoplasm** [comment]
looks like `scope_percents.nonreporting` returns `None` or `''`

![image](https://user-images.githubusercontent.com/169060/49179962-54098c80-f308-11e8-9c98-c8a9b10a3fa0.png)

**Comment by hannalcamp** [comment]
Validated by changing my language first to French and then Spanish, and visiting the Jordan, Iraq, and Tolaland countrypages as well as various program pages underneath them.
