### ISSUE TITLE
Additional string translations

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#856]
Need to translate these strings
- Your profile has been updated
- Thank you, You have been registered as a new user.
- Success, Bookmark Created!
- Success, Bookmark Updated!
- Success, Bookmark Deleted!
- Invalid Form
- Missing targets
- Please complete all required fields in the Performance tab

**Comment by jennyhavah** [comment]
@sanjuroj Bookmarks were killed off a long time ago -- maybe it's time to remove the code instead of translating it?

And since we are renaming Profile --> Settings in Mangosteen, can we change the message "Your profile has been updated" to "Your settings have been updated"

**Comment by sanjuroj** [comment]
Ah, forgot we killed Bookmarks.  All the strings have been sent to the translators now (I generated another .po file after filing this ticket), so we'll just need to change profile to settings when we get the file back.

**Comment by sanjuroj** [comment]
Additional translations will be handled as a larger batch of post-Mangosteen translations.
