### ISSUE TITLE
IPTT Excel download links errors

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#866]
When on a target vs actual report, hitting the Excel download button results in an error.  On demo server, select the Target vs Actual report and use TolaData Test with an annual target frequency to get the error.

<img width="1192" alt="screen shot 2018-11-29 at 12 33 53 pm" src="https://user-images.githubusercontent.com/6685499/49250283-4cfb8080-f3d3-11e8-95e1-4631b91306de.png">

**Comment by hannalcamp** [comment]
Validated on a bunch of programs and time period types for both TvA and Recent Progress.
