### ISSUE TITLE
Indicators > Modal dialog should close when Escape key pressed

### ISSUE THREAD

**Issue by kurtwall** [mercycorps/TolaActivity#87]
1. Using Firefox, open a specific program indicator using the Edit button or by clicking the indicator name in the program indicators dropdown.
2. Immediately press the Esc key to close the dialog.
3. The dialog doesn't close. 
4. Click the Close button in the upper right-hand corner of the dialog. 
5. Dialog closes and no data is saved.

The expected behavior is that pressing Esc to close the dialog would work just as the Close button does.

**Comment by kurtwall** [comment]
This is a UI wart that violates the principle of least surprise. It doesn't happen on every form and window, but I haven't paid attention until now. On some forms, pressing Esc works as expected. I'll try to identify where it's working and where it isn't and update this issue when I do.

**Comment by jennyhavah** [comment]
Believe it or not, I have never used the escape key to close a modal dialogue! I did a quick search, and it looks like this is an accessibility best practice. People with vision impairments using screen readers need a quick and predictable way to back out of modals without having to hunt for an icon that may or may not be a "close" button.

I know the Indicators config modal does not afford closing with the Esc. key.

Please do give us a list of any other ones that need updating.
