### ISSUE TITLE
Endless spinner when updating indicator of a multi-country program

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#875]
For a program that is assigned to multiple countries, when the indicator setup modal is used to try to update the indicator, the update spinner never stops spinning and the indicator never updates.

**Comment by hannalcamp** [comment]
Validated in Tolaland's "QA Program - Hanna". I assigned it to the United States and Guatemala in addition to Tolaland, and added a test indicator. Everything saved instantly and correctly.

**Comment by hannalcamp** [comment]
Made changes to existing indicators and experienced no problems. Also changed the countries back to only Tolaland and it all looked fine.
