### ISSUE TITLE
Update junk strings for mangosteen

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#879]
Update junk strings for JS and CSS for mangosteen so users don't have to do hard refreshes.

**Comment by camgnostic** [comment]
This needs review by Paul who's written the majority of our styling and js automation to ensure I haven't changed something that breaks process, but otherwise is ready to move to staging once that PR is approved.

**Comment by sanjuroj** [comment]
@axoplasm Can you QA this one?  I know you already had a look at it once.

**Comment by axoplasm** [comment]
Yep. Validated.
