### ISSUE TITLE
Pinned report list on program page causes error when year has non-ascii chars

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#880]
Certain pinned reports result in ascii errors when trying to load program page as a user with Spanish language selected.  I'm guessing this is a side-effect of having changed the way we're storing/displaying period names.

Steps to reproduce:
1.  Change language to Spanish (you can do this later if you want).
1.  From the iptt_quickstart page, select a "Recent progress for all indicators" report for any program (TolaData Test will work).
2.  Once in the report, change the TIME PERIODS dropdown to Years. 
3.  Pin the report and select "Visit the program page now" 
4.  The program page will load fine if you've selected English as your language, but it will give you a DjangoUnicodeDecodeError if you have Spanish selected.

**Comment by esinn** [comment]
Program page loaded in Spanish (altho the actual text hasn't been translated yet)
