### ISSUE TITLE
Add indicator success message: include a link to the program page (quick fix)

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#884]
**Note:** A longer term preferred solution is explored in #796. This is a quick fix for the short term...

Right now, after creating an indicator, you just sit there. Why not give you an easy way to the program page?

# Affects
"Form data saved" message that you see after adding an indicator AND completing all required fields. (This does NOT apply to the "Basic indicator created" message you see immediately after adding, prior to completion of targets, etc.)

![image](https://user-images.githubusercontent.com/33670923/49319258-c321e500-f4b0-11e8-8986-e76f2cd357c1.png)

# Acceptance criteria
- [x] Replace the text in the "Success, form data saved" with the following: Success! View your indicator on the program page.
- [x] "View your indicator on the program page." is a link to the program page where the new indicator appears.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [x] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
A distinction I neglected to call out:

When I click the "Create target" button, I should see the original success message, not the new one with the link to the program page.

(At that point, I have not yet _saved_ my targets, so we should not be encouraging them to leave the page.)

**Comment by KennyMonster** [comment]
The Create Target button should now show the original success message.

**Comment by jennyhavah** [comment]
## Full page version
When I add a new indicator, I see the "form data saved" message after entering the name and after clicking "Create targets". 

I see the message with the link to the program page after completing all required fields.

## Pop-up version
If I then edit the saved indicator in the pop-up version and click "Save changes", I see the "form data saved" message.

This is behaving as expected.
