### ISSUE TITLE
Browse Google Drive function: I can select a folder, not just a file

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#887]
**Affects:**
1. Result form 
2. Record form

# Acceptance criteria
When I use the "Browse Google Drive" to obtain a file path for my evidence/record, I have the ability to select a folder, not just a file.

Note from Cameron: This is a boolean in the Google Drive picker API

**Comment by KennyMonster** [comment]
Testing locally, I was able to select folders using the gdrive file picker without the need for any changes to the code.

**Comment by sanjuroj** [comment]
That's a bit odd.  It should work on the server then.

**Comment by KennyMonster** [comment]
I just tested it on production and it seems to work there as well.

![screen shot 2019-01-28 at 1 53 50 pm](https://user-images.githubusercontent.com/1278224/51869003-3e164900-2304-11e9-95e1-a36974619e71.png)

**Comment by RickieT** [comment]
Closing - Won't Fix
