### ISSUE TITLE
Browse documents: Increase number of documents displayed per page

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#888]
**Story**
When browsing documents, I want to see more than 10 documents per page so that I'm not unnecessarily clicking through hundreds of screens.

**Acceptance criteria**
1. I see 50 documents per page instead of 10
2. The page feels quick to load. 

**Testing:**
- [x] Pagination functions properly, on preset documents per page ( 10 - 25 - 50 ) (Do lots of paginating. Alot of it. Shrink and contrasts window size as well. )
- [x] Any filters applied work as UI suggests
- [x] Documents are listed in a manner that makes sense

**Risks:**
N/a

**Estimated Test Time (Acceptance):**  
.45 - 1 hour

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
* Counted manually each page of results possible, and is accurately being displayed
* Pages load in a reasonable amount of time
