### ISSUE TITLE
Browse documents: Filter by indicator

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#892]
# Story
I can easily find all documents used to track the performance of a particular indicator.

# Acceptance criteria
- [x] 1. Next to the _Filter by program_ menu is a _Filter by indicator_ menu
     - [x] 1.1. The default text is "Filter by indicator".
- [x] 2. The _Filter by indicator_ menu is inactive when there is no program selected
- [x] 3. If a program is selected, the _Filter by indicator_ menu is active and only shows indicators associated with the selected program.
- [x] 4. I can type an indicator number or portions of the indicator name and get type-ahead results.
- [x] 5. When I select an indicator from the menu, I see all documents associated with the indicator.
- [x] 6. If I filter on an indicator and then change programs, the following happens:
     - [x] 6.1. The list of documents reloads to show all documents associated with the program.
     - [x] 6.2. The _Filter by indicator_ menu clears.
     - [x] 6.3. When I reopen the _Filter by indicator_ menu, it shows indicators associated with the program I just switched to.

![image](https://user-images.githubusercontent.com/33670923/50926959-33eee200-140b-11e9-8f27-76cdd7ae0bce.png)

**Testing:**
- [ ] IF results provide enough to paginate, ensure Pagination functions properly.
- [ ] Type-ahead function provides results as text is input into search field
- [ ] Results properly reflect information being searched
- [ ] Multiple searches need to be completed to confirm functional implementation based on acceptance criteria. 

**Estimated Test Time w/ Acceptance:**  
2  hours

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [x] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@KennyMonster I replaced the term "Record" with "Document" throughout this ticket. So we just need to ensure that the correct term is used for any work you did on it.

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 11 58 51 am](https://user-images.githubusercontent.com/23220180/52739910-be84ad00-2f86-11e9-81a5-38e65cbc957a.png)
