### ISSUE TITLE
Translation bug: Indicator setup form > Performance tab

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#896]
**Affects:** Performance tab of the indicator setup form -- both full page and modal versions.

With the following form fields, the _label_ is translated. We want to translate the _options_ as well.
- [ ] Level
- [ ] Indicator type

**Comment by KennyMonster** [comment]
These are database values. As such, they can't really be translated unless we remove them as customizable options in the admin.

See Django models:

`Level`
`IndicatorType`

**Comment by jennyhavah** [comment]
I'm gonna add this to Satsuma for further consideration... Once we have preset indicator/result levels, it might be a great time to reconsider the customizability... and therefore translate-ability.

**Comment by jennyhavah** [comment]
The translation of levels will be addressed as part of Satsuma; our Result Framework templates will not be editable database values, and therefore can be translated.

"Type" is not a high priority field to improve, so closing this ticket.
