### ISSUE TITLE
Translation bug: IPTT filter panel

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#897]
**Affects:** Filter panel for both versions of the IPTT form -- Target vs Actuals and Recent Progress

We'd like to translate the _options_ for the following filter menus:
- [ ] Level
- [ ] Type

**Comment by KennyMonster** [comment]
These are database values. As such, they can't really be translated unless we remove them as customizable options in the admin.

See Django models:

`Level`
`IndicatorType`

Related to: #896

**Comment by jennyhavah** [comment]
The translation of levels will be addressed as part of Satsuma; our Result Framework templates will not be editable database values, and therefore can be translated.

"Type" is not a high priority field to improve, so closing this ticket.
