### ISSUE TITLE
Period names missing in results table and target table

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#898]
# Indicator list
![image](https://user-images.githubusercontent.com/33670923/49491401-d7dfdf00-f808-11e8-88fa-23bc79627862.png)

Note: We need to make sure the fix works on both the Program page and Browse > Indicators.

# Indicator setup > Targets tab

This is from an _existing_ indicator.
![image](https://user-images.githubusercontent.com/33670923/49491367-b67ef300-f808-11e8-8b32-982e34bf2096.png)

I also tried setting up _new_ monthly targets. I do see the month names in the Targets tab. But it still says "NONE" on the indicator list.

**Comment by jennyhavah** [comment]
I'm not seeing month names in the indicator list. I'm seeing Period 1, Period 2, etc.

![image](https://user-images.githubusercontent.com/33670923/49557529-d1ab3a80-f8bc-11e8-8622-f872a9a5cd92.png)

This is also true in the target setup table:

![image](https://user-images.githubusercontent.com/33670923/49557566-edaedc00-f8bc-11e8-9adc-318c4d24b220.png)

**Comment by jennyhavah** [comment]
Midline/Endline period names appear to be missing as well.

![image](https://user-images.githubusercontent.com/33670923/49560939-75024c80-f8c9-11e8-87c5-fbcf7d1866c7.png)

@sanjuroj @axoplasm

**Comment by axoplasm** [comment]
This sounds like a deeper ish than I thought. I reverted yesterday's "fix" as a hotfix on Mangosteen

**Comment by jennyhavah** [comment]
@sanjuroj See above... I'm a bit muddled about what's a QA script issue causing the period name problem, and what's an issue with the change Cameron made to translate period names... That we may or may not still need to address. So out of caution, tagging you here.

**Comment by jennyhavah** [comment]
I've tried my darndest to break this, and haven't had any luck!

I've checked the following places for missing/bad period names across multiple target frequencies.
- Indicator list on the program page
- Indicator list on the Browse > indicators page
- Result form
- Target setup form
- IPTT
