### ISSUE TITLE
Indicator: "Save and add another" button is unresponsive

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#9]
**Affects:** Indicator form, at the bottom of all tabs.
**Problem:** "Save and Add Another" button is unresponsive. The intention and utility of this button are unclear.
**Request:** Please investigate the intended behavior and let us know what you find. If the intention can't be deciphered, we should remove the button. 

![unresponsivesaveaddanotherbutton](https://user-images.githubusercontent.com/33670923/33576758-c77bb98c-d8f5-11e7-888d-c873c4d11829.png)

**Comment by mahmoodkhan** [comment]
The idea behind that button is after you saved an indicator and you wanted to create a new indicator then that button would save the current indicator and then redirect you to the new indicator screen. But it is currently only working as a "save" button.

**Comment by jennyhavah** [comment]
Ah okay. In that case, let's restore the button to its intended behavior: To save all changes to the current indicator, then redirect to the new indicator screen.

**Comment by mahmoodkhan** [comment]
@jennyhavah This was a feature when the Indicator creation process was simpler, i.e, when you clicked this button it would save it and then present you with a blank form. But now the new Indicator process would takes you to a different screen from where you select whether to create an Indicator from DIG or not and have to specify a country and a program. I can make it so that after saving the current indicator it would redirect you to that page but not sure this is helpful.

**Comment by jennyhavah** [comment]
@mahmoodkhan Thank you for this background information. Given that the _Save & Add Another_ button was associated with a much simpler process, I share your concern that re-introducing the feature is likely to be more confusing than helpful. It also clutters up that area of the dialogue. Given that it is so much larger than the _Save_ button, it would also be easy for a user to accidentally click it and not understand what happened.

Given all of that, I recommend removing the _Save & Add Another_ button from the dialogue. It's unlikely to be missed, since it hasn't worked for quite some time.

**Comment by jennyhavah** [comment]
@mahmoodkhan Okay to close this?

**Comment by mahmoodkhan** [comment]
@jennyhavah Yes. I am associating it with release v.1.9.3 and closing it.
