### ISSUE TITLE
Country page: Switching to Timor-Leste returns "could not convert string to float" error

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#901]
Reported by Carly Olenick. I was able to reproduce on the QA server but not on demo.

On QA, try switching to Timor Leste -- either using the search box in the top nav or the country switcher above the map.

We get this:

![image](https://user-images.githubusercontent.com/33670923/49527684-4bb0d480-f867-11e8-9fd5-568a60805159.png)

It gets worse: Even if I remove Timor Leste from my accessible countries and reset my cache, the system is still trying to "remember" TL when I go to the QA home page. So this doesn't seem to be a recoverable error from a user perspective.

_I was finally able to recover by copying the URL string with the Afghanistan country code from Demo, changing the demo part of the URL to qa. That reset my default country to Afghanistan._

**Comment by camgnostic** [comment]
See GH #912

**Comment by jennyhavah** [comment]
Selecting Timor-Leste no longer results in an error page.

@camgnostic is there anything else I should try to make sure this is fixed? Any other affected countries?

**Comment by camgnostic** [comment]
Nope!  If this country loads, the bug is fixed. Sanjuro and I looked through the database for any missed lop_targets, but couldn't find any. I think that's all there is to test this one
