### ISSUE TITLE
Country map: Add visual legend explaining site pin colors

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#902]
Right now, it's impossible to tell what the two pin colors mean unless you happen to figure it out by experimenting with the check boxes in the layers menu:

![image](https://user-images.githubusercontent.com/33670923/49529352-adbf0900-f86a-11e8-8192-1f6e8eb039bf.png)

# Acceptance criteria
- [x] The legend appears just below the map, right-aligned.
- [x] The first legend item is "Sites with results" preceded by a blue square to match the blue pins.
- [x] The second legend item is "Sites without results" preceded by an orange square to match the orange pins.

![image](https://user-images.githubusercontent.com/33670923/49615347-25bc2a80-f962-11e8-8aa3-5e3a0581d38e.png)

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [x] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by RickieT** [comment]
**QA Verified:**
* Legend shows now, also, the colors have been (outside ticket) been decided on blue/gray, confirmed with @jennyhavah 
![image](https://user-images.githubusercontent.com/23220180/53273928-4dda4080-36aa-11e9-9f8f-f17f0be91b1f.png)
