### ISSUE TITLE
Problems with dates in reporting period and results modals

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#903]
The reporting period modal is no longer showing the reporting period end date, even when there is one in the database.  

Summary of date issues to fix
- [x] End date should appear in the Reporting Period Modal
- [x] Reset button in reporting period modal should not reset the start date if it's locked.
- [x] Date should appear properly in collected data modal (see comment below)

<img width="928" alt="screen shot 2018-12-05 at 9 56 24 am" src="https://user-images.githubusercontent.com/6685499/49533517-0e9f0f00-f874-11e8-89f7-b388077079d7.png">

**Comment by sanjuroj** [comment]
Might also be related to a couple of problems on the Collected Data modal.  On the attached image, notice the end date of NaN-Nan-NaN or blank in the two error messages.

![image 2](https://user-images.githubusercontent.com/6685499/49542780-4ebdbc00-f88b-11e8-8568-3750b9476b6b.png)

**Comment by hannalcamp** [comment]
Date issue 3 is not fixed for monthly periods - in all 3 languages you get an error in setting a December 2018 date to a result.
![screen shot 2018-12-06 at 2 59 12 pm](https://user-images.githubusercontent.com/38020496/49614544-e2fd5100-f967-11e8-9180-2e5a41396fce.png)
![screen shot 2018-12-06 at 3 00 16 pm](https://user-images.githubusercontent.com/38020496/49614546-e2fd5100-f967-11e8-9c3a-681b1790be69.png)
![screen shot 2018-12-06 at 3 00 50 pm](https://user-images.githubusercontent.com/38020496/49614547-e395e780-f967-11e8-937a-38537fd4c519.png)

**Comment by hannalcamp** [comment]
Everything looks validated!
