### ISSUE TITLE
Change "connot" to "cannot" in pinned report warning

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#906]
Change "connot" to "cannot" in pinned report warning

**Comment by axoplasm** [comment]
in a hotfix

**Comment by jennyhavah** [comment]
@axoplasm Not sure how to test this, how to induce this warning to happen. Is it better verified in the code?

**Comment by jennyhavah** [comment]
Validated.

![image](https://user-images.githubusercontent.com/33670923/49613355-42556400-f95c-11e8-8b48-e63ff9a26f37.png)
