### ISSUE TITLE
Country level M&E metrics: Add the word "of" in three places

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#908]
Reported by Leslie.

![image](https://user-images.githubusercontent.com/33670923/49542215-ce4a8b80-f889-11e8-9677-b081410e0d68.png)

To be grammatically correct, we need to add the word "of", like so:

45%
of programs

25%
of indicators

38%
of results

**Comment by axoplasm** [comment]
Addressed this as a hotfix.

**Comment by jennyhavah** [comment]
Validated. Here's what I see.

![image](https://user-images.githubusercontent.com/33670923/49557478-9e68ab80-f8bc-11e8-8d84-56ac34a82e94.png)
