### ISSUE TITLE
Search box in menu bar is too small on indicator create and update pages

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#918]
On the indicator_create and indicator_update pages, the search box appears shortened when compared to the home page.

On the homepage:
<img width="822" alt="screen shot 2018-12-06 at 10 24 14 am" src="https://user-images.githubusercontent.com/6685499/49603948-7ec79680-f941-11e8-93a7-cdf342772175.png">

On the indicator_create and indicator_update pages:
<img width="821" alt="screen shot 2018-12-06 at 10 23 14 am" src="https://user-images.githubusercontent.com/6685499/49603956-825b1d80-f941-11e8-8d42-d699cab87fc8.png">

**Comment by axoplasm** [comment]
Some templates import the old `select2.min.css` file. CSS for select2 is now imported directly into the master stylesheet, which is loaded in `base.html`. I removed references to select2.min.css from the `indicators` and `workflow` apps.

**Comment by sanjuroj** [comment]
QA note:  The update for this ticket has changed the way we import the select2 library.  In order to ensure that nothing unexpected has happened, the list of pages that need to be tested include the ones below.  Dropdown menus on these pages should be work as expected.
- collected data form
- indicator create
- indicator update
- project complete form
- project agreement form
- stakeholder form

**Comment by hannalcamp** [comment]
Validated. No issues seen in using any of these pages.
