### ISSUE TITLE
Consistent treatment of decimals in all forms and reports

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#92]
This ticket is inspired by feedback from Georgia, in relation to our Indicator Disaggregation Report.

> Decimals are displayed in the male/female age brackets on SADD. this should be removed as humans only occur in whole forms.

First of all, HA! 

Second of all, let's address this systematically:

Recommendation from Mahmood: Look at the models/database to see what fields are of type "Decimal" and then we can trace them to where they're used. Let's create a list for testing purposes.

ACCEPTANCE CRITERIA
For any field of type decimal, set the following rules, consistent with closed ticket #72:
1. If the user manually enters digits, the system displays them out to two decimal places.
2. If the user enters more than two decimals (.785) the system provides the same error message we're currently using -- number isn't valid, two closest options are .xxxxx +1 or .xxxxx - 1.
3. If the user does not manually enter any decimals, the system does not add a .00.

**Comment by jennyhavah** [comment]
@mahmoodkhan Did you fix it in multiple places or just the SADD report? How would you like me to test?

**Comment by mahmoodkhan** [comment]
@jennyhavah I fixed it in as many places I could find decimal fields in the Indicator module.
