### ISSUE TITLE
Occasionally LOP indicators report that they are on track despite being an incomplete program

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#920]

**Comment by camgnostic** [comment]
![image](https://user-images.githubusercontent.com/7941355/49611820-a295d700-f957-11e8-809f-669ec9b1bdf9.png)

the LOP indicator in this screenshot was labeled as "non-reporting" and also "on track" which caused it to be occasionally displayed for "on track".  I have fixed the conflicting outputs and now these indicators are hidden when "on track" is selected.

**Comment by camgnostic** [comment]
To test - open program QA Program - PaQ  and click "on track" and verify the number of indicators shown matches the number of indicators labeled at the top of the table

**Comment by jennyhavah** [comment]
When I click "0% are on track", it returns zero indicators as expected. It correctly says, "0 indicators are on track" above the indicator list.

![image](https://user-images.githubusercontent.com/33670923/49621595-067dc700-f97b-11e8-8595-fc9211955d37.png)

I found a second program example to try -- Humanitarian Assistance for Protracted IDPs and Returnees in Western Afghanistan (OFDA-WASH) -- and got the same result.

Validated.
