### ISSUE TITLE
Indicator setup form: Summary tab > Enlarge text input for indicator names

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#926]
Usability feedback from Thomas Scialfa: It's common for indicator names to be long. On the Indicator setup form, Summary tab, the text input box for the indicator name often doesn't let you see the whole name, like this:

![image](https://user-images.githubusercontent.com/33670923/49621288-72f7c680-f979-11e8-9c7b-26d727f7cd56.png)

## Request 
Make it a two- or three-line text input field. Here's a typical long name to test with: 

AFG - 2.2.1 - # of AUPs who have had at least one internship or apprenticeship in Afghanistan or Pakistan within six months of training graduation

**Comment by axoplasm** [comment]
I'm picking up this ticket now. There are … issues … with the indicator add/edit page. it might be worth a bigger effort to clean up the whole page

**Comment by jennyhavah** [comment]
I'm all for it! If the time feels right, I wonder if we could consolidate the two versions -- full page and modal -- into one. With React in place on the program page, dare we attempt an in-line experience??? Might be too soon, but worth discussing.

**Comment by axoplasm** [comment]
future plans aside, here’s the narrow fix for this issue.

#### On standalone page:
![image](https://user-images.githubusercontent.com/169060/49956437-066d5200-feba-11e8-99da-880e043d4891.png)

#### In modal:
![image](https://user-images.githubusercontent.com/169060/49956478-1d13a900-feba-11e8-9f26-217f164d2682.png)

**Comment by jennyhavah** [comment]
Validated that the text box is bigger in both versions of the form.
