### ISSUE TITLE
Error producing "recent progress" IPTT for all indicators on a new program

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#930]
Steps to produce:

1. Create a new program
2. Assign it some new indicators
3. Go to IPTT quickstart & create a "Recent progress for all indicators” IPTT (right side) for that program
4. __ERROR!__

Raw Traceback:
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/indicators/iptt_report/603/timeperiods/?timeperiods=7&timeframe=2&numrecentperiods=2

Django Version: 1.11.2
Python Version: 2.7.15
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.admin',
 'admin_report',
 'django.contrib.admindocs',
 'social_django',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_tables2',
 'crispy_forms',
 'django_extensions',
 'mathfilters',
 'import_export',
 'django_wysiwyg',
 'ckeditor',
 'ckeditor_uploader',
 'simplejson',
 'simple_history',
 'widget_tweaks',
 'workflow',
 'formlibrary',
 'tola',
 'feed',
 'indicators',
 'customdashboard',
 'tables',
 'reports')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'tola.middleware.UserLanguageMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.RemoteUserMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'tola.middleware.TimingMiddleware')



Traceback:

File "/Users/paul/Repos/TolaActivity/venv/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/Users/paul/Repos/TolaActivity/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/Users/paul/Repos/TolaActivity/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/paul/Repos/TolaActivity/venv/lib/python2.7/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/Users/paul/Repos/TolaActivity/venv/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/Users/paul/Repos/TolaActivity/indicators/views/views_reports.py" in get
  1020.         context = self.get_context_data(**kwargs)

File "/Users/paul/Repos/TolaActivity/indicators/views/views_reports.py" in get_context_data
  656.             report_end_date, all_date_ranges, periods_date_ranges = self._generate_targetperiods(period)

File "/Users/paul/Repos/TolaActivity/indicators/views/views_reports.py" in _generate_targetperiods
  377.         report_end_date = filtered_date_ranges[-1]['end']

Exception Type: IndexError at /indicators/iptt_report/603/timeperiods/
Exception Value: list index out of range

```

**Comment by axoplasm** [comment]
This may be an extreme edge. I created this program through the Django admin so it might be lacking some end dates that normally arrive via GAIT, or other data integrity ish.

**Comment by axoplasm** [comment]
Local vars:

![image](https://user-images.githubusercontent.com/169060/49667455-f3690680-fa0f-11e8-9460-9119a5b82e89.png)

![image](https://user-images.githubusercontent.com/169060/49667468-ffed5f00-fa0f-11e8-9841-75dd7b690e6c.png)


![image](https://user-images.githubusercontent.com/169060/49667493-13002f00-fa10-11e8-9f05-4a01525dc2d2.png)



![image](https://user-images.githubusercontent.com/169060/49667502-20b5b480-fa10-11e8-9b58-84f1c47499f1.png)

**Comment by KennyMonster** [comment]
When creating the new program:

reporting period 2019-01-01 to 2019-12-31

1 indicator in each period (annual, quarterly etc)

It seems to be important the reporting period has a start date in the future from the current date.

**Comment by jennyhavah** [comment]
@kenj What if we set a rule on the IPTT landing page (https://tola-activity-qa.mercycorps.org/indicators/iptt_quickstart/) that if the program start date is in the future, the program does not show up in the program menu for either type of report? If the program hasn't started yet, there's no valid reason to run an IPTT report on it, that I can think of.

**Comment by jennyhavah** [comment]
See #935 and #939 for preventing people from running an IPTT with a program whose start date is in the future.

@KennyMonster @camgnostic is there anything you'd recommend doing to address the underlying issue at this point? Or is it enough to prevent people going there?

**Comment by KennyMonster** [comment]
> is there anything you'd recommend doing to address the underlying issue at this point? Or is it enough to prevent people going there?

If we wanted to be thourough, having the IPTT view redirect the user to the program page instead of trying to run might be worthwhile. That way, even if a user has a direct URL to an IPTT report (possibly generated when the start/end date was not in the future), it would not throw a "Michael Jordan" due to invalid base assumptions in the IPTT report code.

**Comment by jennyhavah** [comment]
@KennyMonster I like that idea! Should that be a new ticket or can we fold it into this one?

**Comment by KennyMonster** [comment]
@jennyhavah I think folding it into this one would be easiest. I can knock it out today along with some other work I did to prevent the crash from happening.

**Comment by jennyhavah** [comment]
Oh fudge... We still have links to the Recent progress report here on the home page
![image](https://user-images.githubusercontent.com/33670923/49764939-befe8000-fc85-11e8-8e81-eb5bd2d474c7.png)

And it takes me to this error page instead of the program page:
![image](https://user-images.githubusercontent.com/33670923/49764975-d50c4080-fc85-11e8-88dd-4a6aa221470c.png)

**Comment by jennyhavah** [comment]
I no longer see a link to the Recent progress IPTT for future programs:
![image](https://user-images.githubusercontent.com/33670923/49771855-f67a2600-fc9f-11e8-8a6d-302026136e49.png)

If I try to get to it via pasting the program ID into a URL, I am taken to the program page.

Validated.
