### ISSUE TITLE
Indicator Level error handling prevents completion of target creation when editing indicator in IPTT

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#931]
Originally noted by @camgnostic:

> looks like I may have a breaking bug - editing an indicator from the IPTT page appears to have some validation issues related to the indicator level (keeps telling me to fill out the field despite already having filled out the field) - would love if someone on a cleaner branch than mine can double-check me here

I can replicate this issue on my local with the latest mangosteen (c282c32). Steps to reproduce:

1. Select any program and time period in IPTT quickstart
2. In the IPTT, select an indicator with targets & open its edit popup
3. Check that __Level__ on the __Performance__ tab has a value (e.g. Goal)
4. Remove all Targets on the __Targets__ tab
5. Select a new Target frequency and click Create Targets
6. __ERROR__ on Performance tab prevents form from saving!
7. I did however correctly remove my targets! (see screenshot below)

Here’s a hint:

I can’t reproduce this bug when editing an indicator in the popup on the Program page (so I think this might be as simple as copypasting some JS between templates)

![image](https://user-images.githubusercontent.com/169060/49667854-3081c880-fa11-11e8-97d5-5b5c5a7bbc93.png)

**Comment by axoplasm** [comment]
@KennyMonster  — This may be related to #885

**Comment by camgnostic** [comment]
That's all I changed to pass this, so that's all I can think of for testing, I also tried to find another way in which editing was broken but couldn't.  I also tested target creation, but that's it.
