### ISSUE TITLE
IPTT: LoP and M/E start/end fields should only show the date

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#936]
Originally reported by @jennyhavah:

For a LoP only report and Midline/Endline report, the Start and End menus are supposed to show the program start and end dates. e.g. https://tola-activity.mercycorps.org/indicators/iptt_report/515/targetperiods/?targetperiods=1&timeframe=1

![image](https://user-images.githubusercontent.com/169060/49689387-4f499300-fad5-11e8-9584-031dd6194dc3.png)

Instead, it looks like this:
![image](https://user-images.githubusercontent.com/169060/49689398-786a2380-fad5-11e8-9a95-9662927a1e15.png)

**Comment by jennyhavah** [comment]
Looking good -- I see the start and end dates, as expected, for LoP-only and Midline/endline filters.
