### ISSUE TITLE
IPTT: LoP-only columns show “None” instead of data

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#937]
originally reported by @jennyhavah:

> the Target, Actual and % Met columns all say "None" instead of displaying the available data. I think this is the first time I've  seen "None" in those columns.

![image](https://user-images.githubusercontent.com/169060/49689423-deef4180-fad5-11e8-82d5-776aabeb1e84.png)

This is not an issue for IPTT reports for other periods:

![image](https://user-images.githubusercontent.com/169060/49689448-4ad1aa00-fad6-11e8-9ab1-a4c1d0742a19.png)

**Comment by camgnostic** [comment]
For reference - this is an extra generated targetperiod that should be removed before display (as the LOP time period is already displayed in the LOP section of the report)

**Comment by jennyhavah** [comment]
I ran a number of Lop-Only Target vs Actual IPTTs on various programs, and no longer see the "extra" Life of Program section.

Is this all that needed to be validated, @camgnostic ?

**Comment by camgnostic** [comment]
yep - I ran through all the other frequencies to ensure nothing got moved on them as a result of fixing the extra columns on the LOP frequency, but that was just to check for regression.  For this ticket if Lop-only has the right number of columns (and they have data) it's fixed
