### ISSUE TITLE
IPTT: filter on TVA report for monthly indicators shows incorrect end dates

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#938]
Originally reported by @jennyhavah:

> If you run a Monthly Target vs Actuals IPTT on TolaData Test on QA (https://tola-activity-qa.mercycorps.org/indicators/iptt_report/442/targetperiods/?targetperiods=7&timeframe=1) and Production (https://tola-activity.mercycorps.org/indicators/iptt_report/442/targetperiods/?targetperiods=7&numrecentperiods=&timeframe=1), Production shows the start month as May 2017 and the end month as  November 2022. But QA shows this

![image](https://user-images.githubusercontent.com/169060/49689507-01358f00-fad7-11e8-9d83-ddccf247a110.png)

**Comment by camgnostic** [comment]
Confirmed: End period is not showing any value as "selected" on QA.  Start period dropdown is showing selected as expected.

**Comment by jennyhavah** [comment]
End period is showing up correctly for all target frequencies.
