### ISSUE TITLE
LoP target field: Don't display extra zeroes

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#940]
Right now, the LoP field is displaying .00 like so:

![image](https://user-images.githubusercontent.com/33670923/49690540-bec87e00-fae7-11e8-9bbc-d6b21ab8916b.png)

Ideally, we handle this the same way we do the Actual Value field in the Result form. There, if you type 92.50, it immediately rounds to 92.5 before you even submit. If you type 92.00, it rounds to 92. And if you just type 92, it displays 92, not 92.00.

**Comment by camgnostic** [comment]
Handled here: https://github.com/mercycorps/TolaActivity/pull/958

**Comment by jennyhavah** [comment]
Validated. No longer seeing extra zeroes. LoP field is automatically rounding to two decimal places.
