### ISSUE TITLE
Recent progress IPTT: Capitalize the names of time periods

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#946]
Time periods are no longer capitalized.

Here's how it looks on QA:
![image](https://user-images.githubusercontent.com/33670923/49705678-ff51f580-fbd4-11e8-8c72-d781c89e78ee.png)

vs. Production:
![image](https://user-images.githubusercontent.com/33670923/49705687-0aa52100-fbd5-11e8-86c9-f52e9ed21abb.png)

@axoplasm I remember you asking me all of the places where we have the names of periods in a menu -- must be connected to whatever you were working on at that time.

**Comment by axoplasm** [comment]
hotfixed in 41c0ccf

![image](https://user-images.githubusercontent.com/169060/49754650-85b91680-fc6b-11e8-9799-4f6bf8c8c706.png)

**Comment by jennyhavah** [comment]
Validated. I see this:
![image](https://user-images.githubusercontent.com/33670923/49754892-2d364900-fc6c-11e8-8919-550ce88d6635.png)

[British accent] Capital!
