### ISSUE TITLE
Home page: Make charts interactive, with the links taking you to a filtered program page

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#948]
Right now our home page charts are purely informational, like so:

![image](https://user-images.githubusercontent.com/33670923/49754167-3aeacf00-fc6a-11e8-90ca-e44246395e1f.png)

We would like to make them fully interactive in the same way that our program page charts are, taking you to filtered lists of indicators. In this case, the home page chart links would take you to a filtered view on the appropriate program page.

In addition to displaying the links and hooking them up to the right queries, there is highlighting behavior we need to mimic.

# Acceptance criteria

## Queries
All of the following chart links take you to a filtered program page and display the expected results.
- [x] 1. **Indicators on track:** % are >15% above target
- [x] 2. **Indicators on track:** % are on track
- [x] 3. **Indicators on track:** % are >15% below target
- [x] 4. **Indicators with targets:** Add missing targets
- [x] 5. **Indicators with results:** Add missing results
- [x] 6. **Results with evidence:** Add missing evidence

## UI details
- [x] 1. **Indicators on track:** 
![image](https://user-images.githubusercontent.com/33670923/49754661-8ce02480-fc6b-11e8-91b3-5985f0f81084.png)
     - [x] 1.1. onHover yellow background highlighting of the three clickable metrics work.
     - [x] 1.2. onClick yellow outline highlighting behavior around the entire block works.
- [x] 2. **Other three charts:** 
![image](https://user-images.githubusercontent.com/33670923/49754681-98cbe680-fc6b-11e8-9b83-a2aebf908883.png)
     - [x] 2.1. onHover yellow highlighting of the entire block works.
     - [x] 2.2. onClick yellow outline highlighting of the entire block works.

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
* The following Filters bring user to the correct filtered program page with related filter clicked:
     - [x] Indicators on track: % are >15% above target
     - [x] Indicators on track: % are on track
     - [x] Indicators on track: % are >15% below target
     - [x] Indicators with targets: Add missing targets
     - [x] Indicators with results: Add missing results
     - [x] Results with evidence: Add missing evidence

**Comment by jennyhavah** [comment]
The following issue applies to all three gauges to the right of "Indicators on track"

Each of the "Add missing ____" links are unresponsive. You can click on the _gauge_ to go to the filtered program page, but not the call to action link itself.

![image](https://user-images.githubusercontent.com/33670923/52766052-ccfcb400-2fda-11e9-8cee-59e345a06481.png)

For comparison's sake, go to the program page and click on those links -- they respond as expected there, activating the filters.

**Comment by jennyhavah** [comment]
One more detail related to the "Add missing targets" links on all three charts where they appear: Please add a space between the warning icon and the first letter of the string -- can use the Program page as a reference.

Here's how it looks now -- no space

![image](https://user-images.githubusercontent.com/33670923/52809800-f43c9b00-3045-11e9-9155-bdb7269f8074.png)

As opposed to this on the program page, with space:

![image](https://user-images.githubusercontent.com/33670923/52809838-0ddde280-3046-11e9-99bf-8dda86afbd01.png)

**Comment by RickieT** [comment]
**QA Verified**
* Add missing _ now has more spacing between the icon and words
* Tested all 3 LINKS and they filter, and the highlights on the gauges between program/home page also remain functional

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.

**Comment by sanjuroj** [comment]
Fixed in Hucklepatch
