### ISSUE TITLE
Indicator setup > Targets tab: Target value fields accept negative numbers

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#950]
**NOTE:** We need to run a query to find out if any program teams have entered negative values to date. If yes, we'll need to work with them to manually change their targets and use the direction of change field instead.

I am not sure how long-standing of an issue this is. I believe we used to prohibit this behavior, but am not 100% certain.

# Issue
In the target value field of the indicator setup form, the form validation does not prevent you from saving negative values. It will highlight the box in red and say "Please enter a target value. Your target value can be zero. But then it will go ahead and save the negative value.

This should not be permitted, as we want teams to use the direction of change field to indicate decreasing values.

The desired validation behavior and messaging is the one we're currently using in the Result form. If you enter a negative sign, the field and field label are highlighted in red and you see the message: Please enter a number with no letters or symbols.
![image](https://user-images.githubusercontent.com/33670923/49757604-a97f5b00-fc71-11e8-91c3-5bf9b77b1971.png)

**Comment by jennyhavah** [comment]
Dec 10, 2018 Sanjuro reports: _I’m semi-pleased to say that the only targets less than 0 are the QA targets.  In addition, because the lop_target field was just made numeric, anything that wasn’t greater than 0 was changed to null.  So I think we are double covered here at the moment._

**Comment by jennyhavah** [comment]
Slack discussion here: https://mercycorps.slack.com/archives/C4SAGL55M/p1544471658228200

**Comment by esinn** [comment]
Not sure this is ideal or intended behavior, but when I create an indicator and complete the required fields on the targets tab, I can select save changes to create the indicator BEFORE I click on create targets. This allows the indicator to be saved without having values entered in the periodic targets fields. Again, not a huge deal but might be a work around where users can create indicators without entering in target values.

**Comment by jennyhavah** [comment]
@esinn Regarding the saving an indicator without completing all required fields -- this has always been the case, even prior to Winterhawks -- it saves the indicator immediately after that first create page, regardless of whatever else you do. I agree it's not ideal; I recall asking Mahmood about it, and learning that it would not be a trivial change to adjust the flow so that nothing is saved in the database until you finish all the targets, etc.

I agree it's not ideal behavior and would like to change it... But it's not a new issue, so shouldn't prevent this ticket from passing.

**Comment by jennyhavah** [comment]
@esinn It is also the case in the Result form that you can enter a negative sign.

My understanding is that, for technical reasons, it would be a lot of work to prohibit even typing a - sign. Same for + sign. I think that normally, numeric fields are _supposed_ to accept certain mathematical symbols. So to override that would be a lot of work. @camgnostic can you confirm this?

Going to move this ticket to Done since everything in the original ticket passes. (Doesn't mean we can't continue to improve the numeric field in the future... we can always file a new ticket.)
