### ISSUE TITLE
Enhance script that creates QA programs

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#953]
The create_qa_program script needs a few improvements

- [x] Stop creating negative lop_targets
- [x] Put in an option to add individual or lists of programs without adding the rest of the programs
- [x] Tighten the way programs are selected to be cleaned
- [x] Add a multi-country program (doesn't need the full set of 64 indicators)
- [x] Assign indicators to a level (cycle through levels rather than adding them randomly)

**Comment by jennyhavah** [comment]
1. Ran a LoP only Target vs Actuals IPTT on "I love indicators so much" and don't see any negative LoP values. 
2. Also verified that indicators have levels assigned.
3. Verified that the multi-country QA program appears in two countries (TolaLand and Tunisia)

@sanjuroj I don't know how to test checkbox items 2 and 3. If you can verify that these are okay, we can move it to Done.

**Comment by sanjuroj** [comment]
Yep, those are done.  I'll close and move the ticket over.
