### ISSUE TITLE
500 Error when adding an indicator from the DIG

### ISSUE THREAD

**Issue by esinn** [mercycorps/TolaActivity#960]
When trying to add a new indicator from the DIG (https://thedig.mercycorps.org/) I get the following errors across production, demo and QA. 

Production:
![image](https://user-images.githubusercontent.com/13574772/49769176-0b50bc80-fc94-11e8-80c2-6d9551c6df0a.png)

Demo:
![image](https://user-images.githubusercontent.com/13574772/49769190-17d51500-fc94-11e8-89da-1c136eeeb55c.png)

QA: 
![image](https://user-images.githubusercontent.com/13574772/49769210-24f20400-fc94-11e8-9335-799829245f53.png)

**Comment by KennyMonster** [comment]
As a second part, update the code to not crash if the DIG server is not reachable through requests.

See view_indicators.py line 180.  `import_indicator()`

**Comment by sanjuroj** [comment]
Emily confirmed that this was no longer happening.
