### ISSUE TITLE
Results table: Improve differentiation of Results column from Evidence column

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#961]
**Affects:** Results table in two places
1. Program pages
2. Browse > Indicators

Reported by Emily: The columns and spacing don't line up. The date is listed under the results column but then there's no date column and the results look like it's part of the evidence column.
![image](https://user-images.githubusercontent.com/33670923/49770305-bf544680-fc98-11e8-8cd8-6c1431792a54.png)

Jenny's suggestion: What if we add a couple of vertical light gray lines around the Result column, like so:

![image](https://user-images.githubusercontent.com/33670923/49770654-5cfc4580-fc9a-11e8-9977-b2635cd0769d.png)

**Comment by axoplasm** [comment]
We also need to account for multiple results documents in a period. Here's where I'm at RN:

![image](https://user-images.githubusercontent.com/169060/49895885-93ef6a00-fe06-11e8-802c-d71fbde50a36.png)

**Comment by axoplasm** [comment]
will you be ITO tomorrow? We could try a few different things in realtime

**Comment by jennyhavah** [comment]
Yep, I'll be in tomorrow -- definitely after the æbleskivers, if not before.

**Comment by axoplasm** [comment]
Here's kind of where I'm at now:

![image](https://user-images.githubusercontent.com/169060/49955353-73cbb380-feb7-11e8-95dc-1dd6659b4ff8.png)

**Comment by jennyhavah** [comment]
We have an issue with indicators that are missing targets -- This may or may not have anything to do with the work recently done on this ticket. Depending, I can open up a new one. Tagging @axoplasm 

# Production example (from TolaData Test)
![image](https://user-images.githubusercontent.com/33670923/50523809-ec6d6b00-0a86-11e9-9d80-a07a3c861983.png)

# Demo example (from Jenny QA program)
![image](https://user-images.githubusercontent.com/33670923/50523828-fabb8700-0a86-11e9-81a7-09901ce72397.png)

**Comment by jennyhavah** [comment]
There's a results table style difference between Prod and Demo that I'd like to address. Again, let me know if this should be a new ticket. 

The following screenshots were taken of the same browser window, no adjustments to the window size in between takes. Do you see how the relative proportions of columns are different, so that the result values are now pretty far apart from the result dates, and the Evidence column doesn't have as much breathing room? (Doc titles tend to be long.) 

# Production example
![image](https://user-images.githubusercontent.com/33670923/50523882-57b73d00-0a87-11e9-8766-eb8ca6f0851b.png)

# Demo example
![image](https://user-images.githubusercontent.com/33670923/50523888-6140a500-0a87-11e9-976f-8d91c31d2140.png)

**Comment by jennyhavah** [comment]
One other detail that is also true in production, seems like a good time to fix it since you're already in there -- button wraps when the "results not assigned" message appears.

![image](https://user-images.githubusercontent.com/33670923/50524298-d01efd80-0a89-11e9-9882-e7b33669e76d.png)

**Comment by axoplasm** [comment]
Last 3 commits should fix these issues. Here's the (very…weird…) indicator I'm using to test all three.

![image](https://user-images.githubusercontent.com/169060/50527621-4ded0400-0a9e-11e9-8138-fda64f5f098a.png)

**Comment by jennyhavah** [comment]
All fixes looking good!
