### ISSUE TITLE
Gracefully handle external network call failures

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#964]
When Tola makes `requests` calls to external services like the DIG server during DIG indicator creation, or when creating a new project, it's possible these external API calls can fail. Right now the app just throws an exception.

Handle this failure case in such a way the end user is notified, and the app does not crash.

**Comment by KennyMonster** [comment]
The existing code that makes external calls doesn’t seem to assume failure at all, and in the case of things like AJAX calls, doesn’t have an existing channel in place for reporting server side errors. I’m wondering if we should evaluate where reporting may be most needed as to not spend a bunch of time on reporting that is of little to no value to end users

**Comment by KennyMonster** [comment]
All of the places in the codebase where `requests` are used:

```
            configurabledashboard  
                views.py  
                    
                    Called once in dead code - IGNORE
                    
            customdashboard  
                views.py  
                    
                    Called 2 times
                    
                    SurveyPublicDashboard
                      "http://tola-tables.mercycorps.org/api/silo/430/data/"
                      
                    SurveyTalkPublicDashboard
                      "http://tables.toladata.io/api/silo/9/data/"
                      
                    Pretty sure these are dead code paths - IGNORE
                    
            indicators/views  
                views_indicators.py  
                    
                    import_indicator()  # DIG indicator import function
                      pulls URL from ExternalService DB entry
                      Called by
                        indicator_create()  # when creating DIG indicator
                        service_json()  # populates dropdown box on indicator create
                        
                	  I already fixed this code path to log on error
                	  
                	getTableCount()  # get number of rows in tola table
                	  CollectedDataCreate()
                	  CollectedDataUpdate()
                	  collecteddata_import()  # import collected data from tola tables
                    
            scripts  
                get_github_project_issues.py  
                    
                    This is a dev script - devs problem
                    
            tables  
                views.py  
                    
                    import_table() # import collected data from Tola Tables
                    
                      pulls url from: ExternalService.objects.get(name="TolaTables")
                        this entry doesn't exist in my DB dump
                        this makes me think it's dead code!
                        
                        IGNORE
                    
            tola  
                util.py  
                    
                    get_table()
                      # Get table data from a Silo.  First get the Data url from the silo details
                      Called by:
                        customdashboard/views PublicDashboard
                        
                        views_indicators collecteddata_import()  # tola table data ??
                    
            workflow  
                views.py  
                    
                    import_service()  # yet another DIG indicator import function
                      called only by service_json() 
                        this is in turn called by some JS which my or may not be dead
                    
            workflow/management/commands  
                fetch_gait_dates.py  
                    
                    dev's problem - IGNORE
```

**Comment by KennyMonster** [comment]
I have deleted `workflow.views.import_service()/service_json()` as this was just copy n pasted from the indicators version (which is already reporting errors in logging).

Out of the list above, the only things that need error handling are:

`tola.util.get_table()`
`tola.utils.get_GAIT_data()`
`indicators.views.views_indicators.getTableCount()`

Two of these relate to TolaTables import which is know nothing about and could use some input on wrt how to handle error reporting.

The third is for pulling info from GAIT during program creation. For this, should Program creation continue without populating the fields normally populated by GAIT, or stop creation and give an error to the admin?

**Comment by KennyMonster** [comment]
Since TolaTable importing from the collect data form is going away in Huckleberry, no work will be done for those.

That just leaves handling network errors during program creation which will still allow Program creation with error reporting if possible.

**Comment by RickieT** [comment]
** Validation Complete ** 
* So I just played around with creating DIG indicators and did not see any issues in console, or site behavior.

**Comment by RickieT** [comment]
Closing as fixed and deployed.
