### ISSUE TITLE
Global: Program filter menu should cascade, but should not be required, and auto-suggest

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#97]
Throughout TolaActivity, we have program and indicator filters side by side. In many cases, selecting a program does not cascade and you continue to see all of your indicators for all of your programs.

**Also:** In the Program Report, you are able to select a country and a program that don't relate to each other. These should cascade as well -- anywhere this type of widget appears in the app.

I have not done an audit to find all of the places where these menus show up -- reports, forms, etc. Hoping that's something you can quickly assemble with some sort of query. _Can you please add a comment with a list of all the places where you've made the change, that I should test?_

DESIRED BEHAVIOR
1. If I select a program, I only see indicators associated with that program.
2. I am _not_ required to select a program first before choosing an indicator. I can still go directly to the Indicators menu and choose from the master list.

BONUS
Add auto-suggest capability to Programs and Indicators selection widgets throughout TolaActivity. (If it looks strange to have that type of widget side by side with the type we have now, I'm fine doing the auto-suggest variety for all filters, even though it's less useful where there is a short list.)

**Comment by kurtwall** [comment]
I tested this manually, but it's a _great_ candidate for automation.
- Selected arbitrary combinations of program, indicator, and indicator type filters to confirm that results were limited to the selected combination of filters. 
- Selecting a program and then selecting a indicator with multiple matches only populates the table with a single indicator rather than the expected multiple matches -- I thought the filtering was a search functionality, but the UI allows indicators to have the same name even though they might otherwise be different indicators entirely. What's unique is the number, not the name.

**Comment by jennyhavah** [comment]
Can we make the three menus fit on a single row, without needing to open the browser window to nearly the full width of a laptop screen?

**Comment by jennyhavah** [comment]
When you pick an indicator from the "filter by indicator" menu, can we automatically open the program in which the indicator is contained, so that you don't need a second click to see it?

**Comment by jennyhavah** [comment]
"Filter by indicator type" is getting truncated to "Filter by indic..."
![image](https://user-images.githubusercontent.com/33670923/36434257-89b1b5f4-1656-11e8-89b8-94273d15bc5f.png)

Could we keep the menu labels as they are on production? Programs, Indicators, Types? Seems like this would be less likely to get truncated in a confusing way.

**Comment by jennyhavah** [comment]
![image](https://user-images.githubusercontent.com/33670923/36447796-62628876-167d-11e8-8435-fbb1ef2f3db6.png)

If there are no indicators in a program, we hide the Indicators menu, which makes sense. But we still show the Types menu, which seems odd. Is this easy to fix?

**Comment by mahmoodkhan** [comment]
The fix for this is a little involved. Currently, it is setup to show a filtering dropdown only if it has data. The indicator dropdown is connected to the program dropdown so it gets updated but the type dropdown is independent and always has data.

**Comment by jennyhavah** [comment]
Okay, let's leave it alone for now and address as part of Winterhawks.
