### ISSUE TITLE
Update files to reflect move away from MyISAM

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#971]
There are two places where MyISAM is still present.  
- [x] sample-settings.secret.yml
- [x] settings.travis.yml

**Comment by KennyMonster** [comment]
My latest change only affects Travis CI. As such, there isn't much to test other than seeing if Travis blows up (it didn't when I tried).

**Comment by RickieT** [comment]
**QA:**
See developer comments, moving this through
