### ISSUE TITLE
LOP Indicators with no lop_target break filtering for needs-targets

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#976]
found by @KennyMonster  - per the following screenshot: 
<img width="1113" alt="screen shot 2018-12-13 at 4 00 34 pm" src="https://user-images.githubusercontent.com/7941355/49970228-46e7c280-fef0-11e8-9c81-d9fc7c060338.png">
8 indicators according to graph and label, no indicators showing

**Comment by camgnostic** [comment]
Missing indicators all LOP frequency indicators with no lop_target.

Definitely an edge case (as it is difficult to impossible outside of the QA creation script to create an indicator and set the frequency without setting a lop_target) but the fix involves a change to how the template determines if the data-defined-targets attribute should be set.

**Comment by esinn** [comment]
I'm not totally sure the details of this ticket. Is it that it now prohibits a user to save an indicator without entering an LOP target value? But when you click on the missing targets link it doesn't take you to those? Is that right?

**Comment by sanjuroj** [comment]
@esinn I think the best you can do to test this is to create a few indicators, do nothing else with them (i.e. don't create periodic targets), and see if the missing targets filter works properly.  Another test that one of the devs will need to do is to create LoP targets and then go through the backend and delete the target itself, to see if that breaks the filter too.  That would be the simulation of an older indicator that has a LoP target type but managed to have to no value filled in for the target itself.

**Comment by esinn** [comment]
Per Sanjuro's testing instructions, filter is working properly when creating a new indicator but not saving it with any LOP values or perdiodic frequency selected.
