### ISSUE TITLE
Indicator setup/edit forms: refactor and refresh

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#978]
- [x] Refactor code to reduce dependence on Bootstrap convenience selectors like `mb-3`
- [x] Simplify form code to make it more conformant to Bootstrap standard form layout
- [x] Refresh design to align to forms elsewhere, and with current form best-practices
    - [x] Vertical tabs
    - [x] vertically-stacked labels and form elements

**Comment by axoplasm** [comment]
some screenshots from my local:

#### Modal:
![image](https://user-images.githubusercontent.com/169060/50248365-a2ea9500-038f-11e9-8271-61e88b4a68db.png)

#### Page:
![image](https://user-images.githubusercontent.com/169060/50248417-d3323380-038f-11e9-8087-9fa0f26cbbdf.png)

#### Targets table:
![image](https://user-images.githubusercontent.com/169060/50248437-e8a75d80-038f-11e9-8dfb-7d7d717b4c22.png)

**Comment by axoplasm** [comment]
Targets tab:
![targets-tab](https://user-images.githubusercontent.com/169060/50405161-88d0fe00-0765-11e9-895e-38a26e16ed20.png)

**Comment by jennyhavah** [comment]
I like the vertical tabs! It'll be an improvement in any format we use -- full page, modal, or in-line.

Some feedback:

1. What do you think about changing the background of the entire form area to the lighter shade of gray that you're currently using for the selected tab? It would do a couple of things -- highlight the primary action area a little more, and provide some horizontal differentiation between the title/indicator area and the form, particularly when anything but the top tab is selected. Like so:
![image](https://user-images.githubusercontent.com/33670923/50405326-d484a700-0767-11e9-86c5-b8c5b1c9cee8.png)

2. Regarding "Delete this ____" treatment: Because this is a destructive and irreversible action, I liked the previous no-background treatment better. It was less button-like ("click me! boop!") and less eye-catching.

3. I wish there were some subtle text style differentiation between the form labels and the field entries; what I've been doing in my mockups is make the form labels a bit smaller than the text inside the fields. Other options would be to make the form labels bold or all caps. In the particular form you screenshotted, it's not a problem. But in other forms that will use the same styles, it becomes a bit harder to differentiate label from form, like here for example:
![image](https://user-images.githubusercontent.com/33670923/50405400-e0bd3400-0768-11e9-896b-87e8cb61be56.png)

**Comment by jennyhavah** [comment]
Oh! one other small detail... Is it possible to have the event name boxes arranged in such a way that there isn't such a large gap in between? (Low priority, only if it's easy.)

![image](https://user-images.githubusercontent.com/33670923/50405657-f6ccf380-076c-11e9-8770-77d2c56c6db4.png)

**Comment by hannalcamp** [comment]
@sanjuroj @jennyhavah Should I just be checking that there's no failures/errors with the new vertical setup?

**Comment by sanjuroj** [comment]
@hannalcamp Yeah, that's about right, along with testing some of the tweaks that Jenny mentioned above.  I'm going to loop @axoplasm in, since he did the work.

**Comment by hannalcamp** [comment]
seeing this, testing on Chrome: 
![screen shot 2018-12-27 at 4 52 59 pm](https://user-images.githubusercontent.com/38020496/50497756-ed0af080-09f7-11e9-9cfa-d776af64c29b.png)

**Comment by axoplasm** [comment]
This is actually a global issue with `select2` lists. My “fix” introduces a global visual regression. These list elements will now wrap:

![image](https://user-images.githubusercontent.com/169060/50498425-753bc680-09f5-11e9-86e6-ec42657110ae.png)

**Comment by jennyhavah** [comment]
I'm not able to see the changes -- possibly because Hanna has a local instance and I am looking at Demo. 

Can we push these updates to Demo, @sanjuroj?

**Comment by jennyhavah** [comment]
Looks like there's an issue with percentage signs again:
![image](https://user-images.githubusercontent.com/33670923/50524145-ee382e00-0a88-11e9-923c-f6366cd19e59.png)

Here's how it looks in Production
![image](https://user-images.githubusercontent.com/33670923/50524187-43743f80-0a89-11e9-8d21-889b6957b782.png)

![image](https://user-images.githubusercontent.com/33670923/50524168-20e22680-0a89-11e9-940b-027bc3ac29fa.png)

**Comment by jennyhavah** [comment]
@hannalcamp @axoplasm We should also keep an eye on this variation of the form, that you get when you click "Start by selecting a target frequency" here:
![image](https://user-images.githubusercontent.com/33670923/50525267-43773e00-0a8f-11e9-8410-6975aef9036f.png)

So far, not finding any new issues, but would appreciate Hanna's help trying out various target frequencies.

![image](https://user-images.githubusercontent.com/33670923/50525293-6efa2880-0a8f-11e9-87b8-860399f7010a.png)

**Comment by jennyhavah** [comment]
The target period names are no longer vertically aligned with the Sum of targets and LoP rows.

# Production
![image](https://user-images.githubusercontent.com/33670923/50525361-d7e1a080-0a8f-11e9-9abe-ee46396d13f0.png)

# Demo
![image](https://user-images.githubusercontent.com/33670923/50525338-acf74c80-0a8f-11e9-80ae-8cfbe96ff267.png)

**Comment by jennyhavah** [comment]
I also wonder whether -- given the information density of the Targets tab in general, we should consider making the modal window a bit wider, to adjust for all the space taken up by the vertical tabs? It feels a bit crowded to me now.

**Comment by hannalcamp** [comment]
Seeing some weird behavior with the cumulative vs non-cumulative options in the target periods:

![screen shot 2018-12-28 at 12 04 56 pm](https://user-images.githubusercontent.com/38020496/50525507-09ab3500-0a99-11e9-978b-fef9a6252d07.png)

They still work but there's no radio button or anything to show which has been selected?

**Comment by axoplasm** [comment]
@jennyhavah the modal window size might be globally determined

**Comment by axoplasm** [comment]
Also, fixed both minor visual bugs (vertical alignment and % sign in the form element):

![image](https://user-images.githubusercontent.com/169060/50528777-277e9700-0aa5-11e9-9b5c-f0f5872cc7ba.png)

**Comment by axoplasm** [comment]
@hannalcamp I can’t reproduce the missing radio buttons for cumulative/non-cumulative. Can you give me some steps to reproduce?

**Comment by hannalcamp** [comment]
@axoplasm I'm seeing it in every indicator for every program - no matter how I get to the indicator details form. I'm on Chrome ver 71.0.3578.98

**Comment by axoplasm** [comment]
I have the same. Are you using a Mac?

**Comment by axoplasm** [comment]
we're tracking the weird behavior for adding/deleting targets on #1009

**Comment by jennyhavah** [comment]
@axoplasm Regarding the target table, The left side is now vertically aligned, but the right side isn't. I am also wondering if we can get the Demo version closer to production in terms of the visual hierarchy of the target period area, and some other visual details. See labeled mockup below.

![image](https://user-images.githubusercontent.com/33670923/50619485-508c9680-0eae-11e9-8da7-cffae5750b43.png)

**Comment by hannalcamp** [comment]
Only thing I'm noticing is that the "Indicators with results" and "Results with evidence" metrics have been updating automatically without needing to refresh the page, but the "Indicators with targets" metric does not. Not sure if this is anything to be concerned about.

**Comment by axoplasm** [comment]
visual fixes on my machine:

![image](https://user-images.githubusercontent.com/169060/50710685-8c476d80-1020-11e9-91da-fc10600c2a22.png)
![image](https://user-images.githubusercontent.com/169060/50710702-936e7b80-1020-11e9-91bf-1f3186a1d160.png)
![image](https://user-images.githubusercontent.com/169060/50710712-9c5f4d00-1020-11e9-9792-1feb53ffdef4.png)

When testing, please be sure to toggle the Cumulative/nonCumulative radio, and Number/Percentage radio.

Commit 9d78df7 introduces a new, slightly lighter "secondary" gray color which may produce global visual regressions.

**Comment by axoplasm** [comment]
@hannalcamp those are all React components. @KennyMonster might want to know about this. Can you make a comment on #965?

**Comment by sanjuroj** [comment]
@RickieT Can you make sure these updates didn't break anything?  Even if Jenny wants two tweak the look a bit more, we'll need to do it in a follow-up release.

**Comment by jennyhavah** [comment]
Most recent visual tweaks are looking good!
