### ISSUE TITLE
On track chart: When program hasn't started but targets are set up, show a different message

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#988]
## Affects
On track chart in two places: Home page and program page

## Issue
This is not a bug, but rather a "friendliness" issue. When a program starts in the future, the behavior we want to encourage is 100% of targets set up. We don't expect any results or evidence until the program starts.

Right now, even if you complete 100% of targets, you see the sadfaced "Unavailable until results are reported" message, like this:
![image](https://user-images.githubusercontent.com/33670923/50245773-4172f800-0388-11e9-86b6-464290d0c0fc.png)

It would be nicer to show the "Unavailable until your first target period ends" message instead:
![image](https://user-images.githubusercontent.com/33670923/50245851-72532d00-0388-11e9-8ce3-1da472264b5a.png)

See #910 for the related code -- we currently only display that message if results are also reported.

**Comment by jennyhavah** [comment]
Just noting for the record, that the approach we ended up taking is to consolidate the messaging so that, whether the program has started or not, and whether you have targets set up or not, you see an empty gauge for "on track" with the message, "Unavailable until the first target period ends with results reported." Like so -- with 100% of targets complete but program hasn't started yet:

![image](https://user-images.githubusercontent.com/33670923/52660889-8b261d80-2eb5-11e9-82d3-233c8abf6c44.png)

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 2 23 33 pm](https://user-images.githubusercontent.com/23220180/52748278-f7c71800-2f9a-11e9-8939-8daf7288a5e3.png)
