### ISSUE TITLE
More QA program script improvements

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#989]
## Bugfixes
- [ ] LoP indicator are show up with 2 targets, rather than just the LOP target.

## All QA indicators - decreasing direction of change combined with increasing targets
We need to introduce some validation to prevent this from being set up in the first place. But for now, we can at least make sure our test programs aren't throwing off performance metrics in this particular way.
- [ ] Decreasing direction of change combined with increasing intermediate targets

## QA Program -- No Targets Here
For LoP only indicators in this program, you see a results table even though there is no LoP value entered. It turns out that even though there's no LoP _value_, the target frequency is set to LoP only, which may be why you see the table. We need to make sure the target frequency is not set for LoP only indicators in this program.

## All QA programs - no cumulative LoP indicators
Make sure that for LoP-only indicators, there are no cumulative indicators such as:
- [ ] Number (#) | Increase (+) | cumulative
- [ ] Percentage (%) | Increase (+) | cumulative
- [ ] Number (#) | Decrease (-) | cumulative
- [ ] Percentage (%) | Decrease (-) | cumulative

## Tweaks to Small Indicator Set program
- [ ] 1. Make sure one of the quarterly indicators has targets completed.
- [ ] 2. Add an event-based indicator.

## Future program
Auto-generate a program that:
- [ ] 1. Has a start date in the future
- [ ] 2. Has at least one indicator with time-aware target frequencies set up, to simulate the scenario where no target periods have yet been completed, because the program hasn't started.
- [ ] 3. Does not have any results or evidence.

## Vary the completeness of indicators for all named QA programs
Right now, all the named QA programs have a 100% success rate for the targets set up, results reported, and evidence attached gauges. Instead, let's do the following
- [ ] 1. Add 5 indicators without any targets: Instead of removing targets from some of the desirable target frequency combinations, it would be better to create separate indicators with names like "No targets indicator 1" etc. 
- [ ] 2. Do not report results for roughly 15% of indicators
- [ ] 3. Do not attach evidence to roughly 15% of results

## Add more than one result to some target periods
In order to check the behaviors of the various calculation scenarios, and the styling of a fairly complex table, it's useful to have more than one result for at least one target period. How about this... For all indicators that have reported results, we do the following
- [ ] 1. Time-aware frequencies: The first period always has two reported results.
     1.1. For purposes of realism, we could make them not wildly different from each other or wildly off target. For example, Result number 2 is X number or % greater or lesser than result number 1.
- [ ] 2. Midline/endline: A handful of these (ideally not all) have two reported results for Midline and Endline. (Really an edge case, but it could happen, like if you had multiple surveys from multiple geographic regions.)
- [ ] 3. LoP only: There are at least two reported results.
- [ ] 4. Event: First event always has multiple reported results. 

## Update string used for GAIT ID to be something other than the program name
I reported an issue-not-really-an-issue that I suspect will throw other QA testers once we start improving the indicator plan. Right now, on the Indicator plan, it looks as though we're accidentally repeating the program name twice in the title. (See https://github.com/mercycorps/TolaActivity/issues/980#issuecomment-450394639 for the problem.)

Instead of using the program string for the GAIT ID, it would be better to generate some other type of fake ID. I know we have to be careful not to use numbers that could conflict with real IDs. Maybe a combination of numbers and letters like 1A4D?

**Comment by sanjuroj** [comment]
@jennyhavah What do you think about using the shorter list of indicators for all of the named QA Programs (e.g. QA Program - Jenny) and use the comprehensive list for the other ones?  I feel like the shorter list may be more tractable for testers.  We could bulk up the number of indicators a bit to get a decent spectrum.

**Comment by jennyhavah** [comment]
@sanjuroj I like having the current combination and quantity of indicators to test edge cases, and they load quickly. I see it as the happy medium in between "I Love Indicators So Much" and "just a handful".

If others are finding the current list too much, could we do a "Named program - SM" and Named program - LG" and people can pick the version they want?

**Comment by sanjuroj** [comment]
I haven't heard any complaints, we can keep them the way they are.  If I do, we can implement the person-specific list length, as you suggest.

**Comment by sanjuroj** [comment]
@jennyhavah I think I've completed most of these.  I didn't quite do what was requested for the "
Add more than one result to some target periods" section.  Instead of targeting very specific periods or indicator types for additional results, I just added a setting to cyclically skip or double up on results and cyclically skip evidence.  This can be tweaked for how frequently each of those types of events is.  If this and/or a tweaked version of this doesn't work for you, I can implement what you described.  

@RickieT I don't think you need to QA this ticket, just because the whole thing is for the purpose of QA.  By all means submit requests for changes and/or additions that would help in your QA process though.

**Comment by jennyhavah** [comment]
Sounds good, @sanjuroj!
