### ISSUE TITLE
Need clean environment for testing

### ISSUE THREAD

**Issue by kurtwall** [mercycorps/TolaActivity#99]
Does MC have a way for us to spin up a clean host on which to run these tests? Say, a docker image or a VM? Dev machines like the ones we use are notoriously dirty from the standpoint of testing -- the results aren't reliable or necessarily reproducible -- so another best practice is starting a test suite with clean systems in a known state. I can't say right now that I am confident the tests will work properly  just checking out the repo and following the README. This will also be important if or when we set up a CI system.

I would be willing to look into this if we agree it it worth pursuing.

**Comment by mahmoodkhan** [comment]
Unfortunately we do not have Docker setup, but you could setup a vagrant on your system to spin up fresh instances of the app or we can restore the demo database onto dev every day or so or as often as you need to.

**Comment by kurtwall** [comment]
Docker is a possibility. It's not the data that's the issue but rather that the iMac is just not a clean machine -- it's a dev box with all manner of stuff installed. so tests run against it are questionable.
