### ISSUE TITLE
Life of Program target frequency: Unexpected display when multiple results are added

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#990]
## Affects
Indicators with a target frequency of LoP only

## Production (looks as expected)
![image](https://user-images.githubusercontent.com/33670923/50247687-7897d800-038d-11e9-9a1c-7e72f02a693b.png)

## Demo 
Note how the "Life of Program (LOP) only period name is displayed for each result.
![image](https://user-images.githubusercontent.com/33670923/50247737-99602d80-038d-11e9-9f73-a6ce1c514d75.png)

**Comment by axoplasm** [comment]
I'm unable to replicate this on either Demo or my local machine:

#### Demo:
![image](https://user-images.githubusercontent.com/169060/50362954-a9f3dd80-051e-11e9-8f77-2381db1ceb40.png)

#### My local machine:
![image](https://user-images.githubusercontent.com/169060/50362979-bd9f4400-051e-11e9-941e-21752ddf093f.png)

Can you grant me access to TolaLand so I can view the QA program?

**Comment by jennyhavah** [comment]
@axoplasm Check out the first two indicators in QA Program -- Jenny. I've been adding more results to the very first one, and it is adding the new records as expected, but I still see that extra LoP row underneath. 

Some notable things in the second indicator (which I haven't added more records to, today:
1. The original two records were entered on the same date. (This is permitted.)
2. There are two different targets!

![image](https://user-images.githubusercontent.com/33670923/50363501-c133ca80-0520-11e9-81e3-11d615ef6cdd.png)

**Comment by jennyhavah** [comment]
It gets weirder. Paul just noticed that one of the LoP items is described as cumulative and the other as non-cumulative. We aren't actually supposed to be offering cumulative LoP-only indicators -- only non-cumulative.

Check this out:

![image](https://user-images.githubusercontent.com/33670923/50363710-b168b600-0521-11e9-9238-576004707813.png)

**Comment by sanjuroj** [comment]
I think that's an artifact of the QA script.  I just need to add a check to handle this appropriately.  It's just looping through all of the possibilities right now.

**Comment by jennyhavah** [comment]
What's causing the multiple LoP targets, @sanjuroj ?

**Comment by sanjuroj** [comment]
The script just automatically creates two targets for every combination of the four indicator parameters that it's looping through (with the exception of midline/endline).  It's a pretty easy fix.  If the only place you're seeing this is the QA script, then I don't think it's worth chasing this particular problem. Maybe just add a fix for this to the QA script update ticket you created a day or two ago.

**Comment by sanjuroj** [comment]
This is a bug in the QA program creation script and will be dealt with as part of #989.
