### ISSUE TITLE
Queries calculating indicators with targets: Intermediate targets with a value of zero should be considered "defined"

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#991]
This came up as a result of some issues reported by Myanmar. 

## Affects
- [ ] 1. Country level query: % of programs have all targets defined
- [ ] 2. Program level query: Indicators with targets
     - [ ] 2.1. % no targets
     - [ ] 2.2. % have targets

# Acceptance criteria
While LoP targets must have a value greater than zero to be accepted as complete, this is not the case for intermediate targets. An intermediate target should be accepted as "defined" when the value is zero.

## Context
Some examples of why zero might be entered:
1. No work related to that indicator is planned for a given target period, and therefore the expected result is zero.
2. A program is not ready to set target values for the final periods of a long program, and is entering zero as a placeholder.

Slack discussion here: https://mercycorps.slack.com/archives/C4SAGL55M/p1545257289050700?thread_ts=1545256048.048100&cid=C4SAGL55M

**Comment by camgnostic** [comment]
This bug not actually a bug (behavior that was originally assessed to be due to not counting "0" as a defined target is _actually_ caused by mismatched program reporting dates and periodic target date cover range.  0 is counted as a defined target (and this behavior is tested)

**Comment by jennyhavah** [comment]
Since there is no issue with intermediate targets with a value of zero being treated as "defined", this issue is invalid. Tagging as "notabug" and closing.
