### ISSUE TITLE
TolaUser's country assignment can't be changed in Tola

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#992]
It is not possible to change a TolaUser's "Country" field through the admin interface.  If you go to the admin interface on the server, you'll notice that while field values can be modified, most field labels, with the exception of language and user are greyed out.  When the country value is updated and saved, it looks like it's successful, but navigating back to the same TolaUser reveals that the new value was not saved.  This behavior differs from a local installation, where the country can be changed.

**Comment by jennyhavah** [comment]
@sanjuroj I'm not seeing this on Demo or Production. I've been able to update my own countries in Admin > Tola Users with no problems.

**Comment by sanjuroj** [comment]
@jennyhavah Did you try the "Country" field rather than the "Accessible Countries" field?

**Comment by sanjuroj** [comment]
I updated the ticket a bit to make it more clear.

**Comment by jennyhavah** [comment]
Ah no, I was focused on Accessible Countries. Thanks for clarifying. I wonder how much of this will butt up against Partner Access work that will refine how we're handling country assignments...

**Comment by sanjuroj** [comment]
It might do.  How and if partners are assigned to countries and whether their assigned country will affect what programs they have access to is something I'm not clear about.

**Comment by sanjuroj** [comment]
After some research, we discovered that each page load is checking the login credentials against the LDAP server and that each one of these checks also updates the country assignment of the user.  This is why the country will always reflect what is in LDAP, regardless of what you save in Tola.  If this behavior needs to be changed, partner access would be the sensible place to do it.
