### ISSUE TITLE
Indicator list: Wording of list description in title varies from production

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#995]
We made some tweaks late in Mangosteen to the wording above the indicator list, but it looks like the React version has some older wording. I found two examples:

Indicators with results filter -- the one on the left is Production and correct.
![image](https://user-images.githubusercontent.com/33670923/50355280-0812c780-0503-11e9-9ac6-9d1cfaf4170d.png)

Results with evidence filter -- the one on the left is Production and correct.
![image](https://user-images.githubusercontent.com/33670923/50355372-50ca8080-0503-11e9-87bd-d5f45d729192.png)

Is there a way to do a comparison to look for anything else like this that might need to be updated?

**Comment by sanjuroj** [comment]
We could check the translation files.  Anything that is new in the JS should be new or fuzzy in the .po files.  The strings that Jenny gave examples of are in the .po files as new/fuzzy, depending on how they're run.

**Comment by jennyhavah** [comment]
The two examples I found are fixed. @sanjuroj if you find anything fuzzy along the same lines, let's file a new GP ticket.
